---
layout: passport-doc
title: Tenant APIs
description: APIs for creating, retrieving, updating and deleting tenants
---

[NOTE.since]
====
Available Since Version 1.22.0
====

== Overview

A Passport Tenant is a named object that represents a discrete namespace for Users, Applications and Groups. A user is unique by email
address or username within a tenant.

Tenants may be useful to support a multi-tenant application where you wish to use a single instance of Passport but require the ability to
have duplicate users across the tenants
in your own application. In this scenario a user may exist multiple times with the same email address and different passwords across tenants.

Tenants may also be useful in a test or staging environment to allow multiple users to call APIs and create and modify users without
possibility of collision.

The following APIs are provided to manage Tenants.

* <<Create a Tenant>>
* <<Retrieve a Tenant>>
* <<Update a Tenant>>
* <<Delete a Tenant>>


== Create a Tenant


This API is used to create a new Tenant.

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Create a Tenant with a randomly generated Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/tenant#
--

link:authentication#api-key-authentication[icon:lock[role=red]] Create a Tenant with the provided unique Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/tenant/`\{tenantId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#tenantId# [type]#[UUID]# [optional]#Optional# [default]#defaults to secure random UUID#
|The Id to use for the new Tenant. If not specified a secure random UUID will be generated.
|===

include::docs/passport/apis/_tenant-request-body.adoc[]

=== Response

The response for this API contains the Tenant that was created.

include::docs/passport/apis/_standard-post-response-codes.adoc[]

:response_body_title: Response Body for a single Tenant
include::docs/passport/apis/_tenant-response-body.adoc[]

== Retrieve a Tenant

This API is used to retrieve a single Tenant by unique Id or all of the configured Tenants.

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Retrieve all of the Tenants
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/tenant#
--

link:authentication#api-key-authentication[icon:lock[role=red]] Retrieve a Tenant by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/tenant/`\{tenantId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#tenantId# [type]#[UUID]# [required]#Required#
|The unique Id of the Tenant to retrieve.
|===

=== Response

The response for this API contains either a single Tenant or all of the Tenants. When you call this API with an Id the response will
contain a single Tenant. When you call this API without an Id the response will contain all of the Tenants. Both response types are
defined below along with an example JSON response.

include::docs/passport/apis/_standard-get-response-codes.adoc[]

include::docs/passport/apis/_tenant-response-body.adoc[]

include::docs/passport/apis/_tenants-response-body.adoc[]

== Update a Tenant

This API is used to update an existing Tenant. You must specify the Id of the Tenant you are updating on the URI. You must specify
all of the properties of the Tenant when calling this API. This API does not merge the existing Tenant and your new data. It replaces
the existing Tenant with your new data.

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Update the Tenant with the given Id
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/tenant/`\{tenantId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#tenantId# [type]#[UUID]# [required]#Required#
|The Id of the Tenant to update.
|===

include::docs/passport/apis/_tenant-request-body.adoc[]

=== Response

The response for this API contains the Tenant that was updated.

include::docs/passport/apis/_standard-put-response-codes.adoc[]

:response_body_title: Response Body
include::docs/passport/apis/_tenant-response-body.adoc[]


== Delete a Tenant

This API is used to permanently delete a Tenant. Deleting a Tenant will delete all Users, Applications and Groups that belong to this
tenant. Proceed with caution.

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Delete a Tenant by Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/tenant/`\{tenantId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#tenantId# [type]#[UUID]# [required]#Required#
|The unique Id of the Tenant to delete.
|===

=== Response

This API does not return a JSON response body.

include::docs/passport/apis/_standard-delete-response-codes.adoc[]