select FIRST_NAME, LAST_NAME, EMAIL, USERNAME, EMAIL_VERIFIED, U.ID as ID,
SECRET_DATA ->> '$.value' as PASSWORD,
SECRET_DATA ->> '$.salt' as SALT,
CREDENTIAL_DATA ->> '$.hashIterations' as HASHITERATIONS,
CREDENTIAL_DATA ->> '$.algorithm' as ALGORITHM,
CREATED_TIMESTAMP, REALM_ID
from USER_ENTITY U, CREDENTIAL C
where U.ID = C.USER_ID AND U.REALM_ID = 'RealmID'
