== Stolen refresh token ==
Hacker->Store : GET /shopping-cart\n[Refresh token and bad JWT HttpOnly w/ domain: Store.Example.com]
Store->FusionAuth : POST /oauth2/token or POST /api/jwt/refresh\n(grant_type=refresh and refresh token)
FusionAuth->Store : (JWT)
Store->Hacker : (Shopping cart HTML)\n[New JWT HttpOnly w/ domain: Store.Example.com]
