@startuml
  !include ../../_config.plantuml

participant "User Agent" as u
participant "Firebase" as f

u -> f  : Request login page
f -> u  : Receive login page
u -> f  : Post credentials
f -> f : Verify credentials
f -> u  : Display results.

@enduml
