@startuml
  !include ../../_config.plantuml

participant "User Agent" as u
participant "Azure AD B2C" as c

u -> c  : Request login page
c -> u  : Receive login page
u -> c  : Post credentials
c -> c : Verify credentials
c -> u  : Display results.

@enduml
