@startuml
  !include ../../_config.plantuml

participant Browser
participant "Pied Piper Video Chat" as pp
participant FusionAuth as f
Browser -> pp : Registers
Browser -> pp : Submit tenant creation form
pp -> pp : Creates tenant object
pp -> f : Creates needed configuration
pp ->> f : Create optional configuration
pp -> Browser : Tenant configuration details
@enduml
