@startuml
  !include ../../_config.plantuml

participant "User Agent" as u
participant "New System" as ns

u -> ns  : Request login page
ns -> u  : Receive login page
u -> ns  : Post credentials
ns -> ns : Verify credentials
ns -> u  : Display results.

@enduml
