@startuml
  !include ../../_config.plantuml

participant Browser
participant "Pied Piper" as pp
participant FusionAuth
participant "Hooli" as h
Browser -> pp : View Home Page
pp -> pp : Check Session Existence
pp -> Browser : Redirect to FusionAuth Because There is No Valid Session
Browser -> FusionAuth : Request Login Page
FusionAuth -> FusionAuth : Check FA Session Existence
FusionAuth -> Browser : Send Login Page
Browser -> FusionAuth : Send Credentials
FusionAuth -> Browser : Redirects to Pied Piper
Browser -> pp : Requests Home Page
pp -> Browser : Sends Home Page
Browser -> h : Requests Home Page
h -> h : Check Session Existence
h -> Browser : Redirect to FusionAuth Because There is No Valid Session
Browser -> FusionAuth : Request Login Page
FusionAuth -> FusionAuth : Check FA Session Existence
FusionAuth -> Browser : Redirects to Home Page
Browser -> h : Requests Application Page
h -> Browser : Sends Application Page
@enduml
