@startuml
  !include ../../_config.plantuml

participant Browser
participant "Pied Piper" as pp
participant FusionAuth
participant "Hooli" as h
Browser -> pp : View Home Page
Browser -> pp : Click Logout
pp -> pp : Destroy Local Session
pp -> Browser : Redirect to FusionAuth
Browser -> FusionAuth : Request Logout
FusionAuth -> FusionAuth : Destroy FusionAuth Session
FusionAuth -> h : GET Request to Logout URL
h -> h : Destroy Local Session
FusionAuth -> Browser : Redirect to Pied Piper Configured Logout URL
Browser -> pp : Request Login URL
pp -> Browser : Redirect to Login URL
@enduml
