@startuml
  !include ../../_config.plantuml

"User" -up-> "Tenant"
"Application" -up-> "Tenant"
"Group" -up-> "Tenant"
"Role" -up-> "Application"
"User" -up-> "Group"
"Registration" -up-> "User"
"Registration" -up-> "Application"
"User" -up-> "Role"
"Entity" -up-> "Application"
@enduml
