@startuml
  !include ../../_config.plantuml

[*] --> Started
Started --> Modified
Modified --> Cancelled
Started --> Cancelled
Started --> Ended
Modified --> Ended
Modified -[dashed]-> Modified
@enduml