@startuml
  !include ../../_config.plantuml

participant "HR Admin" as h
participant "HR System" as hs
participant "AWS" as ccp
participant "GitHub" as scs
participant "Ping Pong Tournament System" as ppts

  == Employee Hired ==

h -> hs : Add user
hs -> ccp : Provision User
hs -> scs : Provision User
hs -> ppts : Provision User

  == Time Passes ==

h -> hs : Remove user
hs -> ccp : Deprovision User
hs -> scs : Deprovision User
hs -> ppts : Deprovision User

@enduml
