---
layout: doc
title: 5-Minute Guide
description: This guide will walk you through the steps required to use FusionAuth for login and logout.
navcategory: getting-started
---

:sectnumlevels: 0

Welcome! At the end of this guide, you will know how to add login (sign in) and logout (sign out) to an application.

FusionAuth is a standalone server. When your user tries to log in from your application, you'll send them to FusionAuth. FusionAuth will authenticate them and then send them back to your application, where they can use features that you wrige.

This has a number of benefits:

* FusionAuth is the only system that sees confidential credentials such as passwords.
* It is easy to have additional applications use the same authentication system.
* If you have (or add in the future) different needs around user login and registration, such as requiring multi-factor authentication, you can implement them in a central location.

FusionAuth is avaiable both as an installable piece of software and a SaaS service, so you have options to start. The software is exactly equivalent no matter where you run it (or if you let us do so) so which method you pick really depends on your needs.

Once you have signed in and are at the admin dashboard, the rest of these instructions are the same.

TODO image of dashboard

One of FusionAuth's unique attributes is the variety of places you can install it. You can learn more about link:/docs/v1/tech/installation-guide/[different options in the installation guide].

Please pick the option you'd like to follow to get FusionAuth up and running.

* link:/docs/v1/tech/getting-started/5-minute-fastpath[FastPath], which requires a local database (postgreSQL or mySQL). This is the best option if you have a local database set up.
* link:/docs/v1/tech/getting-started/5-minute-docker[docker compose], which requires docker and docker compose, or a docker compatible system. This is the best choice if you have docker  and docker compose installed. TODO what about compatible options.
* link:/docs/v1/tech/getting-started/5-minute-sandbox[The sandbox], which is a public shared location, with data regularly wiped. This is the best choice if you don't want to install anything and are okay with other's seeing your test users and other data.




add login
add logout
add registration
use passport
explain what happens after
- you have the token. you can either store it in session or send it down as a cookie. Much more in the login workflows section


== Next Steps

include::docs/v1/tech/getting-started/_5-minute-next-steps.adoc[]
