---
layout: doc
title: 5-Minute Guide
description: This guide will walk you through the steps required to use FusionAuth for login and logout.
navcategory: getting-started
---

:page-liquid:

:sectnumlevels: 0

Welcome! At the end of this guide, you will know how to add login (sign in) and logout (sign out) to a Node.js application, using Express and Pug.

== Intro to FusionAuth 

++++
{% capture intro %}
  {% include docs/_fusionauth-intro.liquid %}
{% endcapture %}
{{ intro | markdownify }}
++++

== Choose Your Own Adventure

One of FusionAuth's unique attributes is the variety of places you can install it. Bare metal, cloud, container: yup. Windows, macOS, Linux: sure! You can learn more about link:/docs/v1/tech/installation-guide/[different options in the installation guide]. But for this guide, you'll pick one of three options.

Please choose an option below to explore FusionAuth.

link:/docs/v1/tech/getting-started/5-minute-docker[[.button .brochure .orange .text-larger]#Docker#] &nbsp;&nbsp;&nbsp; link:/docs/v1/tech/getting-started/5-minute-fastpath[[.button .brochure .orange .text-larger]#FastPath#] &nbsp;&nbsp;&nbsp; link:/docs/v1/tech/getting-started/5-minute-sandbox[[.button .brochure .orange .text-larger]#Sandbox#]

* link:/docs/v1/tech/getting-started/5-minute-docker[Docker] requires docker and docker compose. This is the best choice if you have docker and docker compose installed.
* link:/docs/v1/tech/getting-started/5-minute-fastpath[FastPath] requires a local database (PostgreSQL or MySQL). This is the best option if you have a local MySQL or PostgreSQL database installed and want to get the full installation experience.
* link:/docs/v1/tech/getting-started/5-minute-sandbox[The sandbox], which is a public shared location, with data **regularly wiped**. This is the best choice if you don't want to install anything and are okay with other people seeing your test users, applications and data. However, this choice is the quickest way to test drive an integration with FusionAuth without installing anything.

Each of these options will end up at the same place; you'll have a functioning application with login and logout provided by FusionAuth.

Afterwards, you can dig deeper into a number of areas.

== Next Steps

include::docs/v1/tech/getting-started/_5-minute-next-steps.adoc[]
