---
layout: doc
title: Common Errors
description: A list of common errors that you might see in FusionAuth and how to fix them
---

== Access Denied

If you see an Access Denied error in your browser while using the FusionAuth UI, this could be caused by a mis-configured CDN or proxy. This error often produces a 4xx error code such as a 403. In order to fix this issue, ensure that your CDN, proxy or gateway does not prevent traffic from flowing directly to FusionAuth. FusionAuth is able to handle all HTTP traffic and any network handling between the browser and FusionAuth should be as simple as possible.

== FusionAuth Stops 

If you are running FusionAuth on a server with limited memory, it may stop unexpectedly.

You might see lines like this in logs on your server:

```
Dec 30 12:00:38 vps kernel: Out of memory: Kill process 30047 (java) score 98 or sacrifice child
```

The OOM killer will begin killing services once the kernel runs out of memory. The solution will be to allocate less memory to FusionAuth or to increase the amount of RAM available. 

You can do the former with the `fusionauth-app.memory` setting. See the link:/docs/v1/tech/reference/configuration/[configuration reference] for more details. 

You may do the latter by running a larger server or running fewer competing applications. In particular, applications used by FusionAuth such as Elasticsearch or the database may be moved off to external servers.

