---
layout: doc
title: Welcome
description: FusionAuth documentation - Getting Started, Tutorials, API Docs and More
skipFeedback: 1
---
:page-liquid:

:sectnumlevels: 0

== FusionAuth Documentation

Welcome to the FusionAuth technical documentation site. FusionAuth integrates with your application, offering critical, yet undifferentiated, authentication and authorization functionality. We take care of auth so you can build your app.

== Introduction to FusionAuth

++++
{% capture intro %}
  {% include docs/_fusionauth-intro.liquid %}
{% endcapture %}
{{ intro | markdownify }}
++++

== Documentation Overview

Here is an overview of each of the sections:

* *Getting Started*: This section contains helpful concepts and tutorials if you are new to auth or FusionAuth.
* *Installation Guide*: You can install FusionAuth in a variety of ways, from rpm, zip and deb packages to Docker to FusionAuth Cloud, a SaaS offering. This section also covers minimal system requirements and how to set up clustered FusionAuth instances.
* *Migration Guide*: Often times you are migrating to FusionAuth from another system. This section has a general guide as well as specific documentation for Auth0, Keycloak and more.
* *Admin Guide*: Everything you need to operating FusionAuth, from securing FusionAuth to proxy setup. It also includes advice for receiving technical assistance and roadmap.
* *Login methods*: This section offers a deeper dive into using SAML and OAuth/OIDC with FusionAuth. It also includes instructions for setting up FusionAuth to delegate authentication decisions to third party providers. These include social providers such as Facebook, Apple and Google as well as enterprise providers such as SAML and OIDC.
* *Developer Guide*: FusionAuth is built by developers, for developers, and this section contains information about integration, advanced features, guides to specific features and our client libraries documentation.
* *Customization*: FusionAuth's end user interface is extremely customizable, and this section covers how to modify email content, user facing login screens and more.
* *Premium Features*: FusionAuth has a full featured community edition, but some features are reserved for customer with a license key. This section outlines the features and how to use them.
* *APIs*: APIs are the heart of FusionAuth and are documented in depth in this section.
* *Release Notes*: The all important release notes so you can stay current on what is new in FusionAuth!

== Documentation Conventions

- We apitalize all domain objects, especially when calling the API in which the object is created and/or updated in FusionAuth.
For example, see the link:/docs/v1/tech/apis/api-keys[API Key API] description for `apiKeyId`, where API Key is capitalized: `The unique Id of the API Key to create. If not specified a secure random UUID will be generated.`
- If referring to something which is a domain object in FusionAuth, but we are not explicitly referring to an object being created/updated in FusionAuth, we use lowercase.
    Here are some examples:
`To allow users to log into and use your application, you’ll need to create an Application in FusionAuth.`
- From the link:/docs/v1/tech/apis/identity-providers/links[Link API], note the difference between a FusionAuth User and a 3rd party user: `This API is used to create a link between a FusionAuth User and a user in a 3rd party identity provider. This API may be useful when you already know the unique Id of a user in a 3rd party identity provider and the corresponding FusionAuth User.`

Thanks for choosing FusionAuth!
