---
layout: doc
title: Welcome
description: FusionAuth documentation - Getting Started, Tutorials, API Docs and More
skipFeedback: 1
---

:sectnumlevels: 0

== FusionAuth Documentation

Welcome to the FusionAuth technical documentation site. FusionAuth integrates with your application, offering critical, yet undifferentiated, authentication and authorization functionality. We take care of auth so you can build your app.

Here is an overview of each of the sections:

* *Getting Started*: This section contains helpful concepts and tutorials if you are new to auth or FusionAuth.
* *Installation Guide*: You can install FusionAuth in a variety of ways, from rpm, zip and deb packages to Docker to FusionAuth Cloud, a SaaS offering. This section also covers minimal system requirements and how to set up clustered FusionAuth instances.
* *Migration Guide*: Often times you are migrating to FusionAuth from another system. This section has a general guide as well as specific documentation for Auth0, Keycloak and more.
* *Admin Guide*: Everything you need to operating FusionAuth, from securing FusionAuth to proxy setup. It also includes advice for receiving technical assistance, a roadmap and our release notes.
* *Login methods*: This section offers a deeper dive into using SAML and OAuth/OIDC with FusionAuth. It also includes instructions for setting up FusionAuth to delegate authentication decisions to third party providers. These include social providers such as Facebook, Apple and Google as well as enterprise providers such as SAML and OIDC.
* *Developer Guide*: FusionAuth is built by developers, for developers, and this section contains information about integration, advanced features, guides to specific features and our client libraries documentation.
* *Customization*: FusionAuth's end user interface is extremely customizable, and this section covers how to modify email content, user facing login screens and more.
* *Premium Features*: FusionAuth has a full featured community edition, but some features are reserved for customer with a license key. This section outlines the features and how to use them.j
* *APIs*: APIs are the heart of FusionAuth and are documented in depth in this section.

Thanks for choosing FusionAuth!
