---
layout: doc
title: Release Notes
description: Release notes for each version of FusionAuth
---

////
Hide stuff inside these lines
////

++++
<style>
section.docs article blockquote {
  background: none;
}
</style>

<label class="select" style="width: 100%;">
  <select id="release-notes-version" class="select" style="width: 100%;"></select>
</label>
++++

////
If we change the version for archive, update 'cutOverVersion' in the `_download.liquid` file as well.
////

////
Process, or at least one way to do it.

1. Review the Milestone for the release in GH.
2. Order the GH issues by number sequentially.
3. Document the issue, describing the issue at a high level such that most anyone can understand it.
4. Identify if any doc updates need to be made as a result of the issue being closed out.
5. Make any doc changes necessary w/ version flags if necessary.
6. If the issue is for a new API, feature, or change to anything, please add a link to that API or relevant section if you say "for more information see..."
7. Close the GH issue.
8. Rinse and repeat until all issues in the milestone are complete.
9. Once all issues are closed in the milestone, close it in GH w/ a date equal to that of the release.
10. If the patch or point release has a db migration, ensure you add the warning for db migration, and add the version to the `upgrade.adoc` file.
11. Do a read through / visual sanity check of release notes for typos, test links, etc.

Release notes should have sections such as the following, omit ones that do not have any entries, and use this order:

=== Known Issues
=== Changed
=== Fixed
=== Enhancements
=== New
=== Internal

////

Looking for release notes older than 1.23.0? Look in the link:/docs/v1/tech/archive/release-notes/[release notes archive].

[role=release-note]

== Version 1.32.1
_December 13th, 2021_

=== Fixed
* If you are modifying the user email or username in an Identity Provider Reconcile Lambda, the lambda may be invoked more than once after the initial link has been established. This may cause User registration data to be modified, or lost. If you have not yet upgraded to this version, it is advised that you wait until you can update to version `1.32.1`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1517[GitHub Issue #1517], thanks to https://github.com/Oceanswave[@Oceanswave] for letting us know and for the fantastic bug write up!
* The 1.32.0 version of the Docker image was initially released with a missing Java module that may cause the image to fail during startup. An updated version of the image has been released, if you encounter an issue, please delete your local version of the image and pull it again. The issue is also resolved in this version, so you may also pull the `latest` tag once this version is available.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1518[GitHub Issue #1518]

[role=release-note]

== Version 1.32.0
_December 10th, 2021_

=== Fixed
* The global and application registration count rollup may fail when using PostgreSQL. This will cause the registration count reports to be incorrect.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1498[GitHub Issue #1498]
* When using the Development Reset feature (technical preview) and the FusionAuth application is configured to use a specific theme, the reset will fail.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1514[GitHub Issue #1514]

=== Enhancements
* Identity provider linking that was introduced in version 1.28.0 can now optionally be configured to limit the number of unique links to an IdP for a particular user.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1310[GitHub Issue #1310]
* Allow application URIs to be configured as an OAuth2 Authorized request origin URLs. For example, you may now configure `android-app://com.example` as a valid Authorized request origin.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1443[GitHub Issue #1443], thanks to https://github.com/bonify-b2b[@bonify-b2b] for the request.
* Add configuration to allow implicit email verification to be disabled. For example, prior to this release, email based workflows such as Passwordless login, email based registration verification, email based password change, and verifying a two-factor code during login through an email would implicitly mark a user's email as verified if email verification was enabled and the user had not yet completed email verification. In most cases this seems to be the best choice for the end user such that they do not perform redundant tasks to verify their email address once they have provided evidence they have access to the email address. This configuration allows this behavior to be disabled if you wish to require your end user to always go through a specific email verification process for legal or other similar reasons.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1467[GitHub Issue #1467], thanks to https://github.com/lliu-20200701[@lliu-20200701] for the request.
* Add a notice on the Device workflow panel when an existing SSO session exists to allow the user to optionally logout prior to continuing.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1495[GitHub Issue #1495]

=== New
* You may optionally specify custom SMTP headers in the Tenant email configuration. These configured headers will be added to all outbound messages.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/628[GitHub Issue #628], thanks to https://github.com/arni-inaba[arni-inaba] for the suggestion.

=== Internal
* Java 17 LTS. Update to the latest long term support version of Java.

[role=release-note]

== Version 1.31.0
_November 18th, 2021_

=== Known Issues
* If you are modifying the user email or username in an Identity Provider Reconcile Lambda, the lambda may be invoked more than once after the initial link has been established. This may cause User registration data to be modified, or lost. If you have not yet upgraded to this version, it is advised that you wait until you can update to version `1.32.1`.
** Resolved in 1.32.1 by https://github.com/FusionAuth/fusionauth-issues/issues/1517[GitHub Issue #1517]

=== Changed
* You may now modify, or fabricate an email or username in the Identity Provider Reconcile Lambda regardless of the Identity Provider type.
** Some of this capability has been provided in the past for the OpenID Connect Identity Provider. This capability was removed in version `1.28.0` when Identity Provider Linking was introduced due to the additional use cases now supported through linking strategies. Due to high demand, and many real world use-cases presented by our users, this decision has been reversed in favor of flexibility for the developer. Please use caution when using this capability, and note that if you create or modify a `username` or `email` in the Reconcile lambda, the lambda will be invoked twice during a single login request.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1425[GitHub Issue #1425]

=== Fixed
* Requiring a birthdate on a self-service registration form when also requiring a parent email may cause an exception.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/702[GitHub Issue #702]
* Improvements to locale handling to expand beyond ISO 639 support to support locales such as `es_419`, `aghem` and others.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/978[GitHub Issue #978]
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1132[GitHub Issue #1132]
* Disabling webhooks on the tenant configuration by clicking on the [field]#Enabled# header doesn't work as expected.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1123[GitHub Issue #1123]
* Fix general message template issues when using the preview action for a message template, or a localized version of the template.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1171[GitHub #1171]
* An API key created using Kickstart is not validated for length correctly.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1397[GitHub #1397], thanks to https://github.com/miaucl[@miaucl] for reporting!
* The error message returned to the end user when a webhook fails during a Self-Service Registration is not able to be customized through a theme.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1446[GitHub Issue #1446]
* The Theme preview may not render the Account Edit themed page when a Self-Service form is configured
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1448[GitHub Issue #1448]
* Unable to delete an email template when an email template is not assigned to a Consent.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1449[GitHub #1449]
* A timing issue exists when creating a new Application role, and then immediately attempting to register a user with that role.
** This issue was introduced in version `1.30.2`
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1452[GitHub Issue #1452], thanks to one of our MVPs https://github.com/johnmaia[@johnmaia] for reporting!
* Using an expired Passwordless link may result in an infinite redirect
** This issue was introduced in version `1.27.0` when support for Microsoft Outlook Safe Links was added via https://github.com/FusionAuth/fusionauth-issues/issues/629[GitHub Issue #629]
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1456[GitHub #1456], thanks to https://github.com/rscheuermann[@rscheuermann] for the report!
* Missing validation on the Registration API to ensure the User exists by Id when passing the `userId` on the HTTP request URL segment
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1457[GitHub #1457]
* When copying a Tenant in the FusionAuth Admin UI when the source Tenant has Blocked domain configuration present, the Blocked domain configuration is not copied to the new tenant.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1459[GitHub #1459]
* When using the OAuth2 Password Grant (Resource Owner Credentials Grant), and the `client_id` is provided in the HTTP Basic Authorization header, but not in the HTTP post body, the resulting JWT will not contain the `aud` claim.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1462[GitHub #1462]
* A database FK violation may occur in the Registration Count aggregation service if you delete a Tenant before the aggregator runs.
** This issue was introduced in version `1.30.2`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1466[GitHub #1466]
* Enabling Two-Factor in the Self-Service themed forms, or in the Admin UI may fail to render the QR code if the encoded string used to build the QR code is between 192 and 220 characters in length.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1470[GitHub #1470], thanks to https://github.com/jasonaowen[@jasonaowen] for letting us know and helping us debug it!
* When a user is assigned roles explicitly through a User Registration in addition to a Group membership, the roles assigned by the Group membership will not be returned.
** This issue was introduced in version `1.30.2` vi https://github.com/FusionAuth/fusionauth-issues/issues/480[GitHub Issue #480]
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1473[GitHub #1473]
* When using the Setup Password email template provided by FusionAuth with the User Registration API to create a User and a Registration in a single API call the URL generated and sent to the user may not be usable. A `client_id` will have been added to the URL which will result in an error when the FusionAuth page is rendered. To work around the issue prior to this release, please remove the `client_id` from the Email template.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1476[GitHub #1476]
* A SAML v2 SP using an HTTP Redirect Binding that has URL encoded the query string using lower case percent encoding may cause FusionAuth to fail to validate the signature.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1496[GitHub #1496], thanks to engineering team at https://www.haproxy.com[HAProxy] for the assist!

=== Enhancements
* You may now access the `id_token` when available during an OpenID Connect Reconcile lambda
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/323[GitHub Issue #323], thanks to https://github.com/Thammada[@Thammada] for opening the issue!
* Add additional support for `idp_hint` for Apple and Twitter Identity Providers.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1306[GitHub #1306]
* Add an example use and changed user to the Audit Log Test event when using the Webhook Tester in the FusionAuth Admin UI
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1360[GitHub Issue #1360]
* When FusionAuth is unable to discover OpenID endpoints using the configured Issuer during configuration of an OpenID Connect Identity Provider an Event Log will be produced to assist you in debugging the connection.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1417[GitHub Issue #1417]

=== Internal
* Update the internal scheduler library.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1461[GitHub #1461]


[role=release-note]

== Version 1.30.2
_October 13th, 2021_

include::docs/v1/tech/__database-migration-warning.adoc[]

=== Fixed
* When logging in with an anonymous user from an IdP that now has a linking strategy other than Anonymous an exception occurs. This can occur if you change your linking strategy from Anonymous to something else, and users that were created while configured as Anonymous log in again.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1316[GitHub Issue #1316]
* The view dialog may not completely render for an SAML v2 IdP Initiated IdP configuration. The dialog fails to completely render due to a FreeMarker exception.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1324[GitHub Issue #1324]
* If you are activating FusionAuth Reactor during initial startup via Kickstart, and you have CAPTCHA enabled for the FusionAuth admin application, you may not be able to login until the Threat Detection feature comes online. Depending upon your network connection, this may take a few seconds, or a few minutes.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1358[GitHub Issue #1358]
* The .NET client library handled `exp` and other JWT timestamp values incorrectly.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1362[GitHub Issue #1362], thanks to https://github.com/RyanDennis2018[@RyanDennis2018] for reporting.
* When using the duplicate Application button in the admin UI, if the source Application has SAML v2 configured, but not enabled, the copy may fail with an exception.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1366[GitHub Issue #1366]
* Updating a connector will add an additional `*` domain configuration. This is a regression issue introduced in version `1.28.0`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1367[GitHub Issue #1367]
* When generating an RSA Key, a user cannot specify a certain Id.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1368[GitHub Issue #1368]
* If using kickstart to activate a licensed instance with advanced threat detection enabled, it is possible to get stuck in the Setup Wizard.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1369[GitHub Issue #1369]
* A user can add new entries to an access control list, but can't delete them using the administrative user interface.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1371[GitHub Issue #1371]
* Default lambdas are no longer available in Kickstart environment variables. This is a regression introduced in version `1.30.0`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1373[GitHub Issue #1373]
* The event payload for a user deactivation was not complete when the deactivation happened via the administrative user interface. It lacked some information such as the IP address of the request.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1375[GitHub Issue #1375]
* When both Kickstart and maintenance mode occur during an upgrade, a NullPointerException could occur if the default tenant Id was being modified.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1382[GitHub Issue #1382]
* The IP address can be missing from login records in certain circumstances.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1391[GitHub Issue #1391]
* Requests with IPv6 addresses cause NumberFormatExceptions.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1392[GitHub Issue #1392]
* CAPTCHA may not work on the email verification required page. 
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1396[GitHub Issue #1396]
* Rendering the passwordValidationRules object on the register page in theme preview does not work.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1398[GitHub Issue #1398]
* User search widget has an empty value if the user does not have a name.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1399[GitHub Issue #1399]
* Filling out a CAPTCHA through self service registration or other paths does not save device trust; the user will be prompted a second time.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1400[GitHub Issue #1400]
* Setup Wizard may be shown in a multi-node environment after it has completed.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1402[GitHub Issue #1402]
* When using advanced threat detection rate limiting, users are unable to set the rate limit configuration to 1 to allow a limited action be performed only once.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1407[GitHub Issue #1407]
* Custom data for webhooks not displayed in the admin UI.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1422[GitHub Issue #1422]
* A truncated deflated SAML AuthN request was not handled as well as it should have been.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1424[GitHub Issue #1424]
* Some key pairs capable of signing a SAML request are not eligible in the UI.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1430[GitHub Issue #1430]
* Custom data for connectors not displayed in the admin UI.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1435[GitHub Issue #1435]

=== Enhancements
* When using MySQL with a large number of applications, and application roles, it may become slow to retrieve a user. This change should improve performance when using MySQL.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/480[GitHub Issue #480], thanks to https://github.com/nikos[@nikos] and David B. for the assist!
* Improve the performance of using the Public Key API endpoint when you have a lot of applications and keys.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1145[GitHub Issue #1145], thanks to https://github.com/nulian[@nulian] for reporting, and https://github.com/Johpie[@Johpie] for the additional debug.
* Display the database version and elastic search versions in the administrative user interface.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1390[GitHub Issue #1390]
* Improve User and Registration API performance at scale.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1415[GitHub Issue #1415]
* Try to support SAML POST bindings with SSO even when cookie samesite policy is set to `SameSite=Lax`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1426[GitHub Issue #1426]
* Add a default NameID format when one is not provided on SAML AuthN or Logout requests.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1428[GitHub Issue #1428]

=== Internal

* Update Apache Tomcat from `8.5.63` to `8.5.72`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1433[GitHub Issue #1433]

[role=release-note]

== Version 1.30.1
_August 25th, 2021_

include::docs/v1/tech/__database-migration-warning.adoc[]

=== Known Issues
* Registration counts may fail to be rolled up into reports when using PostgreSQL. Updating to 1.3.20 should resolve the issue.
** Resolved in 1.32.0 by https://github.com/FusionAuth/fusionauth-issues/issues/1498[GitHub Issue #1498]

=== Fixed
* The Text MIME type of an email may not render unicode correctly when the host system does not have `UTF-8` set as the default character set.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1122[GitHub Issue #1122], thanks to https://github.com/soullivaneuh[@soullivaneuh] for the report!
* Unable to assign an IP ACl to an application if one is not already assigned to the tenant.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1349[GitHub Issue #1349]
* Unable to delete an IP ACL in use by a tenant
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1350[GitHub Issue #1350]

=== Enhancements
* General performance improvements for login, OAuth2 grants, and user create and registration.
* Add the User Two Factor methods to the Elasticsearch index.
** If you have existing users with Two-Factor enabled, you will want to perform a re-index in order to search on two-factor configuration.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1352[GitHub Issue #1352], thanks to one of our favorite FusionAuth users https://github.com/flangfeldt[@flangfeldt] for making the request.

=== Internal
* Performance improvements

[role=release-note]

== Version 1.30.0
_August 12th, 2021_

:warning_message: pass:normal[Many of the new features in this release will only be available in the Enterprise edition of FusionAuth and will require the Threat Detection feature to be enabled. Contact sales for more information. \
{nbsp} + \
{nbsp} + \
Features that require the Threat Detection feature: \
{nbsp} + \
- CAPTCHA \
{nbsp} + \
- Domain blocking in registration \
{nbsp} + \
- IP access control lists \
{nbsp} + \
- IP location \
{nbsp} + \
- Some of the new events and transactional emails \
{nbsp} + \
- Rate limiting]
include::docs/v1/tech/__general-migration-warning.adoc[]


include::docs/v1/tech/__database-migration-warning.adoc[]

=== Known Issues
* If you are referencing any Reconcile Lambda Ids using the syntax `FUSIONAUTH_LAMBDA{type}_ID` - this may no longer work due to a change in how these default lambdas are initialized.
** The current work around is to modify your kickstart to build your own version of this lambda instead of using the FusionAuth default.
** You will find a copy of the default lambdas shipped with FusionAuth in the link:/docs/v1/tech/lambdas/[Lambda] documentation that you may use to copy into your kickstart.
** The issue is being tracked here https://github.com/FusionAuth/fusionauth-issues/issues/1373[GitHub Issue #1373]

=== Fixed
* Unable to enable `user.action` event at the tenant using the UI. If you encounter this issue, you may work around it by using the Tenant API.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1307[GitHub Issue #1307]
* If you make an API request to `/api/two-factor/login` with an empty JSON body, an exception will occur instead of a validation error being returned with a `400` status code.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1330[GitHub Issue #1330]
* When using an IdP with a linking mode other than Create Pending Link, the token may not correctly be stored. If you previously had been using the token stored on the User Registration, and are now looking for it in the Identity Provider Link, you may not find it. This fix resolves the issue.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1341[GitHub Issue #1341]
* When you are using FusionAuth as a SAML v2 IdP with Redirect bindings, you were unable to use idp_hint to bypass the login page to federate to another provider.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1331[GitHub Issue #1331]


=== Changed
* New themed page added for Unauthorized access.
** See the link:/docs/v1/tech/apis/themes/[Theme API] and the link:/docs/v1/tech/themes/[Theme] documentation for additional details.
* A macro available to themes named `[@helpers.input]` was modified to be able to build a checkbox. This change could affect you if you try to copy and paste the checkbox usage without modifying the macro definition in your Helper file. Review the link:docs/v1/tech/themes/#upgrading[Upgrading] section on the link:docs/v1/tech/themes/[Themes] page for information on how to resolve potential breaking changes.

=== New
* JWT Vending machine
** This allows a JWT to be created for a not-yet-existing user with a payload defined by the API caller.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/525[GitHub Issue #525]
* FusionAuth wasn't awesome enough, so we added a robust Threat Detection feature for enterprise customers. This feature includes:
* IP Access Control for API keys
** This allows support for an API key to be further restricted by the origin IP address.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/933[GitHub Issue #933]
* IP Access Control for SSO and self service forms
** This allows you to limit access to the FusionAuth SSO or a particular application login through SSO by IP address
* Blocked domain configuration to limit registrations from specific email domains
* Rate limiting per user for the following requests:
** Failed login (only used if Failed Login configuration is not in use)
** Forgot password
** Send email verification
** Send passwordless
** Send registration verification
** Send two-factor
* Captcha - add CAPTCHA to login and other end user forms to help ensure only humans are submitting forms.
** This feature is in tech preview and is subject to change.
** Support for Google ReCaptcha v2, Google ReCaptcha v3, HCaptcha and HCaptcha Enterprise
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/278[GitHub Issue #278]
* IP location.
** When possible, an IP address will be resolved to include city, country, region, zip code, longitude and latitude.
** IP location will be included in login records and will be available in some email templates and webhook events
** Used to calculate impossible travel between login locations
* New Webhook events:
** Audit Log Create `audit-log.create`
** Event Log Create `event-log.create`
** Kickstart Success `kickstart.success`
** User Create Complete `user.create.complete`
** User Delete Complete `user.delete.complete`
** User Update Complete `user.update.complete`
** User LoginId Duplicate On Create `user.loginId.duplicate.create`
** User LoginId Duplicate Update `user.loginId.duplicate.update`
** User Email Update `user.email.update`
** User Login New Device `user.login.new-device`
** User Login Suspicious `user.login.suspicious`
** User Password Reset Success `user.password.reset.success`
** User Password Reset Send `user.password.reset.send`
** User Password Reset Start `user.password.reset.start`
** User Password Update `user.password.update`
** User Registration Create Complete `user.registration.create.complete`
** User Registration Delete Complete `user.registration.delete.complete`
** User Registration Update Complete `user.registration.update.complete`
** User Two Factor Method Added `user.two-factor.method.add`
** User Two Factor Method Removed `user.two-factor.method.remove`
** See the link:/docs/v1/tech/#eventswebhooks/[Event Webhooks] documentation for additional details.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1308[GitHub Issue #1308], thanks to https://github.com/adoliver[@adoliver] for the suggestion!
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1178[GitHub Issue #1178]
* New transactional emails:
** Email update
** Login Id duplicate on create
** Login Id duplicate on update
** Login with new device
** Suspicious login
** Password reset success
** Password update
** Two-factor method added
** Two-factor method removed

=== Enhancements
* Search on `oldValue`, `newValue` and `reason` in the Audit Log.
** See the link:/docs/v1/tech/apis/audit-logs/#search-the-audit-log[Audit Log Search API] for additional details on searching on `oldValue`, `newValue` and `reason` in the audit log.
* When using IdP linking in conjunction with the Oauth2 Device Grant, the recently completed links will be available on the Device complete themed page by using the `completedLinks` variable.
** See the link:/docs/v1/tech/themes/#oauth-device-complete[Device Complete] themed page documentation for additional details.
* More themed pages will have access to the currently logged in user using the `currentUser` variable.
** See the link:/docs/v1/tech/themes/[Theme] documentation for additional details.

[role=release-note]

== Version 1.29.4
_August 12th, 2021_

=== Fixed
* When a user is required to complete registration after login, the user may no longer be able to login w/out a password reset. This is a regression from version 1.28.0, and only affects those using self-service registration that will have existing users that do not have all required fields on their account.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1344[GitHub Issue #1344], thanks to https://github.com/flangfeldt[@flangfeldt] for reporting the issue

[role=release-note]

== Version 1.29.3
_August 6th, 2021_

=== Fixed
* A `404` may be returned when attempting to update a user with `PUT` or `PATCH` on the User API if the user has an unverified email and email verification has been disabled.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1333[GitHub Issue #1333]

[role=release-note]

== Version 1.29.2
_July 31st, 2021_

=== Fixed
* When using a SAML v2 IdP that does not send back a `KeyInfo` element in the XML response, an exception may occur when attempting to parse the response.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1332[GitHub Issue #1332]


[role=release-note]

== Version 1.29.1
_July 26th, 2021_

include::docs/v1/tech/__database-migration-warning.adoc[]

=== Fixed
* In a multi-tenant configuration, SSO sessions may be pre-maturely terminated if one tenant has a lower TTL configuration than the other tenants. To work around this issue prior to this release, ensure all SSO TTL configurations are equal.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1262[GitHub Issue #1262]
* The arg names in the `LambdaType` enum were not all correct.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1284[GitHub Issue #1284]
* An IdP Debug event log may not get produced when a unique Id could not be resolved.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1315[GitHub Issue #1315]
* When enabling the SAMl v2 IdP debug log an exception may be taken when attempting to produce the debug event log. The result is that the debug log will not be produced.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1317[GitHub Issue #1317]

[role=release-note]

== Version 1.29.0
_July 10th, 2021_

=== Fixed
* When viewing the theme preview for the `oauth2/start-idp-link.ftl` template, and error may be logged.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1276[GitHub Issue #1276]
* When a webhook transaction fails to create a user or registration on a themed page, a non-themed error page may be displayed
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1279[GitHub Issue #1279]

=== Enhancements
* Enhance the Link API to retrieve a user by a 3rd party unique Id to identify a FusionAuth user is linked to the user. See the link:/docs/v1/tech/apis/identity-providers/links/[Link API] for additional details.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1277[GitHub Issue #1277]
* During a device link request which contains a device linking token, show an intermediate page asking the user if they would like to sign in with an existing user or create a new user.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1287[GitHub Issue #1287]
* Allow the IdP Login API to optionally be passed a request parameter to indicate a link should not be established and a `404` should be returned instead. This is useful if you wish to identify if a link exists first before starting an auxiliary workflow such as a device grant with a linking token. See the link:/docs/v1/tech/apis/identity-providers/[Login API] for additional details.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1288[GitHub Issue #1288]
* Add additional configuration to the unique username configuration to support always appending a suffix even when the username is not in use. See the link:/docs/v1/tech/apis/tenants/[Tenant API] for additional details.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1290[GitHub Issue #1290]
* Add an additional debug event log when for the SAML IdP to debug the `AuthN` request sent to the SAML IdP
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1293[GitHub Issue #1293]
* In version `1.28.0` the resolution of the value returned by the SAML v2 IdP in the `NameID` was modified. If the IdP returns a format of `unspecified` with a value of `email` then after upgrading to version `1.28.0` your SAML IdP will not function properly. Ideally you would ask your IdP to return you a NameID format of `emailAddress`, but if that is not possible this enhancement will allow FusionAuth to accept the value returned in the `NameID` if the format is returned as `unspecified`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1294[GitHub Issue #1294]
* Instead of logging FreeMarker exceptions to the system log and producing a stack trace that may end up in the UI, an event log will be produced. The message in the UI will be condensed based upon the runtime mode. When in `development` mode some details will be provided to assist in debugging your themed template. If in `production` runtime mode only a message indicating an error occurred will be displayed to the user.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1299[GitHub Issue #1299]

=== Internal
* Update HikariCP from `3.4.1` to `4.0.3`, and update PostgreSQL JDBC driver from `42.2.14` to `42.2.22`
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1300[GitHub Issue #1300]

[role=release-note]

== Version 1.28.1
_June 21st, 2021_

include::docs/v1/tech/__database-migration-warning.adoc[]

=== Fixed
* Allow self-consent form field on a self-service form.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1258[GitHub Issue #1258]
* Correct validation of a consent form field on edit. Control type was failing validation on edit.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1260[GitHub Issue #1260]
* An imported user requiring password change, and email verification may fail to verify email verification with an email verification gate.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1265[GitHub Issue #1265]
* Better parsing of the `X-Fowarded-For` HTTP request header. This header may contain one to many IP addresses, and only the first value should be preserved for the login record. Prior to this fix, it would be possible to see a login record that contained multiple IP addresses separated by a comma.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1267[GitHub Issue #1267]
* Correctly show the Verification URL in the OAuth2 configuration when the `Device` grant is selected. This issue was introduced in `1.28.0`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1268[GitHub Issue #1268]
* Use the correct FusionAuth redirect URL when using the Sony Playstation Network IdP.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1269[GitHub Issue #1269]
* Use the correct FusionAuth redirect URL when using the Steam IdP. This IdP uses an Implicit Grant and should be using the `/oauth2/callback/implicit` callback URL.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1272[GitHub Issue #1272]
* Allow the Epic Games IdP to function properly when omitting the `scope` configuration property.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1273[GitHub Issue #1273]

=== Tech Preview
* You may optionally start an account link when beginning a Device grant.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1274[GitHub Issue #1274]

[role=release-note]

== Version 1.28.0
_June 7rd, 2021_

:warning_message: pass:normal[The FusionAuth identity providers have undergone a significant improvement to add additional flexibility and support for 3rd parties. Please take time to test this upgrade with your existing configuration to ensure compatibility. Some of the features in this release are in tech-preview.]
include::docs/v1/tech/__general-migration-warning.adoc[]

include::docs/v1/tech/__database-migration-warning.adoc[]

=== Known Issues
* If you are using self-service registration there is a possibility that a user may be required to complete registration by adding additional fields to their account after they login. In this scenario it is possible that they will no longer be able to login and will be required to reset their password. The fix for this was added in `1.29.4`.
** Fixed in `1.29.4`, under https://github.com/FusionAuth/fusionauth-issues/issues/1344[GitHub Issue #1344], thanks to https://github.com/flangfeldt[@flangfeldt] for reporting the issue

=== Changed
* You may no longer build a synthetic email address using a lambda for an OpenID Connect identity provider. This has been removed because you may now link a user by username or create a link w/out a username or an email to an existing FusionAuth user. If you are using this feature, you may need to plan for a migration to this new behavior. If you have a support contract with FusionAuth, please reach out and ask for additional information.
* When using FusionAuth as a SAML IdP, FusionAuth will now accept `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` in addition to `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`. This should allow FusionAuth to work with SAML v2 service providers that only support the persistent NameID format.
* Tokens returned by IdPs are no longer stored on the User Registration object in the `tokens` field. Each token is now stored with the IdP link for the User and the IdP. See the link:/docs/v1/tech/apis/identity-providers/links/[Link API] for additional details.

=== New
* Reindex API
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1232[GitHub Issue #1232]
** See the link:/docs/v1/tech/apis/system/#rebuild-the-elasticsearch-index[Reindex API] for usage.
* Account Link API
** This API will allow you to link and un-link users in 3rd party identity providers with a FusionAuth user.
** See the link:/docs/v1/tech/apis/identity-providers/links/[Link API] for usage.
* IdP Linking options
** Each Identity Provider may now be configured with a linking strategy. The strategies will include linking by email, username, anonymous or a link to an existing user.
** Linking by username is now supported. There is a higher risk of account takeover using this strategy, you should use caution when using this feature.
** Tokens from identity providers should now be retrieved from the link, rather than the registration. More information can be found under `identityProviderLink.token` response value link:/docs/v1/tech/apis/identity-providers/links/#retrieve-a-link[here]
* Email Send API allows an email address in the To field instead of only allowing FusionAuth userIds
** See the link:https://fusionauth.io/docs/v1/tech/apis/emails/#send-an-email[Email Send API] for additional details.
* SAML Identity Provider can now be configured to use any NameID format. Previously only the Email NameID format was utilized.
** This should allow the SAML identity provider configuration to be more flexible and work with additional SAML identity providers.

=== Enhanced
* When FusionAuth is acting as a SAML Identity Provider, you may now send a NameID format of Email or Persistent.
** This should allow FusionAuth to work with additional SAML service providers such as Slack.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/522[GitHub Issue #522]
* The link:https://fusionauth.io/docs/v1/tech/apis/emails/#send-an-email[Email Send API] now allows you to send to a user that does not yet exist in FusionAuth by allowing you to specify an email address for the `To:` field.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/743[GitHub Issue #743]
** See the  link:/docs/v1/tech/apis/login[Email Send API] for additional details.
* The Facebook and Google Identity Providers will now default to using a redirect instead of a popup for login. All existing configurations will be migrated to use the popup dialog to remain consistent with the previous behavior. With this update you may now also use the `idp_hint` parameter to login with Facebook and Google.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/909[GitHub Issue #909]
* Additional PKCE and Client Authentication configuration
** You may now optionally configure PKCE as required, not required, or required when not using a confidential client. This offers better compatibility when multiple client types (a webapp and a mobile app, for example) are authenticating against a single FusionAuth application.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1152[GitHub #1152]
* Add the currently selected Two Factor method object to the Themed Two Factor page `/oauth2/two-factor`
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1237[GitHub Issue #1237], thanks to one of our MVPs - https://github.com/flangfeldt[@flangfeldt] for the suggestion!
* Allow using IdP buttons on the Themed registration page
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/554[GitHub Issue #554], thanks to https://github.com/gordody[@gordody] for the request!
* When using email verification required with the gated configuration, optionally send the user another email before entering the gated page if the user does not have an existing verification email that is not expired.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1247[GitHub Issue #1247], thanks to https://github.com/lliu-20200701[@lliu-20200701] for the suggestion.

=== Fixed
* Do not add the `NotBefore` assertion on the SAML AuthN response on the subject confirmation.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1215[GitHub #1215], thanks to https://github.com/pakomp[@pakomp] for pointing out this issue!
* When importing users with `passwordChangeRequired=true` w/out specifying the change reason an exception may occur during login.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1245[GitHub Issue #1245], thanks to https://github.com/lliu-20200701[@lliu-20200701] for finding this bug.
* When using the email verification gate and self-service registration if a user requires their email to be verified and is forced through the complete registration flow they will not be correctly gated.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1246[GitHub Issue #1246], thanks to https://github.com/lliu-20200701[@lliu-20200701] for reporting!
* Fix a JavaScript bug that may cause some of the themed pages to render incorrectly in the view window.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1228[GitHub Issue #1228], thanks to https://github.com/flangfeldt[@flangfeldt] for reporting!

=== Tech Preview
* New IdPs for EpicGames, Nintendo, Sony PlayStation Network, Steam, Twitch, Xbox - see link:/docs/v1/tech/identity-providers/[link] for more information
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1205[GitHub Issue #1205] - Sony Playstation Network
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1206[GitHub Issue #1206] - Nintendo
*** Note, the Nintendo IdP is not yet fully functional. This will be completed in a patch release.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1207[GitHub Issue #1207] - Twitch
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1208[GitHub Issue #1208] - Steam
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1209[GitHub Issue #1209] - Epic Games
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1210[GitHub Issue #1210] - Xbox
* Development kickstart reset. When you are running in `development` runtime mode, you'll see a `Reset` menu item in the System navigation menu.
** See [breadcrumb]#System -> Reset#
* There is now a JWT populate lambda for the Client Credentials Grant. See link:/docs/v1/tech/lambdas/client-credentials-jwt-populate/[link] for more information.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1233[GitHub Issue #1233]

[role=release-note]

== Version 1.27.2
_May 10th, 2021_

=== Changed
* In version `1.26.0` the ability to use `user.data.email` for Forgot Password and Passwordless login flows was removed. Support for this behavior has been restored in this patch.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1204[GitHub Issue #1204], thanks to https://github.com/mcs[@mcs] for letting us know how this change impacted his usage.

=== Fixed
* When building a new theme starting with 1.27.0, you may encounter a JavaScript error during page render. This error should not cause any end user failures, but the login may not properly capture the browser type.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1216[GitHub Issue #1216]


[role=release-note]

== Version 1.27.1
_May 7th, 2021_

=== Fixed
* When migrating from 1.26.0 or earlier to version 1.27.0 the initial render of the add Tenant panel in the admin UI may fail to render. If you encounter this issue, you may upgrade or edit the FusionAuth tenant first and then try the request again.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1196[GitHub Issue #1196]
* Make the verification flow simpler when you enable both email and registration verification during self-service registration.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1198[GitHub Issue #1198]
* The view dialog for the SAML v2 IdP Initiated configuration may not render correctly.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1200[GitHub Issue #1200]
* When configuring the SAML v2 IdP Initiated Login configuration for an IdP that has a `issuer` that is not a URL the configuration will fail because we are expecting a URL for this field.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1203[GitHub Issue #1203]

[role=release-note]

== Version 1.27.0
_May 5th, 2021_

:warning_message: pass:normal[Some of the features in this release are in tech-preview. Please give us feedback and let us know how they work for you!]

include::docs/v1/tech/__general-migration-warning.adoc[]

include::docs/v1/tech/__database-migration-warning.adoc[]

=== Changed
* Login API now returns `213` for Registration Not Verified.
** See the link:/docs/v1/tech/apis/login[Login API] response for additional details.
* The Login API and the User API may optionally return a `emailVerificationId` or `registrationVerificationId` to assist the developer in completing a verification workflow when the verification strategy has been configured to use a short code instead of a long "clickable" link.
** See the link:/docs/v1/tech/apis/login[Login API] response for additional details.
* The Verify Email API now takes the `verificationId` in the request body instead of a URL segment. See the link:/docs/v1/tech/apis/users/#verify-a-users-email[Verify Email API] for additional details.
** This change is backwards compatible, but the deprecated use of the API may be removed in the future.
** The client libraries methods have also been preserved, but a new method has been added to accept a request body.
* The Verify Registration API now takes the `verificationId` in the request body instead of a URL segment.
** This change is backwards compatible, but the deprecated use of the API may be removed in the future.
** The client libraries methods have also been preserved, but a new method has been added to accept a request body.
* When calling `PUT` on the Login API (ping) the response may optionally return an `emailVerificationId` or `registrationVerificationId` to assist the developer in completing a verification workflow when the verification strategy has been configured to use a short code instead of a long "clickable" link.
** See the Login API response for additional details.
* The User API and Registration API may optionally return an `emailVerificationId` or a map of registration verification Ids to assist the developer in completing a verification workflow when the verification strategy has been configured to use a short code instead of a long "clickable" link.
** See the User and Registration API response examples for additional details.

=== Fixed
* CleanSpeak username filtering may not always work when using advanced self-service registration forms with only one step.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1158[GitHub Issue #1158]
* Link to SAML v2 IdP Initiated Add in the Admin UI was missing. See GH issue for a work around.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1181[GitHub Issue #1181]
* Fixes for the new API Key API - usages in the Admin UI. Allow the Admin UI to upgrade and downgrade API keys for Key Manager.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1174[GitHub Issue #1174]

=== Tech Preview
* Application Themes. You may optionally assign a theme per application which will then be utilize instead of the tenant configuration.
** https://github.com/FusionAuth/fusionauth-issues/issues/769[GitHub Issue #769]
* Email verification gate. When using the FusionAuth themed pages, you may force a user to verify their email address before being redirected back to your application.
** https://github.com/FusionAuth/fusionauth-issues/issues/1191[GitHub Issue #1191]
* Configurable verification strategies to use an interactive form instead of a clickable link.
** May require a change to your email template, see the updated Email Verification documentation for additional details.
** https://github.com/FusionAuth/fusionauth-issues/issues/1191[GitHub Issue #1191]
* Unique usernames. Allow more than one user to select the same username and allow FusionAuth to manage a unique suffix.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1190[GitHub Issue #1190]

=== New
* Product Version API.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1193[GitHub Issue #1193]
** Thanks to https://github.com/jegger[@jegger] for the request!
** See link:/docs/v1/tech/apis/system/#retrieve-system-version/[Version API] for additional details or find `retrieveVersion` in your FusionAuth client library.

=== Enhancements
* Try to support Microsoft Outlook Safe Links
** Hopefully  resolves https://github.com/FusionAuth/fusionauth-issues/issues/629[GitHub Issue #629]
* Support HTTP Basic Auth using an API key for the Prometheus Metrics endpoint added in 1.26.0.
** See Prometheus endpoint documentation for additional details on authenticating this endpoint.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1189[GitHub Issue #1189]

[role=release-note]

== Version 1.26.1
_April 20th, 2021_

=== Fixed
* If you use a non default theme for the FusionAuth default tenant, you may see an error when trying to log in to the admin UI after upgrading to version 1.25.0. You can workaround this by appending `?&bypassTheme=true` to your login URL, or append `/admin/` to your base FusionAuth URL to log into the admin UI.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1175[GitHub Issue #1175].

=== Known Issues
* You cannot create a "SAML v2 IdP Initiated" Identity Provider in the admin UI; it isn't present in the "Add Identity Providers" dropdown. You can workaround this by entering the URL to add an Identity Provider manually: `\https://auth.example.com/admin/identity-provider/add/SAMLv2IdPInitiated` (append `/admin/identity-provider/add/SAMLv2IdPInitiated` to your FusionAuth base URL). Tracking in https://github.com/FusionAuth/fusionauth-issues/issues/1181[GitHub Issue #1181].


[role=release-note]

== Version 1.26.0
_April 20th, 2021_

:warning_message: pass:normal[Lots of changes ahead! Read carefully to see how this release may affect you. \
{nbsp} + \
{nbsp} + \
*Two Factor APIs* \
{nbsp} + \
Breaking changes. If you use this functionality, please review the API changes and test before upgrading. \
{nbsp} + \
{nbsp} + \
The Two-Factor API, two-factor fields on the User and Import User APIs and the Integrations API have changed and are not backwards compatible. If you use this functionality, please review the API changes and test before upgrading. \
{nbsp} + \
{nbsp} + \
*Upgrading from < 1.7.0* \
{nbsp} + \
If you are upgrading from a version less than 1.7.0, you must do a two stage upgrade. Upgrade to a version greater than or equal to 1.7.0 but less than 1.26.0, then upgrade from that version to 1.26.0. There were internal migration changes which necessitate this two stage process. \
{nbsp} + \
{nbsp} + \
*Accessing the admin Login after upgrading:* \
{nbsp} + \
The `/` path of FusionAuth no longer automatically forwards to the admin login. To access the Admin UI to complete this configuration append `/admin/` to the URL. Once the theme configuration is complete, this root page will contain links to login and instructions on how to utilize this root landing page.]
include::docs/v1/tech/__general-migration-warning.adoc[]

include::docs/v1/tech/__database-migration-warning.adoc[]

=== Known Issues
* If you use a non default theme for the FusionAuth default tenant, you may see an error when trying to log in to the admin UI. You can workaround this by appending `?&bypassTheme=true` to your login URL.
** Resolved in 1.26.1, see https://github.com/FusionAuth/fusionauth-issues/issues/1175[GitHub Issue #1175] for additional details.

=== Changed

* The Two-Factor API has changed which allows you to enable and disable Two-Factor methods as well as send codes.
** See the link:/docs/v1/tech/apis/two-factor/[Two-Factor API] for more details.
* The Two-Factor Login API now returns `409` for too many attempts. This allows the Two-Factor Login API to provide the same locking capability as the Login API when too many failed attempts occur.
** See the link:/docs/v1/tech/apis/login/#complete-two-factor-authentication[Two-Factor Login API] for more details.
* The Import API has changed for enabling Two-Factor.
**  See the link:/docs/v1/tech/apis/users/#import-users[User Import API] for changes.
* The User API has changed for enabling and disabling Two-Factor. See the link:/docs/v1/tech/apis/users/[User API] for changes.
** See the link:/docs/v1/tech/apis/users/[User API] for changes.
* Email and SMS Two-Factor methods will now require a paid edition of FusionAuth. link:/pricing/[Learn more about paid editions].
** If you are only using Authenticator/TOTP for Two-Factor, this functionality will continue to work properly in the community edition.
* If you are upgrading from a version less than 1.7.0, you must do a two stage upgrade. Upgrade to a version greater than or equal to 1.7.0 but less than 1.26.0, then upgrade from that version to 1.26.0. There were internal migration changes which necessitate this two stage process.

=== Fixed
* You can now delete a user registration for an inactive application
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1148[GitHub Issue #1148]
* Spurious text '[object Object]' on FusionAuth admin UI screen when certain Chrome extensions present.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/887[GitHub Issue #1151]. Thanks to https://github.com/NikolayMetchev[@NikolayMetchev] for filing this.

=== Tech Preview
* Entity Management/link:https://github.com/FusionAuth/fusionauth-issues/issues/881[GitHub Issue #881].

=== New
* Prometheus Metrics endpoint
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/362[GitHub Issue #362]
* IdP initiated SSO
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/566[GitHub Issue #566]
* An API key to create API keys!
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/887[GitHub Issue #887]. Thanks to https://github.com/Tintwo[@Tintwo] for filing this.
* Portions of https://github.com/FusionAuth/fusionauth-issues/issues/960[GitHub Issue #960] were delivered, including features such as:
** Two-Factor step-up API
** SMS Two-Factor with configurable delivery methods
** Localized Message Templates which can be used for SMS Two-Factor messages
* Self service user profile page
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/682[GitHub Issue #682]
* Themeable root page
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/378[GitHub Issue #378]
* Messengers which are used to send SMS messages through Twilio, Kafka or a generic JSON REST API
* Licensing now supports air-gapped deployments
* Client Credentials grant
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/155[GitHub Issue #155]

=== Enhancements
* Add IP address to login success and failed events.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1162[GitHub Issue #1162]


[role=release-note]

== Version 1.25.0
_March 10th, 2021_


:warning_message: pass:normal[SAML v2 Logout is now fully supported. No action should be required. If you are currently using FusionAuth as a SAML v2 IdP, please verify your configuration as you may want to provide additional configuration to take full advantage of the SAML v2 Logout configuration. The additional of SAML v2 Logout means there is a new themed page to manage the user experience for SAML v2 Logout. Please review your theme to ensure your user experience is not interrupted. See additional details in the New section below.]
include::docs/v1/tech/__general-migration-warning.adoc[]

include::docs/v1/tech/__database-migration-warning.adoc[]

=== Changed
* In support of the SAML v2 Logout feature, the following theme changes have been made.
** New themed template `SAMLv2 logout template`. This template will be rendered when you utilize the SAML v2 Logout feature, it is nearly identical to the existing OAuth2 logout themed page. If you are using themes, please review your theme to ensure your user experience is not interrupted.

=== Fixed
* If you are using Elasticsearch version 6 you may encounter an error when using the Search API. This is due to a change in how we optionally request the document hit count in the search request to Elasticsearch. The change is not compatible with Elasticsearch version 6. As a work around, you can set `accurateTotal=true` in the API request. See the link:/docs/v1/tech/apis/users/#search-for-users[User Search API] for additional details on using this parameter.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1135[GitHub Issue #1135]
* Using the HTTP `PATCH` method on the FusionAuth application may produce erroneous validation errors.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1110[GitHub Issue #1110]
* Adding additional Java options in the configuration file when the value contains a space may not work correctly.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1065[GitHub Issue #1065]
* A `NullPointerException` may occur when you have users registered for an application in a non default tenant and you create a login report for only that application. Thanks to https://github.com/NikolayMetchev[@NikolayMetchev] for filing this.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1115[GitHub Issue #1115]
* When you omit the `state` parameter on the Authorization request, you may receive a `state` parameter on the `redirect_uri` that you did not expect.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1113[GitHub Issue #1113]

=== New
* Add full support for SAML v2 Logout
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1137[GitHub Issue #1137]

=== Enhancements
* Add a button to the Sessions tab in the FusionAuth admin UI to delete all user sessions at once, this action is also available from the drop down action list when managing a user.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1094[GitHub Issue #1094]
* Add Debug to OAuth2 Grants, this will primarily assist in debugging the Authorization Code Grant auth code exchange with the Token endpoint.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/781[GitHub Issue #781]
* Add CORS Debug, this will assist you in debugging CORS related `403` HTTP status codes.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1126[GitHub Issue #1126]
* Better SMTP debug for specific scenarios. This should assist with async connection issues and provide context to the tenant and template being rendered during the exception.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1064[GitHub Issue #1064]
* Allow the Registration API to accept the `applicationId` as a URL segment
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1127[GitHub Issue #1127]
* Twitter IdP Login API can optionally accept an access token. When building your own login page, if you complete the initial step with Twitter and utilize the `oauth_verifier` to perform some initial processing of the Twitter user, you may now still send the access token in the form of `oauth_token` and `oauth_token_secret` to FusionAuth to complete the login. This is done by omitting the `oauth_verifier` on the Login request. See link:/docs/v1/tech/apis/identity-providers/twitter/#complete-the-twitter-login[Complete the Twitter Login] for additional information.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1073[GitHub Issue #1073]
* When Key Master generates a `kid` because one is not provided on the request, if there is a public key, generate the `kid` as a JWK thumbprint instead of a randomly generated value.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1136[GitHub Issue #1136]
* When using the Search feature in the FusionAuth admin UI, once you begin searching using a specific term or any of the advanced controls, the pagination result total will be an accurate representation of the number of matches returned by Elasticsearch. When no search criteria is provided, the number of matches will cap at the default value of 10,000 and the pagination results will indicate 10,000+ which means at least 10,000 users match the search criteria.

=== Internal
* Upgrade Tomcat from version `8.5.57` to `8.5.63`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1119[GitHub Issue #1119]

[role=release-note]

== Version 1.24.0
_February 11th, 2021_

=== Security
* More consistent usage of the `Cache-Control` HTTP response header. The default for all pages will be `Cache-Control: no-cache`, and some pages that may contain potentially sensitive information such as the API key add, edit or index pages will use a `Cache-Control: no-store`. No known vulnerability exists with the previous behavior, this is just a proactive change to limit the possible mis-use of cached pages in the FusionAuth admin UI.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1103[GitHub Issue #1103]
* A vulnerability in an underlying SAML v2 library was resolved. If you are using SAML please upgrade FusionAuth to 1.24.0 or later as soon as possible.
** https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-27736[CVE-2021-27736]
** https://www.compass-security.com/fileadmin/Research/Advisories/2021-03_CSNC-2021-004_FusionAuth_SAML_Library_XML_External_Entity.txt[CSNC-2021-004]

=== Known Issues
* If you are using Elasticsearch version 6 you may encounter an error when using the Search API. This is due to a change in how we optionally request the document hit count in the search request to Elasticsearch. The change is not compatible with Elasticsearch version 6. As a work around, you can set `accurateTotal=true` in the API request.
** Resolved in 1.25.0, see https://github.com/FusionAuth/fusionauth-issues/issues/1135[GitHub Issue #1135] for additional details.

=== Changed

* The `applicationId` and `roles` claims are no longer returned in the `id_token` issued when requesting the `openid` scope. The `id_token` should not be used for authorization, this change makes it less likely to mis-use this token. If you have a requirement for these claims (you shouldn't), you can add them back by using a JWT Populate lambda. See link:/docs/v1/tech/oauth/tokens/#id-token[Id Token claims] for additional information.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1102[GitHub Issue #1102]

=== Fixed
* When using the Add or Edit Identity Provider forms in the admin UI, if you have ~2,000 or more applications it is possible for the form request to be truncated by the underlying application server. This error is caused by the maximum number of request parameters being exceeded. This form in particular, along with the Group Add/Edit and Webhook Add/Edit contains a number of fields that is a function of the number of applications configured. An informational error may be written to the system log indicating this truncation has occurred, but no hard error would have occurred. The symptom will be that depending upon your configuration, a portion of it may be lost during this form submit. The entry in the log will contain this message `org.apache.tomcat.util.http.Parameters.processParameters More than the maximum number of request parameters (GET plus POST) for a single request ([10,000]) were detected. Any parameters beyond this limit have been ignored.`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1057[GitHub Issue #1057]
* When you have registered a custom plugin for password hashing, using the View Tenant dialog may fail to render.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1063[GitHub Issue #1063]
* Unable to remove a User from a Group using the admin UI dialog. This was a regression issue introduced in version 1.23.0.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1081[GitHub Issue #1081]
* If a user was not currently in the Elasticsearch index, the user delete request may fail.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1088[GitHub Issue #1088]
* The JWT returned from the Register API when you are creating a User and a Registration in one request may not contain the `roles` claim. This occurs when you do not assign the roles explicitly on the request, and instead are using default role assignment in the application configuration.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1106[GitHub Issue #1106]
* Updating a User that has existing group memberships may no longer be searchable in Elasticsearch by their Group memberships until the next time the user logs into FusionAuth.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1087[GitHub Issue #1087]
* A Kafka Producer configuration that contains an equals sign `=` in the property value will fail to parse. This was identified in attempting to configure credentials to connect to CloudKarafka.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1107[GitHub Issue #1107], thanks to https://fusionauth.io/community/forum/user/chris-bridges[@chris-bridges] for letting us know!

=== Enhancements
* Support a Kickstart file with only a `licenseId`. Previously at least one API key was required because the intent of Kickstart is to call one or more APIs. While there is not a very practical use case for only providing a `licenseId` and no API requests,  this minimal configuration will no longer fail indicating an API key is required. See link:/docs/v1/tech/installation-guide/kickstart/#set-your-license-id[Set your License Id] in the link:/docs/v1/tech/installation-guide/kickstart/[Kickstart] documentation.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1080[GitHub Issue #1080]
* You may now import an RSA certificate with a key bit length less than `2048` into Key Master. The minimum supported RSA key length for signing a JWT is `2048`, so this was previously the minimum requirement to import anything into Key Master. However, we have several configurations now that require a certificate that is only used to verify a signature from a third party. In these cases, we are not using the certificate to sign anything, and https://github.com/trevorr[@trevorr] rightly pointed out that we should allow smaller keys to be imported to support these use cases. Thank you for the (now obvious) insight! We really appreciate our community members that provide us value for value.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1085[GitHub Issue #1085] & https://github.com/FusionAuth/fusionauth-issues/issues/1091[GitHub Issue #1091]
* Added an additional Search API parameter to allow you to obtain the actual hit count from Elasticsearch. For performance reasons, the default behavior of an Elasticsearch query is to limit the hit count to 10,000. This means that if your query matched more than 10,000 records, the API response will only indicate that at least 10,000 records matched. This is very adequate for pagination purposes, or general queries. There are times where you are building a very specific query and the intent is to identify an accurate number of matching records. You may now provide an additional parameter to the search request named `accurateTotal` which will then return an accurate hit count on the API response. See the link:/docs/v1/tech/apis/users/#search-for-users[User Search API] for additional details.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1086[GitHub Issue #1086]
* Allow the user to click on the Enabled column in the Webhook event configuration in the Webhook and Tenant configurations to enable or disable all events at once. This is just a usability enhancement to save you from clicking over and over. You're welcome.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1093[GitHub Issue #1093]
* For pages with potentially a lot of items such as Applications, Tenants, etc - that do not currently have pagination, add a count at the bottom of the panel. This allows you to look smart by knowing how many "things" you have without having to count them yourself.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1104[GitHub Issue #1104]

=== Internal
* Some enhancements to JavaScript event handlers to perform better on pages with 2-3k+ applications. Pretty boring.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1105[GitHub Issue #1105]

[role=release-note]

== Version 1.23.3
_January 21th, 2021_

=== Fixed
* A tenant delete request may fail. See details in the linked GH issue for a work around. This issue was introduced in version 1.22.0.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1075[GitHub Issue #1075]

[role=release-note]

== Version 1.23.2
_January 20th, 2021_

=== Fixed
* A bug in the PostgreSQL migration will cause you to lose your SAML v2 IdP configuration. If you are using MySQL or you are not using the SAML v2 IdP configuration, this bug will not affect you. The issue was introduced in version 1.21.0, so if you are upgrading from a version prior to 1.21.0 to 1.23.2 you will not be affected. If you have already upgraded to 1.21.0 or any version greater than 1.21.0 prior to this patch, you will have already encountered the issue. If you do encounter this issue, you will need to update the SAML v2 IdP configuration found in each affected Application configuration.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1074[GitHub Issue #1074]

[role=release-note]

== Version 1.23.1
_January 13th, 2021_

=== Fixed
* When configured to sign the SAML v2 AuthN requests to the SAML v2 IdP, the SAML v2 SP metadata does not correctly reflect this settings. The attribute `AuthnRequestsSigned` should now reflect the signing configuration.
** When configured to sign requests, the SP metadata response will now also contain the KeyDescriptor element to describe the X.509 certificate used to verify the signature.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1067[GitHub Issue #1067]


== Version 1.23.0
_January 11th, 2021_

include::docs/v1/tech/__database-migration-warning.adoc[]

=== Known Issues
* If you are upgrading to this version, are using PostgreSQL, and you intend to use the provided LinkedIn Reconcile lambda, you will need to make a small adjustment prior to using it.
** Navigate to [breadcrumb]#Customizations -> Lambdas# and edit the lambda named `Default LinkedIn Reconcile provided by FusionAuth` and click edit. You will see an error indicated by a red dot on line `23` of the function body. To fix this error, delete the two empty lines between the end of line `23` and `25`, once the error indicator is gone, save the lambda.
* Unable to remove a User from a group using the Admin UI dialog.
** Fixed in version 1.24.0 via https://github.com/FusionAuth/fusionauth-issues/issues/1081[GitHub Issue #1081]


=== Fixed
* A validation error may not be visible when selecting self service registration options when the FusionAuth license has not been activated.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/951[GitHub Issue #951]
* The User Action API was returning a `200` status code instead of a `404` when requesting an action by Id that did not exist.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/991[GitHub Issue #991], thanks to https://github.com/hkolbeck-streem[@hkolbeck-streem] for the report!
* The IP address shown on the About panel may be the same for each node when viewed on a multi-node FusionAuth instance. This address is shown for informational purposes and was only a cosmetic defect w/out any functional issues.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1030[GitHub Issue #1030]
* The SAML Response XML was failing XSD validation for the `Signature` element location when the request was not successful, or FusionAuth was configured to sign the response instead of the assertion.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1047[GitHub Issue #1047], thanks to https://github.com/MrChrisRodriguez[@MrChrisRodriguez] for the excellent report!
* Fix a possible NPE when making an Update request to a group in a multi-tenant environment. With this fix, the correct API response will be returned.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1052[GitHub Issue #1052], thanks to https://github.com/atrauzzi[@atrauzzi] for the report!
* When creating an IdP from the API for Google, Facebook, Twitter, or HYPR - the API was allowing an Id to be provided. Each of these IdP types of which only one are allowed, have a fixed Id that is managed by FusionAuth. The API should ignore the requested Id and set the correct Id instead. If you encounter this issue, the work around is to omit the Id on the API request.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1058[GitHub Issue #1058]
* Kickstart fails when using a variable in the `tenantId` field for an API key.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1060[GitHub Issue #1060], thanks to https://github.com/rhofland[@rhofland] for the report and the excellent recreate steps!

=== New
* Sign in with LinkedIn. A new identity provider type is available for LinkedIn.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/34[GitHub Issue #34]
* New FusionAuth roles oriented for Level 1 support personnel. These new roles are named `user_support_viewer` and `user_support_manager`, see FusionAuth application roles for additional detail.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1027[GitHub Issue #1027]

=== Enhancements
* Updates to the User and Import API to provide validation on the length of an email address. This will provide a developer a better error when the provided email address is too long.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/900[GitHub Issue #900]

=== Client libraries
* Enhancements to the .NET Core client library to better support requests in a multi-tenant environment and to use the `IDictionary` reference instead of `Dictionary`.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/1049[GitHub Issue #1049] and https://github.com/FusionAuth/fusionauth-issues/issues/1050[GitHub Issue #1050], thanks to https://github.com/atrauzzi[@atrauzzi] for sharing his .NET Core expertise!


++++
<script>
var options = '';
var elements = document.querySelectorAll('section.release-note h2');
for (var i = 0; i < elements.length; i++) {
  var element = elements[i];
  options += '<option value="' + element.id + '">' + element.innerHTML.trim() + '</option>\n';
}

var select = document.getElementById('release-notes-version');
select.insertAdjacentHTML('beforeend', options);
select.addEventListener('change', function() {
  window.location.hash = select.options[select.selectedIndex].value;
});
</script>
++++
