@startuml
  !include ../../_config.plantuml

participant "User" as u
participant "FusionAuth" as f
participant "API Gateway" as ag
participant "Service A" as sa
participant "Service B" as sb

u -> ag : Requests Service A
ag -> ag : Token validation failure\n(it doesn't exist)
ag -> u  : Sends redirect to FusionAuth
u -> f  : Authenticates
f -> f  : Verifies credentials
f -> u : Issues token
u -> ag : Requests Service A and presents token
ag -> ag : Validates token 
ag -> sa : Forwards request for Service A
sa -> ag : Data from Service A
ag -> u : Data
u -> ag : Requests Service B and presents token
ag -> ag : Validates token 
ag -> sb : Forwards request for Service B
sb -> ag : Data
ag -> u : Data from Service B

@enduml
