@startuml
  !include ../../_config.plantuml

participant "User/Browser" as User
participant App
participant FusionAuth
participant "api.example.com" as API1

  == ... Get The Token From FusionAuth ... ==
App -> User : Send Tokens As HTTPOnly, Secure Cookies\nWith a Domain of example.com
User -> API1 : Send Tokens With Request
API1 -> API1 : Validate Tokens
API1 -> User : Send Data or Complete Requested Operation
User -> API1 : Send Tokens With Request
API1 -> API1 : Validate Tokens\nToken Invalid
API1 -> User : Sends Access Denied Message
User -> FusionAuth: Present Refresh Token
FusionAuth -> FusionAuth : Validate Refresh Token
FusionAuth -> User : Present New Access Token
User -> API1 : Send Tokens With Request
API1 -> API1 : Validate Tokens
API1 -> User : Send Data or Complete Requested Operation
@enduml
