@startuml
  !include ../../_config.plantuml

participant "User/Browser" as User
participant App
participant FusionAuth
participant "proxy.example.com" as Proxy
participant "api.example.com" as API1
participant "todos.com" as API2
User -> App : View Initial Page\nClick Login
App -> User : Redirect User To FusionAuth
User -> FusionAuth : Request Login Page
FusionAuth -> User : Return Login Page
User -> FusionAuth : Provides Credentials
FusionAuth -> User : Redirect With Authorization Code 
User -> App : Request Redirect URI
App -> FusionAuth : Request Tokens
FusionAuth -> App : Return Tokens
App -> User : Send Tokens As HTTPOnly, Secure Cookies\nWith a Domain of example.com
User -> API1 : Send Tokens With Request
API1 -> API1 : Validate Tokens
API1 -> User : Send Data or Complete Requested Operation
User -> Proxy : Send Tokens With Request
Proxy -> Proxy : Validate Tokens
Proxy -> API2 : Send Tokens With Request
API2 -> API2 : Validate Tokens
API2 -> Proxy : Send Data or Complete Requested Operation
Proxy -> User : Send Data or Complete Requested Operation
@enduml
