@startuml
  !include ../../_config.plantuml

participant "User/Browser" as User
User -> App : View Initial Page\nClick Login
App -> User : Redirect User To FusionAuth
User -> FusionAuth : Request Login Page
FusionAuth -> User : Return Login Page
User -> FusionAuth : Provides Credentials
FusionAuth -> User : Redirect With Authorization Code 
User -> App : Request Redirect URI
App -> FusionAuth : Request Tokens
FusionAuth -> App : Return Tokens
@enduml
