@startuml
  !include ../../_config.plantuml

participant "User/Browser" as User
participant App
participant FusionAuth

  == ... Proceed Through Authorization Code Grant ... ==
FusionAuth -> App : Return Tokens
App -> App : Store Tokens in Session
App -> User : Return Session Cookie
User -> App : Session Based Interactions
App -> User : Data/HTML/JSON
@enduml
