@startuml
  !include ../../_config.plantuml

participant "User/Browser" as User
participant "api.example.com" as API1
participant "contacts.example.com" as API2

  == ... Tokens Have Been Stored In Cookies ... ==
User -> API1 : Send Tokens As Cookies With Request
API1 -> API1 : Validate Tokens
API1 -> User : Send Data or Complete Requested Operation
User -> API2 : Send Tokens As Cookies With Request
API2 -> API2 : Validate Tokens
API2 -> User : Send Data or Complete Requested Operation
User -> API1 : Send Tokens As Cookies\nWith Different Request
API1 -> API1 : Validate Tokens
API1 -> User : Send Data or Complete Requested Operation
@enduml
