@startuml
  !include ../../../../_config.plantuml

actor "User/Browser" as user
'participant "New Auth System" as newauth
'participant "New Auth Datastore" as newauthds
participant "Old Auth System" as oldauth
participant "Old Auth Datastore" as oldauthds
user -> oldauth : Provide credentials
oldauth -> oldauthds : Verify credentials
oldauthds -> oldauth : User data
oldauth -> user : Authentication complete
@enduml
