@startuml
  !include ../../../../_config.plantuml

participant "Migration process" as migrator
participant "New Auth Datastore" as newauthds
participant "Old Auth Datastore" as oldauthds
migrator -> oldauthds : User data, please
oldauthds -> migrator : Here's all the user data
migrator -> migrator : Transform, clean, verify user data
migrator -> newauthds : Here's all the user data
@enduml
