---
layout: doc
title: SAML v2 Reconcile lambda
description: An overview of the SAML v2 Response Reconcile lambda
---

:sectnumlevels: 0

== SAML v2 Reconcile lambda

When to use a SAML v2 Reconcile lambda...

When you create a new lambda using the FusionAuth UI we will provide you an empty function for you to implement. If you are using the API to create the lambda you will need to ensure your function has the following signature:

[source,javascript]
----
function reconcile(user, registration, samlResponse) {
  // Lambda code goes here
}
----

This lambda must contain a function named `reconcile` that takes three parameters. The parameters that the lambda is passed are:

* `user` - the FusionAuth User object
* `registration` - the FusionAuth UserRegistration object
* `samlResponse` - the SAML v2 response

The two FusionAuth objects are well documented here in the link:../apis/users[User API] and link:../apis/registrations[Registration API] documentation. The SAML v2 response ....


== Example lambda

Here is an example of a simple Lambda that...

[source,javascript]
----
function reconcile(user, registration, samlResponse) {


  // Create an event log of type 'Debug' when the lambda has Debug enabled
  console.debug('FusionAuth reconciled a User from a SAML v2 IdP and I helped!');
}
----
