== Stolen refresh token ==
Hacker->Store : GET /api/load-shopping-cart\n(Refresh token and JWT)
Store->FusionAuth : POST /oauth2/token or POST /api/jwt/refresh\n(grant_type=refresh and refresh token)
FusionAuth->Store : (JWT)
Store->Hacker : (Shopping cart contents and new JWT)
