matrix:
- name: Markdown
  sources:
  - '_site/**/*.html|!_site/*at89us2r9qj7kyvrfuntpsp524fe5m*'
  default_encoding: utf-8
  spellchecker: hunspell
  dictionary:
    encoding: utf-8
    wordlists:
    - .github/knownwords.txt
  pipeline:
  - pyspelling.filters.url:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
