#!/bin/sh
set -e

cd $(dirname "$0")

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "Usage: $0 [command]"
    echo "Tool to help building and running containers to compile (default action) or serve the website"
    echo "Commands:"
    echo "  -h, --help  Display this help and exit"
    echo "  --recreate  Rebuild docker image"
    echo "  --serve     Serve the website instead of building it"
    exit
fi

IMAGE_NAME="fusionauth-site:latest"
RUBY_CACHE_VOLUME_NAME="fusionauth-site-ruby"
SAVANT_CACHE_VOLUME_NAME="fusionauth-site-savant"

# Building docker image
if [ "$1" = "--recreate" ] || [ "$(docker images -q "${IMAGE_NAME}" 2> /dev/null)" = "" ]; then
    docker build -t "${IMAGE_NAME}" .
    if [ "$1" = "--recreate" ]; then
        shift
    fi
fi

# Default command is "sb compile" from the image
COMMAND=""
if [ "$1" = "--serve" ]; then
    echo "Will serve at http://localhost:4000/"
    COMMAND="sb serve"
fi

docker run --rm \
    -v "${PWD}:/srv/jekyll" \
    -v "${RUBY_CACHE_VOLUME_NAME}:/usr/local/bundle" \
    -v "${SAVANT_CACHE_VOLUME_NAME}:/root/.savant" \
    -p "4000:4000" -it \
    "${IMAGE_NAME}" $COMMAND
