---
layout: doc
title: Passwordless
description: An overview of the passwordless capabilities of FusionAuth
navcategory: login-methods
---

== Overview

Passwordless authentication refers to any method where users to not need to provide a password to authenticate.

These methods have user interface benefits and can help decrease friction for users looking to login. No more passwords to remember, or, worse, to forget.

== Magic Link

Instead of asking your users to remember a password, with a magic link, you send an email, text message, or other communication to the user. Possession of the message proves their identity and authenticates them.

Learn how to implement link:/docs/v1/tech/passwordless/magic-link[magic links with FusionAuth].

== WebAuthn Passkeys

Instead of forcing users to remember a password, with WebAuthn passkeys, they can use strong biometric means of authentication. Using a standard protocol called WebAuthn, web and mobile applications can leverage devices such as phones or YubiKeys to authenticate a user.

Learn how to implement link:/docs/v1/tech/passwordless/webauthn-passkeys[WebAuthn passkeys with FusionAuth].

