Because SCIM schemas are completely customizable, The SCIM response returned is generated from the result of SCIM Group object populated by your outgoing response lambda.

<TODO: insert link to outgoing Group response lambda doc>

The following is an example of a typical SCIM Group response body that your SCIM client might expect. However, your outgoing response lambda could generate a completely different SCIM schema is desired.

This is taken from the SCIM Schema RFC describing a SCIM Group schema. For the full specification you can find the RFC here:

- https://datatracker.ietf.org/doc/html/rfc7643#section-4.2

==== Response Body
[.api]
[field]#active# [type]#[Boolean]# [required]#Required#::
The state of the SCIM Resource. Typically just mapped from the FusionAuth Group.active property.

[field]#schemas# [type]#[Array]# [required]#Required#::
The String identifier of the SCIM Resource schemas and extensions provided in the response. This should match supported schemas and extensions you specified in your schemas endpoint response.
<TODO: link to explanation of SCIM schemas and/or discovery endpoints.>

[field]#id# [type]#[String]# [required]#Required#::
The uniwue id of the SCIM resource on the SCIM provisioning server. This should be populated from the Group.id property by the outgoing response lambda in order for the SCIM client to pass the correct value to the FusionAuth SCIM endpoint when querying a Group by id.

[field]#externalId# [type]#[String]# [optional]#Optional#::
The externalId specified by the SCIM client when the Group was created. It could be the FusionAuth resource id as well, but that is not a requirement of the SCIM specification. That would need to be handled by the defined outgoing response lambda if desired and stored by the incoming request lambda.

    <TODO: do we need a document explaining the concept of external ids and how to manage them?>

[source,json]
.Example Request JSON
----
include::../../../../src/json/scim/group-create-response.json[]
----
