Because SCIM schemas are completely customizable, The SCIM response returned is generated from the result of a SCIM Group object populated by your outgoing response lambda.

The following is an example of a typical SCIM Group response body that a SCIM client might expect. However, your outgoing response lambda could generate a completely different SCIM schema if desired.

This is taken from the SCIM Schema RFC describing a SCIM Group schema. For the full specification you can find the RFC link:https://datatracker.ietf.org/doc/html/rfc7643#section-4.2[here].

==== Response Body
[.api]
include::/docs/v1/tech/apis/scim/_scim-common-body.adoc[]

[field]#meta.resourceType# [type]#[String]#::
The SCIM resource type defined by this schema.

[field]#meta.created# [type]#[String]#::
The date and time that the Group was created.

[field]#meta.lastModified# [type]#[String]#::
The date and time that the Group was last modified.

[field]#meta.location# [type]#[String]#::
The URI that can be used to retrieve data about the Group.

[field]#displayName# [type]#[String]#::
The text that could be used to represent this Group in lists, etc.

[field]#members# [type]#[Array]#::
This list of members included in this Group.

[field]#member.displayName# [type]#[String]#::

[field]#meta.$ref# [type]#[String]#::
The URI that can be used to retrieve data about the Group member.

[field]#meta.value# [type]#[String]#::
The unique id of the Group member.

[source,json]
.Example Response JSON
----
include::/docs/src/json/scim/group-create-response.json[]
----
