Because SCIM schemas are completely customizable, The SCIM response returned is generated from the result of SCIM User object populated by your outgoing response lambda.

<TODO: insert link to outgoing user response lambda doc>

The following is an example of a typical SCIM User response body that your SCIM client might expect. However, your outgoing response lambda could generate a completely different SCIM schema is desired.

This is taken from the SCIM Schema RFC describing a SCIM User schema. For the full specification you can find the RFC here:

- https://datatracker.ietf.org/doc/html/rfc7643#page-19

==== Request Body
[.api]
[field]#active# [type]#[Boolean]# [required]#Required#::
The state of the SCIM Resource.

[field]#schemas# [type]#[Array]# [required]#Required#::
The String identifier of the SCIM Resource schemas and extensions provided in the request. This should match supported schemas and extensions for the provisioning server.

    <TODO: link to explanation of SCIM schemas and/or discovery endpoints.>

[field]#externalId# [type]#[String]# [optional]#Optional#::
The externalId is a unique identifier created by the client that identifies the resource in the SCIM client's environment. It could be used as the FusionAuth resource id as well, but that is not a requirement of the SCIM specification. That would need to be done by the defined incoming lambda if desired.

[field]#name.formatted# [type]#[String]# [optional]#Optional#::
his would typically be the value used to populate the FusionAuth User.fullName by the incoming request lambda.

[field]#name.familyName# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.lastName by the outgoing response lambda.

[field]#name.givenName# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.firstName by the outgoing response lambda.

[field]#name.middleName# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.middleName by the outgoing response lambda.

[field]#name.honorificPrefix# [type]#[String]# [optional]#Optional#::
A FusionAuth User doesn't typically have this data, but you might store it in user.data for example and the retrieve it in the outgoing response lambda

[field]#name.honorificSuffix# [type]#[UUID]# [optional]#Optional#::
A FusionAuth User doesn't typically have this data, but you might store it in user.data for example and the retrieve it in the outgoing response lambda

[field]#userName# [type]#[String]# [optional]#Optional#::
This would typically be the value used to populate the FusionAuth User.userName by the incoming request lambda.

[field]#phoneNumbers# [type]#[Array]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.mobilePhone by the outgoing response lambda.

[field]#phoneNumbers[x].primary# [type]#[Boolean]# [optional]#Optional#::
This would typically be always true because FusionAuth typically only stores a single phone number.

[field]#phoneNumbers[x].value# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.mobilePhone by the outgoing response lambda.

[field]#phoneNumbers[x].type# [type]#[String]# [optional]#Optional#::
This would typically be always mobile because FusionAuth typically only stores a single phone number in User.mobilePhone.

[field]#emails# [type]#[Array]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.email by the outgoing response lambda.

[field]#emails[x].primary# [type]#[Boolean]# [optional]#Optional#::
This would typically be always true because FusionAuth typically only stores a single email address.

[field]#emails[x].value# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.email by the outgoing response lambda.

[field]#emails[x].type# [type]#[String]# [optional]#Optional#::
This would typically be always a single value of your choosing because FusionAuth only stores a single email address.

[source,json]
.Example Request JSON
----
include::../../../../src/json/scim/enterpriseuser-create-response.json[]
----
