Because SCIM schemas are completely customizable, The SCIM response returned is generated from the result of SCIM User object populated by your outgoing response lambda.

The following is an example of a typical SCIM User response body that a SCIM client might expect. However, your outgoing response lambda could generate a completely different SCIM schema is desired.

This is taken from the SCIM Schema RFC describing a SCIM User schema. For the full specification you can find the RFC link:https://datatracker.ietf.org/doc/html/rfc7643#section-4.3[here].

==== Response Body
[.api]
include::/docs/v1/tech/apis/scim/_scim-common-body.adoc[]

[field]#urn:ietf:params:scim:schemas:extension:enterprise:2.0:User# [type]#[String]# [optional]#Required#::
This is the root property of the EnterpriseUser schema extension. It should match the identifier included in the schemas property.

[field]#urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.employeeNumber# [type]#[String]# [optional]#Optional#::
A string identifier, typically numeric or alphanumeric, assigned to a person, typically based on order of hire or association with an organization.

[field]#urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.costCenter# [type]#[String]# [optional]#Optional#::
Identifies the name of a cost center.

[field]#urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.organization# [type]#[String]# [optional]#Optional#::
Identifies the name of an organization.

[field]#urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.division# [type]#[String]# [optional]#Optional#::
Identifies the name of a division.

[field]#urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.department# [type]#[String]# [optional]#Optional#::
Identifies the name of a department.

[field]#urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.manager# [type]#[String]# [optional]#Optional#::
The user's manager.  A complex type that optionally allows service providers to represent organizational hierarchy by referencing the "id" attribute of another User.

[field]#urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.manager.value# [type]#[String]# [optional]#Optional#::
The "id" of the SCIM resource representing the user's manager

[field]#urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.manager.$ref# [type]#[String]# [optional]#Optional#::
The URI of the SCIM resource representing the User's manager.

[field]#urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.manager.displayName# [type]#[String]# [optional]#Optional#::
The displayName of the user's manager.

[source,json]
.Example Response JSON
----
include::/docs/src/json/scim/enterpriseuser-create-response.json[]
----
