Because SCIM schemas are completely customizable, The SCIM response returned is generated from the result of SCIM User object populated by your outgoing response lambda.

<TODO: insert link to outgoing user response lambda doc>

The following is an example of a typical SCIM User response body that your SCIM client might expect. However, your outgoing response lambda could generate a completely different SCIM schema is desired.

This is taken from the SCIM Schema RFC describing a SCIM User schema. For the full specification you can find the RFC here:

- https://datatracker.ietf.org/doc/html/rfc7643#page-19

==== Response Body
[.api]
[field]#active# [type]#[Boolean]# [required]#Required#::
The state of the SCIM Resource. Typically just mapped from the FusionAuth User.active property.

[field]#schemas# [type]#[Array]# [required]#Required#::
The String identifier of the SCIM Resource schemas and extensions provided in the response. This should match supported schemas and extensions you specified in your schemas endpoint response.
<TODO: link to explanation of SCIM schemas and/or discovery endpoints.>

[field]#id# [type]#[String]# [required]#Required#::
The uniwue id of the SCIM resource on the SCIM provisioning server. This should be populated from the User.id property by the outgoing response lambda in order for the SCIM client to pass the correct value to the FusionAuth SCIM endpoint when querying a User by id.

[field]#externalId# [type]#[String]# [optional]#Optional#::
The externalId specified by the SCIM client when the User was created. It could be the FusionAuth resource id as well, but that is not a requirement of the SCIM specification. That would need to be handled by the defined outgoing response lambda if desired and stored by the incoming request lambda.

<TODO: do we need a document explaining the concept of external ids and how to manage them?>

[field]#name.formatted# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.fullName by the outgoing response lambda.

[field]#name.familyName# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.lastName by the outgoing response lambda.

[field]#name.givenName# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.firstName by the outgoing response lambda.

[field]#name.middleName# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.middleName by the outgoing response lambda.

[field]#name.honorificPrefix# [type]#[String]# [optional]#Optional#::
A FusionAuth User doesn't typically have this data, but you might store it in user.data for example and the retrieve it in the outgoing response lambda

[field]#name.honorificSuffix# [type]#[UUID]# [optional]#Optional#::
A FusionAuth User doesn't typically have this data, but you might store it in user.data for example and the retrieve it in the outgoing response lambda

[field]#userName# [type]#[String]# [optional]#Optional#::
This would typically be the value used to populate the FusionAuth User.userName by the incoming request lambda.

[field]#phoneNumbers# [type]#[Array]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.mobilePhone by the outgoing response lambda.

[field]#phoneNumbers[x].primary# [type]#[Boolean]# [optional]#Optional#::
This would typically be always true because FusionAuth typically only stores a single phone number.

[field]#phoneNumbers[x].value# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.mobilePhone by the outgoing response lambda.

[field]#phoneNumbers[x].type# [type]#[String]# [optional]#Optional#::
This would typically be always mobile because FusionAuth typically only stores a single phone number in User.mobilePhone.

[field]#emails# [type]#[Array]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.email by the outgoing response lambda.

[field]#emails[x].primary# [type]#[Boolean]# [optional]#Optional#::
This would typically be always true because FusionAuth typically only stores a single email address.

[field]#emails[x].value# [type]#[String]# [optional]#Optional#::
This would typically be populated from the FusionAuth User.email by the outgoing response lambda.

[field]#emails[x].type# [type]#[String]# [optional]#Optional#::
This would typically be always a single value of your choosing because FusionAuth only stores a single email address.

[source,json]
.Example Request JSON
----
include::../../../../src/json/scim/user-create-response.json[]
----
