Because SCIM schemas are completely customizable, The SCIM response returned is generated from the result of SCIM Group object populated by your outgoing response lambda.

The following is an example of a typical SCIM Group response body that your SCIM client might expect. However, your outgoing response lambda could generate a completely different SCIM schema is desired.

This is taken from the SCIM Schema RFC describing a SCIM Group schema. For the full specification you can find the RFC here:

- https://datatracker.ietf.org/doc/html/rfc7643#section-4.2

==== Response Body
[.api]
[field]#active# [type]#[Boolean]#::
The state of the SCIM Resource. Typically just mapped from the FusionAuth Group.active property.

[field]#schemas# [type]#[Array]#::
The String identifier of the SCIM Resource schemas and extensions provided in the response. This should match supported schemas and extensions you specified in your schemas endpoint response.

[field]#id# [type]#[String]#::
The unique id of the SCIM resource on the SCIM provisioning server. This should be populated from the Group.id property by the outgoing response lambda in order for the SCIM client to pass the correct value to the FusionAuth SCIM endpoint when querying a Group by id.

[field]#externalId# [type]#[String]#::
The externalId specified by the SCIM client when the Group was created. It could be the FusionAuth resource id as well, but that is not a requirement of the SCIM specification. That would need to be handled by the defined outgoing response lambda if desired and stored by the incoming request lambda.

[field]#meta.resourceType# [type]#[String]#::
The SCIM resource type defined by this schema.

[field]#meta.created# [type]#[String]#::
The date and time that the Group was created.

[field]#meta.lastModified# [type]#[String]#::
The date and time that the Group was last modified.

[field]#meta.location# [type]#[String]#::
The URI that can be used to retrieve data about the Group.

[field]#displayName# [type]#[String]#::
The text that could be used to represent this Group in lists, etc.

[field]#members# [type]#[Array]#::
This list of members included in this Group.

[field]#member.displayName# [type]#[String]#::

[field]#meta.$ref# [type]#[String]#::
The URI that can be used to retrieve data about the Group member.

[field]#meta.value# [type]#[String]#::
The unique id of the Group member.

[source,json]
.Example Response JSON
----
include::/docs/src/json/scim/group-create-response.json[]
----
