Because SCIM schemas are completely customizable, there are no required fields for the incoming request other than the common fields that all SCIM requests must include to match the specification. The only requirement about the user data is that in the incoming request lambda, you must specify either the **email** or the **username** or both for the FusionAuth User object. Either of these values may be used to uniquely identify the User and may be used to authenticate the User. Otherwise, it is completely up to your defined lambda to match any other incoming user data to the appropriate FusionAuth User fields for your configuration.

The following is an example of a typical SCIM User create request body your SCIM client might send. However, your incoming request lambda could use these values in completely different ways to populate the FusionAuth User object if you choose.

This is taken from the SCIM Schema RFC describing a SCIM User schema. For the full specification you can find the RFC here:

- https://datatracker.ietf.org/doc/html/rfc7643#page-19

==== Request Body
[.api]
[field]#active# [type]#[Boolean]# [required]#Required#::
The state of the SCIM Resource.

[field]#schemas# [type]#[Array]# [required]#Required#::
The String identifier of the SCIM Resource schemas and extensions provided in the request. This should match supported schemas and extensions for the provisioning server.

[field]#externalId# [type]#[String]# [optional]#Optional#::
The externalId is a unique identifier created by the client that identifies the resource in the SCIM client's environment. It could be used as the FusionAuth resource id as well, but that is not a requirement of the SCIM specification. That would need to be done by the defined incoming lambda if desired.

[field]#name.formatted# [type]#[String]# [optional]#Optional#::
This would typically be the value used to populate the FusionAuth User.fullName by the incoming request lambda.

[field]#name.familyName# [type]#[String]# [optional]#Optional#::
This would typically be the value used to populate the FusionAuth User.lastName by the incoming request lambda.

[field]#name.givenName# [type]#[String]# [optional]#Optional#::
This would typically be the value used to populate the FusionAuth User.firstName by the incoming request lambda.

[field]#name.middleName# [type]#[String]# [optional]#Optional#::
This would typically be the value used to populate the FusionAuth User.middleName by the incoming request lambda.

[field]#name.honorificPrefix# [type]#[String]# [optional]#Optional#::
A prefix to be applied to the User's full name.

[field]#name.honorificSuffix# [type]#[UUID]# [optional]#Optional#::
A suffix to be applied to the User's full name.

[field]#userName# [type]#[String]# [optional]#Optional#::
This would typically be the value used to populate the FusionAuth User.userName by the incoming request lambda.

[field]#password# [type]#[String]# [optional]#Optional#::
This would typically be the value used to populate The FusionAuth User.password by the incoming request lambda.

[field]#phoneNumbers# [type]#[Array]# [optional]#Optional#::
SCIM supports multiple phone numbers while FusionAuth only allows a single phone number for a User. The incoming request lambda would need to determine which one to use if multiple are specified. The most common strategy would be to just use the one where primary is true.

[field]#phoneNumbers[x].primary# [type]#[Boolean]# [optional]#Optional#::
Indicates that this phone number is the User's primary phone number.

[field]#phoneNumbers[x].value# [type]#[String]# [optional]#Optional#::
This would typically be used to populate the FusionAuth User.mobilePhone by the incoming request lambda.

[field]#phoneNumbers[x].type# [type]#[String]# [optional]#Optional#::
This might be used to alternatively choose a value to decide which phone number to use to populate the FusionAuth User.mobilePhone by the incoming request lambda.

[field]#emails# [type]#[Array]# [optional]#Optional#::
SCIM supports multiple email addresses while FusionAuth only allows a email address for a User. The incoming request lambda would need to determine which one to use if multiple are specified. The most common strategy would be to just use the one where primary is true.

[field]#emails[x].primary# [type]#[Boolean]# [optional]#Optional#::
Indicates that this phone number is the User's primary email address.

[field]#emails[x].value# [type]#[String]# [optional]#Optional#::
This would typically be used to populate the FusionAuth User.email by the incoming request lambda.

[field]#emails[x].type# [type]#[String]# [optional]#Optional#::
This might be used to alternatively choose a value to decide which email address to use to populate the FusionAuth User.email by the incoming request lambda.

[source,json]
.Example Request JSON
----
include::/docs/src/json/scim/user-create-request.json[]
----
