---
layout: doc
title: SCIM API Overview
description: APIs for provisioning SCIM Resources in FusionAuth using your SCIM Client
---

== SCIM API Overview

This page contains all of the APIs for managing Users and Groups using SCIM requests. See our link:/docs/v1/tech/core-concepts/scim[overview] of FusionAuth's support for the SCIM specification for more details.

FusionAuth supported SCIM Resource API endpoints

* link:/docs/v1/tech/apis/scim/SCIMUser[SCIM User]
* link:/docs/v1/tech/apis/scim/SCIMEnterpriseUser[SCIM EnterpriseUser]
* link:/docs/v1/tech/apis/scim/SCIMGroup[SCIM Group]

FusionAuth also supports the SCIM service provider discovery endpoints per the specifiction

* link:/docs/v1/tech/apis/scim/SCIMServiceProvider[SCIM Service Provider]

== Authentication

In order to use the authenticated FusionAuth SCIM API endpoints, you must create a SCIM client entity and execute the client credentials authorization workflow.

== SCIM Error Responses

All error responses from From FusionAuth SCIM API endpoints will be returned in SCIM compliant schem as defined here.

- https://datatracker.ietf.org/doc/html/rfc7644#section-3.12

[source,json]
.Example SCIM error response JSON
----
include::../../../../src/json/scim/scim-error-response.json[]
----

In addition, FusionAuth will append additional error data when available with a SCIM schema extension.

[source,json]
.Example SCIM Error Response JSON with FusionAuth custom extension schema
----
include::../../../../src/json/scim/scim-extended-error-response.json[]
----
