---
layout: doc
title: SCIM Server API Overview
description: APIs for provisioning SCIM Resources in FusionAuth using a SCIM Client
---

== SCIM API Overview

[NOTE.since]
====
This API has been available since 1.36.0
====

This page contains all of the APIs for managing Users and Groups using SCIM requests. See our link:/docs/v1/tech/core-concepts/scim[overview] of FusionAuth's support for the SCIM specification for more details.

FusionAuth supported SCIM Resource API endpoints

* link:/docs/v1/tech/apis/scim/SCIMUser[SCIM User]
* link:/docs/v1/tech/apis/scim/SCIMEnterpriseUser[SCIM EnterpriseUser]
* link:/docs/v1/tech/apis/scim/SCIMGroup[SCIM Group]

== Authentication

In order to use the authenticated FusionAuth SCIM API endpoints, you must create a SCIM client entity and execute the link:/docs/v1/tech/apis/authentication#client-credentials[Client Credentials] authorization workflow.

== SCIM Error Responses

All error responses from From FusionAuth SCIM API endpoints will be returned in SCIM compliant schema as defined link:https://datatracker.ietf.org/doc/html/rfc7644#section-3.12[here].

[source,json]
.Example SCIM error response JSON
----
include::/docs/src/json/scim/scim-error-response.json[]
----

In addition, FusionAuth will append additional error data when available with a SCIM schema extension.

[source,json]
.Example SCIM Error Response JSON with FusionAuth custom extension schema
----
include::/docs/src/json/scim/scim-extended-error-response.json[]
----
