---
layout: doc
title: SCIM Service Provider API Overview
description: APIs for discovering configuration information about FusionAuth SCIM Service Provider using a SCIM Client
---

:no_authentication:
:never_missing:
:never_search:
:never_webhook_event:

== Overview
This API is used to retrieve information about the configuration of the link:https://datatracker.ietf.org/doc/html/rfc7644#section-3.2[FusionAuth SCIM Service Provider as specified in the RFC].

* <<Retrieve Resource Types>>
* <<Retrieve Schemas>>
* <<Retrieve Service Provider Configuration>>

== Retrieve Resource Types

=== Request
[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Retrieve All Resource Types
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resource/v2/ResourceTypes#
--

:http_method: GET

=== Response

The response for this API contains the ResourceTypes in standard SCIM link:https://datatracker.ietf.org/doc/html/rfc7643#section-6[schema].

include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-resourcetypes-response-body.adoc[]

== Retrieve Schemas

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Retrieve All Schemas
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resource/v2/Schemas#
--

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Retrieve a Schema by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resource/v2/Schemas/`\{schemaId\}`#
--

==== Request Parameters

[.api]
[field]#schemaId# [type]#[String]# [optional]#Optional#::
The unique Schema Id, such as `urn:ietf:params:scim:schemas:core:2.0:User`.

:http_method: GET

=== Response

The response for this API contains the Schema definition(s) in standard SCIM link:https://datatracker.ietf.org/doc/html/rfc7643#section-7[schema].

:never_missing!:
include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:never_missing:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-schemas-response-body.adoc[]

== Retrieve Service Provider Configuration

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Retrieve Service Provider Configuration
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resource/v2/ServiceProviderConfig#
--

:http_method: GET

=== Response

The response for this API contains the Service Provider Configuration in standard SCIM link:https://datatracker.ietf.org/doc/html/rfc7643#section-5[schema].

include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-serviceproviderconfig-response-body.adoc[]
