---
layout: doc
title: SCIM EnterpriseUser APIs
description: APIs for provisioning SCIM EnterpriseUsers in FusionAuth using a SCIM Client
---

== Overview

This page contains all of the APIs for managing Users through link:https://datatracker.ietf.org/doc/html/rfc7643#section-4.3[SCIM EnterpriseUser] requests.

* <<Create an EnterpriseUser>>
* <<Retrieve an EnterpriseUser>>
* <<Retrieve EnterpriseUsers>>
* <<Update an EnterpriseUser>>
* <<Delete an EnterpriseUser>>

== Create an EnterpriseUser

This API is intended to be called by a SCIM Client and is used to create a new FusionAuth User.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:passport[type=fas]] Create a User
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/scim/resource/v2/EnterpriseUsers#
--

:http_method: POST
include::docs/v1/tech/apis/scim/_scim-enterpriseuser-request-body.adoc[]

=== Response

The response for this API contains the User that was just created in SCIM schema format.

:never_missing:
include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:never_missing!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-enterpriseuser-response-body.adoc[]

== Retrieve an EnterpriseUser

This API is used to retrieve a FusionAuth User in SCIM schema format through a SCIM request.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:passport[type=fas]] Retrieves an EnterpriseUser
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resource/v2/EnterpriseUsers/`\{userId\}`#
--
==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth unique User Id.

:http_method: GET

=== Response

The response for this API contains the User in SCIM schema format.

:never_webhook_event:
include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:never_webhook_event!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-enterpriseuser-response-body.adoc[]

== Retrieve EnterpriseUsers

This API is used to retrieve a paginated set of Users with an optional filter.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:passport[type=fas]] Retrieves users
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resource/v2/EnterpriseUsers#
--
==== Request Parameters

[.api]
[field]#count# [type]#[Integer]# [optional]#Optional#::
The number of results to return. Used for pagination.

[field]#excludedAttributes# [type]#[String]# [optional]#Optional# [since]#Available since 1.39.0#::
A comma separated list of one or more attributes to exclude in the JSON response body.
+
For example, a value of `phoneNumbers` will remove the `phoneNumbers` attribute from all Users returned in the response.

[field]#filter# [type]#[String]# [optional]#Optional# [since]#Available since 1.39.0#::
The optional filter string to limit the Users returned to those matching the filter criteria.

[field]#startIndex# [type]#[Integer]# [optional]#Optional#::
The offset into the total results. In order to paginate the results, increment this value by the [field]#count# for subsequent requests.
+
This parameter begins at `1`.

:http_method: GET

=== Response

The response for this API contains the EnterpriseUsers in SCIM schema format.

include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-group-list-response-body.adoc[]

== Update an EnterpriseUser

This API is used to update a new FusionAuth User from a SCIM request. The FusionAuth User will be overwritten by  the data contained in the request. It is not a partial update or a patch.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:passport[type=fas]] Updates an EnterpriseUser from a SCIM request
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/scim/resource/v2/EnterpriseUsers/`\{userId\}`#
--
==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth unique User Id.

:http_method: PUT
include::docs/v1/tech/apis/scim/_scim-enterpriseuser-request-body.adoc[]

=== Response

The response for this API contains the User that was updated in SCIM schema format.

include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]

For SCIM endpoints, error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-enterpriseuser-response-body.adoc[]

== Delete an EnterpriseUser

This API is used to hard delete a FusionAuth User. You must specify the Id of the User on the URI.

The data of a User who has been hard deleted is permanently removed from FusionAuth. The User's data cannot be restored via the FusionAuth API or the administrative user interface. If you need to restore the User's data, you must retrieve it from a database backup.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:passport[type=fas]] Delete a User
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/scim/resource/v2/EnterpriseUsers/``\{userId\}``#
--
==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The FusionAuth unique User Id.

:http_method: DELETE

=== Response

This API does not return a JSON response body.

:delete:
include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:delete!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].


