---
layout: doc
title: SCIM Group APIs
description: APIs for provisioning SCIM Groups in FusionAuth using a SCIM Client
---
:no_webhook_event:

== Overview

This page contains all of the APIs for managing Groups through link:https://datatracker.ietf.org/doc/html/rfc7643#section-4.2[SCIM Group] requests.

* <<Create a Group>>
* <<Delete a Group>>
* <<Retrieve a Group>>
* <<Update a Group>>

== Create a Group

This API is used to create a new FusionAuth Group from a SCIM request.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:empire[type=fab]]icon:building-lock[type=fas] Create a Group from a SCIM request
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/scim/resources/v2/Groups#
--

:http_method: POST
include::/docs/v1/tech/apis/scim/_scim-group-request-body.adoc[]

=== Response

The response for this API contains the Group that was just created in SCIM schema format.

:no_missing:
include::/docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:no_missing!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

include::/docs/v1/tech/apis/scim/_scim-group-response-body.adoc[]

== Delete a Group

This API is used to hard delete a FusionAuth Group through a SCIM request. You must specify the Id of the Group on the URI.

The data of a Group who has been hard deleted is permanently removed from FusionAuth. The Group's data cannot be restored via the FusionAuth API or the administrative Group interface. If you need to restore the Group's data, you must retrieve it from a database backup.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:empire[type=fab]] Delete a Group through a SCIM request
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/scim/resources/v2/Groups/``\{groupId\}``#
--
==== Request Parameters

[.api]
[field]#groupId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth unique Group Id.

:http_method: DELETE

=== Response

This API does not return a JSON response body.

The DELETE endpoint will return a 204 status code upon success or one of the standard error status codes.

:delete:
include::/docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:delete!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

== Retrieve a Group

This API is used to retrieve a FusionAuth Group in SCIM schema format through a SCIM request.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:empire[type=fab]] Retrieves a Group through a SCIM request
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resources/v2/Groups/`\{groupId\}`#
--
==== Request Parameters

[.api]
[field]#groupId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth unique Group Id.

:http_method: GET

=== Response

The response for this API contains the Group in SCIM schema format.

include::/docs/v1/tech/apis/scim/_scim-response-codes.adoc[]

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

include::/docs/v1/tech/apis/scim/_scim-group-response-body.adoc[]

== Update a Group

This API is used to update a new FusionAuth Group from a SCIM request. The FusionAuth Group will be overwritten with only the data contained in the request. It is not a partial update or patch.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:empire[type=fab]] Updates a Group from a SCIM redquest
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/scim/resources/v2/Groups/`\{groupId\}`#
--
==== Request Parameters

[.api]
[field]#groupId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth Group Id.

:http_method: PUT
include::/docs/v1/tech/apis/scim/_scim-group-request-body.adoc[]

=== Response

The response for this API contains the Group that was updated in SCIM schema format.

include::/docs/v1/tech/apis/scim/_scim-response-codes.adoc[]

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

include::/docs/v1/tech/apis/scim/_scim-group-response-body.adoc[]
