---
layout: doc
title: SCIM Group APIs
description: APIs for provisioning SCIM Groups in FusionAuth using a SCIM Client
---
:never_webhook_event:

== Overview

This page contains all of the APIs for managing Groups through link:https://datatracker.ietf.org/doc/html/rfc7643#section-4.2[SCIM Group] requests.

* <<Create a Group>>
* <<Retrieve a Group>>
* <<Retrieve Groups>>
* <<Update a Group>>
* <<Delete a Group>>

== Create a Group

This API is intended to be called by a SCIM Client and is used to create a new FusionAuth Group.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:passport[type=fas]] Create a Group
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/scim/resource/v2/Groups#
--

:http_method: POST
include::docs/v1/tech/apis/scim/_scim-group-request-body.adoc[]

=== Response

The response for this API contains the Group that was just created in SCIM schema format.

:never_missing:
include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:never_missing!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-group-response-body.adoc[]


== Retrieve a Group

This API is used to retrieve a FusionAuth Group in SCIM schema format through a SCIM request.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:passport[type=fas]] Retrieves a Group
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resource/v2/Groups/`\{groupId\}`#
--
==== Request Parameters

[.api]
[field]#groupId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth unique Group Id.

:http_method: GET

=== Response

The response for this API contains the Group in SCIM schema format.

include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-group-response-body.adoc[]

== Retrieve Groups

This API is used to retrieve a paginated set of Groups with an optional filter.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:passport[type=fas]] Retrieve Groups
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resource/v2/Groups#
--
==== Request Parameters

[.api]
[field]#count# [type]#[Integer]# [optional]#Optional#::
The number of results to return. Used for pagination.

[field]#excludedAttributes# [type]#[String]# [optional]#Optional# [since]#Available since 1.39.0#::
A comma separated list of one or more attributes to exclude in the JSON response body.
+
For example, a value of `members` will remove the `members` attribute from all Groups returned in the response.

[field]#filter# [type]#[String]# [optional]#Optional# [since]#Available since 1.39.0#::
The SCIM filter string used to limit the Groups returned to those matching the criteria.
+
The use of this parameter is limited when using to filter Groups. The following limitations apply:
+
* Only the `displayName` and `externalId` attributes may be used
* Only the `eq` operator may be used

[field]#startIndex# [type]#[Integer]# [optional]#Optional#::
The offset into the total results. In order to paginate the results, increment this value by the [field]#count# for subsequent requests.
+
This parameter begins at `1`.

:http_method: GET

=== Response

The response for this API contains the Groups in SCIM schema format.

include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-group-list-response-body.adoc[]

== Update a Group

This API is used to update a new FusionAuth Group from a SCIM request. The FusionAuth Group will be overwritten with only the data contained in the request. It is not a partial update or patch.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:passport[type=fas]] Updates a Group from a SCIM request
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/scim/resource/v2/Groups/`\{groupId\}`#
--
==== Request Parameters

[.api]
[field]#groupId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth Group Id.

:http_method: PUT
include::docs/v1/tech/apis/scim/_scim-group-request-body.adoc[]

=== Response

The response for this API contains the Group that was updated in SCIM schema format.

include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].

include::docs/v1/tech/apis/scim/_scim-group-response-body.adoc[]

== Delete a Group

This API is used to hard delete a FusionAuth Group. You must specify the Id of the Group on the URI.

The data of a Group who has been hard deleted is permanently removed from FusionAuth. The Group's data cannot be restored via the FusionAuth API or the administrative Group interface. If you need to restore the Group's data, you must retrieve it from a database backup.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:passport[type=fas]] Delete a Group
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/scim/resource/v2/Groups/``\{groupId\}``#
--
==== Request Parameters

[.api]
[field]#groupId# [type]#[UUID]# [require]#Required#::
The FusionAuth unique Group Id.

:http_method: DELETE

=== Response

This API does not return a JSON response body.

The DELETE endpoint will return a `204` status code upon success or one of the standard error status codes.

:delete:
include::docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:delete!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim/[SCIM API Overview].



