---
layout: doc
title: SCIM User APIs
description: APIs for provisioning SCIM Users in FusionAuth using a SCIM Client
---

== Overview

This page contains all of the APIs for managing Users through link:https://datatracker.ietf.org/doc/html/rfc7643#section-4.1[SCIM User] requests.

* <<Create a User>>
* <<Delete a User>>
* <<Retrieve a User>>
* <<Update a User>>

== Create a User

This API is used to create a new FusionAuth User from a SCIM request.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:empire[type=fab]] Create a User from a SCIM request
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/scim/resources/v2/Users#
--

:http_method: POST
include::/docs/v1/tech/apis/scim/_scim-user-request-body.adoc[]

=== Response

The response for this API contains the User that was created in SCIM schema format.

:create:
include::/docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:create!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

include::/docs/v1/tech/apis/scim/_scim-user-response-body.adoc[]

== Delete a User

This API is used to hard delete a FusionAuth User through a SCIM request. You must specify the Id of the User on the URI.

The data of a User who has been hard deleted is permanently removed from FusionAuth. The User's data cannot be restored via the FusionAuth API or the administrative user interface. If you need to restore the User's data, you must retrieve it from a database backup.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:empire[type=fab]] Delete a User through a SCIM request
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/scim/resources/v2/Users/``\{userId\}``#
--
==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth unique User Id.

:http_method: DELETE

=== Response

This API does not return a JSON response body.


:delete:
include::/docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:delete!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

== Retrieve a User

This API is used to retrieve a FusionAuth User in SCIM schema format through a SCIM request.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:empire[type=fab]] Retrieves a User through a SCIM request
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resources/v2/Users/`\{userId\}`#
--
==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth unique User Id.

:http_method: GET

=== Response

The response for this API contains the User in SCIM schema format.

:no_webhook_event:
include::/docs/v1/tech/apis/scim/_scim-response-codes.adoc[]
:no_webhook_event!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

include::/docs/v1/tech/apis/scim/_scim-user-response-body.adoc[]

== Update a User

This API is used to update a new FusionAuth User from a SCIM request. The FusionAuth User will be overwritten by the data contained in the request. It is not a partial update or a patch.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:empire[type=fab]] Updates a User from a SCIM request
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/scim/resources/v2/Users/`\{userId\}`#
--
==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth unique User Id.

:http_method: PUT
include::/docs/v1/tech/apis/scim/_scim-user-request-body.adoc[]

=== Response

The response for this API contains the User that was updated in SCIM schema format.

include::/docs/v1/tech/apis/scim/_scim-response-codes.adoc[]

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

include::/docs/v1/tech/apis/scim/_scim-user-response-body.adoc[]
