---
layout: doc
title: SCIM EnterpriseUser APIs
description: APIs for provisioning SCIM EnterpriseUsers in FusionAuth using a SCIM Client
---

== Overview

This page contains all of the APIs for managing Users through SCIM EnterpriseUser requests.

* <<Create a EnterpriseUser>>
* <<Delete a EnterpriseUser>>
* <<Retrieve a EnterpriseUser>>
* <<Update a EnterpriseUser>>

== Create a EnterpriseUser

This API is used to create a new FusionAuth User from a SCIM request.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:cogs[type=fas]] Create a EnterpriseUser from a SCIM request
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/scim/resources/v2/EnterpriseUsers#
--

:http_method: POST
include::/docs/v1/tech/apis/scim/_scim-enterpriseuser-request-body.adoc[]

=== Response

The response for this API contains the User that was just created in SCIM schema format.

:webhook_event:
:create_user:
include::/docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:create_user!:
:webhook_event!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

:create_user:
include::/docs/v1/tech/apis/scim/_scim-enterpriseuser-response-body.adoc[]
:create_user!:

== Delete a EnterpriseUser

This API is used to hard delete a FusionAuth User through a SCIM request. You must specify the Id of the User on the URI.

The data of a User who has been hard deleted is permanently removed from FusionAuth. The User's data cannot be restored via the FusionAuth API or the administrative user interface. If you need to restore the User's data, you must retrieve it from a database backup.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:cogs[type=fas]] Delete a EnterpriseUser through a SCIM request
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/scim/resources/v2/EnterpriseUsers`\{userId\}`#
--
==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth userId.

:http_method: DELETE

=== Response

This API does not return a JSON response body.

The DELETE endpoint will return a 204 status code upon success or one of the standard error status codes.

:webhook_event:
:create_user:
include::/docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:create_user!:
:webhook_event!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

== Retrieve a EnterpriseUser

This API is used to retrieve a FusionAuth User in SCIM schema format through a SCIM request.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:cogs[type=fas]] Retrieves a EnterpriseUser through a SCIM request
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/scim/resources/v2/EnterpriseUsers/`\{userId\}`#
--
==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth userId.

:http_method: GET

=== Response

The response for this API contains the User in SCIM schema format.

:webhook_event:
:create_user:
include::/docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:create_user!:
:webhook_event!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

:create_user:
include::/docs/v1/tech/apis/scim/_scim-enterpriseuser-response-body.adoc[]
:create_user!:

== Update a EnterpriseUser

This API is used to update a new FusionAuth User from a SCIM request. The FusionAuth User will be overwritten by  the data contained in the request. It is not a partial update or a patch. The only exceptions are ...

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#client-credentials[icon:cogs[type=fas]] Updates a EnterpriseUser from a SCIM request
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/scim/resources/v2/EnterpriseUsers/`\{userId\}`#
--
==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth userId.

:http_method: PUT
include::/docs/v1/tech/apis/scim/_scim-enterpriseuser-request-body.adoc[]

=== Response

The response for this API contains the User that was just updated in SCIM schema format.

:webhook_event:
:create_user:
include::/docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:create_user!:
:webhook_event!:

For FusionAuth SCIM endpoints, any error responses will be returned in standard SCIM schema. See more details in the link:/docs/v1/tech/apis/scim[SCIM API Overview].

:create_user:
include::/docs/v1/tech/apis/scim/_scim-enterpriseuser-response-body.adoc[]
:create_user!:
