---
layout: doc
title: Using FusionAuth on Docker
description: Deploy and test FusionAuth using a Docker container
---

:sectnumlevels: 0

== Docker Compose

All of the FusionAuth Docker images may be found on https://hub.docker.com/u/fusionauth/[Docker Hub]. If you're looking for a complete configuration to get up and running quickly, use our Docker Compose example. The following is an example and it may not be the most recent version. Refer to the following link in https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/docker-compose.yml[GitHub] to find the latest version.

```
docker-compose up
```

```yaml
version: '2.3'

services:
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:

  search1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    healthcheck:
      test: "curl --fail -s http://localhost:9200 || exit 1"
      interval: 1s
      timeout: 1s
      retries: 10
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  fusionauth:
    depends_on:
      db:
        condition: service_started
      search1:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USER: postgres
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USER: fusionauth
      DATABASE_PASSWORD: hkaLBM3RVnyYeYeqE3WI1w2e4Avpy0Wd5O3s3
      FUSIONAUTH_MEMORY: 256M
      FUSIONAUTH_SEARCH_SERVERS: http://search1:9200
    image: fusionauth/fusionauth-app:latest
    links:
      - db
      - search1
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config

volumes:
  db_data:
  es_data1:
  fa_config:
```

=== Database Service

At a minimum, you wil need to either set the `POSTGRES_PASSWORD` environment variable in the `db` service section, or more ideally set the value in the host environment and leave it out of the `docker-compose.yml` file. Ensure the other properties fit your requirements.

=== Search Service

We currently are only supporting Elasticsearch 6.3.1, do not modify the image value. Let us know if you have a requirement for a different version of Elasticsearch. The remainder of the properties can be changed to whatever you need.

=== FusionAuth Service

== Docker Images

=== FusionAuth App
```
docker pull fusionauth/fusionauth-app
```

=== FusionAuth Search
The FusionAuth Search image is provided for convenience, you may also choose to use any ElasticSearch container or service running at version 6.3.
```
docker pull fusionauth/fusionauth-search
```





