---
layout: doc
title: FusionAuth Search Installation
description: Install the FusionAuth Search bundle.
---

== Overview

This guide will assist you with installing FusionAuth Search on your own server running Linux, Mac OS, or Windows. The search engine
is required by Passport and provides full text search. This service may be horizontally scaled by using Elasticsearch clustering.

== Download the Packages

Navigate to the https://fusionauth.io/downloads[Download] page and find FusionAuth Search package for your target platform.

== Red Hat

To install on a Red Hat based system, use the RPM bundle. Execute this command to install the FusionAuth Search RPM (replace `<version>` with
 the correct version number):
[source,shell]
----
$ sudo rpm -i fusionauth-search<version>.rpm
----

== Debian

To install on a Debian based system, use the DEB bundle. Execute this command to install the FusionAuth Search DEB (replace `<version>` with
 the correct version number):

[source,shell]
----
$ sudo dpkg -i fusionauth-search<version>.deb
----

== macOS X

To install on Mac OS use the ZIP bundle. Extract the FusionAuth Search ZIP file anywhere on the file system. Remember where you extract the file.
 This location will be referred to as `FUSIONAUTH_HOME`. We suggest extracting this file to a directory such as `/usr/local/fusionauth`.

Once the zip bundle has been extracted, the directory structure should look similar to this. If you installed somewhere other the default `FUSIONAUTH_HOME`,
 your directory structure will be different, this is only for shown as an example.

[source,shell]
----
/usr/local/fusionauth/bin
/usr/local/fusionauth/config
/usr/local/fusionauth/config/keystore
/usr/local/fusionauth/config/fusionauth.properties
/usr/local/fusionauth/fusionauth-search
----

== Windows

To install on Windows use the ZIP bundle. Extract the FusionAuth Search ZIP file anywhere on the file system. Remember where you extract
 the file. This location will be referred to as `FUSIONAUTH_HOME`. We suggest extracting this file to a directory such as `C:\inversoft` on Windows.

Once the zip bundle has been extracted, the directory structure should look similar to this. If you installed somewhere other the default `FUSIONAUTH_HOME`,
 your directory structure will be different, this is only for shown as an example.

[source]
----
C:\fusionauth\bin
C:\fusionauth\config
C:\fusionauth\config\keystore
C:\fusionauth\config\fusionauth.properties
C:\fusionauth\fusionauth-search\
----

Next, install the Windows service by changing to the directory designated as `FUSIONAUTH_HOME` and then running the install command.

[source]
----
C:\> cd C:\fusionauth\fusionauth-search\elasticsearch\bin
C:\fusionauth\fusionauth-search\elasticsearch\bin> FusionAuthSearch.exe /install
----

== Configuration

If you will be running more than one search engine service, or the search engine is installed on a separate server than the FusionAuth App service,
you will need to modify the default configuration in the `fusionauth.properties` file.

If you have installed the Search Engine service on the same server that is running FusionAuth App no further configuration is required.

Each server running the FusionAuth Search service will need to be added to the configuration. To do this, you will need to edit the
`fusionauth.properties` configuration file. More information about this configuration file is located in the link:../reference/configuration[Configuration Reference] section.

The following examples assume that FusionAuth App and FusionAuth Search can communicate either on `localhost` if running on the same
system, or if running on separate systems that a site local connection exists between both servers. If you require communication between
FusionAuth App and FusionAuth Search on a public IP address, you will also need to modify the `fusionauth-search.hosts` property
on the server running FusionAuth Search. The default value will only bind to localhost and site local IP addresses. See the
link:../reference/configuration[Configuration Reference] for more information on configuring the `fusionauth-search.hosts` property.

The following examples also assume the default port as specified by the `fusionauth-search.transport-port` property. If this value has been
modified, adjust the examples accordingly.


=== Example Configuration 1
The following is an example where FusionAuth Search is running on the same server as FusionAuth. This is the default configuration,
if this is how you have your system configured, no change to `fusionauth.properties` is required.

[source,ini]
.fusionauth.properties
----
fusionauth-search.servers=localhost:9020
----


=== Example Configuration 2
The following is an example where the FusionAuth Search is running on a separate system than the FusionAuth App and the Passport
Search Engine has an IP Address of `192.168.1.41`.

We'll refer to the server running FusionAuth App as System 1, and the server running FusionAuth Search as System 2.

[source,ini]
.fusionauth.properties on System 1
----
fusionauth-search.servers=192.168.1.41:9020
----

[source,ini]
.fusionauth.properties on System 2
----
fusionauth-search.servers=localhost:9020
----

=== Example Configuration 3
The following is an example where FusionAuth Search is running on the same server as FusionAuth App, and another server also has
both the FusionAuth App and the FusionAuth Search installed.

We will refer to these systems as System 1 and System 2, where System 1 has an IP address of `192.168.1.41` and System 2 has an IP address
of `192.168.1.42`.


[source,ini]
.fusionauth.properties on System 1
----
fusionauth-search.servers=localhost:9020,192.168.1.42:9020
----

[source,ini]
.fusionauth.properties on System 2
----
fusionauth-search.servers=localhost:9020,192.168.1.41:9020
----

== Start FusionAuth Search

Passport Search Engine should now be ready to run. Use the instructions below to start FusionAuth Search. The search engine should be started
first before the FusionAuth App service.

[source,shell]
.Linux (RPM or DEB package)
----
$ sudo service fusionauth-search start
----

[source,shell]
.macOS (ZIP package)
----
$ <FUSIONAUTH_HOME>/fusionauth-search/elasticsearch/bin/elasticsearch -d
----

[source]
.Windows (ZIP package)
----
C:\fusionauth\fusionauth-search\elasticsearch\bin>elasticsearch.bat
----

[source]
.Windows Service
----
C:\> net start PassportSearchEngine
----
