---
layout: doc
title: Install FusionAuth using Homebrew
description: Install FusionAuth using Homebrew
---

:sectnumlevels: 0

== Homebrew

Homebrew is a macOS package manager, so if you're running macOS and you're familiar with Homebrew, we've got you covered. Our Homebrew formula is open source and available on GitHub.
https://github.com/FusionAuth/homebrew-fusionauth

To install FusionAuth using brew, first install the Tap, you will only need to do this step once.

```
brew tap fusionauth/homebrew-fusionauth
```

Next, install the FusionAuth services, you can optionally skip the `fusionauth-search` service if you already have a compatible Elasticsearch service running. See system requirements.

```
brew install fusionauth-app fusionauth-search
```

That's it!  Now fire it up!

```
brew services start fusionauth-search
brew services start fusionauth-app
```

Now to get started open your browser to `http://localhost:9011`, and complete maintenance mode and the setup wizard.

The shared configuration file will be located here: `/usr/local/etc/fusionauth/fusionauth.properties` and the logs are here : `/usr/local/var/log/fusionauth/`.




