---
layout: doc
title: Packages
description: Determine which installation packages you need
---

:sectnumlevels: 0

== What Packages do I need?

When you've navigated to the Download page after logging into your https://www.inversoft.com/account[Inversoft account] you'll be
presented with several packages to download.

Review the following information to understand which packages you need to download. If your target platform is Linux, using
the RPM or DEB packages is preferred and provides the simplest installation process. Only ZIP files are provided for Windows and macOS.

[heading]*Backend Downloads*

The FusionAuth App is the web service that handles all API calls and provides the web based management interface to Passport. You will
always need to download this package since it is the core component of Passport.

[heading]*Search Engine Downloads*

The Search Engine package contains the Elasticsearch service that Passport uses to index and provide ability to search for users.

[heading]*Database Downloads*

The database package contains the Passport schema and migration scripts that Inversoft provides to support version upgrades when database changes
were made. In most cases, you will not need to use this package. Instead, FusionAuth App will enter Maintenance Mode when it is started and
this will automatically create the database or upgrade it. If you need to perform unattended installs or upgrades of Passport, you will need
to download this package for the schema and migration SQL scripts. You can review the link:passport-backend#advanced-installation[Advanced Installation]
portion of the link:passport-backend[Install FusionAuth App] section to learn more about unattended installations and upgrades.
