---
layout: doc
title: System Requirements
description: The minimum system requirements required to install and run FusionAuth
---

== System Requirements

FusionAuth will install and run on nearly any system. We have done our best to document the supported configurations here. If you
have any questions about platform support, please contact us. Please read through this documentation and ensure you have met all of
the requirements before continuing with the installation of FusionAuth.

== Operating System

* Linux - all distributions (64-bit)
* macOS 10.8 (Mountain Lion) or newer
* Windows Server 2008 SP2 (64-bit) w/ Windows Management Framework 3.0 or newer
* Windows Server 2008 R2 (64-bit) w/ Windows Management Framework 3.0 or newer
* Windows 7 SP1 (64-bit) w/ Windows Management Framework 3.0 or newer

== Database

* MySQL 5.6.17 or newer.
** IBM Compose for MySQL or other MysQL platforms that utilize MySQL Group Replication are not supported.
** MariaDB is known to work, however this variant is not actively tested against by FusionAuth. Please do let us know if you run into an issue.
* PostgreSQL 9.5 or newer

== Elasticsearch

* Elasticsearch is a core required for FusionAuth
* You can use the link:packages#fusionauth-search[`fusionauth-search`] package or any other Elasticsearch service including a cloud hosted service or just downloading it and installing it yourself from https://www.elastic.co/products/elasticsearch[elastic.co].
* Version 6.3.x is the currently supported version, later versions may work as well but may not have been tested for compatibility.
