---
layout: doc
title: System Requirements
description: The minimum system requirements required to install and run FusionAuth
---

== System Requirements

FusionAuth will install and run on nearly any system. We have done our best to document the supported configurations here. If you
have any questions about platform support, please contact us. Please read through this documentation and ensure you have met all of
the requirements before continuing with the installation of FusionAuth.

=== Operating System

* Linux - all distributions (64-bit)
* macOS 10.8 (Mountain Lion) or newer
* Windows Server 2008 SP2 (64-bit) w/ Windows Management Framework 3.0 or newer
* Windows Server 2008 R2 (64-bit) w/ Windows Management Framework 3.0 or newer
* Windows 7 SP1 (64-bit) w/ Windows Management Framework 3.0 or newer

=== Database

* MySQL 5.6.17 or newer. IBM Compose for MySQL or other MysQL platforms that utilize MySQL Group Replication are not supported.
* PostgreSQL 9.5 or newer

=== Elastic Search

* Elastic Search is required
* You can use the `fusionauth-search` package or any other Elastic Search service (including a cloud hosted service or just downloading it and installing it yourself)
* Version 6.3.x is currently the supported version however newer versions might work as well
