---
layout: doc
title: SCIM With SCIM-client
description: How to set up SCIM with scim-client
navcategory: premium
---

:sectnumlevels: 0

== Overview

This document will walk through using the open source https://github.com/Captain-P-Goldfish/SCIM-SDK[SCIM-Client Java Library] with FusionAuth

== FusionAuth Configuration

In order for FusionAuth to accept requests from SCIM clients, you need to configure a few things.

First, make sure you have a license. You can link:/docs/v1/tech/admin-guide/licensing[learn more about licensing here]. SCIM requires an enterprise license. Learn more about link:/docs/v1/tech/core-concepts/editions-features[license options here] and link:/pricing[pricing here].

=== Set Up Entities

Then, you need to set up the required entity types. These will be present if you have a default installation of FusionAuth, but will not be if you use Kickstart.

First, add the SCIM server. Navigate to [breadcrumb]#Entity Management -> Entity Types# and select the [breadcrumb]#Add SCIM Server# option.

TODO PICTURE add-scim-server-entity-type

This will have the following default permissions.

// TODO have this be an include file
* `scim:enterprise:user:create`
* `scim:enterprise:user:delete`
* `scim:enterprise:user:read`
* `scim:enterprise:user:update`
* `scim:group:create`
* `scim:group:delete`
* `scim:group:read`
* `scim:group:update`
* `scim:user:create`
* `scim:user:delete`
* `scim:user:read`
* `scim:user:update`

TODO PICTURE  adding-scim-server-entity-type-details

You can remove permissions if you never want your SCIM server to be able to undertake an operation. For example, remove `scim:user:delete` if you will never delete users.

Then, create a SCIM client entity type. Unlike the server, this doesn't require any special permissions, but will instead represent the SCIM client applications which will be providing user and group data to the SCIM server for provisioning.

TODO PICTURE add-scim-server-entity-type

TODO PICTURE  adding-scim-server-entity-type-details

Next, set up two entities. You need to set up an instance of the SCIM server and the SCIM client, and then grant permissions on the SCIM server to the SCIM client. You can have as many SCIM clients as you would like. You can have one SCIM server per tenant.

Navigate to [breadcrumb]#Entity Management -> Entities# and create a new entity.

TODO Picture
Make sure it has the type of the SCIM Server entity type you created above.

TODO Picture

Add another entity.

Make sure it has the type of the SCIM Client entity type you created above.

TODO Picture

Manage the client entity; you need to add permissions to the server entity.

TODO Picture

Add the permissions. You may grant one or more SCIM permissions to the client. These will be provided during the SCIM process to authenticate the appropriate level of access. Select the SCIM server entity in the [field]#Name# field and any permissions you'd like this client to have.


TODO Picture

Note the client Id of the SCIM server and the client Id and Secret of the SCIM client.

TODO Picture

Next, we need to add the lambdas.

Next, we need to configure the tenant

Next, we need to configure the SCIM-sdk client.

Then we need to run it

Then we need to see the new user added.



- You need to enable SCIM support for your tenant.
- You need to define your incoming request and outgoing response lambdas for each the supported SCIM resource types (User, Enterprise User, Group)
- You will need to verify that the default SCIM schemas provided match your desired SCIM schema for each of the SCIM resource types or provide your own.
- You will need an Entity defined for each SCIM client and SCIM Server. link:/docs/v1/tech/core-concepts/entity-management#scim-configuration[Default entity types] are provided for you. You can create the entities from those default types or create your own types.

== FusionAuth SCIM API Endpoints

In order to use FusionAuth as your SCIM provisioning server for SCIM clients, you will need to call the correct FusionAuth SCIM API endpoint. FusionAuth provides endpoints for retrieving, creating, replacing, and deleting SCIM link:https://datatracker.ietf.org/doc/html/rfc7643#section-4.1[Users], link:https://datatracker.ietf.org/doc/html/rfc7643#section-4.3[EnterpriseUsers], and link:https://datatracker.ietf.org/doc/html/rfc7643#section-4.2[Groups].

See the link:/docs/v1/tech/apis/scim/[SCIM API Overview] for details about the supported endpoints.

== Limits

include::docs/v1/tech/shared/_scim-limits.adoc[]
