@startuml
  !include ../../_config.plantuml

participant "User/Browser" as User
participant "PPVC code" as ppvc

User -> ppvc : Click Login 
ppvc -> User : Redirect to FusionAuth
User -> FusionAuth : Request Login Page
FusionAuth -> User : Return Login Page
User -> FusionAuth : Provides Credentials
FusionAuth -> User : Redirect With Authorization Code 
User -> ppvc : Request configured Redirect URI (connect_fusionauth_check)
ppvc -> ppvc : Authenticator catches request to connect_fusionauth_check, calls authenticate
ppvc -> FusionAuth : Authenticator.authenticate calls endpoints to get token and user info
FusionAuth -> ppvc : Sends user info
ppvc -> ppvc : Stores email, FusionAuth id
ppvc -> ppvc : Calls Authenticator.onAuthenticationSuccess
ppvc -> User : Sends user to home page
User -> ppvc : Clicks on chat link
ppvc -> ppvc : Checks for valid user
ppvc -> User : Sends chat page
@enduml
