skinparam shadowing false
skinparam NoteBackgroundColor #LightBlue
skinparam NoteBorderColor #CornflowerBlue
skinparam ParticipantBackgroundColor #LightGray
skinparam ParticipantBorderColor #Gray
skinparam SequenceArrowColor #Black
skinparam SequenceLifeLineBorderColor #Black
skinparam SequenceDividerTextAlignment center
skinparam SequenceDividerFontStyle Normal
skinparam SequenceDividerBorderThickness 1