skinparam FontColor #5C666F
skinparam Padding 5
skinparam RoundCorner 8
skinparam Shadowing false

'skinparam NoteBackgroundColor #3F2C61
skinparam NoteBackgroundColor #8B80A1
skinparam NoteBorderColor #White
skinparam NoteFontColor #white
skinparam NoteFontStyle Italic

skinparam ParticipantBackgroundColor #D8D8D8
skinparam ParticipantBorderColor #979797
skinparam ParticipantBorderThickness 1

skinparam ArrowColor #56666F
skinparam ArrowThickness 1

skinparam SequenceLifeLineBorderColor #CDCDCD

skinparam SequenceDividerBackgroundColor #3F2C61
skinparam SequenceDividerBorderColor #white
skinparam SequenceDividerBorderThickness 1
skinparam SequenceDividerFontColor #white
skinparam SequenceDividerFontStyle Bold
