==== Response Body

[.api]
[field]#connector.authenticationURL# [type]#[String]#::
The fully qualified URL used to send an HTTP request to authenticate the user.

[field]#connector.connectTimeout# [type]#[Integer]#::
The connect timeout for the HTTP connection, in milliseconds. Value must be greater than `0`.

[field]#connect.data# [type]#[Object]#::
An object that can hold any information about the Connector that should be persisted.

[field]#connector.debug# [type]#[Boolean]#::
Determines if debug should be enabled to create an event log to assist in debugging integration errors.

[field]#connector.headers# [type]#[Object]#::
An object that can hold HTTPHeader key and value pairs.

[field]#connector.httpAuthenticationPassword# [type]#[String]#::
The basic authentication password to use for requests to the Connector.

[field]#connector.httpAuthenticationUsername# [type]#[String]#::
The basic authentication username to use for requests to the Connector.

[field]#connector.id# [type]#[UUID]#::
The unique Id of the Connector.

[field]#connector.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the Connector was created.

[field]#connector.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the Connector was last updated.

[field]#connector.name# [type]#[String]#::
The unique Connector name.

[field]#connector.readTimeout# [type]#[Integer]#::
The read timeout for the HTTP connection, in milliseconds. Value must be greater than `0`.

[field]#connector.sslCertificateId# [type]#[UUID]#::
The Id of an existing link:/docs/v1/tech/apis/keys[Key]. The X509 certificate is used for client certificate authentication in requests to the Connector.

[field]#connector.type# [type]#[String]#::
This field must be set to `Generic`.

[source,json]
.Example Generic Connector Response JSON
----
include::../../../../src/json/connectors/generic-response.json[]
----
