==== Request Body

[.api]
[field]#connector.authenticationURL# [type]#[String]# [optional]#Optional#::
The fully qualified URL used to send an HTTP request to authenticate the user.

[field]#connector.connectTimeout# [type]#[Integer]# [required]#Required#::
The connect timeout for the HTTP connection, in milliseconds. Value must be greater than `0`.

[field]#connect.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Connector that should be persisted.

[field]#connector.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if debug should be enabled to create an event log to assist in debugging integration errors.

[field]#connector.headers# [type]#[Object]# [optional]#Optional#::
An object that can hold HTTPHeader key and value pairs.

[field]#connector.httpAuthenticationPassword# [type]#[String]# [optional]#Optional#::
The basic authentication password to use for requests to the Connector.

[field]#connector.httpAuthenticationUsername# [type]#[String]# [optional]#Optional#::
The basic authentication username to use for requests to the Connector.

[field]#connector.name# [type]#[String]# [required]#Required#::
The unique Connector name.

[field]#connector.readTimeout# [type]#[Integer]# [required]#Required#::
The read timeout for the HTTP connection, in milliseconds. Value must be greater than `0`.

[field]#connector.sslCertificateId# [type]#[UUID]# [optional]#Optional#::
The Id of an existing link:/docs/v1/tech/apis/keys[Key]. The X509 certificate is used for client certificate authentication in requests to the Connector.

[field]#connector.type# [type]#[String]# [required]#Required#::
This field must be set to `Generic`.

[source,json]
.Example Generic Connector Request JSON
----
include::../../../../src/json/connectors/generic-request.json[]
----
