==== Response Body

[.api]
[field]#connector.authenticationURL# [type]#[String]#::
The fully qualified LDAP URL to authenticate.

[field]#connector.baseStructure# [type]#[String]#::
The top of the LDAP directory hierarchy. Typically this contains the `dc` (domain component) element.

[field]#connector.connectTimeout# [type]#[Integer]#::
The connect timeout for the HTTP connection, in milliseconds. Value must be greater than `0`.

[field]#connect.data# [type]#[Object]#::
An object that can hold any information about the Connector that should be persisted.

[field]#connector.debug# [type]#[Boolean]# [default]#::
Determines if debug should be enabled to create an event log to assist in debugging integration errors.

[field]#connector.id# [type]#[UUID]#::
The unique Id of the LDAP Connector.

[field]#connector.identifyingAttribute# [type]#[String]#::
The entry attribute name which is the first component of the distinguished name of entries in the directory.

[field]#connector.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the LDAP Connector was created.

[field]#connector.lambdaConfiguration.reconcileId# [type]#[UUID]#::
The Id of an existing link:/docs/v1/tech/apis/lambdas/[Lambda]. The lambda is executed after the user authenticates with the connector. This lambda can create a user, registrations, and group memberships in FusionAuth based on attributes returned from the connector.

[field]#connector.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the LDAP Connector was last updated.

[field]#connector.loginIdAttribute# [type]#[String]#::
The entity attribute name which stores the identifier that is used for logging the user in.

[field]#connector.name# [type]#[String]#::
The unique LDAP Connector name.

[field]#connector.readTimeout# [type]#[Integer]#::
The read timeout for the HTTP connection, in milliseconds. Value must be greater than `0`.

[field]#connector.requestedAttributes# [type]#[Array<String>]#::
The attributes to request for an entry from the DIT (Directory Information Tree).

[field]#connector.securityMethod# [type]#[String]#::
The LDAP security method.
Possible values are:
* `None` - Requests will be made without encryption.
* `LDAPS` - A secure connection will be made to a secure port over using the LDAPS protocol.
* `StartTLS` - An un-secured connection will initially be established, followed by secure connection established using the StartTLS extension.

[field]#connector.systemAccountDN# [type]#[String]#::
The distinguished name of an entry that has read access to the directory.

[field]#connector.systemAccountPassword# [type]#[String]#::
The password of an entry that has read access to the directory.

[field]#connector.type# [type]#[String]#::
This field must be set to `LDAP`.

[source,json]
.Example LDAP Connector Response JSON
----
include::../../../../src/json/connectors/ldap-response.json[]
----
