==== Request Body

[.api]
[field]#connector.authenticationURL# [type]#[String]# [required]#Required#::
The fully qualified LDAP URL to authenticate.

[field]#connector.baseStructure# [type]#[String]# [required]#Required#::
The top of the LDAP directory hierarchy. Typically this contains the `dc` (domain component) element.

[field]#connector.connectTimeout# [type]#[Integer]# [required]#Required#::
The connect timeout for the HTTP connection, in milliseconds. Value must be greater than `0`.

[field]#connect.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Connector that should be persisted.

[field]#connector.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if debug should be enabled to create an event log to assist in debugging integration errors.

[field]#connector.identifyingAttribute# [type]#[String]# [required]#Required#::
The entry attribute name which is the first component of the distinguished name of entries in the directory.

[field]#connector.lambdaConfiguration.reconcileId# [type]#[UUID]# [required]#Required#::
The Id of an existing link:/docs/v1/tech/apis/lambdas/[Lambda]. The lambda is executed after the user authenticates with the connector. This lambda can create a user, registrations, and group memberships in FusionAuth based on attributes returned from the connector.

[field]#connector.loginIdAttribute# [type]#[String]# [required]#Required#::
The entity attribute name which stores the identifier that is used for logging the user in.

[field]#connector.name# [type]#[String]# [required]#Required#::
The unique LDAP Connector name.

[field]#connector.readTimeout# [type]#[Integer]# [required]#Required#::
The read timeout for the HTTP connection, in milliseconds. Value must be greater than `0`.

[field]#connector.requestedAttributes# [type]#[Array<String>]# [required]#Required#::
The attributes to request for an entry from the DIT (Directory Information Tree).

[field]#connector.securityMethod# [type]#[String]# [required]#Required#::
The LDAP security method.
Possible values are:
* `None` - Requests will be made without encryption.
* `LDAPS` - A secure connection will be made to a secure port over using the LDAPS protocol.
* `StartTLS` - An un-secured connection will initially be established, followed by secure connection established using the StartTLS extension.

[field]#connector.systemAccountDN# [type]#[String]# [required]#Required#::
The distinguished name of an entry that has read access to the directory.

[field]#connector.systemAccountPassword# [type]#[String]# [required]#Required#::
The password of an entry that has read access to the directory.

[field]#connector.type# [type]#[String]# [required]#Required#::
This field must be set to `LDAP`.

[source,json]
.Example LDAP Connector Request JSON
----
include::../../../../src/json/connectors/ldap-request.json[]
----
