---
layout: doc
title: Connector API Overview
description: APIs for creating, retrieving, updating and deleting identity providers
---

== Overview

A Connector is a named object that provides configuration for allowing authentication against external systems. When you configure a Connector, you can write flexible rules determining which users will use the Connector and whether to migrate the external user information to FusionAuth. FusionAuth will authenticate users against external systems. FusionAuth currently supports the following Connector types:

* link:ldap[LDAP]
* link:generic[Generic]

The type of the connector will determine the object's properties as well as the validation that is performed. You can click into any of the connector API docs to get a list of that connector's properties.

=== Global Operations

* <<Retrieve all Connectors>>

== Retrieve all Connectors

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Retrieve all Connectors
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/connector#
--

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Retrieve a Conneector by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/connector/`\{connectorId\}`#
--

==== Request Parameters

[.api]
[field]#connectorId# [type]#[UUID]# [required]#Required#::
The unique Id of the Connector to retrieve.

=== Response

:never_missing:
:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_search_error!:
:never_missing!:

include::docs/v1/tech/apis/connectors/_multiple-response-body.adoc[]

