---
layout: doc
title: Migration From Duende IdentityServer
description: How to migrate your users to FusionAuth from Duende IdentityServer
---
:page-liquid:

:migration_source_name: Duende IdentityServer
:migration_source_dir: duende
:script_supports_social_logins: true
:add-tenant-image-role: bottom-cropped
:extra_permissions_text:

== Overview

This document will help you migrate from Duende IdentityServer to FusionAuth.

This guide assumes you have installed FusionAuth. If you have not, please link:/docs/v1/tech/installation-guide/[view our installation guides] and install FusionAuth before you begin. For more general migration information, please view the link:/docs/v1/tech/migration-guide/general[FusionAuth migration guide].

* <<Planning Considerations>>
** <<Obtaining User Data>>
** <<Mapping User Attributes>>
** <<Social Logins>>
** <<Other Entities>>
** <<Login UI>>
* <<Exporting Users>>
** <<Create a User File>>
* <<Importing Users>>
** <<Set Up FusionAuth>>
** <<Add the ASP.NET Identity V2 Hashing Plugin>>
** <<Get the Script>>
** <<Install Needed Gems>>
** <<Use the Script>>
** <<Verify the Import>>
** <<The Final Destination of Imported Users>>
* <<What to Do Next>>
* <<Additional Support>>

There are a number of different ways applications can be integrated with Duende IdentityServer and it would be difficult to cover them all. This guide mentions the typical parts of a bulk migration and focuses on migrating user data from a Duende IdentityServer user database into FusionAuth.

== Planning Considerations

=== Obtaining User Data

Duende IdentityServer does not prescribe where you store your user data. You can store it in a database of your choice, in a file, or in a custom data store. How you store your user information will determine how you export it. This guide assumes your Duende IdentityServer installation uses https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio[ASP.NET Identity] to manage users and passwords stored in a https://www.microsoft.com/en-us/sql-server/[Microsoft SQL Server] database. If you are using another custom setup, this guide should still be helpful as a starting point, but you will need to modify the export program to match your setup.

=== Mapping User Attributes

include::docs/v1/tech/migration-guide/_mapping-user-attributes.adoc[]

=== Social Logins

include::docs/v1/tech/migration-guide/_social-login-note.adoc[]

include::docs/v1/tech/migration-guide/_social-login-migration.adoc[]

=== Other Entities

:other_migrated_entities: connections or roles
include::docs/v1/tech/migration-guide/_other-entities-intro.adoc[]
:other_migrated_entities!:

* In Duende IdentityServer, External Identity Providers are a source of data for users. FusionAuth calls these Identity Providers.
* Login flows with Duende IdentityServer are highly customizable using custom code in your host application. FusionAuth authentication flows can be customized with a feature called link:/docs/v1/tech/lambdas[Lambdas].
* Duende IdentityServer has the concept of clients. Clients are sets of credentials and authentication flow settings. FusionAuth refers to these as Applications.
* FusionAuth Tenants are a high-level construct that groups entities such as users and applications together. Duende IdentityServer does not have an equivalent concept. Each Duende IdentityServer deployment is in effect a tenant.
* For Duende IdentityServer, roles can be implemented through connecting to .Net IdentityStore or through custom code. FusionAuth roles are defined on an application-by-application basis.
* Refresh tokens allow JWTs to be refreshed without a user logging in. These can be migrated using the link:/docs/v1/tech/apis/users#import-refresh-tokens[Import Refresh Tokens API].
* Since Duende IdentityStore is a framework used to build custom authentication servers, the actual functionality and features of the particular custom server you are migrating from could vary widely. FusionAuth may not have equivalents for these custom features and functionality, and is focused primarily on authentication.

[NOTE]
====
In Duende IdentityServer, users have access to all clients on the same server by default. 

In FusionAuth, users are explicitly mapped to applications with a link:/docs/v1/tech/core-concepts/registrations[Registration].
====

==== Identifiers

When creating an object with the FusionAuth API, you can specify the Id. It must be a link:/docs/v1/tech/reference/data-types#uuids[UUID].

This works for users, applications, and tenants, among others.

Duende IdentityServer implementations may use any format for an identifier. If you're managing users with ASP.NET, this identifier may be a UUID, which can be imported when you create the user on FusionAuth.

If you have an IdentityServer implementation that does not use a UUID as the user identifier, you can add a new attribute under [field]#user.data# (such as [field]#user.data.originalId#) with the value of the Duende IdentityServer identifier. Because everything under [field]#user.data# is indexed and available via search, you'll be able to find your users using either a new FusionAuth UUID Id or the original Duende IdentityServer identifier.

=== Login UI

Duende IdentityServer does not prescribe a particular login UI. Login pages are highly variable across Duende IdentityServer implementations.

FusionAuth's login experience follows two paths. You can choose to build your own login pages or use FusionAuth's hosted login pages. link:/docs/v1/tech/core-concepts/integration-points#login-options[Read more about these choices].

== Exporting Users

Duende IdentityServer provides a package to integrate with https://docs.duendesoftware.com/identityserver/v6/aspnet_identity/[ASP.NET Identity], which determines the format user information is stored in.

We recommend exporting your user information in JSON format so that you can import the data into FusionAuth using the FusionAuth API. Alternatively, you can create a custom tool to read your user attributes from the Duende IdentityServer database and directly call the link:/docs/v1/tech/apis/users[FusionAuth API to create users].

=== Create a User File

We've created a sample C# export program to export users from a Duende IdentityServer database to a JSON file. This program assumes you are using https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio[ASP.NET Identity]. You can find the folder with the source code for the export program https://github.com/fusionauth/fusionauth-import-scripts/tree/identityserver/duende/identity-server-export[here].

Clone the repo and open the solution in Visual Studio Code. 

Update the [field]#connectionString# variable in the `Program.cs` file with your database connection information. 

The export program assumes that user data is stored in the standard ASP.NET Identity tables, namely `AspNetUsers` and `AspNetUserLogins`. If you are using a different table or have extended the ASP.NET Identity tables, you will need to update the program to select from the correct tables. You can do this by modifying the `SqlCommand` in the `Program.cs` file. You can also modify the mapping of the user information to the `User` export objects in the `Program.cs` file.

The program also assumes that you have used ASP.NET Identity to create the users' password hashes. ASP.NET Identity stores the salt, hash, and iteration in a single Base64-encoded string. There are two versions of hashing used, as you can see in the https://github.com/dotnet/aspnetcore/blob/v6.0.14/src/Identity/Extensions.Core/src/PasswordHasher.cs[ASP.NET Identity source code].

* V2 - PBKDF2 with HMAC-SHA1, 128-bit salt, 256-bit subkey, 1000 iterations. The format of the Base64-encoded hash string is `{ 0x00, salt, subkey }`. The first byte is a version marker, `0x00` representing V2. The next 128 bits are the salt, and the remaining 256 bits are the subkey or salted password hash. The iteration count is hardcoded to 1000.
* V3 - PBKDF2 with HMAC-SHA256, 128-bit salt, 256-bit subkey, 10000 iterations. The format  of the Base64-encoded hash string is a little more complicated: `{ 0x01, prf (UInt32), iter count (UInt32), salt length (UInt32), salt, subkey }`. The first byte is a version marker, `0x01` representing V3.

The export program will detect which version of hashing is used and parse out the salt, hash, iterations, and algorithm. The exported `users.json` file has a property named [field]#encryptionScheme#. For V2, the [field]#encryptionScheme# value will be set to `example-asp-identity-v2`. For V3, the algorithm will be set to `salted-pbkdf2-hmac-sha256`.

The ASP.NET Identity V3 hashing algorithm is link:/docs/v1/tech/reference/password-hashes#salted-pbkdf2-hmac-sha-256[directly supported by FusionAuth].

The ASP.NET Identity V2 hashing algorithm is not directly supported by FusionAuth. If you have V2 hashes, you will need to install a custom hashing plugin in FusionAuth. This is covered in detail in the <<Add the ASP.NET Identity V2 Hashing Plugin>> section further on in this guide.

If you have not used ASP.NET Identity or if you have created your own password hashing algorithm, you will need to update the export program to use this hashing algorithm and create a custom hashing plugin for FusionAuth if necessary. FusionAuth supports link:/docs/v1/tech/reference/password-hashes[these hashing algorithms] out of the box, so you can check if your algorithm is already supported.

Once you have customized the export program to your Duende IdentityServer implementation, run it. It will output a `users.json` file in the same directory as the running program, usually the `bin/Debug/net6.0` folder.

Once the export is complete, you should have a JSON file called `users.json` containing user objects that look something like this:

[source,json]
----
{
  "users": [
    {
      "active": true,
      "birthDate": null,
      "insertInstance": 1680463413000,
      "data": {
        "migrated": true,
        "favoriteColors": "red"
      },
      "email": "richard@example.com",
      "expiry": null,
      "firstName": "",
      "fullName": "",
      "id": "004eba25-8f8a-4571-ac02-d4d618fa0e28",
      "lastLoginInstant": 0,
      "lastName": "",
      "middleName": "",
      "mobilePhone": "",
      "password": "kYvylojznO+rLOZm+Y0r3q52aFrtIwJucApZY8HF/wk=",
      "salt": "dFilBnTpkMaB5NnPGEaBTg==",
      "factor": 10000,
      "encryptionScheme": "salted-pbkdf2-hmac-sha256",
      "passwordChangeRequired": false,
      "passwordLastUpdateInstant": 0,
      "preferredLanguages": [
        "en"
      ],
      "identityProviders": {},
      "timezone": null,
      "twoFactorEnabled": false,
      "username": "alice",
      "verified": true
    }
 ]
}
----

Check the output for any errors and to make sure the data looks correct. If you have any issues, you can modify the export program to output more information about the users being exported.

Also check if there are any [field]#encryptionScheme# values that are set to  `example-asp-identity-v2`. If there are, you will need to create a custom hashing plugin for FusionAuth. This is covered in detail in the <<Add the ASP.NET Identity V2 Hashing Plugin>> section further on in this guide.


== Importing Users

Next, import the user data. Here are the steps we need to take.

1. Set Up FusionAuth.
2. Get the Script.
3. Install Needed Gems.
4. Use the Script.
5. Verify the Import.
6. The Final Destination of Imported Users.

=== Set Up FusionAuth

include::docs/v1/tech/migration-guide/_set-up-fusionauth.adoc[]

==== Create a Test Tenant

include::docs/v1/tech/migration-guide/_create-test-tenant.adoc[]

==== Create a Test Application

include::docs/v1/tech/migration-guide/_create-test-application.adoc[]

==== Add an API Key

include::docs/v1/tech/migration-guide/_create-api-key-social.adoc[]

==== Add the ASP.NET Identity V2 Hashing Plugin

Some older IdentityServer systems using ASP.NET Identity may still have password hashes created by the V2 version of the ASP.NET Identity hashing scheme. FusionAuth does not support this scheme directly, but does link:/docs/v1/tech/plugins/custom-password-hashing[support plugins for custom hashing].

FusionAuth has a repository for https://github.com/FusionAuth/fusionauth-contrib[community-contributed examples and code]. This repo contains a password hash plugin called `ExampleASPIdentityV2PasswordEncryptor`. To extend FusionAuth to support ASP.NET Identity V2 hashes, follow the instructions in the article link:/docs/v1/tech/plugins/writing-a-plugin[writing a plugin] using the plugin in the contributed examples. A quick summary of the steps:

* Clone the https://github.com/FusionAuth/fusionauth-contrib[community-contributed examples and code] repository.
* Navigate to the `Password Hashing Plugins` directory.
* Install Java JDK 8 or higher, for example, from https://jdk.java.net/20/[https://jdk.java.net/20/].
* Install https://maven.apache.org/[Maven].
* Install http://savantbuild.org/[Savant].
* Run `mvn install` to test that the plugin builds.
* Run `mvn clean compile package` to create the plugin JAR file.
* Copy the plugin `.jar` file from the `./target` directory to the `plugin` directory of your FusionAuth installation.
** On Linux and macOS, the plugin directory is `/usr/local/fusionauth/plugins`.
** On Windows, the plugin directory is `\fusionauth\plugins`.
* Restart FusionAuth.

After installing the plugin and restarting FusionAuth, you can verify that the plugin is installed by navigating to [breadcrumb]#Tenants -> Your Tenant#, then the [breadcrumb]#Password# tab. Under the [breadcrumb]#Cryptographic hash settings# section, you should see the new hash scheme available in the [uielement]#Scheme# dropdown. Only check that the plugin is listed, don't select it or any new user will be created with that hash scheme. Rather than selecting the plugin here, it is specified per user in the `users.json` file.

If the plugin doesn't show up, please review the link:/docs/v1/tech/plugins/writing-a-plugin#troubleshooting[plugin troubleshooting steps].

=== Get the Script

include::docs/v1/tech/migration-guide/_get-script.adoc[]

=== Install Needed Gems

The following gems must be available to the import script:

* `date`
* `json`
* `optparse`
* `securerandom`
* `fusionauth_client`

It is likely that all of these will be on your system already, except the `fusionauth_client` gem.

If you have `bundler` installed, run `bundle install` in the `duende` directory. Otherwise, install the needed gems another way.

=== Use the Script

You can see the output of the script by running it with the `-h` option:

[source,sh,title=Running the import script with the help command line switch]
----
ruby ./import.rb -h
----

The output will be similar to this:

[source,sh,title=The help output of the import.rb script]
----
Usage: import.rb [options]
    -l, --link-social-accounts       Link social accounts, if present, after import. This operation is slower than an import.
    -r APPLICATION_IDS,              A comma separated list of existing applications Ids. All users will be registered for these applications.
        --register-users
    -o, --only-link-social-accounts  Link social accounts with no import.
    -u, --users-file USERS_FILE      The exported JSON user data file from IdentityServer. Defaults to users.json.
    -f FUSIONAUTH_URL,               The location of the FusionAuth instance. Defaults to http://localhost:9011.
        --fusionauth-url
    -k, --fusionauth-api-key API_KEY The FusionAuth API key.
    -t TENANT_ID,                    The FusionAuth tenant id. Required if more than one tenant exists.
        --fusionauth-tenant-id
    -h, --help                       Prints this help.
----

For this script to work correctly, set the following switches, unless the defaults work for you:

* `-u` should point to the location of the user export file you obtained, unless the default works.
* `-f` should point to your FusionAuth instance. If you are testing locally, it will probably be `\http://localhost:9011`.
* `-k` should be set to the value of the API key created above.
* `-t` should be set to the Id of the testing tenant created above.

The `-o` and `-l` switches will attempt to create links for any users authenticated via Google or another social identity provider found in the users data file.

If you are loading users with social account authentication, you must create the social identity providers in FusionAuth beforehand or the links will fail. Additionally, creating a link is not currently optimized in the same way that loading a user is. It may make sense to import all the users in one pass (omitting the `-l` switch) and then create the links using the `-o` switch in a second pass, after the users are imported.

[NOTE.note]
====
The social account linking functionality will only work with FusionAuth version 1.28 or above. The `fusionauth_client` library must be >= 1.28.
====

When you run the script, you should get an output similar to the following:

[source,shell,title=Import script output]
----
$ ruby ./import.rb -f http://localhost:9011 -k '...' -t '...' -u users.json
FusionAuth Importer : IdentityServer
 > User file: users.json
 > Call FusionAuth to import users
 > Import success
Duplicate users 0
Import complete. 2 users imported.
----

==== Enhancing the Script

You may want to migrate additional data. Currently, the following attributes are migrated:

* `user_id`
* `email`
* `email_verified`
* `username`
* `insertInstance`
* the password hash and supporting attributes, if available
* `registrations`, if supplied

The migrated user will have the original Duende IdentityServer user Id. If you have additional user attributes to migrate, review and modify the `map_user` method.

You may also want to assign Roles or associate users with Groups by creating the appropriate JSON data structures in the import call. These are documented in the link:/docs/v1/tech/apis/users#import-users[Import User API docs]. This will require modifying the `import.rb` code.

=== Verify the Import

include::docs/v1/tech/migration-guide/_verify-import.adoc[]

=== The Final Destination of Imported Users

include::docs/v1/tech/migration-guide/_final-destination.adoc[]

== What to Do Next

include::docs/v1/tech/migration-guide/_what-next.adoc[]

== Additional Support

include::docs/v1/tech/migration-guide/_additional-support.adoc[]

:migration_source_name!:
:migration_source_dir!:
