---
layout: doc
title: Migration From Duende
description: How to migrate your users to FusionAuth from Duende.
---
:page-liquid:

:migration_source_name: Duende
:migration_source_dir: duende
:script_supports_social_logins: true
:add-tenant-image-role: bottom-cropped
:extra_permissions_text:


== Overview

This document will help you migrate off of Duende Indentity Server.

This guide assumes you have installed FusionAuth. If you have not, please link:/docs/v1/tech/installation-guide/[view our installation guides] and install FusionAuth before you begin. For more general migration information, please view the link:/docs/v1/tech/migration-guide/general[FusionAuth migration guide].

* <<Planning Considerations>>
** <<Obtaining User Data>>
** <<Mapping User Attributes>>
** <<Social Logins>>
** <<Other Entities>>
** <<Login UI>>
* <<Exporting Users>>
** <<Create a User File>>
* <<Importing Users>>
** <<Set Up FusionAuth>>
** <<Get the Script>>
** <<Install Needed Gems>>
** <<Use the Script>>
** <<Verify the Import>>
** <<The Final Destination of Imported Users>>
* <<What to Do Next>>
* <<Additional Support>>

There are a number of different ways applications can be integrated with
Firebase, and it would be difficult to cover them all. This guide
mentions the typical parts of a bulk migration and focuses on migrating
user data from a Firebase managed user database into FusionAuth.

== Planning Considerations

=== Obtaining User Data

You can use the Firebase CLI or API to export user data. This guide uses
the CLI, but if you have a large number of users, or want to build the 
migration into your application, the API might be useful. 
Firebase also has a https://firebase.google.com/docs/firestore/manage-data/export-import[high level export guide worth
reviewing].

If you haven't already installed and set up the Firebase CLI, you can
follow the
https://firebase.google.com/docs/cli#install-cli-mac-linux[guide here]
to do so.


=== Mapping User Attributes

include::docs/v1/tech/migration-guide/_mapping-user-attributes.adoc[]

=== Social Logins

include::docs/v1/tech/migration-guide/_social-login-note.adoc[]

include::docs/v1/tech/migration-guide/_social-login-migration.adoc[]

=== Other Entities

:other_migrated_entities: connections or roles
include::docs/v1/tech/migration-guide/_other-entities-intro.adoc[]
:other_migrated_entities!:

* In Firebase, sign-in providers are a source of data for users.
FusionAuth calls these Identity Providers.
* Observers are ways for you to customize authentication
or authorization workflows. FusionAuth has a similar concept called
Lambdas.
* With Firebase, Applications are what your
users can log in to. FusionAuth refers to these as Applications as well.
* Projects are a high level construct which groups entities such as
users and applications together. FusionAuth calls these Tenants.
* For Firebase, Roles can be implemented using a combination of https://firebase.google.com/docs/auth/admin/custom-claims[custom claims and security rules.] FusionAuth has Roles and they are defined on an Application by Application basis.
* Refresh tokens allow JWTs to be refreshed without a user logging in.
These can be migrated using the link:/docs/v1/tech/apis/users#import-refresh-tokens[Import Refresh Tokens API].
* Firebase has many other products your applications might be using, from Cloud Firestore for data, Analytics and more. FusionAuth does not have equivalents for these products, and is focused only on authentication. You can use FusionAuth in conjunction with all the other Firebase products.

[NOTE]
====
In FusionAuth, users are explicitly mapped to applications with a link:/docs/v1/tech/core-concepts/registrations[Registration].

In Firebase, users have access to all Firebase Applications in the same project by default. You can control access by using Roles and Security Rules per Application if you need.
====


==== Identifiers 

When creating an object with the FusionAuth API, you can specify the Id. It must be a link:/docs/v1/tech/reference/data-types#uuids[UUID].

This works for users, applications, and tenants, among others.

Firebase uses a custom UID format. When migrating, a new UUID will be created for the user on FusionAuth. 

If you have external dependencies on an Id stored in Firebase, you can add a new attribute under `user.data` (such as `user.data.originalId`) with the value of the Firebase Id. Because everything under `user.data` is indexed and available via search, you'll be able to find your users using either the new FusionAuth Id, or the original Firebase one.

=== Login UI

Firebase has pre-built UIs for web, iOS, Android, etc. called FirebaseUI Auth. You can also choose to build your own login page, and call the Firebase APIs. 

FusionAuth’s login experience is similar. You can choose to
build your own login pages or use FusionAuth’s hosted login pages. link:/docs/v1/tech/core-concepts/integration-points#login-options[Read more about these choices].

Once you’ve planned your migration, the next step is to export your user
data from Firebase.

== Exporting Users


Duende IdentityServer does not prescribe where you store your user data. You can store it in a database, in a file, or in a custom data store. How you store your users will determine how you export them. 

1. Install the Firebase CLI
2. Retrieve the Project Id of the Firebase application you want to export the users from
3. Download the exported file in your chosen format


=== Create a User File
 
To download the user file, run the following
https://firebase.google.com/docs/cli/auth[Firebase `auth:export` CLI
command]:

[source,bash]
----
firebase auth:export users.json --format=JSON --project your_project_id
----

Replace `your_project_id` with the Project Id you noted above.

After the export finishes, you’ll end up with a JSON file called
`users.json`. It should look something like this:

[source,json]
----
{"users": [
    {
      "localId": "OzDdXA7LwoR7lX2MH7AXaEmmn5u2",
      "email": "user1@test.com",
      "emailVerified": false,
      "passwordHash": "0fn2PA6FmYZynpk9cvekSgbJTXa7j0XQAwtp4XuyyuIYzX5hASd4mB4GFeaS5OiG9mENrvt+sPoZmwVjvEDZ2Q==",
      "salt": "+mkMRRbwdwqJkA==",
      "createdAt": "1648020042135",
      "disabled": false,
      "providerUserInfo": []
    },
    {
      "localId": "bBd018SFAYa8fkkZdgAz3PEgaKj1",
      "email": "user2@test.com",
      "emailVerified": false,
      "passwordHash": "TFJtUjKMN4dNcp5IuSwaeRkPwjwpkp9ZlqXuL/QHsQ3097QLHnZWccWt2yThLa0Q5rmbuOOXoqzoHBZM8x3GpQ==",
      "salt": "RHQ5jbaxNJ1lDA==",
      "createdAt": "1648020072141",
      "disabled": false,
      "providerUserInfo": []
    }
]}
----

== Importing Users

Next up, import the user data. Here are the steps we need to take.

1. Set Up FusionAuth
2. Get the Script
3. Install Needed Gems
4. Use the Script
5. Verify the Import
6. The Final Destination of Imported Users

=== Set Up FusionAuth

include::docs/v1/tech/migration-guide/_set-up-fusionauth.adoc[]

==== Create a Test Tenant

include::docs/v1/tech/migration-guide/_create-test-tenant.adoc[]

==== Create a Test Application

include::docs/v1/tech/migration-guide/_create-test-application.adoc[]

==== Add an API Key

include::docs/v1/tech/migration-guide/_create-api-key-social.adoc[]

=== Get the Script

include::docs/v1/tech/migration-guide/_get-script.adoc[]

=== Install Needed Gems

The following gems must be available to the import script:

* `date`
* `json`
* `optparse`
* `securerandom`
* `fusionauth_client`

Most likely all of these will be on your system already, except the
`fusionauth_client` gem.

If you have `bundler` installed, run `bundle install` in the `firebase`
directory. Otherwise install the needed gems in some other way.

=== Use the Script

You can see the output of the script by running it with the `-h` option:

Running the import script with the help command line switch

[source,sh]
----
ruby ./import.rb -h
----

The output will be similar to this:

[source,sh,title=The help output of the import.rb script]
----
Usage: import.rb [options]
    -l, --link-social-accounts       Link social accounts, if present, after import. This operation is slower than an import.
    -r APPLICATION_IDS,              A comma separated list of existing applications Ids. All users will be registered for these applications.
        --register-users
    -o, --only-link-social-accounts  Link social accounts with no import.
    -u, --users-file USERS_FILE      The exported JSON user data file from Firebase. Defaults to users.json.
    -f FUSIONAUTH_URL,               The location of the FusionAuth instance. Defaults to http://localhost:9011.
        --fusionauth-url
    -k, --fusionauth-api-key API_KEY The FusionAuth API key.
    -t TENANT_ID,                    The FusionAuth tenant id. Required if more than one tenant exists.
        --fusionauth-tenant-id
    -m, --map-firebase-id            Whether to map the Firebase id for normal imported users to the FusionAuth user id.
    -h, --help                       Prints this help.
----

For this script to work correctly, set the following switches, unless the defaults work for you:

* `-u` should point to the location of the user export file you obtained, unless the default works.
* `-f` must point to your FusionAuth instance. If you are testing locally, it will probably be `http://localhost:9011`.
* `-k` needs to be set to the value of the API key created above.
* `-t` should be set to the Id of the testing tenant created above.

The `-o` and `-l` switches will attempt to create links for any social users (where the user authenticated via Google or another social provider) found in the users data file.

If you are loading social users, you must create the social providers in FusionAuth beforehand, or the links will fail. Additionally, creating a link is not currently optimized in the same way that loading users is. So it may make sense to import all the users in one pass (omitting the `-l` switch). Then, after the users are imported, create the links using the `-o` switch in a second pass.

[NOTE.note]
====
The social account linking functionality will only work with FusionAuth versions above or equal to 1.28. The `fusionauth_client` library must be >= 1.28 as well.
====

You may or may not want to use the `-m` switch, which takes the Firebase Id for users without a social login and uses the same value for the FusionAuth user Id. If you have external systems reliant on the Firebase user identifier, set this. Doing so ensures imported users have the same Id as they did in Firebase. Otherwise, you can omit this switch.

When you run the script, you’ll see output like:

[source,shell,title=Import script output]
----
$ ruby ./import.rb -f http://localhost:9011 -k '...' -u user-data.json
FusionAuth Importer : Firebase
 > User file: user-data.json
 > Call FusionAuth to import users
 > Import success
Duplicate users 0
Import complete. 2 users imported.
----

==== Enhancing the Script

You may also want to migrate additional data. Currently, the following
attributes are migrated:

* `user_id`
* `email`
* `email_verified`
* `username`
* `insertInstant`
* the password hash and supporting attributes, if available
* `registrations`, if supplied

The migrated user will have the Firebase project Id and original user Id
stored on the `user.data` object. If you have additional user attributes
to migrate, review and modify the `map_user` method.

You may also want to assign Roles, or associate users with Groups, by
creating the appropriate JSON data structures in the import call. These
are documented in the
https://fusionauth.io/docs/v1/tech/apis/users#import-users[Import User
API docs]. This will require modifying the `import.rb` code.

=== Verify the Import

include::docs/v1/tech/migration-guide/_verify-import.adoc[]

=== The Final Destination of Imported Users

include::docs/v1/tech/migration-guide/_final-destination.adoc[]

== What to Do Next

include::docs/v1/tech/migration-guide/_what-next.adoc[]

== Additional Support

include::docs/v1/tech/migration-guide/_additional-support.adoc[]

:migration_source_name!:
:migration_source_dir!:
