---
layout: doc
title: Migration From Duende IdentityServer
description: How to migrate your users to FusionAuth from DuendeIdentityServer
---
:page-liquid:

:migration_source_name: Duende
:migration_source_dir: duende
:script_supports_social_logins: true
:add-tenant-image-role: bottom-cropped
:extra_permissions_text:

== Overview

This document will help you migrate off of Duende IdentityServer, and onto FusionAuth.

This guide assumes you have installed FusionAuth. If you have not, please link:/docs/v1/tech/installation-guide/[view our installation guides] and install FusionAuth before you begin. For more general migration information, please view the link:/docs/v1/tech/migration-guide/general[FusionAuth migration guide].

* <<Planning Considerations>>
** <<Obtaining User Data>>
** <<Mapping User Attributes>>
** <<Social Logins>>
** <<Other Entities>>
** <<Login UI>>
* <<Exporting Users>>
** <<Create a User File>>
* <<Importing Users>>
** <<Set Up FusionAuth>>
** <<Add the ASP Identity V2 Hashing Plugin>>
** <<Get the Script>>
** <<Install Needed Gems>>
** <<Use the Script>>
** <<Verify the Import>>
** <<The Final Destination of Imported Users>>
* <<What to Do Next>>
* <<Additional Support>>

There are a number of different ways applications can be integrated with Duende IdentityServer, and it would be difficult to cover them all. This guide mentions the typical parts of a bulk migration and focuses on migrating user data from a Duende IdentityServer user database into FusionAuth.

== Planning Considerations

=== Obtaining User Data

Duende IdentityServer does not prescribe where you store your user data. You can store it in any database of your choice, in a file, or in a custom data store. How you store your users will determine how you export them. This guide assumes your IdentityServer installation is using link:https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio[ASP Identity] to manage users and passwords, and that you are using link:https://www.microsoft.com/en-us/sql-server/[MS SQL Server as your IdentityServer database]. If you are using another custom setup, this guide should still be helpful as a starting point, but you will need to modify the export program to match your setup.

=== Mapping User Attributes

include::docs/v1/tech/migration-guide/_mapping-user-attributes.adoc[]

=== Social Logins

include::docs/v1/tech/migration-guide/_social-login-note.adoc[]

include::docs/v1/tech/migration-guide/_social-login-migration.adoc[]

=== Other Entities

:other_migrated_entities: connections or roles
include::docs/v1/tech/migration-guide/_other-entities-intro.adoc[]
:other_migrated_entities!:

* In Duende IdentityServer, External Identity Providers are a source of data for users. FusionAuth calls these Identity Providers.
* Being a framework, login flows can be highly customizable with Duende IdentityServer, using custom code in your host application. FusionAuth authentication flows can be customized with a feature called link:/docs/v1/tech/lambdas[Lambdas].
* Duende IdentityServer has the concept of Clients. These are a set of credentials and authentication flow settings. FusionAuth refers to these as Applications.
* FusionAuth Tenants are a high level construct which groups entities such as users and applications together. Duende IdentityServer does not have such a concept. Each IdentityServer deployment is in effect a Tenant.
* For Duende IdentityServer, Roles can be implemented through connecting to .Net IdentityStore, or through custom code. FusionAuth has Roles and they are defined on an Application by Application basis.
* Refresh tokens allow JWTs to be refreshed without a user logging in. These can be migrated using the link:/docs/v1/tech/apis/users#import-refresh-tokens[Import Refresh Tokens API].
* Since Duende IdentityStore is a framework used to build custom authentication servers, the actual functionality and features of the particular custom server you are migrating from could be very wide. FusionAuth may not have equivalents for these custom features and functionality, and is focused only on authentication.

[NOTE]
====
In FusionAuth, users are explicitly mapped to Applications with a link:/docs/v1/tech/core-concepts/registrations[Registration].

In Duende IdentityServer, users have access to all Clients in the same server by default. You can control access by using Roles and Security Rules per application if you need.
====

==== Identifiers 

When creating an object with the FusionAuth API, you can specify the Id. It must be a link:/docs/v1/tech/reference/data-types#uuids[UUID].

This works for users, applications, and tenants, among others.

Duende IdentityServer implementations may use any format for an Id. Often times this will be a UUID if using ASP.Net Identity for user management. When migrating, this UUID can be imported when creating the user on FusionAuth.   

If you have an IdentityServer implementation that does not use a UUID as the user Id, you can add a new attribute under `user.data` (such as `user.data.originalId`) with the value of the Duende IdentityServer Id. Because everything under `user.data` is indexed and available via search, you'll be able to find your users using either a new FusionAuth UUID Id, or the original Duende IdentityServer one.

=== Login UI

Duende IdentityServer does not prescribe a particular login UI. Login pages are highly variable across Duende IdentityServer implementations. 

FusionAuth's login experience follows 2 paths. You can choose to build your own login pages or use FusionAuth's hosted login pages. link:/docs/v1/tech/core-concepts/integration-points#login-options[Read more about these choices].

Once you've planned your migration, the next step is to export your user data from Duende IdentityServer.

== Exporting Users

Duende IdentityServer does not prescribe where you store your user data. You can store it in a relational database, in a file, or in a custom data store. How you store your users will determine how you export them. Duende IdentityServer provides a package to integrate with link:https://docs.duendesoftware.com/identityserver/v6/aspnet_identity/[ASP.NET Identity], which is often used to assist in manage users, and will determine the format the users are stored in.

In this guide, we will suggest a file format to export your users. This format is JSON, and is the same format used by FusionAuth. This will allow you to import your users into FusionAuth using the FusionAuth API. How the file is populated will be determined by your Duende IdentityServer implementation. An alternative is to create a custom tool to read your user data from your Duende IdentityServer database and directly call the link:https://fusionauth.io/docs/v1/tech/apis/users[FusionAuth API to create users]. 


=== Create a User File
 
We've created a sample C# export program to export users from a Duende IdentityServer database to a JSON file. This program assumes you are using link:https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio[ASP.NET Identity]. You can find the repo with the source code for the export program link:https://github.com/TheMiniDriver/identity-server-export[here].

Clone the repo and open the solution in Visual Studio. You will need to update the `connectionString` variable in the `Program.cs` file with your database connection information. The export program assumes that the users are stored in the standard ASP.NET Identity tables, namely `AspNetUsers` and `AspNetUserLogins`. If you are using a different table, or have extended the ASP.NET Identity tables, you will need to update the program to select from the correct tables. You can do this by modifying the `SqlCommand` in the `Program.cs` file. You can also modify the mapping of the user data to the `User` export objects in the `Program.cs` file.

The program also assumes that you have used ASP Identity to create the user's password hashes. ASP Identity stores the salt, hash and iteration in a single base64 encoded string. There are 2 versions of hashing used, as can be seen in the link:https://github.com/dotnet/aspnetcore/blob/v6.0.14/src/Identity/Extensions.Core/src/PasswordHasher.cs[ASP Identity source code].   

* V2 - PBKDF2 with HMAC-SHA1, 128-bit salt, 256-bit subkey, 1000 iterations. The format of the base64 encoded hash string is `{ 0x00, salt, subkey }`. The first byte is a version marker, `0x00` representing V2. The next 128 bits are the salt, and the remaining 256 bits are the subkey or salted password hash. The iteration count is hardcoded to 1000.
* V3 - PBKDF2 with HMAC-SHA256, 128-bit salt, 256-bit subkey, 10000 iterations. The format  of the base64 encoded hash string is a little more complicated: `{ 0x01, prf (UInt32), iter count (UInt32), salt length (UInt32), salt, subkey }`. The first byte is a version marker, `0x01` representing V3.

The export program will detect which version of hashing is used and parse out the salt, hash, iterations and algorithm.The exported `users.json` file has a property named `encryptionScheme`. For V2, the `encryptionScheme` value will be set to `example-asp-identity-v2`. For V3, the algorithm will be set to `salted-pbkdf2-hmac-sha256`.

The ASP Identity V3 hashing algorithm is directly supported by FusionAuth, called the  link:docs/v1/tech/reference/password-hashes#salted-pbkdf2-hmac-sha-256[salted-pbkdf2-hmac-sha256] algorithm in FusionAuth.

The ASP Identity V2 hashing algorithm is not directly supported by FusionAuth. If you have V2 hashes, you will need to install a custom hashing plugin in FusionAuth. This is covered in detail in the "Add the ASP Identity V2 Hashing Plugin" section further on in this guide.

If you have not used ASP Identity, or if you have created your own password hashing algorithm, you will need to update the export program to use this hashing algorithm, as well as create a custom hashing plugin for FusionAuth if necessary. FusionAuth supports link:https://fusionauth.io/docs/v1/tech/reference/password-hashes[these hashing algorithms] out of the box, so you can check if your algorithm is already supported.

After you have customized the export program to your IdentityServer implementation, you can run the program. The program will output a `users.json` file in the same directory as the program, usually the `bin/Debug/net6.0` folder.

After the export finishes, you'll end up with a JSON file called `users.json`. It should contain user objects that look something like this:

[source,json]
----
{
  "users": [
    {
      "active": true,
      "birthDate": null,
      "insertInstance": 1680463413000,
      "data": {
        "migrated": true,
        "favoriteColors": "red"
      },
      "email": "jared@piedpiper.com",
      "expiry": null,
      "firstName": "",
      "fullName": "",
      "id": "004eba25-8f8a-4571-ac02-d4d618fa0e28",
      "lastLoginInstant": 0,
      "lastName": "",
      "middleName": "",
      "mobilePhone": "",
      "password": "kYvylojznO+rLOZm+Y0r3q52aFrtIwJucApZY8HF/wk=",
      "salt": "dFilBnTpkMaB5NnPGEaBTg==",
      "factor": 10000,
      "encryptionScheme": "salted-pbkdf2-hmac-sha256",
      "passwordChangeRequired": false,
      "passwordLastUpdateInstant": 0,
      "preferredLanguages": [
        "en"
      ],
      "identityProviders": {},
      "timezone": null,
      "twoFactorEnabled": false,
      "username": "alice",
      "verified": true
    }
]}

Check the output for any errors, and that the data looks correct. If you have any issues, you can modify the export program to output more information about the users being exported. 

Also check if there are any `encryptionScheme` values that are set to  `example-asp-identity-v2`. If there are, you will need to create a custom hashing plugin for FusionAuth. This is covered in detail in the "Add the ASP Identity V2 Hashing Plugin" section further on in this guide.
----

== Importing Users

Next up, import the user data. Here are the steps we need to take.

1. Set Up FusionAuth
2. Get the Script
3. Install Needed Gems
4. Use the Script
5. Verify the Import
6. The Final Destination of Imported Users

=== Set Up FusionAuth

include::docs/v1/tech/migration-guide/_set-up-fusionauth.adoc[]

==== Create a Test Tenant

include::docs/v1/tech/migration-guide/_create-test-tenant.adoc[]

==== Create a Test Application

include::docs/v1/tech/migration-guide/_create-test-application.adoc[]

==== Add an API Key

include::docs/v1/tech/migration-guide/_create-api-key-social.adoc[]

==== Add the ASP Identity V2 Hashing Plugin

Some older IdentityServer systems using ASP Identity may still have password hashes created by the V2 version of the ASP Identity hashing scheme. FusionAuth does not support this scheme directly, but does link:/docs/v1/tech/plugins/custom-password-hashing[support plugins for custom hashing].

FusionAuth has a repository for link:https://github.com/FusionAuth/fusionauth-contrib[community contributed examples and code]. This repo contains a password hash plugin called "example-asp-identity-v2". To extend FusionAuth to support ASP Identity V2 hashes, follow the instructions in the article https://fusionauth.io/docs/v1/tech/plugins/writing-a-plugin[writing a plugin], using the plugin in the contributed examples. A quick summary of the steps:

* Clone the link:https://github.com/FusionAuth/fusionauth-contrib[community contributed examples and code] repository.
* Navigate to the `Password Hashing Plugins` directory.
* Install a Java JDK 8 or higher, for example from link:https://jdk.java.net/20/[https://jdk.java.net/20/]
* Install link:https://maven.apache.org/[Maven]
* Install link:http://savantbuild.org/[Savant]
* Run `mvn install` to test that the plugin builds.
* Run `mvn clean compile package` to create the plugin jar file.
* Copy the plugin `.jar` file from the `./target` directory to the `plugin` directory of your FusionAuth installation. 
** On linux and macOS, this is `/usr/local/fusionauth/plugins`
** On Windows, it is `\fusionauth\plugins`
* Restart FusionAuth.

After installing the plugin and restarting FusionAuth, you can verify that the plugin is installed by navigating to [breadcrumb]#Tenants -> Your Tenant# you created earlier. Navigate to the [breadcrumb]#Password# tab. Under the [breadcrumb]#Cryptographic hash settings# section, you should see the new hash scheme available in the [field]#Scheme# dropdown. Only check that the plugin is listed - don't select it, or any new user will be created with that hash scheme. Rather than selecting the plugin here, it is specified per user in the user json file. 

If the plugin doesn't show up, please review the link:/docs/v1/tech/plugins/writing-a-plugin#troubleshooting[plugin troubleshooting steps].

=== Get the Script

include::docs/v1/tech/migration-guide/_get-script.adoc[]

=== Install Needed Gems

The following gems must be available to the import script:

* `date`
* `json`
* `optparse`
* `securerandom`
* `fusionauth_client`

Most likely all of these will be on your system already, except the
`fusionauth_client` gem.

If you have `bundler` installed, run `bundle install` in the `identityserver`
directory. Otherwise install the needed gems in some other way.

=== Use the Script

You can see the output of the script by running it with the `-h` option:

Running the import script with the help command line switch

[source,sh]
----
ruby ./import.rb -h
----

The output will be similar to this:

[source,sh,title=The help output of the import.rb script]
----
Usage: import.rb [options]
    -l, --link-social-accounts       Link social accounts, if present, after import. This operation is slower than an import.
    -r APPLICATION_IDS,              A comma separated list of existing applications Ids. All users will be registered for these applications.
        --register-users
    -o, --only-link-social-accounts  Link social accounts with no import.
    -u, --users-file USERS_FILE      The exported JSON user data file from IdentityServer. Defaults to users.json.
    -f FUSIONAUTH_URL,               The location of the FusionAuth instance. Defaults to http://localhost:9011.
        --fusionauth-url
    -k, --fusionauth-api-key API_KEY The FusionAuth API key.
    -t TENANT_ID,                    The FusionAuth tenant id. Required if more than one tenant exists.
        --fusionauth-tenant-id
    -h, --help                       Prints this help.
----

For this script to work correctly, set the following switches, unless the defaults work for you:

* `-u` should point to the location of the user export file you obtained, unless the default works.
* `-f` must point to your FusionAuth instance. If you are testing locally, it will probably be `http://localhost:9011`.
* `-k` needs to be set to the value of the API key created above.
* `-t` should be set to the Id of the testing tenant created above.

The `-o` and `-l` switches will attempt to create links for any social users (where the user authenticated via Google or another social provider) found in the users data file.

If you are loading social users, you must create the social providers in FusionAuth beforehand, or the links will fail. Additionally, creating a link is not currently optimized in the same way that loading users is. So it may make sense to import all the users in one pass (omitting the `-l` switch). Then, after the users are imported, create the links using the `-o` switch in a second pass.

[NOTE.note]
====
The social account linking functionality will only work with FusionAuth versions above or equal to 1.28. The `fusionauth_client` library must be >= 1.28 as well.
====

When you run the script, you’ll see output like:

[source,shell,title=Import script output]
----
$ ruby ./import.rb -f http://localhost:9011 -k '...' -u user-data.json
FusionAuth Importer : IdentityServer
 > User file: user-data.json
 > Call FusionAuth to import users
 > Import success
Duplicate users 0
Import complete. 2 users imported.
----

==== Enhancing the Script

You may also want to migrate additional data. Currently, the following
attributes are migrated:

* `user_id`
* `email`
* `email_verified`
* `username`
* `insertInstant`
* the password hash and supporting attributes, if available
* `registrations`, if supplied

The migrated user will have the IdentityServer original user Id. If you have additional user attributes
to migrate, review and modify the `map_user` method.

You may also want to assign Roles, or associate users with Groups, by creating the appropriate JSON data structures in the import call. These are documented in the https://fusionauth.io/docs/v1/tech/apis/users#import-users[Import User API docs]. This will require modifying the `import.rb` code.

=== Verify the Import

include::docs/v1/tech/migration-guide/_verify-import.adoc[]

=== The Final Destination of Imported Users

include::docs/v1/tech/migration-guide/_final-destination.adoc[]

== What to Do Next

include::docs/v1/tech/migration-guide/_what-next.adoc[]

== Additional Support

include::docs/v1/tech/migration-guide/_additional-support.adoc[]

:migration_source_name!:
:migration_source_dir!:
