---
layout: doc
title: Migration From Keycloak
description: How to migrate your users to FusionAuth from Keycloak.
---
:page-liquid:

:migration_source_name: Keycloak
:migration_source_dir: keycloak
:add-tenant-image-role: 

== Overview

This document will help you migrate off of Keycloak. 

If you are looking to compare FusionAuth and Keycloak, link:/blog/2019/03/06/keycloak-fusionauth-comparison/[this document may help]. 

This guide assumes you have installed FusionAuth. If you have not, please link:/docs/v1/tech/installation-guide/[view our installation guides] and install FusionAuth before you begin. For more general migration information, please view the link:../general/[FusionAuth migration guide].

There are a number of different ways applications can be integrated with Keycloak, and it would be difficult to cover them all. This guide mentions the typical parts of a bulk migration and in particular focuses on migrating user data from a Keycloak user database into FusionAuth. 

[NOTE.note]
====
This guide was tested against Keycloak 15.
====

* <<Planning Considerations>>
** <<Obtaining User Data>>
** <<Mapping User Attributes>>
** <<Social Logins>>
** <<Other Entities>>
* <<Exporting Users>>
* <<Importing Users>>
** <<Set Up FusionAuth>>
** <<Get the Script>>
** <<Install Needed Gems>>
** <<Use the Script>>
** <<Verify the Import>>
** <<The Final Destination of Imported Users>>
* <<What to Do Next>>
* <<Additional Support>>

== Planning Considerations

=== Obtaining User Data

You will need read only database access to your Keycloak database. As part of the planning process, gather the credentials that will allow you to run SQL queries against this database.

You will need read only access to these tables:

* `USER_ENTITY`
* `CREDENTIAL`

=== Mapping User Attributes

include::docs/v1/tech/migration-guide/_mapping-user-attributes.adoc[]

=== Social Logins

include::docs/v1/tech/migration-guide/_social-login-note.adoc[]

include::docs/v1/tech/migration-guide/_social-login-migration.adoc[]

=== Other Entities

:other_migrated_entities: identity providers, clients, or keys
include::docs/v1/tech/migration-guide/_other-entities-intro.adoc[]
:other_migrated_entities!:

* In Keycloak, Identity Providers and User Federation allow user data to remain in external systems of record. FusionAuth has similar concepts of link:/docs/v1/tech/identity-providers/[Identity Providers] and link:/docs/v1/tech/connectors/[Connectors].
* Mappers are ways for you to customize authentication or authorization workflows. FusionAuth has a similar concept called link:/docs/v1/tech/lambdas/[Lambdas].
* Keycloak has the ability to add custom scopes. FusionAuth does not, though there is an https://github.com/FusionAuth/fusionauth-issues/issues/275[open feature request].
* With Keycloak, Clients are what your users can log in to. FusionAuth refers to these as link:/docs/v1/tech/core-concepts/applications/[Applications]. In both cases, you can use either OAuth/OIDC or SAML to do so.
* Realms are a high level construct which groups other entities such as users and clients together. FusionAuth calls these link:/docs/v1/tech/core-concepts/tenants/[Tenants]. FusionAuth supports a multi-tenant configuration by default.
* For Keycloak, https://www.keycloak.org/docs/latest/server_admin/#core-concepts-and-terms[Roles] provide information about what your users can do in your custom or off the shelf applications. Roles can be associated with other roles. FusionAuth has link:/docs/v1/tech/core-concepts/roles/[Roles] and they are defined on an Application by Application basis and cannot be composed.
* Refresh tokens allow JWTs to be refreshed without a user logging in. These can be migrated using the link:/docs/v1/tech/apis/users/#import-refresh-tokens[Import Refresh Tokens API]. Keycloak calls these "Offline Sessions"

==== Identifiers 

include::docs/v1/tech/migration-guide/_identifiers.adoc[]

Once you've planned your migration, the next step is to export your user data from Keycloak.

== Exporting Users

To import your users, you'll need their attributes, including their password hashes and other information. Some of these are stored in JSON fields.

include::docs/v1/tech/migration-guide/_password-hash-note.adoc[]

Here's a SQL script that will query the needed fields.

[source,sql]
.Keycloak Export SQL
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-import-scripts/master/keycloak/keycloak-export.sql[]
----

You'll need to run this SQL query in such a way as to get comma separated values (CSV) out of it. Depending on your database, you'll do this differently.

Here's how to generate CSV with MySQL, assuming the SQL above is in `keycloak-export.sql`. You may have to remove the header line from the `out.csv` file.

[source,shell]
.Generate CSV with MySQL
----
cat keycloak-export.sql | mysql -u USER -p keycloak| sed 's/\t/,/g' > out.csv
----

Here's how to generate CSV with PostgreSQL. Replace `CONTENTS OF SQL FILE` with the SQL above.

[source,shell]
.Generate CSV with PostgreSQL
----
psql -W -h localhost -p5433 -U USER -d fusionauth -c "Copy (CONTENTS OF SQL FILE) To STDOUT With CSV HEADER DELIMITER ',';" > out.csv
----

At the end of this process, you'll have a file that looks like:

[source,csv]
.Sample User Export
----
FIRST_NAME,LAST_NAME,EMAIL,USERNAME,EMAIL_VERIFIED,ID,PASSWORD,SALT,HASHITERATIONS,ALGORITHM,CREATED_TIMESTAMP,REALM_ID
Test,Example,test@example.com,test,\0,f35a58e2-0247-4c38-aa39-93405e09c677,T6S/56cQy0ahQKohXe61aMOhvFr/PHEPfQbILKMLZKrdfOSo8wc+S6HCYomSJwTgYmdPy2gKh+oQW9UbeCmEwQ==,eYcTxcZhBV+GU9BQRt8Ypw==,27500,pbkdf2-sha256,1634670076567,Test
Test,Example2,test2@example.com,test2,,1709a278-12a5-4126-9542-02f6809a349e,LjFqvhPuUHJdQvWIwVQfqxjeujAWqG/DVQRFoOv62/cTznl9ob4jwWwY6i1RrwGviu5iNPU5VIp03SxDyetyfw==,jVqbuA9k2Mlo37OWXBMKLw==,27500,pbkdf2-sha256,1634670197972,Test
----

Now, you can begin the user import process.

== Importing Users

Next up, import the user data. Here are the steps we need to take:

1. Set Up FusionAuth
1. Get the Script
1. Install Needed Gems
1. Use the Script
1. Verify the Import
1. The Final Destination of Imported Users

=== Set Up FusionAuth

include::docs/v1/tech/migration-guide/_set-up-fusionauth.adoc[]

==== Install the Hashing Plugin

The default Keycloak configuration uses a different hashing algorithm than those which ship with FusionAuth.

You need to install a custom password hashing plugin. The link:/docs/v1/tech/plugins/writing-a-plugin/[documentation for doing so is here].

The FusionAuth team has written a Keycloak compatible plugin https://github.com/FusionAuth/fusionauth-example-password-encryptor/blob/master/src/main/java/com/mycompany/fusionauth/plugins/ExamplePBDKF2HMACSHA256Keylength512PasswordHasher.java[available for download].

If you have configured Keycloak to use a different hashing algorithm, you will need to write and install a plugin using that algorithm.

==== Create a Test Tenant

include::docs/v1/tech/migration-guide/_create-test-tenant.adoc[]

==== Create a Test Application

include::docs/v1/tech/migration-guide/_create-test-application.adoc[]

==== Add an API Key

include::docs/v1/tech/migration-guide/_create-api-key.adoc[]

=== Get the Script

include::docs/v1/tech/migration-guide/_get-script.adoc[]

=== Install Needed Gems

The following gems must be available to the import script:

* `date`
* `csv`
* `optargs`
* `fusionauth_client`

Most likely all of these will be on your system already, except the `fusionauth_client` gem.

If you have `bundler` installed, run `bundle install` in the `keycloak` directory. Otherwise install the needed gems in some other way.

=== Use the Script

You can see the output of the script by running it with the `-h` option:

[source,sh,title=Running the import script with the help command line switch]
----
ruby ./import.rb -h
----

The output will be similar to this:

[source,sh,title=The help output of the import.rb script]
----
Usage: import.rb [options]
    -r APPLICATION_IDS,              A comma separated list of existing applications Ids. All users will be registered for these applications.
        --register-users
    -u, --users-file USERS_FILE      The exported CSV user data file from Keycloak. Defaults to out.csv.
    -f FUSIONAUTH_URL,               The location of the FusionAuth instance. Defaults to http://localhost:9011.
        --fusionauth-url
    -k, --fusionauth-api-key API_KEY The FusionAuth API key.
    -t TENANT_ID,                    The FusionAuth tenant id. Required if more than one tenant exists.
        --fusionauth-tenant-id
    -m, --map-keycloak-user-id       Whether to map the keycloak user id for normal imported users to the FusionAuth user id.
    -h, --help                       Prints this help.
----

For this script to work correctly, set the following switches, unless the defaults work for you:

* `-u` should point to the location of the user export file you created.
* `-f` must point to your FusionAuth instance. If you are testing locally, it will probably be `\http://localhost:9011`.
* `-k` needs to be set to the value of the API key created above.
* `-t` should be set to the Id of the testing tenant created above.

You may or may not want to use the `-m` switch, which takes the Keycloak Id and uses that for the FusionAuth user Id. If you have external systems reliant on the identifier, set this. Doing so ensures imported users have the same Id as they did in Keycloak. Otherwise, you can omit this switch.

When you run the script, you'll see output like:

[source,shell,title=Import script output]
----
$ ruby ./import.rb -f http://localhost:9011 -k '...' -u users.json
FusionAuth Importer : Keycloak
 > User file: users.json
 > Call FusionAuth to import users
 > Import success
Duplicate users 0
Import complete. 2 users imported.
----

==== Enhancing the Script

You may also want to migrate additional data. Currently, the following attributes are migrated:

* `user_id`
* `email`
* `email_verified`
* `username`
* `firstName`
* `lastName`
* `insertInstant`
* the password hash and supporting attributes, if available
* `registrations`, if supplied

The migrated user will have the Keycloak tenant Id and original user Id stored on the `user.data` object. If you have additional user attributes to migrate, review and modify the `map_user` method. 

You may also want to assign Roles, or associate users with Groups, by creating the appropriate JSON data structures in the import call. These are documented in the link:/docs/v1/tech/apis/users/#import-users[Import User API docs]. This will require modifying the `import.rb` code.

=== Verify the Import

include::docs/v1/tech/migration-guide/_verify-import.adoc[]

=== The Final Destination of Imported Users

include::docs/v1/tech/migration-guide/_final-destination.adoc[]

== What to Do Next

include::docs/v1/tech/migration-guide/_what-next.adoc[]

== Additional Support

include::docs/v1/tech/migration-guide/_additional-support.adoc[]

:migration_source_name!:
:migration_source_dir!:
