---
layout: doc
title: Migration From Supabase
description: How to migrate your users to FusionAuth from Supabase.
---
:page-liquid:

:migration_source_name: Supabase
:migration_source_dir: supabase



== Overview

This document will help you migrate off of Supabase Authentication. If
you are looking to compare FusionAuth and Supabase Authentication,
link:https://blog.logrocket.com/firebase-vs-supabase-choosing-right-tool-project/[this document may help].

This guide assumes you have installed FusionAuth. If you have not, please link:/docs/v1/tech/installation-guide/[view our installation guides] and install FusionAuth before you begin. For more general migration information, please view the link:/docs/v1/tech/migration-guide/general[FusionAuth migration guide].

* <<Planning Considerations>>
** <<Obtaining User Data>>
** <<Generating Json User Data>>
** <<Social Logins>>
* <<Exporting Users>>
* <<Importing Users>>
** <<Set Up FusionAuth>>
** <<Get the Script>>
** <<Install Needed Gems>>
** <<Use the Script>>
** <<Verify the Import>>
** <<The Final Destination of Imported Users>>


This guide mentions the typical parts of a bulk migration and focuses on migrating
user data from a Supabase managed user database into FusionAuth.

== Planning Considerations

=== Obtaining User Data

Supabase includes a Postgres database and authentication service, storage, and Edge functions (serverless functions for backend logic). You can write your custom psql script in the SQL Query Editor in your Supabase UI and select the data returned by the script as JSON formatted to FusionAuth format. User data is stored in `auth.users` table in Supabase and can be joined with other tables to pull specific data.

Attached below is a screenshot of the SQL Query Editor in Supabase:

include::img/sql-editor.png

=== Generating Json User Data

The data required can be selected from the `auth` tables unless there are other public tables you have which may container other user specific fields like usernames e.t.c. We created a custom function which returns json data after formatting and mapping the data to Fusionauth's required format.

[source,json]
----
[
  {
    "instance_id": "00000000-0000-0000-0000-000000000000",
    "encrypted_password": "",
    "created_at": 1684248249840.815,
    "provider": "facebook",
    "email": "awaneji.projects@gmail.com",
    "user_id": "facebook|99af46c2-b9e9-4471-81fd-35bdf12957aa",
    "salt": "",
    "password": "hasprovider",
    "tenant": "955a8687-0376-45cb-2f49-26e66050dea2",
    "email_verified": true
  },
  {
    "instance_id": "00000000-0000-0000-0000-000000000000",
    "encrypted_password": "$2a$10$VnxRmsfGTooc.Yy7Ez7L7.bkdHaSzseGwHkjvxZUGaGo5k4XIfDYe",
    "created_at": 1684096920263.688,
    "provider": "email",
    "email": "tatenda72@gmail.com",
    "user_id": "auth0|b60d3ece-2c59-43d0-acf1-632fdefb6a54",
    "factor": "10",
    "salt": "VnxRmsfGTooc.Yy7Ez7L7.",
    "password": "bkdHaSzseGwHkjvxZUGaGo5k4XIfDYe",
    "encryptionScheme": "bcrypt",
    "tenant": "955a8687-0376-45cb-2f49-26e66050dea2",
    "email_verified": true
  },
  {
    "instance_id": "00000000-0000-0000-0000-000000000000",
    "encrypted_password": "",
    "created_at": 1684269308911.086,
    "provider": "google",
    "email": "tsurokudzanai@gmail.com",
    "user_id": "google|1a5347be-4bab-4113-aaf5-51d358fd4165",
    "salt": "",
    "password": "hasprovider",
    "tenant": "955a8687-0376-45cb-2f49-26e66050dea2",
    "email_verified": true
  },
  {
    "instance_id": "00000000-0000-0000-0000-000000000000",
    "encrypted_password": "$2a$10$X06hVD7/522iK698AxX1u.NINSImp/Md75dY/yz5sYjpmGF/5aeM6",
    "created_at": 1684052197215.207,
    "provider": "email",
    "email": "tsurokudzanai@outlook.com",
    "user_id": "auth0|90d5cfea-e41e-44ea-a3bd-e16d112622f8",
    "factor": "10",
    "salt": "X06hVD7/522iK698AxX1u.",
    "password": "NINSImp/Md75dY/yz5sYjpmGF/5aeM6",
    "encryptionScheme": "bcrypt",
    "tenant": "955a8687-0376-45cb-2f49-26e66050dea2",
    "email_verified": true
  }
]
----

=== Social Logins

In the event that we have users in Supabase linked with Providers like (Google, Facebook, LinkedIn and so on), we also pull those users and the provider details as saved in Supabase `auth` tables and format the data in the SQL script to the specification of Fusionauth data structure.

==== Identifiers

When creating an object with the FusionAuth API, you can specify the Id. It must be a link:/docs/v1/tech/reference/data-types#uuids[UUID].

This works for users, applications, and tenants, among others.

Supabase uses a custom UID format. When migrating, a new UUID will be created for the user on FusionAuth, or we can use the Supabase user Id migration.

If you have external dependencies on an Id stored in Supabase, you can add a new attribute under `user.data` (such as `user.data.originalId`) with the value of the Supabase Id. Because everything under `user.data` is indexed and available via search, you'll be able to find your users using either the new FusionAuth Id, or the original Supabase one.

== Exporting Users
The script for generating user data is found here, it is a user defined psql function which generates a json array object:

include::data-script/Supabase_User_Migration_PSQL_Script.sql

To execute the function once the function is created :
`SELECT "ufn_get_user_migration_data_json"() as "User Migration Data";` where `ufn_get_user_migration_data_json` is the function name. The function returns a JSON array with formatted user data. We the copy the generated JSON and save the JSON to a file on your machine to upload later in Fusionauth environment.

To export users from Supabase, you’ll perform the following steps:

1. Access the Supabase Query Editor and create a new query
2. Paste contents of Supabase_User_Migration_PSQL_Script.sql script into the editor and execute
3. Execute the function created as instructed above and save the json data to a name file for example, `users.json`

== Importing Users

Next up, import the user data. Here are the steps we need to take.

1. Set Up FusionAuth
2. Install Needed Gems
3. Get the Script
4. Use the Script
5. Verify the Import
6. The Final Destination of Imported Users

=== Set Up FusionAuth

Running the Fusionauth UI client on your machine/environment is a start, you will need to create an application, generate an API key from the dashboard and create a Tenant from the dashboard as well. The API key is useful as an Authorization key when accessing Fusionauth APIs. We use the Tenant id to identify your application and it's users.

==== Create a Test Tenant
Below is a screenshot for creating your Tenant:

include::img/create-tenant.png

==== Create a Test Application

Below is a screenshot for creating your Tenant:

include::img/create-application.png

==== Add an API Key

Below is a screenshot for adding an API Key, on the Add Key screen, you need to specify the Tenant (created above) from the dropdown and give your API Key specific APIs to work with otherwise it will be a super key with access to all available APIs.

include::img/add-api-key.png

=== Get the Script

The json file above will need to be uploaded via a Ruby script found here:

include::supabase-import-script/import.rb

This file has been edited to suit the data received from Supabase and fitting into Fusionauth data specification.

=== Install Needed Gems

The following gems must be available to the import script:

* `date`
* `json`
* `optparse`
* `securerandom`
* `fusionauth_client`

Most likely all of these will be on your system already, except the
`fusionauth_client` gem.

If you have `bundler` installed, run `bundle install` in the `supabase`
directory. Otherwise, install the needed gems in some other way.

=== Use the Script

You can see the output of the script by running it with the `-h` option:

Running the import script with the help command line switch

[source,sh]
----
ruby ./import.rb -h
----

The output will be similar to this:

[source,sh,title=The help output of the import.rb script]
----
Usage: import.rb [options]
    -l, --link-social-accounts       Link social accounts, if present, after import. This operation is slower than an import.
    -r APPLICATION_IDS,              A comma separated list of existing applications Ids. All users will be registered for these applications.
        --register-users
    -o, --only-link-social-accounts  Link social accounts with no import.
    -u, --users-file USERS_FILE      The exported JSON user data file from Supabase. Defaults to users.json.
    -f FUSIONAUTH_URL,               The location of the FusionAuth instance. Defaults to http://localhost:9011.
        --fusionauth-url
    -k, --fusionauth-api-key API_KEY The FusionAuth API key.
    -t TENANT_ID,                    The FusionAuth tenant id. Required if more than one tenant exists.
        --fusionauth-tenant-id
    -m, --map-supa-id            Whether to map the Supabase id for normal imported users to the FusionAuth user id.
    -h, --help                       Prints this help.
----

For this script to work correctly, set the following switches, unless the defaults work for you:

* `-u` should point to the location of the user export file you obtained, unless the default works.
* `-f` must point to your FusionAuth instance. If you are testing locally, it will probably be `http://localhost:9011`.
* `-k` needs to be set to the value of the API key created above.
* `-t` should be set to the Id of the testing tenant created above.

The `-o` and `-l` switches will attempt to create links for any social users (where the user authenticated via Google or another social provider) found in the users data file.

If you are loading social users, you must create the social providers in FusionAuth beforehand, or the links will fail. Additionally, creating a link is not currently optimized in the same way that loading users is. So it may make sense to import all the users in one pass (omitting the `-l` switch). Then, after the users are imported, create the links using the `-o` switch in a second pass.

[NOTE.note]
====
The social account linking functionality will only work with FusionAuth versions above or equal to 1.28. The `fusionauth_client` library must be >= 1.28 as well.
====

When you run the script:

[source,shell,title=Import script output]
----
ruby ./import.rb -f http://localhost:9011 -k '...' -u user-data.json
----

you’ll see output like:

include::img/user-migration-result-using-ruby-script.png

==== Enhancing the Script

You may also want to migrate additional data. Currently, the following
attributes are migrated:

* `user_id`
* `email`
* `email_verified`
* `username`
* the password hash and supporting attributes, if available
* `registrations`, if supplied

If you have additional user attributes to migrate, review and modify the `map_user` method.

You may also want to assign Roles, or associate users with Groups, by
creating the appropriate JSON data structures in the import call. These
are documented in the
link:/docs/v1/tech/apis/users#import-users[Import User API docs]. This will require modifying the `import.rb` code.

=== Verify the Import

If the data imported successfully you will see the users in Fusionauth, below is an image of user accounts linked to social logins:

include::img/facebook-user-imported.png

include::img/google-user-imported.png

=== The Final Destination of Imported Users

The imported users in Fusionauth are located here http://localhost:9011/admin/user/[Fusionauth Users]


:migration_source_name!:
:migration_source_dir!: