---
layout: doc
title: Email & Templates Overview
description: An overview of the FusionAuth Email Template system
---

:sectnumlevels: 0

== Overview

This section is designed to review how to utilize email and email templates in FusionAuth. See link:/docs/v1/tech/apis/emails/[Email APIs]
for additional information on integrating directly with the APIs.

Email and Email Templates are a core feature of FusionAuth. This feature provides the ability to communicate with your Users via email. FusionAuth
comes shipped with a few basic email templates for common workflows such as Setup Password, Change Password and Verify Email.

In order to use email templates and email based workflows, you will need to enable and complete the SMTP configuration. Generally this will
have been completed during the link:/docs/v1/tech/tutorials/setup-wizard/[FusionAuth Setup Wizard]. If you have not yet completed this step see the topic
link below for configuring email.

Here are the topics in this section:

* link:/docs/v1/tech/email-templates/configure-email/[Configure Email]
* link:/docs/v1/tech/email-templates/email-templates/[Email Templates]

