---
layout: doc
title: Email & Templates Overview
description: An overview of the FusionAuth Email Template system
---

:sectnumlevels: 0

== Overview

This section is designed to review how to utilize email, email templates, and messenger templates in FusionAuth. See link:/docs/v1/tech/apis/emails/[Email APIs] for additional information on integrating directly with the email APIs and link:/docs/v1/tech/apis/messengers/templates/[Messenger Templates] for more information on modifying messenger templates directly.

== Email

Email and Email Templates are a core feature of FusionAuth. This feature provides the ability to communicate with your Users via email. FusionAuth
comes shipped with a few basic email templates for common workflows such as Setup Password, Change Password and Verify Email.

In order to use email templates and email based workflows, you will need to enable and complete the SMTP configuration. Generally this will
have been completed during the link:/docs/v1/tech/tutorials/setup-wizard/[FusionAuth Setup Wizard]. If you have not yet completed this step see the topic
link below for configuring email.

Here are the topics in this section:

* link:/docs/v1/tech/email-templates/configure-email/[Configure Email]
* link:/docs/v1/tech/email-templates/email-templates/[Email Templates]

Here's a brief video covering some aspects of email templates:

video::3xQyIq9p4DQ[youtube,width=560,height=315]

== Message Templates

Message templates are used by Messengers. Currently there is only one messenger type: SMS. Just as with emails, these can be customized and localized, but unlike email templates, there are not HTML and text versions of a messenger template.

Here are the topics in this section:

* link:/docs/v1/tech/email-templates/message-templates/[Message Templates]

== Common Providers

=== SendGrid

[NOTE]
====
This information is for starting guidance only - FusionAuth connects seamlessly with many different email services. A deep exploration of email best practices and providers is outside the scope of this section.
====

SendGrid is a commonly used email provider and integrates well with FusionAuth via API. To setup SendGrid, please follow the instructions below:

- https://docs.sendgrid.com/for-developers/sending-email/integrating-with-the-smtp-api

Other resources related to SendGrid are linked below:

1. https://docs.sendgrid.com/for-developers/sending-email/getting-started-with-transactional-emails
1. https://docs.sendgrid.com/for-developers/sending-email/sender-identity
1. https://docs.sendgrid.com/ui/account-and-settings/how-to-set-up-domain-authentication

Using dedicated IP addresses for any SendGrid account will build email reputation over time (improving email deliverability). And lastly, to control spoofing, phishing, and spam, it is recommended to set up SPF and DKIM for the primary email domain (such as `example-company.com`). Emails should also be sent from an address such as `no-reply@example-company.com`.

== Troubleshooting

include::docs/v1/tech/email-templates/_email-troubleshooting.adoc[]
