create Forums

== Initialize ==
Browser->Forums : GET /\n[No cookies]
Forums->Browser : (SPA HTML, CSS & JavaScript)
Browser->Forums : GET /api/user\n[No cookies]
Forums-[#red]>Browser : <color red>404 Missing</color>
