@startuml
  !include ../_config.plantuml
  !include ../_participants.plantuml
  !include ../_intro.plantuml
  !include _initialize.plantuml

  == Login (inside SPA) ==
  Browser->Browser : Render login form
  Browser->Store : AJAX POST /api/login
  Store->FusionAuth : POST /api/login
  FusionAuth->Store : (User, Refresh Token and JWT)
  Store->Browser : (User object)\n[Refresh Token and JWT HttpOnly w/ domain: Store.Example.com]

  !include _shopping-cart-refresh-jwt-load.plantuml

  !include _shopping-cart-refresh-jwt-refresh.plantuml

  !include _shopping-cart-refresh-jwt-relogin.plantuml

  ||50||
  note over Browser, Hacker #purple;line:white : <color white>SSO login to forums - not provided by FusionAuth for this workflow</color>
  ||50||

  !include _forums-initialize.plantuml

  == Login (inside SPA) ==
  Browser->Browser : Render login form
  Browser->Forums : AJAX POST /api/login
  Forums->FusionAuth : POST /api/login
  FusionAuth->Forums : (Refresh Token and JWT)
  Forums->Browser : (User object)\n[Refresh Token and JWT HttpOnly w/ domain: Forums.Example.com]

  !include _forums-refresh-jwt-load.plantuml

  !include ../_attack-vectors.plantuml

  !include _stolen-refresh-token-refresh-jwt.plantuml
  
  !include _stolen-jwt-refresh-jwt.plantuml
@enduml