---
layout: doc
title: CORS Reference
description: Cross-Origin Resource Sharing (CORS) configuration
---

:sectnumlevels: 0
== Cross-Origin Resource Sharing (CORS) Configuration

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS[Cross-Origin Resources Sharing] (CORS) provide a mechanism to control permission
to resources on a server on a different domain or origin than the originating request.

Practically this means that in order to make HTTP requests in JavaScript to FusionAuth when the request
is coming from a different domain CORS needs to be configured to allow the request.

The following URLs or URL patterns are allowed through the CORS filter.

////
Internal Note: This needs to match our shipped CORS configuration. See /fusionauth-app/web/WEB-INF/web.xml
////

[source]
----
/api/*
/oauth2/introspect
/oauth2/token
/oauth2/userinfo
/.well-known/openid-configuration
----

If you need further assistance, or require additional endpoints allowed through the CORS filter, ask a question on https://stackoverflow.com/questions/tagged/fusionauth[Stack Overflow, window="_blank"] or open an issue on https://github.com/FusionAuth/fusionauth-issues/issues/new/choose[Github, window="_blank"] if you have additional questions. If you have a support contract you may send a request to support@fusionauth.io.