@startuml
  !include ../../../../_config.plantuml
  !include ../_participants.plantuml
  !include ../_intro.plantuml
  !include _initialize.plantuml

  == Login (browser navigates away from SPA) ==
  Browser->FusionAuth : GET /oauth2/authorize {response_type=code}
  FusionAuth->Browser : (Login form HTML)
  Browser->FusionAuth : POST /oauth2/authorize {response_type=code}
  FusionAuth->Browser : 302 Location: {redirect_uri w/ code}\n[SessionId HttpOnly w/ domain: login.fusionauth.io]
  Browser->Store : GET {redirect_uri w/ code}
  Store->FusionAuth : POST /oauth2/token\n(code, client_secret)
  FusionAuth->Store : 200 Ok\n(Refresh token and JWT)
  Store->Browser : 302 Location: /\n[Refresh token and JWT HttpOnly w/ domain: Store.Example.com]
  Browser->Store : GET /
  Store->Browser : (SPA HTML, CSS & JavaScript)
  Browser->Store : AJAX GET /api/user\n[Refresh token and JWT HttpOnly w/ domain: Store.Example.com]
  Store->Browser : 200 Ok\n(User)

  !include _shopping-cart-refresh-jwt-load.plantuml

  !include _shopping-cart-refresh-jwt-refresh.plantuml

  !include _shopping-cart-refresh-jwt-relogin.plantuml

  !include ../_sso.plantuml

  !include _forums-initialize.plantuml
  
  == Login (browser navigates away from SPA but auto-logs-in since the session exists) ==
  Browser->FusionAuth : GET /oauth2/authorize {response_type=code}\n[SessionId HttpOnly w/ domain: login.fusionauth.io]
  FusionAuth->Browser : 302 Location: {redirect_uri w/ code}\n[SessionId HttpOnly w/ domain: login.fusionauth.io]
  Browser->Forums : GET {redirect_uri w/ code}
  Forums->FusionAuth : POST /oauth2/token\n(code, client_secret)
  FusionAuth->Forums : 200 Ok\n(Refresh token and JWT)
  Forums->Browser : 302 Location: /\n[Refresh token and JWT HttpOnly w/ domain: Forums.Example.com]
  Browser->Forums : GET /
  Forums->Browser : (SPA HTML, CSS & JavaScript)
  Browser->Forums : AJAX GET /api/user\n[Refresh token and JWT HttpOnly w/ domain: Forums.Example.com]
  Forums->Browser : 200 Ok\n(User)

  !include _forums-refresh-jwt-load.plantuml

  !include ../_attack-vectors.plantuml

  !include _stolen-refresh-token-refresh-jwt.plantuml

  !include _stolen-jwt-refresh-jwt.plantuml
@enduml
