==== Request Body

[.api]
[field]#entity.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Entity that should be persisted. Please review the link:/docs/v1/tech/reference/limitations#data-field-limitations[limits on data field types] as you plan for and build your custom data schema.

[field]#entity.clientId# [type]#[String]# [optional]#Optional#::
The OAuth 2.0 client Id. If you leave this blank during a POST, the value of the Entity Id will be used.

[field]#entity.clientSecret# [type]#[String]# [optional]#Optional#::
The OAuth 2.0 client secret. If you leave this blank during a POST, a secure secret will be generated for you. If you leave this blank during PUT, the previous value will be maintained. For both POST and PUT you can provide a value and it will be stored.

[field]#entity.name# [type]#[String]# [required]#Required#::
A descriptive name for the Entity (i.e. "Raviga" or "Email Service").

[field]#entity.tenantId# [type]#[UUID]# [Optional]#Optional#::
The Tenant Id. Required if there is more than one tenant.

[field]#entity.type.id# [type]#[UUID]# [required]#Required#::
The type of the Entity. Types are consulted for permission checks.

[source,json]
.Example Request JSON
----
include::../../../../src/json/entities/request.json[]
----
