[api]
ifdef::search_result[]
[field]#total# [type]#[Long]#::
The number of entities that matched the search criteria. The number of results in the response will be equal to the `numberOfResults` provided on the request, if not provided the default number of results will be returned.
+
This value may cap out at 10,000 even if more entities are found based upon the provided search query. Use the `accurateTotal` request parameter if you require this value to represent the actual number of matching entities in the search index when your query may match more than 10,000 entities.

[field]#nextResults# [type]#[String]# [since]#Available since 1.48.0#::
An encoded token that can be used in subsequent search requests to page forward after the last result of the current response. Will only be returned if using the Elasticsearch engine.
+
See link:/docs/v1/tech/core-concepts/search#extended-pagination[Extended Pagination] for more information.
endif::[]

ifeval::["{base_field_name}" != "entity"]
[field]#{base_field_name}# [type]#[Array]#::
The list of Entity objects.
endif::[]

[field]#{base_field_name}.data# [type]#[Object]#::
An object that can hold any information about the Entity that should be persisted. Please review the link:/docs/v1/tech/reference/limitations#data-field-limitations[limits on data field types] as you plan for and build your custom data schema.

[field]#{base_field_name}.clientId# [type]#[String]#::
The OAuth 2.0 client Id. 

[field]#{base_field_name}.clientSecret# [type]#[String]#::
The OAuth 2.0 client secret. 

[field]#{base_field_name}.id# [type]#[UUID]#::
The unique Id of the Entity.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Entity was added to the FusionAuth database.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Entity was last updated in the FusionAuth database.

[field]#{base_field_name}.name# [type]#[String]#::
A descriptive name for the Entity (i.e. "Raviga" or "Email Service").

[field]#{base_field_name}.tenantId# [type]#[UUID]#::
The Id of the Tenant to which this Entity belongs.

[field]#{base_field_name}.type# [type]#[Object]#::
The Entity Type of this Entity. Consult the link:entity-types[Entity Type documentation] for more details about the fields of this object.

ifeval::["{base_field_name}" == "entity"]
[source,json]
.Example Response JSON for an Entity
----
include::../../../../src/json/entities/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "entity"]
[source,json]
.Example Response JSON for multiple Entities
----
include::../../../../src/json/entities/responses.json[]
----
endif::[]
