---
layout: doc
title: Entity Management API Overview
description: APIs for creating, retrieving, updating and deleting entities and entity types
---

== Overview

Entities are arbitrary objects which can be modeled in FusionAuth. Anything which is not a user but might need permissions managed by FusionAuth is a possible entity. Examples might include devices, cars, computers, customers, companies, etc. 

FusionAuth's Entity Management has the following major concepts:

* Entity Types categorize Entities. An Entity Type could be `Device`, `API` or `Company`.
* Permissions are defined on an Entity Type. These are arbitrary strings which can fit the business domain. A Permission could be `read`, `write`, or `file-lawsuit`. 
* Entities are instances of a single type. An Entity could be a `nest device`, an `Email API` or `Raviga`.
* Entities can have Grants. Grants are relationships between a target Entity and one of two other types: a recipient Entity or a User. Grants can have zero or more Permissions associated with them.

// TBD link to client credentials grant
You can use the Client Credentials grant to see if an Entity has permission to access another Entity.

You can learn more about link:/docs/v1/tech/core-concepts/entity-management/[Entities in the Core Concepts section].

The following APIs are available.

* link:/docs/v1/tech/apis/entity-management/entities/[Entities]
* link:/docs/v1/tech/apis/entity-management/entity-types/[Entity Types]
* link:/docs/v1/tech/apis/entity-management/grants/[Grants]
