---
layout: doc
title: Messengers
description: Adding and Configuring Messengers
---

[NOTE.since]
====
Available since 1.26.0
====

== Messengers

Messengers are used to send messages from within FusionAuth to other systems.

=== Message Transports
In version `1.26.0`, each messenger type is assigned a read-only transport value of `sms`. This tells FusionAuth which configurations the messenger may be assigned to.  For example, when configuring `SMS settings` in link:/docs/v1/tech/guides/multi-factor-authentication#tenant-set-up[multi-factor configuration] on a Tenant, we can safely assign only messengers designated with the corresponding transport value.

== Set Up a Messenger

In FusionAuth, you can set up three types of messengers:

- link:/docs/v1/tech/messengers/generic-messenger[Set Up a Generic Messenger]
- link:/docs/v1/tech/messengers/kafka-messenger[Set Up a Kafka Messenger]
- link:/docs/v1/tech/messengers/twilio-messenger[Set Up a Twilio Messenger]

To configure a messenger, navigate to [breadcrumb]#Settings-> Messengers# and click on the appropriate messenger type in the top right.

== Create a Messenger Template

Message templates are a powerful way to customize messengers and the communication contained within. FusionAuth uses FreeMarker for all templating.

- link:/docs/v1/tech/email-templates/message-templates[Manage Message Templates]

To configure a message template, navigate to [breadcrumb]#Customizations -> Message Templates#.
