# Put your AWS credentials for `fusionauth-dev` in ~/.aws/credentials.
s3_bucket: fusionauth-dev-site
gzip: true
cloudfront_distribution_id: E3N8W7YX4AAW44
cloudfront_invalidate_root: false
cloudfront_wildcard_invalidation: false
