@startuml
  !include ../../_config.plantuml

participant "Client" as cl
participant "Server" as svr
participant "Certificate Authorithy" as ca

cl -> svr : Sends "clienthello" message
svr -> cl : Sends "serverhello" message
cl -> ca : Verifies the server's certificate's validity
cl <-> svr : A secret key is exchanged
cl -> svr : Sends "finished" message
svr -> cl : Sends "finsihed" message
cl <-> svr : Sends encrypted data back and forth
@enduml
