scrape_configs:
  - job_name: FusionAuth
    scrape_interval: 5s
    scheme: https
    metrics_path: api/prometheus/metrics
    static_configs:
      - targets: ['local.fusionauth.io']
    basic_auth:
      username: "apikey"
      password: "Jw4cGzKpzxcEsqnqFKw3m7jUvgeS-jtUvn8B0TDBxgQ="