---
layout: doc
title: OpenID Connect & OAuth 2.0 Integration Examples
description: Examples of integrations with OIDC and OAuth
navcategory: login-methods
---

== Overview

FusionAuth is an OIDC and OAuth server, which means it integrates with a variety of third party systems out of the box.

In general, you'll want to do the following to perform an integration:

* Create an application in FusionAuth.
* Record the [field]#Client Id# and the [field]#Client Secret#.
* Provide the [field]#Client Id# and the [field]#Client Secret# to the application which will be delegating authentication to FusionAuth.
* Add the configured redirect URL, typically specified by the delegating application, to the [field]#Authorized redirect URLs# field in the client.

You may need to ensure that FusionAuth is signing the JWT with an asymmetric key. You can do that using Key Master to create or import the key and then configuring the application by navigating to [breadcrumb]#Applications -> Your Application -> JWT#.

== Example Integrations

Here are some example integrations.

* link:/docs/v1/tech/oauth/ngrok-cloud-edge[ngrok Cloud Edge]

Here's a link:/community/forum/topic/112/what-open-source-and-commercial-packages-are-known-to-work-with-fusionauth[list of applications supplied by the community].

