---
layout: doc
title: Tokens
description: OAuth2 & OpenID Connect Tokens and what they are used
---

== Overview

When using the OAuth2 and OpenID Connect authentication grants you'll be dealing with some tokens. We'll review each token type, the purpose and how to use them.

Here's a presentation discussing how to use JWTs in a microservices architecture:

video::SLc3cTlypwM[youtube,width=560,height=315]

== Access Token
The access token is an opaque token per the OAuth2 specification. In the FusionAuth implementation the access token is a JSON Web Token (JWT).

=== Access Token Claims

[.api]
[field]#applicationId# [type]#[UUID]#::
The unique Id of the Application for which the User has been authenticated. A JWT can only represent authorization to a single Application.
+
This claim is only present if the User has a registration to the Application.
+
To obtain a JWT for another Application you must either authenticate again with a different `applicationId` using the link:/docs/v1/tech/apis/login#authenticate-a-user[Authentication] API or utilize the link:/docs/v1/tech/apis/jwt#issue-a-jwt[Issue a JWT] API to exchange a valid JWT for another.

[field]#aud# [type]#[String]#::
The audience the JWT is intended for. This registered claim is defined by https://tools.ietf.org/html/rfc7519#section-4.1.3[RFC 7519 Section 4.1.3].
+
This claim will be equal to the `client_id`.

[field]#authenticationType# [type]#[String]#::
The method used to authenticate the User which resulted in this JWT being generated. The possible values are:
+
    * `APPLE` - The User was authenticated using Apple. [since]#Available since 1.17.0#
    * `APPLICATION_TOKEN` - The User was authenticated using an link:/docs/v1/tech/tutorials/application-authentication-tokens/[Application Authentication Token].
    * `FACEBOOK` - The User was authenticated using Facebook. &nbsp; [since]#Available since 1.1.0#
    * `FEDERATED_JWT` - The User was authenticated using a JWT from an external Identity Provider.
    * `GENERIC_CONNECTOR` - The user was authenticated using a generic connector.  &nbsp; [since]#Available since 1.18.0#
    * `GOOGLE` - The User was authenticated using Google. [since]#Available since 1.1.0#
    * `HYPR` - The User was authenticated using the HYPR provider. [since]#Available since 1.12.0#
    * `JWT_SSO` - A valid JWT authorized to one Application was exchanged for another JWT authorized to a different Application.
    * `LDAP_CONNECTOR` -  The user was authenticated using an LDAP connector.  &nbsp; [since]#Available since 1.18.0#
    * `LINKEDIN` -  The user was authenticated using LinkedIn.  &nbsp; [since]#Available since 1.23.0#
    * `ONE_TIME_PASSWORD` The User was authenticated using a one time password. &nbsp; [since]#Available since 1.5.0#
    * `OPENID_CONNECT` - The User was authenticated using an external OpenID Connect provider. [since]#Available since 1.1.0#
    * `PASSWORD` - The User was authenticated using a loginId and password combination.
    * `PASSWORDLESS` - The user was authenticated using a passwordless login link. &nbsp; [since]#Available since 1.5.0#
    * `PING` - The user was authenticated using the PING API w/ a valid JWT.
    * `REGISTRATION` - The user was created using the Registration API.  &nbsp; [since]#Available since 1.16.0#
    * `REFRESH_TOKEN` - The User requested a new JWT using a Refresh Token.
    * `SAMLv2` - The User was authenticated using an external SAMLv2 provider. [since]#Available since 1.6.0#
    * `TWITTER` - The User was authenticated using Twitter. [since]#Available since 1.1.0#
    * `USER_CREATE` - The user was created using the User API. &nbsp; [since]#Available since 1.16.0#

[field]#email# [type]#[String]#::
The email address of the User whose claims are represented by this JWT.

[field]#email_verified# [type]#[Boolean]#::
The OpenId Connect claim indicating if the User's email has been verified.

[field]#exp# [type]#[Long]#::
The expiration instant of the JWT, expressed as UNIX time which is the number of seconds since Epoch. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.4[RFC 7519 Section 4.1.4].

[field]#iat# [type]#[Long]#::
The instant that the JWT was issued, expressed as UNIX time which is the number of seconds since Epoch. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.6[RFC 7519 Section 4.1.6].

[field]#jti# [type]#[String]# [since]#Available since 1.18.0#::
The unique identifier for this JWT. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.7[RFC 7519 Section 4.1.7].

[field]#iss# [type]#[String]#::
The issuer of the JWT. For FusionAuth, this is always the value defined in the global JWT configuration. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.1[RFC 7519 Section 4.1.1].

[field]#preferred_username# [type]#[String]# [since]#Available since 1.5.0#::
The username of the User whose claims are represented by this JWT.

[field]#roles# [type]#[Array<String>]#::
The roles assigned to the User in the authenticated Application. This claim is only present if the User has a registration to the Application.

[field]#sub# [type]#[UUID]#::
The subject of the access token. This value is equal to the User's unique Id in FusionAuth. This registered claim is defined by https://tools.ietf.org/html/rfc7519#section-4.1.2[RFC 7519 Section 4.1.2].



== Id Token
The Id Token is part of the OpenID Connect specification. The Id Token is a JSON Web Token (JWT) per the OpenID Connect specification. The Id Token is similar to the access token in the FusionAuth implementation. The Id Token may contain additional claims not present in the Access Token.

The Id Token may be returned as part of an Authentication request when the `openid` scope is requested.

=== Id Token Claims

[.api]
[field]#applicationId# [type]#[UUID]# [deprecated]#Deprecated#::
The unique Id of the Application for which the User has been authenticated. A JWT can only represent authorization to a single Application.
+
This claim is only present if the User has a registration to the Application.
+
To obtain a JWT for another Application you must either authenticate again with a different `applicationId` using the link:/docs/v1/tech/apis/login#authenticate-a-user[Authentication] API or utilize the link:/docs/v1/tech/apis/jwt#issue-a-jwt[Issue a JWT] API to exchange a valid JWT for another.
+
[deprecated]#Removed in version 1.24.0#
As of version 1.24.0, this claim is no longer returned by default. The `id_token` should not be utilized for authorization, so this claim was removed to make it less likely for a holder of this token to incorrectly utilize this token. If you have a need for this claim, it can be added back using a JWT populate lambda.

[field]#at_hash# [type]#[String]# [since]#Available since 1.5.0#::
The Access Token hash value. As defined by the https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken[3.1.3.6 of the OpenID Connect Core specification] this value is a base64 encoded hash of the access token.

[field]#aud# [type]#[String]#::
The audience the JWT is intended for. This registered claim is defined by https://tools.ietf.org/html/rfc7519#section-4.1.3[RFC 7519 Section 4.1.3].
+
This claim will be equal to the `client_id`.

[field]#authenticationType# [type]#[String]#::
The method used to authenticate the User which resulted in this JWT being generated. The possible values are:
+
    * `APPLE` - The User was authenticated using Apple. [since]#Available since 1.17.0#
    * `APPLICATION_TOKEN` - The User was authenticated using an link:/docs/v1/tech/tutorials/application-authentication-tokens/[Application Authentication Token].
    * `FACEBOOK` - The User was authenticated using Facebook. &nbsp; [since]#Available since 1.1.0#
    * `FEDERATED_JWT` - The User was authenticated using a JWT from an external Identity Provider.
    * `GENERIC_CONNECTOR` - The user was authenticated using a generic connector.  &nbsp; [since]#Available since 1.18.0#
    * `GOOGLE` - The User was authenticated using Google. [since]#Available since 1.1.0#
    * `HYPR` - The User was authenticated using the HYPR provider. [since]#Available since 1.12.0#
    * `JWT_SSO` - A valid JWT authorized to one Application was exchanged for another JWT authorized to a different Application.
    * `LDAP_CONNECTOR` -  The user was authenticated using an LDAP connector.  &nbsp; [since]#Available since 1.18.0#
    * `LINKEDIN` -  The user was authenticated using LinkedIn.  &nbsp; [since]#Available since 1.23.0#
    * `ONE_TIME_PASSWORD` The User was authenticated using a one time password. &nbsp; [since]#Available since 1.5.0#
    * `OPENID_CONNECT` - The User was authenticated using an external OpenID Connect provider. [since]#Available since 1.1.0#
    * `PASSWORD` - The User was authenticated using a loginId and password combination.
    * `PASSWORDLESS` - The user was authenticated using a passwordless login link. &nbsp; [since]#Available since 1.5.0#
    * `PING` - The user was authenticated using the PING API w/ a valid JWT.
    * `REGISTRATION` - The user was created using the Registration API.  &nbsp; [since]#Available since 1.16.0#
    * `REFRESH_TOKEN` - The User requested a new JWT using a Refresh Token.
    * `SAMLv2` - The User was authenticated using an external SAMLv2 provider. [since]#Available since 1.6.0#
    * `TWITTER` - The User was authenticated using Twitter. [since]#Available since 1.1.0#
    * `USER_CREATE` - The user was created using the User API. &nbsp; [since]#Available since 1.16.0#


[field]#c_hash# [type]#[String]# [since]#Available since 1.5.0#::
The Authorization Code hash value. As defined by the https://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken[3.3.2.11 of the OpenID Connect Core specification] this value is an encoded hash of the authorization code, the algorithm used to generate this hash depends upon the algorithm used to generate the `id_token` signature.

[field]#email# [type]#[String]#::
The email address of the User whose claims are represented by this JWT.

[field]#email_verified# [type]#[Boolean]#::
The OpenId Connect claim indicating if the User's email has been verified.

[field]#exp# [type]#[Long]#::
The expiration instant of the JWT, expressed as UNIX time which is the number of seconds since Epoch. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.4[RFC 7519 Section 4.1.4].

[field]#iat# [type]#[Long]#::
The instant that the JWT was issued, expressed as UNIX time which is the number of seconds since Epoch. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.6[RFC 7519 Section 4.1.6].

[field]#iss# [type]#[String]#::
The issuer of the JWT. For FusionAuth, this is always the value defined in the global JWT configuration. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.1[RFC 7519 Section 4.1.1].

[field]#jti# [type]#[String]# [since]#Available since 1.18.0#::
The unique identifier for this JWT. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.7[RFC 7519 Section 4.1.7].

[field]#nonce# [type]#[String]# [since]#Available since 1.5.0#::


[field]#preferred_username# [type]#[String]# [since]#Available since 1.5.0#::
The username of the User whose claims are represented by this JWT.

[field]#roles# [type]#[Array<String>]# [deprecated]#Deprecated#::
The roles assigned to the User in the authenticated Application. This claim is only present if the User has a registration to the Application.
+
[deprecated]#Removed in version 1.24.0#
As of version 1.24.0, this claim is no longer returned by default. The `id_token` should not be utilized for authorization, so this claim was removed to make it less likely for a holder of this token to incorrectly utilize this token. If you have a need for this claim, it can be added back using a JWT populate lambda.

[field]#sub# [type]#[UUID]#::
The subject of the access token. This value is equal to the User's unique Id in FusionAuth. This registered claim is defined by https://tools.ietf.org/html/rfc7519#section-4.1.2[RFC 7519 Section 4.1.2].




== Refresh Token
The refresh token is an opaque token that is used to "refresh", or obtain a new access token. Because the life of an access token is generally measured in minutes, the Refresh Token is by comparison a long lived token that can be used to maintain access to a protected resource.

To request a refresh token during authentication you must provide the `offline_access` scope. The refresh token is not supported by the Implicit Grant, so if you provide the `offline_access` scope during an Implicit Grant workflow it will be ignored.

If you request the `offline_access` scope and an Refresh Token is not returned, ensure that the FusionAuth application has been configured to generate refresh tokens. Ensure `Generate refresh tokens` is enabled in your application settings. See [breadcrumb]#Settings -> Applications -> OAuth#. This setting will cause a Refresh Token to be returned when the `offline_access` scope is requested. You will also want to ensure the `Refresh Token` grant is enabled which allows the use of the Refresh Token to be exchanged for a new Access Token.
