---
layout: doc
title: Tokens
description: OAuth2 & OpenID Connect Tokens and what they are used
navcategory: login-methods
---

== Overview

When using the OAuth2 and OpenID Connect authentication grants you'll be dealing with some tokens. We'll review each token type, the purpose and how to use them.

Here's a presentation discussing how to use JWTs in a microservices architecture:

video::SLc3cTlypwM[youtube,width=560,height=315]

&nbsp;

* <<Header>>
* <<Access Token>>
* <<Client Credentials Access Token>>
* <<Id Token>>
* <<Refresh Token>>

== Header

With the exception of the refresh token, each token described here is a JSON Web Token (JWT) and each JWT has a header, a payload and a signature. The following describes the claims found in the JWT header.

[.api]
[field]#gty# [type]#[Array<String>]# [since]#Available since 1.36.0#::
The list of grants in the order the grant occurred.
+
For example, if the token was the result of an `authorization_code` grant, the value will be `[authorization_code]`.
+
If the token was generated using a refresh token using the `refresh_token` grant, the value will be `[authorization_code, refresh_token]` if the initial grant used to obtain the refresh token was the `authorization_code` grant.

[field]#kid# [type]#[String]#::
The unique key identifier that represents the key used to build the signature.

[field]#typ# [type]#[String]#::
The type of token, this value is always `JWT`.


== Access Token
The access token is an opaque token per the OAuth2 specification. In the FusionAuth implementation the access token is a JSON Web Token (JWT).

=== Access Token Claims

include::docs/v1/tech/oauth/_access-token-claims.adoc[]

== Client Credentials Access Token

The access token is an opaque token per the OAuth2 specification. In the FusionAuth implementation, the credentials access token is a JSON Web Token (JWT).

[NOTE.since]
====
Available since version 1.26.
====

=== Client Credentials Access Token Claims

[.api]
[field]#aud# [type]#[String]#::
The audience of this token. This value is equal to the target Entity's unique Id in FusionAuth. This registered claim is defined by https://tools.ietf.org/html/rfc7519#section-4.1.3[RFC 7519 Section 4.1.3].

[field]#exp# [type]#[Long]#::
The expiration instant of the JWT expressed as UNIX time, which is the number of seconds since Epoch. This registered claim is defined by https://tools.ietf.org/html/rfc7519#section-4.1.4[RFC 7519 Section 4.1.4].

[field]#iat# [type]#[Long]#::
The instant that the JWT was issued expressed as UNIX time, which is the number of seconds since Epoch. This registered claim is defined by https://tools.ietf.org/html/rfc7519#section-4.1.6[RFC 7519 Section 4.1.6].

[field]#jti# [type]#[String]#::
The unique identifier for this JWT. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.7[RFC 7519 Section 4.1.7].

[field]#iss# [type]#[String]#::
The issuer of the JWT. For FusionAuth, this is always the value defined in the tenant JWT configuration. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.1[RFC 7519 Section 4.1.1].

[field]#permissions# [type]#[Array<String>]#::
The permission granted to the recipient Entity by the target Entity. This claim is only present if permissions are associated with the grant and any requested permissions are found in the grant.

[field]#scope# [type]#[String]#::
The scope of the Access token. This meaning of this field is specified by
https://datatracker.ietf.org/doc/html/rfc6749#section-3.3[RFC 6749 Section 3.3] and referenced in Client Credentials Grant https://datatracker.ietf.org/doc/html/rfc6749#section-4.4[RFC 6749 Section 4.4]
+
Valid scopes are described in the link:https://fusionauth.io/docs/v1/tech/oauth/#client-credentials-scopes[client credentials scopes section].

[field]#sub# [type]#[UUID]#::
The subject of the access token. This value is equal to the recipient Entity's unique Id in FusionAuth. This registered claim is defined by https://tools.ietf.org/html/rfc7519#section-4.1.2[RFC 7519 Section 4.1.2].

[field]#tid# [type]#[UUID]# [since]#Available since 1.36.0#::
The FusionAuth Tenant unique Id.


== Id Token
The Id Token is part of the OpenID Connect specification. The Id Token is a JSON Web Token (JWT) per the OpenID Connect specification. The Id Token is similar to the access token in the FusionAuth implementation. The Id Token may contain additional claims not present in the Access Token.

The Id Token may be returned as part of an Authentication request when the `openid` scope is requested.

=== Id Token Claims

[.api]
[field]#applicationId# [type]#[UUID]# [deprecated]#Deprecated#::
The unique Id of the Application for which the User has been authenticated. A JWT can only represent authorization to a single Application.
+
This claim is only present if the User has a registration to the Application.
+
To obtain a JWT for another Application you must either authenticate again with a different `applicationId` using the link:/docs/v1/tech/apis/login#authenticate-a-user[Authentication] API or utilize the link:/docs/v1/tech/apis/jwt#issue-a-jwt[Issue a JWT] API to exchange a valid JWT for another.
+
[deprecated]#Removed in version 1.24.0#
As of version `1.24.0`, this claim is no longer returned by default. The `id_token` should not be utilized for authorization, so this claim was removed to make it less likely for a holder of this token to incorrectly utilize this token. If you have a need for this claim, it can be added back using a JWT populate lambda.

[field]#at_hash# [type]#[String]# [since]#Available since 1.5.0#::
The Access Token hash value. As defined by the https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken[3.1.3.6 of the OpenID Connect Core specification] this value is a base64 encoded hash of the access token.

[field]#aud# [type]#[String]#::
The audience the JWT is intended for. This registered claim is defined by https://tools.ietf.org/html/rfc7519#section-4.1.3[RFC 7519 Section 4.1.3].
+
This claim will be equal to the `client_id`.

[field]#authenticationType# [type]#[String]#::
The method used to authenticate the User which resulted in this JWT being generated. The possible values are:
+
include::docs/v1/tech/oauth/_authentication_type_claim_values.adoc[]

[field]#auth_time# [type]#[Long]# [since]#Available since 1.36.0#::
The time of the initial authentication request expressed as UNIX time which is the number of seconds since Epoch. This claim will remain the same even when the token has been re-issued through the use of a Refresh Token.

[field]#c_hash# [type]#[String]# [since]#Available since 1.5.0#::
The Authorization Code hash value. As defined by the https://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken[3.3.2.11 of the OpenID Connect Core specification] this value is an encoded hash of the authorization code, the algorithm used to generate this hash depends upon the algorithm used to generate the `id_token` signature.

[field]#email# [type]#[String]#::
The email address of the User whose claims are represented by this JWT.

[field]#email_verified# [type]#[Boolean]#::
The OpenId Connect claim indicating if the User's email has been verified.

[field]#exp# [type]#[Long]#::
The expiration instant of the JWT, expressed as UNIX time which is the number of seconds since Epoch. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.4[RFC 7519 Section 4.1.4].

[field]#iat# [type]#[Long]#::
The instant that the JWT was issued, expressed as UNIX time which is the number of seconds since Epoch. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.6[RFC 7519 Section 4.1.6].

[field]#iss# [type]#[String]#::
The issuer of the JWT. For FusionAuth, this is always the value defined in the tenant JWT configuration. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.1[RFC 7519 Section 4.1.1].

[field]#jti# [type]#[String]# [since]#Available since 1.18.0#::
The unique identifier for this JWT. This registered claim is defined by
https://tools.ietf.org/html/rfc7519#section-4.1.7[RFC 7519 Section 4.1.7].

[field]#nonce# [type]#[String]# [since]#Available since 1.5.0#::

[field]#preferred_username# [type]#[String]# [since]#Available since 1.5.0#::
The username of the User whose claims are represented by this JWT.

[field]#roles# [type]#[Array<String>]# [deprecated]#Deprecated#::
The roles assigned to the User in the authenticated Application. This claim is only present if the User has a registration to the Application.
+
[deprecated]#Removed in version 1.24.0#
As of version `1.24.0`, this claim is no longer returned by default. The `id_token` should not be utilized for authorization, so this claim was removed to make it less likely for a holder of this token to incorrectly utilize this token. If you have a need for this claim, it can be added back using a JWT populate lambda.

[field]#sid# [type]#[String]#::
The SSO session Id. This claim will only be present when this token is produced using an interactive grant during a single-signon request such as the Authorization Code grant or the Implicit grant.

[field]#sub# [type]#[UUID]#::
The subject of the access token. This value is equal to the User's unique Id in FusionAuth. This registered claim is defined by https://tools.ietf.org/html/rfc7519#section-4.1.2[RFC 7519 Section 4.1.2].

[field]#tid# [type]#[UUID]# [since]#Available since 1.36.0#::
The FusionAuth Tenant unique Id.


== Refresh Token
The refresh token is an opaque token that is used to "refresh", or obtain a new access token. Because the life of an access token is generally measured in minutes, the Refresh Token is by comparison a long lived token that can be used to maintain access to a protected resource.

To request a refresh token during authentication you must provide the `offline_access` scope. The refresh token is not supported by the Implicit Grant, so if you provide the `offline_access` scope during an Implicit Grant workflow it will be ignored.

If you request the `offline_access` scope and an Refresh Token is not returned, ensure that the FusionAuth application has been configured to generate refresh tokens. Ensure `Generate refresh tokens` is enabled in your application settings. See [breadcrumb]#Settings -> Applications -> OAuth#. This setting will cause a Refresh Token to be returned when the `offline_access` scope is requested. You will also want to ensure the `Refresh Token` grant is enabled which allows the use of the Refresh Token to be exchanged for a new Access Token.
