---
layout: doc
title: Group Member Add Complete
description: Group Member Add Complete event details
navcategory: developer
---

:type: group.member.add.complete
:event_info_since_threat_detection: 
:event_info_since_ip_address: 
:version_available: 1.38.0

== Group Member Add Complete

This event is generated when one or more users are added to a group. The JSON includes the Group and the Ids of the added members.

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-scoped-event.adoc[]

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_non-transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.group# [type]#[Object]#::
The group to which members were added. See the link:/docs/v1/tech/apis/groups[Groups API] for property definitions and example JSON.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.members# [type]#[Array]#::
An array of added group members.

[field]#event.members[``x``].data# [type]#[Object]#::
An object that can hold any information about the group member.

[field]#event.members[``x``].id# [type]#[UUID]#::
The unique Id of this group member. This is not the user Id.

[field]#event.members[``x``].insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that this membership was created.

[field]#event.members[``x``].userId# [type]#[UUID]#::
The user Id of the member.

[field]#event.tenantId# [type]#[UUID]#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/group-member-add-complete.json[]
----

