---
layout: doc
title: Group Update Complete
description: Group Update Complete event details
navcategory: developer
---

:type: group.update.complete
:event_info_since_threat_detection: 
:event_info_since_ip_address: 
:version_available: 1.38.0

== Group Update Complete

[NOTE.since]
====
This event has been available since {version_available}.
====

This event is generated when a group is updated. The JSON includes the Group that was updated.

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-scoped-event.adoc[]

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_non-transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.group# [type]#[Object]#::
The group that has been updated. See the link:/docs/v1/tech/apis/groups[Groups API] for property definitions and example JSON.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.original# [type]#[Object]#::
The original group, before update. See the link:/docs/v1/tech/apis/groups[Groups API] for property definitions and example JSON.

[field]#event.tenantId# [type]#[UUID]#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/group-update-complete.json[]
----
