---
layout: doc
title: JWT Refresh
description: JWT Refresh event details
---

:type: jwt.refresh
== JWT Refresh

[NOTE.since]
====
This event has been available since 1.16.0
====

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-scoped-event.adoc[]

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the token provides access.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.original# [type]#[String]#::
The original encoded access token which was provided on the JWT refresh request.  This field will be omitted if the [field]#token# parameter was not provided on the initiating request.

[field]#event.refreshToken# [type]#[String]#::
The refresh token which was provided on the JWT refresh request, used in refreshing the JWT.

[field]#event.token# [type]#[String]#::
The new encoded access token.

[field]#event.tenantId# [type]#[UUID]#::
The unique tenant identifier.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/jwt-refresh.json[]
----