---
layout: doc
title: JWT Refresh Token Revoke
description: JWT Refresh Token Revoke event details
---

:type: jwt.refresh-token.revoke
== JWT Refresh Token Revoke

This event is generated when a refresh token is revoked. The JSON includes either the User Id and User or the Application Id depending on what was revoked. It will also include the time to live duration (in seconds) for each Application. This value is used to determine if JWTs are valid or not based on their expiration instants.

The following scenarios will cause this event to be generated:

* A single Refresh Token is revoked
* All Refresh Tokens owned by a single User are revoked (if there is at least one valid Refresh Token for this User)
* All Refresh Tokens owned by a single User for an Application are revoked
* All Refresh Tokens for an Application are revoked


[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-or-application-scoped-event.adoc[]

=== Revoking Single Refresh Token

This example JSON would reflect a scenario where a single refresh token is revoked for a single user for a single application.

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the refresh token have been revoked.

[field]#event.applicationTimeToLiveInSeconds# [type]#[Map<UUID, Integer>]#::
A map of Application Id to the configured time to live (TTL) for the access token (JWT). This can be used to identify the maximum amount of time after this event occurred where an un-expired access token may be held by a user.
+
If you take the [field]#createInstant# of this event and add the number of seconds for a specific application TTL you come up with an instant in time where you should consider all access tokens issued before this time invalid. This is because the access token will have been issued on or before the instant the refresh token was revoked.
+
This map will contain a single entry for the application represented by the [field]#applicationId# field.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[field]#event.userId# [type]#[UUID]#::
The unique Id of the User for which a refresh token has been revoked.

[field]#event.user# [type]#[Object]# [since]#Available since 1.8.0#::
The user for which a refresh token has been revoked. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/jwt-refresh-token-revoke-user.json[]
----

=== All User Refresh Tokens Revoked

This example JSON would reflect a scenario where all refresh tokens owned by a single user are revoked.

=== Event Body

[.api]
[field]#event.applicationTimeToLiveInSeconds# [type]#[Map<UUID, Integer>]#::
A map of Application Id to the configured time to live (TTL) for the access token (JWT). This can be used to identify the maximum amount of time after this event occurred where an un-expired access token may be held by a user.
+
If you take the [field]#createInstant# of this event and add the number of seconds for a specific application TTL you come up with an instant in time where you should consider all access tokens issued before this time invalid. This is because the access token will have been issued on or before the instant the refresh token was revoked.
+
This map will contain an entry for each application for which the user has a refresh token.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[field]#event.userId# [type]#[UUID]#::
The unique Id of the User for which all refresh tokens have been revoked.

[field]#event.user# [type]#[Object]# [since]#Available since 1.8.0#::
The user for which a refresh token has been revoked. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/jwt-refresh-token-revoke-all-user.json[]
----

=== All Applications Refresh Tokens Revoked

This example JSON would reflect a scenario where all refresh tokens issued for a specific application are revoked.

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which all of the refresh tokens have been revoked.

[field]#event.applicationTimeToLiveInSeconds# [type]#[Map<UUID, Integer>]#::
A map of Application Id to the configured time to live (TTL) for the access token (JWT). This can be used to identify the maximum amount of time after this event occurred where an un-expired access token may be held by a user.
+
If you take the [field]#createInstant# of this event and add the number of seconds for a specific application TTL you come up with an instant in time where you should consider all access tokens issued before this time invalid. This is because the access token will have been issued on or before the instant the refresh token was revoked.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/jwt-refresh-token-revoke-application.json[]
----
