---
layout: doc
title: User Registration Create
description: User Registration Create event details
---

:type: user.registration.create
== User Registration Create

[NOTE.since]
====
This event has been available since 1.6.0
====

This event is generated when a user registration is created.

The final state of the operation which caused the webhook is not persisted to FusionAuth until after the webhook finishes; link:/docs/v1/tech/events-webhooks/writing-a-webhook#calling-fusionauth-apis-in-webhooks[learn more].

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-scoped-event.adoc[]

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the user has now been registered.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.registration# [type]#[Object]#::
The user registration that has been created. See the link:/docs/v1/tech/apis/registrations[Registration API] for property definitions and example JSON.

[field]#event.tenantId# [type]#[UUID]#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[field]#event.user# [type]#[Object]#::
The user that owns the new registration. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-registration-create.json[]
----