---
layout: doc
title: User Action
description: User Action event details
---

:type: user.action
== User Action

This event is generated when a User Action is taken on a user and when temporal actions transition between phases.

A temporal action is one that has a start time and and a duration. When a phase transition occurs for a temporal action, an event will be sent to the webhook. See the [field]#event.phase# in the message body.

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-or-application-scoped-event.adoc[]

=== Event Body

[.api]
[field]#event.action# [type]#[String]#::
This parameter specifies the name of the action that is occurring.

[field]#event.actionId# [type]#[UUID]#::
This parameter specifies the unique Id of the action that is occurring.

[field]#event.actioneeUserId# [type]#[UUID]#::
This parameter specifies the unique identifier of the user the action is being performed on.

[field]#event.actionerUserId# [type]#[UUID]#::
This parameter specifies the Id of the User that performed the action that resulted in the notification being sent. If the action was initiated by FusionAuth this value will not be provided.

[field]#event.applicationIds# [type]#[Array<UUID>]#::
This parameter if provided specifies the scope of the User Action. When an Action is scoped to one or more Applications the Application Ids will be provided in this parameter.

[field]#event.comment# [type]#[String]#::
An optional comment left to possibly indicate why the action was taken, modified or canceled.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.email# [type]#[Object]#::
When the action is configured to send the email in the event body, FusionAuth will render the email and provide the result in the event body. This can be used to send an email through a third party provider. See Example POST body below for fields.

[field]#event.emailedUser# [type]#[Boolean]#::
This parameter will indicate if FusionAuth has already sent an email to the user as a result of this event. When `true` an email was sent to the user, and if `false` an email was not sent to the user.

[field]#event.expiry# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the action will expire, if the action expires.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.localizedAction# [type]#[String]#::
This parameter specifies the localized version of the [field]#action# field, based on the user's preferred languages.

[field]#event.localizedDuration# [type]#[String]#::
The duration of the action in a human readable format that is localized based on the user's preferred languages.

[field]#event.localizedOption# [type]#[String]#::
This parameter specifies the localized version of the [field]#option# field, based on the user's preferred languages.

[field]#event.localizedReason# [type]#[String]#::
This parameter specifies the localized reason of the [field]#reason# field, based on the user's preferred languages.

[field]#event.notifyUser# [type]#[Boolean]#::
This parameter specifies whether the user should be notified. FusionAuth will only set this value based upon the event configuration, it is simply an indicator to the event consumer to notify the user.

[field]#event.option# [type]#[String]#::
An optional value to provide additional context to the Action. This value is free form and defined by the User Action.

[field]#event.phase# [type]#[Boolean]#::
If the Action is temporal, this parameter will be provided to indicate the current phase of the action. The following are the possible Action states:
+
* `start` - The event has started.
* `modify` - The event has been modified.
* `cancel` - The event has been canceled, the `end` phase will not be reached.
* `end` - The event has ended.
+
When the action is started by an admin, the phase will be "start". If an admin changes the duration of the action, the phase will be "modify". If an admin cancels an action it will be "cancel" or the action expires, the phase will be "end". If the action is key-based, the phase will be "start".

[field]#event.reason# [type]#[String]#::
The reason the admin selected. Reasons may be configured in the FusionAuth UI, navigate to [breadcrumb]#Settings -> User Actions -> Reasons#. This value will be omitted when no reasons are selected (or configured).

[field]#event.reasonCode# [type]#[String]#::
The reason code the admin selected. Reasons may be configured in the FusionAuth UI, navigate to [breadcrumb]#Settings -> User Actions -> Reasons#. This value will be omitted when no reasons are selected (or configured).

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-actions.json[]
----