---
layout: doc
title: User Delete
description: User Delete event details
---

:type: user.delete

// these are passed in because there are new events after 1.30 and it doesn't make sense to say that this event has attributes from a version before it was created
:event_info_since_threat_detection: pass:normal[[since]#Available since 1.30.0#]
:event_info_since_ip_address: pass:normal[[since]#Available since 1.27.0#]

== User Delete

This event is generated when a user is deleted.

[source,shell]
.Event type
[subs="attributes"]
----
user.delete
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-scoped-event.adoc[]

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[field]#event.user# [type]#[Object]#::
The user that has been deleted. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-delete.json[]
----
