---
layout: doc
title: User Update
description: User Update event details
navcategory: developer
---

:type: user.update
:event_info_since_threat_detection: pass:normal[[since]#Available since 1.30.0#]
:event_info_since_ip_address: pass:normal[[since]#Available since 1.27.0#]

== User Update

[NOTE.since]
====
This event has been available since 1.6.0
====

This event is generated when a user is updated. The event will include the before and after versions of the User being updated.

This event is currently generated each time a user logs in via an IdP, such as Google, or OIDC -- even if the user data or user details in the IdP have not been modified.

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-scoped-event.adoc[]

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.original# [type]#[Object]#::
The user before the update occurred, this is the old version of the user. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON.

[field]#event.tenantId# [type]#[UUID]#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[field]#event.user# [type]#[Object]#::
The user after the update, this is the new version of the user. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-update.json[]
----
