---
layout: doc
title: User Login Id Duplicate Update
description: User Login Id Duplicate Update event details
---

:type: user.loginId.duplicate.update
== User Login Id Duplicate Update

[NOTE.since]
====
This event has been available since 1.30.0
====

This event is generated when a request to update a user with a login Id (email or username) which is already in use has been received.

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-scoped-event.adoc[]

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_non-transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.duplicateEmail# [type]#[String]#::
The email address that is already in-use.

[field]#event.duplicateUsername# [type]#[String]#::
The username that is already in-use.

[field]#event.existing# [type]#[Object]#::
The existing user that is using the requested email address or username. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.tenantId# [type]#[UUID]#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[field]#event.user# [type]#[Object]#::
The user on the update request that attempted to use a duplicate login Id. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-login-id-duplicate-update.json[]
----