---
layout: doc
title: User Login Failed
description: User Login Failed event details
---

:type: user.login.failed
== User Login Failed

[NOTE.since]
====
This event has been available since 1.6.0
====

This event is generated when a user login request fails due to invalid credentials.

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-or-application-scoped-event.adoc[]

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the user has requested login. If the login request omits the [field]#applicationid# or the user is not registered for the requested [field]#applicationId# this value will not be returned in the event.

[field]#event.authenticationType# [type]#[String]#::
The type of authentication used in the login request.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.ipAddress# [type]#[String]# [deprecated]#Deprecated#::
The ip address provided in the login request.
+
[.deprecated]
Moved to [field]#event.info# in 1.30.0

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[field]#event.user# [type]#[Object]#::
The user that failed the login request. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-login-failed.json[]
----