---
layout: doc
title: User Password Reset Success
description: User Password Reset Success event details
---

:type: user.password.reset.success
== User Password Reset Success

[NOTE.since]
====
This event has been available since 1.30.0
====

This event is generated when the reset password flow has completed successfully.

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-scoped-event.adoc[]

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_non-transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.tenantId# [type]#[UUID]#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[field]#event.user# [type]#[Object]#::
The user that the reset password flow has been completed for. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON.

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-password-reset-success.json[]
----