---
layout: doc
title: User Login Suspicious
description: User Login Suspicious event details
---

:type: user.login.suspicious
== User Login Suspicious

[NOTE.since]
====
This event has been available since 1.30.0
====

This event is generated when a user logs in and FusionAuth has considered them to be a potential threat.

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::docs/v1/tech/events-webhooks/_tenant-scoped-event.adoc[]

=== Transaction Compatibility

include::docs/v1/tech/events-webhooks/events/_transactional-event.adoc[]

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the user has requested login. If the login request omits the [field]#applicationid# or the user is not registered for the requested [field]#applicationId# this value will not be returned in the event.

[field]#event.authenticationType# [type]#[String]#::
The type of authentication used in the login request.

[field]#event.connectorId# [type]#[UUID]#::
The unique Id of the connector used to complete the login.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.identityProviderId# [type]#[UUID]#::
The unique Id of the identity provider used to complete the login. This value will be omitted from the event if an identity provider was not used.

[field]#event.identityProviderName# [type]#[String]#::
The name of the identity provider used to complete the login. This value will be omitted from the event if an identity provider was not used.

include::docs/v1/tech/events-webhooks/events/_event-info.adoc[]

[field]#event.tenantId# [type]#[UUID]#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.threatsDetected# [type]#[Array<String>]#::
The types of potential threats that have been flagged for this event.
+
The possible values are:
+
 * `ImpossibleTravel` - The distance between recent logins exceeds the possible value a person can travel within the allotted time frame.
+

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[field]#event.user# [type]#[Object]#::
The user that completed the login request. See the link:/docs/v1/tech/apis/users[Users API] for property definitions and example JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-login-suspicious.json[]
----