---
layout: doc
title: Docker Install For the 5-Minute Guide
description: Use Docker and docker compose for the 5-minute guide.
navcategory: getting-started
---

:imagesuffix: 
:installmethod: docker

You've chosen to install FusionAuth via docker and docker compose.

This is the best option if you have docker installed locally or you plan to run FusionAuth in a Docker compatible environment such as Kubernetes and want to learn more about how FusionAuth runs in Docker.

If you've arrived here directly, start with the link:/docs/v1/tech/5-minute-setup-guide/[5-Minute Setup Guide Overview].

== Requirements

include::docs/v1/tech/getting-started/_5-minute-requirements.adoc[]

== Overview

Here are steps to take to set up FusionAuth and configure it to provide login and logout functionality for your application.

. xref:1-install-and-start-fusionauth[Install and Start FusionAuth]
. xref:2-complete-the-setup-wizard[Complete the Setup Wizard]
. xref:3-create-an-application-and-configure-the-oauth-settings[Create an Application and configure the OAuth settings]
. xref:4-grant-permissions[Grant Permissions]
. xref:5-configure-the-backend-to-complete-the-login[Configure the Backend to Complete the Login]
. xref:6-store-the-user-object-in-the-session[Store the user object in the session]
. xref:7-test-the-application[Test the Application]
. xref:8-logout[Logout]
. xref:9-summing-up[Summing Up]

== 1. Install and Start FusionAuth

You are following the Docker 5 minute guide, so you'll use `docker-compose`.

:with_elasticsearch:
include::docs/v1/tech/installation-guide/_docker-compose-files.adoc[]
:with_elasticsearch!:

Once the installer completes, you will see something similar to this output on the console:

[source,title=Docker Install Complete]
----
fusionauth-1  | 2022-10-29 01:01:16.527 AM INFO  org.primeframework.mvc.netty.PrimeHTTPServer - Starting FusionAuth HTTP server on port [9011]
fusionauth-1  | 2022-10-29 01:01:16.583 AM INFO  org.primeframework.mvc.netty.PrimeHTTPServer - Starting FusionAuth HTTP loopback server on port [9012]
----

And that's it! Docker makes standing up a FusionAuth instance a snap. Next, create a user by navigating to `http://localhost:9011`.

== 2. Complete the Setup Wizard

include::docs/v1/tech/getting-started/_5-minute-setup-wizard.adoc[]

== 3. Create an Application and Configure the OAuth settings

include::docs/v1/tech/getting-started/_5-minute-application-setup.adoc[]

== 4. Grant Permissions 

include::docs/v1/tech/getting-started/_5-minute-register-user.adoc[]

== 5. Configure the Backend to Complete the Login

include::docs/v1/tech/getting-started/_5-minute-configure-node-application.adoc[]

== 6. Store the User Object In The Session

include::docs/v1/tech/getting-started/_5-minute-store-user-object.adoc[]

== 7. Test the Application

include::docs/v1/tech/getting-started/_5-minute-test-application.adoc[]

== 8. Logout

include::docs/v1/tech/getting-started/_5-minute-logout.adoc[]

== 9. Summing Up

include::docs/v1/tech/getting-started/_5-minute-summing-up.adoc[]

== Feedback 

include::docs/v1/tech/getting-started/_5-minute-feedback.adoc[]
