Before you test the login, write the route/controller in your application's backend that will complete the OAuth workflow.

After a user logs into FusionAuth's OAuth front-end successfully, their browser will be redirected to the URL you provided in the configuration step above. This redirect will contain a query parameter called `code` that contains the OAuth authorization code from FusionAuth. 

Your application code will use this `code` parameter to call back to FusionAuth to exchange the code for an access token.

In order to complete this process, you'll be using the FusionAuth typescript client library along with Express and Pug templates. This https://github.com/FusionAuth/fusionauth-example-node[code is available] on the FusionAuth GitHub.

Clone the project and navigate to the directory:

[source,shell,title=Get the example application code]
----
git clone https://github.com/FusionAuth/fusionauth-example-node \
&& cd fusionauth-example-node
----

Here's the `package.json`:

[source,json,title=package.json]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/package.json[]
----

Install these libraries after creating the above `package.json` file.

[source,shell,title=Install the packages]
----
npm install
----

Here's the entire Express router, from `routes/index.js`:

[source,javascript,title=Node.js Express Router]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/routes/index.js[]
----

This is a lot, so we're not going to go through it line by line. But let's look at a few specific sections. 

First, to call the function on the FusionAuth client, you will also need the Client Id and the Client Secret from your Application configuration above. We'll take those values and put them in the code. These are required so that your application can prove it is the correct application the user is logging into. 

Make sure you update the code with the correct values for your Application:

[source,javascript,title=Node.js Client Id and Secret config]
----
//... 
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/routes/index.js[tags=clientIdSecret]
//...
----

ifeval::["{installmethod}" == "sandbox"]

Change the `fusionAuthURL` to the sandbox URL: `\https://sandbox.fusionauth.io`
[source,javascript,title=Modifying the Base URL]
----
//... 
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/routes/index.js[tags=baseURL]
//...
----
endif::[]

You also need a route that will respond to the URL you configured in the FusionAuth admin user interface above (`\https://localhost:3000/oauth-redirect`). This route will retrieve the `code` parameter from the request and exchange it for an access token.

This access token can be used to prove that any client holding it is authorized.

Here's the code for the route:

[source,javascript,title=Node.js Redirect Route]
----
//...
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/routes/index.js[tags=exchangeOAuthCode]
//...
----

