
You need to have Node.js installed. This document has been tested with version 14 and 18, but should work with other versions.

[source,shell script,title=Testing the Node.js Installation]
----
node -v
----

[source,shell script,title=Result Of Testing the Node.js Installation]
----
v18.10.0
----

ifeval::["{installmethod}" == "docker"]
You need to have Docker installed. This document has been tested with Docker version 20, but should work with other versions.

[source,shell script,title=Testing the Docker Installation]
----
docker -v
----

[source,shell script,title=Result Of Testing the Docker Installation]
----
Docker version 20.10.17, build 100c701
----

endif::[]

ifeval::["{installmethod}" == "fastpath"]
You need to have either a MySQL or PostgreSQL database installed. You also need a superuser name and password for the database; this user needs to be able to create schemas and databases.

If you do not have a database installed, follow the instructions in our link:/docs/v1/tech/installation-guide/database[Database Installation Guide] to install a database. Below, you see commands to test if the PostgreSQL command line tool, `psql`, is present.

[source,shell,title=Testing the Postgresql Installation]
----
psql --version
----

[source,shell,title=Result Of Testing the Postgresql Installation]
----
psql (PostgreSQL) 12.3
----
endif::[]
