Before you test the login, write the route/controller in your application's backend that will complete the OAuth workflow.

After a user logs into FusionAuth's OAuth front-end successfully, their browser will be redirected to the URL you provided in the configuration step above. This redirect will contain a query parameter called `code` that contains the one-time use OAuth authorization code from FusionAuth. 

Your application code uses this `code` parameter to call back to FusionAuth to exchange the code for an access token.

In order to complete the process, use the FusionAuth typescript client library along with Express and Pug templates. This https://github.com/FusionAuth/fusionauth-example-node[code is available], but is downloaded by `npm` below.

Clone the project and navigate to the directory.

[source,shell,title=Get the Example Application Code]
----
git clone https://github.com/FusionAuth/fusionauth-example-node \
&& cd fusionauth-example-node
----

Here's the `package.json` file.

[source,json,title=The Contents of the package.json File]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/package.json[]
----

Install required packages using `npm`.

[source,shell,title=Install Required Packages]
----
npm install
----

This is now ready to run, but let's look at some code first.

[source,javascript,title=The Node.js Complete Express Router]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/routes/index.js[]
----

There are one or two changes you need to make to make this application to work for your application.

First, to call the function on the FusionAuth client, you will also need the Client Id and the Client Secret from your Application configuration above. Take those values and put them in the code. These are required so that your application can prove it is the correct application the user is logging into. 

Make sure you update the file with the correct values for your Application, which you noted after you created the application in the step above.

[source,javascript,title=The Node.js Application Client Id and Secret config]
----
//... 
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/routes/index.js[tags=clientIdSecret]
//...
----

ifeval::["{installmethod}" == "sandbox"]

Change the `fusionAuthURL` to the sandbox URL: `\https://sandbox.fusionauth.io`
[source,javascript,title=Modifying the Base URL]
----
//... 
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/routes/index.js[tags=baseURL]
//...
----
endif::[]

ifeval::["{installmethod}" != "sandbox"]

If you are not running locally, change the `fusionAuthURL` to the correct value.

[source,javascript,title=Modifying the Base URL]
----
//... 
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/routes/index.js[tags=baseURL]
//...
----
endif::[]

