Before you test the login, examine the route/controller in your application's backend that will complete the OAuth workflow.

After a user logs into FusionAuth's OAuth front-end successfully, their browser will be redirected to the URL you provided in the configuration step above. This redirect will contain a query parameter called `code` that contains the one-time use OAuth authorization code from FusionAuth. 

Your application code provides the `code` parameter in a request to FusionAuth. It will exchange the code for an access token, which can be used for a variety of purposes.

In order to complete the process, you'll use a sample application, which uses the FusionAuth typescript client library, Express and Pug templates. This https://github.com/FusionAuth/fusionauth-example-node[code is available for download].

To get started, clone the project, and navigate to the project directory.

[source,shell,title=Get the Example Application Code]
----
git clone https://github.com/FusionAuth/fusionauth-example-node \
&& cd fusionauth-example-node
----

Here's a sample `.env` file, which includes some configuration you'll need to change.

[source,ini,title=The Contents Of the .env.sample File]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/.env.sample[]
----

[source,shell,title=Copy .env.sample To .env]
----
cp .env.sample .env
----

Edit the `.env` file and update the `CLIENT_ID` and `CLIENT_SECRET` values. Set them to the Client Id and the Client Secret you noted when examining the application configuration in a previous step. 

ifeval::["{installmethod}" == "sandbox"]
Change the `BASE_URL` value to the sandbox URL: `\https://sandbox.fusionauth.io`
endif::[]

ifeval::["{installmethod}" != "sandbox"]
If you are not running locally, change the `BASE_URL` to the correct value.
endif::[]

That's all the changes you need to make to the `.env` file.

Next, here's the `package.json` file, which includes all the components you'll need.

[source,json,title=The Contents Of the package.json File]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/package.json[]
----

Install required packages using `npm`.

[source,shell,title=Install Required Packages]
----
npm install
----

This application is almost ready to run, but let's look at some code first. Here's the heart of the application, the main Express router.

[source,javascript,title=The Node.js Complete Express Router]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/routes/index.js[]
----

There are three main routes:

* `/logout`, which logs the user out by destroying the local session
* `/`, which is the home page
* `/oauth-redirect` which catches handles the results of the login at FusionAuth and completes the grant, as mentioned above. After the token is retrieved, the user is stored in the session. This will be discussed further below.

There are also files under the `views` directory, which are the views shown to the end user.
