
There is a route that corresponds to the URL you configured in the FusionAuth admin user interface above (`\https://localhost:3000/oauth-redirect`). This is critical functionality, so let's take a look at this.

Here's the complete code for exchanging the token, retrieving the user data, storing it in the session, and redirecting the user.

[source,javascript,title=Node.js Complete OAuth Code Exchange]
----
//...
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-node/master/routes/index.js[tags=fullOAuthCodeExchange]
//...
----

This route retrieves the `code` parameter from the request and exchanges it for an access token. This access token can be used for a variety of purposes, but in this tutorial is used to retrieve user data from FusionAuth.

Once you have the User object, it is stored in a server side session so that it can be used in other parts of the application, such as a view where it is used to greet the user. There are other options for storing this user object, but for this tutorial, this will work fine.

The final task is to redirect the authorized user back to the homepage.

