---
layout: doc
title: SCIM With SCIM-client
description: How to set up SCIM with a SCIM-SDK client
navcategory: premium
---

:sectnumlevels: 0

== Overview

This document explains how to build a SCIM client using the open source https://github.com/Captain-P-Goldfish/SCIM-SDK[SCIM-SDK Java Library] and use it with FusionAuth.

== Prequisites

You'll need to have FusionAuth installed. link:/docs/v1/tech/installation-guide/[Learn more about various ways of installing it].

Ensure you have a license. You can link:/docs/v1/tech/admin-guide/licensing[learn more about licensing here]. SCIM requires an enterprise license. Learn more about link:/docs/v1/tech/core-concepts/editions-features[license options here] and link:/pricing[pricing here].

You'll need maven 3 and a modern version of Java installed. This document has been tested with Java 17.

You'll also need git installed.

== FusionAuth Configuration

In order for FusionAuth to accept requests from SCIM clients, you need to configure a few things.

=== Set Up Entities

Then, you need to set up the required entity types. These will be present if you have a default installation of FusionAuth, but will not be if you use Kickstart.

First, add the SCIM server. Navigate to [breadcrumb]#Entity Management -> Entity Types# and select the [breadcrumb]#Add SCIM Server# option.

TODO PICTURE add-scim-server-entity-type

This will have the following default permissions.

// TODO have this be an include file
* `scim:enterprise:user:create`
* `scim:enterprise:user:delete`
* `scim:enterprise:user:read`
* `scim:enterprise:user:update`
* `scim:group:create`
* `scim:group:delete`
* `scim:group:read`
* `scim:group:update`
* `scim:user:create`
* `scim:user:delete`
* `scim:user:read`
* `scim:user:update`

TODO PICTURE  adding-scim-server-entity-type-details

You can remove permissions if you never want your SCIM server to be able to undertake an operation. For example, remove `scim:user:delete` if you will never delete users.

Then, create a SCIM client entity type. Unlike the server, this doesn't require any special permissions, but will instead represent the SCIM client applications which will be providing user and group data to the SCIM server for provisioning.

TODO PICTURE add-scim-server-entity-type

TODO PICTURE  adding-scim-server-entity-type-details

Next, set up two entities. You need to set up an instance of the SCIM server and the SCIM client, and then grant permissions on the SCIM server to the SCIM client. You can have as many SCIM clients as you would like. You can have one SCIM server per tenant.

Navigate to [breadcrumb]#Entity Management -> Entities# and create a new entity.

TODO Picture
Make sure it has the type of the SCIM Server entity type you created above.

TODO Picture

Add another entity.

Make sure it has the type of the SCIM Client entity type you created above.

TODO Picture

Manage the client entity; you need to add permissions to the server entity.

TODO Picture

Add the permissions. You may grant one or more SCIM permissions to the client. These will be provided during the SCIM process to authenticate the appropriate level of access. Select the SCIM server entity in the [field]#Name# field and any permissions you'd like this client to have.


TODO Picture

Note the client Id of the SCIM server and the client Id and Secret of the SCIM client. You can see the details screen by clicking on the "View" button (the magnifying glass) from the entities list screen.

TODO Picture

=== Set Up Lambdas

Next, we need to review the lambdas. Navigate to [breadcrumb]#Customizations -> Lambdas#. You should see four lambdas labelled with "SCIM".

There are two sets of default lambdas, one for users and one for groups. Each set of lambdas has one lambda for incoming requests and the other for outgoing responses. You can use the same lambda for both User and EnterpriseUser resources, or you can use different ones. Lambdas can transform requests and responses, register users for applications, make HTTP requests to external APIs, and contain other business logic. You can link:/docs/v1/tech/lambdas/[learn more about the different lambdas], including their arguments.

TODO Picture

You may modify the lambdas as needed, but for the purposes of this document, the default lambdas are fine.

TODO Picture

=== Set Up The Tenant

Finally, you have set up all the needed scaffolding to enable SCIM for a given tenant. 

To do so, navigate to [breadcrumb]#Tenants -> Default Tenant#. Edit the tenant and then navigate to the [breadcrumb]#SCIM# tab. Once you've checked the [field]#Enabled# field, you'll see the all the SCIM settings.

Configure the following details:

* The [field]#Client entity type# should be the client entity type you previously created: `SCIM Client`.
* The [field]#Server entity type# should be the client entity type you previously created: `SCIM Server`.
* The [field]#User request lambda# should be the default lambda.
* The [field]#User response lambda# should be the default lambda.
* The [field]#Enterprise User request lambda# should be the default lambda.
* The [field]#Enterprise User response lambda# should be the default lambda.
* The [field]#Group request lambda# should be the default lambda.
* The [field]#Group response lambda# should be the default lambda.

You can leave the [field]#Schemas# field blank, and a default schema will be provided.

TODO picture

link:/docs/v1/tech/core-concepts/tenants#scim[Review detailed documentation about the various Tenant settings]. 

== The SCIM Client Application

Next, you will create small Java application to act as a SCIM client. This application will use the open source SCIM-sdk Java library to interact with the SCIM server that you have configured. Recall that clients are the source of user information, so this client will create, list and update a user in FusionAuth.

The https://github.com/FusionAuth/fusionauth-example-scim-integration[source code is available], but below you'll walk through configuring and running in.

Before you configure the application, clone the repository and compile it:

[source,shell,title=Setting up the example application]
----
git clone https://github.com/FusionAuth/fusionauth-example-scim-integration && cd fusionauth-example-scim-integration && mvn compile
----

=== Configure the Application

You'll need to modify the application by editing `src/main/java/io/fusionauth/example/scim/ScimExample.java` using the text editor or IDE of your choice. Search for the text `change these`. You'll see something similar to:

[source,java,title="Configuration to change for the example"]
----
//...
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-scim-integration/main/src/main/java/io/fusionauth/example/scim/ScimExample.java[tags=scimConfiguration]
//...
----

Update the `FUSIONAUTH_HOST` constant with the URL pointing to your FusionAuth installation, such as `http://localhost:9011`.

Update the `SCIM_SERVER_ENTITY_ID` constant with the Id of the entity with the type `SCIM Server` created above. This represents the FusionAuth server. If you didn't record this, navigate to [breadcrumb]#Entity Management -> Entities# and copy the Id from the list of entities. Also update the `CLIENT_ID` constant with the Id of the entity with the type `SCIM Client` created above. This will represent this java program. If you didn't record this, navigate to [breadcrumb]#Entity Management -> Entities# and copy the Id from the list of entities.

TODO picture

Optionally update the `EXISTING_USER_ID` constant with the Id of any user in your system. You can find one by navigating to [breadcrumb]#Users# and viewing the details of a user. If you don't do this, you won't be able to retrieve a user.

Optionally update the `CREATED_USER_LOGIN_ID` constant with a unique username for your system. This will be the username of the created user. If you don't modify this value, the default username will be used.

The other constants may be left unchanged, unless you want to experiment with changing permissions or setting a different password.

=== Run the Application

The application can be run in one of three modes:

* `get` which retrieves a single user
* `list` which lists users 
* `create`, which adds a new user

Let's create a new user and then check to see that the user was added.

To run the program, you need to recompile it after making the changes mentioned above:

[source,shell,title=Recompiling the sample application]
----
mvn compile
----

Then, you can run it. You need to provide two arguments to the application. The first is the client secret for the SCIM client entity. This value, along with the configured client Id, will be used to authenticate the SCIM client before the SCIM APIs are called. If you didn't record this, navigate to [breadcrumb]#Entity Management -> Entities#, view the details of the SCIM Client entity, and and copy the secret.

TODO picture

Then, run the command below, with the value of `YOUR_CLIENT_SECRET` updated to the real value, such as `i2kN2KFBPKKj3FsxfilPXDDreBUskn2Sl-27QbQRYQM`.

[source,shell,title=Running the sample application]
----
mvn exec:java -Dexec.mainClass="io.fusionauth.example.scim.ScimExample" -Dexec.args="YOUR_CLIENT_SECRET create"
----

You'll see the output of the sample application, which should look something like this:

[source,shell,title=Output of sample application]
----
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< io.fusionauth.example:scim-integration >---------------
[INFO] Building scim-integration 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ scim-integration ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
error message status: 200
error message: {"active":true,"emails":[{"primary":true,"type":"work"}],"id":"d7d98d7f-392d-4e61-a0ee-64fce8c1bf3a","meta":{"created":"2022-06-29T00:31:26.749Z","lastModified":"2022-06-29T00:31:26.749Z","location":"https://local.fusionauth.io/api/scim/resource/v2/Users/d7d98d7f-392d-4e61-a0ee-64fce8c1bf3a","resourceType":"User"},"name":{},"phoneNumbers":[{"primary":true,"type":"mobile"}],"schemas":["urn:ietf:params:scim:schemas:core:2.0:User"],"userName":"test@example.com"}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.209 s
[INFO] Finished at: 2022-06-28T18:31:26-06:00
[INFO] ------------------------------------------------------------------------
----

TODO why is this an error message? some kind of mapping issue. May need to tweak the response lambda

If you navigate to [breadcrumb]#Users# in the administrative user interface, you will see the new user has been added.


=== Examine the Application

Let's look at two sections of the example application. The first is the SCIM client authentication and the second is the method that creates the user.

To authenticate a SCIM client in FusionAuth, the client credentials grant is performed, including requesting any needed SCIM permissions. The resulting access token is then used as a bearer token in the SCIM API request, by including it in the `Authorization` header.

[source,java,title="The getCredentials method"]
----
//...
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-scim-integration/main/src/main/java/io/fusionauth/example/scim/ScimExample.java[tags=getCredentials]
//...
----

The `create` operation first builds a user object and then call the SDK provided `scimRequestBuilder.create` method, which posts to the FusionAuth server.

[source,java,title="The createUser method"]
----
//...
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-scim-integration/main/src/main/java/io/fusionauth/example/scim/ScimExample.java[tags=createUser]
//...
----

The list and get operations of this client application similarly build the request and then use the SDK to make a SCIM compliant request.

== More Information

* See the link:/docs/v1/tech/core-concepts/scim[SCIM Overview] for details about SCIM.
* See the link:/docs/v1/tech/apis/scim[SCIM API Overview] for details about the supported endpoints.
* See the link:/docs/v1/tech/core-concepts/tenants#scim[Tenants SCIM Overview] for details about SCIM Tenant settings.



== Limits

include::docs/v1/tech/shared/_scim-limits.adoc[]
