@startuml
  !include ../../_config.plantuml

participant Browser
participant "Zendesk" as z
participant FusionAuth
participant "Gusto" as g
Browser -> z : Requests App
z -> z : Check Session Existence, Session Missing
z -> Browser : Redirect to FusionAuth With a Signed AuthNRequest (XML)
Browser -> FusionAuth : Request Login Page
FusionAuth -> FusionAuth : Validate AuthNRequest (XML)
FusionAuth -> FusionAuth : Check FA Session Existence (Doesn't Exist)
FusionAuth -> Browser : Send Login Page
Browser -> FusionAuth : Send Credentials Of User
FusionAuth -> Browser : Redirects to Zendesk With a Response (XML)
Browser -> z : Requests App and Provides Response (XML)
z -> z : Processes Response (XML)
z -> Browser : Sends App
Browser -> g : Requests App
g -> g : Check Session Existence, Session Missing
g -> Browser : Redirect to FusionAuth With a Signed AuthNRequest (XML)
Browser -> FusionAuth : Request Login Page
FusionAuth -> FusionAuth : Validate AuthNRequest (XML)
FusionAuth -> FusionAuth : Check FA Session Existence (Exists)
FusionAuth -> Browser : Redirects to Gusto With a Response (XML)
Browser -> g : Requests App and Provides Response (XML)
g -> g : Processes Response (XML)
g -> Browser : Sends App 
@enduml
