@startuml
  !include ../../_config.plantuml

participant Browser
participant "Zendesk" as z
participant FusionAuth
participant "Gusto" as g
Browser -> z : Requests App
z -> z : Check Session Existence, Session Missing
z -> Browser : Redirect to FusionAuth With a Signed AuthNRequest
Browser -> FusionAuth : Request Login Page
FusionAuth -> FusionAuth : Check FA Session Existence
FusionAuth -> Browser : Send Login Page
Browser -> FusionAuth : Send Credentials
FusionAuth -> Browser : Redirects to Zendesk With a Response
Browser -> z : Requests App
z -> Browser : Sends App
Browser -> g : Requests App
g -> g : Check Session Existence, Session Missing
g -> Browser : Redirect to FusionAuth With a Signed AuthNRequest
Browser -> FusionAuth : Request Login Page
FusionAuth -> FusionAuth : Check FA Session Existence
FusionAuth -> Browser : Redirects to Gusto With a Response
Browser -> g : Requests App Provides Response
g -> Browser : Sends App
@enduml
