@startuml
  !include ../../_config.plantuml

participant Browser
participant "Zendesk" as z
participant FusionAuth
participant "Gusto" as g
Browser -> z : View Home Page
z -> z : Check Session Existence
z -> Browser : Redirect to FusionAuth Because There is No Valid Session
Browser -> FusionAuth : Request Login Page
FusionAuth -> FusionAuth : Check FA Session Existence
FusionAuth -> Browser : Send Login Page
Browser -> FusionAuth : Send Credentials
FusionAuth -> Browser : Redirects to Pied Piper
Browser -> z : Requests Home Page
z -> Browser : Sends Home Page
Browser -> g : Requests Home Page
g -> g : Check Session Existence
g -> Browser : Redirect to FusionAuth Because There is No Valid Session
Browser -> FusionAuth : Request Login Page
FusionAuth -> FusionAuth : Check FA Session Existence
FusionAuth -> Browser : Redirects to Home Page
Browser -> g : Requests Application Page
g -> Browser : Sends Application Page
@enduml
