!include ../_refresh-token-expires.plantuml

== Re-login ==
Browser->Store : GET /shopping-cart\n[Refresh token and JWT HttpOnly w/ domain: Store.Example.com]
Store->FusionAuth : POST /oauth2/token or POST /api/jwt/refresh\n(grant_type=refresh and refresh token)
FusionAuth-[#red]>Store : <color red>404 Missing</color>
Store->Browser : 302 Location: /login
Browser->Browser : Login same as above
