note over Browser, Browser #red;line:white : <color white>Session expires - refresh token still valid</color>

== Shopping cart load ==
Browser->Store : GET /shopping-cart\n[SessionId and Refresh token HttpOnly w/ domain: Store.Example.com]
Store->FusionAuth : POST /oauth2/token or POST /api/jwt/refresh\n(grant_type=refresh and refresh token)
FusionAuth->Store : (JWT)
Store->Store : Create new session and store User in it
Store->Browser : (Shopping cart contents)\n[New SessionId HttpOnly w/ domain: Store.Example.com]
