=== Form Fields

[.api]
[field]#Client Id# [required]#Required#::
The unique client identifier obtained from {identity_provider}. See {get_started_link}.

[field]#Client secret# [required]#Required#::
The client secret obtained from {identity_provider} used to authenticate the request. See {get_started_link}.

[field]#Button text# [optional]#Optional#::
The text to be displayed in the button on the login form. This value is defaulted to `Login with {identity_provider}` but it may be modified to your preference.

ifdef::scope_description[]
ifdef::scope_default[]
[field]#Scope# [optional]#Optional# [default]#defaults to `{scope_default}`#::
endif::[]
ifndef::scope_default[]
[field]#Scope# [optional]#Optional#::
endif::[]
{scope_description}
endif::[]

[field]#Linking strategy# [optional]#Optional# [default]#defaults to `{linking_strategy}`#::
The linking strategy for the {identity_provider} provider. link:/docs/v1/tech/identity-providers/#linking-strategies[See Linking Strategies for more].

[field]#Reconcile lambda# [optional]#Optional#::
A lambda maps custom claims returned from {identity_provider} to the FusionAuth User or Registration.
+
To create or configure a lambda, navigate to [breadcrumb]#Customizations -> Lambdas#. link:/docs/v1/tech/lambdas/[See the lambda documentation for more].

[field]#Debug enabled# [optional]#Optional# [default]#defaults to `false`#::
Enable debug to create event log entries during the user login process. This will assist you in debugging integration issues.
+
