=== Form Fields

[.api]
[field]#Client id# [required]#Required#::
`Client id` obtained from {identity_provider}. See {get_started_link}.

[field]#Client secret# [required]#Required#::
`Client secret` obtained from {identity_provider}. See {get_started_link}.

[field]#Button text# [optional]#Optional#::
The text to be displayed in the button on the login form. This value is defaulted to `Login with {identity_provider}` but it may be modified to your preference.

[field]#Scope# [optional]#Optional#::
Some identity providers allow you to select and configure custom scopes.
{scope_addon}

[field]#Linking strategy# [optional]#Optional# [default]#defaults to `{linking_strategy}`#::
The linking strategy for the {identity_provider} provider. link:/docs/v1/tech/identity-providers/#linking-strategies[See Linking Strategies for more].

[field]#Reconcile lambda# [optional]#Optional#::
A lambda may be utilized to map custom claims returned from {identity_provider}.
+
To configure a lambda, navigate to [breadcrumb]#Settings -> Lambdas#. link:/docs/v1/tech/lambdas/[See the lambda documentation for more].

[field]#Debug enabled# [optional]#Optional# [default]#defaults to `false`#::
Enable debug to create event log entries during the user login process. This will assist you in debugging integration issues.
+
