---
layout: passport-doc
title: Troubleshooting
description: Troubleshoot any issues that might arise while install or running Passport or contact Inversoft Support for assistance.
---

== Overview

If any problems arise or if you are unable to access Passport, consult the Passport log files. In most cases API errors will be written out to the passport-backend.log file.

Please email support@inversoft.com if you need assistance. If possible, when contacting Inversoft support, zip the contents of the logs directory and attach it to the email.

=== Logs

The following are the default locations for each of the Passport log files. You may or may not have all of the Passport services installed on the same system so you may not have all of the following logs on your server.

[source,shell]
.Linux and Mac OS X
----
/usr/local/inversoft/logs/passport-backend.log
/usr/local/inversoft/logs/passport-frontend.log
/usr/local/inversoft/logs/passport-search-engine.log
----

These paths assume the suggested product location of `C:\inversoft`. This path may be different on your system depending on where you unpacked the zip files.

[source,shell]
.Windows
----
C:\inversoft\logs\passport-backend.log
C:\inversoft\logs\passport-frontend.log
C:\inversoft\logs\passport-search-engine.log
----
