@startuml
  !include ../../_config.plantuml

participant "User/Browser" as User
participant "The ATM" as php
User -> php : View Initial Page
User -> php : Click Login 
User -> FusionAuth : Request Login Page
FusionAuth -> User : Return Login Page
User -> FusionAuth : Provides Credentials
FusionAuth -> User : Redirect With Authorization Code 
User -> php : Request Redirect URI
php -> FusionAuth : Request Access Token 
FusionAuth -> php : Return Access Token
php -> FusionAuth : Request User Info While Sending Token
FusionAuth -> php : Return User Info
php -> php : Store User Info in Session
php -> User : Display User Info
@enduml
