@startuml
  !include ../../_config.plantuml
Gatsby -> NodeApp : Click login
NodeApp -> FusionAuth : Forward user
FusionAuth -> FusionAuth: Credentials verified
FusionAuth -> NodeApp : Authorization Code
NodeApp -> FusionAuth : Request Access Token 
FusionAuth -> NodeApp : Access Token
NodeApp -> NodeApp : Store access token in session
Gatsby -> NodeApp : Request user info
NodeApp -> FusionAuth : Access token and user info request
FusionAuth -> NodeApp : user info
NodeApp -> Gatsby : user info
@enduml
