@startuml
  !include ../../_config.plantuml
User -> Gatsby : View Page
User -> NodeApp : Click Login 
NodeApp -> FusionAuth : Forward User With PCKE Challenge
User -> FusionAuth : Provides Credentials
FusionAuth -> NodeApp : Send Authorization Code and Verifier
FusionAuth -> FusionAuth : Validate Challenge and Verifier
NodeApp -> FusionAuth : Request Access Token 
FusionAuth -> NodeApp : Send Access Token
NodeApp -> NodeApp : Store Access Token in Session
Gatsby -> NodeApp : Request User Info
NodeApp -> FusionAuth : Request User Info While Sending Token
FusionAuth -> NodeApp : Send User Info
NodeApp -> Gatsby : Send User Info
Gatsby -> User : Display User Info
@enduml
