@startuml
  !include ../../_config.plantuml

participant "User/Browser" as User
User -> Gatsby : View Initial Page
User -> NodeApp : Click Login 
NodeApp -> User : Generate PCKE Challenge, Redirect User
User -> FusionAuth : Request Login Page
FusionAuth -> User : Return Login Page
User -> FusionAuth : Provides Credentials
FusionAuth -> User : Redirect With Authorization Code 
User -> NodeApp : Request Redirect URI
NodeApp -> FusionAuth : Request Access Token 
FusionAuth -> FusionAuth : Validate Challenge and Verifier
FusionAuth -> NodeApp : Return Access Token
NodeApp -> NodeApp : Store Access Token in Session
NodeApp -> Gatsby : Return Session Cookie \nAnd Redirect To Profile Page
Gatsby -> NodeApp : Request User Info
NodeApp -> FusionAuth : Request User Info While Sending Token
FusionAuth -> NodeApp : Return User Info
NodeApp -> Gatsby : Return User Info
Gatsby -> User : Display User Info
@enduml
