@startuml
  !include ../../../../_config.plantuml
  !include ../_mobile-participants.plantuml
  !include ../_mobile-intro.plantuml
  !include _initialize.plantuml

  == Login ==
  Mobile->Store : POST /api/login
  Store->FusionAuth : POST /api/login
  FusionAuth->Store : (User, Refresh Token and JWT)
  Store->Mobile : (User, Refresh Token and JWT)

  !include _shopping-cart-refresh-jwt-load.plantuml

  !include _shopping-cart-refresh-jwt-refresh.plantuml

  !include _shopping-cart-refresh-jwt-relogin.plantuml

  !include ../_mobile-attack-vectors.plantuml

  !include _stolen-refresh-token-refresh-jwt.plantuml

  !include _stolen-jwt-refresh-jwt.plantuml
@enduml