To delete your account, take the following steps:

* delete all deployments
* switch your account to the community plan

For security reasons, we are not able to cancel accounts with deployments that could potentially contain critical user data.

[NOTE.note]
====
FusionAuth require that customers delete their own deployments using the account portal.
====

To remove your deployments, please https://account.fusionauth.io/account/deployment/[log into your account and navigate to your deployments]. Once you see your deployment, you can click the [uielement]#Action# button and select [uielement]#Delete#. After a deployment is destroyed, you won't be charged for it.

Then, https://account.fusionauth.io/account/plan/[switch your plan to to the community plan]. After the current billing cycle is done, you won't be charged. (Plans run for a month.)

After deleting your deployments and changing your plan, your account will not be charged. It is inactive and can be deleted.

At this time, to delete your account details, please https://account.fusionauth.io/account/support/[open a support ticket].
