=== TLS v1.2

The first step in securing your {request_entity}s is to ensure that they are using TLS v1.2. You should be using a web server that is configured with a certificate from a valid certificate authority and be configured to only receive traffic that is over a secure connection. We also recommend that you disable all older secure protocols including SSL, TLS 1.0 and TLS 1.1.

If you need a certificate, most cloud providers offer certificates or you can use LetsEncrypt to generate a certificate and ensure it is always up-to-date.

=== Headers

When you configure your {request_entity} with FusionAuth, you should include a security header of some kind. There are two ways to define a security header:

* Add a Basic Authentication username and password under the Security tab
* Define an HTTP header under the Headers tab

In either case, your {request_entity} code should validate the security header to ensure the event is coming from FusionAuth. Here's some example code that validates an `Authorization` header:

[source,javascript, subs="attributes"]
.Example {request_entity}
----
router.route('/fusionauth-{request_entity_lc}').post((req, res) => {
  const authorization = req.header('Authorization');
  if (authorization !== 'API-KEY') {
    res.status(401).send({
      'errors': [{
        'code': '[notAuthorized]'
      }]
    });
  } else {
    // ...
  }
});
----

=== Client Certificates

You may create a client certificate to secure your {request_entity}. {ssl_certificate_sentence}. It is used to establish a TLS connection to the {request_entity}.

=== Firewalls

In addition to using TLS and a security header, you might also want to put a firewall in front of your {request_entity}. In most cases, this firewall will only allow traffic to your {request_entity} that originated from your FusionAuth server. Depending on how you are hosting your {request_entity}, you might be able to lock down the URL for your {request_entity} specifically. You might also leverage an API gateway or a proxy to ensure that only traffic coming from FusionAuth is routed to your {request_entity}. The exact specifics of deploying and configuring a Firewall are outside the scope of this document, but you can consult the documentation for your proxy, API Gateway or hosting provider to determine how to manage the firewall.

As an example, you can configure an AWS Application Load Balancer so that traffic coming from the IP address of your FusionAuth servers with a URL of `\https://apis.mycompany.com/fusionauth-{request_entity_lc}` is routed through. You can then configure the Application Load Balancer so that all other traffic to that URL is rejected.

