Please review the procedure outlined below if attempting to perform a clean install or upgrade using RPM's and have experienced a failure that you have been unable to resolve. Please only consider these steps after other attempts have been unsuccessful.

[WARNING]
====
This will completely remove FusionAuth App and FusionAuth Search from your server. Proceed with caution.

It is always recommended you back up the database before performing an upgrade or troubleshooting steps outlined here.
====

The following steps will produce a clean installation preserving:

- The FusionAuth config file found in `/usr/local/fusionauth/config/fusionauth.properties`
- The Elasticsearch index found in `/usr/local/fusionauth/data`

Below assumes both `fusionauth-app` and `fusionauth-search` will be uninstalled and reinstalled together. If you are not using `fusionauth-search`, you may ignore the steps related to this service.

=== Manual Removal Steps

. Remove the RPM package for `fusionauth-search` and `fusionauth-app`
    * `sudo rpm -e fusionauth-search`
    * `sudo rpm -e fusionauth-app`
+
. Manually delete anything leftover from RPM
    * `sudo rm -rf /usr/local/fusionauth/fusionauth-search/`
    * `sudo rm -rf /usr/local/fusionauth/fusionauth-app/`
    * `sudo rm -rf /usr/local/fusionauth/bin/`
+
. After removal, the following directories will remain:
    * `/usr/local/fusionauth/config/`
    * `/usr/local/fusionauth/data/` - In some cases this directory may not exist
    * `/usr/local/fusionauth/java/` - While safe to delete, it is not necessary.
+
. Reinstall `fusionauth-app` and `fusionauth-search`.
    * Download the desired version of `fusionauth-app` and `fusionauth-search`
    ** link:/direct-download[Direct download].
    ** `sudo rpm -i <file_to_be_installed>.rpm`

