[WARNING]
====
This will completely remove FusionAuth App and FusionAuth Search from your server. +
Proceed with caution. It is recommended you back up the database before performing any troubleshooting steps listed here.
====

=== A Final Option

Please review the procedure outlined below if attempting set up a clean install or upgrade using RPM's.  However, this is an option of final recourse and only necessary if unexpected upgrade or installation issues arise.

The following steps will produce a clean installation preserving:

- The FusionAuth config file found in `/usr/local/fusionauth/config/fusionauth.properties`
- The Elasticsearch index found in `/usr/local/fusionauth/data`

Below assumes both FusionAuth App and FusionAuth Search will be uninstalled and reinstalled together (your setup may vary).

==== Manual Removal Steps

1. Remove the RPM package for `fusionauth-search` and `fusionauth-app`
- `sudo rpm -e fusionauth-search`
- `sudo rpm -e fusionauth-app`

2. Manually delete anything leftover from RPM
- `sudo rm -rf /usr/local/fusionauth/fusionauth-search/`
- `sudo rm -rf /usr/local/fusionauth/fusionauth-app/`
* `sudo rm -rf /usr/local/fusionauth/bin/`

3. After removal, the following directories will remain:
* `/usr/local/fusionauth/config/`
* `/usr/local/fusionauth/data/`
** (if it exists)
* `/usr/local/fusionauth/java/`
** (is also safe to delete, but is not necessary)

4. Reinstall FusionAuth App and FusionAuth Search
* Using RPM commands
** `sudo rpm -i <file_to_be_installed>.rpm`
** link:/direct-download/[Direct download packages/rpm link]
* If in a Development Environment, FastPath installation is also an option.
**  link:/docs/v1/tech/installation-guide/fast-path/#fast-path-install[Fast Path Install]

[WARNING]
====
It is recommended users not use our FastPath install scripts in a Production Environment.

These scripts are wrappers for our link:/direct-download/[direct download packages]. When installed directly, there is:

- Greater control over how FusionAuth is installed.
- Greater control over the roles/users/permissions assigned to FusionAuth folders and files.
- Greater likelihood of a 'clean' uninstall/upgrade with a package manager (rpm) in the future.
====

