[NOTE.since]
====
Available since 1.48.0

When using the Elasticsearch engine you can use the `nextResults` token to page past the 10,000 limit. See link:/docs/v1/tech/core-concepts/search#extended-pagination[Extended Pagination] for more information.
====

You can work around the user search limit by writing one or more search queries to return less than 10,000 users. You can know if the query returns more than that limit by using the `accurateTotal` request parameter. The link:/docs/v1/tech/apis/users#search-for-users[User Search API] contains more information about the `accurateTotal` parameter and its effect.

For example, if you needed to download all users, you could query for users with an email address starting with `A`, then starting with `B`, and so on. Here's a https://github.com/FusionAuth/fusionauth-example-full-user-search[sample shell script which retrieves all users] using this strategy.

If you have access to the Elasticsearch server, you may also run your query directly against it. The Elasticsearch query result will return Elasticsearch document Ids. Each document Id corresponds to a FusionAuth user Id. To retrieve user data, which is most likely what you are after, use the link:/docs/v1/tech/apis/users#search-for-users[User Search API] with one or more user Ids.
