[.api]
[field]#applicationId# [type]#[UUID]#::
The unique Id of the Application for which the User has been authenticated.

ifdef::show_since[]
[field]#birthdate# [type]#[String]# [since]#Available since 1.1.0#::
endif::[]
ifndef::show_since[]
[field]#birthdate# [type]#[String]#::
endif::[]
The birthDate of the User if available.
Format will be in `YYYY-MM-DD` as defined by the OpenID Connect core specification.

[field]#email# [type]#[String]#::
The email address of the User.

[field]#email_verified# [type]#[Boolean]#::
Indicates if the User's email has been verified.

ifdef::show_since[]
[field]#family_name# [type]#[String]# [since]#Available since 1.1.0#::
endif::[]
ifndef::show_since[]
[field]#family_name# [type]#[String]#::
endif::[]
The last name of the User if available.

ifdef::show_since[]
[field]#given_name# [type]#[String]# [since]#Available since 1.1.0#::
endif::[]
ifndef::show_since[]
[field]#given_name# [type]#[String]#::
endif::[]
The first name of the User if available.

ifdef::show_since[]
[field]#name# [type]#[String]# [since]#Available since 1.1.0#::
endif::[]
ifndef::show_since[]
[field]#name# [type]#[String]#::
endif::[]
The full name of the User if available.

ifdef::show_since[]
[field]#middle_name# [type]#[String]# [since]#Available since 1.1.0#::
endif::[]
ifndef::show_since[]
[field]#middle_name# [type]#[String]#::
endif::[]
The middle name of the User if available.

ifdef::show_since[]
[field]#phone_number# [type]#[String]# [since]#Available since 1.1.0#::
endif::[]
ifndef::show_since[]
[field]#phone_number# [type]#[String]#::
endif::[]
The phone number of the User if available.

ifdef::show_since[]
[field]#picture# [type]#[String]# [since]#Available since 1.1.0#::
endif::[]
ifndef::show_since[]
[field]#picture# [type]#[String]#::
endif::[]
A URL to a picture of the User if available.

ifdef::show_since[]
[field]#preferred_username# [type]#[String]# [since]#Available since 1.1.0#::
endif::[]
ifndef::show_since[]
[field]#preferred_username# [type]#[String]#::
endif::[]
The username of the User if available.

[field]#roles# [type]#[Array]#::
The roles assigned to the User in the authenticated Application.

[field]#sub# [type]#[UUID]#::
The subject of the access token.
This value is equal to the User's unique Id in FusionAuth.

[source,json]
.Example JSON Response
----
{
  "applicationId": "3c219e58-ed0e-4b18-ad48-f4f92793ae32",
  "birthdate": "1982-03-10",
  "email": "richard@pipedpuper.com",
  "email_verified": true,
  "family_name": "Hendricks",
  "given_name": "Richard",
  "phone_number": "555-555-5555",
  "picture": "http://www.piedpiper.com/app/themes/pied-piper/dist/images/photo-richard.png",
  "roles": [
    "admin"
  ],
  "sub": "858a4b01-62c8-4c2f-bfa7-6d018833bea7"
}
----