@startuml
  !include ../../../_config.plantuml

  participant Browser
  participant Backend
  participant "OAuth Server"

  Browser->Backend : User opens your application in their browser
  Backend->Browser : Your Backend sends back HTML, CSS, and JavaScript
  Browser->"OAuth Server" : User clicks "Login" button and is taken to the OAuth Server login page
  "OAuth Server"->Browser : OAuth Server sends back the login form as HTML, CSS, and JavaScript
  Browser->"OAuth Server" : User fills out login form (or signs up) and submits the form
  "OAuth Server"->Browser : OAuth Server validates their credentials and sends back a redirect with an Authorization Code
  Browser->Backend : The Browser requests the redirect URL in your Backend
  Backend->"OAuth Server" : Calls the OAuth server with the Authorization Code
  "OAuth Server"->Backend : Sends back the tokens
  Backend->Backend : Store the tokens in a session
  Backend->Browser : Redirects the browser to the location that logged in users go
@enduml
