@startuml
  !include ../../../_config.plantuml

participant Browser as browser
participant "Printing Website" as pw
participant "Pinterest Login Service" as auth
participant "Pinterest Photo Service" as photos

browser->pw : Click button in app, as\nuser wants Pinterest photos
pw->browser : Redirect to Pinterest
browser->photos : Request photos
photos->browser : Who are you? Redirect to User Login
browser->auth : Send the login form
auth->browser : Here is the login form
browser->auth : Present user's credentials
auth->browser : What scopes does the \nuser want to grant?
browser->auth : User chooses scopes
auth->browser : Here's the authorization code and a redirect to the Printing Website
browser->pw : Here's an authorization code\n(in the URL)
pw->auth : Here's an authorization code \nand app credentials
auth->pw : Here's an \naccess token
pw->pw : Stores access token
pw->photos : Request photos w/token
photos->pw : Send photos
pw->pw : Takes action based on photos

@enduml
