---
layout: doc
title: Getting Started
description: What is FusionAuth and how to get started
---

:sectnumlevels: 0

== Introduction

FusionAuth is a modern platform for Customer Identity and Access Management (CIAM). FusionAuth provides APIs and a responsive web user interface to support
login, registration, localized email, multi-factor authentication, reporting and much more.

== Core Concepts

Legacy identity technologies have complex hierarchy and cryptic terminology like realms, principals, subjects and distinguished names. Ugh.

In order to simplify something perceived to be complex, the best approach is to go back to the basics, to the atomic elements and throw everything else away.

When we built FusionAuth we took the back to basics approach. If we had the opportunity to build the next generation of CIAM from scratch we
most certainly would not choose to build it using LDAP or SAML; so, we didn't.

We identified two atomic elements of identify, Users and Applications. Everyone has Users, and Users need to be authenticated to Applications.
For this reason FusionAuth is built upon these two elements; Users and Applications.

=== Users

A user is uniquely identified in any particular tenant by an email address or username. A User can be registered to one or more FusionAuth Applications. A User Registrations
can define one to many Application Roles.

=== Applications

A FusionAuth Application represents an authenticated resource such as a web application, mobile application or any other application that requires authenticated users. A FusionAuth Application is defined by a name and a set of Roles.

== Getting Started

First you will need to install and configure FusionAuth before starting your integration. Here are some links to get you started:

* [Tech Docs] link:../installation-guide/fusionauth-app[Install FusionAuth App]
* [Tutorial] link:../tutorials/#first_login_and_api_keys[First Login and API Keys]
* [Tutorial] link:../tutorials/#setup_an_application[Setup an Application]
* [Tutorial] link:../tutorials/#registering_a_user_and_logging_users_in_via_the_api[Registering a User and Logging Users in via the API]
* [Tech Docs] link:../apis/[API Docs]
