==== Response Body

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]#::
This is an optional Application specific override for the top level [field]#buttonText#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]# [default]#defaults to `true`#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]# [default]#defaults to `false`#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.applicationConfiguration``[applicationId]``.keyId# [type]#[UUID]#::
This is an optional Application specific override for the top level [field]#keyId#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.scope# [type]#[String]#::
This is an optional Application specific override for for the top level [field]#scope#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.servicesId# [type]#[String]#::
This is an optional Application specific override for for the top level [field]#servicesId#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.teamId# [type]#[String]#::
This is an optional Application specific override for for the top level [field]#teamId#.

[field]#identityProvider.buttonText# [type]#[String]#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.debug# [type]#[Boolean]# [default]#defaults to `false`#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
+
This is useful for debugging purposes, but is not intended to be left on during production. It should be enabled during integration or if you are experiencing an issue with this identity provider.

[field]#identityProvider.enabled# [type]#[Boolean]# [default]#defaults to `false`#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.id# [type]#[UUID]#::
The Id of the Apple identity provider, which will always be `13d2a5db-7ef9-4d62-b909-0df58612e775`.

[field]#identityProvider.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was added to the FusionAuth database.

[field]#identityProvider.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was updated in the FusionAuth database.

[field]#identityProvider.keyId# [type]#[UUID]#::
The unique Id of the private key downloaded from Apple and imported into Key Master that will be used to sign the client secret.

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]#::
The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.

[field]#identityProvider.name# [type]#[String]#::
The name of the provider, this field will always be set to `Apple`.

[field]#identityProvider.scope# [type]#[String]#::
The top-level space separated scope that you are requesting from Apple.

[field]#identityProvider.servicesId# [type]#[String]#::
The Apple Services identifier found in your Apple Developer Account which has been configured for Sign in with Apple.

[field]#identityProvider.teamId# [type]#[String]#::
The Apple App ID Prefix, or Team ID found in your Apple Developer Account which has been configured for Sign in with Apple.

[field]#identityProvider.type# [type]#[String]#::
The type of this provider, this field will always be set to `Apple`.

[source,json]
.Example Apple Response JSON
----
include::../../../../src/json/identity-providers/apple-response.json[]
----
