==== Request Body

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]# [optional]#Optional#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `true`#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.claimMap# [type]#[Map<String, String>]# [optional]#Optional#::
include::_claim_mappings.adoc[]

[field]#identityProvider.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`# [since]#Available Since 1.7.3#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
+
This is useful for debugging purposes, but is not intended to be left on during production. It should be enabled during integration or if you are experiencing an issue with this identity provider.

[field]#identityProvider.domains# [type]#[Array<String>]# [optional]#Optional#::
An array of domains that are managed by this Identity Provider.

[field]#identityProvider.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.headerKeyParameter# [type]#[String]# [required]#Required#::
The name header claim that identifies the public key used to verify the signature. In most cases this be `kid` or `x5t`.

[field]#identityProvider.keys# [type]#[Map<String, String>]# [optional]#Optional#::
A map of public keys used to verify JWT signatures issued from the configured Identity Provider. The key is the key identifier, this
may be referred to as the `kid` or for X.509 certificates the `x5t` claim may be used.
+
The map may contain one entry with an empty map key. When provided this key will be used when no header claim is provided to indicate
which public key should be used to verify the signature. Generally speaking this will only be used when the Identity Provider issues
JWTs without a key identifier in the header.

[field]#identityProvider.name# [type]#[String]# [required]#Required#::
The name of the Identity Provider.

[field]#identityProvider.oauth2.authorization_endpoint# [type]#[String]# [optional]#Optional#::
The authorization endpoint for this Identity Provider. This value is not utilized by FusionAuth is only provided to be returned by the
Lookup Identity Provider API response. During integration you may then utilize this value to perform the browser redirect to the OAuth2
authorize endpoint.

[field]#identityProvider.oauth2.token_endpoint# [type]#[String]# [optional]#Optional#::
The token endpoint for this Identity Provider. This value is not utilized by FusionAuth is only provided to be returned by the
Lookup Identity Provider API response. During integration you may then utilize this value to complete the OAuth2 grant workflow.

[field]#identityProvider.type# [type]#[String]# [required]#Required#::
This field must be set to `ExternalJWT`.

[field]#identityProvider.uniqueIdentityClaim# [type]#[String]# [required]#Required#::
The name of the claim that represents the unique identify of the User. This will generally be `email` or the name of the claim that provides
the email address.

[source,json]
.Example Request JSON
----
include::../../../../src/json/identity-providers/external-jwt-request.json[]
----
