==== Response Body

[.api]
[field]#identityProvider.appId# [type]#[String]#::
The top-level Facebook `appId` for your Application. This value is retrieved from the Facebook developer website when you setup your Facebook developer account.

[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.appId# [type]#[String]#::
This is an optional Application specific override for the top level [field]#appId#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]#::
This is an optional Application specific override for the top level [field]#buttonText#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.client_secret# [type]#[String]#::
This is an optional Application specific override for the top level [field]#client_secret#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.applicationConfiguration``[applicationId]``.fields# [type]#[String]#::
This is an optional Application specific override for for the top level [field]#fields#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.permissions# [type]#[String]#::
This is an optional Application specific override for the top level [field]#permissions#.

[field]#identityProvider.buttonText# [type]#[String]#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.client_secret# [type]#[String]#::
The top-level client secret to use with the Facebook Identity Provider when retrieving the long-lived token. This value is retrieved from the Facebook developer website when you setup your Facebook developer account.

[field]#identityProvider.debug# [type]#[Boolean]# [since]#Available since 1.7.3#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.

[field]#identityProvider.enabled# [type]#[Boolean]#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.fields# [type]#[String]#::
The top-level fields that you are requesting from Facebook.

[field]#identityProvider.id# [type]#[UUID]#::
The Id of the Facebook identity provider, which will always be `56abdcc7-8bd9-4321-9621-4e9bbebae494`.

[field]#identityProvider.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was added to the FusionAuth database.

[field]#identityProvider.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was updated in the FusionAuth database.

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]# [since]#Available since 1.17.0#::
The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.

[field]#identityProvider.name# [type]#[String]#::
The name of the provider, this field will always be set to `Facebook`.

[field]#identityProvider.permissions# [type]#[String]#::
The top-level permissions that your application is asking of the user's Facebook account.

[field]#identityProvider.type# [type]#[String]#::
The type of this provider, this field will always be set to `Facebook`.

[source,json]
.Example Facebook Response JSON
----
include::../../../../src/json/identity-providers/facebook-response.json[]
----
