==== Response Body

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.applicationConfiguration``[applicationId]``.relyingPartyApplicationId# [type]#[String]#::
This is an optional Application specific override for the top level [field]#relyingPartyApplicationId# value.

[field]#identityProvider.applicationConfiguration``[applicationId]``.relyingPartyURL# [type]#[String]#::
This is an optional Application specific override for the top level [field]#relyingPartyURL# value.

[field]#identityProvider.debug# [type]#[Boolean]#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.

[field]#identityProvider.enabled# [type]#[Boolean]#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.id# [type]#[UUID]#::
The Id of the HYPR identity provider, which will always be `778985b7-6fd8-414d-acf2-94f18fb7c7e0`.

[field]#identityProvider.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the provider was added to the FusionAuth database.

[field]#identityProvider.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the provider was updated in the FusionAuth database.

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]# [since]#Available since 1.17.0#::
The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.

[field]#identityProvider.name# [type]#[String]#::
The name of the provider, this fill will always be set to `HYPR`.

[field]#identityProvider.relyingPartyApplicationId# [type]#[String]#::
The Relying Party Application identifier provided to you by HYPR.

[field]#identityProvider.relyingPartyURL# [type]#[String]#::
The Relying Party URL provided to you by HYPR.

[field]#identityProvider.type# [type]#[String]#::
The type of this provider, this field will always be set to `HYPR`.

[source,json]
.Example HYPR Response JSON
----
include::../../../../src/json/identity-providers/hypr-response.json[]
----
