==== Request Body

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]# [optional]#Optional#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `true`#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.applicationConfiguration``[applicationId]``.relyingPartyApplicationId# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#relyingPartyApplicationId# value.

[field]#identityProvider.applicationConfiguration``[applicationId]``.relyingPartyURL# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#relyingPartyURL# value.

[field]#identityProvider.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
+
This is useful for debugging purposes, but is not intended to be left on during production. It should be enabled during integration or if you are experiencing an issue with this identity provider.

[field]#identityProvider.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.17.0#::
The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
+
The specified Lambda Id must be of type `HYPRReconcile`

[field]#identityProvider.relyingPartyApplicationId# [type]#[String]# [required]#Required#::
The Relying Party Application identifier provided to you by HYPR.

[field]#identityProvider.relyingPartyURL# [type]#[String]# [required]#Required#::
The Relying Party URL provided to you by HYPR.

[field]#identityProvider.type# [type]#[String]# [required]#Required#::
This field must be set to `HYPR`.

[source,json]
.Example HYPR Request JSON
----
include::../../../../src/json/identity-providers/hypr-request.json[]
----
