// parameter_prefix is either blank for parameters or "search." for body

[.api]

[field]#{parameter_prefix}name# [type]#[String]# [optional]#Optional#::
The string to search for in the Identity Provider name. This can contain wildcards using an asterisk (`*`). This search parameter is case-insensitive.

[field]#{parameter_prefix}numberOfResults# [type]#[Integer]# [optional]#Optional# [default]#defaults to `25`#::
The number of results to return from the search.

[field]#{parameter_prefix}orderBy# [type]#[String]# [optional]#Optional# [default]#defaults to `name ASC`#::
The field to order the search results as well as an order suffix.
+
The possible values are:
+
 * `id` - the UUID of the Identity Provider
 * `insertInstant` - the link:/docs/v1/tech/reference/data-types#instants[instant] when the Identity Provider was created
 * `name` - the Identity Provider name
 * `enabled` - whether the identity provider is enabled
+
The order suffix  is optional. Possible values of the order suffix are `ASC` or `DESC`. If omitted, the default sort order is `ASC`.
+
For example, to order the results by the insert instant in a descending order, use `insertInstant DESC`.

[field]#{parameter_prefix}startRow# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The offset into the total results. In order to paginate the results, increment this value by the [field]#numberOfResults# for subsequent requests.


ifeval::["{parameter_prefix}" == "search."]
[source,json]
.Example Request JSON
include::../../../../src/json/identity-providers/search-post-request.json[]
endif::[]

