==== Request Body

[.api]
[field]#applicationId# [type]#[UUID]# [required]#Required#::
The Id of the Application the user is to be logged into. This application must have {loginProvider} login enabled for this request to succeed.

[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the identity provider to process this login request.
+
ifeval::["{loginProvider}" == "Apple"]
For the {loginProvider} identity provider, this value will always be `13d2a5db-7ef9-4d62-b909-0df58612e775`.
endif::[]
ifeval::["{loginProvider}" == "Facebook"]
For the {loginProvider} identity provider, this value will always be `56abdcc7-8bd9-4321-9621-4e9bbebae494`.
endif::[]
ifeval::["{loginProvider}" == "HYPR"]
For the {loginProvider} identity provider, this value will always be `778985b7-6fd8-414d-acf2-94f18fb7c7e0`.
endif::[]
ifeval::["{loginProvider}" == "LinkedIn"]
For the {loginProvider} identity provider, this value will always be `6177c09d-3f0e-4d53-9504-3600b1b23f46`.
endif::[]
ifeval::["{loginProvider}" == "Twitter"]
For the {loginProvider} identity provider, this value will always be `45bb233c-0901-4236-b5ca-ac46e2e0a5a5`.
endif::[]
ifdef::idp_id[]
For the {idp_display_name} identity provider, this value will always be `{idp_id}`.
endif::[]

[field]#ipAddress# [type]#[String]# [optional]#Optional#::
The IP address of the end-user that is logging into FusionAuth. If this value is omitted FusionAuth will attempt to obtain the IP address of
the client, the value will be that of the `X-Forwarded-For` header if provided or the last proxy that sent the request. The IP address will
be stored in the User login history.

ifeval::["{loginProvider}" == "Apple"]
[field]#data.appleUser# [type]#[String]# [optional]#Optional#::
The Apple user object. The first time a user completes the Sign in with Apple flow a user object will be returned, when this occurs pass it in using this property. During subsequent authentication requests to Apple the user object will not be returned.

[field]#data.code# [type]#[String]# [required]#Required#::
The authorization code returned from the Sign in with Apple.

[field]#data.id_token# [type]#[String]# [required]#Required#::
The Apple `id_token` returned during Sign in with Apple.

[field]#data.redirect_uri# [type]#[String]# [required]#Required#::
The authorized redirect URI from your Sign in with Apple configuration. This value will be the publicly available URL of FusionAuth with the `/oauth2/callback` suffix.
endif::[]
ifeval::["{loginProvider}" == "Facebook"]
[field]#data.code# [type]#[String]# [optional]#Optional#::
When using the authorization code grant, Facebook will have returned an authorization code. To complete the login request, provide the `code` and the `redirect_uri` parameters to allow FusionAuth to complete this grant by exchanging the authorization code for an `access_token`.
+
When using `code` you must also supply `redirect_uri`. If `code` is not provided, then `token` will be required.

[field]#data.redirect_uri# [type]#[String]# [optional]#Optional#::
The redirect URI that was provided to the Facebook Authorization endpoint. This value will be sent to the Token Info API as the `redirect_uri` parameter.

[field]#data.token# [type]#[String]# [optional]#Optional#::
When using a popup or other login mode where Facebook has already returned you an `accessToken` through a JavaScript callback or other mechanism, you will send this value in the `token` parameter. FusionAuth will use this value to request user details and then complete the login.
+
When using `token` you do not have to supply `redirect_uri`. If `token` is not provided, then `code` will be required.

endif::[]
ifeval::["{idp_type}" == "Google"]
[field]#data.code# [type]#[String]# [optional]#Optional#::
When using the authorization code grant, Google will have returned an authorization code. To complete the login request, provide the `code` and the `redirect_uri` parameters to allow FusionAuth to complete this grant by exchanging the authorization code for an `access_token`.
+
When using `code` you must also supply `redirect_uri`. If `code` is not provided, then `token` will be required.

[field]#data.redirect_uri# [type]#[String]# [optional]#Optional#::
The redirect URI that was provided to the Google Authorization endpoint. This value will be sent to the Token Info API as the `redirect_uri` parameter.

[field]#data.token# [type]#[String]# [optional]#Optional#::
When using a popup or other login mode where Google has already returned you an `id_token` through a JavaScript callback or other mechanism, you will send this value in the `token` parameter. FusionAuth will use this value to request user details and then complete the login.
+
When using `token` you do not have to supply `redirect_uri`. If `token` is not provided, then `code` will be required.
endif::[]
ifeval::["{loginProvider}" == "HYPR"]
[field]#data.code# [type]#[String]# [required]#Required#::
The `code` returned from the Start Login API.
endif::[]
ifeval::["{loginProvider}" == "LinkedIn"]
[field]#data.token# [type]#[String]# [required]#Required#::
The LinkedIn id token returned from their login API. This token will be sent to the LinkedIn Lite Profile And Email Address APIs as a bearer token in the `Authorization` header.
endif::[]
ifeval::["{loginProvider}" == "SAML v2"]
[field]#data.samlResponse# [type]#[String]# [required]#Required#::
The `SAMLResponse` parameter from the form submit (via a `POST` request) from the SAML v2 identity provider.
endif::[]
ifeval::["{loginProvider}" == "SAML v2 IdP Initiated"]
[field]#data.samlResponse# [type]#[String]# [required]#Required#::
The `SAMLResponse` parameter from the form submit (via a `POST` request) from the SAML v2 IdP Initiated identity provider.
endif::[]
ifeval::["{loginProvider}" == "Twitter"]
[field]#data.oauth_token# [type]#[String]# [required]#Required#::
The Twitter oauth token returned from their login API. This token will be sent to the Twitter OAuth Access Token API as the `oauth_token` parameter.
+
[since]#Since 1.25.0#
Beginning in version 1.25.0, if this value is an access token then it will not be sent to the Twitter OAuth Access Token API, and instead be directly used to call the Twitter Verify Credentials API to obtain user details.  See notes in [field]#oauth_verifier#.

[field]#data.oauth_token_secret# [type]#[String]# [required]#Required#::
The Twitter oauth token secret returned from their login API. This token will be used to sign the request to the OAuth Access Token API.
+
[since]#Since 1.25.0#
Beginning in version 1.25.0, if this value is an access token then it will not be sent to the Twitter OAuth Access Token API, and instead be directly used to call the Twitter Verify Credentials API to obtain user details. See notes in [field]#oauth_verifier#.

[field]#data.oauth_verifier# [type]#[String]# [required]#Required#::
The Twitter oauth verifier returned from their login API. This token will be sent to the Twitter OAuth Access Token API in the request body as the `oauth_verifier` parameter.
+
[since]#Since 1.25.0#
Beginning in version 1.25.0, you may optionally omit the [field]#oauth_verifier# field if the values for [field]#oauth_token# and [field]#oauth_token_secret# are an access token. This allows for a use case where you are not using the FusionAuth themed login pages and you have integrated the Twitter login using this API and prior to calling FusionAuth you have already exchanged these values for a Twitter access token. In this scenario, you may take these two parameters representing the access token and FusionAuth will still complete the login for you by skipping the request to exchange the request token for an access token.
endif::[]
ifeval::["{loginProvider}" == "OpenID Connect"]
[field]#data.code# [type]#[String]# [required]#Required#::
The authorization code, this is the `code` parameter that was returned on the Authorization redirect URI. This code will be sent to the Token endpoint as the `code` parameter.

[field]#data.redirect_uri# [type]#[String]# [required]#Required#::
The redirect URI that was provided to the OpenID Connect Authorization endpoint. This value will be sent to the Token endpoint as the `redirect_uri` parameter.
endif::[]
ifeval::["{idp_token_or_code}" == "code"]
[field]#data.code# [type]#[String]# [required]#Required#::
The authorization code, this is the `code` parameter that was returned on the Authorization redirect URI. This code will be sent to the Token endpoint as the `code` parameter. If `code` is not provided, then the `token` will be required.

[field]#data.redirect_uri# [type]#[String]# [required]#Required#::
The redirect URI that was provided to the {idp_display_name} Authorization endpoint. This value will be sent to the Token endpoint as the `redirect_uri` parameter.
endif::[]
ifeval::["{idp_token_or_code}" == "token"]
[field]#data.oauth# [type]#[String]# [required]#Required#::
The Steam oauth token returned from their login API. This token will be sent to the Steam Token Details API as the `access_token` parameter.
endif::[]

[field]#metaData.device.description# [type]#[String]# [optional]#Optional#::
A human readable description of the device represented by the `device` parameter.

[field]#metaData.device.lastAccessedAddress# [type]#[String]# [optional]#Optional#::
The IP address of this login request.

[field]#metaData.device.name# [type]#[String]# [optional]#Optional#::
A human readable name of the device represented by the `device` parameter.

[field]#metaData.device.type# [type]#[String]# [optional]#Optional#::
The type of device represented by the `device` parameter. The following types may be specified:
+
* `BROWSER`
* `DESKTOP`
* `LAPTOP`
* `MOBILE`
* `OTHER`
* `SERVER`
* `TABLET`
* `TV`
* `UNKNOWN`

[field]#noJWT# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
When this value is set to true a JWT will not be issued as part of this request. The response body will not contain the `token` field, and the `access_token` and `refresh_token` cookies will not be written to the HTTP response.
+
This optional parameter may be helpful when performing high volume authentication requests and the JWT is not being utilized, in this scenario removing the additional latency required to issue and sign the JWT may have a measurable cumulative effect on performance.

ifeval::["{loginProvider}" == "Apple"]
:idp_request: apple
endif::[]
ifeval::["{loginProvider}" == "Facebook"]
:show_code_and_token_examples:
:idp_request: facebook
endif::[]
ifeval::["{idp_type}" == "Google"]
:show_code_and_token_examples:
endif::[]
ifeval::["{loginProvider}" == "HYPR"]
:idp_request: hypr
endif::[]
ifeval::["{loginProvider}" == "LinkedIn"]
:idp_request: linkedin
endif::[]
ifeval::["{loginProvider}" == "Twitter"]
:idp_request: twitter
endif::[]
ifeval::["{loginProvider}" == "OpenID Connect"]
:idp_request: openid-connect
endif::[]
ifeval::["{loginProvider}" == "SAML v2"]
:idp_request: samlv2
endif::[]
ifeval::["{loginProvider}" == "SAML v2 IdP Initiated"]
:idp_request: samlv2
endif::[]
ifdef::idp_lowercase[]
:idp_request: {idp_lowercase}
endif::[]

include::_identity-provider-login-request-example.adoc[]
:show_code_and_token_examples!:
:idp_request!:
