[cols="3a,7a"]
[.api]
.Request Headers
|===
|[field]#X-Forwarded-For# [type]#[String]# [optional]#Optional#
|The IP address of a client requesting authentication. If the IP address is provided it will be stored for login history of the user. It is
generally preferred to specify the IP address in the request body. If it is not provided in the request body this header value will be used
if available, the request body value will take precedence.
|===

[cols="3a,7a"]
[.api]
.Request Body
|===
|[field]#applicationId# [type]#[UUID]# [required]#Required#
|The Id of the Application the user is to be logged into. This application must have {loginProvider} login enabled for this request to succeed.

|[field]#identityProviderId# [type]#[UUID]# [required]#Required#
|The unique Id of the identity provider to process this login request.

ifeval::["{loginProvider}" == "HYPR"]
For the {loginProvider} identity provider, this value will always be `778985b7-6fd8-414d-acf2-94f18fb7c7e0`.
endif::[]

|[field]#ipAddress# [type]#[String]# [optional]#Optional#
|The IP address of the end-user that is logging into FusionAuth. If this value is omitted FusionAuth will attempt to obtain the IP address of
the client, the value will be that of the `X-Forwarded-For` header if provided or the last proxy that sent the request. The IP address will
be stored in the User login history.
|===

[source,json]
.Example Request JSON
----
ifeval::["{loginProvider}" == "HYPR"]
include::../../../../src/json/identity-providers/start/hypr-request.json[]
endif::[]
----

