==== Response Body

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]#::
This is an optional Application specific override for the top level [field]#buttonText#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.client_id# [type]#[String]#::
This is an optional Application specific override for the top level [field]#client_id#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.client_secret# [type]#[String]#::
This is an optional Application specific override for the top level [field]#client_secret#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.applicationConfiguration``[applicationId]``.scope# [type]#[String]#::
This is an optional Application specific override for for the top level [field]#scope#.

[field]#identityProvider.buttonText# [type]#[String]#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.client_id# [type]#[String]#::
The Linked client id for your App. This value is retrieved from the LinkedIn developer website when you set up your LinkedIn App.

[field]#identityProvider.client_secret# [type]#[String]#::
The top-level client secret to use with the LinkedIn Identity Provider when retrieving the long-lived token. This value is retrieved from the LinkedIn developer website when you set up your LinkedIn App.

[field]#identityProvider.debug# [type]#[Boolean]#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.

[field]#identityProvider.enabled# [type]#[Boolean]#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.id# [type]#[UUID]#::
The Id of the LinkedIn identity provider, which will always be `6177c09d-3f0e-4d53-9504-3600b1b23f46`.

[field]#identityProvider.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was added to the FusionAuth database.

[field]#identityProvider.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was updated in the FusionAuth database.

[field]#identityProvider.name# [type]#[String]#::
The name of the provider, this field will always be set to `LinkedIn`.

[field]#identityProvider.scope# [type]#[String]#::
The top level scope that you are requesting from LinkedIn.

[field]#identityProvider.type# [type]#[String]#::
The type of this provider, this field will always be set to `LinkedIn`.

[source,json]
.Example LinkedIn Response JSON
----
include::../../../../src/json/identity-providers/linkedin-response.json[]
----
