==== Response Body

[.api]
[field]#identityProviderLink.displayName# [type]#[String]#::
A optional human readable name for this link such as an email address, username or given name. This value should be used to make it easier to identify the user this link represents in the remote identity provider.
+
Please note, that this value will always be overwritten during login to reflect the most current information from the identity provider. In most cases this value will be an email address or username.

[field]#identityProviderLink.identityProviderId# [type]#[UUID]#::
The unique Id of the identity provider.

[field]#identityProviderLink.identityProviderName# [type]#[String]# [since]#Available since 1.47.0#::
The name of the identity provider.

[field]#identityProviderLink.identityProviderType# [type]#[String]#::
The type of the identity provider.

[field]#identityProviderLink.identityProviderUserId# [type]#[String]#::
The Id for the User that is provided by the identity provider.

[field]#identityProviderLink.userId# [type]#[UUID]#::
The unique Id of the FusionAuth User that is being linked to the identity provider.

[field]#identityProviderLink.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] the Link was created.

[field]#identityProviderLink.lastLoginInstant# [type]#[Long]#::
The last link:/docs/v1/tech/reference/data-types#instants[instant] of the User's most recent login to the identity provider linked Application.

[field]#identityProviderLink.tenantId# [type]#[UUID]#::
The Id of the Tenant that this User belongs to.

[field]#identityProviderLink.token# [type]#[String]# ::
The token returned from the identity provider. This is treated as an opaque token as the type varies by identity provider, this value may not be returned by all identity providers. When provided, this token is typically a long lived access or refresh token, but consult individual identity provider documentation for specifics.

[field]#identityProviderLink.userId# [type]#[UUID]#::
The unique Id of the FusionAuth User that is linked to the identity provider.

[source,json]
.Example Response JSON
----
include::../../../../src/json/identity-providers/links/response.json[]
----
