==== Request Body

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]# [optional]#Optional#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#buttonText#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.client_id# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#client_id#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.client_secret# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#client_secret#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `true`#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.applicationConfiguration``[applicationId]``.scope# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for for the top level [field]#scope#.

[field]#identityProvider.buttonText# [type]#[String]# [required]#Required#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.client_id# [type]#[String]# [required]#Required#::
The top-level LinkedIn client id for your Application. This value is retrieved from the LinkedIn developer website when you set up your LinkedIn app.

[field]#identityProvider.client_secret# [type]#[String]# [required]#Required#::
The top-level client secret to use with the LinkedIn Identity Provider when retrieving the long-lived token. This value is retrieved from the LinkedIn developer website when you set up your LinkedIn app.

[field]#identityProvider.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`# [since]#Available since 1.7.3#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
+
This is useful for debugging purposes, but is not intended to be left on during production. It should be enabled during integration or if you are experiencing an issue with this identity provider.

[field]#identityProvider.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.17.0#::
The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
+
The specified Lambda Id must be of type `LinkedInReconcile`.

[field]#identityProvider.scope# [type]#[String]# [optional]#Optional#::
The top-level scope that you are requesting from LinkedIn.

[field]#identityProvider.type# [type]#[String]# [required]#Required#::
This field must be set to `LinkedIn`.

[source,json]
.Example LinkedIn Request JSON
----
include::../../../../src/json/identity-providers/linkedin-request.json[]
----
