[api]
ifeval::["{base_field_name}" != "identityProviderLink"]
[field]#identityProviderLinks# [type]#[Array]#::
The list of Link objects.
endif::[]

[field]#{base_field_name}.displayName# [type]#[String]#::
A human readable name for this link to help you identify this link. This value will generally be an email address, or username. This value is recorded when the link is made, and updated during the next login for this identity provider. This value may not necessarily reflect the username or email you used to authenticate with the 3rd party identity provider.

[field]#{base_field_name}.identityProviderId# [type]#[UUID]#::
The unique Id of the identity provider.

[field]#{base_field_name}.identityProviderUserId# [type]#[String]#::
The unique user Id in the 3rd party identity provider. Ideally this value never changes and will always uniquely identify the user in the 3rd party identity provider.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Link was added to the FusionAuth database.

[field]#{base_field_name}.lastLoginInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the User logged in last with this identity provider using this link.

[field]#{base_field_name}.tenantId# [type]#[UUID]#::
The Id of the Tenant that this User belongs to.

[field]#{base_field_name}.token# [type]#[String]#::
The token returned from the identity provider. This is treated as an opaque token as the type varies by identity provider, this value may not be returned by all identity providers.
+
*Note:*
Prior to version 1.28.0, this value can be retrieved using the link:/docs/v1/tech/apis/registrations[User Registration APIs] using the [field]#registration.token# field.

[field]#{base_field_name}.userId# [type]#[UUID]#::
The FusionAuth User Id that is linked to the identity provider.

ifeval::["{base_field_name}" == "identityProviderLink"]
[source,json]
.Example Response JSON
----
include::../../../../src/json/identity-providers/links/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "identityProviderLink"]
[source,json]
.Example Response JSON for a collection of Links
----
include::../../../../src/json/identity-providers/links/responses.json[]
----
endif::[]
