[api]
ifeval::["{base_field_name}" != "identityProviderLink"]
[field]#identityProviderLinks# [type]#[Array]#::
The list of Link objects.
endif::[]

[field]#{base_field_name}.displayName# [type]#[String]#::
The display name for the user.

[field]#{base_field_name}.identityProviderId# [type]#[UUID]#::
The unique Id of the identity provider.

[field]#{base_field_name}.identityProviderUserId# [type]#[String]#::
The Id for the User that is provided by the identity provider.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Tenant was added to the FusionAuth database.

[field]#{base_field_name}.lastLoginInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the User logged in last.

[field]#{base_field_name}.tenantId# [type]#[UUID]#::
The Id of the Tenant that this User belongs to

[field]#{base_field_name}.token# [type]#[String]#::
The access token, this string is an encoded JSON Web Token (JWT).

[field]#{base_field_name}.userId# [type]#[UUID]#::
The FusionAuth User Id that is linked to the identity provider.

ifeval::["{base_field_name}" == "identityProviderLink"]
[source,json]
.Example Response JSON
----
include::../../../../src/json/identity-providers/links/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "identityProviderLink"]
[source,json]
.Example Response JSON for a collection of Links
----
include::../../../../src/json/identity-providers/links/responses.json[]
----
endif::[]
