==== Example Response JSON

[.api]
[field]#identityProvider.id# [type]#[UUID]#::
The unique Id of the Identity Provider.

[field]#identityProvider.applicationIds# [type]#[Array<UUID>]# [since]#Available since 1.16.0#::
The list of Application Ids that are enabled for this Identity Provider.

[field]#identityProvider.name# [type]#[String]#::
The name of the Identity Provider.

[field]#identityProvider.idpEndpoint# [type]#[String]# [since]#Available since 1.16.0#::
The configured SAML v2 endpoint. This value will only be returned for a SAML v2 Identity Provider. This may be used to aid in building the SAML request so that it does not need to be hard coded in your application.

[field]#identityProvider.oauth2.authorization_endpoint# [type]#[String]#::
The OAuth2 Authorize endpoint. This may be used to as the redirect location to begin the authorize workflow so that it does not need to be hard coded in your application.

[field]#identityProvider.oauth2.token_endpoint# [type]#[String]#::
The OAuth2 Token endpoint. This may be used during your integration so that this URI does not need to be hard coded in your application.

[source,json]
.Example Response JSON for an ExternalJWT or OpenID Connect IdP
----
include::../../../../src/json/identity-providers/lookup/response.json[]
----

[source,json]
.Example Response JSON for a SAML v2 IdP
----
include::../../../../src/json/identity-providers/lookup/samlv2/response.json[]
----

