==== Response Body
:optional_tag:

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]#::
This is an optional Application specific override for the top level [field]#buttonText#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.client_id# [type]#[String]#::
This is an optional Application specific override for the top level [field]#client_id#.

ifeval::["{idp_type" != "Steam"]
[field]#identityProvider.applicationConfiguration``[applicationId]``.client_secret# [type]#[String]#::
This is an optional Application specific override for the top level [field]#client_secret#.
endif::[]

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.applicationConfiguration``[applicationId]``.scope# [type]#[String]#::
This is an optional Application specific override for the top level [field]#scope#.

ifeval::["{idp_type}" == "Steam"]
[field]#identityProvider.applicationConfiguration``[applicationId]``.webAPIKey# [type]#[String]#::
This is an optional Application specific override for the top level [field]#webAPIKey#.
endif::[]

[field]#identityProvider.buttonText# [type]#[String]#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.client_id# [type]#[String]#::
The top-level {idp_display_name} client id for your Application. This value is retrieved from the {idp_display_name} developer website when you setup your {idp_display_name} developer account.

ifeval::["{idp_type" != "Steam"]
[field]#identityProvider.client_secret# [type]#[String]#::
The top-level client secret to use with the {idp_display_name} Identity Provider when retrieving the long-lived token. This value is retrieved from the {idp_display_name} developer website when you setup your {idp_display_name} developer account.
endif::[]

include::_identity-provider-debug-response-parameter.adoc[]

[field]#identityProvider.enabled# [type]#[Boolean]#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.id# [type]#[UUID]#::
The Id of the {idp_display_name} identity provider, which will always be `{idp_id}`.

[field]#identityProvider.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the provider was added to the FusionAuth database.

[field]#identityProvider.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the provider was updated in the FusionAuth database.

include::_identity-provider-linking-strategy-response-parameter.adoc[]

ifdef::idp_login_method[]
include::_identity-provider-login-method-response-parameter.adoc[]
endif::[]

[field]#identityProvider.name# [type]#[String]#::
The name of the provider, this field will always be set to `{idp_type}`.

[field]#identityProvider.scope# [type]#[String]#::
The top-level scope that you are requesting from {idp_display_name}.

include::_identity-provider-tenant-configuration.adoc[]

[field]#identityProvider.type# [type]#[String]#::
The type of this provider, this field will always be set to `{idp_type}`.

ifeval::["{idp_type}" == "Steam"]
[field]#identityProvider.webAPIKey# [type]#[String]#::
The top-level web API key to use with the {idp_display_name} Identity Provider when retrieving the player summary info. This value is retrieved from the {idp_display_name} developer website when you setup your {idp_display_name} developer account.
endif::[]

[source,json]
.Example {idp_display_name} Response JSON
----
include::../../../../src/json/identity-providers/{idp_lowercase}-response.json[]
----
