==== Request Body
ifeval::["{idp_type}" == "Google"]
:display_since_173:
endif::[]

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]# [optional]#Optional#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#buttonText#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.client_id# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#client_id#.

ifeval::["{idp_type" != "Steam"]
[field]#identityProvider.applicationConfiguration``[applicationId]``.client_secret# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#client_secret#.
endif::[]

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `true`#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.applicationConfiguration``[applicationId]``.scope# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#scope#.

ifeval::["{loginProvider}" == "Steam"]
[field]#identityProvider.applicationConfiguration``[applicationId]``.webAPIKey# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#webAPIKey#.
endif::[]

[field]#identityProvider.buttonText# [type]#[String]# [required]#Required#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.client_id# [type]#[String]# [required]#Required#::
The top-level {idp_display_name} client id for your Application. This value is retrieved from the {idp_display_name} developer website when you setup your {idp_display_name} developer account.

ifeval::["{loginProvider}" != "Steam"]
[field]#identityProvider.client_secret# [type]#[String]# [required]#Required#::
The top-level client secret to use with the {idp_display_name} Identity Provider when retrieving the long-lived token. This value is retrieved from the {idp_display_name} developer website when you setup your {idp_display_name} developer account.
endif::[]

include::_identity-provider-debug-request-parameter.adoc[]

[field]#identityProvider.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]# [optional]#Optional# #ifdef::display_since_1170[[since]#Available since 1.17.0#]::
The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
+
The specified Lambda Id must be of type `{idp_type}Reconcile`.

[field]#identityProvider.linkingStrategy# [type]#[String]# [optional]#Optional# [default]#defaults to `{idp_linking_strategy}`#::
The linking strategy to use when creating the link between the {idp_display_name} Identity Provider and the user.
+
The possible values are:
+
* `CreatePendingLink` - Do not automatically link, instead return a pending link identifier that can be used to link to an existing user.
* `LinkAnonymously` - Always create a link based upon the unique Id returned by the identify provider. A username or email is not required and will not be used to link the user. A reconcile lambda will not be used in this configuration.
* `LinkByEmail` - Link to an existing user based upon email. A user will be created with the email returned by the identity provider if one does not already exist.
* `LinkByEmailForExistingUser` - Only link to an existing user based upon email. A user will not be created if one does not already exist with email returned by the identity provider.
* `LinkByUsername` - Link to an existing user based upon username. A user will be created with the username returned by the identity provider if one does not already exist.
* `LinkByUsernameForExistingUser` - Only link to an existing user based upon username. A user will not be created if one does not already exist with username returned by the identity provider.

ifdef::idp_login_method[]
[field]#identityProvider.loginMethod# [type]#[String]# [optional]#Optional# [default]#defaults to `UseRedirect`#::
The login method to use for this Identity Provider.
+
The possible values are:
+
* `UsePopup` - When logging in use a popup window and the {idp_display_name} javascript library.
* `UseRedirect` - When logging in use the {idp_display_name} Oauth redirect login flow.
endif::[]

[field]#identityProvider.scope# [type]#[String]# [optional]#Optional#::
The top-level scope that you are requesting from {idp_display_name}.

[field]#identityProvider.type# [type]#[String]# [required]#Required#::
This field must be set to `{idp_type}`.

ifeval::["{loginProvider}" != "Steam"]
[field]#identityProvider.webAPIKey# [type]#[String]# [required]#Required#::
The top-level web API key to use with the {idp_display_name} Identity Provider when retrieving the player summary info. This value is retrieved from the {idp_display_name} developer website when you setup your {idp_display_name} developer account.
endif::[]

[source,json]
.Example {idp_display_name} Request JSON
----
include::../../../../src/json/identity-providers/{idp_lowercase}-request.json[]
----
:display_since_173!:
