==== Request Body
:optional_tag: pass:normal[[optional]#Optional#]

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]# [optional]#Optional#::
The configuration for each Application that the identity provider is enabled for.

ifeval::["{idp_type}" == "Steam"]
[field]#identityProvider.applicationConfiguration``[applicationId]``.apiMode# [type]#[String]# [optional]#Optional# [since]#Available since 1.44.0#::
This is an optional Application specific override for the top level [field]#apiMode#.
endif::[]

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#buttonText#.
ifeval::["{idp_type}" == "Google"]
+
[since]#Since 1.44.0#
The [field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# value may only be used when the [field]#identityProvider.loginMethod# is set to `UseRedirect`. The button text is managed by Google for all other configurations. Google allows for minor adjustments using their API. You may specify any valid API parameter in the [field]#identityProvider.properties.button# configuration.
endif::[]

[field]#identityProvider.applicationConfiguration``[applicationId]``.client_id# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#client_id#.

ifeval::["{idp_type}" != "Steam"]
[field]#identityProvider.applicationConfiguration``[applicationId]``.client_secret# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#client_secret#.
endif::[]

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `true`#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

ifeval::["{idp_type}" == "Google"]
[field]#identityProvider.applicationConfiguration``[applicationId]``.properties# [type]#[Object]# [optional]#Optional# [since]#Available since 1.44.0#::
This is an optional Application specific override for the top level [field]#properties#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.properties.api# [type]#[String]# [optional]#Optional# [since]#Available since 1.44.0#::
This is an optional Application specific override for the top level [field]#properties.api#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.properties.button# [type]#[String]# [optional]#Optional# [since]#Available since 1.44.0#::
This is an optional Application specific override for the top level [field]#properties.button#.

endif::[]
ifeval::["{idp_type}" != "Steam"]
[field]#identityProvider.applicationConfiguration``[applicationId]``.scope# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#scope#.
ifeval::["{idp_type}" == "Google"]
+
[since]#Since 1.44.0#
The [field]#identityProvider.applicationConfiguration``[applicationId]``.scope# value may only be used when the [field]#identityProvider.loginMethod# is set to `UseRedirect`. The `email`, `profile`, and `openid` scopes will always be requested for all other configurations.
endif::[]
endif::[]

ifeval::["{idp_type}" == "Steam"]
[field]#identityProvider.applicationConfiguration``[applicationId]``.webAPIKey# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#webAPIKey#.

[field]#identityProvider.apiMode# [type]#[String]# [optional]#Optional# [default]#Defaults to `Public`# [since]#Available since 1.44.0#::
Determines which Steam API to utilize.
+
The possible values are:
+
 * `Partner` - The Steam partner API is used. `\https://partner.steam-api.com`
 * `Public` - The public Steam API is used. `\https://api.steampowered.com`
+
The only functional difference between these two APIs is that the public API is rate limited, and the partner API is not. If you are a Steam partner, you will want to set this value to `Partner`. Prior to version `1.44.0`, the public API was always used.
endif::[]

[field]#identityProvider.buttonText# [type]#[String]# [required]#Required#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.
ifeval::["{idp_type}" == "Google"]
+
[since]#Since 1.44.0#
The [field]#identityProvider.buttonText# value may only be used when the [field]#identityProvider.loginMethod# is set to `UseRedirect`. The button text is managed by Google for all other configurations. Google allows for minor adjustments using their API. You may specify any valid API parameter in the [field]#identityProvider.properties.button# configuration.
endif::[]

[field]#identityProvider.client_id# [type]#[String]# [required]#Required#::
The top-level {idp_display_name} client id for your Application. This value is retrieved from the {idp_display_name} developer website when you setup your {idp_display_name} developer account.

ifeval::["{idp_display_name}" != "Steam"]
[field]#identityProvider.client_secret# [type]#[String]# [required]#Required#::
The top-level client secret to use with the {idp_display_name} Identity Provider when retrieving the long-lived token. This value is retrieved from the {idp_display_name} developer website when you setup your {idp_display_name} developer account.
endif::[]

include::_identity-provider-debug-request-parameter.adoc[]

ifeval::["{idp_type}" == "Nintendo"]
[field]#identityProvider.emailClaim# [type]#[String]# [optional]#Optional# [default]#defaults to `email`#::
An optional configuration to modify the expected name of the claim returned by the {idp_display_name} Identity Provider that contains the email address.
endif::[]

[field]#identityProvider.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

include::_identity-provider-reconcileid-request-parameter.adoc[]

include::_identity-provider-linking-strategy-request-parameter.adoc[]

ifdef::idp_login_method[]
include::_identity-provider-login-method-request-parameter.adoc[]
endif::[]

ifeval::["{idp_type}" == "Google"]
[field]#identityProvider.properties# [type]#[Object]# [optional]#Optional# [since]#Available since 1.44.0#::
An object to hold configuration parameters for the https://developers.google.com/identity/gsi/web/reference/html-reference[Google Identity Services API]. See the [field]#identityProvider.properties.api# and [field]#identityProvider.properties.button# fields for more detail on format and configurable values.

[field]#identityProvider.properties.api# [type]#[String]# [optional]#Optional# [default]#defaults to **[see description]**# [since]#Available since 1.44.0#::
Google Identity Services login API configuration in a properties file formatted String. Any attribute from https://developers.google.com/identity/gsi/web/reference/html-reference#element_with_id_g_id_onload[Google's documentation] can be added. Properties can be referenced in templates that support Google login to initialize the API via HTML or JavaScript. The properties specified in this field should not include the `data-` prefix on the property name.
+
If omitted, this value will default to the following properties:
+
[source,properties]
.Default API Configuration Properties
----
auto_prompt=true
auto_select=false
cancel_on_tap_outside=false
context=signin
itp_support=true
----

[field]#identityProvider.properties.button# [type]#[String]# [optional]#Optional# [default]#defaults to **[see description]**# [since]#Available since 1.44.0#::
Google Identity Services button configuration in a properties file formatted String. Any attribute from https://developers.google.com/identity/gsi/web/reference/html-reference#element_with_class_g_id_signin[Google's documentation] can be added. Properties can be referenced in templates that support Google login to render the login button via HTML or JavaScript. The properties specified in this field should not include the `data-` prefix on the property name.
+
If omitted, this value will default to the following properties:
+
[source,properties]
.Default Button Properties
----
logo_alignment=left
shape=rectangular
size=large
text=signin_with
theme=outline
type=standard
----

endif::[]
ifeval::["{idp_type}" != "Steam"]
[field]#identityProvider.scope# [type]#[String]# [optional]#Optional#::
The top-level scope that you are requesting from {idp_display_name}.
ifeval::["{idp_type}" == "Google"]
+
[since]#Since 1.44.0#
The [field]#identityProvider.scope# value may only be used when the [field]#identityProvider.loginMethod# is set to `UseRedirect`. The `email`, `profile`, and `openid` scopes will always be requested for all other configurations.
endif::[]
endif::[]

include::_identity-provider-tenant-configuration.adoc[]

[field]#identityProvider.type# [type]#[String]# [required]#Required#::
This field must be set to `{idp_type}`.

ifeval::["{idp_type}" == "Steam"]
[field]#identityProvider.webAPIKey# [type]#[String]# [required]#Required#::
The top-level web API key to use with the {idp_display_name} Identity Provider when retrieving the player summary info. This value is retrieved from the {idp_display_name} developer website when you setup your {idp_display_name} developer account.
endif::[]

ifeval::["{idp_type}" == "Nintendo"]
[field]#identityProvider.uniqueIdClaim# [type]#[String]# [optional]#Optional# [default]#defaults to `id`#::
An optional configuration to modify the expected name of the claim returned by the {idp_display_name} Identity Provider that contains the user Id.

[field]#identityProvider.usernameClaim# [type]#[String]# [optional]#Optional# [default]#defaults to `preferred_username`#::
An optional configuration to modify the expected name of the claim returned by the {idp_display_name} Identity Provider that contains the username.
endif::[]

[source,json]
.Example {idp_display_name} Request JSON
----
include::../../../../src/json/identity-providers/{idp_lowercase}-request.json[]
----
