==== Response Body

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonImageURL# [type]#[String]#::
This is an optional Application specific override for the top level button image URL.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]#::
This is an optional Application specific override for the top level button text.

[field]#identityProvider.applicationConfiguration``[applicationId]``.client_id# [type]#[String]#::
This is an optional Application specific override for the top level client id.

[field]#identityProvider.applicationConfiguration``[applicationId]``.client_secret# [type]#[String]#::
This is an optional Application specific override for the top level client secret.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.applicationConfiguration``[applicationId]``.scope# [type]#[String]#::
This is an optional Application specific override for for the top level scope.

[field]#identityProvider.buttonImageURL# [type]#[String]#::
The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.buttonText# [type]#[String]#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.debug# [type]#[Boolean]# [since]#Available since 1.7.3#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.

[field]#identityProvider.enabled# [type]#[Boolean]#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.domains# [type]#[Array<String>]#::
This is an optional list of domains that this OpenID Connect provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an OpenID Connect identity provider should be used. If an OpenID Connect provider should be used, the browser is redirected to the authorization endpoint of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.

[field]#identityProvider.id# [type]#[UUID]#::
The Id of the provider.

[field]#identityProvider.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was added to the FusionAuth database.

[field]#identityProvider.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was updated in the FusionAuth database.

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]# [since]#Available since 1.6.0#::
The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.

[field]#identityProvider.name# [type]#[String]#::
The name of this OpenID Connect identity provider. This is only used for display purposes.

[field]#identityProvider.oauth2.authorization_endpoint# [type]#[String]#::
The top-level authorization endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the `issuer` field, which will be used to make a request to the OpenID Connect `.well-known` endpoint in order to dynamically resolve the authorization endpoint. If you provide an `issuer` then this field will be ignored.

[field]#identityProvider.oauth2.client_id# [type]#[String]#::
The top-level client id for your Application.

[field]#identityProvider.oauth2.client_secret# [type]#[String]#::
The top-level client secret to use with the OpenID Connect identity provider.

[field]#identityProvider.oauth2.clientAuthenticationMethod# [type]#[String]# [since]#Available since 1.15.3#::
The client authentication method to use with the OpenID Connect identity provider.  Possible values are:
+
* `client_secret_basic`
* `client_secret_post`
* `none`

[field]#identityProvider.oauth2.emailClaim# [type]#[String]# [since]#Available since 1.17.3#::
An optional configuration to modify the expected name of the claim returned by the IdP that contains the email address.

[field]#identityProvider.oauth2.issuer# [type]#[String]#::
The top-level issuer URI for the OpenID Connect identity provider. If this is provided, the authorization endpoint, token endpoint and userinfo endpoint will all be resolved using the `issuer` URI plus `/.well-known/openid-configuration`.

[field]#identityProvider.oauth2.scope# [type]#[String]#::
The top-level scope that you are requesting from the OpenID Connect identity provider.

[field]#identityProvider.oauth2.token_endpoint# [type]#[String]#::
The top-level token endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the `issuer` field, which will be used to make a request to the OpenID Connect `.well-known` endpoint in order to dynamically resolve the token endpoint. If you provide an `issuer` then this field will be ignored.

[field]#identityProvider.oauth2.userinfo_endpoint# [type]#[String]#::
The top-level userinfo endpoint for the OpenID Connect identity provider. You can leave this blank if you provide the `issuer` field, which will be used to make a request to the OpenID Connect `.well-known` endpoint in order to dynamically resolve the userinfo endpoint. If you provide an `issuer` then this field will be ignored.

[field]#identityProvider.type# [type]#[String]#::
The type of this provider, this field will always be set to `OpenIDConnect`.

[source,json]
.Example OpenID Connect Response JSON
----
include::../../../../src/json/identity-providers/openid-connect-response.json[]
----
