==== Response Body

[api]
[field]#identityProviderTenantConfiguration.limitUserLinkCount.enabled# [type]#[Boolean]#::
The tenant configuration for identity provider linking. If enabled the [field]#maximumLinks# value will be enforced during linking. This will only be present if you have configured a tenant policy for this identity provider.

[field]#identityProviderTenantConfiguration.limitUserLinkCount.maximumLinks# [type]#[Integer]#::
The maximum number of links a user can have to a single identity provider. This will only be present if you have configured a tenant policy for this identity provider.

[field]#linkCount# [type]#[Long]#::
The user's current link count. This will only be present if a [field]#userId# was provided on the request.

[field]#pendingIdPLink.displayName# [type]#[String]#::
A optional human readable name for this link such as an email address, username or given name. This value should be used to make it easier to identify the user this link represents in the remote identity provider.

[field]#pendingIdPLink.email# [type]#[String]#::
The optional email address provided by the identity provider. This value will not always be present, it will depend upon the identity provider.

[field]#pendingIdPLink.identityProviderId# [type]#[UUID]#::
The unique Id of the identity provider.

[field]#pendingIdPLink.identityProviderName# [type]#[UUID]#::
The name of the identity provider.

[field]#pendingIdPLink.identityProviderType# [type]#[UUID]#::
The type of the identity provider.

[field]#pendingIdPLink.identityProviderUserId# [type]#[String]#::
The unique user Id in the 3rd party identity provider. Ideally this value never changes and will always uniquely identify the user in the 3rd party identity provider.

[field]#pendingIdPLink.username# [type]#[String]#::
The optional username provided by the identity provider. This value will not always be present, it will depend upon the identity provider.

[source,json]
.Example Response JSON
----
include::../../../../src/json/identity-providers/links/pending-response.json[]
----

