==== Request Body

// SAMLv2 idp initiated has a subset of the attributes of the normal SAML IdP so just omitting the extra attributes for that idp.
// do the check on every attribute for clarity

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]# [optional]#Optional#::
The configuration for each Application that the identity provider is enabled for.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonImageURL# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#buttonImageURL#.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#buttonText#.
endif::[]

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `true`#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.buttonImageURL# [type]#[String]# [optional]#Optional#::
The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.buttonText# [type]#[String]# [required]#Required#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`# [since]#Available since 1.7.3#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
+
This is useful for debugging purposes, but is not intended to be left on during production. It should be enabled during integration or if you are experiencing an issue with this identity provider.
endif::[]
ifdef::samlv2_idp_initiated[]
[field]#identityProvider.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
+
This is useful for debugging purposes, but is not intended to be left on during production. It should be enabled during integration or if you are experiencing an issue with this identity provider.
// no 'since' needed
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.domains# [type]#[Array<String>]# [optional]#Optional#::
This is an optional list of domains that this SAML v2 provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an identity provider should be used. If an identity provider should be used, the browser is redirected to the login URL of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
endif::[]

[field]#identityProvider.emailClaim# [type]#[String]# [optional]#Optional#::
The name of the email claim (Attribute in the `Assertion` element) in the SAML response that FusionAuth uses to uniquely identity the user. If this is not set, the `useNameIdForEmail` flag must be true.

[field]#identityProvider.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.idpEndpoint# [type]#[String]# [optional]#Optional#::
The SAML v2 login page of the identity provider.
endif::[]

ifdef::samlv2_idp_initiated[]
[field]#identityProvider.issuer# [type]#[String]# [required]#Required#::
The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. This must be a URL.
endif::[]

[field]#identityProvider.keyId# [type]#[UUID]# [required]#Required#::
The id of the key stored in Key Master that is used to verify the SAML response sent back to FusionAuth from the identity provider. This key must be a verification only key or certificate (meaning that it only has a public key component).

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]# [optional]#Optional#::
The id of a SAML reconcile lambda that is applied when the identity provider sends back a successful SAML response.
+
The specified Lambda Id must be of type `SAMLv2Reconcile`.

[field]#identityProvider.name# [type]#[String]# [required]#Required#::
The name of this SAML v2 identity provider. This is only used for display purposes.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.postRequest# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.20.0#::
When `true` the authentication request will use the HTTP POST binding with the identity provider instead of the default Redirect binding which uses the HTTP GET method.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.requestSigningKeyId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.20.0#::
The key pair Id to use to sign the SAML request. 
+
Required when [field]#identityProvider.signRequest# is `true`.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.signRequest# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.20.0#::
When `true` authentication requests sent to the identity provider will be signed.
endif::[]
ifndef::samlv2_idp_initiated[]
[field]#identityProvider.type# [type]#[String]# [required]#Required#::
This field must be set to `SAMLv2`.
endif::[]
ifdef::samlv2_idp_initiated[]
[field]#identityProvider.type# [type]#[String]# [required]#Required#::
This field must be set to `SAMLv2IdPInitiated`.
endif::[]

[field]#identityProvider.useNameIdForEmail# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`#::
Whether or not FusionAuth will use the `NameID` element value as the email address of the user for reconciliation processing. If this is false, then the `emailClaim` property must be set.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.xmlSignatureC14nMethod# [type]#[String]# [optional]#Optional# [default]#Defaults to `exclusive`# [since]#Available since 1.20.0#::
The XML signature canonicalization method used when digesting and signing the SAML request. 
+
Required when [field]#identityProvider.signRequest# and [field]#identityProvider.postRequest# are `true`.
+
include::../../shared/_xmlSignatureC14nMethod-values.adoc[]
endif::[]

ifndef::samlv2_idp_initiated[]
[source,json]
.Example SAML v2 Request JSON
----
include::../../../../src/json/identity-providers/samlv2-request.json[]
----
endif::[]

ifdef::samlv2_idp_initiated[]
[source,json]
.Example SAML v2 IdP Initiated Request JSON
----
include::../../../../src/json/identity-providers/samlv2-idp-initiated-request.json[]
----
endif::[]
