==== Request Body
:optional_tag: pass:normal[[optional]#Optional#]
ifndef::samlv2_idp_initiated[]
:display_since_173:
endif::[]

// SAMLv2 idp initiated has a subset of the attributes of the normal SAML IdP so just omitting the extra attributes for that idp.
// do the check on every attribute for clarity

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]# [optional]#Optional#::
The configuration for each Application that the identity provider is enabled for.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonImageURL# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#buttonImageURL#.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#buttonText#.
endif::[]

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `true`#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.assertionConfiguration.destination.alternates# [type]#[Array]# [optional]#Optional# [since]#Available since 1.43.0#::
The array of URLs that FusionAuth will accept as SAML login destinations if the [field]#identityProvider.assertionConfiguration.destination.policy# setting is `AllowAlternates`.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.assertionConfiguration.destination.policy# [type]#[String]# [optional]#Optional# [default]#defaults to `Enabled`# [since]#Available since 1.43.0#::
The policy to use when performing a destination assertion on the SAML login request.
+
The possible values are:
+
* `Enabled` - Verifies the Destination attribute in the SAML response is equal to the expected Destination which is the FusionAuth ACS (Assertion Consumer Service) URL. This is the default and the recommended setting.
* `Disabled` - Do not validate the Destination attribute. This is not recommended, please use with caution.
* `AllowAlternates` - Verifies the Destination attribute is either the expected FusionAuth ACS, or one of the configured alternate values. This option is intended to assist with migrations from third-party IdPs and should be used with caution.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.buttonImageURL# [type]#[String]# [optional]#Optional#::
The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.buttonText# [type]#[String]# [required]#Required#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.
endif::[]

include::_identity-provider-debug-request-parameter.adoc[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.domains# [type]#[Array<String>]# [optional]#Optional#::
This is an optional list of domains that this SAML v2 provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an identity provider should be used. If an identity provider should be used, the browser is redirected to the login URL of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
endif::[]

[field]#identityProvider.emailClaim# [type]#[String]# [optional]#Optional#::
The name of the email claim (attribute in the `Assertion` element) in the SAML response that FusionAuth uses to uniquely identity the user.
+
Required when [field]#identityProvider.useNameIdForEmail# is `false`.

[field]#identityProvider.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.idpEndpoint# [type]#[String]# [required]#Required#::
The SAML v2 login page of the identity provider. Must be a valid URL.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.idpInitiatedConfiguration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`# [since]#Available since 1.43.0#::
Determines if FusionAuth will accept IdP initiated login requests from this SAMLv2 Identity Provider. A valid license is required to use this feature.
+
include::../../shared/_saml-idp-init-warning.adoc[]
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.idpInitiatedConfiguration.issuer# [type]#[String]# [optional]#Optional# [since]#Available since 1.43.0#::
The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you.
+
Required when [field]#identityProvider.idpInitiatedConfiguration.enabled# is `true`.
endif::[]

ifdef::samlv2_idp_initiated[]
[field]#identityProvider.issuer# [type]#[String]# [required]#Required#::
The EntityId (unique identifier) of the SAML v2 identity provider. This value should be provided to you. Prior to 1.27.1 this value was required to be a URL.
endif::[]

[field]#identityProvider.keyId# [type]#[UUID]# [required]#Required#::
The id of the key stored in Key Master that is used to verify the SAML response sent back to FusionAuth from the identity provider. This key must be a verification only key or certificate (meaning that it only has a public key component).

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]# [optional]#Optional#::
The id of a SAML reconcile lambda that is applied when the identity provider sends back a successful SAML response.
+
The specified Lambda Id must be of type `SAMLv2Reconcile`.

include::_identity-provider-linking-strategy-request-parameter.adoc[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.loginHintConfiguration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `true`# [since]#Available since 1.43.0#::
When enabled and HTTP-Redirect bindings are used, FusionAuth will provide the username or email address when available to the IdP as a login hint using the configured parameter name set by the [field]#identityProvider.loginHintConfiguration.parameterName# to initiate the AuthN request.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.loginHintConfiguration.parameterName# [type]#[String]# [optional]#Optional# [default]#defaults to `login_hint`# [since]#Available since 1.43.0#::
The name of the parameter used to pass the username or email as login hint to the IDP when enabled, and HTTP redirect bindings are used to initiate the AuthN request.
+
Required when [field]#identityProvider.loginHintConfiguration.enabled# is `true`.
endif::[]

[field]#identityProvider.name# [type]#[String]# [required]#Required#::
The name of this SAML v2 identity provider. This is only used for display purposes. Must be unique across all identity providers.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.nameIdFormat# [type]#[String]# [required]#Required# [default]#Defaults to **[see description]**#::
The Name Id is used to facilitate communication about a user between a Service Provider (SP) and Identity Provider (IdP). The SP can specify the preferred format in the AuthN request regarding a user. The identity Provider will attempt to honor this format in the AuthN response.
When this parameter is omitted a default value of `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` will be used.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.postRequest# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.20.0#::
When `true` the authentication request will use the HTTP POST binding with the identity provider instead of the default Redirect binding which uses the HTTP GET method.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.requestSigningKeyId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.20.0#::
The key pair Id to use to sign the SAML request.
+
Required when [field]#identityProvider.signRequest# is `true`.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.signRequest# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.20.0#::
When `true` authentication requests sent to the identity provider will be signed.
endif::[]

include::_identity-provider-tenant-configuration.adoc[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.type# [type]#[String]# [required]#Required#::
This field must be set to `SAMLv2`.
endif::[]
ifdef::samlv2_idp_initiated[]
[field]#identityProvider.type# [type]#[String]# [required]#Required#::
This field must be set to `SAMLv2IdPInitiated`.
endif::[]

[field]#identityProvider.uniqueIdClaim# [type]#[String]# [optional]#Optional#::
The name of the unique claim in the SAML response that FusionAuth uses to uniquely link the user. If this is not set, the `emailClaim` will be used when linking user.

[field]#identityProvider.useNameIdForEmail# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`#::
Whether or not FusionAuth will use the `NameID` element value as the email address of the user for reconciliation processing. If this is set to `false`, then the `emailClaim` property must be set.

[field]#identityProvider.usernameClaim# [type]#[String]# [optional]#Optional#::
The name of the claim in the SAML response that FusionAuth uses to identity the username. If this is not set, the `NameId` value will be used to link a user. This property is required when [field]#identityProvider.linkingStrategy# is set to `LinkByUsername` or `LinkByUsernameForExistingUser`


ifndef::samlv2_idp_initiated[]
[field]#identityProvider.xmlSignatureC14nMethod# [type]#[String]# [optional]#Optional# [default]#Defaults to `exclusive`# [since]#Available since 1.20.0#::
The XML signature canonicalization method used when digesting and signing the SAML request.
+
Required when [field]#identityProvider.signRequest# and [field]#identityProvider.postRequest# are `true`.
+
include::../../shared/_xmlSignatureC14nMethod-values.adoc[]
endif::[]

ifndef::samlv2_idp_initiated[]
[source,json]
.Example SAML v2 Request JSON
----
include::../../../../src/json/identity-providers/samlv2-request.json[]
----
endif::[]

ifdef::samlv2_idp_initiated[]
[source,json]
.Example SAML v2 IdP Initiated Request JSON
----
include::../../../../src/json/identity-providers/samlv2-idp-initiated-request.json[]
----
endif::[]

:display_since_173!:
