==== Response Body

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonImageURL# [type]#[String]#::
This is an optional Application specific override for the top level button image URL.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]#::
This is an optional Application specific override for the top level button text.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.buttonImageURL# [type]#[String]#::
The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.buttonText# [type]#[String]#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.debug# [type]#[Boolean]# [since]#Available since 1.7.3#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.

[field]#identityProvider.domains# [type]#[Array<String>]#::
This is an optional list of domains that this SAML v2 provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an identity provider should be used. If an identity provider should be used, the browser is redirected to the login URL of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.

[field]#identityProvider.emailClaim# [type]#[String]#::
The name of the email claim (Attribute in the `Assertion` element) in the SAML response that FusionAuth uses to uniquely identity the user. If this is not set, the `useNameIdForEmail` flag must be true.

[field]#identityProvider.enabled# [type]#[Boolean]#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.id# [type]#[UUID]#::
The Id of the provider.

[field]#identityProvider.idpEndpoint# [type]#[String]#::
The SAML v2 login page of the identity provider.

[field]#identityProvider.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was added to the FusionAuth database.

[field]#identityProvider.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was updated in the FusionAuth database.

[field]#identityProvider.keyId# [type]#[UUID]#::
The id of the key stored in KeyMaster that is used to verify the SAML response sent back to FusionAuth from the identity provider. This key must be a verification only key or certificate (meaning that it only has a public key component).

[field]#identityProvider.lambdaConfiguration.reconcileId#::
The id of a SAML reconcile lambda that is applied when the identity provider sends back a successful SAML response.

[field]#identityProvider.name# [type]#[String]#::
The name of this SAML v2 identity provider. This is only used for display purposes.

[field]#identityProvider.useNameIdForEmail# [type]#[Boolean]#::
Whether or not FusionAuth will use the `NameID` element value as the email address of the user for reconciliation processing. If this is false, then the `emailClaim` property must be set.

[field]#identityProvider.type# [type]#[String]#::
The type of this provider, this field will always be set to `SAMLv2`.

[source,json]
.Example SAML v2 Response JSON
----
include::../../../../src/json/identity-providers/samlv2-response.json[]
----
