==== Response Body

// SAMLv2 idp initiated has a subset of the attributes of the normal SAML IdP so just omitting the extra attributes for that idp.
// do the check on every attribute for clarity

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]#::
The configuration for each Application that the identity provider is enabled for.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonImageURL# [type]#[String]#::
This is an optional Application specific override for the top level button image URL.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]#::
This is an optional Application specific override for the top level button text.
endif::[]

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.buttonImageURL# [type]#[String]#::
The top-level button image (URL) to use on the FusionAuth login page for this Identity Provider.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.buttonText# [type]#[String]#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.debug# [type]#[Boolean]# [since]#Available since 1.7.3#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
endif::[]

ifdef::samlv2_idp_initiated[]
[field]#identityProvider.debug# [type]#[Boolean]#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created. 
// no 'since' needed
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.domains# [type]#[Array<String>]#::
This is an optional list of domains that this SAML v2 provider should be used for. This converts the FusionAuth login form to a domain-based login form. This type of form first asks the user for their email. FusionAuth then uses their email to determine if an identity provider should be used. If an identity provider should be used, the browser is redirected to the login URL of that identity provider. Otherwise, the password field is revealed on the form so that the user can login using FusionAuth.
endif::[]

[field]#identityProvider.emailClaim# [type]#[String]#::
The name of the email claim (Attribute in the `Assertion` element) in the SAML response that FusionAuth uses to uniquely identity the user. If this is not set, the `useNameIdForEmail` flag must be true.

[field]#identityProvider.enabled# [type]#[Boolean]#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.id# [type]#[UUID]#::
The Id of the provider.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.idpEndpoint# [type]#[String]#::
The SAML v2 login page of the identity provider.
endif::[]

[field]#identityProvider.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was added to the FusionAuth database.

[field]#identityProvider.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the provider was updated in the FusionAuth database.

[field]#identityProvider.keyId# [type]#[UUID]#::
The id of the key stored in KeyMaster that is used to verify the SAML response sent back to FusionAuth from the identity provider. This key must be a verification only key or certificate (meaning that it only has a public key component).

[field]#identityProvider.lambdaConfiguration.reconcileId#::
The id of a SAML reconcile lambda that is applied when the identity provider sends back a successful SAML response.

[field]#identityProvider.name# [type]#[String]#::
The name of this SAML v2 identity provider. This is only used for display purposes.

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.postRequest# [type]#[Boolean]# [since]#Available since 1.20.0#::
When `true` the authentication request will use the HTTP POST binding with the identity provider instead of the default Redirect binding which uses the HTTP GET method.
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.requestSigningKeyId# [type]#[UUID]# [since]#Available since 1.20.0#::
The key pair Id to use to sign the SAML request. 
endif::[]

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.signRequest# [type]#[Boolean]# [since]#Available since 1.20.0#::
When `true` authentication requests sent to the identity provider will be signed.
endif::[]
ifndef::samlv2_idp_initiated[]
[field]#identityProvider.type# [type]#[String]#::
This field will be `SAMLv2`.
endif::[]
ifdef::samlv2_idp_initiated[]
[field]#identityProvider.type# [type]#[String]#::
This field will be `SAMLv2IdPInitiated`.
endif::[]

[field]#identityProvider.useNameIdForEmail# [type]#[Boolean]#::
Whether or not FusionAuth will use the `NameID` element value as the email address of the user for reconciliation processing. 

ifndef::samlv2_idp_initiated[]
[field]#identityProvider.xmlSignatureC14nMethod# [type]#[String]# [since]#Available since 1.20.0#::
The XML signature canonicalization method used when digesting and signing the SAML request. 
+
include::../../shared/_xmlSignatureC14nMethod-values.adoc[]
endif::[]

ifndef::samlv2_idp_initiated[]
[source,json]
.Example SAML v2 Response JSON
----
include::../../../../src/json/identity-providers/samlv2-response.json[]
----
endif::[]

ifdef::samlv2_idp_initiated[]
[source,json]
.Example SAML v2 IdP Initiated Response JSON
----
include::../../../../src/json/identity-providers/samlv2-idp-initiated-request.json[]
----
endif::[]
