FusionAuth will also store the {idp_display_name} {token_name} returned from the {return_text} in the `identityProviderLink` object, in the [field]#identityProviderLink.token# field. This object is accessible using the link:/docs/v1/tech/apis/identity-providers/links[Link API].

The `identityProviderLink` object stores the token so that you can use it in your application to call {idp_display_name} APIs on behalf of the user if desired.

ifeval::["{idp_long_lived_token_type}" == "refresh"]
Calling {idp_display_name} APIs first requires a refresh grant to get a new access token. 

ifdef::idp_refresh_additional_info_url[]
{idp_refresh_additional_info_url}[More about the refresh grant,window=_blank].
endif::[]

endif::[]

ifeval::["{idp_display_name}" == "Google"]
The Google Identity Provider stores the `id_token`. If you need the refresh token, use an link:/docs/v1/tech/apis/identity-providers/openid-connect[OpenID Connect Identity Provider].
endif::[]

ifndef::hide_token_map_deprecation[]
[NOTE.note]
====
Prior to version `1.28.0`, the token was stored in the `UserRegistration` object, in the `tokens` Map.
====
endif::[]
 
