FusionAuth will also store the {idp_display_name} {token_name} returned from the {return_text} in the `identityProviderLink` object, in the [field]#identityProviderLink.token# field. This object is accessible using the link:/docs/v1/tech/apis/identity-providers/links[Link API].

The `identityProviderLink` object stores the token so that you can use it in your application to call {idp_display_name} APIs on behalf of the user if desired.

ifeval::["{idp_long_lived_token_type}" == "refresh"]
Calling {idp_display_name} APIs first requires a refresh grant to get a new access token. 

ifdef::idp_refresh_additional_info_url[]
{idp_refresh_additional_info_url}[More about the refresh grant,window=_blank].
endif::[]

endif::[]

ifeval::["{idp_display_name}" == "Google"]
f you need the refresh token to obtain new access tokens, the typed Google IdP will not meet your needs, since it stores the `id_token` on the Link. However, Google supports OIDC, which in turn allows for refresh tokens. Therefore, please use an link:/docs/v1/tech/apis/identity-providers/openid-connect[OpenID Connect Identity Provider].
endif::[]

ifeval::["{idp_display_name}" == "Facebook"]
The Facebook Identity Provider stores a long-lived token. https://developers.facebook.com/docs/facebook-login/guides/access-tokens/get-long-lived/[More about this token,window=_blank].
endif::[]

ifndef::hide_token_map_deprecation[]
[NOTE.note]
====
Prior to version `1.28.0`, the token was stored in the `UserRegistration` object, in the `tokens` Map.
====
endif::[]
 
