==== Response Body

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]#::
This is an optional Application specific override for the top level [field]#buttonText#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.consumerKey# [type]#[String]#::
This is an optional Application specific override for the top level [field]#consumerKey#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.consumerSecret# [type]#[String]#::
This is an optional Application specific override for the top level [field]#consumerSecret#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.buttonText# [type]#[String]#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.consumerKey# [type]#[String]#::
The top-level consumer key to use with the Twitter Identity Provider. This value is retrieved from the Twitter developer website when you setup your Twitter developer account.

[field]#identityProvider.consumerSecret# [type]#[String]#::
The top-level consumer secret to use with the Twitter Identity Provider. This value is retrieved from the Twitter developer website when you setup your Twitter developer account.

[field]#identityProvider.debug# [type]#[Boolean]# [since]#Available since 1.7.3#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.

[field]#identityProvider.enabled# [type]#[Boolean]#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.id# [type]#[UUID]#::
The Id of the Twitter identity provider, which will always be `45bb233c-0901-4236-b5ca-ac46e2e0a5a5`.

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]# [since]#Available since 1.17.0#::
The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.

[field]#identityProvider.name# [type]#[String]#::
The name of the provider, this field will always be set to `Twitter`.

[field]#identityProvider.type# [type]#[String]#::
The type of this provider, this field will always be set to `Twitter`.

[source,json]
.Example Twitter Response JSON
----
include::../../../../src/json/identity-providers/twitter-response.json[]
----
