==== Request Body

[.api]
[field]#identityProvider.applicationConfiguration# [type]#[Map<UUID, Object>]# [optional]#Optional#::
The configuration for each Application that the identity provider is enabled for.

[field]#identityProvider.applicationConfiguration``[applicationId]``.buttonText# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#buttonText#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.consumerKey# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#consumerKey#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.consumerSecret# [type]#[String]# [optional]#Optional#::
This is an optional Application specific override for the top level [field]#consumerSecret#.

[field]#identityProvider.applicationConfiguration``[applicationId]``.createRegistration# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `true`#::
Determines if a UserRegistration is created for the User automatically or not. If a user doesn't exist in FusionAuth and logs in through an identity provider, this boolean controls whether or not FusionAuth creates a registration for the User in the Application they are logging into.

[field]#identityProvider.applicationConfiguration``[applicationId]``.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this identity provider is enabled for the Application specified by the `applicationId` key.

[field]#identityProvider.buttonText# [type]#[String]# [required]#Required#::
The top-level button text to use on the FusionAuth login page for this Identity Provider.

[field]#identityProvider.consumerKey# [type]#[String]# [required]#Required#::
The top-level consumer key to use with the Twitter Identity Provider. This value is retrieved from the Twitter developer website when you setup your Twitter developer account.

[field]#identityProvider.consumerSecret# [type]#[String]# [required]#Required#::
The top-level consumer secret to use with the Twitter Identity Provider. This value is retrieved from the Twitter developer website when you setup your Twitter developer account.

[field]#identityProvider.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`# [since]#Available since 1.7.3#::
Determines if debug is enabled for this provider. When enabled, each time this provider is invoked to reconcile a login an Event Log will be created.
+
This is useful for debugging purposes, but is not intended to be left on during production. It should be enabled during integration or if you are experiencing an issue with this identity provider.

[field]#identityProvider.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if this provider is enabled. If it is false then it will be disabled globally.

[field]#identityProvider.lambdaConfiguration.reconcileId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.17.0#::
The unique Id of the lambda to used during the user reconcile process to map custom claims from the external identity provider to the FusionAuth user.
+
The specified Lambda Id must be of type `TwitterReconcile`

[field]#identityProvider.type# [type]#[String]# [required]#Required#::
This field must be set to `Twitter`.

[source,json]
.Example Twitter Request JSON
----
include::../../../../src/json/identity-providers/twitter-request.json[]
----
