---
layout: doc
title: Apple Identity Provider APIs
description: APIs for creating, retrieving, updating and disabling the Apple identity provider
---

== Overview

[NOTE.since]
====
This API has been available since 1.17.0
====

The Apple identity provider type will use the Sign in with Apple APIs and will provide a `Sign with Apple` button on FusionAuth's login page that will either redirect to an Apple sign in page or leverage native controls when using Safari on macOS or iOS. Additionally, this identity provider will call Apples's `/auth/token` API to load additional details about the user and store them in FusionAuth.

FusionAuth will also store the Apple `refresh_token` that is returned from the `/auth/token` endpoint in the `UserRegistration` object inside the `tokens` Map. This Map stores the tokens from the various identity providers so that you can use them in your application to call their APIs.

=== Operations

* <<Create the Apple Identity Provider>>
* <<Retrieve the Apple Identity Provider>>
* <<Update the Apple Identity Provider>>
* <<Delete the Apple Identity Provider>>
* <<Complete the Apple Login>>

== Create the Apple Identity Provider

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Create the Google Identity Provider
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider#
--

The [field]#type# in the request JSON is used to determine that you are managing the Apple identity provider.

include::docs/v1/tech/apis/identity-providers/_apple-request-body.adoc[]

=== Response

:never_search_error:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_apple-response-body.adoc[]

== Retrieve the Apple Identity Provider

There is only one Google Identity Provider, so this Identity Provider may be retrieved by type or Id.

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Retrieve the Google Identity Provider by type
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider``?type=Apple``#
--

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Retrieve the Apple Identity Provider by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/`13d2a5db-7ef9-4d62-b909-0df58612e775`#
--

=== Response

:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_apple-response-body.adoc[]

== Update the Apple Identity Provider

There is only one Apple Identity Provider, so this Identity Provider may be updated by type or Id.

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Update the Apple Identity Provider by type
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/identity-provider``?type=Apple``#
--

:api_endpoint: pass:normal[/api/identity-provider``?type=Apple``]
include::docs/v1/tech/apis/_patch-support.adoc[]

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Update the Apple Identity Provider by Id
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/identity-provider/`13d2a5db-7ef9-4d62-b909-0df58612e775`#
--

:api_endpoint: pass:normal[/api/identity-provider/`13d2a5db-7ef9-4d62-b909-0df58612e775`]
include::docs/v1/tech/apis/_patch-support.adoc[]

include::docs/v1/tech/apis/identity-providers/_apple-request-body.adoc[]


=== Response

The response for this API contains the Apple Identity Provider.

:never_search_error:
include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_apple-response-body.adoc[]

== Delete the Apple Identity Provider

There is only one Apple Identity Provider, so this Identity Provider may be deleted by type or Id.

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Delete the Apple Identity Provider by type
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/identity-provider``?type=Apple``#
--

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Delete the Apple Identity Provider by Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/identity-provider/`13d2a5db-7ef9-4d62-b909-0df58612e775`#
--

=== Response

This API does not return a JSON response body.

:never_search_error:
include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]
:never_search_error!:

== Complete the Apple Login

This API allows you to complete a Apple login after authenticating a user using the Apple API. If you are using the FusionAuth login UI with the Apple button you will not utilize this API directly.

This API is intended to be used if you want to build your own login page and you have added the Apple login button to your own login page and you then need to complete the login with FusionAuth.

For example, if you built your own login page, you could add a Login with Apple button and complete the Apple authentication. When you complete the Apple authentication you will have been returned an id token from Apple. Using this API you can pass that id token returned from Apple to FusionAuth and we will complete the login workflow and reconcile the user to FusionAuth.

The user does not need to exist yet in FusionAuth to utilize this API. The token returned from Apple will be used to retrieve the user's email address, if that user does not yet exist in FusionAuth the user will be created. If create registration has been enabled for this identity provider and the user does not yet have a registration for this application, a registration will be automatically created for the user. The user will be assigned any default roles configured for the application. If create registration has not been enabled, a registration will not be created if one does not yet exist. This last scenario is useful if you wish to manually provision users and then subsequently allow them to login with Apple.

=== Request

[.api-authentication]
link:../authentication#no-authentication-required[icon:unlock[role=green,type=fas]] Complete Apple Login
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/login#
--

==== Request Headers

[.api]
[field]#X-Forwarded-For# [type]#[String]# [optional]#Optional#::
The IP address of a client requesting authentication. If the IP address is provided it will be stored for login history of the user. It is generally preferred to specify the IP address in the request body. If it is not provided in the request body this header value will be used if available, the request body value will take precedence.
include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation-row-only.adoc[]

:loginProvider: Apple
include::docs/v1/tech/apis/identity-providers/_identity-provider-login-request-body.adoc[]
:loginProvider!:

=== Response

The response for this API contains the User object.

:loginProvider: Apple
include::docs/v1/tech/apis/identity-providers/_identity-provider-login-response-body.adoc[]
:loginProvider!:
