---
layout: doc
title: Epic Games Identity Provider APIs
description: APIs for creating, retrieving, updating and disabling the Epic Games identity provider
---

== Overview

[NOTE.since]
====
This API has been available since 1.28.0
====

The Epic Games identity provider type will use the Epic Games OAuth login API. It will also provide a `Login with Epic Games` button on FusionAuth’s login page that will direct a user to the Epic Games login page.

This identity provider will call Epic Games's API to load the Epic Games user's `displayName` and use that as `username` to lookup or create a user in FusionAuth depending on the linking strategy configured for this identity provider.  However, Epic Games does not allow access to user emails, so neither email linking strategy can be used and user’s will not be able to login or be created.

FusionAuth will also store the Epic Games `refresh_token` that is returned from the Epic Games login in the link between the user and the identity provider. This token can be used by an application to make further requests to Epic Games APIs on behalf of the user.

:idp_display_name: Epic Games
:idp_id: 1b932b19-61a8-47c7-9e81-27dbf9011dad
:idp_linking_strategy: CreatePendingLink
:idp_lowercase: epicgames
:idp_token_or_code: code
:idp_type: EpicGames
include::docs/v1/tech/apis/identity-providers/_oauth-idp-operations.adoc[]
:idp_display_name!:
:idp_id!:
:idp_linking_strategy!:
:idp_lowercase!:
:idp_token_or_code!:
:idp_type!:
