---
layout: doc
title: Google Identity Provider APIs
description: APIs for creating, retrieving, updating and disabling the Google identity provider
---

== Overview

[NOTE.since]
====
This API has been available since 1.1.0
====

The Google identity provider type will use the Google OAuth v2.0 login API. It will also provide a `Login with Google` button on FusionAuth’s login page that will direct a user to the Google login page.

This identity provider will call Google’s API to load the user's `email` and `preferred_username` and use those as `email` and `username` to lookup or create a user in FusionAuth depending on the linking strategy configured for this identity provider. Additional claims returned by Google can be used to reconcile the user to FusionAuth by using a Google Reconcile Lambda.

FusionAuth will also store the Google `refresh_token` returned from the Google API in the link between the user and the identity provider. This token can be used by an application to make further requests to Google APIs on behalf of the user.

:idp_display_name: Google
:idp_id: 82339786-3dff-42a6-aac6-1f1ceecb6c46
:idp_login_method:
:idp_lowercase: google
:idp_since: 10100
:idp_token_or_code: token or code
:idp_type: Google
include::docs/v1/tech/apis/identity-providers/_oauth-idp-operations.adoc[]
:idp_display_name!:
:idp_id!:
:idp_login_method!:
:idp_lowercase!:
:idp_since!:
:idp_token_or_code!:
:idp_type!: