---
layout: doc
title: Identity Provider API Overview
description: APIs for creating, retrieving, updating and deleting identity providers
---

== Overview

An Identity Provider is a named object that provides configuration to describe an external and/or social identity provider. This configuration will be used to perform an alternative login to the standard FusionAuth local login. FusionAuth currently supports a number of different identity provider types:

* link:/docs/v1/tech/apis/identity-providers/apple[Apple]
* link:/docs/v1/tech/apis/identity-providers/epicgames[Epic Games] - requires a paid edition.
* link:/docs/v1/tech/apis/identity-providers/external-jwt[External JWT]
* link:/docs/v1/tech/apis/identity-providers/facebook[Facebook]
* link:/docs/v1/tech/apis/identity-providers/google[Google]
* link:/docs/v1/tech/apis/identity-providers/hypr[HYPR]
* link:/docs/v1/tech/apis/identity-providers/linkedin[LinkedIn]
* link:/docs/v1/tech/apis/identity-providers/nintendo[Nintendo] - requires a paid edition.
* link:/docs/v1/tech/apis/identity-providers/openid-connect[OpenID Connect]
* link:/docs/v1/tech/apis/identity-providers/samlv2[SAML v2]
* link:/docs/v1/tech/apis/identity-providers/samlv2-idp-initiated[SAML v2 IdP Initiated] - requires a paid edition.
* link:/docs/v1/tech/apis/identity-providers/sonypsn[Sony PlayStation Network] - requires a paid edition.
* link:/docs/v1/tech/apis/identity-providers/steam[Steam] - requires a paid edition.
* link:/docs/v1/tech/apis/identity-providers/twitch[Twitch] - requires a paid edition.
* link:/docs/v1/tech/apis/identity-providers/twitter[Twitter]
* link:/docs/v1/tech/apis/identity-providers/xbox[Xbox] - requires a paid edition.

The type of the identity provider will determine the object's properties as well as the validation that is performed. You can click into any of the identity provider API docs to get a list of that identity provider's properties.

To learn how to configure these Identity Providers using the FusionAuth UI, go here link:/docs/v1/tech/identity-providers/[Identity Providers].

=== Link APIs

The way a link is established between an identity provider and FusionAuth is determined by the `linkingStrategy` for each identity provider. An API is provided to manually link and unlink a user to a 3rd party identity provider. To learn more about managing links between FusionAuth and a 3rd party identity provider, see the link:/docs/v1/tech/apis/identity-providers/links[Link APIs].

=== Global Operations

* <<Retrieve all Identity Providers>>
* <<Search for Identity Providers>>
* <<Lookup an Identity Provider>>

== Retrieve all Identity Providers

=== Request

link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve all of the Identity Providers
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider#
--

=== Response

:never_missing:
:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_search_error!:
:never_missing!:

include::docs/v1/tech/apis/identity-providers/_multiple-response-body.adoc[]

== Search for Identity Providers

[NOTE.since]
====
This API has been available since 1.44.0
====

This API is used to search for Identity Providers and may be called using the `GET` or `POST` HTTP methods. Examples of each are provided below. The `POST` method is provided to allow for a richer request object without worrying about exceeding the maximum length of a URL. Calling this API with either the `GET` or `POST` HTTP method will provide the same search results given the same query parameters.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Search for Identity Providers by name
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/search``?name=\{name\}``#
--

=== Request Parameters

:parameter_prefix:
include::docs/v1/tech/apis/identity-providers/_identity-provider-search-request-parameters.adoc[]
:parameter_prefix!:


[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Search for Identity Providers
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/search#
--

When calling the API using a `POST` request you will send the search criteria in a JSON request body.

=== Request Body

:parameter_prefix: search.
include::docs/v1/tech/apis/identity-providers/_identity-provider-search-request-parameters.adoc[]
:parameter_prefix!:

=== Response

The response for this API contains the Identity Providers matching the search criteria in paginated format and the total number of results matching the search criteria.

:never_missing:
:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_missing!:
:never_search_error!:

:include_total:
include::docs/v1/tech/apis/identity-providers/_multiple-response-body.adoc[]
:include_total!:

== Lookup an Identity Provider

The Lookup API is intended to be used during an external login workflow.

For example, you might build your own login page. This page might collect the user's email as the first step. That email address can be sent to this API to determine which identity provider was designated as the provider for this email address. If the identity provider is an OpenID Connect provider, then you might redirect the user over to that provider.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Lookup an Identity Provider by domain/email
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/lookup``?domain={domain}``#
--

==== Request Parameters

[.api]
[field]#domain# [type]#[String]# [required]#Required#::
The email domain or the full email address of the user.
+
[quote]
For example, `jenny@acme.com` and `acme.com` are functionally equivalent.

=== Response

The Lookup response is a subset of the Identity Provider configuration that would be returned by the normal identity provider retrieve operation. A `200` response code indicates the domain is managed and the response will contain a JSON body, a `404` response code indicates it is not managed by a configured Identity Provider.

:never_search_error:
:no_authorization:
:missing_message: The requested domain is not being managed by a configured Identity Provider.
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:missing_message!:
:no_authorization!:
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_lookup-response-body.adoc[]
