---
layout: doc
title: Identity Provider API Overview
description: APIs for creating, retrieving, updating and deleting identity providers
---

== Overview

An Identity Provider is a named object that provides configuration to describe an external and/or social identity provider. This configuration will be used to perform an alternative login to the standard FusionAuth local login. FusionAuth currently supports a number of different identity provider types:

* link:facebook[Facebook]
* link:google[Google]
* link:twitter[Twitter]
* link:openid-connect[OpenID Connect]
* link:external-jwt[External JWT]

The type of the identity provider will determine the object's properties as well as the validation that is performed. You can click into any of the identity provider API docs to get a list of that identity provider's properties.

To learn how to configure these Identity Providers using the FusionAuth UI, go here link:../../identity-providers/[Identity Providers].

=== Global Operations

* <<Retrieve all Identity Providers>>
* <<Lookup an Identity Provider>>

== Retrieve all Identity Providers

=== Request

link:../authentication#api-key-authentication[icon:lock[role=red,type=far]] Retrieve all of the Identity Providers
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider#
--

=== Response

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_multiple-response-body.adoc[]

== Lookup an Identity Provider

The Lookup API is intended to be used during an external login workflow.

For example, you might build your own login page. This page might collect the user's email as the first step. That email address can be sent to this API to determine which identity provider was designated as the provider for this email address. If the identity provider is an OpenID Connect provider, then you might redirect the user over to that provider.

=== Request

[.api-authentication]
link:../authentication#no-authentication-required[icon:unlock-alt[role=green,type=far]] Lookup an Identity Provider by domain/email
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/lookup``?domain={domain}``#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#domain# [type]#[String]# [required]#Required#
|The email domain or the full email address of the user.

[block-quote]#For example, `jenny@acme.com` and `acme.com` are functionally equivalent.#
|===

=== Response

The Lookup response is a subset of the Identity Provider configuration that would be returned by the normal identity provider retrieve operation. A `200` response code indicates the domain is managed and the response will contain a JSON body, a `404` response code indicates it is not managed by a configured Identity Provider.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_lookup-response-body.adoc[]