---
layout: doc
title: Link APIs
description: The APIs for creating, retrieving, and deleting Identity Provider Links
---

== Overview

[NOTE.since]
====
This API has been available since 1.28.0
====

This page contains the APIs that are used to manage Links that establish a relationship between a FusionAuth User and an Identity Provider.

* <<Link a User>>
* <<Complete a pending Link>>
* <<Retrieve a Link>>
* <<Unlink a User>>

== Link a User

This API is used to create a link between a FusionAuth User and a user in a 3rd party identity provider. This API may be useful when you already know the unique Id of a user in a 3rd party identity provider and the corresponding FusionAuth User.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Link a User
[.endpoint]

[NOTE.since]
====
Available Since Version 1.43.0
====

[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/link#
--

==== Request Body

[.api]
[field]#identityProviderLink.displayName# [type]#[String]# [optional]#Optional#::
A optional human readable name for this link such as an email address, username or given name. This value should be used to make it easier to identify the user this link represents in the remote identity provider.
+
Please note, that this value will always be overwritten during login to reflect the most current information from the identity provider. In most cases this value will be an email address or username.

[field]#identityProviderLink.identityProviderId# [type]#[UUID]# [required]#Required#::
The Id of the identify provider that will be linked to the User.

[field]#identityProviderLink.identityProviderUserId# [type]#[String]# [required]#Required#::
The Id for the user that is provided by the upstream identity provider. This is the value that will allow FusionAuth to link this User on future logins. This value is expected to be immutable.

[field]#identityProviderLink.userId# [type]#[UUID]# [required]#Required#::
The unique Id of the FusionAuth User that is being linked to the identity provider.

[source,json]
.Example Request JSON
----
include::docs/src/json/identity-providers/links/request.json[]
----
=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Link a User

[WARNING]
====
Deprecated in version 1.43.0.

While this API is still functional, its usage is discouraged. When available please use the link:/docs/v1/tech/apis/identity-providers/links#link-a-user[Link a User endpoint].
====

[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/link#
--

==== Request Body

[.api]
[field]#displayName# [type]#[String]# [optional]#Optional# [since]#Available since 1.28.1#::
An optional human readable name for this link such as an email address, username or given name. This value should be used to make it easier to identify the user this link represents in the remote identity provider.
+
Please note, that this value will always be overwritten during login to reflect the most current information from the identity provider. In most cases this value will be an email address or username.

[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The Id of the identity provider.

[field]#identityProviderUserId# [type]#[String]# [required]#Required#::
The Id for the User that is provided by the identity provider. This is the value that will allow FusionAuth to link this user on future logins. This value is expected to be immutable.

[field]#userId# [type]#[UUID]# [required]#Required#::
The FusionAuth Id of the User that is being linked to the identity provider.

[source,json]
.Example Request JSON
----
include::docs/src/json/identity-providers/links/create-link-request-deprecated.json[]
----
=== Response

:never_search_error:
:webhook_event:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:webhook_event!:
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_links-post-response-body.adoc[]

== Complete a pending Link

This API is used complete a pending link. If an identity provider is configured with a linking strategy of `Create a pending link`, a `pendingLinkId` will be returned by the Identity Provider API (see the `Complete the Login` section for each respective IdP). This value can be used in the request below.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Complete a pending Link

[NOTE.since]
====
Available Since Version 1.43.0
====
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/link#
--

==== Request Body

[.api]
[field]#pendingIdPLinkId# [type]#[String]# [required]#Required#::
The pending identity provider link Id.

[field]#identityProviderLink.userId# [type]#[String]# [required]#Required#::
The unique Id of the FusionAuth User that is being linked to the identity provider.

[source,json]
.Example Request JSON
----
include::docs/src/json/identity-providers/links/pending-link-request-identityProviderLink-in-body.json[]
----

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Complete a pending Link

[WARNING]
====
Deprecated in version 1.43.0.

While this API is still functional, its usage is discouraged. When available please use the link:/docs/v1/tech/apis/identity-providers/links#complete-a-pending-link[Complete a Pending Link].
====

[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/link#
--

==== Request Body

[.api]
[field]#pendingIdPLinkId# [type]#[String]# [required]#Required#::
The pending identity provider link Id.

[field]#userId# [type]#[String]# [required]#Required#::
The Id of the User that is being linked to the identity provider.

[source,json]
.Example Request JSON
----
include::docs/src/json/identity-providers/links/request-deprecated.json[]
----

=== Response

:never_search_error:
:webhook_event:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:webhook_event!:
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_links-post-response-body.adoc[]

== Retrieve a Link

This API is used to retrieve a single Link, all Links for a specific identity provider and user, or all Links for a user.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve a single link
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/link``?identityProviderId=\{identityProviderId\}&identityProviderUserId=\{identityProviderUserId\}&userId=\{userId\}``#
--

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the identity provider.

[field]#identityProviderUserId# [type]#[String]# [required]#Required#::
The unique user Id in the 3rd party identity provider. Ideally this value never change and will always uniquely identify the user in the 3rd party identity provider.

[field]#userId# [type]#[UUID]# [optional]#Optional#::
The FusionAuth user Id that is linked to the identity provider. When this value is provided, a `404` status code will be returned if the link does not exist, or the link exists but is linked to a different `userId`. If you wish to identify if any user is linked, omit this parameter.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve all links for a specific user by identity provider
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/link``?identityProviderId=\{identityProviderId\}&userId=\{userId\}``#
--

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the identity provider.

[field]#userId# [type]#[UUID]# [required]#Required#::
The FusionAuth user Id that is linked to the identity provider.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve all links for a user
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/link``?userId=\{userId\}``#
--

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The FusionAuth User Id that is linked to the identity provider.

=== Response

:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_link-response-body.adoc[]

include::docs/v1/tech/apis/identity-providers/_links-response-body.adoc[]

== Unlink a User

This API is used to remove a link between a FusionAuth user and a 3rd party identity provider.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Delete the Link with the given Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/identity-provider/link``?identityProviderId=\{identityProviderId\}&identityProviderUserId=\{identityProviderUserId\}&userId=\{userId\}``#
--

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the identity provider.

[field]#identityProviderUserId# [type]#[String]# [required]#Required#::
The Id for the user that is provided by the upstream identity provider. This is the value that will allow FusionAuth to link this user on future logins. This value is expected to be immutable.

[field]#userId# [type]#[UUID]# [required]#Required#::
The FusionAuth User Id that is linked to the identity provider.

=== Response

This API does not return a JSON response body.

:never_search_error:
:webhook_event:
include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]
:never_search_error!:
:webhook_event!:
