---
layout: doc
title: Link APIs
description: The APIs for creating, retrieving, and deleting Identity Provider Links
---

== Overview

[NOTE.since]
====
This API has been available since 1.28.0
====

This page contains the APIs that are used to manage Links that establish a relationship between a FusionAuth User and an Identity Provider.

* <<Link a User>>
* <<Complete a pending Link>>
* <<Retrieve a Link>>
* <<Unlink a User>>

== Link a User

This API is used to create a link between a FusionAuth user and a user in a 3rd party identity provider. This API may be useful when you already know the unique Id of a user in a 3rd party identity provider and the corresponding FusionAuth user.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Link a User
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/link#
--

==== Request Body

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The Id of the identity provider.

[field]#identityProviderUserId# [type]#[String]# [required]#Required#::
The Id for the User that is provided by the identity provider. This is the value that will allow FusionAuth to link this user on future logins. It is expected to be immutable.

[field]#userId# [type]#[UUID]# [required]#Required#::
The FusionAuth Id of the User that is being linked to the identity provider.

[source,json]
.Example Request JSON
----
include::docs/src/json/identity-providers/links/create-link-request.json[]
----

=== Response

:never_search_error:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_links-post-response-body.adoc[]

== Complete a pending Link

This API is used complete a pending Link. If an identity provider is configured with a linking strategy of `Create a pending link`, a pending link Id will be returned from the Login API that can be used here.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Complete a pending Link
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/link#
--

==== Request Body

[.api]
[field]#pendingIdPLinkId# [type]#[String]# [required]#Required#::
The pending identity provider link id.

[field]#userId# [type]#[String]# [required]#Required#::
The Id of the User that is being linked to the identity provider

[source,json]
.Example Request JSON
----
include::docs/src/json/identity-providers/links/pending-link-request.json[]
----

=== Response

:never_search_error:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_links-post-response-body.adoc[]

== Retrieve a Link

This API is used to retrieve a single Link, all Links for a specific identity provider and user, or all Links for a user.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve a single link
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/link``?identityProviderId=\{identityProviderId\}&identityProviderUserId=\{identityProviderUserId\}&userId=\{userId\}``#
--

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve all links for a specific identity provider and user
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/link``?identityProviderId=\{identityProviderId\}&userId=\{userId\}``#
--

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve all links for a user
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/link``?userId=\{userId\}``#
--

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the identity provider.

[field]#identityProviderUserId# [type]#[String]# [optional]#Optional#::
The Id for the User that is provided by the identity provider. This is the value that will allow FusionAuth to link this user on future logins. It is expected to be immutable.

[field]#userId# [type]#[UUID]# [required]#Required#::
The FusionAuth User Id that is linked to the identity provider.

=== Response

The response for this API contains either a single Link or an array of Links. When you call this API with [field]#identityProviderId#, [field]#identityProviderUserId#, and [field]#userId#, the response will contain a single Link. When you call this API with [field]#userId# and either [field]#identityProviderId# or [field]#identityProviderUserId#, the response will contain an array of Links. All response types are defined below along with an example JSON response.

:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_link-response-body.adoc[]

include::docs/v1/tech/apis/identity-providers/_links-response-body.adoc[]

== Unlink a User

This API is used to remove a link between a FusionAuth user and a 3rd party identity provider.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Delete the Link with the given Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/identity-provider/link``?identityProviderId=\{identityProviderId\}&identityProviderUserId=\{identityProviderUserId\}&userId=\{userId\}``#
--

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the identity provider.

[field]#identityProviderUserId# [type]#[String]# [required]#Required#::
The Id for the User that is provided by the identity provider. This is the value that will allow FusionAuth to link this user on future logins. It is expected to be immutable.

[field]#userId# [type]#[UUID]# [required]#Required#::
The FusionAuth User Id that is linked to the identity provider.

=== Response

This API does not return a JSON response body.

:never_search_error:
include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]
:never_search_error!:
