---
layout: doc
title: Nintendo Identity Provider APIs
description: APIs for creating, retrieving, updating and deleting the Nintendo identity provider
---

include::docs/v1/tech/shared/_premium-edition-blurb.adoc[]

== Overview

[NOTE.since]
====
This API has been available since 1.36.0
====

The Nintendo identity provider type will use the Nintendo OAuth login API. It will also provide a `Login with Nintendo` button on FusionAuth's login page.

If the linking strategy depends on a username or email address, FusionAuth will leverage the `/users/me` API that is part of the Nintendo specification. The email address and username returned in the response will be used to create or lookup the existing User. Additional claims from the response can be used to reconcile the User in FusionAuth by using an Nintendo Reconcile Lambda. Unless you assign a reconcile lambda to this provider or configure the IdP options to use different claims, the `email` and `preferred_username` will be used from the available claims returned by the Nintendo identity provider.

:idp_display_name: Nintendo
:token_name: pass:normal[`access_token`]
:return_text: pass:normal[Nintendo API]
:hide_token_map_deprecation: true

include::docs/v1/tech/apis/identity-providers/_token-storage-note.adoc[]

:idp_display_name!:
:token_name!:
:return_text!:
:hide_token_map_deprecation!:

:idp_display_name: Nintendo
:idp_id: b0ac2e16-d4af-483e-98c8-7f6693610665
:idp_linking_strategy: CreatePendingLink
:idp_lowercase: nintendo
:idp_since: 13600
:idp_token_or_code: token or code
:idp_type: Nintendo
include::docs/v1/tech/apis/identity-providers/_oauth-idp-operations.adoc[]
:idp_display_name!:
:idp_id!:
:idp_linking_strategy!:
:idp_lowercase!:
:idp_since!:
:idp_token_or_code!:
:idp_type!:
