---
layout: doc
title: OpenID Connect Identity Provider APIs
description: APIs for creating, retrieving, updating and deleting OpenID Connect identity providers
---

== Overview

[NOTE.since]
====
This API has been available since 1.1.0
====

OpenID Connect identity providers connect to external OpenID Connect login systems. This type of login will optionally provide a `Login with ...` button on FusionAuth's login page. This button is customizable by using different properties of the identity provider.

Optionally, this identity provider can define one or more domains it is associated with. This is useful for allowing employees to log in with their corporate credentials. As long as the company has an identity solution that provides OpenID Connect, you can leverage this feature. This is referred to as a **Domain Based Identity Provider**. If you enable domains for an identity provider, the `Login with ...` button will not be displayed. Instead, only the `email` form field will be displayed initially on the FusionAuth login page. Once the user types in their email address, FusionAuth will determine if the user is logging in locally or if they should be redirected to this identity provider. This is determined by extracting the domain from their email address and comparing it to the domains associated with the identity provider.

FusionAuth will also leverage the `/userinfo` API that is part of the OpenID Connect specification. This API provides user information that is stored in FusionAuth. Since FusionAuth is also an OpenID Connect provider, it translates most of the OpenID Connect claims over. Here are the OpenID Connect claims that FusionAuth stores from an external OpenID Connect identity provider and the User object fields they are stored in:

* `birthdate` -> `birthDate`
* `email` -> `email`
* `family_name` -> `lastName`
* `given_name` -> `firstName`
* `locale` -> `preferredLanguages`
* `middle_name` -> `middleName`
* `name` -> `fullName`
* `phone_number` -> `mobilePhone`
* `picture` -> `imageUrl`

If the external OpenID Connect identity provider returns a refresh token, it will be stored in the `UserRegistration` object inside the `tokens` Map. This Map stores the tokens from the various identity providers so that you can use them in your application to call their APIs.

=== Operations

* <<Create an OpenID Connect Identity Provider>>
* <<Retrieve an OpenID Connect Identity Provider>>
* <<Update an OpenID Connect Identity Provider>>
* <<Delete an OpenID Connect Identity Provider>>
* <<Complete an OpenID Connect Login>>


== Create an OpenID Connect Identity Provider

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=far]] Create an OpenID Connect Identity Provider using a generated id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider#
--

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=far]] Create an OpenID Connect Identity Provider with the provided unique id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#identityProviderId# [type]#[UUID]# [optional]#Optional# [default]#defaults to secure random UUID#
|The Id to use for the new Identity Provider. If an id is not provided, a secure random UUID is generated.
|===

include::docs/v1/tech/apis/identity-providers/_openid-connect-request-body.adoc[]

=== Response

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_openid-connect-response-body.adoc[]

== Retrieve an OpenID Connect Identity Provider

=== Request
[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=far]] Retrieve an Identity Provider by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#identityProviderId# [type]#[UUID]# [required]#Required#
|The unique Id of the OpenID Connect Identity Provider to retrieve.
|===

=== Response

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_openid-connect-response-body.adoc[]

== Update an OpenID Connect Identity Provider

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=far]] Update an Identity Provider
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

:api_endpoint: pass:normal[/api/identity-provider/`\{identityProviderId\}`]
include::docs/v1/tech/apis/_patch-support.adoc[]

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#identityProviderId# [type]#[UUID]# [required]#Required#
|The unique Id of the OpenID Connect Identity Provider to update.
|===

include::docs/v1/tech/apis/identity-providers/_openid-connect-request-body.adoc[]

=== Response

The response for this API contains the OpenID Connect Identity Provider that was updated.

include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_openid-connect-response-body.adoc[]

== Delete an OpenID Connect Identity Provider

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=far]] Delete an OpenId Connect Identity Provider by Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#identityProviderId# [type]#[UUID]# [required]#Required#
|The unique Id of the OpenId Connect Identity Provider to delete.
|===

=== Response

This API does not return a JSON response body.

include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]

== Complete an OpenID Connect Login

This API allows you to complete an OpenID Connect login after authenticating a user using the OpenID Connect Authorized endpoint. If you are using the FusionAuth login UI with the OpenID Connect button you will not utilize this API directly.

This API is intended to be used if you want to build your own login page and you have added an OpenID Connect login button to your own login page and you then need to complete the login workflow.

For example, if you built your own login page, you could add a Login with Pied Piper button to utilize a third party OpenID Connect identity provider. When you complete the OpenID Connect authorization step you will have been returned an authorization code from the OpenID Connect provider. Using this API you can pass the authorization token returned from the OpenID Connect provider to FusionAuth and we will complete the login workflow and reconcile the user to FusionAuth.

The user does not need to exist yet in FusionAuth to utilize this API. The token returned from the OpenID Connect provider will be used to retrieve the user's email address, if that user does not yet exist in FusionAuth the user will be created. If create registration has been enabled for this identity provider and the user does not yet have a registration for this application, a registration will be automatically created for the user. The user will be assigned any default roles configured for the application. If create registration has not been enabled, a registration will not be created if one does not yet exist. This last scenario is useful if you wish to manually provision users and then subsequently allow them to login with this OpenID Connect identity provider.

=== Request

[.api-authentication]
link:../authentication#no-authentication-required[icon:unlock-alt[role=green,type=far]] Complete OpenID Connect Login
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/login#
--

:loginProvider: OpenID Connect
include::docs/v1/tech/apis/identity-providers/_identity-provider-login-request-body.adoc[]
:loginProvider!:

=== Response

The response for this API contains the User object.

:loginProvider: OpenID Connect
include::docs/v1/tech/apis/identity-providers/_identity-provider-login-response-body.adoc[]
:loginProvider!:
