---
layout: doc
title: SAML v2 Identity Provider APIs
description: APIs for creating, retrieving, updating and deleting SAML v2 identity providers
---
:idp_since: 10600
:extra_start_text: pass:normal[This parameter must be added as the `ID` attribute in the SAML request you are making. After you have retrieved the SAML response, this value will be in the `InResponseTo` attribute. When the Complete Login API is called this value will be verified by FusionAuth.]
:idp_linking_strategy: pass:normal[`LinkByEmail`]

== Overview

[NOTE.since]
====
This API has been available since 1.6.0
====

SAML v2 identity providers connect to external SAML v2 login systems. This type of login will optionally provide a `Login with ...` button on FusionAuth's login page. This button is customizable by using different properties of the identity provider.

Optionally, this identity provider can define one or more domains it is associated with. This is useful for allowing employees to log in with their corporate credentials. As long as the company has an identity solution that provides SAML v2, you can leverage this feature. This is referred to as a **Domain Based Identity Provider**. If you enable domains for an identity provider, the `Login with ...` button will not be displayed. Instead, only the `email` form field will be displayed initially on the FusionAuth login page. Once the user types in their email address, FusionAuth will determine if the user is logging in locally or if they should be redirected to this identity provider. This is determined by extracting the domain from their email address and comparing it to the domains associated with the identity provider.

FusionAuth will locate the user's email address in the SAML assertion which will be used to create or lookup the existing user. Additional claims from the SAML response can be used to reconcile the User to FusionAuth by using a SAML v2 Reconcile Lambda. Unless you assign a reconcile lambda to this provider, on the `email` address will be used from the available assertions returned by the SAML v2 identity provider.

=== Operations

* <<Create a SAML v2 Identity Provider>>
* <<Retrieve a SAML v2 Identity Provider>>
* <<Update a SAML v2 Identity Provider>>
* <<Delete a SAML v2 Identity Provider>>

=== Login Operations

* <<Start a SAML v2 Login Request>>
* <<Complete a SAML v2 Login>>

=== Integration Details

The following values will likely be required by your SAML v2 Identity Provider in order to trust FusionAuth as a relying party.

These values are autogenerated and viewable within the UI after creating the Identity Provider. They can be viewed by navigating to [breadcrumb]#Settings -> Identity Providers -> SAMLv2 -> View#. 

include::docs/v1/tech/identity-providers/_saml-config-urls.adoc[]

== Create a SAML v2 Identity Provider

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Create a SAML v2 Identity Provider using a generated id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider#
--

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Create a SAML v2 Identity Provider with the provided unique id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

The [field]#type# property in the request JSON indicates you are managing a SAML v2 identity provider.

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [optional]#Optional# [default]#defaults to secure random UUID#::
The Id to use for the new Identity Provider. If an id is not provided, a secure random UUID is generated.

include::docs/v1/tech/apis/identity-providers/_samlv2-request-body.adoc[]

=== Response

:never_search_error:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_samlv2-response-body.adoc[]

== Retrieve a SAML v2 Identity Provider

=== Request
[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve an Identity Provider by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the SAML v2 Identity Provider to retrieve.

=== Response

:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_samlv2-response-body.adoc[]

== Update a SAML v2 Identity Provider

:capitalized_object_name: SAML v2 Identity Provider
include::docs/v1/tech/apis/_generic-update-explanation-fragment.adoc[]
:capitalized_object_name!:

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Update an Identity Provider
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

:api_endpoint: pass:normal[/api/identity-provider/`\{identityProviderId\}`]
include::docs/v1/tech/apis/_patch-support.adoc[]

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the SAML v2 Identity Provider to update.

include::docs/v1/tech/apis/identity-providers/_samlv2-request-body.adoc[]

=== Response

The response for this API contains the SAML v2 Identity Provider that was updated.

:never_search_error:
include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_samlv2-response-body.adoc[]

== Delete a SAML v2 Identity Provider

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Delete a SAML v2 Identity Provider by Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the SAML v2 Identity Provider to delete.

=== Response

This API does not return a JSON response body.

:never_search_error:
include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]
:never_search_error!:

== Start a SAML v2 Login Request

[NOTE.since]
====
This API has been available since 1.19.0
====

This API is used to initiate a SAML v2 login request when integrating without the FusionAuth hosted login pages.

The SAML v2 AuthN request will require a unique request identifier. This API must be used to record this identifier prior to sending the SAML response from the IdP to FusionAuth in order to protect against SAML response replay attacks. You may optionally provide an identifier to this API if you need to generate your own identifier, or use the generated value provided in the API response.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Start a login request
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/start#
--

:idp_display_name: SAML v2
include::docs/v1/tech/apis/identity-providers/_identity-provider-start-request-body.adoc[]
:idp_display_name!:

=== Response

The response for this API contains a code that can be used to complete the login request.

:idp_display_name: SAML v2
include::docs/v1/tech/apis/identity-providers/_identity-provider-start-response-body.adoc[]
:idp_display_name!:

== Complete a SAML v2 Login

This API allows you to complete a SAML v2 login after the user has authenticated with a SAML v2 identity provider. If you are using the FusionAuth login UI with the SAML v2 button you will not utilize this API directly.

This API is intended to be used if you want to build your own login page and you have added a SAML v2 login button to this page.

For example, if you built your own login page, you could add a Login with Pied Piper button to utilize a third party SAML v2 identity provider. When the user completes the SAML v2 login step, they will be redirected back to your application. This is done via a form submit (using the HTTP `POST` method). This `POST` will contain a parameter named `SAMLResponse`. Using this API you can pass the `SAMLResponse` returned from the SAML v2 provider to FusionAuth and we will complete the login workflow and reconcile the user to FusionAuth.

include::docs/v1/tech/apis/identity-providers/_saml-complete-user-registration.adoc[]

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Complete SAML v2 Login
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/login#
--

==== Request Headers

[.api]
include::docs/v1/tech/apis/identity-providers/_x-forwarded-for-header.adoc[]
include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation-row-only.adoc[]

:idp_display_name: SAML v2
include::docs/v1/tech/apis/identity-providers/_identity-provider-login-request-body.adoc[]
:idp_display_name!:

=== Response

The response for this API contains the User object.

:idp_display_name: SAML v2
include::docs/v1/tech/apis/identity-providers/_identity-provider-login-response-body.adoc[]
:idp_display_name!:
:idp_since!:
