---
layout: doc
title: SAML v2 Identity Provider APIs
description: APIs for creating, retrieving, updating and deleting SAML v2 identity providers
---

== Overview

[NOTE.since]
====
This API has been available since 1.6.0
====

SAML v2 identity providers connect to external SAML v2 login systems. This type of login will optionally provide a `Login with ...` button on FusionAuth's login page. This button is customizable by using different properties of the identity provider.

Optionally, this identity provider can define one or more domains it is associated with. This is useful for allowing employees to log in with their corporate credentials. As long as the company has an identity solution that provides SAML v2, you can leverage this feature. This is referred to as a **Domain Based Identity Provider**. If you enable domains for an identity provider, the `Login with ...` button will not be displayed. Instead, only the `email` form field will be displayed initially on the FusionAuth login page. Once the user types in their email address, FusionAuth will determine if the user is logging in locally or if they should be redirected to this identity provider. This is determined by extracting the domain from their email address and comparing it to the domains associated with the identity provider.

FusionAuth will locate the user's email address in the SAML assertion which will be used to create or lookup the existing user. Additional claims from the SAML response can be used to reconcile the User to FusionAuth by using a SAML v2 Reconcile Lambda. Unless you assign a reconcile lambda to this provider, on the `email` address will be used from the available assertions returned by the SAML v2 identity provider.

=== Operations

* <<Create a SAML v2 Identity Provider>>
* <<Retrieve a SAML v2 Identity Provider>>
* <<Update a SAML v2 Identity Provider>>
* <<Delete a SAML v2 Identity Provider>>
* <<Complete a SAML v2 Login>>

=== Integration Details

The following values will likely be required by your SAML v2 Identity Provider in order to trust FusionAuth as a relying party.

They are autogenerated and viewable within the UI after creating the Identity Provider. [breadcrumb]#Settings -> Identity Providers -> SAMLv2 -> View#

[cols="1,3"]

*Callback URL (ACS):*
`<base_url>`/samlv2/acs

*Issuer:*
`<base_url>`/samlv2/sp/`{identityProvider.id}`

*Metadata URL:*
`<base_url>`/samlv2/sp/metadata/`{identityProvider.id}`

== Create a SAML v2 Identity Provider

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Create a SAML v2 Identity Provider using a generated id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider#
--

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Create a SAML v2 Identity Provider with the provided unique id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

The [field]#type# property in the request JSON is used to determine that you are managing an SAML v2 identity provider.

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [optional]#Optional# [default]#defaults to secure random UUID#::
The Id to use for the new Identity Provider. If an id is not provided, a secure random UUID is generated.

include::docs/v1/tech/apis/identity-providers/_samlv2-request-body.adoc[]

=== Response

:never_search_error:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_samlv2-response-body.adoc[]

== Retrieve a SAML v2 Identity Provider

=== Request
[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Retrieve an Identity Provider by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the SAML v2 Identity Provider to retrieve.

=== Response

:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_samlv2-response-body.adoc[]

== Update a SAML v2 Identity Provider

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Update an Identity Provider
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

:api_endpoint: pass:normal[/api/identity-provider/`\{identityProviderId\}`]
include::docs/v1/tech/apis/_patch-support.adoc[]

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the SAML v2 Identity Provider to update.

include::docs/v1/tech/apis/identity-providers/_samlv2-request-body.adoc[]

=== Response

The response for this API contains the SAML v2 Identity Provider that was updated.

:never_search_error:
include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/identity-providers/_samlv2-response-body.adoc[]

== Delete a SAML v2 Identity Provider

=== Request

[.api-authentication]
link:../authentication#api-key-authentication[icon:lock[role=red,type=fas]] Delete a SAML v2 Identity Provider by Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

==== Request Parameters

[.api]
[field]#identityProviderId# [type]#[UUID]# [required]#Required#::
The unique Id of the SAML v2 Identity Provider to delete.

=== Response

This API does not return a JSON response body.

:never_search_error:
include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]
:never_search_error!:

== Complete a SAML v2 Login

This API allows you to complete a SAML v2 login after the user has authenticated with a SAML v2 identity provider. If you are using the FusionAuth login UI with the SAML v2 button you will not utilize this API directly.

This API is intended to be used if you want to build your own login page and you have added a SAML v2 login button to this page.

For example, if you built your own login page, you could add a Login with Pied Piper button to utilize a third party SAML v2 identity provider. When the user completes the SAML v2 login step, they will be redirected back to your application. This is done via a form submit (using the HTTP `POST` method). This `POST` will contain a parameter named `SAMLResponse`. Using this API you can pass the `SAMLResponse` returned from the SAML v2 provider to FusionAuth and we will complete the login workflow and reconcile the user to FusionAuth.

The user does not need to exist yet in FusionAuth to utilize this API. The `SAMLResponse` returned from the SAML v2 provider will be used to retrieve the user's email address, if that user does not yet exist in FusionAuth the user will be created. If create registration has been enabled for this identity provider and the user does not yet have a registration for this application, a registration will be automatically created for the user. The user will be assigned any default roles configured for the application. If create registration has not been enabled, a registration will not be created if one does not yet exist. This last scenario is useful if you wish to manually provision users and then subsequently allow them to login with this SAML v2 identity provider.

=== Request

[.api-authentication]
link:../authentication#no-authentication-required[icon:unlock[role=green,type=fas]] Complete SAML v2 Login
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/login#
--

==== Request Headers

[.api]
[field]#X-Forwarded-For# [type]#[String]# [optional]#Optional#::
The IP address of a client requesting authentication. If the IP address is provided it will be stored for login history of the user. It is generally preferred to specify the IP address in the request body. If it is not provided in the request body this header value will be used if available, the request body value will take precedence.
include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation-row-only.adoc[]

:loginProvider: SAML v2
include::docs/v1/tech/apis/identity-providers/_identity-provider-login-request-body.adoc[]
:loginProvider!:

=== Response

The response for this API contains the User object.

:loginProvider: SAML v2
include::docs/v1/tech/apis/identity-providers/_identity-provider-login-response-body.adoc[]
:loginProvider!:
