---
layout: doc
title: Sony PlayStation Network Identity Provider APIs
description: APIs for creating, retrieving, updating and disabling the Sony PlayStation Network identity provider
---

== Overview

[NOTE.since]
====
This API has been available since 1.28.0
====

The Sony PlayStation Network identity provider type will use the Sony OAuth v2.0 login API. It will also provide a `Login with Sony PlayStation Network` button on FusionAuth’s login page that will direct a user to the Sony login page.

This identity provider will call Sony’s API to load the user's `email` and `online_id` and use those as `email` and `username` to lookup or create a user in FusionAuth depending on the linking strategy configured for this identity provider. Additional claims returned by Sony PlayStation Network can be used to reconcile the user to FusionAuth by using a Sony PlayStation Network Reconcile Lambda.

FusionAuth will also store the Sony PlayStation Network `access_token` returned from the Sony PlayStation Network API in the link between the user and the identity provider. This token can be used by an application to make further requests to Sony PlayStation Network APIs on behalf of the user.

:idp_display_name: Sony PlayStation Network
:idp_id: 7764b5c7-165b-4e7e-94aa-02ebe2a0a5fb
:idp_linking_strategy: CreatePendingLink
:idp_lowercase: sonypsn
:idp_since: 12800
:idp_token_or_code: code
:idp_type: SonyPSN
include::docs/v1/tech/apis/identity-providers/_oauth-idp-operations.adoc[]
:idp_display_name!:
:idp_id!:
:idp_linking_strategy!:
:idp_lowercase!:
:idp_since!:
:idp_token_or_code!:
:idp_type!:
