---
layout: doc
title: Steam Identity Provider APIs
description: APIs for creating, retrieving, updating and disabling the Steam identity provider
---

include::docs/v1/tech/shared/_premium-edition-blurb.adoc[]

== Overview

[NOTE.since]
====
This API has been available since 1.28.0
====

The Steam identity provider type will use the Steam OAuth login API. It will also provide a `Login with Steam` button on FusionAuth’s login page that will direct a user to the Steam login page. The Steam login uses the implicit OAuth grant and will return to the callback URL with `token` and `state` in the URL Fragment. This is handled by the FusionAuth `/oauth2/implicit` javascript function to pass those values to the `/oauth2/callback` endpoint.

This identity provider will call Steam's API to load the Steam user's `personaname` and use that as `username` to lookup or create a user in FusionAuth depending on the linking strategy configured for this identity provider.  However, Steam does not allow access to user emails, so neither email linking strategy can be used and user’s will not be able to login or be created.

:idp_display_name: Steam
:token_name: pass:normal[`token`]
:return_text: pass:normal[Steam login]
:hide_token_map_deprecation: true

include::docs/v1/tech/apis/identity-providers/_token-storage-note.adoc[]

:token_name!:
:return_text!:
:hide_token_map_deprecation!:


:idp_id: e4f39345-7833-4b1d-b331-ca03bdc2c4be
:idp_linking_strategy: CreatePendingLink
:idp_lowercase: steam
:idp_since: 12800
:idp_token_or_code: token
:idp_type: Steam
include::docs/v1/tech/apis/identity-providers/_oauth-idp-operations.adoc[]
:idp_display_name!:
:idp_id!:
:idp_linking_strategy!:
:idp_lowercase!:
:idp_since!:
:idp_token_or_code!:
:idp_type!:
