---
layout: doc
title: Twitch Identity Provider APIs
description: APIs for creating, retrieving, updating and disabling the Twitch identity provider
---

include::docs/v1/tech/shared/_premium-edition-blurb.adoc[]

== Overview

[NOTE.since]
====
This API has been available since 1.28.0
====

The Twitch identity provider type will use the Twitch OAuth v2.0 login API. It will also provide a `Login with Twitch` button on FusionAuth’s login page that will direct a user to the Twitch login page.

This identity provider will call Twitch’s API to load the user's `email` and `preferred_username` and use those as `email` and `username` to lookup or create a user in FusionAuth depending on the linking strategy configured for this identity provider. Additional claims returned by Twitch can be used to reconcile the user to FusionAuth by using a Twitch Reconcile Lambda.

FusionAuth will also store the Twitch `refresh_token` returned from the Twitch API in the link between the user and the identity provider. This token can be used by an application to make further requests to Twitch APIs on behalf of the user.

:idp_display_name: Twitch
:token_name: pass:normal[`refresh_token`]
:return_text: pass:normal[Twitch API]
:hide_token_map_deprecation: true

include::docs/v1/tech/apis/identity-providers/_token-storage-note.adoc[]

:token_name!:
:return_text!:
:hide_token_map_deprecation!:

:idp_id: bf4cf83f-e824-42d7-b4a3-5b10847a66b2
:idp_linking_strategy: CreatePendingLink
:idp_lowercase: twitch
:idp_since: 12800
:idp_token_or_code: token or code
:idp_type: Twitch
include::docs/v1/tech/apis/identity-providers/_oauth-idp-operations.adoc[]
:idp_display_name!:
:idp_id!:
:idp_linking_strategy!:
:idp_lowercase!:
:idp_since!:
:idp_token_or_code!:
:idp_type!:
