---
layout: doc
title: XBOX Identity Provider APIs
description: APIs for creating, retrieving, updating and disabling the XBOX identity provider
---

== Overview

[NOTE.since]
====
This API has been available since 1.28.0
====

The XBOX identity provider type will use the XBOX OAuth v2.0 login API. It will also provide a `Login with XBOX` button on FusionAuth’s login page that will direct a user to the XBOX login page.

This identity provider will call XBOX’s API to load the user's `email` and `gtg` (Gamer Tag) and use those as `email` and `username` to lookup or create a user in FusionAuth depending on the linking strategy configured for this identity provider. Additional claims returned by XBOX can be used to reconcile the user to FusionAuth by using an XBOX Reconcile Lambda.

FusionAuth will also store the XBOX `refresh_token` returned from the XBOX API in the link between the user and the identity provider. This token can be used by an application to make further requests to XBOX APIs on behalf of the user.

:idp_display_name: XBOX
:idp_id: af53ab21-34c3-468a-8ba2-ecb3905f67f2
:idp_linking_strategy: CreatePendingLink
:idp_lowercase: xbox
:idp_token_or_code: code
:idp_type: Xbox
include::docs/v1/tech/apis/identity-providers/_oauth-idp-operations.adoc[]
:idp_display_name!:
:idp_id!:
:idp_linking_strategy!:
:idp_lowercase!:
:idp_token_or_code!:
:idp_type!:
