---
layout: doc
title: Start and Stop FusionAuth
description: Learn how to start and stop the FusionAuth services
---

== Start and Stop FusionAuth

If you are using the FusionAuth server version, may need to manually start or stop FusionAuth periodically. If you find yourself in this situation
you'll be glad you know how.

[NOTE]
====
Unless you are hosting and managing FusionAuth these instructions do not apply to you. FusionAuth manages and monitors instances hosted in our private
cloud and will restart FusionAuth if necessary.
====


[NOTE]
====
*Note* that you *MUST* start the FusionAuth Search before starting the FusionAuth App service. You should also shutdown the Search Engine last. FusionAuth
utilizes the Search Engine and database for persisting and retrieving users.
====

The following examples will make the assumption that all of the services are running on the same server. Based upon how you have installed FusionAuth
you may or may not have all of the services running on the same server.

The macOS and Windows instructions assume an installation directory of `/usr/local/fusionauth` and `\fusionauth` respectively. Please adjust to your
specific installation directory. We'll refer to this directory as `FUSIONAUTH_HOME`.

=== Linux
When you install FusionAuth using our Debian or RPM packages a service is registered. It is recommended you utilize these services to start and stop
FusionAuth. If the version of Linux your using supports `systemd` you may use the `systemctl` command as well to manage services.

The service names are as follows:

* `fusionauth-search`
* `fusionauth-app`

[source,shell]
.Start FusionAuth
----
$ sudo service fusionauth-search start
$ sudo service fusionauth-app start
----

[source,shell]
.Stop FusionAuth
----
$ sudo service fusionauth-app stop
$ sudo service fusionauth-search stop
----

If you'd like to use the `systemctl` command instead, the syntax is similar to the `service` command. For example, to check the status, stop and
then start the FusionAuth App service using the `systemctl` command

[source,shell]
.Check Status, then Stop and Start FusionAuth App
----
$ systemctl status fusionauth-app.service
$ systemctl stop fusionauth-app.service
$ systemctl start fusionauth-app.service
----

If you'd prefer to use the native Elastic and Tomcat scripts you may follow the macOS instructions, the same scripts may be executed on Linux.

=== macOS

*Start and Stop services using the native Elastic and Tomcat scripts*

[source,shell]
.Start FusionAuth
----
$ /usr/local/fusionauth/fusionauth-search/elasticsearch/bin/elasticsearch
$ /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.bat start
----

[source,shell]
.Stop FusionAuth
----
$ /usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.bat stop
----

Elasticsearch should be stopped last. If you started Elasticsearch using the `elasticsearch` script then you may simply kill the terminal where
the service is running to initiate shutdown.

=== Windows

*Start and Stop services using the native Elastic and Tomcat scripts*

[source]
.Start CleanSpeak
----
> \fusionauth\fusionauth-search\elasticsearch\bin\elasticsearch.bat
> \fusionauth\fusionauth-app\apache-tomcat\bin\catalina.bat start
----

[source]
.Stop FusionAuth
----
> \fusionauth\fusionauth-app\apache-tomcat\bin\catalina.bat stop
----

Elasticsearch should be stopped last. If you started Elasticsearch using the `elasticsearch.bat` script then you may simply close the command
window where the service is running to initiate shutdown.

*Start and Stop services using Windows Services*

We also provide support for running FusionAuth as a Windows service.

[source]
.Register Windows Services
----
> \fusionauth\fusionauth-search\elasticsearch\bin\FusionAuthSearch.exe /install
> \fusionauth\fusionauth-app\apache-tomcat\bin\FusionAuthApp.exe /install
----

[source]
.Unregister Windows Services
----
> \fusionauth\fusionauth-app\apache-tomcat\bin\FusionAuthApp.exe /uninstall
> \fusionauth\fusionauth-search\elasticsearch\bin\FusionAuthSearch.exe /uninstall
----

[source]
.Start Services
----
> net start FusionAuthSearch
> net start FusionAuthApp
----

[source]
.Stop Services
----
> net stop FusionAuthApp
> net stop FusionAuthSearch
----