---
layout: doc
title: FusionAuth Advanced Threat Detection
description: FusionAuth Advanced Threat Detection gives you a variety of tools to secure your application
---
:page-liquid:

:sectnumlevels: 0

include::docs/v1/tech/shared/_enterprise-edition-blurb.adoc[]

== Overview

[NOTE.since]
====
Available since 1.30.0
====

Flagging and responding to suspicious behavior is a part of any cybersecurity product. 
Advanced Threat Detection, a feature that brings best-practice functionality to help you deal with bizarre, possibly malicious behavior around logins, registrations, user creation, and user updates.

Turning this feature on requires a support ticket, as this feature is being rolled out over time. Submit a [support ticket through your account portal](https://account.fusionauth.io/account/support).

This feature includes:

* <<Customizable Rate Limiting>>
* <<CAPTCHA>>
* <<Location Aware Security>>
* <<IP ACLs>>
* <<Registration Domain Blocking>>
* <<Webhook Events>>

Each is configurable on a tenant by tenant basis. You can do so via link:/docs/v1/tech/apis/tenants[the Tenant API] or by navigating to [breadcrumb]#Tenants -> My Tenant -> Security#.

Here's a brief video covering some aspects of Advanced Threat Detection:

video::pjGxOXamVfk[youtube,width=560,height=315]

== Customizable Rate Limiting

These are per user rate limits for the following user actions

* Failed login
* Forgot password
* Send or resend email verification
* Passwordless/magic link login
* Send or resend registration verification
* Send two-factor code

IMAGE

You can enable or disable each of these and control the number of allowed attempts within a window before an action will be rate limited.
When an action is rate limited, it will not succeed. 

== CAPTCHA 

CAPTCHA stands for Completely Automated Public Turing test to tell Computers and Humans Apart, and can provide additional security.
FusionAuth will require a CAPTCHA in certain circumstances such as when a device has never been seen before. 

There are a variety of paid and free CAPTCHAs supported, including Google ReCaptcha and HCaptcha.

== Location Aware Security

FusionAuth has location information for requests and uses it in a variety of ways to secure user accounts.
These are all configurable and controllable by developers integrating FusionAuth into their applications.

Some location aware features include:

* Inside of every Forgot/Reset Password email sent to a user, the geographic location of where the password reset request was made is displayed. The recipient can determine if the location of the requester seems suspicious. 
* Flag suspicious login events and notify the user of a new login with the approximate location. A webhook is also sent.
* Calculates "impossible travel" to see if a user could realistically log in at different locations around the globe in a reasonable time frame.
* When a login request occurs from an unexpected IP address, a user receives an email to notify them of a new login with an approximate location of the IP address.

== IP ACLs

For security purposes, you may want to lock down an application or API key to a certain IP address or range of IP addresses.

With Advanced Threat Detection, you can do this. Create an IP ACL:

IMAGE

and then you can apply it to an application (if using the hosted login pages).
This will prevent a user from being able to even access an application login page if they are not in the IP address range.
If you have internal applications or applications to which access should otherwise be limited, this feature can help lock those applications down.

IMAGE 

You can also lock down an API key to a given range.
This is useful if you are managing your FusionAuth configuration via a CI/CD system.
You can create an API key to modify configurations, but limit that key to the IP address range of your CI/CD system, increasing security and lowering the risk of the API key being used incorrectly.

IMAGE

== Registration Domain Blocking

If you enable self service registration, users can provide any email address they like.
But you may have email domains that have elevated privileges, like your `company.com` domain.
There may be email addresses for which you want to block registration, like consumer `gmail.com` addresses if your application is aimed at business users.

In either of these cases, you can block one or more domains from the registration process using Advanced Threat Detection. 

IMAGE

== Webhook Events

There are a number of security related events that your SIEM or other analytics systems may want to ingest, such as when MFA has been disabled for a user or when a user has requested a password reset. 

Here's the full list of Advanced Threat Detection webhooks:

include::docs/v1/tech/events-webhooks/events/_list-advanced-threat-detection-webhooks.adoc[]


