---
layout: doc
title: Custom Password Hashing (Password Encryptors)
description: Learn how to write a FusionAuth plugin to implement a custom password hashing algorithm (also referred to a password encryptors)
---

== Overview

There are times when you have a custom password hash that you want to import into FusionAuth. link:/docs/v1/tech/reference/password-hashes[FusionAuth supports a number of password hashing schemes] but you can write a custom plugin if you have hashed your passwords using a different scheme.

You can use your custom password hashing scheme going forward, or you can rehash your passwords. You'd use the former strategy if you wanted to use a strong, unsupported password hashing scheme such as Argon2. You'd use the latter strategy if you are migrating from a system with a weaker hashing algorithm.

* <<Write the Password Encryptor Class>>
* <<Adding the Guice Bindings>>
* <<Writing a Unit Test>>
* <<Integration Test>>
* <<Sample Code>>
* <<Rehashing User Passwords>>

[NOTE]
====
This code uses the words 'encryption' and 'encryptor' for backwards compatibility, but what it is really doing is hashing the password.
====

=== Write the Password Encryptor Class

The main plugin interface in FusionAuth is the Password Encryptors interface. This allows you to write a custom password hashing scheme. A custom password hashing scheme is useful when you import users from an existing database into FusionAuth so that the users don't need to reset their passwords to login into your applications.

To write a Password Encryptor, you must first implement the `io.fusionauth.plugin.spi.security.PasswordEncryptor` interface. Here's an example Password Encryptor.

[source,java]
.Password Encryptor
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-password-encryptor/master/src/main/java/com/mycompany/fusionauth/plugins/ExamplePBDKF2HMACSHA1PasswordEncryptor.java[]
----

=== Adding the Guice Bindings

To complete the main plugin code (before we write a unit test), you need to add Guice binding for your new Password Encryptor. Password Encryptors use Guice Multibindings via Map. Here is an example of binding our new Password Encryptor so that FusionAuth can use it for users.

[source,java]
.Guice Module
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-password-encryptor/master/src/doc/java/MyExampleFusionAuthPluginModule.java[]
----

You can see that we have bound the Password Encryptor under the name `example-salted-pbkdf2-hmac-sha1-10000`. This is the same name that you will use when creating users via the link:/docs/v1/tech/apis/users[User API].

=== Writing a Unit Test

You'll probably want to write some tests to ensure that your new Password Encryptor is working properly. Our example uses TestNG, but you can use JUnit or another framework if you prefer. Here's a simple unit test for our Password Encryptor:

[source,java]
.Unit Test
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-password-encryptor/master/src/test/java/com/mycompany/fusionauth/plugins/ExamplePBDKF2HMACSHA1PasswordEncryptorTest.java[]
----

To run the tests using the Java Maven build tool, run the following command.

[source]
----
mvn test
----

=== Integration Test

After you have completed your plugin, the unit test and installed the plugin into a running FusionAuth installation, you can test it by hitting the User API and creating a test user. Here's an example JSON request that uses the new Password Encryptor:

[source,json]
----
{
  "user": {
    "id": "00000000-0000-0000-0000-000000000001",
    "active": true,
    "email": "test0@fusionauth.io",
    "encryptionScheme": "example-salted-pbkdf2-hmac-sha1-10000",
    "password": "password",
    "username": "username0",
    "timezone": "Denver",
    "data": {
      "attr1": "value1",
      "attr2": ["value2", "value3"]
    },
    "preferredLanguages": ["en", "fr"],
    "registrations": [
      {
        "applicationId": "00000000-0000-0000-0000-000000000042",
        "data": {
          "attr3": "value3",
          "attr4": ["value4", "value5"]
        },
        "id": "00000000-0000-0000-0000-000000000003",
        "preferredLanguages": ["de"],
        "roles": ["role 1"],
        "username": "username0"
      }
    ]
  }
}
----

Notice that we've passed in the `encryptionScheme` property with a value of `example-salted-pbkdf2-hmac-sha1-10000`. This will instruct FusionAuth to use your newly written Password Encryptor.

=== Sample Code

https://github.com/FusionAuth/fusionauth-example-password-encryptor[A sample plugin project is available]. If you are looking to write your own custom password hashing algorithm, this project is a good starting point.

=== Rehashing User Passwords

include::docs/v1/tech/shared/_rehashing-user-passwords.adoc[]
