---
layout: doc
title: Writing a Plugin
description: Learn how to write a FusionAuth Plugin
---

== Overview

FusionAuth provides a plugin mechanism that loads plugins at startup rather than at runtime. This provides much better performance than a runtime plugin system. Therefore, you must restart FusionAuth anytime a plugin is installed.

There are two steps to adding a plugin to FusionAuth:

1. Write the plugin by implementing the correct plugin interface
2. Install the plugin into your FusionAuth installation

You may also want to review the link:../reference/password-encryptors[standard FusionAuth Password Encryption schemes].

== Writing a Plugin

=== Install Java 8

If you haven't already, you need to download the Java 8 JDK. This contains all of the tools you need to compile Java projects and create JAR files. You can download the Java 8 JDK from the Oracle at the following link.

- https://www.oracle.com/java/technologies/javase-downloads.html

==== Get the example code

To begin, clone the following GitHub repository. This example code will assume you are able to use the Maven build commands.

[source,shell]
----
git clone git@github.com:FusionAuth/fusionauth-example-password-encryptor.git
cd fusionauth-example-password-encryptor
mvn compile package
----

If the above commands were successful you have now downloaded the example code and performed and initial build of the jar. If last command was not found, you do not yet have Maven build tool installed. You may utilize whatever Java build system you prefer, such as Maven, Ant, Gradle or Savant. This example wil use the Maven build system.

The following is is a representation of the plugin project layout.

[source]
.Plugin Project Layout
----
fusionauth-example-password-encryptor
  |
  |- src
  |   |- main
  |   |   |- java
  |   |
  |   |- test
  |       |- java
  |
  |- pom.xml
----

Following the Java convention of using packages for all classes, you will want to create sub-directories under src/main/java and src/test/java that identify the package for your plugin. For example, you might create a directory under each called `com/mycompany/fusionauth/plugins` that will contain your plugin code.

In the example code you are beginning from, you will find the Plugin `MyExamplePasswordEncryptor` in the package `com/mycompany/fusionauth/plugins`.

Your project is now ready for you to start coding.

=== Edit your build file

To modify the name of your plugin, edit your build file.  Below is a small portion of the build file, you may change whatever you like, but to start with you will want to change the `groupId` and the `artifactId`. These values are used to name the jar that will be built later.


[source,xml]
.pom.xml
----
  <groupId>io.fusionauth</groupId>
  <artifactId>fusionauth-example-password-encryptor</artifactId>
  <version>0.1.0</version>
----

=== Code the plugin

This is where you get to code! Ideally you would have one or two known passwords in the data you will be importing to Fusionauth so that you can test your plugin prior to installing it in FusionAuth.

Begin by modifying the `MyExamplePasswordEncryptor` class found in `src/main/java`.

You will find a test ready for you to use called `MyExamplePasswordEncryptorTest` in the package `com/mycomany/fusionauth/plugins` in the `src/test/java` directory. Use this test to assert on one or two known plain text passwords to ensure that the hash you calculate is equal to the actual hash that you will be importing from your existing system.

You will also find a few other example plugins that are written and tested that you can review to get an idea of how they work. You may delete any of the example code you do not want in your final jar.

=== Create the Guice binding

FusionAuth uses Guice for dependency injection and also to setup plugins. No matter what type of plugin you are writing, you need to add a single Guice module to your project.

[WARNING]
====
In order for FusionAuth to locate your plugin, the package you put your plugin module into must include a parent package named either plugin or plugins. For example, a plugin class cannot be named `com.mycompany.fusionauth.MyExampleFusionAuthPluginModule`. Instead, it must be named `com.mycompany.fusionauth.plugins.MyExampleFusionAuthPluginModule`.
====

Edit the example Guice module in the `src/main/java` directory.

[source]
----
com/mycompany/fusionauth/plugins/guice/MyExampleFusionAuthPluginModule.java
----

Here is an example of what you will find in the example Guice module referenced above.

[source,java]
----
package com.mycompany.fusionauth.plugins.guice;

import com.google.inject.AbstractModule;
import com.google.inject.multibindings.MapBinder;
import com.mycompany.fusionauth.plugins.MyExamplePasswordEncryptor;
import io.fusionauth.plugin.spi.PluginModule;
import io.fusionauth.plugin.spi.security.PasswordEncryptor;

/**
 * My cool FusionAuth plugin module.
 */
@PluginModule
public class MyExampleFusionAuthPluginModule extends AbstractModule {
  @Override
  protected void configure() {
    MapBinder<String, PasswordEncryptor> passwordEncryptorMapBinder = MapBinder.newMapBinder(binder(), String.class, PasswordEncryptor.class);
    passwordEncryptorMapBinder.addBinding("example-hash").to(MyExamplePasswordEncryptor.class);
  }
}
----

Notice that this plugin is annotated with the class `io.fusionauth.plugin.spi.PluginModule`. This is how FusionAuth locates the Guice module and installs your plugin.

=== Building

This will assume you using the Maven build tool. You are welcome to utilize any Java build tool that you wish.

[source,shell]
----
mvn clean compile package
ls -lah ./target/*.jar
-rw-r--r--  1 robotdan  staff   4.5K Apr 24 08:06 ./target/fusionauth-example-password-encryptor-0.1.0.jar
----

The above command will compile and build a jar artifact that we will install onto FusionAuth. The jar found in the `target` directory is your plugin.

=== Install the Plugin

After you have completed your plugin code and all of your unit tests pass, you are ready to install the plugin into FusionAuth. You will utilize the jar build output file from the previous step.

Next, you need to create the plugin directory in your FusionAuth installation. Depending on where you installed FusionAuth, you will create the plugin directory in the `FUSIONAUTH_HOME` directory. This directory is the directory right above the `FUSIONAUTH_HOME` directory. Here are some examples for the plugin directory:

[source,text]
.Linux and macOS
----
/usr/local/fusionauth/plugins
----

[source,text]
.Windows
----
\fusionauth\plugins
----

The location of this directory might be different if you install using the ZIP bundles and placed FusionAuth somewhere else.

Next, you copy this JAR file from your plugin project into the plugin directory like this:

[source,shell]
.Linux/Mac/Unix
----
cp target/fusionauth-example-password-encryptor-0.1.0.jar /usr/local/fusionauth/plugins
----

[source]
.Windows
----
cp target\fusionauth-example-password-encryptor-0.1.0.jar \fusionauth\plugins
----

Now you can restart FusionAuth and it should load your plugin. If you plugin is found and loaded successfully, you should see a message like this in the logs:

[source,log]
----
INFO  io.fusionauth.api.plugin.guice.PluginModule - Installing plugin [com.mycompany.fusionauth.plugins.guice.MyExampleFusionAuthPluginModule]
INFO  io.fusionauth.api.plugin.guice.PluginModule - Plugin successfully installed
----
