==== Request Body

[.api]
[field]#messenger.connectTimeout# [type]#[Integer]# [required]#Required#::
The connect timeout for the HTTP connection, in milliseconds. Value must be greater than `0`.

[field]#messenger.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Messenger that should be persisted.

[field]#messenger.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if debug should be enabled to create an event log to assist in debugging messenger errors.

[field]#messenger.headers# [type]#[Object]# [optional]#Optional#::
An object that can hold HTTPHeader key and value pairs.

[field]#messenger.httpAuthenticationPassword# [type]#[String]# [optional]#Optional#::
The basic authentication password to use for requests to the Messenger.

[field]#messenger.httpAuthenticationUsername# [type]#[String]# [optional]#Optional#::
The basic authentication username to use for requests to the Messenger.

[field]#messenger.name# [type]#[String]# [required]#Required#::
The unique Messenger name.

[field]#messenger.readTimeout# [type]#[Integer]# [required]#Required#::
The read timeout for the HTTP connection, in milliseconds. Value must be greater than `0`.

[field]#messenger.sslCertificateId# [type]#[UUID]# [optional]#Optional#::
The Id of an existing link:/docs/v1/tech/apis/keys/[Key]. The X509 certificate is used for client certificate authentication in requests.

[field]#messenger.type# [type]#[String]# [required]#Required#::
This field must be set to `Generic`.

[field]#messenger.url# [type]#[String]# [required]#Required#::
The fully qualified URL of the endpoint that will accept requests from FusionAuth.

[source,json]
.Example Generic Messenger Request JSON
----
include::../../../../src/json/messengers/generic-request.json[]
----
