==== Response Body

[.api]
[field]#messenger.data# [type]#[Object]#::
An object that can hold any information about the Messenger that should be persisted.

[field]#messenger.debug# [type]#[Boolean]#::
If debug is enabled, an event log is created to assist in debugging messenger errors.

[field]#messenger.defaultTopic# [type]#[String]#::
The name of the Kafka topic to send messages.

[field]#messenger.id# [type]#[UUID]#::
The unique Id of the Messenger.

[field]#messenger.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Messenger was added to the FusionAuth database.

[field]#messenger.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Messenger was last updated in the FusionAuth database.

[field]#messenger.name# [type]#[String]#::
The unique Messenger name.

[field]#messenger.producer# [type]#[Map<String, String>]#::
String key value pairs to be used when building the Kafka Producer.

[field]#messenger.transport# [type]#[String]#::
The message transport protocol used to send a message. This value is currently read-only and set to `sms`.

[field]#messenger.type# [type]#[String]#::
This field will always be `Kafka`.

[source,json]
.Example Request JSON
----
include::../../../../src/json/messengers/kafka-response.json[]
----