==== Response Body

[.api]
[field]#messenger.accountSID# [type]#[String]#::
The Twilio Account ID to use when connecting to the Twilio API. This can be found in your Twilio dashboard.

[field]#messenger.authToken# [type]#[String]#::
The Twilio Auth Token to use when connecting to the Twilio API. This can be found in your Twilio dashboard.

[field]#messenger.debug# [type]#[Boolean]#::
Determines if debug should be enabled to create an event log to assist in debugging messenger errors.

[field]#messenger.fromPhoneNumber# [type]#[String]#::
The configured Twilio phone number that will be used to send messages. This can be found in your Twilio dashboard.

[field]#messenger.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Messenger was added to the FusionAuth database.

[field]#messenger.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Messenger was last updated in the FusionAuth database.

[field]#messenger.messagingServiceSid# [type]#[String]#::
The Twilio message service Id, this is used when using Twilio Copilot to load balance between numbers. This can be found in your Twilio dashboard.
+
When using the Twilio Messaging Services Id, you may omit the [field]#fromPhoneNumber# field.

[field]#messenger.name# [type]#[String]#::
The unique Messenger name.

[field]#messenger.url# [type]#[String]#::
The fully qualified URL of the endpoint that will accept requests from FusionAuth.

[source,json]
.Example Response JSON
----
include::../../../../src/json/messengers/twilio-response.json[]
----