==== Response Body

[.api]
[field]#messenger.accountSID# [type]#[String]#::
The Twilio Account ID to use when connecting to the Twilio API.

[field]#messenger.authToken# [type]#[String]#::
The Twilio Auth Token to use when connecting to the Twilio API.

[field]#messenger.data# [type]#[Object]#::
An object that can hold any information about the Messenger that should be persisted.

[field]#messenger.debug# [type]#[Boolean]#::
Determines if debug should be enabled to create an event log to assist in debugging messenger errors.

[field]#messenger.fromPhoneNumber# [type]#[String]#::
The configured Twilio phone number that will be used to send messages.

[field]#messenger.id# [type]#[UUID]#::
The unique Id of the Messenger.

[field]#messenger.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Messenger was added to the FusionAuth database.

[field]#messenger.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Messenger was last updated in the FusionAuth database.

[field]#messenger.messagingServiceSid# [type]#[String]#::
The Twilio message service Id, this is used when using Twilio Copilot to load balance between numbers.
+
When using [field]#messagingServicesSid#, you may omit the [field]#fromPhoneNumber# field.

[field]#messenger.name# [type]#[String]#::
The unique Messenger name.

[field]#messenger.transport# [type]#[String]#::
The message transport protocol used to send a message. This value is currently read-only and set to `sms`.

[field]#messenger.type# [type]#[String]#::
This field will always be `Twilio`.

[field]#messenger.url# [type]#[String]#::
The fully qualified URL of the Twilio API endpoint that will accept requests from FusionAuth.

[source,json]
.Example Response JSON
----
include::../../../../src/json/messengers/twilio-response.json[]
----