==== Request Body

[.api]
[field]#messenger.accountSID# [type]#[String]# [required]#Required#::
The Twilio Account ID to use when connecting to the Twilio API. This can be found in your Twilio dashboard.

[field]#messenger.authToken# [type]#[String]# [optional]#Optional#::
The Twilio Auth Token to use when connecting to the Twilio API. This can be found in your Twilio dashboard.

[field]#messenger.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Messenger that should be persisted.

[field]#messenger.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
If debug is enabled, an event log is created to assist in debugging messenger errors.

[field]#messenger.fromPhoneNumber# [type]#[String]# [optional]#Optional#::
The configured Twilio phone number that will be used to send messages. This can be found in your Twilio dashboard.

[field]#messenger.messagingServiceSid# [type]#[String]# [optional]#Optional#::
The Twilio message service Id, this is used when using Twilio Copilot to load balance between numbers. This can be found in your Twilio dashboard.
+
When using [field]#messagingServicesSid#, you may omit the [field]#fromPhoneNumber# field.

[field]#messenger.name# [type]#[String]# [required]#Required#::
The unique Messenger name.

[field]#messenger.url# [type]#[String]# [required]#Required#::
The fully qualified URL of the Twilio API endpoint that will accept requests from FusionAuth.

[source,json]
.Example Request JSON
----
include::../../../../src/json/messengers/twilio-request.json[]
----
