create Forums

== Initialize ==
Browser->Forums : GET /\n[No cookies]
Forums->Browser : (SPA HTML, CSS & JavaScript)
Browser->Forums : GET /api/user\n[No cookies]
Forums-[#EB8C52]>Browser : <color #EB8C52>404 Missing</color>
