== Initialize ==
autonumber
Browser->Store : GET /
Store->Browser : (SPA HTML, CSS & JavaScript)
Browser->Store : AJAX GET /api/user\n[No cookies]
Store-[#red]>Browser : <color red>404 Missing</color>
