== Initialize ==
autonumber
Browser->Store : GET /
Store->Browser : (SPA HTML, CSS & JavaScript)
Browser->Store : AJAX GET /api/user\n[No cookies]
Store-[#EB8C52]>Browser : <color #EB8C52>404 Missing</color>
