note over Browser, Browser #EB8C52;line:white : <color white><b>Session expires - refresh token still valid</b></color>

== Shopping cart load ==
Browser->Store : AJAX GET /api/load-shopping-cart\n[SessionId and Refresh token HttpOnly w/ domain: Store.Example.com]
Store->FusionAuth : POST /oauth2/token or POST /api/jwt/refresh\n(grant_type=refresh and refresh token)
FusionAuth->Store : (JWT)
Store->Store : Create new session
Store->Browser : (Shopping cart contents)\n[New SessionId HttpOnly w/ domain: Store.Example.com]
