!include ../_session-expires.plantuml

== Re-login ==
Browser->Store : AJAX GET /api/load-shopping-cart\n[SessionId HttpOnly w/ domain: Store.Example.com]
Store-[#red]>Browser : <color red>401 Not Authorized</color>
Browser->Browser : Login same as above
