!include ../_jwt-expires.plantuml

== Shopping cart load ==
Browser->Store : AJAX GET /api/load-shopping-cart\n[Refresh token and JWT HttpOnly w/ domain: Store.Example.com]
Store->FusionAuth : POST /oauth2/token or POST /api/jwt/refresh\n(grant_type=refresh and refresh token)
FusionAuth->Store : (JWT)
Store->Browser : (Shopping cart contents)\n[New JWT HttpOnly w/ domain: Store.Example.com]
