note over Browser #red;line:white : <color white>Session expires - refresh token expires</color>

== Re-login ==
Browser->Store : AJAX GET /api/load-shopping-cart\n[SessionId and Refresh token HttpOnly w/ domain: Store.Example.com]
Store->FusionAuth : POST /oauth2/token or POST /api/jwt/refresh\n(grant_type=refresh and refresh token)
FusionAuth-[#red]>Store : <color red>404 Missing</color>
Store-[#red]>Browser : <color red>401 Not Authorized</color>
Browser->Browser : Login same as above
