== Stolen refresh token ==
Hacker->Store : GET /shopping-cart\n[Refresh token and bad session id HttpOnly w/ domain: Store.Example.com]
Store->FusionAuth : POST /oauth2/token or POST /api/jwt/refresh\n(grant_type=refresh and refresh token)
FusionAuth->Store : (JWT)
Store->Store : Create session and store User in
Store->Hacker : (Shopping cart contents)\n[New JWT HttpOnly w/ domain: Store.Example.com]
