@startuml
  !include ../_config.plantuml
  !include ../_participants.plantuml
  !include ../_intro.plantuml
  !include _initialize.plantuml

  == Login (inside SPA) ==
  Browser->Browser : Render login form
  Browser->FusionAuth : AJAX POST /api/login
  FusionAuth->Browser : (JWT)\n[Refresh token HttpOnly w/ domain: login.fusionauth.io]

  == Cookie drop ==
  Browser->Store : AJAX POST /api/cookie-drop\n(JWT from IdP response)
  Store->Browser : [JWT HttpOnly w/ domain: Store.Example.com]

  !include _shopping-cart-jwtCookie-load.plantuml

  !include ../_jwt-expires.plantuml
  
  == Refresh JWT ==
  Browser->FusionAuth : AJAX POST /api/jwt/refresh\n[Refresh token w/ domain login.fusionauth.io]
  FusionAuth->Browser : (JWT)

  == Cookie drop ==
  Browser->Store : AJAX POST /api/cookie-drop\n(JWT from IdP response body)
  Store->Browser : [JWT HttpOnly w/ domain: Store.Example.com]

  !include_many _shopping-cart-jwtCookie-load.plantuml

  == Re-login (inside SPA) ==
  note over Browser, Browser #EB8C52;line:white : <color white><b>Refresh token expires</b></color>
  Browser->FusionAuth : AJAX POST /api/jwt/refresh\n[Refresh token w/ domain login.fusionauth.io]
  FusionAuth-[#EB8C52]>Browser : <color #EB8C52>404 Missing</color>
  Browser->Browser : Login same as above

  !include ../_sso-not-provided.plantuml

  !include _forums-initialize.plantuml

  == Login (inside SPA) ==
  Browser->Browser : Render login form
  Browser->FusionAuth : AJAX POST /api/login\n[Refresh token HttpOnly w/ domain: login.fusionauth.io - <color #EB8C52>FOR WRONG APP</color>]
  FusionAuth->Browser : (JWT)\n[New Refresh token HttpOnly w/ domain: login.fusionauth.io]
  Browser->Browser : <color #EB8C52>Refresh token cookie from Store gets</color>\n<color #EB8C52>clobbered by Refresh token for Forums</color>

  == Cookie drop ==
  Browser->Forums : AJAX POST /api/cookie-drop\n(JWT from IdP response)
  Forums->Browser : [JWT HttpOnly w/ domain: Forums.Example.com]

  !include _forums-jwtCookie-load.plantuml

  !include ../_attack-vectors.plantuml

  == Stolen Refresh token ==
  Hacker->FusionAuth : POST /api/jwt/refresh\n[Refresh token HttpOnly w/ domain login.fusionauth.io]
  FusionAuth->Hacker : (JWT)
  Hacker->Store : GET /api/load-shopping-cart\n[JWT HttpOnly w/ domain: Store.Example.com]
  Store->Hacker : (Shopping cart contents)

  !include _stolen-jwt-refresh-jwt.plantuml
@enduml
