@startuml
  !include ../_config.plantuml
  !include ../_participants.plantuml
  !include ../_intro.plantuml
  !include _initialize.plantuml

  == Login (inside SPA) ==
  Browser->Browser : Render login form
  Browser->Store : AJAX POST /api/login
  Store->FusionAuth : POST /oauth2/token\n(grant_type=password)
  FusionAuth->Store : (Refresh Token and JWT)
  Store->Store : Create session and store User in it
  Store->Browser : [SessionId HttpOnly w/ domain: Store.Example.com]

  !include _shopping-cart-session-load.plantuml

  !include _shopping-cart-session-relogin.plantuml

  !include ../_sso-not-provided.plantuml

  !include _forums-initialize.plantuml
  
  == Login (inside SPA) ==
  Browser->Browser : Render login form
  Browser->Forums : AJAX POST /api/login
  Forums->FusionAuth : POST /oauth2/token\n(grant_type=password)
  FusionAuth->Forums : (Refresh Token and JWT)
  Forums->Forums : Create session and store User in it
  Forums->Browser : [SessionId HttpOnly w/ domain: Forums.Example.com]

  !include _forums-session-load.plantuml

  !include ../_attack-vectors.plantuml

  !include _stolen-session-id.plantuml
@enduml