@startuml
  !include ../_config.plantuml
  !include ../_participants.plantuml
  !include ../_intro.plantuml
  !include _initialize-local-storage.plantuml

  == Login (browser navigates away from SPA) ==
  Browser->FusionAuth : GET /oauth2/authorize {response_type=token}
  FusionAuth->Browser : (Login form HTML)
  Browser->FusionAuth : POST /oauth2/authorize (response_type=token)
  FusionAuth->Browser : 302 Location: {redirect_uri w/ JWT in redirect URI and no refresh token}\n[SessionId HttpOnly w/ domain: login.fusionauth.io]
  Browser->Store : GET {redirect_uri w/o JWT in URI}
  Store->Browser : (SPA HTML, CSS & JavaScript)

  == Local storage drop ==
  Browser->Browser : Move JWT from URI to local storage

  !include _shopping-cart-jwt-local-storage-load.plantuml

  !include ../_jwt-expires.plantuml

  == Automatic re-login (since session exists) ==
  Browser->FusionAuth : GET /oauth2/authorize {response_type=token}\n[SessionId HttpOnly w/ domain: login.fusionauth.io]
  FusionAuth->Browser : 302 Location: {redirect_uri w/ JWT in redirect URI and no refresh token}\n[SessionId HttpOnly w/ domain: login.fusionauth.io]
  Browser->Store : GET {redirect_uri w/o JWT in URI}
  Store->Browser : (SPA HTML, CSS & JavaScript)

  == Local storage drop ==
  Browser->Browser : Move JWT from URI to local storage

  !include_many _shopping-cart-jwt-local-storage-load.plantuml

  !include ../_sso.plantuml

  !include _forums-initialize-local-storage.plantuml

  == Login (browser navigates away from SPA but auto-logs-in since the session exists) ==
  Browser->FusionAuth : GET /oauth2/authorize {response_type=token}\n[SessionId HttpOnly w/ domain: login.fusionauth.io]
  FusionAuth->Browser : 302 Location: {redirect_uri w/ JWT in redirect URI and no refresh token}\n[SessionId HttpOnly w/ domain: login.fusionauth.io]
  Browser->Forums : GET {redirect_uri w/o JWT in URI}
  Forums->Browser : (SPA HTML, CSS & JavaScript)

  == Local storage drop ==
  Browser->Browser : Move JWT from URI to local storage

  !include _forums-jwt-local-storage-load.plantuml

  !include ../_attack-vectors.plantuml

  == Stolen JWT ==
  Hacker->Store : GET /api/load-shopping-cart\n(JWT)
  Store->Hacker : (Shopping cart contents)
@enduml