---
layout: doc
title: Configuration Reference
description: A complete list of the configuration options in the fusionauth.properties file
---

:sectnumlevels: 0
== Configuration Reference

Much of the FusionAuth configuration is performed in the UI. Some additional advanced configuration is provided through a configuration file.
Additionally, some of these properties may be overridden a related environment variable.
Updates to the properties file or environment variables require FusionAuth to be restarted to pick up these configuration changes.

This page describes the advanced configuration of FusionAuth.

  * link:#properties[Properties]
  * link:#environment-variables[Environment Variables]
  * link:#silent-configuration[Silent Configuration]

==== Properties

Assuming you installed in the default locations, the configuration file may be found in the following directory. If you have installed in an
alternate location the path to this file will be different.

[source,text]
.Linux and macOS
----
/usr/local/fusionauth/config/fusionauth.properties
----

[source,text]
.Windows
----
\fusionauth\config\fusionauth.properties
----

The following table contains all of the configuration options available in the `fusionauth.properties` file.

[.api]
[field]#database.url# [type]#[String]#::
include::docs/v1/tech/reference/_property-database-url.adoc[]

[field]#database.username# [type]#[String]#::
include::docs/v1/tech/reference/_property-database-username.adoc[]

[field]#database.password# [type]#[String]#::
include::docs/v1/tech/reference/_property-database-password.adoc[]

[field]#database.mysql.enforce-utf8mb4# [type]#[String]# [default]#defaults to `true`#::
When set to `true` and using MySQL, a 4 byte UTF compatible character set configuration is enforced at startup.
+
If this validation is not desired or not it is not possible to modify your MySQL configuration to satisfy the validation, disable this check by setting this value to `false`. If this is `false`, any attempt to store a 4 byte unicode character will cause the `INSERT` or `UPDATE` request to fail. The initial MySQL UTF-8 implementation only supported up to characters up to 3 bytes in length; utf8mb4 extends this to 4 byte characters.

[field]#fusionauth.runtime-mode# [type]#[String]# [default]#defaults to `development`# [since]#Available since 1.16.0#::
include::docs/v1/tech/reference/_property-runtime-mode.adoc[]

[field]#fusionauth-search.transport-port# [type]#[Integer]# [default]#defaults to `9020`#::
The port that the search engine will use for optimized TCP communications instead of HTTP communications. This port is used internally by the search engine to communicate between clustered nodes.

[field]#fusionauth-search.http-port# [type]#[Integer]# [default]#defaults to `9021`#::
The port number that the Search Engine will use to accept HTTP requests. This value is also utilized by FusionAuth to make HTTP requests to the FusionAuth Search.

[field]#fusionauth-search.memory# [type]#[String (Memory)]# [default]#defaults to `512M`#::
include::docs/v1/tech/reference/_property-memory.adoc[]

[field]#fusionauth-search.additional-java-args# [type]#[String]#::
include::docs/v1/tech/reference/_property-additional-jvm-args.adoc[]

[field]#fusionauth-search.hosts# [type]#[String]# [default]#defaults to `\_local_`#::
This parameter indicates which address or network interfaces to bind during service startup. The default value will cause the service to bind  any loopback address on the system such as `127.0.0.1`.
+
This default value is sufficient for running FusionAuth and the Search Engine on the same server. If you run FusionAuth Search on a separate system than FusionAuth App you will need to modify this value. You may specify a single hostname or IP address or one of the special values in any combination.
+
Special values include:
+
    * `\_[networkInterface]_` - Addresses of a network interface, for example `\_en0_`
    * `\_local_` - Any loopback address on the system, for example `127.0.0.1`
    * `\_site_` - Any site-local addresses on the system, for example `192.168.0.1`.
    * `\_global_` - Any globally-scoped addresses on the system, for example `8.8.8.8`.
+
The following is an example to bind to `localhost` as well as any site local addresses on the system such at `192.168.1.42`.
+
[quote]
`fusionauth-search.hosts=\_local_,\_site_`

[field]#fusionauth-search.servers# [type]#[String]# [default]#defaults to `localhost:9020`#::
A comma separated list of stand-alone search engine servers that will be used by FusionAuth. The port specified on the server should be the
Search Engine Transport port, not the HTTP port.
+
The following is an example of a configuration for two separate search engines, one running on localhost and the other is on remote system.
+
[quote]
`fusionauth-search.servers=localhost:9020,search2.example.com:9020`
+
This configuration value is used by the FusionAuth Search and the FusionAuth App services. Even when running FusionAuth App without
FusionAuth Search on the same server this configuration value will need to be provided.

[field]#fusionauth-search.data-directory# [type]#[String (Path)]#::
The location on disk where FusionAuth Search will store its data. This value is defaulted if not specified and generally should not be modified.

[field]#fusionauth-app.cookie-same-site-policy# [type]#[String]# [since]#Available since 1.16.0#::
include::docs/v1/tech/reference/_property-cookie-same-site-policy.adoc[]

[field]#fusionauth-app.public-url# [type]#[String]# [deprecated]#Deprecated#::
The FusionAuth App URL that is used to communicate with other FusionAuth nodes. This value is defaulted if not specified to use a localhost address or a site local if available. Unless you have multiple FusionAuth nodes the generated value should always work. You may need to manually specify this value if you have multiple FusionAuth nodes and the only way the nodes can communicate is on a public network.
+
Once available use `fusionauth-app.url` instead.

[field]#fusionauth-app.reindex-batch-size# [type]#[Integer]# [default]#defaults to `1000`#::
The number of users to process per batch for a reindex operation.

[field]#fusionauth-app.reindex-thread-count# [type]#[Integer]# [default]#defaults to `2`#::
The number of threads to process batches of users on for a reindex operation.

[field]#fusionauth-app.search-engine-type# [type]#[String]# [default]#defaults to `database`# [since]#Available since 1.16.0#::
include::docs/v1/tech/reference/_property-search-engine-type.adoc[]

[field]#fusionauth-app.search-servers# [type]#[String]# [default]#defaults to `http://localhost:9021`#::
include::docs/v1/tech/reference/_property-search-servers.adoc[]

[field]#fusionauth-app.management-port# [type]#[Integer]# [default]#defaults to `9010`#::
include::docs/v1/tech/reference/_property-management-port.adoc[]

[field]#fusionauth-app.http-port# [type]#[Integer]# [default]#defaults to `9011`#::
include::docs/v1/tech/reference/_property-http-port.adoc[]

[field]#fusionauth-app.https-port# [type]#[Integer]# [default]#defaults to `9013`#::
include::docs/v1/tech/reference/_property-https-port.adoc[]

[field]#fusionauth-app.ajp-port# [type]#[Integer]# [default]#defaults to `9019`#::
include::docs/v1/tech/reference/_property-ajp-port.adoc[]

[field]#fusionauth-app.memory# [type]#[String]# [default]#defaults to `512M`#::
include::docs/v1/tech/reference/_property-memory.adoc[]

[field]#fusionauth-app.additional-java-args# [type]#[String]#::
include::docs/v1/tech/reference/_property-additional-jvm-args.adoc[]

[field]#fusionauth-app.url# [type]#[String]# [since]#Available since 1.4.0#::
include::docs/v1/tech/reference/_property-url.adoc[]

[field]#fusionauth-app.http-max-header-size# [type]#[Integer]# [default]#Defaults to `8192`# [since]#Available since 1.17.0#::
include::docs/v1/tech/reference/_property-max-http-header-size.adoc[]

==== Environment Variables

Environment variables specified with an [note]#overrides# tag below will override the related property defined in the `fusionauth.properties` configuration file.
These environment variables will be honored when they are provided to an environment running the `fusionauth-app` package.

[.api]
[field]#DATABASE_URL# [overrides]#overrides# [field]#database.url# [optional]#Optional#::
include::docs/v1/tech/reference/_property-database-url.adoc[]

[field]#DATABASE_ROOT_USER# [optional]#Optional#::
The database root user that is used to create the FusionAuth schema and FusionAuth user.
+
Once FusionAuth is configured and running this value is no longer used and is never persisted.

[field]#DATABASE_ROOT_PASSWORD# [optional]#Optional#::
The database root password that is used to create the FusionAuth schema and FusionAuth user. It is recommended to leave the value of this variable empty as it is shown in the example. Using this configuration, the value will be picked up from the host environment. To use the value in this way, be sure to set this named environment value before calling `docker-compose up`.
+
Once FusionAuth is configured and running this value is no longer used and is never persisted.

[field]#DATABASE_USER# [overrides]#overrides# [field]#database.username# [optional]#Optional# [default]#Defaults to `fusionauth`#::
include::docs/v1/tech/reference/_property-database-username.adoc[]

[field]#DATABASE_PASSWORD# [overrides]#overrides# [field]#database.password# [optional]#Optional# [default]#Defaults to `fusionauth`#::
include::docs/v1/tech/reference/_property-database-password.adoc[]

[field]#FUSIONAUTH_ADDITIONAL_JAVA_ARGS# [overrides]#overrides# [field]#fusionauth-app.additional-java-args# [optional]#Optional#::
include::docs/v1/tech/reference/_property-additional-jvm-args.adoc[]

[field]#FUSIONAUTH_AJP_PORT# [overrides]#overrides# [field]#fusionauth-app.ajp-port# [optional]#Optional# [default]#defaults to `9019`#::
include::docs/v1/tech/reference/_property-ajp-port.adoc[]

[field]#FUSIONAUTH_COOKIE_SAME_SITE_POLICY# [overrides]#overrides# [field]#fusionauth-app.cookie-same-site-policy# [optional]#Optional# [since]#Available since 1.16.0#::
include::docs/v1/tech/reference/_property-cookie-same-site-policy.adoc[]

[field]#FUSIONAUTH_HTTP_PORT# [overrides]#overrides# [field]#fusionauth-app.http-port# [optional]#Optional# [default]#defaults to `9011`#::
include::docs/v1/tech/reference/_property-http-port.adoc[]

[field]#FUSIONAUTH_HTTPS_PORT# [overrides]#overrides# [field]#fusionauth-app.https-port# [optional]#Optional# [default]#defaults to `9013`#::
include::docs/v1/tech/reference/_property-https-port.adoc[]

[field]#FUSIONAUTH_MEMORY# [overrides]#overrides# [field]#fusionauth-app.memory# [optional]#Optional# [default]#defaults to `512M`#::
include::docs/v1/tech/reference/_property-memory.adoc[]

[field]#FUSIONAUTH_MANAGEMENT_PORT# [overrides]#overrides# [field]#fusionauth-app.management-port# [optional]#Optional# [default]#defaults to `9010`#::
include::docs/v1/tech/reference/_property-management-port.adoc[]

[field]#FUSIONAUTH_RUNTIME_MODE# [overrides]#overrides# [field]#fusionauth.runtime-mode# [optional]#Optional# [default]#defaults to `development`# [since]#Available since 1.16.0#::
include::docs/v1/tech/reference/_property-runtime-mode.adoc[]

[field]#FUSIONAUTH_SEARCH_ENGINE_TYPE# [overrides]#overrides# [field]#fusionauth-app.search-engine-type# [optional]#Optional# [defaults]#defaults to `database`#::
include::docs/v1/tech/reference/_property-search-engine-type.adoc[]

[field]#FUSIONAUTH_SEARCH_SERVERS# [overrides]#overrides# [field]#fusionauth-app.search-servers# [optional]#Optional# [default]#defaults to `http://localhost:9021`#::
include::docs/v1/tech/reference/_property-search-servers.adoc[]

[field]#FUSIONAUTH_URL# [overrides]#overrides# [field]#fusionauth-app.url# [optional]#Optional# [since]#Available since 1.4.0#::
include::docs/v1/tech/reference/_property-url.adoc[]

[field]#FUSIONAUTH_HTTP_MAX_HEADER_SIZE# [overrides]#overrides# [field]#fusionauth-app.http-max-header-size# [optional]#Optional# [since]#Available since 1.17.0#::
include::docs/v1/tech/reference/_property-max-http-header-size.adoc[]

==== Silent Configuration
All of the environment variables are optional, if not provided a default will be utilized. If you wish to perform a silent configuration which means you will not stop in maintenance mode to configure the database or search engine, you must provide the following environment variables:

* `DATABASE_URL`
* `DATABASE_ROOT_USER`

If `FUSIONAUTH_SEARCH_ENGINE_TYPE` is set to `elasticsearch` you will also need to provide the `FUSIONAUTH_SEARCH_SERVERS` environment variable in order to bypass maintenance mode.

When configured correctly these variables will allow FusionAuth to silently configure itself and go directly to the setup wizard. If they are omitted, FusionAuth will start up in Maintenance mode and require you to interactively configure the database and search engine.
