---
layout: doc
title: Hosted Login Pages Cookies
description: A list of cookies set by the FusionAuth Hosted Login pages
navcategory: admin
---

== Overview

Cookies are a critical part of web applications, and FusionAuth sets cookies. When you call certain APIs, such as the Login API, cookies may be set. These cookies are specified in the link:/docs/v1/tech/apis[API documentation].

When you use the link:/docs/v1/tech/core-concepts/integration-points#hosted-login-pages[hosted login pages], FusionAuth sets cookies to enable functionality.

[WARNING.warning]
====
Cookies set by the hosted login pages are displayed here for informational purposes only.

Duration, name, and purpose are subject to change.
====

When a cookie is described as a prefix, the name is used as a prefix for one or more cookies.


== Domains

The domain of all cookies is limited to the domain on which the FusionAuth instance is running. You can control the domain FusionAuth uses by link:/docs/v1/tech/admin-guide/proxy-setup[setting up a proxy].

In other words, if FusionAuth lives at `auth.piedpiper.com`, it will only set cookies for that domain. It will never set cookies for `.piedpiper.com`.

== Cookie List

//Pulled from Cookies.java

.Hosted Login Page Cookies 
[cols="2,1,1,3"]
|===
| Name | Prefix | Duration | Function

| fusionauth.csrf
| No
| Session
| Protects against Cross Site Request Forgery.

| fusionauth.flash-message
| No
| Session
| Used to display information or error messages to a user.

| fusionauth.known-device
| Yes
| 70 Years
| Determines if this device is known or not.

| fusionauth.locale
| No
| 70 Years
| The locale of the user if specified.

| fusionauth.app.pkce-verifier
| No
| 70 Years
| Used to implement security measures around login.

| fusionauth.pkce-verifier
| No
| Session
| Used to implement security measures around login.

| fusionauth.remember-device
| No
| 70 years
| Indicates whether the user wants to remain logged in.

| fusionauth.session
| No
| ??
| ?? TODO

| fusionauth.sso
| No
| 70 Years
| Used to implement single sign-on functionality.

| fusionauth.timezone
| No
| Session
| The timezone of the user.

| fusionauth.trusted-device
| Yes
| 70 Years
| Used to implement security functionality.

| fusionauth.trust_c
| No
| 70 Years
| Used to implement security functionality.

| fusionauth.trust_t
| No
| 70 Years
| Used to implement security functionality.

| fusionauth.trust
| No
| 70 Years
| Used to implement security functionality.

| prime-mvc-saved-request
| No
| Session
| Used to implement login functionality.

|===

//any other prime mvc cookies? 

