---
layout: doc
title: Hosted Login Pages Cookies
description: A list of cookies set by the FusionAuth Hosted Login pages
navcategory: admin
---

== Overview

Cookies are a critical part of web applications, and FusionAuth sets cookies. When you call certain APIs, such as the Login API, cookies may be set. These cookies are specified in the link:/docs/v1/tech/apis[API documentation].

When you use the link:/docs/v1/tech/core-concepts/integration-points#hosted-login-pages[hosted login pages], FusionAuth sets cookies to enable functionality.

== Domains

The domain of all cookies is limited to the domain on which the FusionAuth instance is running. You can control the domain FusionAuth uses by link:/docs/v1/tech/admin-guide/proxy-setup[setting up a proxy].

In other words, if FusionAuth lives at `auth.piedpiper.com`, it will only set cookies for that domain. It will never set cookies for `.piedpiper.com`.

== Cookie List

[WARNING.warning]
====
Cookies set by the hosted login pages are displayed here for informational purposes only. Name, type and description of each cookie are subject to change.
====

//Pulled from Cookies.java

.Hosted Login Page Cookies 
[cols="2,1,3"]
|===
| Name | Type | Description

| `fusionauth.flash-message`
| Request
| Used to display message across requests.

| `fusionauth.known-device.*`
| Persistent
| Identifies a device known to FusionAuth. More than one cookie may be set.

| `fusionauth.locale`
| Persistent
| The locale used to localize the themed pages.

| `fusionauth.pkce-verifier`
| Request
| Used to support Proof Key for Code Exchange during login.

| `fusionauth.remember-device`
| Persistent
| Records if the user wants to remain logged in on this device.

| `fusionauth.sso`
| Persistent
| Represents a single sign-on session.

| `fusionauth.timezone`
| Persistent
| The configured or approximated timezone used to adjust dates and times for display.

| `fusionauth.trusted-device.*`
| Persistent
| Identifies a trusted device. More than one cookie may be set.

| `fusionauth.trust_c`
| Request
| Implements security functionality.

| `fusionauth.trust_t`
| Request
| Implements security functionality.

| `fusionauth.trust`
| Persistent
| Allows a 2FA challenge to be bypassed during login.

|===
