---
layout: doc
title: Hosted Login Pages Cookies
description: A list of cookies set by the FusionAuth Hosted Login pages
navcategory: admin
---

== Overview

Cookies are a critical part of web applications, and FusionAuth sets cookies. When you call certain APIs, such as the Login API, cookies may be set. These cookies are specified in the link:/docs/v1/tech/apis[API documentation].

When you use the link:/docs/v1/tech/core-concepts/integration-points#hosted-login-pages[hosted login pages], FusionAuth sets cookies to enable functionality.

== Domains

The domain of all cookies is limited to the domain on which the FusionAuth instance is running. You can control the domain FusionAuth uses by link:/docs/v1/tech/admin-guide/proxy-setup[setting up a proxy].

In other words, if FusionAuth lives at `auth.piedpiper.com`, it will only set cookies for that domain. It will never set cookies for `.piedpiper.com`.

== Cookie List

[WARNING.warning]
====
Cookies set by the hosted login pages are displayed here for informational purposes only.

Name, type and purpose of each cookie are subject to change.
====

//Pulled from Cookies.java

.Hosted Login Page Cookies 
[cols="2,1,1,3"]
|===
| Name | Type | Purpose

| fusionauth.flash-message
| Request
| Displays information or error messages.

| fusionauth.known-device
| Persistent
| Determines if this device is known.

| fusionauth.locale
| Persistent
| The locale used to localize the themed pages.

| fusionauth.pkce-verifier
| Request
| Used to support Proof Key for Code Exchange during login.

| fusionauth.remember-device
| Persistent
| Records if the user wants to remain logged in on this device.

| fusionauth.sso
| Persistent
| Implements single sign-on functionality.

| fusionauth.timezone
| Persistent
| The configured or approximated timezone used to adjust dates and times for display.

| fusionauth.trusted-device.{generated}
| Persistent
| Implements security functionality.

| fusionauth.trust_c
| Request
| Implements security functionality.

| fusionauth.trust_t
| Request
| Implements security functionality.

| fusionauth.trust
| Persistent
| Implements security functionality.

|===
