---
layout: doc
title: Limitations
description: FusionAuth built in limitations
navcategory: admin
---

== Overview

FusionAuth has the following known limits.

* <<User Searches>>
* <<Field Lengths>>
* <<API Keys>>
* <<Minimum Key Lengths>>
* <<Updating Keys>>
* <<Default Configuration>>
* <<OAuth Logout Behavior>>
* <<SAML>>
* <<Identifiers>>
** <<User Identifiers>>
** <<Client Ids>>
* <<Data Type Changes In 'data' Fields>>
* <<TOTP Algorithm Implementation>>
* <<Multi-Tenancy>>
* <<System Upgrade Downtime>>
* <<Database Configuration>>
* <<Password Hashes>>
* <<SCIM>>
* <<Email Templates>>
* link:#whats-not-limited[What's Not Limited]

== User Searches

include::docs/v1/tech/shared/_user-search-limits.adoc[]

=== Maximum Users Returned Workarounds

include::docs/v1/tech/shared/_user-search-limits-workarounds.adoc[]

== Field Lengths

FusionAuth stores most data in a database. Lengths of specific fields are documented in the database schema for your database type. Please link:/direct-download[download the database schema for your version of FusionAuth] to review length limits for a particular column.

Many varchar columns have a length of 191. Why 191? In MySQL when using a `utf8mb4` (4 byte character set) on an indexed column, MySQL limits the usable characters to 191 to account for the overhead of the 4 byte addressing. The InnoDB MySQL engine has a max index length of 767 bytes (for mysql 5.7.9, the earliest version of MySQL which link:/docs/v1/tech/installation-guide/system-requirements[Fusionauth supports]). Because we are using `utf8mb4` which allows up to 4 bytes per character, we end up with 767/4 ~ 191, so we set the column length to that.

== API Keys

FusionAuth is API first and everything can be managed by an API. You can create an API key in the following ways:

* Using the link:/docs/v1/tech/apis/api-keys[API Key API], if you are using version 1.26 or greater.
* Use the administrative user interface.
* link:/docs/v1/tech/installation-guide/kickstart[Kickstart] which only works on fresh installations.

== Minimum Key Lengths

You can use FusionAuth to manage your cryptographic keys. Due to security considerations, FusionAuth won't import keys below a certain length.

For RSA keys used to verify signatures, the minimum length is 1024. This key length is allowed as of FusionAuth 1.23.4 and supports external systems that rely upon this weak key length.

For RSA keys used for signing or any other purpose, the minimum length is 2048. 

For ECC keys, the minimum length is 256.

See the link:/docs/v1/tech/apis/keys[Keys API] for more, including supported algorithms and lengths.

== Updating Keys

FusionAuth can manage keys, secrets, and certificates, using link:/docs/v1/tech/core-concepts/key-master[Key Master]. You can update a Key managed by FusionAuth, with some limits.

include::docs/v1/tech/apis/_update-key-note.adoc[]

== Default Configuration

There are a number of items in FusionAuth created by default and which cannot be removed. Additionally, there are sometimes limits to modifying them. These defaults include:

include::docs/v1/tech/shared/_default-entities.adoc[]

== OAuth Logout Behavior

include::docs/v1/tech/oauth/_logout-behavior-all-applications.adoc[]

== SAML

=== IdP Limitations

include::docs/v1/tech/samlv2/_saml-idp-limitations.adoc[]

=== SP Limitations

include::docs/v1/tech/identity-providers/samlv2/_saml-sp-limitations.adoc[]

== Identifiers

Identifiers (Ids) in FusionAuth are link:/docs/v1/tech/reference/data-types#uuids[UUIDs].

If you are creating an object, such as an Application, with the FusionAuth API, you can specify this Id, as long as it is a valid UUID. The ability to choose specific Ids exists for Users, Applications, and Tenants, among others, and allows you to avoid breaking external systems dependent on existing identifiers.

Ids cannot be modified after the object is created. If you need to change an identifier, delete the object and recreate it with the correct Id.

=== User Identifiers

Each account must have an identifier, either an email address or a username. Users may not have multiple email addresses. See https://github.com/fusionauth/fusionauth-issues/issues/1[this issue for more information].

An account may have both a username and an email address.

=== Client Ids

OAuth has the concept of a `client_id`. In FusionAuth, `client_id`s cannot be modified after creation. As mentioned above, during creation, an Id can be set to any valid, unique UUID value.

A `client_id` is always the same as the Application Id or an Entity Id.

== Data Type Changes In 'data' Fields
[[data-field-limitations]]

include::docs/v1/tech/shared/_data_field_data_type_changes.adoc[]

== TOTP Algorithm Implementation

include::docs/v1/tech/apis/_two-factor-totp-limits.adoc[]

== Multi-Tenancy

include::docs/v1/tech/guides/_multi-tenant-limitations.adoc[]

== System Upgrade Downtime

include::docs/v1/tech/installation-guide/_downtime-upgrade-limitation.adoc[]

== Database Configuration

include::docs/v1/tech/reference/_configuration-limits.adoc[]

== Password Hashes

There is no FusionAuth API allowing user password hashes to be exported.

If you need to migrate hashes from FusionAuth to any other system, use a database export.

== SCIM

include::docs/v1/tech/shared/_scim-limits.adoc[]

== Email Templates

include::docs/v1/tech/email-templates/_template-content-limits.adoc[]

== What's Not Limited

All other objects and configuration, including but not limited to the following, are limited only by the resources of your system:

* Users
* Applications
* Tenants
* Roles
* Groups
* Identity Providers such as SAML or OIDC connections
* API keys to allow for programmatic configuration of and interaction with FusionAuth
* The number of email templates
* Supported languages/locales
* Signing and verifying keys
* MFA methods per user

