---
layout: doc
title: Limitations
description: FusionAuth built in limitations
---

FusionAuth has the following known limits.

== User Identifiers

Each account must have a user identifier, either an email address or a username. Users may not have multiple email addresses. See https://github.com/fusionauth/fusionauth-issues/issues/1[this issue for more information].

== User Searches

When using the Elasticsearch search engine, the maximum number of users returned for any search is 10,000 users. There is an https://github.com/FusionAuth/fusionauth-issues/issues/494[open bug] tracking this issue.

=== Workarounds

You can work around this limit by writing one or more search queries to return less than 10,000 users. 

For example, if you needed to pull all of your users, you could query for users with an email address starting with `A`, then starting with `B`, and so on.

You can also run your query directly against Elasticsearch.

== Field Lengths

FusionAuth stores most data in a database. Lengths of specific fields are documented in the database schema for your database type. Please link:/direct-download/[download the database schema for your version of FusionAuth] to review length limits for a particular column.

Many varchar columns have a length of 191. Why 191? In MySQL when using a `utf8mb4` (4 byte character set) on an indexed column, MySQL limits the usable characters to 191 to account for the overhead of the 4 byte addressing. The InnoDB MySQL engine has a max index length of 767 bytes (for mysql 5.7.9, the earliest version of MySQL which link:/docs/v1/tech/installation-guide/system-requirements/[Fusionauth supports]). Because we are using `utf8mb4` which allows up to 4 bytes per character, we end up with 767/4 ~ 191, so we set the column length to that.

== API Keys

FusionAuth is API first and every entity can be managed by an API, with one exception: API keys cannot be created or managed via the API.

The only ways to create an API key are:

* Use the administrative user interface
* link:/docs/v1/tech/installation-guide/kickstart[Kickstart] which only works on fresh installations.

However, there is an open GitHub issue to create an https://github.com/FusionAuth/fusionauth-issues/issues/887[API key management API].

== Minimum Key Lengths

You can use FusionAuth to manage your keys. Due to security considerations, FusionAuth won't import keys below a certain length.

For RSA keys, the minimum length is 2048.

For ECC keys, the minimum length is 256.

See the link:/docs/v1/tech/apis/keys/[Keys API] for more, including supported algorithms and lengths.

== Default Entities

There are a number of default entities which cannot be removed. Additionally, there are limits to modifying these entities.

This includes:

* The Default tenant
* The FusionAuth application, which resides in the Default tenant
* The Default theme, which is read only
* The FusionAuth application roles, which may be assigned to users, but are immutable

== SAML

include::docs/v1/tech/samlv2/_saml_limitations.adoc[]

== Identifiers

Identifiers (Ids) for entities in FusionAuth are link:/docs/v1/tech/reference/data-types/#uuids[UUIDs].

If you are creating an entity, such as an application, with the FusionAuth API, you can specify this Id, as long as it is a valid UUID. This works for users, applications, and tenants, among others, and makes it possible to avoid breaking external systems dependent on existing identifiers.

== Data Type Changes In 'data' fields

FusionAuth provides `data` fields on the `user` and `registration` objects. 

You should not modify the data type of fields stored in `data` over time. 

For example, if you create a field called `user.data.migrated` and store a boolean value in it, if you later set that field to a string value for any user, subsequent user searches will fail.

`data` fields are indexed by Elasticsearch, if you are using the Elasticsearch search engine. Elasticsearch requires fields to have the same data type across all indexed objects. In the example above, once Elasticsearch sees that `user.data.migrated` is a boolean, it expects that field, if present, to be a boolean on all users.

This limitation applies only to installations using the Elasticsearch search engine. However, if you start with the database search engine and eventually need to switch to the Elasticsearch search engine, you will not be able to do so if you have not enforced consistency in the `data` field types.

== What's Not Limited

All other entities, including but not limited to the following, are limited only by the resources of your system:

* Users
* Applications
* Tenants
* Roles
* Groups
