---
layout: doc
title: Limitations
description: FusionAuth built in limitations
---

== Overview

FusionAuth has the following known limits.

* <<User Identifiers>>
* <<User Searches>>
** <<Workarounds>>
* <<Field Lengths>>
* <<API Keys>>
* <<Minimum Key Lengths>>
* <<Default Configuration>>
* <<SAML>>
* <<Identifiers>>
* <<Data Type Changes In 'data' Fields>>
* <<TOTP Algorithm Implementation>>
* <<Multi-Tenancy>>
* <<System Upgrade Downtime>>
* link:#whats-not-limited[What's Not Limited]

== User Identifiers

Each account must have a user identifier, either an email address or a username. Users may not have multiple email addresses. See https://github.com/fusionauth/fusionauth-issues/issues/1[this issue for more information].

== User Searches

When using the Elasticsearch search engine, the maximum number of users returned for any search is 10,000 users. There is an https://github.com/FusionAuth/fusionauth-issues/issues/494[open bug] tracking this issue.

=== Workarounds

You can work around this limit by writing one or more search queries to return less than 10,000 users. 

For example, if you needed to download all users, you could query for users with an email address starting with `A`, then starting with `B`, and so on. Here's a https://github.com/FusionAuth/fusionauth-example-full-user-search[sample shell script which retrieves all users] using this strategy.

You may also run your query directly against Elasticsearch. The Elasticsearch query result will return Elasticsearch document Ids. Each document Id corresponds to a FusionAuth user Id. To retrieve user data, which is most likely what you are after, use the link:/docs/v1/tech/apis/users/#search-for-users[User Search API] with one or more user Ids.

== Field Lengths

FusionAuth stores most data in a database. Lengths of specific fields are documented in the database schema for your database type. Please link:/direct-download/[download the database schema for your version of FusionAuth] to review length limits for a particular column.

Many varchar columns have a length of 191. Why 191? In MySQL when using a `utf8mb4` (4 byte character set) on an indexed column, MySQL limits the usable characters to 191 to account for the overhead of the 4 byte addressing. The InnoDB MySQL engine has a max index length of 767 bytes (for mysql 5.7.9, the earliest version of MySQL which link:/docs/v1/tech/installation-guide/system-requirements/[Fusionauth supports]). Because we are using `utf8mb4` which allows up to 4 bytes per character, we end up with 767/4 ~ 191, so we set the column length to that.

== API Keys

FusionAuth is API first and every entity can be managed by an API. You can create an API key in the following ways:

* Using the link:/docs/v1/tech/apis/api-keys/[API Key API], if you are using version 1.26 or greater.
* Use the administrative user interface.
* link:/docs/v1/tech/installation-guide/kickstart[Kickstart] which only works on fresh installations.

== Minimum Key Lengths

You can use FusionAuth to manage your cryptographic keys. Due to security considerations, FusionAuth won't import keys below a certain length.

For RSA keys used to verify signatures, the minimum length is 1024. This key length is allowed as of FusionAuth 1.23.4 and supports external systems that rely upon this weak key length.

For RSA keys used for signing or any other purpose, the minimum length is 2048. 

For ECC keys, the minimum length is 256.

See the link:/docs/v1/tech/apis/keys/[Keys API] for more, including supported algorithms and lengths.

== Default Configuration

There are a number of items in FusionAuth created by default and which cannot be removed. Additionally, there are sometimes limits to modifying them. These defaults include:

include::docs/v1/tech/shared/_default-entities.adoc[]

== SAML

=== IdP Limitations

include::docs/v1/tech/samlv2/_saml-idp-limitations.adoc[]

=== SP Limitations

include::docs/v1/tech/identity-providers/samlv2/_saml-sp-limitations.adoc[]

== Identifiers

Identifiers (Ids) for entities in FusionAuth are link:/docs/v1/tech/reference/data-types/#uuids[UUIDs].

If you are creating an entity, such as an application, with the FusionAuth API, you can specify this Id, as long as it is a valid UUID. This works for users, applications, and tenants, among others, and makes it possible to avoid breaking external systems dependent on existing identifiers.

== Data Type Changes In 'data' Fields
[[data-field-limitations]]

include::docs/v1/tech/shared/_data_field_data_type_changes.adoc[]

== TOTP Algorithm Implementation

include::docs/v1/tech/apis/_two-factor-totp-limits.adoc[]

== Multi-Tenancy

include::docs/v1/tech/guides/_multi-tenant-limitations.adoc[]

== System Upgrade Downtime

include::docs/v1/tech/installation-guide/_downtime-upgrade-limitation.adoc[]

== What's Not Limited

All other entities, including but not limited to the following, are limited only by the resources of your system:

* Users
* Applications
* Tenants
* Roles
* Groups
* Identity Providers such as SAML or OIDC connections
* API keys to allow for programmatic configuration of and interaction with FusionAuth
* Supported languages/locales
* Signing and verifying keys
* Number of MFA methods per user
