---
layout: doc
title: Limitations
description: FusionAuth built in limitations
---

FusionAuth has the following known limits.

=== User searches

When using the Elasticsearch search engine, the maximum number of users returned for any search is 10,000 users. There is an https://github.com/FusionAuth/fusionauth-issues/issues/494[open bug] tracking this issue.

==== Workarounds

You can work around this limit by writing one or more search queries to return less than 10,000 users. 

For example, if you needed to pull all of your users, you could query for users with an email address starting with `A`, then starting with `B`, and so on.

=== Field lengths

FusionAuth stores most data in a database. Lengths of specific fields are documented in the database schema for your database type. Please link:/direct-download[download the database schema for your version of FusionAuth] to review length limits for a particular column.

Many varchar columns have a length of 191. Why 191? In MySQL when using a `utf8mb4` (4 byte character set) on an indexed column, MySQL limits the usable characters to 191 to account for the overhead of the 4 byte addressing. 

=== What's not limited

All other entities, including but not limited to the following, are limited only by the resources of your system:

* Users
* Applications
* Tenants
* Roles
* Groups
