---
layout: doc
title: Release Notes
description: Release notes for each version of FusionAuth
---

:sectnumlevels: 0

////
Hide stuff inside these lines
////

[role=release-note]

== Version Next
_Pending Release_

=== Fixed
* Calling the link:../oauth/endpoints#introspect[Introspect] endpoint with a JWT returned from the Issue API may fail due to the missing `aud` claim.

[role=release-note]

== Version 1.2.2
_November 27th, 2018_

=== Fixed
* Add `X-FusionAuth-TenantId` to allowed CORS headers.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/44[GitHub Issue #44 CORS blocks API request containing X-FusionAuth-TenantId]
* When FusionAuth is running behind a proxy such as an AWS ALB / ELB the redirect URI required to complete login may not be resolved correctly. This may cause the redirect back to the FusionAuth UI login to fail with a CSRF exception. If you encounter this issue you may see an error message that says `Something doesn't seem right. You have been logged out of FusionAuth`. The work-around for this issue if you encounter it will be to perform the redirect from HTTP to HTTPS in your load balancer.
* Some minor usability issues in the Identity Provider configuration UI.

[role=release-note]

== Version 1.2.1
_November 16th, 2018_

=== Enhancement
* Better error handling when an API caller sends invalid JSON messages. Prior to this enhancement if FusionAuth did not provide a specific error message for a particular field a `500` HTTP status code was returned if the JSON could not be parsed properly. This enhancement will ensure that sending a FusionAuth API invalid JSON will consistently result in a `400` status code with a JSON body describing the error.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/17[GitHub Issue #17 Malformed or invalid JSON causes 500 error]
* Allow an Identity Provider to be enabled and disabled from the UI. You may still choose to enable or disable a specific Application for use with an Identity Provider, but with this enhancement you may not turn off an Identity Provider for all Applications with one switch.

=== Fixed
* Preserve Application Identity Provider configuration for disabled Applications when editing a Identity Provider from the UI.


== Version 1.2.0
_November 15th, 2018_

=== New
* Add TTL configuration for Refresh Tokens to the Application configuration. When you enable JWT configuration per Application this value will override the global setting.

=== Fixed
* An error in the Twitter OAuth v1 workflow has been resolved.

[role=release-note]

== Version 1.1.1
_November 13th, 2018_

=== Fixed
* If you were to have an Identity Provider for federated third party JSON Web Tokens configured prior to upgrading to `1.1.0` FusionAuth may fail during the database migration to version `1.1.0`.

== Version 1.1.0
_November 13th, 2018_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]

=== New
* Social login support
** link:../apis/identity-providers/facebook[Facebook] Identity Provider
** link:../apis/identity-providers/google[Google] Identity Provider
** link:../apis/identity-providers/twitter[Twitter] Identity Provider
** link:../apis/identity-providers/openid-connect[OpenID Connect] Identity Provider
* Full theme support for login. See the link:../tutorials/login-theme[Login Theme] tutorial for additional information and examples.
* Better localization support in the FusionAuth UI. You now have the option to set or modify your preferred language for use in the FusionAuth UI.
Providing a preferred language will cause dates to be formatted based upon your preference. For example, the default data format is `M/D/YYYY`, but
if you are not in the United States this may not be the way you expect a date to be formatted. If you set your locale to `French` you will now
see a more appropriate format of `D/M/YYYY`. This value is stored on the User Registration for FusionAuth in the `preferredLanguages` field.

=== Enhancement
* When viewing sessions (refresh tokens) on the Manage User panel, the start and expiration times will be displayed.

[role=release-note]

== Version 1.0.18
_October 29th, 2018_

=== Fixed
* If FusionAuth starts up in maintenance mode and stays there for an extended period of time without the User completing the configuration from the web browser, FusionAuth may get stuck in maintenance mode. If you encounter this issue, where you seemingly are entering the correct credentials on the Database configuration page and are unable to continue, restart FusionAuth and the issue will be resolved.

[role=release-note]

== Version 1.0.17
_October 5th, 2018_

=== Fixed
* When running in Docker Compose, FusionAuth cannot connect to the search service when trying to exit the setup wizard.
** https://github.com/FusionAuth/fusionauth-containers/issues/2

[role=release-note]

== Version 1.0.16
_October 5th, 2018_

=== Enhancement
* Better support for running in Docker. Enhanced silent configuration capability for database and search engine boot strap configuration in Docker Compose to be more resilient.

=== Fixed
* If custom data is added to an Application, Group or Tenant before editing the corresponding object in the UI, the custom data may be lost.

[role=release-note]

== Version 1.0.15
_October 1st, 2018_

=== New
* Better support for running in Docker. Configuration can be override using environment variables. See link:../installation-guide/docker[Docker Install] for additional information.

=== Fixed
* The first time a user reached the failed login threshold and a `409` response code was returned the response body was empty. Subsequent login requests correctly returned the JSON response body with the `409`, now the JSON response body is correctly returned the first time the user reaches the failed login threshold.


[role=release-note]

== Version 1.0.14
_September 17th, 2018_

=== Fixed
* When using PostgreSQL an exception may occur during an internal cache reload request. If you encounter this issue you will see a stack trace in the `fusionauth-app.log`. If you see this error and need assistance, please open an issue in the FusionAuth https://github.com/FusionAuth/fusionauth-issues[Issues] GitHub project.

[.code]
____
`Unexpected error. We're missing an internal API key to notify distributed caches.`
____


[role=release-note]

== Version 1.0.13
_September 12th, 2018_

=== New
* General availability release
