---
layout: doc
title: Release Notes
description: Release notes for each version of FusionAuth
---

:sectnumlevels: 0

////
Hide stuff inside these lines
////

[role=release-note]

== Version 1.1.0
_Pending Release_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]

=== New
* Facebook Login Provider
* Google Login Provider
* Twitter Login Provider
* Generic OpenID Connect Login Provider
* Full theme support for login

=== Enhanced
* When viewing sessions (refresh tokens) on the Manage User panel, the start and expiration times will be displayed.

[role=release-note]

== Version 1.0.18
_October 29th, 2018_

=== Fixed
* If FusionAuth starts up in maintenance mode and stays there for an extended period of time without the User completing the configuration from the web browser, FusionAuth may get stuck in maintenance mode. If you encounter this issue, where you seemingly are entering the correct credentials on the Database configuration page and are unable to continue, restart FusionAuth and the issue will be resolved.

[role=release-note]

== Version 1.0.17
_October 5th, 2018_

=== Fixed
* When running in Docker Compose, FusionAuth cannot connect to the search service when trying to exit the setup wizard.
** https://github.com/FusionAuth/fusionauth-containers/issues/2

[role=release-note]

== Version 1.0.16
_October 5th, 2018_

=== Enhanced
* Better support for running in Docker. Enhanced silent configuration capability for database and search engine boot strap configuration in Docker Compose to be more resilient.

=== Fixed
* If custom data is added to an Application, Group or Tenant before editing the corresponding object in the UI, the custom data may be lost.

[role=release-note]

== Version 1.0.15
_October 1st, 2018_

=== New
* Better support for running in Docker. Configuration can be override using environment variables. See link:../installation-guide/docker[Docker Install] for additional information.

=== Fixed
* The first time a user reached the failed login threshold and a `409` response code was returned the response body was empty. Subsequent login requests correctly returned the JSON response body with the `409`, now the JSON response body is correctly returned the first time the user reaches the failed login threshold.


[role=release-note]

== Version 1.0.14
_September 17th, 2018_

=== Fixed
* When using PostgreSQL an exception may occur during an internal cache reload request. If you encounter this issue you will see a stack trace in the `fusionauth-app.log`. If you see this error and need assistance, please open an issue in the FusionAuth https://github.com/FusionAuth/fusionauth-issues[Issues] GitHub project.

[.code]
____
`Unexpected error. We're missing an internal API key to notify distributed caches.`
____


[role=release-note]

== Version 1.0.13
_September 12th, 2018_

=== New
* General availability release
