---
layout: doc
title: Release Notes
description: Release notes for each version of FusionAuth
---

:sectnumlevels: 0

////
Hide stuff inside these lines
////

[role=release-note]

== Version 1.8.0 RC1
_September 8th, 2019_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]

:warning_message: This is a release candidate. This means the version is stable and should work for most cases. However, ue to the complexity of the database migration ensure you have adequately tested the upgrade prior to moving it into production. You may also wish to wait for the forthcoming full release of 1.8.0 before moving into production.
include::docs/v1/tech/release-notes/__general-migration-warning.adoc[]

=== Community MVPs

Thanks to all of our community members who take the time to open features, report bugs, assist others and help us improve FusionAuth! For this release we would like to thank the following GitHub users who helped us out!

* https://github.com/AlvMF1[@AlvMF1]
* https://github.com/colundrum[@colundrum]
* https://github.com/damienherve[@damienherve]
* https://github.com/davidmw[@davidmw]
* https://github.com/fabiojvalente[@fabiojvalente]
* https://github.com/flangfeldt[@flangfeldt]
* https://github.com/johnmaia[@johnmaia]
* https://github.com/petechungtuyco[@petechungtuyco]
* https://github.com/prabhakarreddy1234[@prabhakarreddy1234]
* https://github.com/snmed[@snmed]
* https://github.com/tombeany[@tombeany]
* https://github.com/unkis[@unkis]
* https://github.com/whiskerch[@whiskerch]
* https://github.com/zbruhnke[@zbruhnke]

{nbsp} +
{nbsp} +


=== Changes
* Most of the configuration previously available in the System Settings has been moved to the Tenant configuration to allow for additional flexibility. This is important if you will be utilizing more than one tenant, you may not configure password policies, email configuration, etc per tenant. If you are using the System Configuration or Tenant APIs, please be aware of this change and plan accordingly. If you were manually synchronizing these configurations between systems, you will need to update these processes.
** SMTP configuration
** Event configuration
** Password configuration
** Failed Authentication configuration
** Password configuration
** JWT configuration
** Theme

=== New
* Top level theme menu in FusionAuth UI. [breadcrumb]#Settings# icon:chevron-right[role=breadcrumb] [breadcrumb]#Themes#.
** Create, delete, edit and update themes
** Assign a named theme to a tenant
** Theme preview
* User modifiable link:../reference/cors[CORS configuration]
** https://github.com/FusionAuth/fusionauth-issues/issues/180[GitHub Feature #180 : Expose a CORS configuration to the end user]
* A public key may also be retrieved by `kid` in addition to the `applicationId` when using the link:../apis/jwt#retrieve-public-keys[Public Key API]. This resolves https://github.com/FusionAuth/fusionauth-issues/issues/227[GitHub Issue #227].
* PKCE support for use during the Implicit Grant
* New link:../events-webhooks/events#user-email-verified[User Email Verified] and link:../events-webhooks/events#user-registration-verified[User Registration Verified] events. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/163[GitHub Issue #163], thanks to https://github.com/unkis[@unkis], https://github.com/prabhakarreddy1234[@prabhakarreddy1234] and https://github.com/davidmw[@davidmw] for the great feedback!
* Email Verification, Registration Verification, Change Password, Setup Password and Passwordless Login can be be optionally configured to use codes made up of digits instead of long strings. This may be helpful if you wish the user to type in a code during an interactive workflow.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/269[GitHub Issue #269], thanks to https://github.com/zbruhnke[@zbruhnke] for helping us get this one delivered.

=== Fixed
* Tenant scoped SMTP configuration, password rules, event transactions, JWT signing configuration, etc.
* When viewing Refresh token expiration in the Manage User panel under the Sessions tab, the expiration may be displayed incorrectly if the Refresh Token Time to Live has been set at the Application level. The actual time to live was still correctly enforced, but this display may have been incorrect.
* In some cases an Id Token signed by FusionAuth may not be able to be verified if it is sent back to FusionAuth. This issue was introduced in version `1.6.0`.
* If the host operating system is not configured for `UTF-8` and you specify multi-byte characters in an email template subject, the subject text may not be rendered correctly when viewed by the recipient.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/231[GitHub Issue #231], thanks to https://stackoverflow.com/users/8266623/lechu67[@Lechu67] for reporting via https://stackoverflow.com/questions/57146832/[Stack Overflow] and helping to diagnose the issue.
* Toggle rendering issue in Firefox. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/260[GitHub issue #260], thanks to https://github.com/snmed[@snmed] for the assist!
* When creating users and applications programatically, due to a timing issue, you may receive an unexpected error indicating the Application does not exist. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/252[GitHub Issue $252], thanks to https://github.com/johnmaia[@johnmaia] for reporting the issue.
* An exception may occur when using the Login with Google feature if the `picture` claim returned is not a valid URI. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/249[GitHub Issue #249], thanks to https://github.com/damienherve[@damienherve] for reporting the issue.
* A tenant may fail to be deleted. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/221[GitHub Issue #221], thanks to https://github.com/johnmaia[@johnmaia] for the assist! If you encounter this issue, ensure the search index is updated, generally this will only happen if you programatically create users and then immediately attempt to delete a tenant.
* The relative link on the Change Password themed template to restart the Forgot Password workflow when the code has expired is broken. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/280[GitHub Issue #280], thanks to https://github.com/flangfeldt[@flangfeldt] for letting us know!
* The Import API may fail due to a false positive during password salt validation. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/272[GitHub Issue #272], thanks to https://github.com/tombeany[@tombeany] for reporting the issue.
* Modifying an Identity Provider configuration when an Application has been disabled may cause an error in the UI. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/245[GitHub Issue #245], thanks to https://github.com/fabiojvalente[@fabiojvalente] for reporting the issue.
* When the FusionAuth schema exists in the database and you reconnect FusionAuth using the database maintenance mode, depending upon the version of PostgreSQL we may not properly detect that the schema exists and return an error instead of continuing. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/237[GitHub Issue #237], thanks to https://github.com/whiskerch[@whiskerch] for reporting the issue.
* A typo in the Java FusionAuth client causes the to fail the `generateEmailVerificationId` request. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/282[GitHub Issue #282], thanks to https://github.com/petechungtuyco[@petechungtuyco] for reporting the issue and pointing out the solution!

=== Enhancement
* link:../events-webhooks/events#jwt-refresh-token-revoke[JWT Refresh Token Revoke] event will contain a User object when available
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/255[GitHub Issue #255], thanks to https://github.com/AlvMF1[@AlvMF1] for the great suggestion!
* In a themed template that may have the `passwordValidationRules` available after a password validation field error will now always have the `passwordValidationRules` available if you choose to display them. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/263[GitHub Issue #263], thanks to https://github.com/AlvMF1[@AlvMF1] for the suggestion!
* Updated PostgresSQL connector to support `SCRAM-SHA-256`. Thanks to https://github.com/colundrum[@colundrum] for letting us know and assisting in testing. Resolves https://github.com/FusionAuth/fusionauth-issues/issues/209[GitHub Issue #209]

[role=release-note]

== Version 1.7.4
_August 22th, 2019_

=== Fixed
* When configuring a SAML v2 IdP relying party using the FusionAuth SP metadata, the configured ACS may not work properly. If you encounter this issue you may manually modify the relying party configuration to change the ACS endpoint to `/oauth2/callback`.
** Resolves https://stackoverflow.com/questions/57607810/fusionauth-adfs-integration-issue[Stack Overflow : Fusionauth ADFS integration issue], thanks to https://stackoverflow.com/users/3702939/johan[@johan] for reporting the issue.

[role=release-note]

== Version 1.7.3
_August 15th, 2019_

=== New
* SAML v2, OpenID Connect, Google, Facebook, Twitter and External JWT Identity Provider configurations now have a debug flag. When enabled a debug Event Log will be created during each request to the Identity Provider to assist in debugging integration issues that may occur. In addition, error cases will be logged in the Event log instead of to the product log.
* SAML v2 Service Provider (Relaying Party) Metadata URL

=== Fixed
* In some cases when running FusionAuth behind a proxy without setting the `X-Forwarded-Port` header the URLs returned in the OpenID Configuration discovery document may contain an `https` URL that is suffixed with port `80`. If this is encountered prior to this version you may simply add the `X-Forwarded-Port` header in your proxy configuration.
* SAML v2 fix when using `urn:oasis:names:tc:SAML:2.0:nameid-format:transient` or `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` Name Id formats.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/205[GitHub Issue #205], thanks to https://github.com/mikerees[@mikerees] for reporting the issue and helping us test a fix.
* SAML v2 fix in the IdP Metadata. The `IDPSSODescriptor` was missing the `protocolSupportEnumeration` which may cause some SAML metadata parsers to fail processing.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/235[GitHub Issue #235], thanks to https://github.com/user1970869 [@user1970869 ] for reporting the issue and helping us test a fix.
* SAML v2 fix in the IdP Metadata. The value returned in the `issuer` attribute was not the same as the `entityId` provided in the metadata which may cause some SAML metadata parsers to fail processing.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/240[GitHub Issue #240], thanks to https://github.com/user1970869 [@user1970869 ] for reporting the issue and helping us test a fix.
* And audit log entry may not be created for a FusionAuth admin that does not have an email address when modifying configuration with the FusionAuth UI.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/268[GitHub Issue #268]

=== Enhancement
* Integration details have been moved to a view dialog for each Identity Provider configuration. Previously these values were provided as read only fields on the edit panel in the UI.
** See the View action for your Identity Provider configurations by navigating to [breadcrumb]#Settings# icon:chevron-right[role=breadcrumb] [breadcrumb]#Identity Providers#.


[role=release-note]

== Version 1.7.2
_June 19th, 2019_

=== Fixed
* Deleting a user that has recently had a failed login may fail when FusionAuth is tracking failed login attempts to lock user accounts.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/184[GitHub Issue #184 : Cannot delete user with too many login attempts], thanks to https://github.com/gmpreussner[@gmpreussner] for reporting the issue.
* Login to a 3rd party SAML IdP may fail
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/181[GitHub Issue #181 : Trouble with SAML and OpenID logins], thanks to https://github.com/davidmw[@davidmw] for reporting the issue.
* Fix the uptime calculation for nodes when viewed in the About panel. [breadcrumb]#System# icon:chevron-right[role=breadcrumb] [breadcrumb]#About#

[role=release-note]

== Version 1.7.1
_June 13th, 2019_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]

=== Fixed
* Possible migration error for PostgreSQL users

[role=release-note]

== Version 1.7.0
_June 13th, 2019_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]


=== Changes
* The `timezone` field in the User and UserRegistration must be a https://www.iana.org/time-zones[IANA] time zone. This was previously assumed, but not always enforced. If a timezone is set for a User or UserRegistration that is not a valid IANA timezone, `null` will be returned when retrieving the User or UserRegistration timezone.

=== New
* Family and relationship modeling. Yeah, everyone has users, but does your IdP manage family relationships?
** Family concepts
** link:../apis/families[Family APIs]
* Consent management. Need to record parental consent, or track opt-in for your users? Look no further.
** Consent concepts
** link:../apis/consent[Consent APIs]
** We will ship FusionAuth with COPPA VPC, and COPPA Email+ consents, additional consents may be added through the Consent management interface and through the Consent APIs.
* Export of Audit Logs to a zipped CSV in the UI and via the link:../apis/audit-logs#export-audit-logs[Export API]
* Export of Login Records to a zipped CSV in the UI and via the link:../apis/login#export-login-records[Export API]
* Login Record view that contains limited search and pagination capability. In the UI see [breadcrumb]#System# icon:chevron-right[role=breadcrumb] [breadcrumb]#Login Records#
* Retention policy for Audit Logs. This feature is disabled by default and may be enabled to retain a configured number of days worth of Audit Logs.
* Retention policy for Login Records. This feature is disabled by default and may be enabled to retain a configured number of days worth of Login Records.

=== Fixed
* Some timezones may not be correctly discovered during login. When this occurs an `undefined` value is set which may cause an error during login to the FusionAuth UI.
* Support importing Bcrypt hashes that contain a `.` (dot). The Bcrypt Base64 encoding uses a non standard character set which includes a `.` (dot) instead of a `+` (plus) as in the standard character set. Thank you to Diego Souza Rodrigues for discovering this issue and letting us know!.
* Better support for third party 2FA devices such as an RSA key fob. When providing FusionAuth with a secret to enable Two Factor authentication we will accept a string in a Bas32 or Base64 encoded format. The documentation has been updated to further clarify this behavior. Previously if you brought your own secret to FusionAuth to enable 2FA, depending upon the format of the key, you may not have been successful in enabling 2FA for a user.
* Managed domains were not being returned properly for a SAML v2 IdP configuration. This means that that you could not limit the SAML v2 IdP configuration to users with a specific email domain.

=== Enhancement
* The User Registration object is now available as a top level object in the Verify Registration email template. The registration was previously available in the `user` object, but it will now also be a top level object `registration`.
* Support arbitrary URIs for OAuth redirects.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/58[Github Issue #58 : Support OAuth2 redirect to an arbitrary scheme in support of native applications]
* Add `user.mobilePhone` to the search index. For an existing installation, to take advantage of this field for existing users, you may need to rebuild the search index. See [breadcrumb]#System# icon:chevron-right[role=breadcrumb] [breadcrumb]#Reindex#
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/165[GitHub Issue #165 : Add mobilePhone in User Search]
** Thanks to https://github.com/petechungtuyco[@petechungtuyco] for letting us know and suggesting the addition.

[role=release-note]

== Version 1.6.1
_May 2nd, 2019_

=== Fixed
* Using OpenID Connect with Microsoft Azure AD may fail
** Thanks to https://github.com/FusionAuth/fusionauth-issues/issues/153[@stevenrombauts] and https://github.com/plunkettscott[@plunkettscott] for reporting the issue. https://github.com/FusionAuth/fusionauth-issues/issues/153[OpenID connect fails with Azure AD #153].

[role=release-note]

== Version 1.6.0
_April 28th, 2019_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]

:info_message: The SAML specification is complex and not all SAML v2 Service Providers are specification compliant. This means your mileage may vary as you utilize the FusionAuth SAML v2 IdP to allow services such as Zendesk, Pivotal and Google G-Suite to log into FusionAuth using SAML v2. If you run into problems open a GitHub issue and we will try to help.
include::docs/v1/tech/release-notes/__general-upgrade-info.adoc[]

=== Changes
* Deprecated the following properties `SystemConfiguration` and `Application` domain. This is all now managed through Key Master, and existing keys have been migrated into Key Master.
** `jwtConfiguration.issuer`
** `jwtConfiguration.algorithm`
** `jwtConfiguration.secret`
** `jwtConfiguration.publicKey`
** `jwtConfiguration.privateKey`
* Deprecated the following property `SystemConfiguration.jwtConfiguration.issuer`, it has moved to `SystemConfiguration.issuer`.
* A new macro was added to the `_helpers.ftl` that may be managed by your theme. If you have modified the `_helpers.ftl` template as part of your theme, you will either need to reset that template and merge your changes back in, or add the following code to your `_helpers.ftl` managed by your theme. If you encounter an issue with this, you will still likely be able to login to correct the issue, if you do get stuck you may disable your theme to login. See https://fusionauth.io/docs/v1/tech/tutorials/login-theme#handling-failures.

[.code]
____
```
[#macro link url text extraParameters=""]
<a href="${url}?tenantId=${(tenantId)!''}&client_id=${(client_id?url)!''}&nonce=${(nonce?url)!''}&redirect_uri=${(redirect_uri?url)!''}&response_type=${(response_type?url)!''}&scope=${(scope?url)!''}&state=${(state?url)!''}&timezone=${(timezone?url)!''}&metaData.device.name=${(metaData.device.name?url)!''}&metaData.device.type=${(metaData.device.type?url)!''}${extraParameters!''}">
${text?html}
</a>
[/#macro]
```
____

=== New
* Support for SAMLv2 IdP. This satisfies https://github.com/FusionAuth/fusionauth-issues/issues/3[GitHub Issue #3]
* Support for SAMLv2 Service Provider to support federated authentication to a SAMLv2 Identity Provider. This satisfies https://github.com/FusionAuth/fusionauth-issues/issues/104[GitHub Issue #104]
* Lambda support. Lambdas are user defined JavaScript functions that may be executed at runtime to perform various functions. In the initial release of Lambda support they can be used to customize the claims returned in a JWT, reconcile a SAML v2 response or an OpenID Connect response when using these Identity Providers.
** See the Lambda API and the new Lambda settings in the UI [breadcrumb]#Settings# icon:chevron-right[role=breadcrumb] [breadcrumb]#Lambdas#.
* Event Log. The event log will assist developers during integration to debug integrations. The event log will be found in the UI under [breadcrumb]#System# icon:chevron-right[role=breadcrumb] [breadcrumb]#Event Log#.
** SMTP Transport errors
** Lambda execution exceptions
** Lambda debug output
** SAML IdP integration errors and debug
** Runtime exceptions due to email template rendering issues
** And more!
* Key Master, manage HMAC, Elliptic and RSA keys, import, download, generate, we do it all here at Key Master.
** link:../apis/keys[Key APIs]
* New events
 ** `user.login.failed`
 ** `user.login.success`
 ** `user.registration.create`
 ** `user.registration.update`
 ** `user.registration.delete`
* Easily duplicate email templates using the Duplicate action.
** https://github.com/FusionAuth/fusionauth-issues/issues/142
* Manage Access Token and Id Token signing separately


=== Enhancement
* Insert instant provided on the Import API for Users and Registrations will be reflected in the historical registration reports
** https://github.com/FusionAuth/fusionauth-issues/issues/144
* Additional node information will be available on the About panel when running multiple FusionAuth nodes in a cluster. See [breadcrumb]#System# icon:chevron-right[role=breadcrumb] [breadcrumb]#About#.

=== Fixed
* If Passwordless login is disabled because no email template has been configured the button will not be displayed on the login panel. If a user attempts to use the passwordless login and the feature has been disabled or the user does not have an email address a error will be displayed to alert the user.
* If you are using the Implicit Grant and you have Self Service Registration enabled for the same application, the redirect after the registration check will assume you are using the Authorization Code grant. To work around this issue prior to this release, disable Self Service Registration. Thanks to https://github.com/whiskerch[@whiskerch] for reporting this issue in https://github.com/FusionAuth/fusionauth-issues/issues/102[GitHub Issue #102].
* Fixed OpenID Connect federated login. Our JavaScript code was throwing an exception due to the removal of the `device` field from OAuth. This code wasn't updated and therefore would not perform the redirect to the third-party Open ID Connect IdP. To fix this issue in 1.5.0 or below, you can remove this line from OpenIDConnect.js on or near line 48: `+ '&device=' + Prime.Document.queryFirst('input[name=device]').getValue()`.
* When you use the Refresh Grant with a Refresh Token that was obtained using the Authorization Code grant using the `openid` scope, the response will not contain an `id_token` as you would expect. This fixes https://github.com/FusionAuth/fusionauth-issues/issues/110[GitHub Issue #110 - OIDC and Refresh Tokens]. Thanks to https://github.com/fabiosimeoni[@fabiosimeoni] for reporting this issue
* When using the OpenID Connect Identity Provider that requires client authentication may fail even when you provide a client secret in your OpenID Connect configuration.
* https://github.com/FusionAuth/fusionauth-issues/issues/118
* https://github.com/FusionAuth/fusionauth-issues/issues/119
* https://github.com/FusionAuth/fusionauth-issues/issues/122


[role=release-note]

== Version 1.5.0
_March 25th, 2019_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]

== Changed
* Removed `/oauth2/token` from the CORS configuration. This change will cause the CORS filter to reject a `POST` request to the `/oauth2/token` endpoint when the request originates in JavaScript from a different domain. This will effectively prohibit the use of the OAuth2 Password grant from JavaScript.
* The `device` parameter is no longer required on the link:../apis/login[Login API] or the link:../oauth/endpoints#authorize[Authorized] endpoint in order to receive a Refresh Token. If the `device` parameter is provided it will be ignored.
* Correct the link:../apis/jwt#refresh-a-jwt[Refresh API] response body to match the documentation. If you are currently consuming the JSON body of this API using the `POST` method, you will need to update your integration to match the documented response body.

=== New
* Support for Passwordless login via email. See link:../apis/passwordless[Passwordless API] if you'll be integrating with this API to build your own login form. To use this feature using the provided FusionAuth login form, enable Passwordless by navigating to your FusionAuth Application [breadcrumb]#Settings# icon:chevron-right[role=breadcrumb] [breadcrumb]#Applications# and selecting the `Security` tab.
* Support for the OAuth2 Implicit Grant. See the link:../oauth/overview[OAuth 2.0 & OpenID Connect Overview] and link:../oauth/endpoints[OAuth 2.0 Endpoints] for additional information.
* The `Authorization Code`, `Password`, `Implicit` and `Refresh Token` grants maybe enabled or disabled per application. See `oauthConfiguration.enabledGrants` property in the link:../apis/applications[Application API], or the `OAuth` tab in the Application configuration in the FusionAuth UI.
* The link:../apis/users[Change Password API] can be called using a JWT. This provides additional support for the Change Password workflow in a single page web application. See the Change Password API for additional details.
* The link:../apis/users[Change Password API] in some cases will return a One Time password (OTP). This password may then be exchanged for a new JWT and a Refresh Token on the Login API. This allows for a more seamless user experience when performing a change password workflow. See the Change Password and Login API for additional details.
* The link:../apis/login[Login API] can now be restricted to require an API key. The default for new applications will require authentication which can be disabled. Existing applications will not require authentication via API to preserve the existing behavior. The Login API may also be restricted from return Refresh Tokens are allowing an existing Refresh Token be used to refresh an Access Token. These settings will be configurable per Application, see the Application API for additional details, or the `Security` tab in the Application configuration in the UI. If using the link:../apis/applications[Application API], see the `application.loginConfiguration` parameters.
* The `c_hash`, `at_hash` and `nonce` claims will be added to the `id_token` payload for the appropriate grants.
* Add support for `client_secret_post` to the already provided `client_secret_basic` Client Authentication method. This means that in addition to using HTTP Basic Authentication, you may also provide the `client_id` and `client_secret` in the request body.

=== Enhancement
* Better ECDSA private and public key validation to ensure the algorithm selected by the user matches the provided key.
* When using the Change Password workflow in the OAuth2 Implicit or Authorization Code grants, the user will be automatically logged in upon completing a change password that is required during login.
* The Two Factor Login API will return the `twoFactorTrustId` as an HTTP Only secure cookie in addition to being returned in the JSON response body. This provides additional support and ease of use when making use of this API in a single page web application. See the Two Factor Login API for additional details.

=== Fixed
* When using the Login Report in the UI and searching by user, if you have more than one tenant you will encounter an error.
* Validation errors are not displayed in the Add Claim dialog when configuring claim mapping for an External JWT Identity Provider
* Calling the Tenant API with the `POST` or `PUT` methods w/out a request body will result in a `500` instead of a `400` with an error message.
* When a locale preference has not been set for a FusionAuth admin and the English locale is used the user may see dates displayed in `d/M/yyyy` instead of `M/d/yyyy`.
* Fix some form validation errors during self-registration.
* The Action user action on the Manage User panel was opening the Comment dialog instead of the Action user dialog
* When a user has 2FA enabled and a password change is required during login, the 2FA will now occur before the change password workflow
* When more than one tenant exists, the Forgot Password link on the FusionAuth login page will not function properly.
* The Logout API may not always delete the `access_token` and `refresh_token` cookies if they exist on the browser.
* The `id_token` will be signed with the `client_secret` when `HS256`, `HS384` or `HS512` is selected as the signing algorithm. This is necessary for compliance with https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation[OpenID Connect Core 3.1.3.7 ID Token Validation]. This fixes GitHub issue https://github.com/FusionAuth/fusionauth-issues/issues/57[GitHub Issue #57], thanks to https://github.com/Garogat[@Garogat] for reporting this issue. If you encounter this issue prior to this version, copy the Client Secret found in the UI on the `OAuth` tab of your Application configuration into the HMAC secret on the `JWT` configuration tab.
* The link:../apis/login[Login API] will now return a `400` with an error JSON response body if the `applicationId` parameter does not belong to any configured applications. Previous to this release, this was treated the same as if the User was not registered to the requested application.
* A change to the Docker build for permissions reduced the overall `fusionauth-app` image by ~ 200 MB.

[role=release-note]

== Version 1.4.0
_February 4th, 2019_

:info_message: The FusionAuth link:../installation-guide/system-requirements[System Requirements] have been updated. Please review the updated requirements to ensure you have met the minimum supported versions of operating system and database.
include::docs/v1/tech/release-notes/__general-upgrade-info.adoc[]

=== Changed
* Renamed `Type` enum in `DeviceInfo` class to `DeviceType`. This will only affect you if you are using the Java or C# client and reference this enum directly. If you are using this class directly, you may need to update an import in your client code.
* More than one authorization code may exist for a single user at a given time. This will allow multiple asynchronous requests to begin an OAuth2 Authorization Grant workflow and succeed regardless of order.

=== New
* Self service registration. You may optionally enable this feature per application and allow users to create a new account or register for new applications without building your own registration forms.
* JSON Web Key set support. This endpoint will be exposed at `/.well-known/jwks.json` and will be published in the link:../oauth/endpoints#openid-configuration[OpenID Configuration] metadata endpoint as well. Prior to this release the public keys used to sign JSON Web Tokens were only available in PEM format using the link:../apis/jwt#retrieve-public-keys[Public Key API], this endpoint will still be available and supported.
** See link:../oauth/endpoints#json-web-key-set-jwks[JSON Web Key Set (JWKS)] for more information.
* Added Elliptic Curve signature support for JSON Web Tokens, ES256, ES384 and ES512.
* Added Typescript client library https://github.com/FusionAuth/fusionauth-typescript-client
* The Login Report may now be optionally filtered to a particular User in the UI, and the link:../apis/reports#generate-login-report[Login Report] API will now take `loginId` or `userId`.

=== Fixed
* When using Docker compose, if you start up with `--pull` to update to the latest version of FusionAuth and there happens to be a database schema update, the silent configuration mode may fail. This occurs because the silent configuration was not performing the database schema update automatically. If you encounter this issue, you will need to manually update the schema.
** This will only occur if you are running a version of FusionAuth prior to `1.1.0` and upgrade using `--pull` during `docker-compose up`.
* When you have multiple tenants created, a tenant may be deleted with an API key that is not assigned to the tenant. This has been corrected and a tenant may only be deleted using an API key that is not assigned to any tenant. This issue will only affect you if you have more than one tenant.
* Updated Maintenance Mode (setup wizard) to work with MySQL version 8.0.13 and above. MySQL has changed their SSL/TLS handling and our connections were not correctly handling public keys. This has been fixed by allowing FusionAuth to perform a secondary request to MySQL to fetch the public key.
* Logging in with a Social Login provider such as Google for an existing FusionAuth user may cause them to be unable to login to FusionAuth directly using their original credentials.
* When using the OpenID Connect Identity Provider, the incoming claim `given_name` was being saved in the `fullName` field instead of the `firstName`.
* When a user is soft deleted, actioned to prevent login, expired, or they have changed their password since their last login, their SSO session will be invalidated instead of waiting for the session to expire.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/59[Github Issue #59 :Using a access token for a lock account]

=== Internal
* Upgrade to fusionauth-jwt 3.0.1 in support of Elliptic Curve crypto support.

[role=release-note]

== Version 1.3.1
_December 19th, 2018_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]

=== Changed
* API key will take precedence for API authentication if both a JWT and an API key are provided on the request. For example, when making a GET request to the User API, if a JWT is provided in a cookie, and a valid API key is also provided in the `Authorization` HTTP header, the previous design was to prefer the JWT. This design point meant that even when an API key was provided, even when providing a valid API key, you would be unable to retrieve any user but the one represented by the JWT.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/43[GitHub Issue #43 : Id is ignored on Retrieve User when JWT is present]
* The `client_id` is no longer required on the OAuth Token endpoint when client authentication is configured as required, in this scenario the client Id is provided in the HTTP Basic Authorization header.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/54[Github Issue #54 :Token request returning 500 when client_id is omitted]

=== Fixed
* When editing the JWT settings in the FusionAuth application the UI a JavaScript error may cause some of the settings to not render properly. This error was introduced in version `1.3.0`.
* Added missing properties to the Application view dialog in the FusionAuth UI.
* The `openid` scope may not be honored during login when a user has Two Factor authentication enabled. The symptom of this issue is that the response from the Token endpoint will not contain an `id_token` even when the `openid` scope was requested.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/53[Github Issue #53 : Authorization with scope openid fails when 2FA is enabled]
* Validation for the OAuth2 Token endpoint may fail when the `client_id` request body parameter is omitted and return a `500` instead of a `400` status code.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/54[Github Issue #54 : Token request returning 500 when client_id is omitted]
* When a OAuth2 redirect URI is registered with a query parameter, the resulting redirect URI will not be built correctly.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/55[Github Issue #55 : Adding a query parameter to the redirect_uri causes an invalid URI to be returned]
* When trying to configure Elasticsearch engine during maintenance mode the index may get created but fail to leave maintenance mode. FusionAuth makes a `HEAD` request to Elasticsearch to check if the required indexes exist during startup and prior to leaving maintenance mode. When connected to an AWS Elasticsearch cluster this request does not behave as expected which causes FusionAuth to stay in maintenance mode. This issue has been resolved and should allow FusionAuth to properly connect to and utilize Elasticsearch running in an AWS cluster.


[role=release-note]

== Version 1.3.0
_December 5th, 2018_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]

=== New
* An Application may disable the issue of refresh tokens through configuration. See `oauthConfiguration.generateRefreshTokens` in the link:../apis/applications[Application API] or the `Generate refresh tokens` toggle in the FusionAuth UI when editing an application.
* The OAuth2 client secret may be optionally regenerated using the FusionAuth UI during Application edit.
* Support for OAuth2 confidential clients, this is supported by optionally requiring client authentication via configuration. See `oauthConfiguration.requireClientAuthentication` in the link:../apis/applications[Application API] or the `Require authentication` toggle in the FusionAuth UI when editing an application.

=== Fixed
* Calling the link:../oauth/endpoints#introspect[Introspect] endpoint with a JWT returned from the Issue API may fail due to the missing `aud` claim.
* The MySQL schema previously was using `random_bytes` which is not available in MariaDB. These usages have been replaced with an equivalent that will function the same in MySQL and MariaDB.
** Thanks to https://github.com/Garogat[@Garogat] for bringing this to our attention and suggesting and verifying a solution via https://github.com/FusionAuth/fusionauth-issues/issues/48[GitHub Issue #48 : Support for MariaDB]
* When editing or adding a new user in the FusionAuth UI, the `Birthdate` field may get set automatically before the date selector is utilized. A JavaScript error was causing this condition and it has been fixed.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/41[GitHub Issue #41 : Birthday is autofilled when adding or editing a user]

[role=release-note]

== Version 1.2.2
_November 27th, 2018_

=== Fixed
* Add `X-FusionAuth-TenantId` to allowed CORS headers.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/44[GitHub Issue #44 : CORS blocks API request containing X-FusionAuth-TenantId]
* When FusionAuth is running behind a proxy such as an AWS ALB / ELB the redirect URI required to complete login may not be resolved correctly. This may cause the redirect back to the FusionAuth UI login to fail with a CSRF exception. If you encounter this issue you may see an error message that says `Something doesn't seem right. You have been logged out of FusionAuth`. The work-around for this issue if you encounter it will be to perform the redirect from HTTP to HTTPS in your load balancer.
* Some minor usability issues in the Identity Provider configuration UI.

[role=release-note]

== Version 1.2.1
_November 16th, 2018_

=== Enhancement
* Better error handling when an API caller sends invalid JSON messages. Prior to this enhancement if FusionAuth did not provide a specific error message for a particular field a `500` HTTP status code was returned if the JSON could not be parsed properly. This enhancement will ensure that sending a FusionAuth API invalid JSON will consistently result in a `400` status code with a JSON body describing the error.
** Resolves https://github.com/FusionAuth/fusionauth-issues/issues/17[GitHub Issue #17 : Malformed or invalid JSON causes 500 error]
* Allow an Identity Provider to be enabled and disabled from the UI. You may still choose to enable or disable a specific Application for use with an Identity Provider, but with this enhancement you may not turn off an Identity Provider for all Applications with one switch.

=== Fixed
* Preserve Application Identity Provider configuration for disabled Applications when editing a Identity Provider from the UI.


== Version 1.2.0
_November 15th, 2018_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]

=== New
* Add TTL configuration for Refresh Tokens to the Application configuration. When you enable JWT configuration per Application this value will override the global setting.

=== Fixed
* An error in the Twitter OAuth v1 workflow has been resolved.

[role=release-note]

== Version 1.1.1
_November 13th, 2018_

=== Fixed
* If you were to have an Identity Provider for federated third party JSON Web Tokens configured prior to upgrading to `1.1.0` FusionAuth may fail during the database migration to version `1.1.0`.

== Version 1.1.0
_November 13th, 2018_

include::docs/v1/tech/release-notes/__database-migration-warning.adoc[]

=== New
* Social login support
** link:../apis/identity-providers/facebook[Facebook] Identity Provider
** link:../apis/identity-providers/google[Google] Identity Provider
** link:../apis/identity-providers/twitter[Twitter] Identity Provider
** link:../apis/identity-providers/openid-connect[OpenID Connect] Identity Provider
* Full theme support for login. See the link:../tutorials/login-theme[Login Theme] tutorial for additional information and examples.
* Better localization support in the FusionAuth UI. You now have the option to set or modify your preferred language for use in the FusionAuth UI.
Providing a preferred language will cause dates to be formatted based upon your preference. For example, the default data format is `M/D/YYYY`, but
if you are not in the United States this may not be the way you expect a date to be formatted. If you set your locale to `French` you will now
see a more appropriate format of `D/M/YYYY`. This value is stored on the User Registration for FusionAuth in the `preferredLanguages` field.

=== Enhancement
* When viewing sessions (refresh tokens) on the Manage User panel, the start and expiration times will be displayed.

[role=release-note]

== Version 1.0.18
_October 29th, 2018_

=== Fixed
* If FusionAuth starts up in maintenance mode and stays there for an extended period of time without the User completing the configuration from the web browser, FusionAuth may get stuck in maintenance mode. If you encounter this issue, where you seemingly are entering the correct credentials on the Database configuration page and are unable to continue, restart FusionAuth and the issue will be resolved.

[role=release-note]

== Version 1.0.17
_October 5th, 2018_

=== Fixed
* When running in Docker Compose, FusionAuth cannot connect to the search service when trying to exit the setup wizard.
** https://github.com/FusionAuth/fusionauth-containers/issues/2

[role=release-note]

== Version 1.0.16
_October 5th, 2018_

=== Enhancement
* Better support for running in Docker. Enhanced silent configuration capability for database and search engine boot strap configuration in Docker Compose to be more resilient.

=== Fixed
* If custom data is added to an Application, Group or Tenant before editing the corresponding object in the UI, the custom data may be lost.

[role=release-note]

== Version 1.0.15
_October 1st, 2018_

=== New
* Better support for running in Docker. Configuration can be override using environment variables. See link:../installation-guide/docker[Docker Install] for additional information.

=== Fixed
* The first time a user reached the failed login threshold and a `409` response code was returned the response body was empty. Subsequent login requests correctly returned the JSON response body with the `409`, now the JSON response body is correctly returned the first time the user reaches the failed login threshold.


[role=release-note]

== Version 1.0.14
_September 17th, 2018_

=== Fixed
* When using PostgreSQL an exception may occur during an internal cache reload request. If you encounter this issue you will see a stack trace in the `fusionauth-app.log`. If you see this error and need assistance, please open an issue in the FusionAuth https://github.com/FusionAuth/fusionauth-issues[Issues] GitHub project.

[.code]
____
`Unexpected error. We're missing an internal API key to notify distributed caches.`
____


[role=release-note]

== Version 1.0.13
_September 12th, 2018_

=== New
* General availability release
