=== Templates

When new functionality is introduced to link:/docs/v1/tech/core-concepts/integration-points/#hosted-login-pages[the hosted login pages], new theme templates are occasionally added. They are added to the default theme by the upgrade process, but if you've customized your theme to fit your brand, you'll need to modify the theme to have the new template.

In the version release notes, any new templates are documented. This will tell you that you'll want to take a closer look at the themes post upgrade.

As part of your upgrade testing, open the administrative user interface and navigate to [breadcrumb]#Customizations > Themes#.

If any themes are missing templates, they will show as "Upgrade Required". Port the new theme files over to your custom theme, modify them as needed, and save the theme.

=== Messages

When new functionality is introduced to link:/docs/v1/tech/core-concepts/integration-points/#hosted-login-pages[the hosted login pages], new theme message keys are sometimes required. They are added to the default theme `messages` file by the upgrade process. 

However, if you have customized your theme, the new keys are not added to that modified theme. The first time you try to modify the [field]#Messages# of your theme, you'll receive an error message similar to the text below:

```
Missing required keys. See text area below for default English translations. To continue, please copy the values from below into the Messages text area.
```

FusionAuth warns you about missing required keys in order to avoid an inadvertent bad user experience. The default display for keys with no valid values in theme [field]#Messages# is the key text, such as `[ExternalAuthenticationException]LinkedInToken`, which can be confusing for end users. 

During an upgrade, you can find these keys by testing the upgrade on a development instance or comparing releases in the link:https://github.com/FusionAuth/fusionauth-localization/[fusionauth-localization] repo. You can safely add these new key values to your theme prior to an upgrade. Any unused messages in a theme's `messages` file are silently ignored (unless malformed). 

The extra lines won't do any harm, and will ensure an excellent end user experience if they stumble on new functionality right after an upgrade.

