---
layout: doc
title: FusionAuth Cloud
description: FusionAuth Cloud is FusionAuth in the cloud, managed by us
---

== What is FusionAuth Cloud

FusionAuth Cloud is an entirely managed FusionAuth server. 

You have complete access to the system via the administrative user interface and API keys. But you have no access to the servers or networks on which the instance runs.

With FusionAuth Cloud, you create deployments. A deployment is a FusionAuth instance, a database, and all the necessary networking configuration to connect your FusionAuth deployment. You can create as many deployments as you want, and tear them down when you do not need them any more.

Each deployment is separated from all other deployments and there is not network path between them. XXX do we put them in sep security groups? I'm guessing so.

== What Does FusionAuth Cloud Cost

Unlike other installation options, FusionAuth Cloud is not free. 

You cannot create a FusionAuth Cloud deployment without a credit card or invoicing agreement.

For full pricing information as well as different deployment architectures, please visit link:/pricing/cloud/[the pricing page].

pricing-calculator-bottom.png
pricing-calculator.png

== Why Use FusionAuth Cloud

FusionAuth Cloud provides a fully managed service that can be used for:

* Proof of concepts or trials
* Testing functionality of new versions with no risk
* Development environments
* High availability production environments

You can spin up a functioning server in minutes, and get to work testing or integrating FusionAuth, rather than trying to configure it. If you want to use FusionAuth but offload all the management burden to the people who built it, FusionAuth Cloud is a good choice.

== How To Use FusionAuth Cloud

You must register by going to https://account.fusionauth.io and creating an account.

You'll be prompted for a username, password and other required information.

TBD image initial-cloud-selection.png
TBD image login-screen.png
TBD image register.png
TBD image billing-prompt.png before you buy anything else
TBD image add-billing-information.png

=== Creating a Deployment

TBD image deployments-tab-no-deployments

==== Provisioning Decisions

provisioning-initial.png
provisioning-choosing-size.png
provisioning-select-version-url.png
provisioning-selecting-region-tier.png

5 things

==== After Provisioning


TBD image deployments-provisioning
TBD image deployments-active

=== Upgrading a Deployment

If you have a running FusionAuth instance and want upgrade the version it is running, you can do so by https://account.fusionauth.io/account/support/[logging into your account] and manage the instance in question. 

Choose the [field]#Upgrade# option. This will be present if the instance is not on the latest available version.

There is downtime when upgrading. Consult the release notes for details about the changes and what kind of downtime to expect.

XXX we stand up new server and then flip dns, right?

You will never be forced to upgrade, though we recommend staying on the latest released version.

You cannot downgrade a FusionAuth Cloud instance. 

=== Restoring From Backup

If you have a FusionAuth Cloud plan which includes backups and you want to restore from a backup, please open a https://account.fusionauth.io/account/support/[support ticket].

=== Terminating an Instance

If you have a running FusionAuth instance and want to shut it down, you can do so by https://account.fusionauth.io/account/support/[logging into your account] and manage the instance in question. Choose the [field]#Destroy# option.

[NOTE.warning]
====
Make sure you have obtained a backup or otherwise retrieved a copy of your data. Once an instance is destroyed, there is no way of retrieving the data on it. 
====

TBD image deployments-prepare-destroy
TBD image delete-deployment-confirm
TBD image deployments-destroying

XXX do we delete backups too? I am guessing yes.

=== Other Account Portal Sections

...
TBD image editions-tab
TBD image users-tab


== Leaving FusionAuth Cloud

If you'd like to get your user data out of FusionAuth Cloud, whether because you are migrating away from FusionAuth or because you need raw user data for analytics or some other purpose, please open a https://account.fusionauth.io/account/support/[support ticket].

If you need to download user data frequently, please consider using the User API or a webhook to retrieve user information as FusionAuth receives it. If these solutions won't meet your needs, please link:/contact/[contact us] to discuss options.

The reason a support request is required is because the backup contains sensitive data, such as password hashes. We need to work with you to provide a safe mechanism to transfer the data.

== Limits

There is currently no API to control creation or deletion of FusionAuth Cloud instances. You can use API keys to control the configuration and behavior of FusionAuth instances within the cloud.

== Support

Support for FusionAuth Cloud is limited to running your FusionAuth cloud instance. 

TBD image support-tab

Support from the engineering team for integrating with FusionAuth is purchased separately through an edition with support. XXX still true? 

Support via our link:/community/forum[forums] and link:/docs/v1/tech/[documentation] is available at no cost.

Please review link:/technical-support/[the technical support page] for more information on support.

== Additional Customization

If you need additional features for a managed FusionAuth deployment, please either link:/contact/[contact us] or https://github.com/fusionauth/fusionauth-issues/issues[file a GitHub issue].


XXX What does production flag do? I don't think anything from looking in fusionauth-cloud?

delete-deployment-confirm.png
deployments-destroying.png
deployments-prepare-destroy.png
deployments-provisioning.png
deployments-tab-no-deployments.png
