---
layout: doc
title: FusionAuth Cloud
description: FusionAuth Cloud is FusionAuth in the cloud, managed by us
---

== What is FusionAuth Cloud

FusionAuth Cloud is an entirely managed FusionAuth server. 

You have complete access to the system via the administrative user interface and API keys. But you have no access to the servers or networks on which the instance runs.

With FusionAuth Cloud, you create deployments. A deployment is a FusionAuth instance, a database, and all the necessary networking configuration to connect your FusionAuth deployment. You can create as many deployments as you want, and tear them down when you do not need them any more.

Each deployment is separated from all other deployments and there is not network path between them. XXX do we put them in sep security groups? I'm guessing so.

== What Does FusionAuth Cloud Cost

Unlike other installation options, FusionAuth Cloud is not free. 

You cannot create a FusionAuth Cloud deployment without a credit card or invoicing agreement.

For full pricing information as well as different deployment architectures, please visit link:/pricing/cloud/[the pricing page].

== Why Use FusionAuth Cloud

FusionAuth Cloud provides a fully managed service that can be used for:

* Proof of concepts or trials
* Testing functionality of new versions with no risk
* Development environments
* High availability production environments

If you want to use FusionAuth but offload all the management burden to the people who built it, FusionAuth Cloud is a good choice.

== How To Use FusionAuth Cloud



=== Creating a Deployment


=== Upgrading a Deployment

If you have a running FusionAuth instance and want upgrade the version it is running, you can do so by https://account.fusionauth.io/account/support/[logging into your account] and manage the instance in question. 

Choose the [field]#Upgrade# option. This will be present if the instance is not on the latest available version.

There is downtime when upgrading. Consult the release notes for details about the changes and what kind of downtime to expect.

You will never be forced to upgrade, though we recommend staying on the latest released version.

You cannot downgrade a FusionAuth Cloud instance. 

=== Restoring From Backup

If you have a FusionAuth Cloud plan which includes backups and you want to restore from a backup, please open a https://account.fusionauth.io/account/support/[support ticket].

=== Terminating an Instance

If you have a running FusionAuth instance and want to shut it down, you can do so by https://account.fusionauth.io/account/support/[logging into your account] and manage the instance in question. Choose the [field]#Destroy# option.

[NOTE.warning]
====
Make sure you have obtained a backup or otherwise retrieved a copy of your data. Once an instance is destroyed, there is no way of retrieving the data on it. 
====

XXX do we delete backups too? I am guessing yes.

=== Other Account Portal Sections

...


== Leaving FusionAuth Cloud

If you'd like to get your user data out of FusionAuth Cloud, whether because you are migrating away from FusionAuth or because you need raw user data for analytics or some other purpose, please open a https://account.fusionauth.io/account/support/[support ticket].

If you need to download user data frequently, please consider using the User API or a webhook to retrieve user information as FusionAuth receives it. If these solutions won't meet your needs, please link:/contact/[contact us] to discuss options.

The reason a support request is required is because the backup contains sensitive data, such as password hashes. We need to work with you to provide a safe mechanism to transfer the data.

== Limits

There is currently no API to control creation or deletion of FusionAuth Cloud instances. You can use API keys to control the configuration and behavior of FusionAuth instances within the cloud.

== Additional Customization

If you need additional features for a managed FusionAuth deployment, please either link:/contact/[contact us] or https://github.com/fusionauth/fusionauth-issues/issues[file a GitHub issue].
