---
layout: doc
title: Install a Database
description: Install the database that FusionAuth will use to store the user data
---

== Install a Database

[NOTE]
====
If you already have a MySQL or PostgreSQL database installed that you will be using with FusionAuth, you can skip this section completely.
====

In order to use FusionAuth, you need to install a database. The database requirements are provided in the link:system-requirements[System Requirements].
 Follow the instructions below to install a supported database.

 * <<Install MySQL>>
 * <<Install PostgreSQL>>

=== Install MySQL

[NOTE]
====
IBM Compose for MySQL or other MysQL platforms that utilize MySQL Group Replication are not supported.
====

==== Linux

To install MySQL on a Linux system, you can use the `apt` or `yum` tools depending on whether or not your Linux distribution is based on Red Hat or Debian. The package name may vary depending on your platform, for example: `mysql-server` or `mysql-server-5.7`. Here's the commands for each:

[source,bash]
.Red Hat
----
$ yum install mysql-server
----

[source,bash]
.Debian
----
$ sudo apt-get install mysql-server
----

==== Windows or macOS

If you are installing MySQL on a platform that does not supports RPM or DEB packages, you will need to download the installer from the MySQL website here: http://dev.mysql.com/downloads/mysql/

==== MySQL and Unicode

[NOTE]
====
To properly store 4 byte unicode, the character set must be set to `utf8mb4`.

By default this configuration is enforced during startup. If FusionAuth fails to startup due to this validation the log will contain detailed
messages about the MySQL configuration.

It is recommended to ensure you have properly configured MySQL to use `utf8mb4` before attempting to startup FusionAuth. Please verify you have
the following configuration in your `my.cnf` file. On Windows the file is called `my.ini`.

If you need to modify your configuration, restart MySQL for the changes to take effect.
====

[source,ini]
.my.cnf
----
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_bin
----

This is a system wide configuration option, so be certain that other databases and applications on the same MySQL server won't be impacted by this change.
It is possible not all of these configuration options will be available depending on your database configuration. Once you have configured the available
options, if startup still fails due to this validation you may disable this feature. See `database.mysql.enforce-utf8mb4` in the link:/docs/v1/tech/reference/configuration[Configuration] reference.

=== Install PostgreSQL

==== Linux

To install PostgreSQL on a Linux system, you can use the `apt` or `yum` tools depending on whether or not your Linux distribution is based
on Red Hat or Debian. The package name may vary depending on your platform.

[source,bash]
.Red Hat
----
$ sudo yum install postgresql-server postgresql
$ sudo yum install postgresql9-contrib.x86_64
----

[source,bash]
.Debian
----
$ sudo apt-get install postgresql-server
$ sudo apt-get install postgresql-contrib
----

==== Windows or macOS

If you are installing PostgreSQL on a platform that does not support RPM or DEB packages, you will need to download the installer from the PostgreSQL website here: https://www.postgresql.org

