---
layout: doc
title: Using FusionAuth on Docker
description: Deploy and test FusionAuth using a Docker container
keywords: docker kubernetes k8s container openshift
navcategory: installation
---

:sectnumlevels: 0

FusionAuth Docker containers can be used with Docker Compose, Kubernetes, Helm or OpenShift. 

The following example is using Docker Compose. Here are link:/docs/v1/tech/installation-guide/kubernetes/[kubernetes and Helm installation instructions. Find links for OpenShift and other community supported Docker environments in the https://github.com/FusionAuth/fusionauth-contrib[FusionAuth Contrib] GitHub repo.

* <<Docker Compose>>
* <<Configuration>>
* <<Docker Services>>
* <<Production Deployment>>
* <<Upgrading>>
* <<Docker Images>>
* <<Kickstart>>
* <<Plugins>>
* <<Accessing the Host Machine>>

== Docker Compose

All of the FusionAuth Docker images may be found on https://hub.docker.com/u/fusionauth/[Docker Hub].

The FusionAuth docker compose yaml files may be found on https://github.com/FusionAuth/fusionauth-containers[FusionAuth containers repository].

If you're looking for a complete configuration to get up and running quickly, use our Docker Compose example. `docker-compose.yml` will install FusionAuth without the enhanced search capability that Elasticsearch provides.  If you would rather use FusionAuth with Elasticsearch for improved searching, make sure you include the `docker-compose.override.yml`.

=== Installing FusionAuth

include::docs/v1/tech/installation-guide/_docker-compose-files.adoc[]

=== Installing FusionAuth with Elasticsearch

:with_elasticsearch:
include::docs/v1/tech/installation-guide/_docker-compose-files.adoc[]
:with_elasticsearch!:

=== The Docker Compose Files

The following is the default `docker-compose.yml` file, which installs FusionAuth without the Elasticsearch engine.

[source,yaml,title=docker-compose.yml]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml[]
----

The following is the default `docker-compose-override.yml` file. When included in your working directory next to the above `docker-compose.yml`, your FusionAuth installation will use Elasticsearch. 

[source,yaml,title=docker-compose-overrride.yml]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.override.yml[]
----

== Docker Services

In the above example configurations there are three services:

* database 
* search 
* FusionAuth

Let's look at each of these.

=== Database Service

The database service provides a postgreSQL database for use by FusionAuth.

You will need to either set the `POSTGRES_PASSWORD` environment variable in the `db` service section, or more ideally, set the value in the host environment and leave it out of the `docker-compose.yml` file.

By default this database is not accessible outside of the docker compose containers, but you may expose the port if you want to examine the database.

Review the other properties to ensure they meet your requirements. 

=== Search Service

include::docs/v1/tech/installation-guide/_elastic-search-version.adoc[]

include::docs/v1/tech/installation-guide/_elasticsearch-ram.adoc[]

=== The FusionAuth Service

This is the service that runs the FusionAuth application.

Review the link:/docs/v1/tech/reference/configuration#options[Configuration] documentation to customize your deployment. The best way t configure FusionAuth when using Docker is to use environment variables.

In addition, the port `9011` is mapped between the container and your host machine. This may be modified if you want to run more than one FusionAuth instance or for any other reason.

=== Other Services

You may add other services to the docker compose files if needed.

For example, in development environments it can be helpful to run mailcatcher for SMTP.

[source,yaml,title=`docker-compose.override.yml with mailcatcher]
----
version: '3'

services:
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - mailcatcher

#other services
----

== Production Deployment

Elasticsearch has a few runtime requirements that may not be met by default on your host platform. Please review the https://www.elastic.co/guide/en/elasticsearch/reference/7.6/docker.html#docker-cli-run-prod-mode[Elasticsearch Docker production mode guide for more information].

For example if startup is failing and you see the following in the logs, you will need to increase `vm.max_map_count` on your host VM.

[source]
----
2018-11-22T12:32:06.779828954Z Nov 22, 2018 12:32:06.779 PM ERROR c.inversoft.maintenance.search.ElasticsearchSilentConfigurationWorkflowTask
  - Silent configuration was unable to complete search configuration. Entering maintenance mode. State [SERVER_DOWN]

2018-11-22T13:00:05.346558595Z ERROR: [2] bootstrap checks failed
2018-11-22T13:00:05.346600195Z [1]: memory locking requested for elasticsearch process but memory is not locked
2018-11-22T13:00:05.346606495Z [2]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
----

== Upgrading

To upgrade FusionAuth when running with `docker-compose`:

. Stop the instance: `docker-compose down`.
. Modify the `docker-compose.yml` file (or the `docker-compose.override.yml` file, if applicable) to point to the version of FusionAuth you want. You can see https://hub.docker.com/r/fusionauth/fusionauth-app[available tags].
. Start it up: `docker-compose up`.
. Login to the administrative UI. 

=== Migrations

If there were database migrations required, what happens on an upgrade depends on two settings: the runtime mode and the silent mode.

[NOTE]
====
Prior to version `1.19.0`, migration behavior was different. See below for more.
====

If silent mode is set to `true`, then database migrations will automatically be performed.

If silent mode is `false` and the runtime mode is set to `development`, then the link:/docs/v1/tech/installation-guide/fusionauth-app#maintenance-mode[maintenance mode screen] will pop up and you will be prompted to complete the migrations there.

In all other cases the migrations will not be applied, and you'll have to perform them yourself. If you want to manage your own database upgrades, performing the SQL migrations out of band with another tool or process is a good option.

[cols="2a,2a,5a"]
.When Are Database Migrations Applied
|===
|Runtime Mode|Silent Mode|Migration Behavior

|`development`
|`true`
|Migration applied automatically

|`development`
|`false`
|Maintenance mode UI displayed, user prompted to run migrations

|`production`
|`true`
|Migration applied automatically

|`production`
|`false`
|Migration never applied by FusionAuth, must be applied out of band
|===

See the link:/docs/v1/tech/reference/configuration[configuration reference] or the link:/docs/v1/tech/guides/silent-mode[silent mode guide] for more information. To apply the database migrations out of band see the link:/docs/v1/tech/admin-guide/upgrade#database[database upgrade] documentation.

==== Prior to 1.19

If the installation is in `production` mode, apply the migrations out of band. 

When running in development runtime mode, silent mode was enabled based upon the presence of environment variables, such as the database user, and could not explicitly be enabled or disabled. 

=== Docker Tags

The docker compose file references the `latest` tag, but that tag is not dynamic. It is only the latest at a point in time. To get the most recently released image, you have a couple of options.

* Edit the docker compose file and specify a specific version. This is a good idea for a production deployment.
* Remove the old image first: `docker rmi <old image id>`. This command may prompt you to remove containers using that image. Since all state is stored in the database, you can safely remove the containers. Then, when you restart docker compose, the latest image will be retrieved.
* Pull the latest image with this command: `docker pull fusionauth/fusionauth-app:latest`.

== Docker Images

If you want to build your own image starting with our base image, start with the `fusionauth/fusionauth-app` image.

//TODO explain how to create a child image

== Kickstart

Using Docker with Kickstart is a powerful combination. Using these technologies together lets you:

* Configure and share development environments
* Create replicable bug reports 
* Spin up auth instances with a well known, versioned set of data for continuous integration and testing

All the normal limitations of Kickstart apply (the Kickstart will not run if the database has already been set up with an API key, for example).

It's easy to get started with Kickstart, but you'll need to tweak your Docker Compose files a bit. Before you begin, you'll need a valid `kickstart.json` file. Note that this file could be called anything, `kickstart.json` is simply a convention. Check out the link:/docs/v1/tech/installation-guide/kickstart[Kickstart documentation] for more information on writing one.

Once you have a valid `kickstart.json` file, create a subdirectory in the location of your `docker-compose.yml` file. It can be named anything; this documentation will use a directory called `kickstart`. Next, you'll mount this directory and set the `FUSIONAUTH_APP_KICKSTART_FILE` variable in the `docker-compose.yml` file. 

Here are the steps to do so:

* In the `volumes:` section of the `fusionauth` service, add `- ./kickstart:/usr/local/fusionauth/kickstart`.
* Modify `.env` and add the Kickstart configuration variable: `FUSIONAUTH_APP_KICKSTART_FILE=/usr/local/fusionauth/kickstart/kickstart.json`. This path should be what the docker container expects, not the path on the host.
* Configure `docker-compose.yml` to pass the environment variable set by `.env` to the container. Do this by adding `FUSIONAUTH_APP_KICKSTART_FILE: ${FUSIONAUTH_APP_KICKSTART_FILE}` to the `environment` section of the `fusionauth` service. 

The following is an example `docker-compose.yml` file configuring FusionAuth to run the commands in a `kickstart.json` at startup.

```yaml
version: '3'

services:
  db:
    image: postgres:12.9
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
# Un-comment to access the db service directly
#    ports:
#      - 5432:5432
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database
      FUSIONAUTH_APP_KICKSTART_FILE: ${FUSIONAUTH_APP_KICKSTART_FILE}
    networks:
     - db
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config
      - ./kickstart:/usr/local/fusionauth/kickstart

networks:
  db:
    driver: bridge

volumes:
  db_data:
  fa_config:
```

After running `docker-compose up` you should see a line like this in the output:

[source]
----
io.fusionauth.api.service.system.kickstart.KickstartRunner - Summary
----

This indicates that Kickstart completed and provides a summary of the configuration changes made by it.

You may also want to check out https://github.com/FusionAuth/fusionauth-example-scripts/tree/master/isolated-docker-setup[the Isolated Docker Setups] if you want the ability to rapidly stand up different versions and configurations of FusionAuth.

== Plugins

You can mount a directory containing a plugin to your Docker container.

Here are the steps to do so:

* In the `volumes:` section of the `fusionauth` service, add `- ./plugins:/usr/local/fusionauth/plugins`.
* Copy your plugin jar file, created link:/docs/v1/tech/plugins/[by following the instructions], to your local `plugins` directory.
* Start your Docker file

The following is an example `docker-compose.yml` file configuring FusionAuth to scan for plugins at startup.

```yaml
version: '3'

services:
  db:
    image: postgres:12.9
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
# Un-comment to access the db service directly
#    ports:
#      - 5432:5432
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database
    networks:
     - db
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config
      - ./plugins:/usr/local/fusionauth/plugins

networks:
  db:
    driver: bridge

volumes:
  db_data:
  fa_config:
```

After running `docker-compose up` you should see a line like this in the output:

[source]
----
INFO  io.fusionauth.api.plugin.guice.PluginModule - Installing plugin [com.mycompany.fusionauth.plugins.guice.MyExampleFusionAuthPluginModule]
INFO  io.fusionauth.api.plugin.guice.PluginModule - Plugin successfully installed
----

Such output indicates that the plugin has been installed and can be used.

== Accessing the Host Machine

The default FusionAuth docker configuration sets up the network using the `bridge` configuration. This means that all the hosts defined by `docker-compose` can access each other. However, it means that any applications running on your host machine cannot be accessed by FusionAuth using `localhost`.

This is typically only an issue when FusionAuth is accessing resources outside of the Docker network to, for example, send email or request a webhook. If a Rails application is running locally on a Mac and you want FusionAuth, running in Docker, to send a webhook payload to it, `localhost` won't work.

In this situation, do one of the following:

* Use `host.docker.internal` as the hostname; this works on macOS and Windows hosts
* Run a container with your application in Docker
* Install FusionAuth on the host machine, using FastPath or another method

Modifying FusionAuth to use other Docker networking schemes such as `host` may work, but isn't fully tested or supported.

