---
layout: doc
title: Fast Path Install & Upgrade
description: Get up and running faster than you can chug a latte
navcategory: installation
---

== Fast Path Install

Want to get up and running super fast on your dev box or server? Use our awesome download scripts and you'll be coding in no time. These commands will download and unpack the latest version of FusionAuth.

By default, FusionAuth installs leveraging the database as the User search engine.  You may optionally also install and configure Elasticsearch to leverage advanced search functionality.  Commands for both configurations are provided below.

=== Environment Variables
The following environment variables may be provided to the install script to augment behavior.

* `TARGET_DIR` - The location to install the zip. Defaults value is $PWD/fusionauth. This value is ignored when installing Debian or RPM packages.
* `VERSION` - The version to install. Defaults to the latest stable version.

include::docs/v1/tech/installation-guide/_fast-path-install.adoc[]

== Fast Path Upgrade

The Fast Path commands can also be used to upgrade to the latest version of FusionAuth.  Follow the steps documented below.

=== macOS
In this example, we'll assume you have previously installed FusionAuth in `/usr/local/fusionauth` and this directory will be referred to `FUSIONAUTH_HOME`. If you have used a different directory you can adjust the following example accordingly.

[source,title=Shutdown FusionAuth]
----
# Stop Services
<FUSIONAUTH_HOME>/bin/shutdown.sh
----

Then, run the appropriate FastPath install/upgrade command from the parent directory of `FUSIONAUTH_HOME` (if `FUSIONAUTH_HOME` is `/usr/local/fusionauth`, run the command from `/usr/local`).
Reference the commands defined in the install steps above to determine which install/upgrade command is appropriate for your environment.

[source,title=Start FusionAuth]
----
# Start Services
<FUSIONAUTH_HOME>/fusionauth/bin/startup.sh
----

=== Windows

In this example, we'll assume you have previously installed FusionAuth in `\fusionauth` and this directory will be referred to `FUSIONAUTH_HOME`. If you have used a different directory you can adjust the following example accordingly.

First, terminate the running FusionAuth and Elasticsearch processes.

[source,title=Shutdown FusionAuth]
----
# Stop Services
<FUSIONAUTH_HOME>\bin\shutdown.ps1
----

[NOTE]
====
If you are running a pre-1.37 version of FusionAuth, you can terminate the processes by closing the command line windows for FusionAuth and Elasticsearch. Versions 1.37 through 1.39 do not support native Windows installation.
====

Then, run the appropriate FastPath install/upgrade command from the parent directory of `FUSIONAUTH_HOME` (if `FUSIONAUTH_HOME` is `\fusionauth`, run this command from `\`).  Reference the commands defined in the install steps above to determine which install/upgrade command is appropriate for your environment.

[source,title=Start FusionAuth]
----
# Startup Services
<FUSIONAUTH_HOME>\bin\startup.ps1
----

[NOTE]
====
Prior to version 1.37 use `startup.bat` to start Elasticsearch and FusionAuth. Versions 1.37 through 1.39 do not support native Windows installation.
====

=== Linux

==== Zip
In this example, we'll assume you have previously installed FusionAuth in `/usr/local/fusionauth` and this directory will be referred to `FUSIONAUTH_HOME`. If you have used a different directory you can adjust the following example accordingly.

[source,title=Stop FusionAuth]
----
<FUSIONAUTH_HOME>/bin/shutdown.sh
----

Then, run the appropriate FastPath install/upgrade command from the parent directory of `FUSIONAUTH_HOME` (if `FUSIONAUTH_HOME` is `/usr/local/fusionauth`, run this command from `/usr/local`). Reference the commands defined in the install steps above to determine which install/upgrade command is appropriate for your environment.

[source,title=Start FusionAuth]
----
<FUSIONAUTH_HOME>/fusionauth/bin/startup.sh
----

==== RPM or DEB

[NOTE]
====
Running the update script will shut down the FusionAuth service if they have not yet been stopped The service will need to be restarted after the update is finished.
====

Then, run the appropriate FastPath install/upgrade command anywhere in your filesystem. Reference the commands defined in the install steps above to determine which install/upgrade command is appropriate for your environment.

[source,title=Start FusionAuth]
----
sudo systemctl start fusionauth-search
sudo systemctl start fusionauth-app
----
