---
layout: doc
title: Fast Path Install & Upgrade
description: Get up and running faster than you can chug a latte
---

== Fast Path Install

Want to get up and running super fast on your dev box or server? Use our awesome download scripts and you'll be coding in no time. These commands will
download and unpack the latest version of FusionAuth.

include::docs/v1/tech/installation-guide/_fast-path-install.adoc[]

== Fast Path Upgrade

The Fast Path commands can also be used to upgrade to the latest version of FusionAuth.  Follow the steps documented below.

=== macOS
In this example, we'll assume you have previously installed FusionAuth in `/usr/local/fusionauth` and this directory will be referred to `FUSIONAUTH_HOME`. If you have used a different directory you can adjust the following example accordingly.

[source,title=Shutdown FusionAuth]
----
# Stop Services
<FUSIONAUTH_HOME>/bin/shutdown.sh
----

Run the FastPath install/upgrade command from the parent directory of `FUSIONAUTH_HOME` (if `FUSIONAUTH_HOME` is `/usr/local/fusionauth`, run this command from `/usr/local`).

[source,title=Upgrade FusionAuth]
----
sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh | sh"
----

[source,title=Start FusionAuth]
----
# Start Services
<FUSIONAUTH_HOME>/fusionauth/bin/startup.sh
----

=== Windows

In this example, we'll assume you have previously installed FusionAuth in `\fusionauth` and this directory will be referred to `FUSIONAUTH_HOME`. If you have used a different directory you can adjust the following example accordingly.

[source,title=Shutdown FusionAuth]
----
# Stop Services
net stop FusionAuthApp
net stop FusionAuthSearch
----

Run the FastPath install/upgrade command from the parent directory of `FUSIONAUTH_HOME` (if `FUSIONAUTH_HOME` is `\fusionauth`, run this command from `\`).

[source,title=Upgrade FusionAuth]
----
iex (new-object net.webclient).downloadstring('https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.ps1')
----

[source,title=Start FusionAuth]
----
# Startup Services
<FUSIONAUTH_HOME>\bin\startup.bat
----

=== Linux

==== Zip
In this example, we'll assume you have previously installed FusionAuth in `/usr/local/fusionauth` and this directory will be referred to `FUSIONAUTH_HOME`. If you have used a different directory you can adjust the following example accordingly.

[source,title=Stop FusionAuth]
----
<FUSIONAUTH_HOME>/bin/shutdown.sh
----

Run the FastPath install/upgrade command from the parent directory of `FUSIONAUTH_HOME` (if `FUSIONAUTH_HOME` is `/usr/local/fusionauth`, run this command from `/usr/local`).

[source,shell,title=Upgrade FusionAuth]
----
sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh | sh -s - -z"
----

[source,title=Start FusionAuth]
----
<FUSIONAUTH_HOME>/fusionauth/bin/startup.sh
----

==== RPM or DEB

[NOTE]
====
Running the update script will shut down the FusionAuth service if they have not yet been stopped The service will need to be restarted after the update is finished.
====

Run the FastPath install/upgrade command anywhere in your filesystem.

[source,shell,title=Upgrade FusionAuth, requires sudo access]
----
sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh | sh"
----

[source,title=Start FusionAuth]
----
sudo service fusionauth-search start
sudo service fusionauth-app start
----