---
layout: doc
title: Install FusionAuth using Homebrew
description: Install FusionAuth using Homebrew
---

== Homebrew Install

Homebrew is a macOS package manager, so if you're running macOS and you're familiar with Homebrew, we've got you covered. Our Homebrew formula is open source and available on GitHub.
https://github.com/FusionAuth/homebrew-fusionauth

To install FusionAuth using brew, first install the Tap, you will only need to do this step once.

```
brew tap fusionauth/homebrew-fusionauth
```

Next, install the FusionAuth services, you can optionally skip the `fusionauth-search` service if you would like to use the database as the User search engine, or if you already have a compatible Elasticsearch service running. See the link:./system-requirements[System Requirements] and link:../reference/configuration[Configuration Reference].

```
brew install fusionauth-app fusionauth-search
```

That's it!  Now fire it up!

```
brew services start fusionauth-search
brew services start fusionauth-app
```

Now to get started open your browser to `\http://localhost:9011`, and complete maintenance mode and the setup wizard.

The shared configuration file will be located here: `/usr/local/etc/fusionauth/fusionauth.properties` and the logs are here : `/usr/local/var/log/fusionauth/`.

== Homebrew Upgrade

If you initially installed FusionAuth using Homebrew, you can also use Homebrew to upgrade to the latest version of FusionAuth.

To upgrade FusionAuth using brew, first stop services.

```
brew services stop fusionauth-search
brew services stop fusionauth-app
```

Next, upgrade services.

```
brew upgrade fusionauth-app fusionauth-search
```

Start services

```
brew services start fusionauth-search
brew services start fusionauth-app
```