---
layout: doc
title: Kickstart
description: Automate development and production deployment using Kickstart
---

== Kickstart

FusionAuth Kickstart is super easy and if you can do it with an API, you can do it in Kickstart. Kickstart allows you to build a template that will be executed during startup to quickly replicate development or production environments.

The kickstart file is a collection of one or more API keys and a list of API requests. You can call `POST`, `PUT` or `PATCH` on any API that you like and each request will be executed in order using the primary API key defined in the bootstrap file.


== Getting Started

Let's work from simple to complex, each example will introduce a new feature so you can learn how to best build and leverage the options available to you as you build out your kickstart file.

The examples found here, as well as community contributed examples may also be found on GitHub in the FusionAuth Kickstart repository.
* https://github.com/FusionAuth/fusionauth-kickstart-examples

=== The Shortest

Here is the simplest kickstart file you can use, it simply adds a single API key and that's it. This may be useful if you intend to complete the rest of your setup by calling APIs in your own application or development setup script.

```json
{
  "apiKeys": [{
      "key": "4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd"
  }],
  "requests": [
  ]
}
```

=== Using Variables

You may find yourself repeating yourself when you build your kickstart file, nobody likes to type the same value over and over. Use variables to help you when you find yourself typing the same value over and over.

Here is the same example as above, but instead of hard coding the API key, we are using a variable which can be re-used. This example is not particularly helpful, we've only moved the value from the `apiKeys` section to the `variables` section, but using variables may come in handy.

```json
{
  "variables":{
    "apiKey": "4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd"
  }
  "apiKeys": [{
      "key": "${apiKey}"
  }],
  "requests": [
  ]
}
```

=== Using Environment Variables

It is reasonable to think you may not want to hard code a password or API key in the kickstart file which could get checked into Git. You can use environment variables which should make this a bit easier for you.

To use an environment variable in your kickstart file, use the `variables` object, an environment variable can only be used in a variable definition while once defined any variable can be used anywhere else in kickstart file.

Here is the same example as above, but instead of hard coding the API key, we are picking it up from an environment variable. Here we will resolve the value of the API key in the environment variable named `FUSIONAUTH_API_KEY`. This value will be set into the variable `apiKey` and then when the API key is constructed the value of the API key will be resolved to the `apiKey` variable value.

```json
{
  "variables":{
    "apiKey": "${ENV.FUSIONAUTH_API_KEY}"
  }
  "apiKeys": [{
      "key": "${apiKey}"
  }],
  "requests": [
  ]
}
```