---
layout: doc
title: Monitoring FusionAuth
description: Understand how your installation is operating by monitoring it.
---

== Overview

You can monitor FusionAuth in a number of ways.

=== Log Files

The system log files will be placed in the `logs` directory under the FusionAuth installation unless you are running FusionAuth in a container. In the latter case, the log output will be sent to STDOUT. 

System logs running in non-containerized instances can also be exported via the link:/docs/v1/tech/apis/system/#export-system-logs[Export System Logs API].

link:/docs/v1/tech/troubleshooting/#logs[Learn more about FusionAuth log files].

=== Application Logging

There are a few different APIs exposing FusionAuth application specific information you may want to ingest into your monitoring system:

* link:/docs/v1/tech/apis/audit-logs/[FusionAuth administrative user interface audit logs]
* link:/docs/v1/tech/apis/event-logs/[Logs and errors from asynchronous code executation]
* link:/docs/v1/tech/apis/login/#export-login-records[Login records]

In general these are APIs you will have poll to ingest.

=== Application Events

There are a a number of events, such as a failed authentication or an account deletion, that you may want to ingest into your monitoring system. These are available as webhooks. 

Here's link:/docs/v1/tech/events-webhooks/events/[the list of all available events].

=== Metrics

You can pull system metrics from the link:/docs/v1/tech/apis/system/#retrieve-system-status[System API]. The format of these metrics are evolving and thus are not documented.

You can also enable JMX metrics as outlined in the link:/docs/v1/tech/troubleshooting/#enabling-jmx[Troubleshooting documentation].

==== Prometheus Endpoint

The default system metrics are also available in a Prometheus compatible form. link:/docs/v1/tech/tutorials/prometheus[This tutorial explains how to set up Prometheus to scrape the FusionAuth metrics].
