---
layout: doc
title: Monitoring FusionAuth
description: Understand how your installation is operating by monitoring it.
---

== Overview

You can monitor FusionAuth in a number of ways.

=== Log Files

The system log files will be placed in the `logs` directory under the FusionAuth installation unless you are running FusionAuth in a container. In the latter case, the log output will be sent to STDOUT. 

System logs running in non-containerized instances can also be exported via the link:/docs/v1/tech/apis/system/#export-system-logs[Export System Logs API].

link:/docs/v1/tech/troubleshooting/#logs[Learn more about FusionAuth log files].

=== Application Logging

There are a few different APIs exposing FusionAuth application specific information you may want to ingest into your monitoring system:

* link:/docs/v1/tech/apis/audit-logs/[FusionAuth administrative user interface audit logs]
* link:/docs/v1/tech/apis/event-logs/[Logs and errors from asynchronous code executation]
* link:/docs/v1/tech/apis/login/#export-login-records[Login records]

In general these are APIs you will have poll to ingest.

=== Log File Formats

.Log File Information
[cols="1,3,3,3,1"]
|===
| Log Type | Export Format | Timezone | Date Format | API Docs

| Audit Logs
| Zipped CSV
| Specified by the `zoneId` parameter
| Specified by the `dateTimeSecondsFormat` parameter, defaults to `M/d/yyyy hh:mm:ss a z`
| link:/docs/v1/tech/apis/audit-logs/[API]

| Event Logs
| JSON
| UTC
| link:/docs/v1/tech/reference/data-types/#instants[Instant]
| link:/docs/v1/tech/apis/event-logs/[API]

| Login Records
| Zipped CSV
| Specified by the `zoneId` parameter
| Specified by the `dateTimeSecondsFormat` parameter, defaults to `M/d/yyyy hh:mm:ss a z`
| link:/docs/v1/tech/apis/login/#export-login-records[API]

| System Logs
| Zipped directory of files. Log entries separated by newlines, but may be unstructured (stack traces, etc).
| For log entries, the timezone of the server. The `zoneId` parameter, if provided, is used to build the filename.
| `yyyy-MM-dd h:mm:ss.SSS a`
| link:/docs/v1/tech/apis/system/#export-system-logs[API]

|===

[NOTE]
====
There are currently no plugins for ingesting FusionAuth logs into a log management system. A polling script using a link:/docs/v1/tech/client-libraries/[client library] is usually sufficient. Please https://github.com/FusionAuth/fusionauth-issues/issues[file an issue] if this does not meet your use case.
====

=== Application Events

There are a number of events, such as a failed authentication or an account deletion, that you may want to ingest into your monitoring system. These are available as webhooks. 

Here's link:/docs/v1/tech/events-webhooks/events/[the list of all available events].

=== Metrics

You can pull system metrics from the link:/docs/v1/tech/apis/system/#retrieve-system-status[System API]. The format of these metrics are evolving and thus are not documented.

You can also enable JMX metrics as outlined in the link:/docs/v1/tech/troubleshooting/#enabling-jmx[Troubleshooting documentation].

==== Prometheus Endpoint

The default system metrics are also available in a Prometheus compatible form. link:/docs/v1/tech/tutorials/prometheus[This tutorial explains how to set up Prometheus to scrape the FusionAuth metrics].

=== Load Testing

You can load test FusionAuth to determine if its performance will meet your calculated needs. The FusionAuth team tests the performance of FusionAuth regularly, but every situation is different and running your own load tests on your instance provides useful information.

You may use your own load testing tool. Any tool which can make HTTP requests, such as gatling or jmeter, will work.

There is an https://github.com/FusionAuth/fusionauth-load-tests/[open source project] which provides some useful scripts for load testing. This is a work in progress, so use at your own risk. Scenarios currently supported include:

* Creating tenants
* Creating applications
* Registering users for applications
* Logging users in using the Login API
* Beginning the Authorization Code grant

