---
layout: doc
title: Packages
description: Determine which installation packages you need
---

:sectnumlevels: 0

== What Packages do I need?

If you will be manually installing packages, you'll have a choice of a few packages on the package link:/download/[Downloads] page.

Review the following information to understand which packages you need to download. If your target platform is Linux, using the RPM or DEB packages is preferred and provides the simplest installation process. The Zip package may be used on macOS, Linux or Windows.

== FusionAuth App

The FusionAuth App is the web service that handles all API calls and provides the web based management interface. You will always need to download this package since it is the core component of FusionAuth.

== FusionAuth Search

[NOTE]
====
The FusionAuth Search package is intended for a single node Elasticsearch configuration.  In order to use the FusionAuth Search package in a multi-node configuration, you will need to modify the shipped `elasticsearch.yml` configuration file accordingly.
====

The FusionAuth Search package contains the Elasticsearch service that FusionAuth uses to provide advanced and performant search capabilities of users. This package is provided to ease setup using Elasticsearch as the search engine.  This package is optional, and you may configure FusionAuth to connect with any Elasticsearch cluster running a supported version of Elasticsearch.

FusionAuth ships configured to use the database as the default search engine type, you will need to update the configuration to leverage Elasticsearch as the search engine.  See the link:/docs/v1/tech/reference/configuration/[Configuration] documentation for reference in configuring the search engine.

== Database

The database package contains the schema and migration scripts to support upgrades as the schema changes. In most cases, you will not need to use this package. Instead, FusionAuth App will enter Maintenance Mode when it is started and this will automatically create the database or upgrade it. If you need to perform unattended installs or upgrades of FusionAuth, you will need to download this package for the schema and migration SQL scripts. You can review the link:/docs/v1/tech/installation-guide/fusionauth-app#advanced-installation[Advanced Installation] portion of the link:/docs/v1/tech/installation-guide/fusionauth-app/[Install FusionAuth App] section to learn more about unattended installations and upgrades.
