---
layout: doc
title: Securing FusionAuth services
description: Secure your installation by limiting network traffic
---

:sectnumlevels: 0

== Securing

If you're installing FusionAuth on your own server, use the following guide as a baseline for securing the network services. If you need further assistance to secure FusionAuth, please ask a question in the https://fusionauth.io/community/forum/[FusionAuth forum, window="_blank"]. If you have a licensed edition you may open a https://account.fusionauth.io/account/support/[support request from your account, window="_blank"].

== Required ports
See the link:/docs/v1/tech/reference/configuration/[Configuration Reference] for more information on default port configuration. The documentation below
assumes the default port configuration.

=== FusionAuth Search

If FusionAuth Search is running on the same system as the FusionAuth App service and you're only running a single instance of FusionAuth
App then no external ports should be allowed for FusionAuth Search. In this scenario, FusionAuth App will access the Elasticsearch
service on port `9021` on the `localhost` address. The default configuration should cause FusionAuth Search to only bind to `127.0.0.1` or other
localhost addresses. See `fusionauth-search.hosts` in the link:/docs/v1/tech/reference/configuration/[Configuration Reference].

If FusionAuth App is installed on multiple servers and those servers can communicate across a private network using a site local address then
the default FusionAuth Search Configuration will not bind to any public IP addresses. In this scenario you will need to allow access to
ports `9020` and `9021` on the site local IP address.

It is not recommended to expose FusionAuth Search to any public network. If this is a requirement, then a firewall should be used to limit traffic to the service based upon the source and destination IP address. 

To protect FusionAuth Search with HTTP basic authentication as well as a firewall, provide the username and password in the URL, like so: `search.servers=http://user:password@myelasticsearchcluster.com`. Support for basic authentication was introduced in version 1.16.

The `9020` port is utilized by Elasticsearch for internal communication including clustering. The `9021` port is the HTTP port utilized by
FusionAuth App to make requests to the search index.

=== FusionAuth App

To access the FusionAuth UI you'll need to open port `9011`. If you have more than one instance of FusionAuth installed you will need
to ensure that each instance of FusionAuth Backend can communicate on port `9011`.

== Custom Certificates

FusionAuth ships with the default `cacerts` file from OpenJDK. There are times when you need to add a certificate to the keystore. This might occur if:

* You are using a self signed certificate.
* Your certificate authority does not ship with the version of Java that FusionAuth uses.

[WARNING.warning]
====
This operation modifies the security of your FusionAuth installation. Ensure that you know the provenance of this certificate and trust the issuer.
====

In some cases, such as with link:/docs/v1/tech/events-webhooks/securing/[webhooks], you may provide your own certificate via the FusionAuth API or UI, but you may need to install the certificate globally. You'll have to import this certificate in every FusionAuth installation.

To add this, we need to use `keytool` to augment the Java keystore. First, find the Java installation that is running FusionAuth. This is typically at `FA_INSTALL_DIR/java/` where `FA_INSTALL_DIR` is where you installed FusionAuth. This is often at `/usr/local/fusionauth` but may vary.

For this documentation, if your Java installation is at `/usr/local/fusionauth/java/current/`, the `/usr/local/fusionauth/java/current/lib/security/cacerts` file should be modified. Let's also assume the new certificate authority public key file is located at `newcacert.pem`, and that you haven't changed your keystore password from the default value, which is `changeit`.

Import the certificate with this command:

[source,sh]
====
/usr/local/fusionauth/java/current/bin/keytool -importcert -file newcacert.pem -keystore fusionauth/java/current/lib/security/cacerts -storepass changeit  -alias faselfsignedcert
====

Then, restart FusionAuth.

If you are using the docker image, you'll have to build a custom dockerfile based on the FusionAuth dockerfile which runs the keytool import command above. The base FusionAuth dockerfile is available in the https://github.com/fusionauth/fusionauth-containers[fusionauth-containers repo].

