---
layout: doc
title: System Requirements
description: The minimum system requirements required to install and run FusionAuth
---

== System Requirements

FusionAuth will install and run on nearly any system. We have done our best to document the supported configurations here. If you
have any questions about platform support, please ask a question on https://fusionauth.io/community/forum/[the forum, window="_blank"] or open an issue on https://github.com/FusionAuth/fusionauth-issues/issues/new/choose[Github, window="_blank"]. If you have a licensed edition you may send a request to support@fusionauth.io. Please read through this documentation and ensure you have met all of
the requirements before continuing with the installation of FusionAuth.

== Operating System

FusionAuth will run on most platforms. We do have a few minor requirements, they are to run Java8 in 64-bit mode and when running on Windows we require WMF 5.0 or newer. The following list summarizes the supported platforms.

* Linux - all distributions (64-bit)
* macOS 10.8 (Mountain Lion) or newer
* Windows Server 2012 R2 (64-bit) w/ Windows Management Framework 5.0 or newer
* Windows 10 (64-bit) w/ Windows Management Framework 5.0 or newer

Docker, k8s and other container platforms are supported and because the host operating system is based upon Linux.

== Memory

The minimum memory required to run FusionAuth will vary depending upon the number of users you expect and the general intended system capacity.

General guideline: `512M`

If you have memory lying around, feel free to throw more at it - but in a multi-node configuration `512M` to `1GB` assigned per node should be very adequate.

If you intend to run Elasticsearch and FusionAuth on the same host you will need to ensure the host has adequate memory for both services and ensure you have adequate disk space for the Elasticsearch index to be stored.

Considerations that may require a larger amount of memory:

* Bulk importing users into FusionAuth. If you are importing in chunks of 250k to 500k it is possible FusionAuth will require additional memory to complete this request.
* > 1k Lambdas. Lambdas need to be pre-compiled, cached and sandboxed in their own JavaScript engine for use a runtime. Creating thousands of Lambdas will increase your memory requirements due to what is needed to keep in memory at runtime.
* > 1k Tenants. There are tasks that require a full traversal of all tenants, when you have 1000's of tenants these tasks may affect performance and will increase your memory requirements.
* > 1k Applications. There are tasks that require a full traversal of all applications, when you have 1000's of applications these tasks may affect performance and will increase your memory requirements.


== Database

* MySQL 5.7.9 or newer.
** IBM Compose for MySQL or other MysQL platforms that utilize MySQL Group Replication are not supported.
** MariaDB and Percona are known to work, however these variants are not actively tested against by FusionAuth. Please do let us know if you run into an issue.
** See https://github.com/FusionAuth/fusionauth-issues/issues/327[MariaDB known issues] on out GitHub issues.
* PostgreSQL 9.5 or newer

== Elasticsearch

Elasticsearch is optional, and may be leveraged for improving user search functionality.  See the link:../core-concepts/users#user-search[Core Concepts - User] documentation for reference in configuration and usage.

If you will be running Elasticsearch on the same host as FusionAuth, please ensure there is adequate RAM for both services to operate normally. Elasticsearch may also protect the index by moving it to read-only if the underlying host is running low on disk space, ensure you have plenty of free storage for the Elasticsearch index.

* You can use the link:packages#fusionauth-search[`fusionauth-search`] package or any other Elasticsearch service including a cloud hosted service or just downloading it and installing it yourself from https://www.elastic.co/products/elasticsearch[elastic.co].
* Versions 6.3.x - 7.6.x are currently supported, later versions may work as well but may not have been tested for compatibility.
