---
layout: doc
title: Implementing Single Sign-on
description: How to implement single sign-on with FusionAuth
---
:page-liquid:


This tutorial will walk you through setting up single sign-on between two web applications both using FusionAuth as their authentication and authorization server.

You'll set up two applications:

* Pied Piper
* Hooli

At the end of this tutorial, you'll have both applications running and be able to log in to Hooli. Then if you visit Pied Piper, you will be automatically signed in with no effort on the end user's part. Finally, if you sign out from either of them, you'll be signed out from both the Pied Piper and Hooli applications.

This will scale to any number of applications, including commerical off the shelf apps. So if you have a suite of applications, you can provide seamless single sign-on for all your users. 


== Concepts

First, it's worth talking about sessions. Sessions are how servers know they've seen the browser before. They are usually used with cookies, but the actual implementation doens't matter too much. In the SSO scenario, you have the following sessions:

* FusionAuth's session
* The Pied Piper application's session
* The Hooli application's session

You also have a JSON web token, but for the typical single sign-on scenario it plays a minor role.

If a session doesn't exist for a given application, then it must be created after credentials are presented. For FusionAuth, the credentials are the username and password of the user, but for the other sessions, the credential is a valid token from FusionAuth.

== Request Flows

Here's the flow of the single sign-on request.

++++
{% plantuml source: _diagrams/docs/tutorials/sso-login.plantuml, alt: "Single sign-on request flow during login" %}
++++

Here's the flow of a logout request.

++++
{% plantuml source: _diagrams/docs/tutorials/sso-logout.plantuml, alt: "Single sign-on request flow during logout" %}
++++

== Prerequisites

You will need to have FusionAuth and node installed. For FusionAuth installation instructions, visit link:/docs/v1/tech/5-minute-setup-guide/[the 5 minute setup guide].

== Configure The Applications

== Set Up The Domains

In order to properly exercise single sign-on, you should 


== Set Up The Code

== Test The Results

video

== Other Scenarios

In this tutorial users who click on the Hooli link are auto logged in. This is appropriate for most applications. However, if you have an application with limited ability to customize the login process, you can still use single sign-on. Your users may have to click on a link to FusionAuth. Once that happens, FusionAuth will recognize the user as being logged in and redirect them back without requiring credentials.


configuration
two types of sso
one requiring click other not
logout functionality
sessions
authorization check


