---
layout: doc
title: Tutorial Overview
description: An overview of the FusionAuth Tutorials
---

:page-liquid:

:sectnumlevels: 0

== Overview

This section contains a number of tutorials that will help you get started with FusionAuth quickly. You can work through each of the tutorials or jump to the one that fits your needs.


=== Getting Started

Here are tutorials to help you get up and running:

* link:/docs/v1/tech/tutorials/setup-wizard/[Setup Wizard & First Login]
* link:/docs/v1/tech/tutorials/register-user-login-api/[Register a User and Login via the API]
* link:/docs/v1/tech/tutorials/migrate-users/[Migrate Users from Another Database]
* link:/docs/v1/tech/tutorials/start-and-stop/[Start and Stop FusionAuth]

Bonus link: link:/docs/v1/tech/5-minute-setup-guide/[The 5 Minute Setup Guide]

=== FusionAuth Features

Here are tutorials about specific topics and FusionAuth features: 

* link:/docs/v1/tech/tutorials/application-authentication-tokens/[Application Authentication Tokens]
* link:/docs/v1/tech/tutorials/gate-accounts-until-verified/[Gate a User Until They Verify Their Email]
* link:/docs/v1/tech/tutorials/json-web-tokens/[JSON Web Tokens]
* link:/docs/v1/tech/tutorials/prometheus/[Prometheus Setup]
* link:/docs/v1/tech/tutorials/switch-search-engines/[Switch Search Engines]
* link:/docs/v1/tech/tutorials/two-factor/[Two Factor Authentication (pre 1.26)]
* link:/docs/v1/tech/tutorials/setting-up-user-account-lockout/[User Account Lockout]

==== FusionAuth Paid Features

Here are tutorials about FusionAuth reactor features available with a paid edition: 

++++
{% capture relatedTag %}tutorial-reactor-feature{% endcapture %}
{% capture noheader %}true{% endcapture %}
{% include _doc_related_posts.liquid %}
++++

=== Integration Tutorials

Here are tutorials about integrating FusionAuth with other systems.


Bonus link: link:/docs/v1/tech/core-concepts/integration-points/[Integration Points]

=== All Tutorials

Here are tutorials in specific languages: 

You can also check out the link:/docs/v1/tech/guides/[guides section]. Guides are deeper dives into particular technical areas.
