---
layout: doc
title: Tutorial Overview
description: An overview of the FusionAuth Tutorials
navcategory: getting-started
---

:page-liquid:

:sectnumlevels: 0

== Overview

This section contains a number of tutorials that will help you get started with FusionAuth quickly. You can work through each of the tutorials or jump to the one that fits your needs. You can also check out the link:/docs/v1/tech/guides/[guides section]. Guides are deeper dives into specific technical areas.

=== Getting Started

Here are tutorials to help you get up and running:

* link:/docs/v1/tech/tutorials/setup-wizard[Setup Wizard & First Login]
* link:/docs/v1/tech/tutorials/start-and-stop[Start and Stop FusionAuth]

Bonus link: link:/docs/v1/tech/5-minute-setup-guide[The 5 Minute Setup Guide]

=== FusionAuth Features

Here are tutorials about specific topics and FusionAuth features.

Tutorials in the documentation section:

* link:/docs/v1/tech/tutorials/application-authentication-tokens[Application Authentication Tokens]
* link:/docs/v1/tech/tutorials/gating/gate-accounts-until-user-email-verified[Gate a User Until They Verify Their Email]
* link:/docs/v1/tech/tutorials/key-rotation[Key Rotation]
* link:/docs/v1/tech/tutorials/json-web-tokens[JSON Web Tokens]
* link:/docs/v1/tech/tutorials/prometheus[Prometheus Setup]
* link:/docs/v1/tech/tutorials/switch-search-engines[Switch Search Engines]
* link:/docs/v1/tech/tutorials/two-factor/[Two Factor Authentication (pre 1.26)]
* link:/docs/v1/tech/tutorials/gating/setting-up-user-account-lockout[User Account Lockout]

=== Integration Tutorials

* link:/docs/v1/tech/tutorials/integrate-expressjs[Integrate Express.js With FusionAuth]
* link:/docs/v1/tech/tutorials/integrate-flutter[Integrate Flutter With FusionAuth]
* link:/docs/v1/tech/tutorials/integrate-java-spring[Integrate Java Spring With FusionAuth]
* link:/docs/v1/tech/tutorials/integrate-python-django[Integrate Python Django With FusionAuth]
* link:/docs/v1/tech/tutorials/integrate-python-flask[Integrate Python Flask With FusionAuth]
* link:/docs/v1/tech/tutorials/integrate-react[Integrate React With FusionAuth]
* link:/docs/v1/tech/tutorials/integrate-ruby-rails[Integrate Ruby on Rails With FusionAuth using Omniauth]
* link:/docs/v1/tech/tutorials/integrate-ruby-rails-api[Integrate a Ruby on Rails API With FusionAuth]

=== Other Tutorials

Here are tutorials from the blog:

++++
{% capture relatedTag %}tutorial-feature{% endcapture %}
{% capture noheader %}true{% endcapture %}
{% include _doc-related-posts.liquid %}
++++

==== FusionAuth Paid Features

Here are tutorials about FusionAuth reactor features available with a paid edition:

++++
{% capture relatedTag %}tutorial-reactor-feature{% endcapture %}
{% capture noheader %}true{% endcapture %}
{% include _doc-related-posts.liquid %}
++++

=== Integration Blog Posts

Here are some blog posts covering integrating FusionAuth with other systems and frameworks.

++++
{% capture relatedTag %}tutorial-integration{% endcapture %}
{% capture noheader %}true{% endcapture %}
{% include _doc-related-posts.liquid %}
++++

Bonus link: link:/docs/v1/tech/core-concepts/integration-points[Integration Points]

=== All Tutorials

Here are all the tutorials:

++++
{% capture relatedTag %}tutorial{% endcapture %}
{% capture noheader %}true{% endcapture %}
{% include _doc-related-posts.liquid %}
++++

