---
layout: doc
title: Tutorial Overview
description: An overview of the FusionAuth Tutorials
navcategory: getting-started
---

:page-liquid:

:sectnumlevels: 0

== Overview

This section contains a number of tutorials that will help you get started with FusionAuth quickly. You can work through each of the tutorials or jump to the one that fits your needs. You can also check out the link:/docs/v1/tech/guides/[guides section]. Guides are deeper dives into specific technical areas.

=== Getting Started

Here are tutorials to help you get up and running:

* link:/docs/v1/tech/tutorials/setup-wizard[Setup Wizard & First Login]
* link:/docs/v1/tech/tutorials/start-and-stop[Start and Stop FusionAuth]

Bonus link: link:/docs/v1/tech/5-minute-setup-guide[The 5 Minute Setup Guide]

=== FusionAuth Features

Here are tutorials about specific topics and FusionAuth features.

Tutorials in the documentation section:

* link:/docs/v1/tech/tutorials/application-authentication-tokens[Application Authentication Tokens]
* link:/docs/v1/tech/tutorials/gating/gate-accounts-until-user-email-verified[Gate a User Until They Verify Their Email]
* link:/docs/v1/tech/tutorials/key-rotation[Key Rotation]
* link:/docs/v1/tech/tutorials/json-web-tokens[JSON Web Tokens]
* link:/docs/v1/tech/tutorials/prometheus[Prometheus Setup]
* link:/docs/v1/tech/tutorials/switch-search-engines[Switch Search Engines]
* link:/docs/v1/tech/tutorials/two-factor/[Two Factor Authentication (pre 1.26)]
* link:/docs/v1/tech/tutorials/gating/setting-up-user-account-lockout[User Account Lockout]

=== Integration Tutorials

See link:/docs/quickstarts[Quickstarts] which guide you through integration with FusionAuth for a variety of languages, frameworks and situations.

