---
layout: doc
title: Integrate Your Python Flask Application With FusionAuth
description: Integrate your Python Flask application with FusionAuth
navcategory: getting-started
---

:page-liquid:

// TBD how much these are useful
:prequisites: python3 and pip3
:technology: Python Flask
:language: python

== Integrate Your {technology} Application With FusionAuth

In this article, you are going to learn how to integrate a {technology} application with FusionAuth.

Here's a typical application login flow before integrating FusionAuth into your {technology} application..

== Prerequisites

For this tutorial, you’ll need to have {prequisites} installed. You'll also need Docker, since that is how you'll install FusionAuth.

The commands below are for macOS, but are limited to `mkdir` and `cd`.

== Download and Install FusionAuth

First, make a project directory:

[source,shell]
----
mkdir integrate-fusionauth && cd integrate-fusionauth
----

Then, install FusionAuth:

[source,bash]
----
curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml
https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.override.yml
curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env
docker-compose up -d
----

== Create a User and an API Key

Next, http://localhost:9011[log into your FusionAuth instance].
You’ll need to set up a user and a password, as well as accept the terms and conditions.

Then, you’re at the FusionAuth admin UI.
This lets you configure FusionAuth manually.
But for this tutorial, you're going to create an API key and then you’ll configure FusionAuth using our {language} client library.

Navigate to [breadcrumb]#Settings -> API Keys#. Click the [uielement]#+# button to add a new API Key.
Copy the value of the [field]#Key# field and then save the key.
It might be a value like `CY1EUq2oAQrCgE7azl3A2xwG-OEwGPqLryDRBCoz-13IqyFYMn1_Udjt`.

Doing so creates an API key that can be used for any FusionAuth API call.
Save that key value off as you’ll be using it later.

== Configure FusionAuth

Next, you need to set up FusionAuth.
This can be done in different ways, but we’re going to use the {language} client library.
The below instructions use maven from the command line, but you can use the client library with an IDE of your preference as well.

First, make a directory:

[source,shell]
----
mkdir setup-fusionauth && cd setup-fusionauth
----

If you want, you can http://localhost:9011[login to your instance] and
examine the new application configuration the script created for you after you are done.

Now, cut and paste the following file into `requirements.txt`.

[source,text,title="Your FusionAuth configuration requirements file"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-client-libraries/main/python/requirements.txt[]
----

Then copy and paste the following code into the `setup.py` file.

[source,python]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-client-libraries/main/python/setup.py[]
----

Then, you can run the setup script. You'll use `venv` to keep your workspace clean. This will create FusionAuth
configuration for your {technology} application.

[source,shell]
----
python -m venv venv && \
source venv/bin/activate && \
pip install -r requirements.txt 
----

Now run the setup script:

[source,shell]
----
fusionauth_api_key=<your API key> python setup.py
----

This configures FusionAuth for your {technology} application.

== Create Your {technology} Application

Now you are going to create a {technology} application. While this section builds a simple {technology} application, you can use the same configuration to integrate your complex {technology} application with FusionAuth.

