---
layout: doc
title: Integrate Your Ruby on Rails Application With FusionAuth
description: Integrate your Ruby on Rails application with FusionAuth
navcategory: getting-started
---

:page-liquid:

:prequisites: Ruby, bundler and Rails
:technology: Ruby on Rails
:language: Ruby

== Integrate Your {technology} Application With FusionAuth

include::docs/v1/tech/tutorials/_integrate-intro.adoc[]

// you can't include these since they are liquid plugins
++++
{% plantuml source: _diagrams/docs/login-before.plantuml, alt: "Login before FusionAuth." %}
++++

And here's the same application login flow when FusionAuth is introduced.
++++
{% plantuml source: _diagrams/docs/login-after.plantuml, alt: "Login with FusionAuth." %}
++++

== Prerequisites

include::docs/v1/tech/tutorials/_integrate-prerequisites.adoc[]

== Download and Install FusionAuth

include::docs/v1/tech/tutorials/_integrate-install-fusionauth.adoc[]

== Create a User and an API Key

include::docs/v1/tech/tutorials/_integrate-add-user.adoc[]

== Configure FusionAuth

Next, you need to set up FusionAuth.
This can be done in different ways, but we’re going to use the {language} client library.
The below instructions use maven from the command line, but you can use the client library with an IDE of your preference as well.

First, make a directory:

[source,shell]
----
mkdir setup-fusionauth && cd setup-fusionauth
----

Now, copy and paste the following file into `Gemfile`.

[source,ruby,title="Your FusionAuth Gemfile"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-client-libraries/main/ruby/Gemfile[]
----

Install the gems.

[source,shell]
----
bundle install
----

Then copy and paste the following code into the `setup.rb` file.

[source,ruby]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-client-libraries/main/ruby/setup.rb[]
----

Then, you can run the setup script.

++++
{% include _callout-note.liquid content="The setup script is designed to run on a newly installed FusionAuth instance with only one user and no tenants other than `Default`. To follow this guide on a FusionAuth instance that does not meet these criteria, you may need to modify the above script. <br><br> Refer to the [Ruby client library](/docs/v1/tech/client-libraries/ruby) documentation for more information." %}
++++

This will create the FusionAuth configuration for your {technology} application.

[source,shell]
----
fusionauth_api_key=YOUR_API_KEY_FROM_ABOVE ruby setup.rb
----

If you are using PowerShell, you will need to set the environment variable in a separate command before executing the script.

[source,shell]
----
$env:fusionauth_api_key='YOUR_API_KEY_FROM_ABOVE'
ruby setup.rb
----

If you want, you can http://localhost:9011[login to your instance] and examine the new application configuration the script created for you.


== Create Your {technology} Application

Now you are going to create a {technology} application. While this section uses a
simple {technology} application, you can use the same configuration to
integrate your {technology} application with FusionAuth.

First, make a directory:

[source,shell]
----
mkdir ../setup-ruby-on-rails && cd ../setup-ruby-on-rails
----

Then, set up a new rails app.

[source,shell]
----
rails new myapp && cd myapp
----

Install the omniauth gem and other supporting gems. Add the following to your Gemfile.

[source,ruby]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/Gemfile[tags=gemfile]
----

Then, install them.

[source,shell]
----
bundle install
----

Next, update your `config/environments/development.rb` file with FusionAuth OIDC configuration information.

[source,ruby]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/config/environments/development.rb[tags=oidcConfig]
----

[NOTE.note]
====
You'll have to add similar configuration to the relevant environment files when deploying to prod or other environments.
====

Create a file called `omniauth.rb` in the `config/initializers` directory. Add the below to the file.

[source,ruby,title="Your omniauth.rb initializer"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/config/initializers/omniauth.rb[]
----

This pulls from the environment file and configures omniauth to communicate with FusionAuth.

Next, you can create the following controllers and scaffolding.

[source,shell]
----
rails generate controller auth
rails generate controller home
rails generate scaffold todos
rails db:migrate
----

These controllers have the following purposes:

* `auth` is for omniauth integration
* `home` is an unprotected home page with a login button
* `todos` is a set of protected CRUD pages; in a real world application these would be built out further.

First, let's update the `config/routes.rb` file. Here's what that should look like:

[source,ruby,title="Your routes"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/config/routes.rb[]
----

Nothing too special here:

* `todos` is the CRUD resource.
* `login` points you to the home page, which is available to unauthenticated users. This is also the default page.
* `logout` is tied to the auth controller's logout method.
* `auth/:provider/callback` is the omniauth callback method, which completes the OIDC grant.

Now, update the auth controller at `app/controllers/auth_controller.rb` to look like this, which fulfills some of the routes above.

This lets us have a nice `logout` method and also handle the callback from omniauth. The latter sets a `session` attribute with user data, which can be used by views later.

[source,ruby,title="Your auth controller"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/app/controllers/auth_controller.rb[]
----

Now, update the application controller at `app/controllers/application_controller.rb`. You're enforcing authentication for all routes in your application by checking for the session attribute set by the auth controller after a successful login.

[source,ruby,title="Your application controller"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/app/controllers/application_controller.rb[]
----

Now, let's build out the home page. Update the home controller at `app/controllers/home_controller.rb` to look like this:

[source,ruby,title="Your homepage controller"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/app/controllers/home_controller.rb[]
----

You're skipping authentication for this route. This is so that a user has someplace to go if they are unauthenticated.

The view is also welcoming, but prompts them to login. Replace `app/views/home/index.html.erb` with this:

[source,ruby,title="Your homepage view"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/app/views/home/index.html.erb[]
----

Finally, update the layout so the user has login or logout buttons on every page. Add the below code just after the `<body>` tag.

[source,ruby,title="An excerpt of changes to your layout"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/app/views/layouts/application.html.erb[tags=loginLogout]
----

Once you’ve created these files, start up the {technology} application using this command: 

[source,shell,title="Start the application"]
----
OP_SECRET_KEY=change-this-in-production-to-be-a-real-secret bundle exec rails s
----

`OP_SECRET_KEY` is the client secret, which was defined by the <<Configure FusionAuth>> step. You don't want to commit secrets like this to version control, so use an environment variable.

You can now open up an incognito window and visit http://localhost:3000[the {technology} app].
Log in with the user account you created when setting up FusionAuth, and you’ll see the email of the user next to a logout link.

