---
layout: doc
title: Integrate Your Python Django Application With FusionAuth
description: Integrate your Python Django application with FusionAuth
navcategory: getting-started
---

:page-liquid:

:prequisites: python3 and pip3
:technology: Python Django
:language: python

== Integrate Your {technology} Application With FusionAuth

include::docs/v1/tech/tutorials/_integrate-intro.adoc[]

++++
{% plantuml source: _diagrams/docs/login-before.plantuml, alt: "Login before FusionAuth." %}
++++

And here's the same application login flow when FusionAuth is introduced.
++++
{% plantuml source: _diagrams/docs/login-after.plantuml, alt: "Login with FusionAuth." %}
++++


== Prerequisites

include::docs/v1/tech/tutorials/_integrate-prerequisites.adoc[]

== Download and Install FusionAuth

include::docs/v1/tech/tutorials/_integrate-install-fusionauth.adoc[]

== Create a User and an API Key

include::docs/v1/tech/tutorials/_integrate-add-user.adoc[]

== Configure FusionAuth

Next, you need to set up FusionAuth.
This can be done in different ways, but we’re going to use the {language} client library.
The below instructions use maven from the command line, but you can use the client library with an IDE of your preference as well.

First, make a directory:

[source,shell]
----
mkdir setup-fusionauth && cd setup-fusionauth
----

Now, copy and paste the following file into `requirements.txt`.

[source,text,title="Your FusionAuth configuration requirements file"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-client-libraries/main/python/requirements.txt[]
----

Then copy and paste the following code into the `setup.py` file.

[source,python]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-client-libraries/main/python/setup-django.py[]
----

Then, you can run the setup script.

++++
{% include _callout-note.liquid content="The setup script is designed to run on a newly installed FusionAuth instance with only one user and no tenants other than `Default`. To follow this guide on a FusionAuth instance that does not meet these criteria, you may need to modify the above script. <br><br> Refer to the [Python client library](/docs/v1/tech/client-libraries/python) documentation for more information." %}
++++

You'll use `venv` to keep your workspace clean. This will create FusionAuth
configuration for your {technology} application.

[source,shell]
----
python -m venv venv && \
source venv/bin/activate && \
pip install -r requirements.txt 
----

Now run the setup script:

[source,shell]
----
fusionauth_api_key=YOUR_API_KEY_FROM_ABOVE python setup.py
----

If you are using PowerShell, you will need to set the environment variable in a separate command before executing the script.

[source,shell]
----
$env:fusionauth_api_key='YOUR_API_KEY_FROM_ABOVE'
python setup.py
----

This configures FusionAuth for your {technology} application.

If you want, you can http://localhost:9011[login to your instance] and
examine the new application configuration the script created for you.

== Create Your {technology} Application

Now you are going to create a {technology} application. While this section builds a simple {technology} application, you can use the same configuration to integrate your complex {technology} application with FusionAuth.

First, make a directory:

[source,shell]
----
mkdir ../setup-django && cd ../setup-django
----

Now, create a new `requirements.txt` file to include {technology}.
Add the `Django` and `mozilla-django-oidc` plugins so that your requirements file looks like this:

[source,text,title="Your application requirements file"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-python-django-guide/main/requirements.txt[]
----

Then, re-run `pip install` to install these new packages

[source,shell]
----
pip install -r requirements.txt
----

Then, create your site:

[source,shell]
----
django-admin startproject mysite
----

=== Start Up The Server

Then, open a new terminal. You'll need to re-source your virtual environment settings:

[source,shell]
----
source venv/bin/activate
----

Then, start your server:

[source,shell]
----
python mysite/manage.py runserver
----

You can http://localhost:8000[visit it] to make sure it is running. If you need to stop it, hit `control-C` to do so. You can leave this running while you build out your application so that you can visit the app and see your progress.

=== Create a View

Switch back to your previous terminal window. It is going to be easier to run commands from within your `mysite` directory, so `cd` into it:

[source,shell]
----
cd mysite
----

Create an app within your `mysite` project:

[source,shell]
----
python manage.py startapp app
----

If you visit http://localhost:8000/app[http://localhost:8000/app] you'll see an error message because you need to create a view. Make a templates directory

[source,shell]
----
mkdir -p app/templates/app
----

And paste this HTML into the `app/templates/app/authentication.html` file:

[source,html]
----
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django OAuth App</title>
</head>
<body>
<div>
Hello!
</div>
</body>
</html>
----

Create a `urls.py` file for your application, at `app/urls.py`, and put the following text in it:


[source,python]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-python-django-guide/add-first-page/mysite/app/urls.py[]
----

Then you have to tie the view to the template you created above by modifying `app/views.py` to look like:

[source,python]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-python-django-guide/add-first-page/mysite/app/views.py[]
----

Then, modify `mysite/settings.py`. First, import the `os` module, changing the imports at the top of `mysite/settings.py` to look like:

[source,python]
----
import os
from pathlib import Path
----

Then, add `'app`' to your list of installed applications. Add it to the `INSTALLED_APPS` array.

[source,python]
----
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]
----

The last change with `mysite/settings.py` is to update the templates variable. Look for the `TEMPLATES` variable and replace the `DIRS` field with this:

[source,python]
----
'DIRS': (os.path.join(BASE_DIR, 'polls/templates'),),
----

Finally you have to edit the `mysite/urls.py` file: 

* Add `path('app/', include('app.urls')),` to the `urlpatterns` variable in that file.
* Change the import line: `from django.urls import path` to `from django.urls import include, path`.

Here's what `mysite/urls.py` should look like:

[source,python]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-python-django-guide/add-first-page/mysite/mysite/urls.py[]
----

At this point, you can visit http://localhost:8000/app[http://localhost:8000/app] and you should be greeted with the contents of the `authentication.html` file you created above.


=== Add Authentication

Now you are going to link up FusionAuth and add authentication to this project.

First, modify `mysite/settings.py` and add `mozilla_django_oidc` to the list of applications. You installed this app in your environment when you updated `requirements.txt`.

[source,python]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-python-django-guide/main/mysite/mysite/settings.py[tags=installedApps]
----

You need to add some additional configuration for this app. Just below the `INSTALLED_APPS` array, add this:

[source,python]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-python-django-guide/main/mysite/mysite/settings.py[tags=oidcConfig]
----

Save the `mysite/settings.py` file.

Next, update the paths to include those provided by the mozilla_django_oidc code. Here's what `mysite/urls.py` should look like:

[source,python]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-python-django-guide/main/mysite/mysite/urls.py[]
----

Then you want to update the `app/templates/app/authentication.html` file to have this content:

[source,html]
----
{% raw %}
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-python-django-guide/main/mysite/app/templates/app/authentication.html[]
{% endraw %}
----

Run all your migrations to make sure you have any needed database tables set up.

[source,shell]
----
python manage.py migrate
----

You can now open up an incognito window and visit http://localhost:8000/app[the {technology} app].
Log in using the user you added in FusionAuth, and you’ll see a welcoming message.

