---
layout: doc
title: Integrate Your Ruby on Rails Application With FusionAuth
description: Integrate your Ruby on Rails application with FusionAuth
navcategory: getting-started
---

:page-liquid:

// TBD how much these are useful
:prequisites: Ruby, bundler and Rails
:technology: Ruby on Rails
:language: Ruby

== Integrate Your {technology} Application With FusionAuth

In this article, you are going to learn how to integrate a {technology} application with FusionAuth.

Here's a typical application login flow before integrating FusionAuth into your {technology} application.

++++
{% plantuml source: _diagrams/docs/login-before.plantuml, alt: "Login before FusionAuth." %}
++++

And here's the same application login flow when FusionAuth is introduced.
++++
{% plantuml source: _diagrams/docs/login-after.plantuml, alt: "Login with FusionAuth." %}
++++


== Prerequisites

For this tutorial, you’ll need to have {prequisites} installed. You'll also need Docker, since that is how you’ll install FusionAuth.

== Download and Install FusionAuth

First, make a project directory:

[source,shell]
----
mkdir integrate-fusionauth && cd integrate-fusionauth
----

Then, install FusionAuth:

[source,bash]
----
curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml
https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.override.yml
curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env
docker-compose up -d
----

== Create a User and an API Key

Next, http://localhost:9011[log into your FusionAuth instance].
You’ll need to set up a user and a password, as well as accept the terms and conditions.

Then, you’re at the FusionAuth admin UI.
This lets you configure FusionAuth manually.
But for this tutorial, you're going to create an API key and then you’ll configure FusionAuth using our {language} client library.

Navigate to [breadcrumb]#Settings -> API Keys#. Click the [uielement]#+# button to add a new API Key.
Copy the value of the [field]#Key# field and then save the key.
It might be a value like `CY1EUq2oAQrCgE7azl3A2xwG-OEwGPqLryDRBCoz-13IqyFYMn1_Udjt`.

Doing so creates an API key that can be used for any FusionAuth API call.
Save that key value off as you’ll be using it later.

== Configure FusionAuth

Next, you need to set up FusionAuth.
This can be done in different ways, but we’re going to use the {language} client library.
The below instructions use maven from the command line, but you can use the client library with an IDE of your preference as well.

First, make a directory:

[source,shell]
----
mkdir setup-fusionauth && cd setup-fusionauth
----

If you want, you can http://localhost:9011[login to your instance] and
examine the new application configuration the script created for you.

Now, cut and paste the following file into `pom.xml`.

[source,ruby,title="Your FusionAuth Gemfile"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-client-libraries/main/ruby/Gemfile[]
----

Install the gems.

[source,shell]
----
bundle install
----

Then copy and paste the following code into the `setup.rb` file.

[source,ruby]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-client-libraries/main/ruby/setup.rb[]
----

Then, you can run the setup class. This will create FusionAuth
configuration for your :technology: application.

[source,shell]
----
ruby setup.rb
----

== Create Your :technology: Application

Now you are going to create a :technology: application. While this section uses a
simple :technology: application, you can use the same configuration to
integrate your :technology: application with FusionAuth.

First, make a directory:

[source,shell]
----
mkdir ../setup-ruby-on-rails && cd ../setup-ruby-on-rails
----

Then, set up a new rails app.

[source,shell]
----
rails new myapp && cd myapp
----

Install the omniauth gem and other supporting gems. Add the following to your Gemfile.

[source,ruby]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/Gemfile[tags=gemfile]
----

Then, install them.

[source,shell]
----
bundle install
----

Next, update your `config/environments/development.rb` file with FusionAuth OIDC configuration information. You'll have to add similar settings when deploying to prod or other environments.

[source,ruby]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/config/environments/development.rb[tags=oidcConfig]
----

Then, create a file called `omniauth.rb` in the `config/initializers` directory. Add this to the file.

[source,ruby,title="Your omniauth.rb initializer"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/config/initializers/omniauth.rb[]
----

This pulls from the environment file and configures omniauth to communicate with FusionAuth.

Next, you can create the following controllers and scaffolding.

[source,shell]
----
rails generate controller auth
rails generate controller home
rails generate scaffold todos
rails db:migrate
----

These controllers have the following purpose:

* `auth` will handle the integration with omniauth
* `home` will be an unprotected home page with a login button
* `todos` is a set of protected CRUD routes; in a real world application these would be built out further.

Let's update the `config/routes.rb` file. Here's what that should look like:

[source,ruby,title="Your routes"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/config/routes.rb[]
----

Nothing too special here:

* `todos` is the CRUD resource.
* `login` points you to the home page, which is available to unauthenticated users. This is also the default page.
* `logout` is tied to the auth controller's logout method.
* `auth/:provider/callback` is the omniauth callback method, which completes the OIDC flow.

Now, update the auth controller at `app/controllers/auth_controller.rb` to have this code, which fulfills some of the routes above. This lets us have a nice `logout` method and handle the callback from omniauth, setting a `session` attribute with user data.

[source,ruby,title="Your auth controller"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/app/controllers/auth_controller.rb[]
----


Now, update the application controller at `app/controllers/application_controller.rb` to have this code. Here you're enforcing authentication for all routes in your application by checking for the session attribute set by the auth controller.

[source,ruby,title="Your application controller"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/app/controllers/application_controller.rb[]
----

Next, update the home controller at `app/controllers/home_controller.rb` to have this code.

[source,ruby,title="Your homepage controller"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/app/controllers/home_controller.rb[]
----

Here, you're skipping authentication for this route so that the user has someplace to go if they are unauthenticated.

The view is also welcoming, but prompts them to login. Replace `app/views/home/index.html.erb` with this:

[source,ruby,title="Your homepage view"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/app/views/home/index.html.erb[]
----

Finally, update the layout so the user has login or logout buttons on every page. Add the below code just after the `<body>` tag.

[source,ruby,title="Your layout"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-ruby-rails-omniauth-guide/main/app/views/layouts/application.html.erb[tags=gemfile]
----


Once you’ve created this directory structure, you can start up the {technology} application using this command: 

[source,shell,title="Start the application"]
----
OP_SECRET_KEY=change-this-in-production-to-be-a-real-secret bundle exec rails s
----

`OP_SECRET_KEY` is the client secret, which was defined by the <<Configure FusionAuth>> step. You don't want to check that in, so you deliver it as an environment variable.

You can now open up an incognito window and visit http://localhost:3000[the {technology} app].
Log in using the user you added in FusionAuth, and you’ll see the email of the user next to a logout link.

