---
layout: doc
title: Integrate Your Python Django Application With FusionAuth
description: Integrate your Python Django application with FusionAuth
navcategory: getting-started
---

:page-liquid:

// TBD how much these are useful
:prequisites: python3 and pip3
:technology: Python Django
:language: python

== Integrate Your {technology} Application With FusionAuth

In this article, you are going to learn how to integrate a {technology} application with FusionAuth.

Here's a typical application login flow before integrating FusionAuth into your {technology} application..

++++
{% plantuml source: _diagrams/docs/login-before.plantuml, alt: "Login before FusionAuth." %}
++++

And here's the same application login flow when FusionAuth is introduced.
++++
{% plantuml source: _diagrams/docs/login-after.plantuml, alt: "Login with FusionAuth." %}
++++


== Prerequisites

For this tutorial, you’ll need to have {prequisites} installed. You'll also need Docker, since that is how you'll install FusionAuth.

The commands below are for macOS, but are limited to `mkdir` and `cd`.

== Download and Install FusionAuth

First, make a project directory:

[source,shell]
----
mkdir integrate-fusionauth && cd integrate-fusionauth
----

Then, install FusionAuth:

[source,bash]
----
curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml
https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.override.yml
curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env
docker-compose up -d
----

== Create a User and an API Key

Next, http://localhost:9011[log into your FusionAuth instance].
You’ll need to set up a user and a password, as well as accept the terms and conditions.

Then, you’re at the FusionAuth admin UI.
This lets you configure FusionAuth manually.
But for this tutorial, you're going to create an API key and then you’ll configure FusionAuth using our {language} client library.

Navigate to [breadcrumb]#Settings -> API Keys#. Click the [uielement]#+# button to add a new API Key.
Copy the value of the [field]#Key# field and then save the key.
It might be a value like `CY1EUq2oAQrCgE7azl3A2xwG-OEwGPqLryDRBCoz-13IqyFYMn1_Udjt`.

Doing so creates an API key that can be used for any FusionAuth API call.
Save that key value off as you’ll be using it later.

== Configure FusionAuth

Next, you need to set up FusionAuth.
This can be done in different ways, but we’re going to use the {language} client library.
The below instructions use maven from the command line, but you can use the client library with an IDE of your preference as well.

First, make a directory:

[source,shell]
----
mkdir setup-fusionauth && cd setup-fusionauth
----

If you want, you can http://localhost:9011[login to your instance] and
examine the new application configuration the script created for you after you are done.

Now, cut and paste the following file into `requirements.txt`.

[source,text,title="Your FusionAuth configuration requirements.txt"]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-client-libraries/main/python/requirements.txt[]
----

Then copy and paste the following code into the `setup.py` file.

[source,python]
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-client-libraries/main/python/setup.py[]
----

Then, you can run the setup script. You'll use `venv` to keep your workspace clean. This will create FusionAuth
configuration for your {technology} application.

[source,shell]
----
python -m venv venv && \
source venv/bin/activate && \
pip install -r requirements.txt 
----

Now run the setup script:

[source,shell]
----
fusionauth_api_key=<your API key> python setup.py
----

This configures FusionAuth for your {technology} application.

== Create Your {technology} Application

Now you are going to create a {technology} application. While this section builds a simple {technology} application, you can use the same configuration to integrate your complex {technology} application with FusionAuth.

First, make a directory:

[source,shell]
----
mkdir ../setup-django && cd ../setup-django
----

Now, update `requirements.txt` to include {technology}.
Add the `Django` and `mozilla-django-oidc` plugins so that your requirements file looks like this:

[source,text,title="Your requirements.txt file"]
----
fusionauth-client==1.42.0
Django==3.2.15
mozilla-django-oidc==2.0.0
----

Then, re-run `pip install`:

[source,shell]
----
pip install -r requirements.txt
----

Then, create your site:

[source,shell]
----
django-admin startproject mysite
----

=== Start Up The Server

Then, open a new terminal. You'll need to re-source your virtual environment settings:

[source,shell]
----
source venv/bin/activate
----

Then, start your server:

[source,shell]
----
python mysite/manage.py runserver
----

You can http://localhost:8000[visit it] to make sure it is running. If you need to stop it, hit `control-C` to do so. You can leave this running while you build out your application so that you can visit the app and see your progress.

=== Create a View

Switch back to your previous terminal window. It is going to be easier to run commands from within your `mysite` directory, so `cd` into it:

[source,shell]
----
cd mysite
----

Create an app within your `mysite` project:

[source,shell]
----
python manage.py startapp app
----

If you visit http://localhost:8000/app[http://localhost:8000/app] you'll see an error message because you need to create a view. Make a templates directory

[source,shell]
----
mkdir -p app/templates/app
----

And paste this HTML into the `app/templates/app/authentication.html` file:

[source,html]
----
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django OAuth App</title>
</head>
<body>
<div>
Hello!
</div>
</body>
</html>
----

Create a `urls.py` file for your application, at `app/urls.py`, and put the following text in it:


[source,python]
----
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]
----

Then you have to tie the view to the template you created above by modifying `app/views.py` to look like:

[source,python]
----
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def index(request):
    return render(request, template_name='app/authentication.html')
----

Then, modify `mysite/settings.py`. First, import the `os` module, changing the imports at the top of `mysite/settings.py` to look like:

[source,python]
----
import os
from pathlib import Path
----

Then, add `'app`' to your list of installed applications. Add it to the `INSTALLED_APPS` array.

[source,python]
----
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app', # this is what you are adding
]
----

Look for the `TEMPLATES` variable and replace the `DIRS` field with this:

[source,python]
----
'DIRS': (os.path.join(BASE_DIR, 'polls/templates'),),
----

Finally you have to edit the `mysite/urls.py` file: 

* Add `path('app/', include('app.urls')),` to the `urlpatterns` variable in that file.
* Change the import line: `from django.urls import path` to `from django.urls import include, path`.

Here's a partial view of what `mysite/urls.py` should look like:

[source,python]
----
# ...

from django.urls import include, path

# ...
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]
# ...
----

At this point, you can visit http://localhost:8000/app[http://localhost:8000/app] and you should be greeted with the contents of the `authentication.html` file you created above.

Now you are going to link up FusionAuth and add authentication to this project.

First, modify `mysite/settings.py` and add `mozilla_django_oidc` to the list of applications. You installed this app in your environment when you modified `requirements.txt`.

[source,python]
----
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'mozilla_django_oidc', # this is what you are adding
]
----

You need to add some additional configuration for this app. Just below the `INSTALLED_APPS` array, add this:

[source,python]
----

INSTALLED_APPS = [
# ...
]

AUTHENTICATION_BACKENDS = (
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
)

# The below config is taken from fusionauth admin UI when you set up the Django application in it
OIDC_RP_CLIENT_ID = 'e9fdb985-9173-4e01-9d73-ac2d60d1dc8e'
OIDC_RP_CLIENT_SECRET = 'change-this-in-production-to-be-a-real-secret'

OIDC_OP_AUTHORIZATION_ENDPOINT = "http://localhost:9011/oauth2/authorize"
OIDC_OP_TOKEN_ENDPOINT = "http://localhost:9011/oauth2/token"
OIDC_OP_USER_ENDPOINT = "http://localhost:9011/oauth2/userinfo"

OIDC_RP_SCOPES = "openid profile email"

OIDC_RP_SIGN_ALGO = "RS256"
OIDC_OP_JWKS_ENDPOINT = "http://localhost:9011/.well-known/jwks.json"

LOGIN_REDIRECT_URL = "http://localhost:8000/app/"
LOGOUT_REDIRECT_URL = "http://localhost:8000/app/"
----

Save the `mysite/settings.py` file.

Next, update the paths to include those provided by the mozilla_django_oidc code. Here's what the `urlpatterns` array of in `mysite/urls.py` should look like:

[source,python]
----
# ...
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('oidc/', include('mozilla_django_oidc.urls')),
]
# ...
----

Then you want to update the `app/templates/app/authentication.html` file to have this content:

[source,html]
----
{% raw %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django OAuth App</title>
</head>
<body>
<div>
    {% if user.is_authenticated %}
    <p>You are signed-in! Welcome {{user.email}}</p>
    <form action="{% url 'oidc_logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout">
    </form>
    {% else %}
    <a href="{% url 'oidc_authentication_init' %}">Login</a>
    {% endif %}
</div>
</body>
</html>{% endraw %}
----

You need to run some migrations to make sure you have all the database tables set up:

[source,shell]
----
python manage.py migrate
----

You can now open up an incognito window and visit http://localhost:8000/app[the {technology} app].
Log in using the user you added in FusionAuth, and you’ll see a welcoming message.

