---
layout: doc
title: Multi-node
description: How to run FusionAuth with multiple nodes
---

This tutorial shows you how to run FusionAuth with multiple nodes. 

FusionAuth is a stateless service, with all required state distributed to either the backend database (user passwords) or to clients (JWTs). This means it is horizontally scalable.

== Multi-node Architecture

== How to Add More Nodes

To add more nodes, you need to stand up new FusionAuth instances and have them connect to the same database.

Each node registers itself in the database and therefore they can all communicate if needed. 

The only reason a node needs to know about another node is for cache reloads and for log downloading. In the UI you can download logs using a button, and that will download logs from each node and put them into one zip file.


== Concerns

Make sure that all the link:/docs/v1/tech/reference/configuration/[configuration settings] are the same for each node. If they are not, behavior is nondeterministic.

