---
layout: doc
title: Set Up User Account Lockout
description: Learn how to set up account locking rules.
---

== Locking User Account Based on Behavior

If a user attempts to authenticate repeatedly and fails, you may want to prevent them after a certain number of attempts.

You can easily do this in FusionAuth.

=== The User Action

The first step is to create a user action, under [breadcrumb]#Settings -> User Actions#.

Give it a name of "Account Lock".

Check the "Time-based" and "Prevent login" checkboxes.

It should look something like this:

TBD picture

Save it.

=== The Tenant Configuration

Then, configure your tenant, under [breadcrumb]#Tenants -> Default#. Then navigate to the "Password" tab.

Under the "Failed authentication settings" tab, change the "User action" to the newly created user action, "Account Lock".

You can configure Failed attempts, Time period, Action duration, and Time unit

For example, the below settings will ....

PIC TBD

Note that since this is a temporary action, the user will still be unlocked on the edit user screen (see the green lock), but you can see the action under the user's "Current actions" tab.

Pic TBD


