---
layout: doc
title: Setting Up User Account Lockout
description: Learn how to set up account locking rules.
---

== Locking User Accounts Based on Failed Authentication Attempts

If a user attempts to authenticate repeatedly and fails, you may want to prevent them doing so after a certain number of attempts. This can help prevent brute force attacks against your users.

This account locking behavior is easily accomplished in FusionAuth. To do this, take two steps:

. Create a user action representing the account lock
. Configure your settings at the tenant level defining when to apply the lock

=== Creating the User Action

The first step is to create a user action, under [breadcrumb]#Settings -> User Actions#.

Give it a name of "Account Lock".

Check the "Time-based" and "Prevent login" checkboxes.

It should look something like this:

TBD picture

Save it.

There are other options available, including localization and auto emailing users; check out the link:../apis/user-actions[User Action APIs] for more information.

=== Tenant Configuration

Next, configure your tenant, under [breadcrumb]#Tenants -> Default#. Then navigate to the "Password" tab.

Under the "Failed authentication settings" tab, change the "User action" to the newly created user action, "Account Lock".

You can configure the number of failed attempts that will trigger this action, the time period during which all the attempts must take place, and the duration of the lockout.

For example, the below settings will allow five failed attempts in 60 seconds. Once the fifth attempt fails, the account will be locked for three minutes. However, each additional failed attempt will reset this three minute duration.

PIC TBD

=== What Happens When The Account is Locked

When a user account has been locked by this mechanism, they'll be able to sign back in after the specified action duration has elapsed since the last failed authentication attempt.

This user will not be able to login using the FusionAuth login pages, and any login API access will return a 4xx error, as specified in the link:../apis/login[API docs].

Note that since this is a temporary action, the user will still be unlocked on the edit user screen (see the green lock), but you can see the action under the user's "Current actions" tab.

Pic TBD

An administrator can manually remove or extend this lock from the administration UI. 

You can also modify an action which has been applied to a user by using the link:../apis/actioning-users[Actioning Users API].

