---
layout: doc
title: Start and Stop FusionAuth
description: Learn how to start and stop the FusionAuth services
navcategory: getting-started
---

== Start and Stop FusionAuth

If you are self-hosting FusionAuth, you may need to manually start or stop FusionAuth periodically. If you find yourself in this situation you'll be glad you know how.

Please note, unless you are self-hosting FusionAuth these instructions do not apply to you. FusionAuth manages and monitors instances hosted in our private
cloud and will restart FusionAuth if necessary.


It is recommended you start the FusionAuth Search service before starting the FusionAuth App service. You should also shutdown the Search Engine last. FusionAuth
utilizes the Search Engine and database for persisting and retrieving users.

The following examples will make the assumption that all of the services are running on the same server. Based upon how you have installed FusionAuth
you may or may not have all of the services running on the same server.

The macOS and Windows instructions assume an installation directory of `/usr/local/fusionauth` and `\fusionauth` respectively. Please adjust to your
specific installation directory. We'll refer to this directory as `FUSIONAUTH_HOME`.

=== Linux
When you install FusionAuth using our Debian or RPM packages a service is registered. It is recommended you utilize these services to start and stop
FusionAuth.

The service names are as follows:

* `fusionauth-search`
* `fusionauth-app`

[source,shell]
.Start FusionAuth
----
sudo systemctl start fusionauth-search
sudo systemctl start fusionauth-app
----

[source,shell]
.Stop FusionAuth
----
sudo systemctl stop fusionauth-app
sudo systemctl stop fusionauth-search
----

If you'd prefer to use the native Elastic and Tomcat scripts you may follow the macOS instructions, the same scripts may be executed on Linux.

=== macOS

*Start and Stop services using the native Elastic and FusionAuth scripts*

[source,shell]
.Start FusionAuth services
----
/usr/local/fusionauth/fusionauth-search/elasticsearch/bin/elasticsearch
/usr/local/fusionauth/fusionauth-app/bin/start.sh
----

[source,shell]
.Stop FusionAuth services
----
/usr/local/fusionauth/fusionauth-app/bin/stop.sh
----

Elasticsearch should be stopped last. If you started Elasticsearch using the `elasticsearch` script then you may simply kill the terminal where
the service is running to initiate shutdown.

[source,shell]
.Start FusionAuth services - Versions < 1.37.0
----
/usr/local/fusionauth/fusionauth-search/elasticsearch/bin/elasticsearch
/usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh start
----

[source,shell]
.Stop FusionAuth services - Versions < 1.37.0
----
/usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/catalina.sh stop
----

=== Windows

*Start and Stop services using the native PowerShell scripts*

[source]
.Start FusionAuth services using command line
----
\fusionauth\fusionauth-search\elasticsearch\bin\elasticsearch.bat
\fusionauth\fusionauth-app\bin\start.ps1
----

[source]
.Stop FusionAuth using command line
----
\fusionauth\fusionauth-app\bin\stop.ps1
----

Elasticsearch should be stopped last. If you started Elasticsearch using the `elasticsearch.bat` script then you may simply close the command
window where the service is running to initiate shutdown.

[source]
.Start FusionAuth services using command line - Versions < 1.37.0
----
\fusionauth\fusionauth-search\elasticsearch\bin\elasticsearch.bat
\fusionauth\fusionauth-app\apache-tomcat\bin\catalina.bat start
----


[source]
.Start FusionAuth services using command line - Versions < 1.37.0
----
\fusionauth\fusionauth-app\apache-tomcat\bin\catalina.bat stop
----

*Start and Stop services using Windows Services*

We also provide support for running FusionAuth as a Windows service.

[source]
.Start Services
----
net start FusionAuthSearch
net start FusionAuthApp
----

[source]
.Stop Services
----
net stop FusionAuthApp
net stop FusionAuthSearch
----

*Uninstall and reinstall Windows Services*

In most cases you will not need to re-install the services. If you want to remove the software from your system, the following commands will un-register the services.

[source]
.Unregister Windows Services
----
\fusionauth\fusionauth-app\bin\FusionAuthApp.exe /uninstall
\fusionauth\fusionauth-search\elasticsearch\bin\FusionAuthSearch.exe /uninstall
----

You may then optionally re-install the Windows services.


[source]
.Register Windows Services
----
\fusionauth\fusionauth-search\elasticsearch\bin\FusionAuthSearch.exe /install
\fusionauth\fusionauth-app\bin\FusionAuthApp.exe /install
----


[source]
.Unregister Windows Services - Versions < 1.37.0
----
\fusionauth\fusionauth-app\apache-tomcat\bin\FusionAuthApp.exe /uninstall
\fusionauth\fusionauth-search\elasticsearch\bin\FusionAuthSearch.exe /uninstall
----

You may then optionally re-install the Windows services.


[source]
.Register Windows Services - Versions < 1.37.0
----
\fusionauth\fusionauth-search\elasticsearch\bin\FusionAuthSearch.exe /install
\fusionauth\fusionauth-app\apache-tomcat\bin\FusionAuthApp.exe /install
----
