---
layout: doc
title: Switching search engines
description: How to switch back and forth between the provided search engines
---

You can switch between the search engines. As of version 1.16, FusionAuth supports two search engines:

* database
* elasticsearch

More details about each, including the strengths and limitations of each search engine type, link:/docs/v1/tech/core-concepts/users#user-search[are documented here].

This document will guide you through changing your search engine. You may do that because you're trying to simplify your deployment strategy and want to switch to the database search engine. Perhaps you need the advanced searching capabilities of Elasticsearch.


=== Prerequisites

This tutorial assumes you have both the application and the search services running on Linux. You also must be running at least version 1.16.0.

If you don't, head on over to the link:/docs/v1/tech/installation-guide/fusionauth-search[installation guide]. If you already have the application running, but need to install the search service, link:/docs/v1/tech/installation-guide/fusionauth-search[here are instructions].

If you are running FusionAuth via Docker, a Windows service, or some other mechanism, this guide will still be useful, but you'll have to stop and start the FusionAuth application in the manner appropriate to your installation.

=== From Elasticsearch to Database

Stop FusionAuth:

```
sudo service fusionauth-app stop
sudo service fusionauth-search stop
```

Locate your config file, it might be at a location similar to `/usr/local/fusionauth/config/fusionauth.properties`.


Comment out the `fusionauth-app.search-servers` value. 

```
#fusionauth-app.search-servers=http://localhost:9021
```

Add or update the `fusionauth-app.search-engine-type` key to have the value `database`.
```
fusionauth-app.search-engine-type=database
```

Restart the FusionAuth application:

```
sudo service fusionauth-app start
```

Navigate to [breadcrumb]#User# and search for a user by email address or first name to confirm that the search engine is working. 

tbdimg

=== From Database to Elasticsearch 


Stop FusionAuth:

```
sudo service fusionauth-app stop
```

Locate your config file, it might be at a location similar to `/usr/local/fusionauth/config/fusionauth.properties`.


Uncomment or add the `fusionauth-app.search-servers` value. This must point to your Elasticsearch server. 

```
fusionauth-app.search-servers=http://localhost:9021
```

Add or update the `fusionauth-app.search-engine-type` key to have the value `elasticsearch`.
```
fusionauth-app.search-engine-type=elasticsearch
```

Restart the FusionAuth application and Elasticsearch:

```
sudo service fusionauth-search start
sudo service fusionauth-app start
```

Login to FusionAuth. Reindex the search index by navigating to [breadcrumb]#System -> Reindex#. This ensures that Elasticsearch has the latest user data. This may take some time, depending on your data.

tbdimg

Navigate to [breadcrumb]#User# and search for a user by email address, first name or other attribute to confirm that the search engine is working. You'll also notice that the advanced search form elements are present.

tdbimg



