---
layout: doc
title: User Search
description: Learn how to search users
navcategory: admin
---

You can search users in FusionAuth to see how many there are, what they are doing, and more.

This tutorial will walk you through how to use FusionAuth's powerful search capabilities to analyze users stored there. Much of this will apply to searching link:/docs/v1/tech/core-concepts/entity-management[Entities], which use a similar approach.

Examples will be in curl, but you can also use any of the link:/docs/v1/tech/client-libraries/[supported client libraries] to build searches in your favorite development language.

== What Type of Engine

First, determine which search engine FusionAuth is using. It will either be the `database` search engine or the `elasticsearch` search engine.

In the administrative user interface, navigate to [breadcrumb]#System -> About# and scroll to the [breadcrumb]#System# section and you will see the type of search.

If you are using the database search engine, you'll want to link:/docs/v1/tech/core-concepts/users#database-search-engine[consult the database search engine documentation] for more information. The rest of this document focuses on the more powerful Elasticsearch search engine.

Learn more about link:/docs/v1/tech/core-concepts/search[each type of search engine]. Learn more about link:/docs/v1/tech/tutorials/switch-search-engines[switching search engines].

== Starting With Elasticsearch

First, you can use either a `POST` or a `GET` when calling this API. The functionality is exactly the same. A `POST` request can be longer. A `GET` request can be easily shared. This document will use `POST` requests.

Each of the methods that use Elasticsearch use the https://www.elastic.co/guide/en/elasticsearch/reference/7.12/analysis-standard-tokenizer.html[standard Elasticsearch tokenizer]. TODO is this true


=== Three Types of Searches

There are three main parameters you can use, and they are mutually exclusive.

First, `ids` searches. These are useful when you know exactly which users you want to retrieve. This can occur if you are storing user Ids outside of FusionAuth, in another datastore, and want to query user data within FusionAuth. This is the only search which is always guaranteed to only hit your database, never Elasticsearch.

Second, there is the `queryString` search. Here, the match is case-insensitive. Whitespace is allowed in the search, but must be URL escaped; for example, using %20 for a space character. Elasticsearch compatible regular expressions may be used, so you may search by prefix or suffix using the `*` wildcard. You may also search particular fields by prefixing the query with a field name: `email:`.

If the query string has a `:` it will be assumed that it is a valid Elasticsearch query and it will be passed as-is. Otherwise, if it has no spaces and has a `@` it will be assumed to be an email address and passed with a prefix: `email:`. Otherwise, if it has no spaces it will have the wildcard `*` prefixed and suffixed.

The last type of search uses the `query` parameter. In this case, you are providing an escaped JSON string which is passed to Elasticsearch. You have the full power of the Elasticsearch query language.

For both `queryString` and `query` searches, you may search against specific fields. The exact fields are not documented, but if you are self-hosted, you can find available search fields by https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-get-mapping.html[retrieving the Elasticsearch mapping]. If you are using FusionAuth Cloud, please https://account.fusionauth.io/account/support[open a support ticket] if you have a question about which fields are searchable.

== Examples

You can run all these examples locally by downloading https://github.com/fusionauth/fusionauth-example-user-search[this GitHub repository] and following the instructions.

These all use this example shell script to actually run the search.

[source,shell] 
.Example Shell Script For Searching
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-user-search/main/examples/search.sh[]
----

Only the value of the filename passed to the script changes.

=== Searching By User Ids

Here's an example of an `ids` query.

[source,json]
.Example Request JSON Searching By [field]#ids#
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-user-search/main/examples/ids/ids-request.json[]
----

This file is then passed is as the first argument for the shell script. Here's how you'd run it if the above JSON is in `ids-request.json`:

[source,shell] 
.Running The Example Shell Script
----
./search.sh ids-request.json
----

== Searching With `queryString`

Here are examples of `queryString` searches.

Below, you are searching for `dinesh`, across all the fields. This matches on the email address of the user.

[source,json]
.Example Request JSON For Searching Across All Indexed Fields With [field]#queryString# 
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-user-search/main/examples/queryString/all-fields-data-request.json[]
----

Here's how you'd run it if the above JSON is in `all-fields-data-request.json`:

[source,shell] 
.Running The Example Shell Script
----
./search.sh all-fields-data-request.json
----

Below, only the email field is searched for the string `dinesh`.

[source,json]
.Example Request JSON For Searching By Emails With [field]#queryString# 
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-user-search/main/examples/queryString/email-data-request.json[]
----

If you change the value from `email:dinesh*` to `email:dinesh` this query will return 0 results, because there is no one with that email and no wildcarding is done. If, instead, you change the value from `email:dinesh*` to `email:dinesh@fusionauth.io` this query will return Dinesh.

== Searching With `query`

The `query` parameter is the most powerful way to search for users, because you have the full power of Elasticsearch. The `query` parameter is a full escaped Elasticsearch query.

=== Searching On One Field

The first thing you need to do is build the Elasticsearch query. Below is a usery to match all users with a `user.data.Company` attribute of `PiedPiper`. 

[NOTE.note]
====
The `user.data` field can hold arbitrary JSON and is useful if your users have customer data fields.

There is a similar `.data` field on many FusionAuth objects, though only `user.data` and `entity.data` fields are currently indexed and searchable.
====

The key is case sensitive. Searching on `user.data.company` will return zero results.

However, the value is case insensitive. Searching for values of `PiedPiper`, `piedpiper` and `PIEDPIPER` will return the same number of results.

[source,json]
.Example Elasticsearch Query JSON For Searching the Company User Attribute
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-user-search/main/examples/query/user-data-simple.json[]
----

Then, you need to escape any JSON characters in the string. This is the main difference between the `query` method and the `queryString` method. Because you can use the full Elasticsearch query language with the `query` method, but FusoinAuth's APIs expect JSON, you must escape the Elasticsearch JSON.

You can use `jq`. If the Elasticsearch query above is in `queryfile`, you can escape it using this command.

[source,shell]
.Escaping Elasticsearch Query String using jq
----
cat queryfile | jq -R -s '.' 
----

That will display this escaped string:

[source,json]
.Example Escaped Elasticsearch Query JSON For Searching the Company User Attribute
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-user-search/main/examples/query/user-data-simple-escaped.json[]
----

The next step is to add that string as the `query` parameter to a request.

[source,json]
.Example Request JSON For Searching By the Company User Attribute Emails With [field]#queryString# 
----
include::https://raw.githubusercontent.com/FusionAuth/fusionauth-example-user-search/main/examples/query/user-data-simple-request.json[]
----

Finally, you can run the query in the same way you do the others, using the `search.sh` script. Here's how you'd run it if the above JSON is in `user-data-simple-request.json`:

[source,shell] 
.Running The Example Shell Script
----
./search.sh user-data-simple-request.json
----

=== Searching On Multiple Fields

You can also do more advanced searches, including multiple clauses and numeric ranges. Let's take a look at a more complex query.



You can push


You can 

can we do filters?I know we can do ranges

total


TODO show example response, you get back full user object

== Troubleshooting Elasticsearch Queries

Build the Elasticsearch queries directly against Elasticsearch
If you are using Docker, expose the port.

+    ports:
+      - 9200:9200

```
{
  "took" : 6,
  "timed_out" : false,
  "_shards" : {
    "total" : 10,
    "successful" : 10,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 2.0,
    "hits" : [
      {
        "_index" : "fusionauth_user",
        "_type" : "_doc",
        "_id" : "00000000-0000-0000-0000-000000000003",
        "_score" : 2.0
      },
      {
        "_index" : "fusionauth_user",
        "_type" : "_doc",
        "_id" : "00000000-0000-0000-0000-000000000006",
        "_score" : 2.0
      },
      {
        "_index" : "fusionauth_user",
        "_type" : "_doc",
        "_id" : "00000000-0000-0000-0000-000000000005",
        "_score" : 2.0
      }
    ]
  }
}

```


== Additional Resources

The link:/docs/v1/tech/apis/users#elasticsearch-search-engine[FusionAuth Elasticsearch API documentation] has examples of JSON for various queries, as well as additional supported parameters.


