---
layout: doc
title: Troubleshooting
description: Troubleshoot any issues that might arise while install or running FusionAuth.
---

== Overview

If any problems arise or if you are unable to access FusionAuth, consult the FusionAuth log files. In most cases API errors will be written out to the fusionauth-app.log file.

Please email support@fusionauth.io if you need assistance. If possible, when contacting FusionAuth support, zip the contents of the logs directory and attach it to the email.

=== Logs

The following are the default locations for each of the FusionAuth log files. You may or may not have all of the FusionAuth services installed on the same system so you may not have all of the following logs on your server.

[source,shell]
.Linux and macOS
----
/usr/local/fusionauth/logs/fusionauth-app.log
/usr/local/fusionauth/logs/fusionauth-search.log
----

These paths assume the suggested product location of `\fusionauth`. This path may be different on your system depending on where you unpacked the zip files.

[source]
.Windows
----
\fusionauth\logs\fusionauth-app.log
\fusionauth\logs\fusionauth-search.log
----
