---
layout: doc
title: Client Libraries Overview
description: An overview of the FusionAuth Client Libraries
---

:sectnumlevels: 0

== Overview

Client libraries will help you quickly integrate your application with FusionAuth. All of our client libraries are open source and hosted on our https://github.com/FusionAuth[GitHub] account. You can fork and tweak them as well as look over the code to learn how the client libraries work.

If we are missing a language, open a https://github.com/FusionAuth/fusionauth-issues/issues[GitHub Issue] as a Feature Request if you don't see it already listed as an open feature.

* link:/docs/v1/tech/client-libraries/go/[Go]
* link:/docs/v1/tech/client-libraries/java/[Java]
* link:/docs/v1/tech/client-libraries/javascript/[JavaScript]
* link:/docs/v1/tech/client-libraries/netcore/[.NET Core]
* link:/docs/v1/tech/client-libraries/node/[Node]
* link:/docs/v1/tech/client-libraries/php/[PHP]
* link:/docs/v1/tech/client-libraries/python/[Python]
* link:/docs/v1/tech/client-libraries/ruby/[Ruby]
* link:/docs/v1/tech/client-libraries/typescript/[Typescript]

=== Request and response objects

All the client libraries use the link:/docs/v1/tech/apis/[REST API]. 

In general, the request object will either be string parameters or a complex object depending on the type of API call being made. Any request object will be mapped by the SDK to a JSON object required by the corresponding API method. Examining the API documents for the operations you're trying to call will therefore be useful, especially if you are using language without static typing.

The response object will typically contain:

* a status corresponding to the HTTP status code returned by the API. It may also be -1 if no HTTP request was successfully made
* a JSON success object if the call succeeded.
* a JSON error object with an intelligible message if the status code is `4xx` or `5xx`.
* an exception object if there was no HTTP request sent or there was no reasonable response from the server.
