---
layout: doc
title: Client Libraries Overview
description: An overview of the FusionAuth Client Libraries
navcategory: developer
---

:sectnumlevels: 0

== Overview

Client libraries will help you quickly integrate your application with FusionAuth. All of our client libraries are open source and hosted on our https://github.com/FusionAuth[GitHub] account. You can fork and tweak them as well as look over the code to learn how the client libraries work.

If we are missing a language, open a https://github.com/FusionAuth/fusionauth-issues/issues[GitHub Issue] as a Feature Request if you don't see it already listed as an open feature.

* link:/docs/v1/tech/client-libraries/dart[Dart]
* link:/docs/v1/tech/client-libraries/go[Go]
* link:/docs/v1/tech/client-libraries/java[Java]
* link:/docs/v1/tech/client-libraries/javascript[JavaScript] (deprecated, prefer link:/docs/v1/tech/client-libraries/typescript[Typescript])
* link:/docs/v1/tech/client-libraries/netcore[.NET Core]
* link:/docs/v1/tech/client-libraries/node[Node] (deprecated, prefer link:/docs/v1/tech/client-libraries/typescript[Typescript])
* link:/docs/v1/tech/client-libraries/openapi[OpenAPI] (**experimental**, please give us feedback)
* link:/docs/v1/tech/client-libraries/php[PHP]
* link:/docs/v1/tech/client-libraries/python[Python]
* link:/docs/v1/tech/client-libraries/ruby[Ruby]
* link:/docs/v1/tech/client-libraries/typescript[Typescript]

There are also https://github.com/FusionAuth/fusionauth-contrib/blob/master/client-libraries.md[community contributed client libraries for other languages].

=== Usage Suggestions

include::docs/v1/tech/client-libraries/_how-to-use-client-libraries.adoc[]

