---
layout: doc
title: Client Libraries and SDKs Overview
description: An overview of the FusionAuth Client Libraries and SDKs
navcategory: developer
---

:sectnumlevels: 0

== Overview

Client libraries and SDks will help you quickly integrate your application with FusionAuth. All of our client libraries are open source and hosted on our https://github.com/FusionAuth[GitHub account]. You can fork and tweak them as well as look over the code to learn how the client libraries work.

* <<Languages>>
* <<Usage Suggestions>>
* <<Versioning>>

== Languages

If we are missing a language, open a https://github.com/FusionAuth/fusionauth-issues/issues[GitHub Issue] as a Feature Request if you don't see it already listed as an open feature.

* link:/docs/v1/tech/client-libraries/dart[Dart]
* link:/docs/v1/tech/client-libraries/go[Go]
* link:/docs/v1/tech/client-libraries/java[Java]
* link:/docs/v1/tech/client-libraries/netcore[.NET Core]
* link:/docs/v1/tech/client-libraries/openapi[OpenAPI]
* link:/docs/v1/tech/client-libraries/php[PHP]
* link:/docs/v1/tech/client-libraries/python[Python]
* link:/docs/v1/tech/client-libraries/react-sdk[React SDK]
* link:/docs/v1/tech/client-libraries/ruby[Ruby]
* link:/docs/v1/tech/client-libraries/typescript[Typescript]

There are also https://github.com/FusionAuth/fusionauth-contrib/blob/master/client-libraries.md[community contributed client libraries for other languages].

=== Deprecated Client Libraries

These client libraries still work and are built for every release, but are deprecated. For new projects, prefer the alternative.

* link:/docs/v1/tech/client-libraries/javascript[JavaScript] (deprecated, prefer link:/docs/v1/tech/client-libraries/typescript[Typescript])
* link:/docs/v1/tech/client-libraries/node[Node] (deprecated, prefer link:/docs/v1/tech/client-libraries/typescript[Typescript])

== Usage Suggestions

include::docs/v1/tech/client-libraries/_how-to-use-client-libraries.adoc[]

== Versioning

Client library versions track the API. The API will only change with a major or minor version release, not with a patch release.

You should use the version of a client library that corresponds to your version of FusionAuth. If that is not available, use the latest release of the client library for the minor version. 

.Examples of Client Library Versions To Use
[cols="1,1,3"]
|===
| FusionAuth Version | Client Library Version | Notes

| `1.41.0`
| `1.41.0`
| Same version

| `1.41.1`
| `1.41.0`
| Same minor version

| `1.29.4`
| `1.29.1`
| Latest release in the minor version 

| `1.29.1`
| `1.29.1`
| Same version

| `1.29.0`
| `1.29.0`
| Same version

|===

