---
layout: doc
title: Client Libraries and SDKs Overview
description: An overview of the FusionAuth Client Libraries and SDKs
navcategory: developer
---

:sectnumlevels: 0

== Overview

Client libraries and SDks will help you quickly integrate your application with FusionAuth. All of our client libraries are open source and hosted on our https://github.com/FusionAuth[GitHub account]. You can fork and tweak them as well as look over the code to learn how the client libraries work.

* <<SDKs vs Client Libraries>>
* <<Languages>>
* <<Usage Suggestions>>
* <<Versioning>>

== SDKs vs Client Libraries

At FusionAuthk, a **client library** is a thin wrapper over our FusionAuth APIs, and it provides complete coverage over all public FusionAuth API endpoints. A client library is like a set of legos, to be put together by a developer who wants to extend or manipulate FusionAuth to meet their needs.

You can use a client library to manage FusionAuth. For instance, if you wanted to rotate client secrets regularly, you could use a client library to do so.

It can also be used to integrate with a custom application to offer login experiences that are different from those that are offered out of the box. If, in your app, you wanted to prompt someone for a username first, then do a lookup, then offer them a custom password field, then prompt them to enter their favorite color, use a client library to perform these complicated, custom operations.

At FusionAuth, an **SDK** is an opinionated set of higher level constructs. These focus on a subset of functionality. These are like an assembled lego set.

These let you quickly accomplish the common tasks and are often targeted at developers working on the front end: mobile/React/Vue/Angular/JavaScript developers. 

FusionAuth SDKs have:

* A button/function for logging in
* A button/function for logging out
* A button/function to register the user
* A filter/some way to examine roles and limit information displayed to a given role or set of roles
* A way to refresh a token without asking the user to reauthenticate.
* Secure access and refresh token storage

SDKs should require minimal customization to use.

You can pair an SDK with a client library.

== Languages

If we are missing a language, open a https://github.com/FusionAuth/fusionauth-issues/issues[GitHub Issue] as a Feature Request if you don't see it already listed as an open feature.

* link:/docs/v1/tech/client-libraries/dart[Dart Client Library]
* link:/docs/v1/tech/client-libraries/go[Go Client Library]
* link:/docs/v1/tech/client-libraries/java[Java Client Library]
* link:/docs/v1/tech/client-libraries/netcore[.NET Core Client Library]
* link:/docs/v1/tech/client-libraries/openapi[OpenAPI Client Library]
* link:/docs/v1/tech/client-libraries/php[PHP Client Library]
* link:/docs/v1/tech/client-libraries/python[Python Client Library]
* link:/docs/v1/tech/client-libraries/react-sdk[React SDK]
* link:/docs/v1/tech/client-libraries/ruby[Ruby Client Library]
* link:/docs/v1/tech/client-libraries/typescript[Typescript Client Library]

There are also https://github.com/FusionAuth/fusionauth-contrib/blob/master/client-libraries.md[community contributed client libraries for other languages].

=== Deprecated Client Libraries

These client libraries still work and are built for every release, but are deprecated. For new projects, prefer the alternative.

* link:/docs/v1/tech/client-libraries/javascript[JavaScript Client Library] (deprecated, prefer link:/docs/v1/tech/client-libraries/typescript[Typescript Client Library])
* link:/docs/v1/tech/client-libraries/node[Node Client Library] (deprecated, prefer link:/docs/v1/tech/client-libraries/typescript[Typescript Client Library])

== Usage Suggestions

include::docs/v1/tech/client-libraries/_how-to-use-client-libraries.adoc[]

== Versioning

Client library versions track the API. The API will only change with a major or minor version release, not with a patch release.

You should use the version of a client library that corresponds to your version of FusionAuth. If that is not available, use the latest release of the client library for the minor version. 

.Examples of Client Library Versions To Use
[cols="1,1,3"]
|===
| FusionAuth Version | Client Library Version | Notes

| `1.41.0`
| `1.41.0`
| Same version

| `1.41.1`
| `1.41.0`
| Same minor version

| `1.29.4`
| `1.29.1`
| Latest release in the minor version 

| `1.29.1`
| `1.29.1`
| Same version

| `1.29.0`
| `1.29.0`
| Same version

|===

