---
layout: doc
title: FusionAuth .NET Core Client Library
description: The FusionAuth .NET Core Client library allows you to call FusionAuth from a .NET Core application
navcategory: developer
---
:page-liquid:

:sectnumlevels: 0

== .NET Core Client Library

The .NET Core client library allows you to integrate FusionAuth with your .NET Core application.

Source Code:

* https://github.com/FusionAuth/fusionauth-netcore-client

NuGet Package:

* https://www.nuget.org/packages/FusionAuth.Client/

To install the FusionAuth Client from NuGet run the following command.

```bash
PM> Install-Package FusionAuth.Client
```
=== Usage Suggestions

include::docs/v1/tech/client-libraries/_how-to-use-client-libraries.adoc[]


== PATCH requests

:client_library_language: .NET Core
include::docs/v1/tech/client-libraries/_static-patch-note.adoc[]
:client_library_language!:


== FusionAuth Templates for .NET

FusionAuth has a collection of .NET templates available as a NuGet package. Quickly create new secured .NET applications with FusionAuth templates using the .NET CLI or Visual Studio. The new applications are pre-configured to use FusionAuth for authentication and authorization. Only standard .NET security libraries are used in the templates.

Currently, the following .NET templates are implemented:

* FusionAuth Blazor Server Application.
* FusionAuth MVC Application.
* FusionAuth Web API Application.


=== Requirements

* A FusionAuth installation. You can link:/docs/v1/tech/installation-guide/[install FusionAuth locally, or sign up for a hosted account].
* .NET Core 7.0 SDK or higher.
* Visual Studio 2022 for Mac, version 17.6 and above (optional).
* Visual Studio 2022 for Windows, version 17.6 and above (optional).


=== Installing the Templates

FusionAuth .NET templates are available on https://www.nuget.org/packages/FusionAuth.Templates/[NuGet]. You can install them by running the following command in your terminal.

```bash
dotnet new install FusionAuth.Templates::1.0.0
```

When installed successfully, the templates will be available in the .NET CLI and Visual Studio. The installation is the same for both Windows and macOS.

=== Using the Templates

To help you set up a valid application in FusionAuth, we have created a FusionAuth link:/docs/v1/tech/installation-guide/kickstart[Kickstart], available on https://github.com/FusionAuth/fusionauth-example-client-libraries/tree/main/kickstart/kickstart.json[GitHub]. Follow the instructions in the https://github.com/FusionAuth/fusionauth-example-client-libraries/tree/main/dotnet/templates/README.md[README.md] file to set up FusionAuth for your project. If you don't want to use the Kickstart file, you can set up your application manually in FusionAuth, using the values referenced in the https://github.com/FusionAuth/fusionauth-example-client-libraries/tree/main/kickstart/kickstart.json[kickstart.json] file.

Note that the Kickstart is designed to be used when starting up FusionAuth for the first time using `docker compose up`.

The FusionAuth instance created by the Kickstart assumes that your .NET project will be running on `HTTPS` on port `5001`. Your project might not run on the same port, as Visual Studio will randomly choose a port if the chosen one is already in use by another project. It may also be a different port if you run the project through IIS or another web server. In this case, update the `authorizedRedirectURL` and `logoutURL` variables in the https://github.com/FusionAuth/fusionauth-example-client-libraries/tree/main/kickstart/kickstart.json[kickstart.json] file to that of your project. You can also update the URLs on the Application settings page in the FusionAuth admin UI on link:/docs/v1/tech/core-concepts/applications#oauth[the OAuth tab] at any time after the Kickstart has run.

Some templates will ask for a FusionAuth Client Secret when initializing a new project. Use a non-sensitive secret from a local FusionAuth installation. If you use the Kickstart to set up your FusionAuth instance, the Client Secret will be `change-this-in-production-to-be-a-real-secret`.

Do not use a production or sensitive Client Secret in the template prompts, as it is stored in the `appsettings.Development.json` file, and will be available in plain text and committed to your repo. To provide the Client Secret to your application in production, you should use one of the secure methods https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-7.0&tabs=windows[recommended by Microsoft]. The platform-independent key for the Client Secret setting is `FusionAuth__ClientSecret` if you want to provide the Client Secret via an https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-7.0&tabs=windows#environment-variables[environment variable].

==== .NET CLI

To create a new project from a template, navigate to your new project directory and run the following command.

```bash
dotnet new [template-name] [options]
```

Where `[template-name]` is the name of the template you want to use from one of the following:

- `fusionauthblazorserver` creates a new Blazor Server application with FusionAuth authentication and authorization.
- `fusionauthmvcwebapp` creates a new MVC application with FusionAuth authentication and authorization.
- `fusionauthwebapi` creates a new Web API application with FusionAuth authentication and authorization.

Use `[options]` to provide your FusionAuth URL and FusionAuth Application Client Id. The following options are available:

- `--issuer` is the fully qualified URL to your FusionAuth server. The default value is `\http://localhost:9011`.
- `--client-id` is the link:/docs/v1/tech/core-concepts/applications[Client Id] associated with your application. The default value is `3c219e58-ed0e-4b18-ad48-f4f92793ae32`.
- `--port` is the port to run on under https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-7.0[Kestrel], using HTTPS. The default value is `5001`. This can be changed after installation in the `appsettings.Development.json` file in the root directory of the project and `launchSettings.json` in the `Properties` directory of the project.

==== Visual Studio for macOS

FusionAuth .NET templates require Visual Studio for macOS version 17.6 or higher. 

To create a new project from a template, first create or open a Solution. Then select [breadcrumb]#File -> New Project#. In the "New Project" dialog, select [breadcrumb]#Custom# from the left-hand menu. Select the FusionAuth template you want to use and click [uielement]#Continue#. Fill in the required information, including the fully qualified URL to your FusionAuth server and your FusionAuth Application Client Id. Click [uielement]#Continue#.

Set the project name and click [uielement]#Create#.

==== Visual Studio for Windows

FusionAuth .NET templates require Visual Studio for Windows version 17.6 or higher. 

To create a new project from a template, first create or open a Solution. Then select [breadcrumb]#File -> New Project#. In the "New Project" dialog, select "FusionAuth" from the "All project types" dropdown. Select the FusionAuth template you want to use. Set the project name and click [uielement]#Next#. Fill in the required information, including the fully qualified URL to your FusionAuth server and your FusionAuth Application Client Id.

Click [uielement]#Create#.

=== Testing

To test projects created using the .NET templates, refer to the testing section in the https://github.com/FusionAuth/fusionauth-example-client-libraries/tree/main/dotnet/templates/README.md[README.md] file.

=== Uninstalling the Templates

You can uninstall the templates using the following command.

```bash
dotnet new uninstall FusionAuth.Templates
```

You will need to restart Visual Studio for the changes to take effect.


++++
{% capture relatedTag %}client-netcore{% endcapture %}
{% include _doc-related-posts.liquid %}
++++


=== Example apps
++++
{%capture language %}netcore{% endcapture %}
{% include _example-apps-one-section.liquid %}
++++
