---
layout: doc
title: FusionAuth .NET Core Client Library
description: The FusionAuth .NET Core Client library allows you to call FusionAuth from a .NET Core application
navcategory: developer
---
:page-liquid:

:sectnumlevels: 0

== .NET Core Client Library

The .NET Core client library allows you to integrate FusionAuth with your .NET Core application.

Source Code:

* https://github.com/FusionAuth/fusionauth-netcore-client

NuGet Package:

* https://www.nuget.org/packages/FusionAuth.Client/

To install the FusionAuth Client from NuGet run the following command.

```bash
PM> Install-Package FusionAuth.Client
```
=== Usage Suggestions

include::docs/v1/tech/client-libraries/_how-to-use-client-libraries.adoc[]


== PATCH requests

:client_library_language: .NET Core
include::docs/v1/tech/client-libraries/_static-patch-note.adoc[]
:client_library_language!:


== FusionAuth Templates for .NET

FusionAuth has a collection of .NET templates available as a NuGet package. Quickly create new secured .NET applications with FusionAuth templates using the .NET CLI or Visual Studio. The new applications are pre-configured to use FusionAuth for authentication and authorization. Only standard .NET security libraries are used in the templates.

Currently, the following .NET templates are implemented:

* FusionAuth Blazor Server Application.
* FusionAuth MVC Application.
* FusionAuth Web API Application.


=== Requirements

* A FusionAuth installation. You can link:/docs/v1/tech/installation-guide/[install FusionAuth locally, or sign up for a hosted account].
* .NET Core 7.0 SDK or higher.
* Visual Studio 2022 for Mac, version 17.6 and above (optional).
* Visual Studio 2022 for Windows, version 17.6 and above (optional).


=== Installing the Templates

FusionAuth .NET templates are available on link:https://www.nuget.org/packages/FusionAuth.Templates/[NuGet]. You can install them by running the following command in your terminal.

```bash
dotnet new install FusionAuth.Templates::1.0.0
```

When installed successfully, the templates will be available in the .NET CLI and Visual Studio. The installation is the same for both Windows and macOS.

=== Using the Templates

Each template also comes with a script to quickly setup FusionAuth with the correct settings and parameters. This script can be found in the `FusionAuth-Setup` directory of a project created from the templates. After creating a new project, view the `README.md` file in the root of the new project for more information on running the setup script for that template type. Note that the setup scripts are designed to run on a newly installed FusionAuth instance with only one user and no tenants other than `Default`. To use the setup scripts on a FusionAuth instance that does not meet these criteria, you may need to modify the scripts.


Note that some templates will ask for a FusionAuth Client Secret when initializing a new project. This should only be filled in with a non-sensitive secret from a local FusionAuth installation. If you've used the setup scripts to set up your FusionAuth instance, the Client Secret will be `change-this-in-production-to-be-a-real-secret`.

Do not use a production or sensitive Client Secret in the template prompts, as it will be stored in the `Appsettings.json.development` file, and therefore be available in plain text and committed to your repo. To provide the Client Secret to your application in production, you should use one of the secure methods https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-7.0&tabs=windows[recommended here by Microsoft]. The platform indepedent hierarchical path for the Client Secret setting is `FusionAuth__ClientSecret`.

==== .NET CLI

To create a new project from a template, run the following command.

```bash
dotnet new [template-name] [options]
```

Where `[template-name]` is the name of the template you want to use from one of the following:

- `fusionauthblazorserver` creates a new Blazor Server application with FusionAuth authentication and authorization.
- `fusionauthmvcwebapp` creates a new MVC application with FusionAuth authentication and authorization.
- `fusionauthwebapi` creates a new Web API application with FusionAuth authentication and authorization.

Use `[options]` to provide your FusionAuth URL and FusionAuth Application Client Id. The following options are available:

- `--issuer` is the fully qualified URL to your FusionAuth server. The default value is `\http://localhost:9011`.
- `--client-id` is the link:/docs/v1/tech/core-concepts/applications[Client Id] associated with your application. The default value is `3c219e58-ed0e-4b18-ad48-f4f92793ae32`.

==== Visual Studio for macOS

FusionAuth .NET templates require Visual Studio for macOS version 17.6 or higher. 

To create a new project from a template, first create or open a Solution. Then select [breadcrumb]#File > New Project#. In the "New Project" dialog, select [breadcrumb]#Custom# from the left-hand menu. Select the FusionAuth template you want to use and click [uielement]#Continue#. Fill in the required information, including the fully qualified URL to your FusionAuth server and your FusionAuth Application Client Id. Click [uielement]#Continue#.

Set the project name and click [uielement]#Create#.

==== Visual Studio for Windows

FusionAuth .NET templates require Visual Studio for Windows version 17.6 or higher. 

To create a new project from a template, first create or open a Solution. Then select [breadcrumb]#File > New Project#. In the "New Project" dialog, select "FusionAuth" from the project types dropdown. Select the FusionAuth template you want to use. Fill in the required information, including the fully qualified URL to your FusionAuth server and your FusionAuth Application Client Id. 

Click [uielement]#Continue#.

Set the project name and click [uielement]#Create#.

=== Uninstalling the Templates

You can uninstall the templates using the following command.

```bash
dotnet new uninstall FusionAuth.Templates
```

You will need to restart Visual Studio for the changes to take effect.


++++
{% capture relatedTag %}client-netcore{% endcapture %}
{% include _doc-related-posts.liquid %}
++++


=== Example apps
++++
{%capture language %}netcore{% endcapture %}
{% include _example-apps-one-section.liquid %}
++++
