---
layout: doc
title: FusionAuth PHP Client
description: The FusionAuth PHP Client library allows you to call FusionAuth from PHP using a simple PHP class
---
:page-liquid:

:sectnumlevels: 0

== PHP Client Library

The PHP client library allows you to integrate FusionAuth with your PHP application. 

Source code:

* https://github.com/FusionAuth/fusionauth-php-client

=== Install the library

To use the client library on your project simply copy the PHP source files from the `src` directory to your project or the following
 Composer package.

Packagist

* https://packagist.org/packages/fusionauth/fusionauth-client

```bash
composer require fusionauth/fusionauth-client
```

Include composer autoloader

```PHP
require __DIR__ . '/vendor/autoload.php';
```

=== Create the Client

The following code assumes FusionAuth is running on `\http://localhost:9011` and uses an API key `5a826da2-1e3a-49df-85ba-cd88575e4e9d`, you will need to supply your own API key, and if you are not running FusionAuth locally, your host parameter may be different.

```PHP
$apiKey = "5a826da2-1e3a-49df-85ba-cd88575e4e9d";
$client = new FusionAuth\FusionAuthClient($apiKey, "http://localhost:9011");
```

=== Login a user

```PHP
$applicationId = "68364852-7a38-4e15-8c48-394eceafa601";

$request = array();
$request["applicationId"] = $applicationId;
$request["loginId"] = "joe@fusionauth.io";
$request["password"] = "abc123";
$result = $client->login($request);
if (!$result->wasSuccessful()) {
 // Error
}

// Hooray! Success
```

++++
{% capture relatedTag %}client-php{% endcapture %}
{% include _doc_related_posts.liquid %}
++++

=== Example apps
++++
{%capture language %}php{% endcapture %}
{% include _example_apps_one_section.liquid %}
++++
