==== Response Body

[.api]
[field]#apiKey.metaData.attributes.description# [type]#[String]#::
Description of the key.

[field]#apiKey.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the API key was added to the FusionAuth database.

[field]#apiKey.key# [type]#[String]#::
The API key value, this is the string value you will use in the Authorization header to link:/docs/v1/tech/apis/authentication/[authenticate API] requests.

[field]#apiKey.keyManager# [type]#[Boolean]#::
This the keymanager is set to false, this API key can be used to call the API key API. Otherwise, this API key will always return a 401 when you try to use this API.

[field]#apiKey.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the API key was last updated in the FusionAuth database.

[field]#apiKey.metaData.attributes.description# [type]#[String]#::
Description of the key.

[field]#apiKey.permissions.endpoints# [type]#[Object]#::
Endpoint permissions for this key. This value is read only once the key is created.

[field]#apiKey.tenantId# [type]#[String]#::
The unique Id of the Tenant. This value is read-only once the key is created.

[source,json]
.Example API Key Response JSON
----
include::../../../src/json/api-keys/apikey-update-response-body.json[]
----