==== Response Body

[.api]
ifdef::apikey_create_resonse[]
[field]#apiKey.id# [type]#[String]#::
The UUID of the API key.
endif::[]

ifdef::apikey_update_response[]
[field]#apiKey.id# [type]#[String]#::
The UUID of the API key.
endif::[]

[field]#apiKey.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the API key was added to the FusionAuth database.

[field]#apiKey.key# [type]#[String]#::
The API key value, this is the string value you will use in the Authorization header to link:/docs/v1/tech/apis/authentication/[authenticate API] requests.

[field]#apiKey.keyManager# [type]#[Boolean]#::
Indicates whether this key is a key manager. Setting this flag to true allows this key to be used to call these APIs. An attempt to call these APIs with a non-manager key (`keyManager` set to `false`) will always return a HTTP response status code 401.

[field]#apiKey.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the API key was last updated in the FusionAuth database.

[field]#apiKey.metaData.attributes.description# [type]#[String]#::
Description of the key.

[field]#apiKey.permissions.endpoints# [type]#[Object]#::
Endpoint permissions for this key. Each key of the object is an endpoint, with the value being an array of the HTTP methods which can be used against the endpoint. An empty permissions object mean that this is a super key that authorizes this key for all the endpoints.

[field]#apiKey.tenantId# [type]#[String]#::
The unique Id of the Tenant. This value is read-only once the key is created.

[source,json]
.Example API Key Response JSON

ifdef::apikey_create_response[]
----
include::../../../src/json/api-keys/apikey-create-response-body.json[]
----
endif::[]

ifdef::apikey_update_response[]
----
include::../../../src/json/api-keys/apikey-update-response-body.json[]
----
endif::[]
