==== Request Body

[.api]
[field]#apiKey.key# [type]#[String]# [optional]#Optional#::
API key string. When you create an API key the key is defaulted to a secure random value but the API key is simply a string, so you may call it `super-secret-key` if you'd like. However a long and random value makes a good API key in that it is unique and difficult to guess.

[field]#apiKey.metaData.attributes.description# [type]#[String]# [optional]#Optional#::
Description of the key.

[field]#apiKey.permissions.endpoints# [type]#[Object]# [optional]#Optional#::
Endpoint permissions for this key. Each key of the object is an endpoint, with the value being an array of the HTTP methods which can be used against the endpoint. Empty permissions object mean that this is a super key that authorizes this key to all the endpoints.

[field]#apiKey.tenantId# [type]#[String]# [optional]#Optional#::
The unique Id of the Tenant. This value is required if the key is meant to be tenant scoped. Tenant scoped keys can only be used to access users and other tenant scoped objects for the specified tenant. This value is read-only once the key is created.

[source,json]
.Example API Key request JSON
----
include::../../../src/json/api-keys/apikey-create-request-body.json[]
----