
==== Request Body

[.api]
[field]#application.authenticationTokenConfiguration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`#::
Determines if Users can have Authentication Tokens associated with this Application. This feature may not be enabled for the FusionAuth application.

[field]#application.cleanSpeakConfiguration.applicationIds# [type]#[Array<UUID>]# [optional]#Optional#::
An array of UUIDs that map to the CleanSpeak applications for this Application. It is possible that a single Application in FusionAuth might have multiple Applications in CleanSpeak. For example, a FusionAuth Application for a game might have one CleanSpeak Application for usernames and another Application for chat.
+
This property is used when CleanSpeak sends user action notifications to FusionAuth (when users are disciplined for example). FusionAuth will translate the CleanSpeak ids to FusionAuth ids and then apply the user action.

[field]#application.cleanSpeakConfiguration.usernameModeration.applicationId# [type]#[UUID]# [optional]#Optional#::
The Id of the CleanSpeak application that usernames are sent to for moderation.

[field]#application.cleanSpeakConfiguration.usernameModeration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`#::
True if CleanSpeak username moderation is enabled.

[field]#application.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Application that should be persisted.

[field]#application.formConfiguration.adminRegistrationFormId# [type]#[UUID]# [optional]#Optional# [default]#Defaults to **[see description]**# [since]#Available since 1.20.0#::
The unique Id of the form to use for the Add and Edit User Registration form when used in the FusionAuth admin UI. 
+
When this parameter is not provided, it will default to the form Id currently assigned to the FusionAuth application.
+
A paid edition of FusionAuth is required to utilize custom forms.

[field]#application.jwtConfiguration.accessTokenKeyId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.6.0#::
The Id of the signing key used to sign the access token.

[field]#application.jwtConfiguration.algorithm# [type]#[String]# [optional]#Optional# [deprecated]#Deprecated#::
include::_jwt_algorithm.adoc[]
+
Required when `enabled` is set to `true`.
+
When an HMAC algorithm is used such as `HS256`, `HS384` or `HS512`, the OAuth `client_secret` will be used as the signing secret.
+
&nbsp;
+
[deprecated]#Removed in version 1.6.0# In version 1.6.0 and beyond, JWT configuration can be managed in the `link:/docs/v1/tech/apis/keys/[Keys API]` and Keymaster.

[field]#application.jwtConfiguration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`#::
Indicates if this application is using the JWT configuration defined here or the global JWT configuration defined by the Tenant. If this is `false` the signing algorithm configured in the Tenant will be used. If `true` the signing algorithm defined in this application will be used.

[field]#application.jwtConfiguration.idTokenKeyId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.6.0#::
The Id of the signing key used to sign the Id token.

[field]#application.jwtConfiguration.privateKey# [type]#[String]# [optional]#Optional# [deprecated]#Deprecated#::
The private key used when an `RSA` or `ECDSA` based signing algorithm has been selected. The private key will be used to sign the JWT. This key is expected to be presented in a PEM encoded format.
+
Required when `enabled` is set to `true` and `algorithm` is set to an `RSA` or `ECDSA` based value.
+
&nbsp;
+
[deprecated]#Removed in version 1.6.0# In version 1.6.0 and beyond, JWT configuration can be managed in the `link:/docs/v1/tech/apis/keys/[Keys API]` and Keymaster.

[field]#application.jwtConfiguration.publicKey# [type]#[String]# [optional]#Optional# [deprecated]#Deprecated#::
The public key used when an `RSA` or `ECDSA` signing algorithms has been selected. The public key will be used to verify JWTs signed with the private key. This key is expected to be presented in a PEM encoded format.
+
Required when `enabled` is set to `true` and `algorithm` is set to an `RSA` or `ECDSA` based value.
+
&nbsp;
+
[deprecated]#Removed in version 1.6.0# In version 1.6.0 and beyond, JWT configuration can be managed in the `link:/docs/v1/tech/apis/keys/[Keys API]` and Keymaster.

[field]#application.jwtConfiguration.refreshTokenTimeToLiveInMinutes# [type]#[Integer]# [optional]#Optional# [since]#Available since 1.2.0#::
The length of time in minutes the JWT refresh token will live before it is expired and is not able to be exchanged for a JWT.
+
Required when `enabled` is set to `true`.

[field]#application.jwtConfiguration.secret# [type]#[String]# [optional]#Optional# [deprecated]#Deprecated#::
The secret used when an `HMAC` based signing algorithm has been selected. This secret is used to sign and verify JWTs.
+
Required when `enabled` is set to `true` and `algorithm` is set to an `HMAC` based value.
+
&nbsp;
+
[deprecated]#Removed in version 1.5.0# In version 1.5.0 and beyond, when selecting an `HMAC` algorithm, the `client_secret` from the OAuth configuration will be used to sign and verify the JWTs.

[field]#application.jwtConfiguration.timeToLiveInSeconds# [type]#[Integer]# [optional]#Optional#::
The length of time in seconds the JWT will live before it is expired and no longer valid.
+
Required when `enabled` is set to `true`.

[field]#application.lambdaConfiguration.accessTokenPopulateId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.6.0#::
The Id of the Lambda that will be invoked when an access token is generated for this application. This will be utilized during OAuth2 and OpenID Connect authentication requests as well as when an access token is generated for the Login API.

[field]#application.lambdaConfiguration.idTokenPopulateId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.6.0#::
The Id of the Lambda that will be invoked when an Id token is generated for this application during an OpenID Connect authentication request.

[field]#application.lambdaConfiguration.samlv2PopulateId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.6.0#::
The Id of the Lambda that will be invoked when a a SAML response is generated during a SAML authentication request.

[field]#application.loginConfiguration.allowTokenRefresh# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.5.0#::
Indicates if a JWT may be refreshed using a Refresh Token for this application. This configuration is separate from issuing new Refresh Tokens which is controlled by the `generateRefreshTokens` parameter. This configuration indicates specifically if an existing Refresh Token may be used to request a new JWT using the link:/docs/v1/tech/apis/jwt#refresh-a-jwt[Refresh API].
+
If you do not intend to use the Login API, and instead will only be using the OAuth endpoints, you may leave this set to `false` to ensure Refresh Tokens cannot be used outside of the Refresh Token Grant.

[field]#application.loginConfiguration.generateRefreshTokens# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.5.0#::
Indicates if a Refresh Token should be issued from the Login API.
+
If you do not intend to use the Login API, and instead will only be using the OAuth endpoints, you may leave this set to `false` to ensure Refresh Tokens will not be issued outside of the OAuth grants.

[field]#application.loginConfiguration.requireAuthentication# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `true`# [since]#Available since 1.5.0#::
Indicates if the Login API should require an API key. If you set this value to `false` and your FusionAuth API is on a public network, anyone may attempt to use the Login API.
+
If you do not intend to use the Login API, or will only be calling this API from a secure backend server, setting this value to `true` in order to require an API key is preferred.

[field]#application.name# [type]#[String]# [required]#Required#::
The name of the Application.

[field]#application.oauthConfiguration.authorizedOriginURLs# [type]#[Array<String>]# [optional]#Optional#::
An array of URLs that are the authorized origins for FusionAuth OAuth.
+
For improved security, all FusionAuth hosted login pages add an HTTP response header of `X-Frame-Options: DENY`. This response header disallows loading the FusionAuth pages from an iframe. To utilize an iframe and load one or more of the FusionAuth hosted login pages, add the iframe page URLs to this property. For that host, FusionAuth will remove the `X-Frame-Options` header allowing the page to load in the iframe.

[field]#application.oauthConfiguration.authorizedRedirectURLs# [type]#[Array<String>]# [optional]#Optional#::
An array of URLs that are the authorized redirect URLs for FusionAuth OAuth.
+
Examples of valid redirect URIs:
+
* \https://example.com/redirect
* com.myApp://redirect
* com.myApp:/redirect
+
[since]#Available since 1.7.0#
+
You may now use URLs that do not begin with `http` to support native application redirect. Prior to this version the value will be validated to begin with `http`.
+
[since]#Available since 1.12.0#
+
You may now use URLs for application redirects that use a single slash to denote there is no naming authority for the scheme. Prior to this version a URL such as `com.myApp:/redirect` would fail validation as in invalid URL.

[field]#application.oauthConfiguration.clientSecret# [type]#[String]# [optional]#Optional#::
The OAuth 2.0 client secret. If you leave this blank during a POST, a secure secret will be generated for you. If you leave this blank during PUT, the previous value will be maintained. For both POST and PUT you can provide a value and it will be stored.

[field]#application.oauthConfiguration.debug# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.25.0#::
Whether or not FusionAuth will log a debug Event Log. This is particular useful for debugging the authorization code exchange with the Token endpoint during an Authorization Code grant.

[field]#application.oauthConfiguration.deviceVerificationURL# [type]#[String]# [optional]#Optional# [since]#Available since 1.11.0#::
The device verification URL to be used with the Device Code grant type, this field is required when `device_code` is enabled.

[field]#application.oauthConfiguration.enabledGrants# [type]#[Array<String>]# [optional]#Optional# [since]#Available since 1.5.0#::
The enabled grants for this application. In order to utilize a particular grant with the OAuth 2.0 endpoints you must have enabled the grant.
+
Supported values include:
+
* `authorization_code`
* `implicit`
* `password`
* `refresh_token`
* `device_code` &nbsp; [since]#Available since 1.11.0#

[field]#application.oauthConfiguration.generateRefreshTokens# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `true`# [since]#Available since 1.3.0#::
Determines if the OAuth 2.0 Token endpoint will generate a refresh token when the `offline_access` scope is requested.

[field]#application.oauthConfiguration.logoutBehavior# [type]#[String]# [optional]#Optional# [default]#Defaults to `AllApplications`# [since]#Available since 1.11.0#::
Behavior when `/oauth2/logout` is called.
+
Valid values:
+
* `RedirectOnly`
** End the SSO session and redirect to the configured Logout URL or the passed in [field]#post_logout_redirect_uri# value.
* `AllApplications`
** End the SSO session and make a `GET` request to all configured Logout URLs for every application in the tenant.

[field]#application.oauthConfiguration.logoutURL# [type]#[String]# [optional]#Optional#::
The logout URL for the Application. FusionAuth will redirect to this URL after the user logs out of OAuth.

[field]#application.oauthConfiguration.requireClientAuthentication# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `true`# [since]#Available since 1.3.0#::
Determines if the OAuth 2.0 Token endpoint requires client authentication. If this is enabled, the client must provide client credentials when using the Token endpoint. The `client_id` and `client_secret` may be provided using a Basic Authorization HTTP header, or by sending these parameters in the request body using POST data.

[field]#application.passwordlessConfiguration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.5.0#::
Determines if passwordless login is enabled for this application.

[field]#application.registrationConfiguration.birthDate.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `birthDate` field will be included on the registration form.

[field]#application.registrationConfiguration.birthDate.required# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `birthDate` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.confirmPassword# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the password should be confirmed during self service registration, this means that the user will be required to type the password twice.

[field]#application.registrationConfiguration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if self service registration is enabled for this application. When this value is false, you may still use the Registration API, this only affects if the self service option is available during the OAuth 2.0 login.
+
Self service registration cannot be enabled on the FusionAuth application.

[field]#application.registrationConfiguration.firstName.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `firstName` field will be included on the registration form.

[field]#application.registrationConfiguration.firstName.required# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `firstName` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.formId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.18.0#::
The Id of an associated link:/docs/v1/tech/apis/forms/[Form] when using `advanced` registration configuration type.
This field is required when [field]#application.registrationConfiguration.type# is set to `advanced`.

[field]#application.registrationConfiguration.fullName.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `fullName` field will be included on the registration form.

[field]#application.registrationConfiguration.fullName.required# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `fullName` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.lastName.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `lastName` field will be included on the registration form.

[field]#application.registrationConfiguration.lastName.required# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `lastName` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.loginIdType# [type]#[String]# [optional]#Optional# [default]#Defaults to `email`# [since]#Available since 1.4.0#::
The unique login Id that will be collected during registration, this value can be `email` or `username`. Leaving the default value of `email` is preferred because an email address is globally unique.
+
- `email`
- `username`

[field]#application.registrationConfiguration.middleName.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `middleName` field will be included on the registration form.

[field]#application.registrationConfiguration.middleName.required# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `middleName` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.mobilePhone.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `mobilePhone` field will be included on the registration form.

[field]#application.registrationConfiguration.mobilePhone.required# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.4.0#::
Determines if the `mobilePhone` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.type# [type]#[String]# [optional]#Optional# [default]#Defaults to `basic`# [since]#Available since 1.18.0#::
The type of registration flow.
+
Supported values include:
+
* `basic` - the basic self registration options available prior to version 1.18.0.
* `advanced` - advanced usage of custom forms, requires a paid edition of FusionAuth.

[field]#application.registrationDeletePolicy.unverified.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.13.0#::
Indicates that users without a verified registration for this application will have their registration permanently deleted after [field]#application.registrationDeletePolicy.unverified.numberOfDaysToRetain# days.

[field]#application.registrationDeletePolicy.unverified.numberOfDaysToRetain# [type]#[Integer]# [optional]#Optional# [since]#Available since 1.13.0#::
The number of days from registration a user's registration will be retained before being deleted for not completing registration verification. This field is required when [field]#application.registrationDeletePolicy.enabled# is set to `true`.  Value must be greater than 0.

ifdef::includeRoles[]
[field]#application.roles# [type]#[Array]# [optional]#Optional#::
An array of Role objects.

[field]#application.roles``[x]``.description# [type]#[String]# [optional]#Optional#::
A description for the role.

[field]#application.roles``[x]``.id# [type]#[UUID]# [optional]#Optional# [default]#generated if null#::
The Id of the Role.

[field]#application.roles``[x]``.name# [type]#[String]# [required]#Required#::
The name of the Role.

[field]#application.roles``[x]``.isDefault# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`#::
Whether or not the Role is a default role. A default role is automatically assigned to a user during registration if no roles are provided.

[field]#application.roles``[x]``.isSuperRole# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`#::
Whether or not the Role is a considered to be a super user role. This is a marker to indicate that it supersedes all other roles. FusionAuth will attempt to enforce this contract when using the web UI, it is not enforced programmatically when using the API.
endif::includeRoles[]

[field]#application.samlv2Configuration.audience# [type]#[String]# [optional]#Optional# [default]#Defaults to `issuer`# [since]#Available since 1.6.0#::
The audience for the SAML response sent to back to the service provider from FusionAuth. Some service providers require different audience values than the `issuer` and this configuration option lets you change the `audience` in the response.

[field]#application.samlv2Configuration.authorizedRedirectURLs# [type]#[Array<String>]# [required]#Required# [since]#Available since 1.20.0#::
One or more authorized URLS that may be specified by the SAML v2 Service Provider in the Authentication request `<AssertionConsumerServiceURL>` element. If a requested URL is not in this list the request will be rejected by FusionAuth.
+
This is the URL that FusionAuth will send the SAML response during a SAML login request, this URL is also referred to as the Assertion Consumer Service or ACS). If the the Authentication request does not contain the `<AssertionConsumerServiceURL>` element, the first URL found in this list will be used to send the SAML response back to the Service Provider.

[field]#application.samlv2Configuration.callbackURL# [type]#[String]# [optional]#Optional# [since]#Available since 1.6.0# [deprecated]#Deprecated#::
The URL of the callback (sometimes called the Assertion Consumer Service or ACS). This is where FusionAuth sends the browser after the user logs in via SAML.
+
[deprecated]#Deprecated in version 1.20.0# 
In version 1.20.0 and beyond, Callback URLs can be managed via [field]#application.samlv2Configuration.authorizedRedirectURLs#.

[field]#application.samlv2Configuration.debug# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.6.0#::
Whether or not FusionAuth will log SAML debug messages to the event log. This is useful for debugging purposes.

[field]#application.samlv2Configuration.defaultVerificationKeyId# [type]#[UUID]# [optional]#Optional#  [since]#Available since 1.20.0#::
The verification key used to verify a signature when the SAML v2 Service Provider is using HTTP Redirect Bindings. 
+ 
When HTTP POST Bindings are used, this is the default verification key used if a `<KeyInfo>` element is not found in the SAML AuthNRequest. If a `<KeyInfo>` element is found, Key Master will be used to resolve the key and this configuration will not be used to verify the request signature. 
+
This parameter is required when [field]#application.samlv2Configuration.requireSignedRequests# is set to `true`. 

[field]#application.samlv2Configuration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.6.0#::
Whether or not the SAML IdP for this Application is enabled.

[field]#application.samlv2Configuration.issuer# [type]#[String]# [required]#Required# [since]#Available since 1.6.0#::
An `issuer` identifies the service provider and allows FusionAuth to load the correct Application and SAML configuration. If you don't know the `issuer`, you can put anything in this field and FusionAuth will display an error message with the `issuer` from the service provider when you test the SAML login.

[field]#application.samlv2Configuration.keyId# [type]#[UUID]# [optional]#Optional# [default]#Defaults to a new key# [since]#Available since 1.6.0#::
The unique Id of the Key used to sign the SAML response. If you do not specify this property, FusionAuth will create a new key and associate it with this Application.

[field]#application.samlv2Configuration.logout.behavior# [type]#[String]# [optional]#Optional# [default]#Defaults to `AllParticipants`# [since]#Available since 1.25.0#::
The possible values are:
+
 * `AllParticipants` - each session participant that has enabled single logout will be sent a Logout Request
 * `OnlyOriginator` - no other session participants will be notified when a logout request is sent for this application
+
This configuration is functionally equivalent to the Logout Behavior found in the OAuth2 configuration.

[field]#application.samlv2Configuration.logout.defaultVerificationKeyId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.25.0#::
The unique Id of the Key used to verify the signature if the public key cannot be determined by the `KeyInfo` element when using POST bindings, or the key used to verify the signature when using HTTP Redirect bindings.
+
This parameter is required when [field]#application.samlv2Configuration.logout.requireSignedRequests# is set to `true`. 

[field]#application.samlv2Configuration.logout.keyId# [type]#[UUID]# [optional]#Optional# [default]#Defaults to **[see description]**# [since]#Available since 1.25.0#::
The unique Id of the Key used to sign the SAML Logout response. 
+
When this parameter is omitted, the key defined by `application.samlv2Configuration.keyId` will be used.

[field]#application.samlv2Configuration.logout.requireSignedRequests# [type]#[boolean]# [required]#Required# [default]#Defaults to `false`# [since]#Available since 1.25.0#::
Set this parameter equal to `true` to require the SAML v2 Service Provider to sign the Logout request. When this value is `true` all Logout requests missing a signature will be rejected.
+
When set to `true`, the parameter [field]#application.samlv2Configuration.logout.defaultVerificationKeyId# is required.

[field]#application.samlv2Configuration.logout.singleLogout.enabled# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.25.0#::
Whether or not SAML Single Logout for this SAML IdP is enabled.

[field]#application.samlv2Configuration.logout.singleLogout.keyId# [type]#[UUID]# [optional]#Optional# [default]#Defaults to **[see description]**# [since]#Available since 1.25.0#::
The unique Id of the Key used to sign the SAML Single Logout response. 
+
When this parameter is omitted, the key defined by `application.samlv2Configuration.keyId` will be used.

[field]#application.samlv2Configuration.logout.singleLogout.url# [type]#[String]# [optional]#Optional# [since]#Available since 1.25.0#::
The URL at which you want to receive the `LogoutRequest` from FusionAuth.
+
Required if [field]#application.samlv2Configuration.logout.singleLogout.enabled# is `true`.

[field]#application.samlv2Configuration.logout.singleLogout.xmlSignatureC14nMethod# [type]#[String]# [optional]#Optional# [default]#Defaults to `exclusive_with_comments`# [since]#Available since 1.25.0#::
+
:signed_entity: SAML Single Logout response
+
include::_xmlSignatureC14nMethod-description.adoc[]
+
include::../shared/_xmlSignatureC14nMethod-values.adoc[]
+
:signed_entity!:

[field]#application.samlv2Configuration.logout.xmlSignatureC14nMethod# [type]#[String]# [optional]#Optional# [default]#Defaults to `exclusive_with_comments`# [since]#Available since 1.25.0#::
+
:signed_entity: SAML Logout response
+
include::_xmlSignatureC14nMethod-description.adoc[]
+
include::../shared/_xmlSignatureC14nMethod-values.adoc[]
+
:signed_entity!:

[field]#application.samlv2Configuration.logoutURL# [type]#[String]# [optional]#Optional# [default]#Defaults to the system logout URL or `/`# [since]#Available since 1.6.0#::
The URL that the browser is taken to after the user logs out of the SAML service provider. Often service providers need this URL in order to correctly hook up single-logout.
+
This is also the URL that will be sent the SAML v2 LogoutResponse using the same bindings that were used to initiate the logout request with the IdP. For example, if POST bindings were used to initiate the logout request, POST bindings will be used for this LogoutResponse request.

[field]#application.samlv2Configuration.requireSignedRequests# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`# [since]#Available since 1.20.0#::
Set this parameter equal to `true` to require the SAML v2 Service Provider to sign the request. When this value is `true` all requests missing a signature will be rejected.
+
When set to `true`, the parameter [field]#application.samlv2Configuration.defaultVerificationKeyId# is required.

[field]#application.samlv2Configuration.xmlSignatureC14nMethod# [type]#[String]# [optional]#Optional# [default]#Defaults to `exclusive_with_comments`# [since]#Available since 1.6.0#::
+
:signed_entity: SAML response
+
include::_xmlSignatureC14nMethod-description.adoc[]
+
include::../shared/_xmlSignatureC14nMethod-values.adoc[]
+
:signed_entity!:

[field]#application.samlv2Configuration.xmlSignatureLocation# [type]#[String]#  [default]#Defaults to `Assertion`# [since]#Available since 1.21.0#::
The location to place the XML signature when signing a successful SAML response.
+
The possible values are:
+
 * `Assertion` - The XML signature will be added as a child element of the Assertion.
 * `Response` - The XML signature will be added as a child element of the Response.
+
In most cases the default configuration will be adequate. If you encounter a SAML v2 Service Provider that requires the signature to be a child of the Response, use this configuration to change the signature location. Prior to version `1.21.0`, the XML signature was always located as a child element of the Assertion when the response was successful.

[field]#application.verificationEmailTemplateId# [type]#[UUID]# [optional]#Optional#::
The Id of the Email Template that is used to send the Registration Verification emails to users. If the `verifyRegistration` field is `true` this field is required.

[field]#application.verifyRegistration# [type]#[Boolean]# [optional]#Optional# [default]#Defaults to `false`#::
Whether or not registrations to this Application may be verified. When this is set to `true` the `verificationEmailTemplateId` parameter is also required.

[field]#webhookIds# [type]#[Array<UUID>]# [optional]#Optional#::
An array of Webhook Ids. For Webhooks that are not already configured for All Applications, specifying an Id on this request will indicate the associated Webhook should handle events for this application.

ifdef::includeRoles[]
[source,json]
.Example Request JSON
----
include::../../../src/json/applications/post-request.json[]
----
endif::includeRoles[]
ifndef::includeRoles[]
[source,json]
.Example Request JSON
----
include::../../../src/json/applications/put-request.json[]
----
endif::includeRoles[]

