==== Response Body

[.api]
[field]#httpSessionMaxInactiveInterval# [type]#[Integer]#::
The time in seconds until an inactive session will be invalidated, from the application's tenant. Used when creating a new session in the FusionAuth Front End.

[field]#logoutURL# [type]#[String]#::
The logout redirect URL when sending the user's browser to the `/oauth2/logout` URI of the FusionAuth Front End. From the application's tenant.

[field]#oauthConfiguration.authorizedRedirectURLs# [type]#[Array<String>]#::
An array of URLs that are the authorized redirect URLs for FusionAuth OAuth.

[field]#oauthConfiguration.clientId# [type]#[String]#::
The OAuth client Id of the Application.

[field]#application.oauthConfiguration.clientSecret# [type]#[String]#::
The OAuth client secret.
This field will only be provided when the request was authenticated using an API key.

[field]#application.oauthConfiguration.enabledGrants# [type]#[Array<String>]# [optional]#Optional# [since]#Available Since 1.5.0#::
The enabled grants for this application. In order to utilize a particular grant with the OAuth 2.0 endpoints you must have enabled the grant.
+
Supported values include:
+
* `authorization_code`
* `implicit`
* `password`
* `refresh_token`

[field]#application.oauthConfiguration.generateRefreshTokens# [type]#[Boolean]# [since]#Available Since 1.3.0#::
Determines if the OAuth 2.0 Token endpoint will generate a refresh token when the `offline_access` scope is requested.

[field]#application.oauthConfiguration.logoutBehavior# [type]#[String]# [since]#Available Since 1.11.0#::
Behavior when `/oauth2/logout` is called.
+
Valid values:
+
* `RedirectOnly`
** End the SSO session and redirect to the configured Logout URL or the passed in [field]#post_logout_redirect_uri# value.
* `AllApplications`
** End the SSO session and make a `GET` request to all configured Logout URLs for every application in the tenant.

[field]#oauthConfiguration.logoutURL# [type]#[String]#::
The logout URL for the Application. FusionAuth will redirect to this URL after the user logs out of OAuth.

[field]#application.oauthConfiguration.requireClientAuthentication# [type]#[Boolean]# [since]#Available Since 1.3.0#::
Determines if the OAuth 2.0 Token endpoint requires client authentication. If this is enabled, the client must provide client credentials when using the Token endpoint. The `client_id` and `client_secret` may be provided using a Basic Authorization HTTP header, or by sending these parameters in the request body using POST data.

[source,json]
.Example Response JSON
----
include::../../../src/json/applications/oauth-configuration/response.json[]
----