==== Response Body

[.api]
[field]#httpSessionMaxInactiveInterval# [type]#[Integer]#::
The time in seconds until an inactive session will be invalidated, from the application's tenant. Used when creating a new session in the FusionAuth Front End.

[field]#logoutURL# [type]#[String]#::
The logout redirect URL when sending the user's browser to the `/oauth2/logout` URI of the FusionAuth Front End. From the application's tenant.

[field]#oauthConfiguration.authorizedOriginURLs# [type]#[Array<String>]#::
An array of URLs that are the authorized origins for FusionAuth OAuth.
+
When this configuration is omitted, all HTTP origins are allowed to use the browser based grants and the HTTP response header of `X-Frame-Options: DENY` will be added to each response to disallow iframe loading.

[field]#oauthConfiguration.authorizedRedirectURLs# [type]#[Array<String>]#::
An array of URLs that are the authorized redirect URLs for FusionAuth OAuth.

[field]#oauthConfiguration.authorizedURLValidationPolicy# [type]#String# [since]#Available since 1.43.0#::
Controls the validation policy for [field]#oauthConfiguration.authorizedOriginURLs# and [field]#oauthConfiguration.authorizedRedirectURLs#.
+
The possible values are:
+
* `ExactMatch` - The configured values cannot include wildcards. Values during OAuth 2.0 workflows must match a configured value exactly.
* `AllowWildcards` - The configured values may contain wildcards. Values during OAuth 2.0 workflows can be matched against wildcard patterns or exactly match a configured value.

[field]#oauthConfiguration.clientAuthenticationPolicy# [type]#[String]# [since]#Available since 1.28.0#::
Determines the client authentication requirements for the OAuth 2.0 Token endpoint.
+
The possible values are:
+
include::_application-oauthConfiguration-clientAuthenticationPolicy.adoc[]

[field]#oauthConfiguration.clientId# [type]#[String]#::
The OAuth client Id of the Application.

[field]#oauthConfiguration.clientSecret# [type]#[String]#::
The OAuth client secret.
This field will only be provided when the request was authenticated using an API key.

[field]#oauthConfiguration.deviceVerificationURL# [type]#[String]# [since]#Available since 1.11.0#::
The device verification URL to be used with the Device Code grant type.

[field]#oauthConfiguration.enabledGrants# [type]#[Array<String>]# [since]#Available since 1.5.0#::
The enabled grants for this application. In order to utilize a particular grant with the OAuth 2.0 endpoints you must have enabled the grant.
+
Supported values include:
+
* `authorization_code`
* `implicit`
* `password`
* `refresh_token`
* `urn:ietf:params:oauth:grant-type:device_code` &nbsp; [since]#Available since 1.11.0#

[field]#oauthConfiguration.generateRefreshTokens# [type]#[Boolean]# [since]#Available since 1.3.0#::
Determines if the OAuth 2.0 Token endpoint will generate a refresh token when the `offline_access` scope is requested.

[field]#oauthConfiguration.logoutBehavior# [type]#[String]# [since]#Available since 1.11.0#::
Behavior when `/oauth2/logout` is called.
+
Valid values:
+
* `RedirectOnly`
** End the SSO session and redirect to the configured Logout URL or the passed in [field]#post_logout_redirect_uri# value.
* `AllApplications`
** End the SSO session and make a `GET` request to all configured Logout URLs for every application in the tenant.

[field]#oauthConfiguration.logoutURL# [type]#[String]#::
The logout URL for the Application. FusionAuth will redirect to this URL after the user logs out of OAuth.

[field]#oauthConfiguration.proofKeyForCodeExchangePolicy# [type]#[String]# [since]#Available since 1.28.0#::
Determines the PKCE requirements when using the authorization code grant.
+
The possible values are:
+
include::_application-oauthConfiguration-proofKeyForCodeExchangePolicy.adoc[]

[field]#oauthConfiguration.requireClientAuthentication# [type]#[Boolean]# [since]#Available since 1.3.0# [deprecated]#Deprecated#::
Determines if the OAuth 2.0 Token endpoint requires client authentication. If this is enabled, the cloient must provide client credentials when using the Token endpoint. The `client_id` and `client_secret` may be provided using a Basic Authorization HTTP header, or by sending these parameters in the request body using POST data.
+
[deprecated]#Deprecated in version 1.28.0#
In version 1.28.0 and beyond, client authentication can be managed via [field]#oauthConfiguration.clientAuthenticationPolicy#.

[field]#oauthConfiguration.requireRegistration# [type]#[Boolean]# [since]#Available since 1.28.0#::
Determines if the user will be required to be registered, or complete registration before redirecting to the configured callback in the authorization code grant or the implicit grant. This configuration does not affect any other grant, and does not affect the API usage.

[source,json]
.Example Response JSON
----
include::../../../src/json/applications/oauth-configuration/response.json[]
----
