==== Response Body

[.api]
[field]#application.id# [type]#[UUID]#::
The Id of the Application.

[field]#application.active# [type]#[Boolean]#::
Whether or not the Application is active.

[field]#application.authenticationTokenConfiguration.enabled# [type]#[Boolean]#::
Whether or not Users can have Authentication Tokens associated with this Application.

[field]#application.cleanSpeakConfiguration.applicationIds# [type]#[Array<UUID>]#::
An array of UUIDs that map to the CleanSpeak applications for this Application. It is possible that a single Application in FusionAuth might have multiple Applications in CleanSpeak. For example, a FusionAuth Application for a game might have one CleanSpeak Application for usernames and another Application for chat.
+
This property is used when CleanSpeak sends user action notifications to FusionAuth (when users are disciplined for example). FusionAuth will translate the CleanSpeak ids to FusionAuth ids and then apply the user action.

[field]#application.cleanSpeakConfiguration.enabled# [type]#[Boolean]#::
True if CleanSpeak integration is enabled. This setting is global and is not modifiable using this API.

[field]#application.cleanSpeakConfiguration.usernameModeration.applicationId# [type]#[UUID]#::
The Id of the CleanSpeak application that usernames are sent to for moderation.

[field]#application.cleanSpeakConfiguration.usernameModeration.enabled# [type]#[Boolean]#::
True if CleanSpeak username moderation is enabled.

[field]#application.data# [type]#[Object]#::
An object that can hold any information about the Application that should be persisted.

[field]#application.jwtConfiguration.accessTokenKeyId# [type]#[UUID]# [since]#Available since 1.6.0#::
The Id of the signing key used to sign the access token.

[field]#application.jwtConfiguration.algorithm# [type]#[String]# [deprecated]#Deprecated#::
include::_jwt_algorithm.adoc[]
+
&nbsp;
+
[deprecated]#Removed in version 1.6.0# In version 1.6.0 and beyond, JWT configuration can be managed in the `link:./keys[Keys API]` and Keymaster.

[field]#application.jwtConfiguration.enabled# [type]#[Boolean]#::
Indicates if this application is using the JWT configuration defined here or the global JWT configuration defined by the System Configuration. If this is `false` the signing algorithm configured in the System Configuration will be used. If `true` the signing algorithm defined in this application will be used.

[field]#application.jwtConfiguration.idTokenKeyId# [type]#[UUID]# [since]#Available since 1.6.0#::
The Id of the signing key used to sign the Id token.

[field]#application.jwtConfiguration.privateKey# [type]#[String]# [deprecated]#Deprecated#::
The private key used when an `RSA` signing algorithm has been selected. The private key will be used to sign the JWT. This key will be returned in a PEM encoded format.
+
&nbsp;
+
[deprecated]#Removed in version 1.6.0# In version 1.6.0 and beyond, JWT configuration can be managed in the `link:./keys[Keys API]` and Keymaster.

[field]#application.jwtConfiguration.publicKey# [type]#[String]# [deprecated]#Deprecated#::
The public key used when an `RSA` signing algorithms has been selected. The public key will be used to verify JWTs signed with the private key. This key will be returned in a PEM encoded format.
+
&nbsp;
+
[deprecated]#Removed in version 1.6.0# In version 1.6.0 and beyond, JWT configuration can be managed in the `link:./keys[Keys API]` and Keymaster.

[field]#application.jwtConfiguration.refreshTokenTimeToLiveInMinutes# [type]#[Integer]# [since]#Available since 1.2.0#::
The length of time in minutes the JWT refresh token will live before it is expired and is not able to be exchanged for a JWT.

[field]#application.jwtConfiguration.secret# [type]#[String]# [deprecated]#Deprecated#::
The secret used when an `HMAC` based signing algorithm has been selected. This secret is used to sign and verify JWTs.
+
&nbsp;
+
[deprecated]#Removed in version 1.5.0# In version 1.5.0 and beyond, when selecting an `HMAC` algorithm, the `client_secret` from the OAuth configuration will be used to sign and verify the JWTs.

[field]#application.jwtConfiguration.timeToLiveInSeconds# [type]#[Integer]#::
The length of time in seconds the JWT will live before it is expired and no longer valid.

[field]#application.lambdaConfiguration.accessTokenPopulateId# [type]#[UUID]# [since]#Available since 1.6.0#::
The Id of the Lambda that will be invoked when an access token is generated for this application. This will be utilized during OAuth2 and OpenID Connect authentication requests as well as when an access token is generated for the Login API.

[field]#application.lambdaConfiguration.idTokenPopulateId# [type]#[UUID]# [since]#Available since 1.6.0#::
The Id of the Lambda that will be invoked when an Id token is generated for this application during an OpenID Connect authentication request.

[field]#application.lambdaConfiguration.samlv2PopulateId# [type]#[UUID]# [since]#Available since 1.6.0#::
The Id of the Lambda that will be invoked when a a SAML response is generated during a SAML authentication request.

[field]#application.name# [type]#[String]#::
The name of the Application.

[field]#application.loginConfiguration.allowTokenRefresh# [type]#[Boolean]# [since]#Available since 1.5.0#::
Indicates if a JWT may be refreshed using a Refresh Token for this application. This configuration is separate from issuing new Refresh Tokens which is controlled by the `generateRefreshTokens` parameter. This configuration indicates specifically if an existing Refresh Token may be used to request a new JWT using the link:jwt#refresh-a-jwt[Refresh API].

[field]#application.loginConfiguration.generateRefreshTokens# [type]#[Boolean]# [since]#Available since 1.5.0#::
Indicates if a Refresh Token should be issued from the Login API.

[field]#application.loginConfiguration.requireAuthentication# [type]#[Boolean]# [since]#Available since 1.5.0#::
Indicates if the Login API should require an API key. If you set this value to `false` and your FusionAuth API is on a public network, anyone may attempt to use the Login API.

[field]#application.oauthConfiguration.authorizedOriginURLs# [type]#[Array<String>]#::
An array of URLs that are the authorized origins for FusionAuth OAuth.

[field]#application.oauthConfiguration.authorizedRedirectURLs# [type]#[Array<String>]#::
An array of URLs that are the authorized redirect URLs for FusionAuth OAuth.

[field]#application.oauthConfiguration.clientId# [type]#[String]#::
The OAuth client Id of the Application.

[field]#application.oauthConfiguration.clientSecret# [type]#[String]#::
The OAuth client secret.

[field]#application.oauthConfiguration.deviceVerificationURL# [type]#[String]# [since]#Available since 1.11.0#::
The device verification URL to be used with the Device Code grant type.

[field]#application.oauthConfiguration.enabledGrants# [type]#[Array<String>]# [since]#Available since 1.5.0#::
The enabled grants for this application.
+
Supported values include:
+
* `authorization_code`
* `implicit`
* `password`
* `refresh_token`
* `device_code` &nbsp; [since]#Available since 1.11.0#

[field]#application.oauthConfiguration.generateRefreshTokens# [type]#[Boolean]# [since]#Available since 1.3.0#::
Determines if the OAuth 2.0 Token endpoint will generate a refresh token when the `offline_access` scope is requested.

[field]#application.oauthConfiguration.logoutBehavior# [type]#[String]# [since]#Available since 1.11.0#::
Behavior when `/oauth2/logout` is called.
+
Valid values:
+
* `RedirectOnly`
** End the SSO session and redirect to the configured Logout URL or the passed in [field]#post_logout_redirect_uri# value.
* `AllApplications`
** End the SSO session and make a `GET` request to all configured Logout URLs for every application in the tenant.

[field]#application.oauthConfiguration.logoutURL# [type]#[String]#::
The logout URL for the Application. FusionAuth will redirect to this URL after the user logs out of OAuth.

[field]#application.oauthConfiguration.requireClientAuthentication# [type]#[Boolean]# [since]#Available since 1.3.0#::
Determines if the OAuth 2.0 Token endpoint requires client authentication. If this is enabled, the client must provide client credentials when using the Token endpoint. The `client_id` and `client_secret` may be provided using a Basic Authorization HTTP header, or by sending these parameters in the request body using POST data.

[field]#application.passwordlessConfiguration.enabled# [type]#[Boolean]# [since]#Available since 1.5.0#::
Determines if passwordless login is enabled for this application.

[field]#application.registrationConfiguration.birthDate.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `birthDate` field will be included on the registration form.

[field]#application.registrationConfiguration.birthDate.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `birthDate` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.confirmPassword# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the password should be confirmed during self service registration, this means that the user will be required to type the password twice.

[field]#application.registrationConfiguration.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if self service registration is enabled for this application. When this value is false, you may still use the Registration API, this only affects if the self service option is available during the OAuth 2.0 login.

[field]#application.registrationConfiguration.firstName.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `firstName` field will be included on the registration form.

[field]#application.registrationConfiguration.firstName.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `firstName` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.fullName.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `fullName` field will be included on the registration form.

[field]#application.registrationConfiguration.fullName.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `fullName` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.lastName.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `lastName` field will be included on the registration form.

[field]#application.registrationConfiguration.lastName.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `lastName` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.loginIdType# [type]#[String]# [since]#Available since 1.4.0#::
The unique login Id that will be collected during registration, this value can be `email` or `username`. Leaving the default value of `email` is preferred because an email address is globally unique.
+
- `email`
- `username`

[field]#application.registrationConfiguration.middleName.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `middleName` field will be included on the registration form.

[field]#application.registrationConfiguration.middleName.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `middleName` field is required when displayed on the registration form.

[field]#application.registrationConfiguration.mobilePhone.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `mobilePhone` field will be included on the registration form.

[field]#application.registrationConfiguration.mobilePhone.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `mobilePhone` field is required when displayed on the registration form.

[field]#application.registrationDeletePolicy.unverified.enabled# [type]#[Boolean]# [since]#Available since 1.13.0#::
Indicates that users without a verified registration for this application will have their registration permanently deleted after [field]#application.registrationDeletePolicy.unverified.numberOfDaysToRetain# days.

[field]#application.registrationDeletePolicy.unverified.numberOfDaysToRetain# [type]#[Integer]# [since]#Available since 1.13.0#::
The number of days from registration a user's registration will be retained before being deleted for not completing registration verification. Value must be greater than 0.

[field]#application.roles# [type]#[Array]#::
An array of Role objects.

[field]#application.roles``[x]``.description# [type]#[String]#::
A description of the role.

[field]#application.roles``[x]``.id# [type]#[UUID]#::
The Id of the Role.

[field]#application.roles``[x]``.name# [type]#[String]#::
The name of the Role.

[field]#application.roles``[x]``.isDefault# [type]#[Boolean]#::
Whether or not the Role is a default role. A default role is automatically assigned to a user during registration if no roles are provided.

[field]#application.roles``[x]``.isSuperRole# [type]#[Boolean]#::
Whether or not the Role is a considered to be a super user role. This is a marker to indicate that it supersedes all other roles. FusionAuth will attempt to enforce this contract when using the web UI, it is not enforced programmatically when using the API.

[field]#application.samlv2Configuration.audience# [type]#[String]# [since]#Available since 1.6.0#::
The audience for the SAML response sent to back to the service provider from FusionAuth. Some service providers require different audience values than the `issuer` and this configuration option lets you change the `audience` in the response.

[field]#application.samlv2Configuration.callbackURL# [type]#[String]# [since]#Available since 1.6.0#::
The URL of the callback (sometimes called the Assertion Consumer Service or ACS). This is where FusionAuth sends the browser after the user logs in via SAML.

[field]#application.samlv2Configuration.debug# [type]#[Boolean]# [since]#Available since 1.6.0#::
Whether or not FusionAuth will log SAML debug messages to the event log. This is useful for debugging purposes.

[field]#application.samlv2Configuration.enabled# [type]#[Boolean]# [since]#Available since 1.6.0#::
Whether or not the SAML IdP for this Application is enabled or not.

[field]#application.samlv2Configuration.issuer# [type]#[String]# [since]#Available since 1.6.0#::
The issuer that identifies the service provider and allows FusionAuth to load the correct Application and SAML configuration.

[field]#application.samlv2Configuration.keyId# [type]#[UUID]# [since]#Available since 1.6.0#::
The id of the Key used to sign the SAML response.

[field]#application.samlv2Configuration.logoutURL# [type]#[String]# [since]#Available since 1.6.0#::
The URL that the browser is taken to after the user logs out of the SAML service provider.

[field]#application.samlv2Configuration.xmlSignatureC14nMethod# [type]#[String]# [since]#Available since 1.6.0#::
The XML signature canonicalization method used when digesting and signing the SAML response.

[field]#application.verificationEmailTemplateId# [type]#[UUID]#::
The Id of the Email Template that is used to send the Registration Verification emails to users.

[field]#application.verifyRegistration# [type]#[Boolean]#::
Whether or not registrations to this Application may be verified.

[source,json]
.Example Response JSON for a Single Application
----
include::../../../src/json/applications/response.json[]
----
