[api]
ifeval::["{base_field_name}" != "application"]
[field]#{base_field_name}# [type]#[Array]#::
The list of Application objects.
endif::[]

[field]#{base_field_name}.active# [type]#[Boolean]# [deprecated]#Deprecated#::
Whether or not the Application is active.
+
[deprecated]#Deprecated in version 1.22.0#
In version 1.22.0 and beyond, prefer the use of [field]#state#.

[field]#{base_field_name}.authenticationTokenConfiguration.enabled# [type]#[Boolean]#::
Whether or not Users can have Authentication Tokens associated with this Application.

[field]#{base_field_name}.cleanSpeakConfiguration.applicationIds# [type]#[Array<UUID>]#::
An array of UUIDs that map to the CleanSpeak applications for this Application. It is possible that a single Application in FusionAuth might have multiple Applications in CleanSpeak. For example, a FusionAuth Application for a game might have one CleanSpeak Application for usernames and another Application for chat.
+
This property is used when CleanSpeak sends user action notifications to FusionAuth (when users are disciplined for example). FusionAuth will translate the CleanSpeak ids to FusionAuth ids and then apply the user action.

[field]#{base_field_name}.cleanSpeakConfiguration.enabled# [type]#[Boolean]#::
True if CleanSpeak integration is enabled. This setting is global and is not modifiable using this API.

[field]#{base_field_name}.cleanSpeakConfiguration.usernameModeration.applicationId# [type]#[UUID]#::
The Id of the CleanSpeak application that usernames are sent to for moderation.

[field]#{base_field_name}.cleanSpeakConfiguration.usernameModeration.enabled# [type]#[Boolean]#::
True if CleanSpeak username moderation is enabled.

[field]#{base_field_name}.data# [type]#[Object]#::
An object that can hold any information about the Application that should be persisted.

[field]#{base_field_name}.formConfiguration.adminRegistrationFormId# [type]#[UUID]# [since]#Available since 1.20.0#::
The unique Id of the form to use for the Add and Edit User Registration form when used in the FusionAuth admin UI. 

[field]#{base_field_name}.id# [type]#[UUID]#::
The unique identifier for this Application.

[field]#{base_field_name}.insertInstant# [type]#[Long]# [since]#Available since 1.18.0#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Application was added to the FusionAuth database.

[field]#{base_field_name}.jwtConfiguration.accessTokenKeyId# [type]#[UUID]# [since]#Available since 1.6.0#::
The Id of the signing key used to sign the access token.

[field]#{base_field_name}.jwtConfiguration.algorithm# [type]#[String]# [deprecated]#Deprecated#::
include::_jwt_algorithm.adoc[]
+
&nbsp;
+
[deprecated]#Removed in version 1.6.0# In version 1.6.0 and beyond, JWT configuration can be managed in the `link:/docs/v1/tech/apis/keys/[Keys API]` and Keymaster.

[field]#{base_field_name}.jwtConfiguration.enabled# [type]#[Boolean]#::
Indicates if this application is using the JWT configuration defined here or the global JWT configuration defined by the Tenant. If this is `false` the signing algorithm configured in the Tenant will be used. If `true` the signing algorithm defined in this application will be used.

[field]#{base_field_name}.jwtConfiguration.idTokenKeyId# [type]#[UUID]# [since]#Available since 1.6.0#::
The Id of the signing key used to sign the Id token.

[field]#{base_field_name}.jwtConfiguration.privateKey# [type]#[String]# [deprecated]#Deprecated#::
The private key used when an `RSA` signing algorithm has been selected. The private key will be used to sign the JWT. This key will be returned in a PEM encoded format.
+
&nbsp;
+
[deprecated]#Removed in version 1.6.0# In version 1.6.0 and beyond, JWT configuration can be managed in the `link:/docs/v1/tech/apis/keys/[Keys API]` and Keymaster.

[field]#{base_field_name}.jwtConfiguration.publicKey# [type]#[String]# [deprecated]#Deprecated#::
The public key used when an `RSA` signing algorithms has been selected. The public key will be used to verify JWTs signed with the private key. This key will be returned in a PEM encoded format.
+
&nbsp;
+
[deprecated]#Removed in version 1.6.0# In version 1.6.0 and beyond, JWT configuration can be managed in the `link:/docs/v1/tech/apis/keys/[Keys API]` and Keymaster.

[field]#{base_field_name}.jwtConfiguration.refreshTokenTimeToLiveInMinutes# [type]#[Integer]# [since]#Available since 1.2.0#::
The length of time in minutes the JWT refresh token will live before it is expired and is not able to be exchanged for a JWT.

[field]#{base_field_name}.jwtConfiguration.secret# [type]#[String]# [deprecated]#Deprecated#::
The secret used when an `HMAC` based signing algorithm has been selected. This secret is used to sign and verify JWTs.
+
&nbsp;
+
[deprecated]#Removed in version 1.5.0# In version 1.5.0 and beyond, when selecting an `HMAC` algorithm, the `client_secret` from the OAuth configuration will be used to sign and verify the JWTs.

[field]#{base_field_name}.jwtConfiguration.timeToLiveInSeconds# [type]#[Integer]#::
The length of time in seconds the JWT will live before it is expired and no longer valid.

[field]#{base_field_name}.lambdaConfiguration.accessTokenPopulateId# [type]#[UUID]# [since]#Available since 1.6.0#::
The Id of the Lambda that will be invoked when an access token is generated for this application. This will be utilized during OAuth2 and OpenID Connect authentication requests as well as when an access token is generated for the Login API.

[field]#{base_field_name}.lambdaConfiguration.idTokenPopulateId# [type]#[UUID]# [since]#Available since 1.6.0#::
The Id of the Lambda that will be invoked when an Id token is generated for this application during an OpenID Connect authentication request.

[field]#{base_field_name}.lambdaConfiguration.samlv2PopulateId# [type]#[UUID]# [since]#Available since 1.6.0#::
The Id of the Lambda that will be invoked when a a SAML response is generated during a SAML authentication request.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]# [since]#Available since 1.18.0#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Application was last updated in the FusionAuth database.

[field]#{base_field_name}.name# [type]#[String]#::
The name of the Application.

[field]#{base_field_name}.loginConfiguration.allowTokenRefresh# [type]#[Boolean]# [since]#Available since 1.5.0#::
Indicates if a JWT may be refreshed using a Refresh Token for this application. This configuration is separate from issuing new Refresh Tokens which is controlled by the `generateRefreshTokens` parameter. This configuration indicates specifically if an existing Refresh Token may be used to request a new JWT using the link:/docs/v1/tech/apis/jwt#refresh-a-jwt[Refresh API].

[field]#{base_field_name}.loginConfiguration.generateRefreshTokens# [type]#[Boolean]# [since]#Available since 1.5.0#::
Indicates if a Refresh Token should be issued from the Login API.

[field]#{base_field_name}.loginConfiguration.requireAuthentication# [type]#[Boolean]# [since]#Available since 1.5.0#::
Indicates if the Login API should require an API key. If you set this value to `false` and your FusionAuth API is on a public network, anyone may attempt to use the Login API.

[field]#{base_field_name}.multiFactorConfiguration.email.templateId# [type]#[UUID]# [since]#Available since 1.26.0#::
The Id of the email template that is used when notifying a user to complete a multi-factor authentication request.

[field]#{base_field_name}.multiFactorConfiguration.sms.templateId# [type]#[UUID]# [since]#Available since 1.26.0#::
The Id of the SMS template that is used when notifying a user to complete a multi-factor authentication request.

[field]#{base_field_name}.oauthConfiguration.authorizedOriginURLs# [type]#[Array<String>]#::
An array of URLs that are the authorized origins for FusionAuth OAuth. 
+
When this configuration is omitted, all HTTP origins are allowed to use the browser based grants and the HTTP response header of `X-Frame-Options: DENY` will be added to each response to disallow iframe loading.

[field]#{base_field_name}.oauthConfiguration.authorizedRedirectURLs# [type]#[Array<String>]#::
An array of URLs that are the authorized redirect URLs for FusionAuth OAuth.

[field]#{base_field_name}.oauthConfiguration.clientId# [type]#[String]#::
The OAuth client Id of the Application.

[field]#{base_field_name}.oauthConfiguration.clientSecret# [type]#[String]#::
The OAuth client secret.

[field]#{base_field_name}.oauthConfiguration.debug# [type]#[Boolean]# [since]#Available since 1.25.0#::
Whether or not FusionAuth will log a debug Event Log. This is particular useful for debugging the authorization code exchange with the Token endpoint during an Authorization Code grant.

[field]#{base_field_name}.oauthConfiguration.deviceVerificationURL# [type]#[String]# [since]#Available since 1.11.0#::
The device verification URL to be used with the Device Code grant type.

[field]#{base_field_name}.oauthConfiguration.enabledGrants# [type]#[Array<String>]# [since]#Available since 1.5.0#::
The enabled grants for this application.
+
Supported values include:
+
* `authorization_code`
* `implicit`
* `password`
* `refresh_token`
* `device_code` &nbsp; [since]#Available since 1.11.0#

[field]#{base_field_name}.oauthConfiguration.generateRefreshTokens# [type]#[Boolean]# [since]#Available since 1.3.0#::
Determines if the OAuth 2.0 Token endpoint will generate a refresh token when the `offline_access` scope is requested.

[field]#{base_field_name}.oauthConfiguration.logoutBehavior# [type]#[String]# [since]#Available since 1.11.0#::
Behavior when `/oauth2/logout` is called.
+
Valid values:
+
* `RedirectOnly`
** End the SSO session and redirect to the configured Logout URL or the passed in [field]#post_logout_redirect_uri# value.
* `AllApplications`
** End the SSO session and make a `GET` request to all configured Logout URLs for every application in the tenant.

[field]#{base_field_name}.oauthConfiguration.logoutURL# [type]#[String]#::
The logout URL for the Application. FusionAuth will redirect to this URL after the user logs out of OAuth.

[field]#{base_field_name}.oauthConfiguration.requireClientAuthentication# [type]#[Boolean]# [since]#Available since 1.3.0#::
Determines if the OAuth 2.0 Token endpoint requires client authentication. If this is enabled, the client must provide client credentials when using the Token endpoint. The `client_id` and `client_secret` may be provided using a Basic Authorization HTTP header, or by sending these parameters in the request body using POST data.

[field]#{base_field_name}.passwordlessConfiguration.enabled# [type]#[Boolean]# [since]#Available since 1.5.0#::
Determines if passwordless login is enabled for this application.

[field]#{base_field_name}.registrationConfiguration.birthDate.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `birthDate` field will be included on the registration form.

[field]#{base_field_name}.registrationConfiguration.birthDate.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `birthDate` field is required when displayed on the registration form.

[field]#{base_field_name}.registrationConfiguration.confirmPassword# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the password should be confirmed during self service registration, this means that the user will be required to type the password twice.

[field]#{base_field_name}.registrationConfiguration.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if self service registration is enabled for this application. When this value is false, you may still use the Registration API, this only affects if the self service option is available during the OAuth 2.0 login.

[field]#{base_field_name}.registrationConfiguration.firstName.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `firstName` field will be included on the registration form.

[field]#{base_field_name}.registrationConfiguration.firstName.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `firstName` field is required when displayed on the registration form.

[field]#{base_field_name}.registrationConfiguration.formId# [type]#[UUID]# [since]#Available since 1.18.0#::
The Id of an associated link:/docs/v1/tech/apis/forms/[Form] when using `advanced` registration configuration type.

[field]#{base_field_name}.registrationConfiguration.fullName.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `fullName` field will be included on the registration form.

[field]#{base_field_name}.registrationConfiguration.fullName.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `fullName` field is required when displayed on the registration form.

[field]#{base_field_name}.registrationConfiguration.lastName.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `lastName` field will be included on the registration form.

[field]#{base_field_name}.registrationConfiguration.lastName.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `lastName` field is required when displayed on the registration form.

[field]#{base_field_name}.registrationConfiguration.loginIdType# [type]#[String]# [since]#Available since 1.4.0#::
The unique login Id that will be collected during registration, this value can be `email` or `username`. Leaving the default value of `email` is preferred because an email address is globally unique.
+
- `email`
- `username`

[field]#{base_field_name}.registrationConfiguration.middleName.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `middleName` field will be included on the registration form.

[field]#{base_field_name}.registrationConfiguration.middleName.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `middleName` field is required when displayed on the registration form.

[field]#{base_field_name}.registrationConfiguration.mobilePhone.enabled# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `mobilePhone` field will be included on the registration form.

[field]#{base_field_name}.registrationConfiguration.mobilePhone.required# [type]#[Boolean]# [since]#Available since 1.4.0#::
Determines if the `mobilePhone` field is required when displayed on the registration form.

[field]#{base_field_name}.registrationConfiguration.type# [type]#[String]# [since]#Available since 1.18.0#::
The type of registration flow.
+
Supported values include:
+
* `basic` - the basic self registration options available prior to version 1.18.0.
* `advanced` - advanced usage of custom forms, requires a paid edition of FusionAuth.

[field]#{base_field_name}.registrationDeletePolicy.unverified.enabled# [type]#[Boolean]# [since]#Available since 1.13.0#::
Indicates that users without a verified registration for this application will have their registration permanently deleted after [field]#{base_field_name}.registrationDeletePolicy.unverified.numberOfDaysToRetain# days.

[field]#{base_field_name}.registrationDeletePolicy.unverified.numberOfDaysToRetain# [type]#[Integer]# [since]#Available since 1.13.0#::
The number of days from registration a user's registration will be retained before being deleted for not completing registration verification. Value must be greater than 0.

[field]#{base_field_name}.roles# [type]#[Array]#::
An array of Role objects.

[field]#{base_field_name}.roles``[x]``.description# [type]#[String]#::
A description of the role.

[field]#{base_field_name}.roles``[x]``.id# [type]#[UUID]#::
The Id of the Role.

[field]#{base_field_name}.roles``[x]``.name# [type]#[String]#::
The name of the Role.

[field]#{base_field_name}.roles``[x]``.isDefault# [type]#[Boolean]#::
Whether or not the Role is a default role. A default role is automatically assigned to a user during registration if no roles are provided.

[field]#{base_field_name}.roles``[x]``.isSuperRole# [type]#[Boolean]#::
Whether or not the Role is a considered to be a super user role. This is a marker to indicate that it supersedes all other roles. FusionAuth will attempt to enforce this contract when using the web UI, it is not enforced programmatically when using the API.

[field]#{base_field_name}.samlv2Configuration.audience# [type]#[String]# [since]#Available since 1.6.0#::
The audience for the SAML response sent to back to the service provider from FusionAuth. Some service providers require different audience values than the `issuer` and this configuration option lets you change the `audience` in the response.

[field]#{base_field_name}.samlv2Configuration.authorizedRedirectURLs# [type]#[Array<String>]# [since]#Available since 1.20.0#::
One or more authorized URLS that may be specified by the SAML v2 Service Provider in the Authentication request `<AssertionConsumerServiceURL>` element. If a requested URL is not in this list the request will be rejected by FusionAuth.
+
This is the URL that FusionAuth will send the SAML response during a SAML login request, this URL is also referred to as the Assertion Consumer Service or ACS). If the the Authentication request does not contain the `<AssertionConsumerServiceURL>` element, the first URL found in this list will be used to send the SAML response back to the Service Provider.

[field]#{base_field_name}.samlv2Configuration.callbackURL# [type]#[String]# [since]#Available since 1.6.0# [deprecated]#Deprecated#::
The URL of the callback (sometimes called the Assertion Consumer Service or ACS). This is where FusionAuth sends the browser after the user logs in via SAML.
+
[deprecated]#Deprecated in version 1.20.0# 
This field is preserved for backwards compatibility and may be removed in a future release. This is the first value found in the [field]#authorizedRedirectURLs# parameter.

[field]#{base_field_name}.samlv2Configuration.debug# [type]#[Boolean]# [since]#Available since 1.6.0#::
Whether or not FusionAuth will log SAML debug messages to the event log. This is useful for debugging purposes.

[field]#{base_field_name}.samlv2Configuration.defaultVerificationKeyId# [type]#[UUID]#  [since]#Available since 1.20.0#::
The verification key used to verify a signature when the SAML v2 Service Provider is using HTTP Redirect Bindings. 
+ 
When HTTP POST Bindings are used, this is the default verification key used if a `<KeyInfo>` element is not found in the SAML AuthNRequest. If a `<KeyInfo>` element is found, Key Master will be used to resolve the key and this configuration will not be used to verify the request signature.

[field]#{base_field_name}.samlv2Configuration.enabled# [type]#[Boolean]# [since]#Available since 1.6.0#::
Whether or not the SAML IdP for this Application is enabled or not.

[field]#{base_field_name}.samlv2Configuration.issuer# [type]#[String]# [since]#Available since 1.6.0#::
The issuer that identifies the service provider and allows FusionAuth to load the correct Application and SAML configuration.

[field]#{base_field_name}.samlv2Configuration.keyId# [type]#[UUID]# [since]#Available since 1.6.0#::
The unique Id of the Key used to sign the SAML response.

[field]#{base_field_name}.samlv2Configuration.logout.behavior# [type]#[String]# [since]#Available since 1.25.0#::
The possible values are:
+
 * `AllParticipants` - each session participant that has enabled single logout will be sent a Logout Request
 * `OnlyOriginator` - no other session participants will be notified when a logout request is sent for this application
+
This configuration is functionally equivalent to the Logout Behavior found in the OAuth2 configuration.

[field]#{base_field_name}.samlv2Configuration.logout.defaultVerificationKeyId# [type]#[UUID]# [since]#Available since 1.25.0#::
The unique Id of the Key used to verify the signature if the public key cannot be determined by the `KeyInfo` element when using POST bindings, or the key used to verify the signature when using HTTP Redirect bindings.

[field]#{base_field_name}.samlv2Configuration.logout.keyId# [type]#[UUID]# [since]#Available since 1.25.0#::
The unique Id of the Key used to sign the SAML Logout response. 

[field]#{base_field_name}.samlv2Configuration.logout.requireSignedRequests# [type]#[Boolean]# [since]#Available since 1.25.0#::
When this value is `true` all Logout requests missing a signature will be rejected.

[field]#{base_field_name}.samlv2Configuration.logout.singleLogout.enabled# [type]#[Boolean]# [since]#Available since 1.25.0#::
Whether or not SAML Single Logout for this SAML IdP is enabled.

[field]#{base_field_name}.samlv2Configuration.logout.singleLogout.keyId# [type]#[UUID]# [since]#Available since 1.25.0#::
The unique Id of the Key used to sign the SAML Single Logout response. 

[field]#{base_field_name}.samlv2Configuration.logout.singleLogout.url# [type]#[String]# [since]#Available since 1.25.0#::
The URL at which you want to receive the `LogoutRequest` from FusionAuth.

[field]#{base_field_name}.samlv2Configuration.logout.singleLogout.xmlSignatureC14nMethod# [type]#[String]# [since]#Available since 1.25.0#::
The XML signature canonicalization method used when digesting and signing the Single Logout response.
+
include::../shared/_xmlSignatureC14nMethod-values.adoc[]

[field]#{base_field_name}.samlv2Configuration.logout.xmlSignatureC14nMethod# [type]#[String]# [optional]#Optional# [default]#Defaults to `exclusive_with_comments`# [since]#Available since 1.25.0#::
The XML signature canonicalization method used when digesting and signing the Logout response.
+
include::../shared/_xmlSignatureC14nMethod-values.adoc[]

[field]#{base_field_name}.samlv2Configuration.logoutURL# [type]#[String]# [since]#Available since 1.6.0#::
The URL that the browser is taken to after the user logs out of the SAML service provider.

[field]#{base_field_name}.samlv2Configuration.requireSignedRequests# [type]#[Boolean]#  [since]#Available since 1.20.0#::
When this value is `true` all requests missing a signature will be rejected.

[field]#{base_field_name}.samlv2Configuration.xmlSignatureC14nMethod# [type]#[String]# [since]#Available since 1.6.0#::
The XML signature canonicalization method used when digesting and signing the SAML response.
+
include::../shared/_xmlSignatureC14nMethod-values.adoc[]

[field]#{base_field_name}.samlv2Configuration.xmlSignatureLocation# [type]#[String]# [since]#Available since 1.21.0#::
The location to place the XML signature when signing the SAML response.
+
The possible values are:
+
* `Assertion` - The XML signature will be added as a child element of the Assertion.
* `Response` - The XML signature will be added as a child element of the Response.

[field]#{base_field_name}.state# [type]#[String]# [since]#Available since 1.22.0#::
The current state of the application. The following are valid values:
+
* `Active` - The tenant is active.
* `Inactive` - The application is not active. An application can not be modified or authenticated against when inactive.

[field]#{base_field_name}.verificationEmailTemplateId# [type]#[UUID]#::
The Id of the Email Template that is used to send the Registration Verification emails to users.

[field]#{base_field_name}.verifyRegistration# [type]#[Boolean]#::
Whether or not registrations to this Application may be verified.

ifeval::["{base_field_name}" == "application"]
[source,json]
.Example Response JSON for a Single Application
----
include::../../../src/json/applications/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "application"]
[source,json]
.Example Response JSON for all the Applications
----
include::../../../src/json/applications/responses.json[]
----
endif::[]
