==== Response Body

[.api]
[field]#consent.consentEmailTemplateId# [type]#[UUID]#::
The Id of the Email Template that is used to send confirmation to the end user.

[field]#consent.countryMinimumAgeForSelfConsent# [type]#[Map<Locale, Integer>]#::
This property optionally overrides the value provided in [field]#defaultMinimumAgeForSelfConsent# if a more specific value is defined. This can be useful when the age of self consent varies by country.
+
&nbsp;
+
For example, consider the following definition:
+
[source,json]
----
{
  "de": 17
}
----
+
If a user has defined their preferred locale to be Germany (`de`), the age of self consent defined for Germany will be used instead of the value defined by [field]#defaultMinimumAgeForSelfConsent#.

[field]#consent.defaultMinimumAgeForSelfConsent# [type]#[Integer]#::
The default age of self consent used when granting this consent to a user unless a more specific one is provided by the [field]#countryMinimumAgeForSelfConsent#.
+
A user that meets the minimum age of self consent may self-consent, this means the recipient may also be the giver.

[field]#consent.emailPlus.enabled# [type]#[Boolean]#::
When this value is `true` the Email Plus workflow is enabled.
+
Email Plus provides and additional opportunity to notify the giver that consent was provided. For example, if [field]#consentEmailTemplateId# is provided then when the consent is granted an email will be sent to notify the giver that consent was granted to the user. When using Email Plus a follow up email will be sent to the giver at a randomly selected time within the configured minimum and maximum range of hours.

[field]#consent.emailPlus.emailTemplateId# [type]#[UUID]#::
The Id of the Email Template that is used to send the reminder notice to the consent giver.

[field]#consent.emailPlus.maximumTimeToSendEmailInHours# [type]#[Integer]#::
The maximum number of hours to wait until sending the reminder notice the consent giver.

[field]#consent.emailPlus.minimumTimeToSendEmailInHours# [type]#[Integer]#::
The minimum number of hours to wait until sending the reminder notice the consent giver.

[field]#consent.id# [type]#[UUID]#::
The unique Id of the consent.

[field]#consent.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Consent was added to the FusionAuth database.

[field]#consent.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Consent was updated in the FusionAuth database.

[field]#consent.multipleValuesAllowed# [type]#[Boolean]#::
When this value is `true` more than one value may be used when granting this consent to a User.
+
This value is not used when no [field]#values# have been defined for this consent.

[field]#consent.name# [type]#[String]#::
The unique name of the consent.

[field]#consent.values# [type]#[Array<String>]#::
One or more values that may be assigned for this consent.

[source,json]
.Example Response JSON
----
include::../../../src/json/consents/response.json[]
----
