==== Request Body

[.api]
[field]#emailTemplate.defaultFromName# [type]#[String (FreeMarker Enabled)]# [required]#Required#::
The default From Name used when sending emails. This is the display name part of the email address ( i.e. **Jared Dunn**  <jared@piedpiper.com>).

[field]#emailTemplate.defaultHtmlTemplate# [type]#[String (FreeMarker Enabled)]# [required]#Required#::
The default HTML Email Template.

[field]#emailTemplate.defaultSubject# [type]#[String (FreeMarker Enabled)]# [required]#Required#::
The default Subject used when sending emails.

[field]#emailTemplate.defaultTextTemplate# [type]#[String (FreeMarker Enabled)]# [required]#Required#::
The default Text Email Template.

[field]#emailTemplate.fromEmail# [type]#[String]# [required]#Required#::
The email address that this email will be sent from. This is the address part email address (i.e.  Jared Dunn  <**jared@piedpiper.com**>).

[field]#emailTemplate.localizedFromNames# [type]#[Map<Locale,String (FreeMarker Enabled)>]# [optional]#Optional#::
The From Name used when sending emails to users who speak other languages. This overrides the default From Name based on the user's list of preferred languages.

[field]#emailTemplate.localizedHtmlTemplates# [type]#[Map<Locale,String (FreeMarker Enabled)>]# [optional]#Optional#::
The HTML Email Template used when sending emails to users who speak other languages. This overrides the default HTML Email Template based on the user's list of preferred languages.

[field]#emailTemplate.localizedSubjects# [type]#[Map<Locale,String (FreeMarker Enabled)>]# [optional]#Optional#::
The Subject used when sending emails to users who speak other languages. This overrides the default Subject based on the user's list of preferred languages.

[field]#emailTemplate.localizedTextTemplates# [type]#[Map<Locale,String (FreeMarker Enabled)>]# [optional]#Optional#::
The Text Email Template used when sending emails to users who speak other languages. This overrides the default Text Email Template based on the user's list of preferred languages.

[field]#emailTemplate.name# [type]#[String]# [required]#Required#::
A descriptive name for the email template (i.e. "April 2016 Coupon Email")

[source,json]
.Example Request JSON
----
include::../../../src/json/email-templates/request.json[]
----
