==== Response Body

[.api]
[field]#emailTemplate.defaultFromName# [type]#[String]#::
The default From Name used when sending emails. If not provided, and a localized value cannot be determined, the default value for the tenant will be used.  This is the display name part of the email address ( i.e. **Jared Dunn**  <jared@piedpiper.com>).

[field]#emailTemplate.defaultHtmlTemplate# [type]#[String]#::
The default HTML Email Template.

[field]#emailTemplate.defaultSubject# [type]#[String]#::
The default Subject used when sending emails.

[field]#emailTemplate.defaultTextTemplate# [type]#[String]#::
The default Text Email Template.

[field]#emailTemplate.fromEmail# [type]#[String]#::
The email address that this email will be sent from.  If not provided, the default value for the tenant will be used. This is the address part email address (i.e.  Jared Dunn  <**jared@piedpiper.com**>).

[field]#emailTemplate.id# [type]#[UUID]#::
The Id of Email Template.

[field]#emailTemplate.localizedFromNames# [type]#[Map<Locale,String>]#::
The From Name used when sending emails to users who speak other languages. This overrides the default From Name based on the user's list of preferred languages.

[field]#emailTemplate.localizedHtmlTemplates# [type]#[Map<Locale,String>]#::
The HTML Email Template used when sending emails to users who speak other languages. This overrides the default HTML Email Template based on the user's list of preferred languages.

[field]#emailTemplate.localizedSubjects# [type]#[Map<Locale,String>]#::
The Subject used when sending emails to users who speak other languages. This overrides the default Subject based on the user's list of preferred languages.

[field]#emailTemplate.localizedTextTemplates# [type]#[Map<Locale,String>]#::
The Text Email Template used when sending emails to users who speak other languages. This overrides the default Text Email Template based on the user's list of preferred languages.

[field]#emailTemplate.name# [type]#[String]#::
A descriptive name for the email template (i.e. "April 2016 Coupon Email")

[source,json]
.Example Response JSON for a Single Email Template
----
include::../../../src/json/email-templates/response.json[]
----
