[api]
ifeval::["{base_field_name}" != "entityType"]
[field]#{base_field_name}s# [type]#[Array]#::
The list of EntityType objects.
endif::[]

[field]#{base_field_name}.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Entity Type that should be persisted.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Entity Type was added to the FusionAuth database.

[field]#{base_field_name}.jwtConfiguration.accessTokenKeyId# [type]#[UUID]# [since]#Available since 1.6.0#::

[field]#{base_field_name}.jwtConfiguration.accessTokenKeyId# [type]#[UUID]# [optional]#Optional#::
The unique id of the signing key used to sign the access token.
+
Required when `enabled` is set to `true`.

[field]#{base_field_name}.jwtConfiguration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Indicates if this application is using the JWT configuration defined here or the global JWT configuration defined by the Tenant. If this is `false` the signing algorithm configured in the Tenant will be used. If `true` the signing algorithm defined in this application will be used. 

[field]#{base_field_name}.jwtConfiguration.timeToLiveInSeconds# [type]#[Integer]# [optional]#Optional#::
The length of time in seconds the JWT will live before it is expired and no longer valid.
+
Required when `enabled` is set to `true`.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Entity Type was last updated in the FusionAuth database.

[field]#{base_field_name}.name# [type]#[String]#::

[field]#{base_field_name}.name# [type]#[String]# [required]#Required#::
A descriptive name for the entity type (i.e. "Customer" or "Email_Service")

ifeval::["{base_field_name}" == "entityType"]
[source,json]
.Example Response JSON for a Single Entity Type
----
include::../../../src/json/entity-types/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "entityType"]
[source,json]
.Example Response JSON for all Entity Types
----
include::../../../src/json/entity-types/responses.json[]
----
endif::[]
