[api]
ifeval::["{base_field_name}" != "entity"]
[field]#{base_field_name}# [type]#[Array]#::
The list of Entity objects.
endif::[]

[field]#{base_field_name}.data# [type]#[Object]#::
An object that can hold any information about the Entity that should be persisted. Please review the link:/docs/v1/tech/reference/limitations#data-field-limitations[limits on data field types] as you plan for and build your custom data schema.

[field]#{base_field_name}.clientId# [type]#[String]#::
The OAuth 2.0 client Id. 

[field]#{base_field_name}.clientSecret# [type]#[String]#::
The OAuth 2.0 client secret. 

[field]#{base_field_name}.id# [type]#[UUID]#::
The unique Id of the Entity.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Entity was added to the FusionAuth database.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Entity was last updated in the FusionAuth database.

[field]#{base_field_name}.name# [type]#[String]#::
A descriptive name for the Entity (i.e. "Raviga" or "Email Service").

[field]#{base_field_name}.tenantId# [type]#[UUID]#::
The Id of the Tenant to which this Entity belongs.

[field]#{base_field_name}.type# [type]#[Object]#::
The Entity Type of this Entity. Consult the Entity Type documentation for more details about the fields of this object.

ifeval::["{base_field_name}" == "entity"]
[source,json]
.Example Response JSON for an Entity
----
include::../../../src/json/entities/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "entity"]
[source,json]
.Example Response JSON for multiple Entities
----
include::../../../src/json/entities/responses.json[]
----
endif::[]
