[api]
ifeval::["{base_field_name}" != "entityType"]
[field]#{base_field_name}# [type]#[Array]#::
The list of EntityType objects.
endif::[]

[field]#{base_field_name}.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Entity Type that should be persisted.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Entity Type was added to the FusionAuth database.

[field]#{base_field_name}.jwtConfiguration.accessTokenKeyId# [type]#[UUID]# [optional]#Optional#::
The unique id of the signing key used to sign the access token.

[field]#{base_field_name}.jwtConfiguration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Indicates if this application is using the JWT configuration defined here.

[field]#{base_field_name}.jwtConfiguration.timeToLiveInSeconds# [type]#[Integer]# [optional]#Optional#::
The length of time in seconds the JWT will live before it is expired and no longer valid.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Entity Type was last updated in the FusionAuth database.

[field]#{base_field_name}.name# [type]#[String]#::
The name of the entity type (i.e. "Customer" or "Email_Service").

[field]#{base_field_name}.permissions# [type]#[Array]#::
An array of Permission objects.

[field]#{base_field_name}.permissions``[x]``.description# [type]#[String]#::
A description of the role.

[field]#{base_field_name}.permissions``[x]``.id# [type]#[UUID]#::
The Id of the Permission.

[field]#{base_field_name}.permissions``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Permission was added to the FusionAuth database.

[field]#{base_field_name}.permissions``[x]``.isDefault# [type]#[Boolean]#::
Whether or not the Permission is a default role. A default role is automatically assigned to an Entity if no permissions are provided.

[field]#{base_field_name}.permissions``[x]``.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Permission was last updated in the FusionAuth database.

[field]#{base_field_name}.permissions``[x]``.name# [type]#[String]#::
The name of the Permission.

ifeval::["{base_field_name}" == "entityType"]
[source,json]
.Example Response JSON for a Single Entity Type
----
include::../../../src/json/entity-types/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "entityType"]
[source,json]
.Example Response JSON for all Entity Types
----
include::../../../src/json/entity-types/responses.json[]
----
endif::[]
