[api]
ifeval::["{base_field_name}" != "grant"]
[field]#{base_field_name}# [type]#[Array]#::
The list of Grant objects.
endif::[]

[field]#{base_field_name}.data# [type]#[Object]#::
An object that can hold any information about the Grant that should be persisted. 

[field]#{base_field_name}.entity# [type]#[Object]#::
The target Entity of this Grant. Consult the Entity documentation for more details about the fields of this object.

[field]#{base_field_name}.id# [type]#[UUID]#::
The unique Id of the Grant.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Grant was added to the FusionAuth database.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Grant was last updated in the FusionAuth database.

[field]#{base_field_name}.permissions# [type]#[Array<String>]# [optional]#Optional#::
The set of permissions of this Grant.

[field]#{base_field_name}.recipientEntityId# [type]#[UUID]# [optional]#Optional#::
The Entity Id for which access is granted.

[field]#{base_field_name}.userId# [type]#[UUID]# [optional]#Optional#::
The User Id for which access is granted.

ifeval::["{base_field_name}" == "grant"]
[source,json]
.Example Response JSON for a Single Grant
----
include::../../../src/json/entities/grant-response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "grant"]
[source,json]
.Example Response JSON for Multiple Grants
----
include::../../../src/json/entities/grant-responses.json[]
----
endif::[]
