[api]
ifeval::["{base_field_name}" != "entityGrant"]
[field]#{base_field_name}# [type]#[Array]#::
The list of Entity Grant objects.
endif::[]

[field]#{base_field_name}.data# [type]#[Object]#::
An object that can hold any information about the Entity Grant that should be persisted. 

[field]#{base_field_name}.id# [type]#[UUID]#::
The unique Id of the Entity Grant.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Entity Grant was added to the FusionAuth database.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Entity Grant was last updated in the FusionAuth database.

[field]#entityGrant.permissions# [type]#[Array<String>]# [optional]#Optional#::
The set of permissions of this Entity Grant.

[field]#entityGrant.recipientEntityId# [type]#[UUID]# [optional]#Optional#::
The Entity Id for which access is granted.

[field]#entityGrant.userId# [type]#[UUID]# [optional]#Optional#::
The User Id for which access is granted.

ifeval::["{base_field_name}" == "entityGrant"]
[source,json]
.Example Response JSON for a Single Entity Grant
----
include::../../../src/json/entities/grant-response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "entityGrant"]
[source,json]
.Example Response JSON for Multiple Entity Grants
----
include::../../../src/json/entities/grant-responses.json[]
----
endif::[]
