==== Response Body

[.api]
[field]#families# [type]#[Array<Object>]#::
The list of Family objects.

[field]#families``[x]``.id# [type]#[UUID]#::
The unique Id of the family.

[field]#families``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Family was added to the FusionAuth database.

[field]#families``[x]``.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Family was updated in the FusionAuth database.

[field]#families``[x]``.members# [type]#[Array<Object>]#::
The members of this family.

[field]#families``[x]``.members``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the user was added to the family.

[field]#families``[x]``.members``[x]``.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the family member was last updated.

[field]#families``[x]``.members``[x]``.owner# [type]#[Boolean]#::
True if this user is the owner of the family, the first Adult user in the family will automatically be set as the owner. A teen or child cannot be the family owner.

[field]#families``[x]``.members``[x]``.role# [type]#[String]#::
The role of the family member. The possible values are:
+
* `Adult`
* `Child`
* `Teen`

[field]#families``[x]``.members``[x]``.userId# [type]#[UUID]#::
The unique user Id of the family member.

[source,json]
.Example Response JSON
----
include::../../../src/json/family/responses.json[]
----
