==== Response Body

[.api]
[field]#users``[x]``.active# [type]#[Boolean]#::
True if the User is active. False if the User has been deactivated. Deactivated Users will not be able to login.

[field]#users``[x]``.birthDate# [type]#[String]#::
The User's birthdate formatted as `YYYY-MM-DD`

[field]#users``[x]``.data# [type]#[Object]#::
An object that can hold any information about the User that should be persisted.

[field]#users``[x]``.email# [type]#[String]#::
The User's email address.

[field]#users``[x]``.fullName# [type]#[String]#::
The User's full name as a separate field that is not calculated from [field]#firstName# and [field]#lastName#.

[field]#users``[x]``.id# [type]#[UUID]#::
The User's unique Id.

[field]#users``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when user was created.

[field]#users``[x]``.parentEmail# [type]#[String]#::
The user's parent's email address.

[field]#users``[x]``.passwordChangeRequired# [type]#[Boolean]#::
Indicates that the User's password needs to be changed during their next login attempt.

[field]#users``[x]``.passwordLastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the User last changed their password.

[field]#users``[x]``.preferredLanguages# [type]#[Array<String>]#::
An array of locale strings that give, in order, the User's preferred languages. These are important for email templates and other localizable text. See link:/docs/v1/tech/reference/data-types/#locales[Locales].

[field]#users``[x]``.tenantId# [type]#[UUID]#::
The Id of the Tenant that this User belongs to.

[field]#users``[x]``.timezone# [type]#[String]#::
The User's preferred timezone. This can be used as a default to display instants, and it is recommended that you allow User's to change this per-session. The string will be in an https://www.iana.org/time-zones[IANA] time zone format.

[field]#users``[x]``.twoFactor.methods``[x]``.authenticator.algorithm# [type]#[String]#::
The algorithm used by the TOTP authenticator. With the current implementation, this will always be `HmacSHA1`.

[field]#users``[x]``.twoFactor.methods``[x]``.authenticator.codeLength# [type]#[Integer]#::
The length of code generated by the TOTP. With the current implementation, this will always be `6`.

[field]#users``[x]``.twoFactor.methods``[x]``.authenticator.timeStep# [type]#[Integer]#::
The time-step size in seconds. With the current implementation, this will always be 30.

[field]#users``[x]``.twoFactor.methods``[x]``.email# [type]#[String]#::
The value of the email address for this method. Only present if [field]#user.twoFactor.methods``[x]``.method# is `email`.

[field]#users``[x]``.twoFactor.methods``[x]``.id# [type]#[String]#::
The unique Id of the method.

[field]#users``[x]``.twoFactor.methods``[x]``.lastUsed# [type]#[Boolean]#::
`true` if this method was used most recently.

[field]#users``[x]``.twoFactor.methods``[x]``.method# [type]#[String]#::
The type of this method. There will also be an object with the same value containing additional information about this method.  The possible values are:
+
* `authenticator`
* `email`
* `sms`

[field]#users``[x]``.twoFactor.methods``[x]``.mobilePhone# [type]#[String]#::
The value of the mobile phone for this method. Only present if [field]#user.twoFactor.methods``[x]``.method# is `sms`.

[field]#users``[x]``.twoFactor.methods``[x]``.secret# [type]#[String]#::
A base64 encoded secret
+
This field is required when [field]#method# is `authenticator`.

[field]#users``[x]``.twoFactor.recoveryCodes# [type]#[Array<String>]#::
A list of recovery codes. These may be used in place of a code provided by an MFA factor. They are single use.
+
If a recovery code is used in a disable request, all MFA methods are removed. If, after that, a Multi-Factor method is added, a new set of recovery codes will be generated.

[field]#users``[x]``.twoFactorDelivery# [type]#[String]# [deprecated]#Deprecated#::
The User's preferred delivery for verification codes during a two factor login request.
+
The possible values are:
+
* `None`
* `TextMessage`

[deprecated]#Removed in version 1.26.0#

[field]#users``[x]``.twoFactorEnabled# [type]#[Boolean]# [deprecated]#Deprecated#::
Determines if the User has two factor authentication enabled for their account or not.
+
[deprecated]#Removed in version 1.26.0#

[field]#users``[x]``.username# [type]#[String]#::
The username of the User.

[field]#users``[x]``.usernameStatus# [type]#[String]#::

include::_moderation_status_response.adoc[]

[field]#users``[x]``.verified# [type]#[Boolean]#::
Whether or not the User's email has been verified.

[source,json]
.Example Response JSON
----
include::../../../src/json/family/pending-response.json[]
----
