==== Request Body

[.api]

[field]#form.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Form that should be persisted.

[field]#form.type# [type]#[String]# [optional]#Optional# [since]#Available since 1.20.0#::::
The type of registration associated with this form. The possible values are:
+
 * `registration` which is used for self-service registration processes
 * `adminRegistration` which is used for administrator registration processes, utilizes `registration.data.*` custom fields
 * `adminUser` which is used for administrator registration process, utilizes `user.data.*` custom fields
+
The form will default to `registration` type if not passed in.

[field]#form.name# [type]#[String]# [required]#Required#::
The unique name of the Form.

[field]#form.steps# [type]#[Array<Object>]# [required]#Required#::
An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.

[field]#form.steps``[x]``.fields# [type]#[Array<UUID>]#::
An ordered list of Form Field Ids assigned to this step.

[source,json]
.Example Request JSON
----
include::../../../src/json/forms/request.json[]
----
