==== Request Body

[.api]

[field]#form.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Form that should be persisted.

[field]#form.name# [type]#[String]# [required]#Required#::
The unique name of the Form.

[field]#form.steps# [type]#[Array<Object>]# [required]#Required#::
An ordered list of objects containing one or more Form Fields. A Form must have at least one step defined.
+
Steps manifest in two different ways. When the form type is `adminRegistration` or `adminUser` steps will be rendered as `sections` because there are no multi-step forms within the UI. For `registration` each step will be considered a step within a multi-step form.
+
*Localization*
+
You may localize the displayed value of this key during registration by adding the key to your theme.
For example, if you specify the key value of `{user-form-section}1` this key value be rendered in the UI, where `1` specifies the section number to adjust the value of.
+
Adding the following message to your theme will cause the first section of the User add or edit form to be rendered as "Optionally name me!". This feature allows you to customize and optionally localize each section heading within the User form.
+ 
```
{user-form-section}1=Optionally name me!
```
+
You may optionally provide a specific label per tenant by prefixing the value the with the tenant Id as follows:
+
```
[cbeaf8fe-f4a7-4a27-9f77-c609f1b01856]{user-form-section}2=Tenant specific label for section 2
```
+
You may also optionally provide a specific label per application for a registration form by prefixing the value the with the application Id as follows:
+
```
[cfb5fab7-b3b6-41bb-adfa-d23ac83a96e5]{registration-form-section}2=Application specific label for section 2
```

[field]#form.steps``[x]``.fields# [type]#[Array<UUID>]#::
An ordered list of Form Field Ids assigned to this step.

[field]#form.type# [type]#[String]# [optional]#Optional# [default]#defaults to `registration`# [since]#Available since 1.20.0#::
The type of form being created, a form type cannot be changed after the form has been created. This type will be used to identify how this form can be utilized by FusionAuth.
+
 * `registration` - This form will be used for self service registration.
 * `adminRegistration` - This form be used to customize the add and edit User Registration form in the FusionAuth UI. [since]#Available since 1.20.0#
 * `adminUser` - This form can be used to customize the add and edit User form in the FusionAuth UI. [since]#Available since 1.20.0#
+
Prior to version `1.20.0`, the default form type was `registration`.

[source,json]
.Example Request JSON
----
include::../../../src/json/forms/request.json[]
----
