==== Response Body

[.api]
[field]#forms# [type]#[Array]#::
The list of Form objects.

[field]#forms``[x]``.data# [type]#[Object]#::
An object that can hold any information about the Form that should be persisted.

[field]#forms``[x]``.id# [type]#[UUID]#::
The unique Id of the Form.

[field]#forms``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Form was added to the FusionAuth database.

[field]#forms``[x]``.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Form was last updated in the FusionAuth database.

[field]#forms``[x]``.name# [type]#[String]#::
The unique name of the Form.

[field]#forms``[x]``.steps# [type]#[Array<Object>]#::
An ordered list of objects containing one or more Form Fields.

[field]#forms``[x]``.steps``[x]``.fields# [type]#[Array<UUID>]#::
An ordered list of Form Field Id's assigned to this step.

[field]#forms``[x]``.type# [type]#[String]#::
The Form type. The possible values are:
+
* `registration` This form will be used for self service registration.
* `adminRegistration` This form be used to customize the add and edit User Registration form in the FusionAuth UI.
* `adminUser` This form can be used to customize the add and edit User form in the FusionAuth UI.

[source,json]
.Example Response JSON
----
include::../../../src/json/forms/responses.json[]
----
