==== Response Body

[.api]
[field]#fields# [type]#[Array]#::
The list of Form Field objects.

[field]#fields``[x]``.confirm# [type]#[Boolean]#::
Determines if the `control` field should be verified. If `true`, a confirmation field is included.

[field]#fields``[x]``.consentId# [type]#[UUID]#::
The Id of an existing link:/docs/v1/tech/apis/consent[Consent].

[field]#fields``[x]``.control# [type]#[String]#::
The Form Field control. The possible values are:
+
* `checkbox`
* `number`
* `password`
* `radio`
* `select`
* `textarea`
* `text`

[field]#fields``[x]``.data# [type]#[Object]#::
An object that can hold any information about the Form Field that should be persisted.

[field]#fields``[x]``.description# [type]#[String]##::
A description of the Form Field.

[field]#fields``[x]``.id# [type]#[UUID]#::
The unique Id of the form field.

[field]#fields``[x]``.insertInstant# [type]#[Integer]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the form field was added to the FusionAuth database.

[field]#fields``[x]``.key# [type]#[String]#::
The key is the path to the value in the `user` or `registration` object.
The possible values include:
+
* `registration.username`
* `user.birthDate`
* `user.email`
* `user.firstname`
* `user.fullName`
* `user.lastName`
* `user.middleName`
* `user.mobilePhone`
* `user.password`
* `user.username`
* `registration.data.*`
* `user.data.*`

[field]#fields``[x]``.lastUpdateInstant# [type]#[Integer]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the form field was last updated in the FusionAuth database.

[field]#fields``[x]``.name# [type]#[String]# [required]#Required#::
The unique name of the Form Field.

[field]#fields``[x]``.options# [type]#[Array<String>]#::
A list of options that are applied to `checkbox`, `radio`, `select`, or `textarea` controls.

[field]#fields``[x]``.required# [type]#[Boolean]#::
Determines if a value is required for the Form Field.

[field]#fields``[x]``.type# [type]#[String]#::
The data type used to store the value in FusionAuth. The possible values are:
+
* `bool`
* `consent`
* `date`
* `email`
* `number`
* `string`

[field]#fields``[x]``.validator# [type]#[Object]#::
When enabled, user input will be evaluated against the `expression`.

[field]#fields``[x]``.validator.enabled# [type]#[Boolean]#::
Determines if user input should be validated.

[field]#fields``[x]``.validator.expression# [type]#[String]#::
A regular expression used to validate user input.

[source,json]
.Example Response JSON
----
include::../../../src/json/form-fields/responses.json[]
----
