==== Response Body

[.api]
[field]#form.data# [type]#[Object]#::
An object that can hold any information about the Form that should be persisted.

[field]#form.id# [type]#[UUID]#::
The unique Id of the Form.

[field]#form.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Form was added to the FusionAuth database.

[field]#form.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Form was last updated in the FusionAuth database.

[field]#form.name# [type]#[String]#::
The unique name of the Form.

[field]#form.steps# [type]#[Array<Object>]#::
An ordered list of objects containing one or more Form Fields.

[field]#form.steps``[x]``.fields# [type]#[Array<UUID>]#::
An ordered list of Form Field Ids assigned to this step.

[field]#form.type# [type]#[String]#::
The form type. The possible values are:
+
* `registration` This form will be used for self service registration.
* `adminRegistration` This form be used to customize the add and edit User Registration form in the FusionAuth UI.
* `adminUser` This form can be used to customize the add and edit User form in the FusionAuth UI.

[source,json]
.Example Response JSON
----
include::../../../src/json/forms/response.json[]
----
