==== Request Body

[.api]

[field]#field.confirm# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if [field]#control# should be verified. If `true`, a confirmation field is included.

[field]#field.consentId# [type]#[UUID]# [optional]#Optional#::
The Id of an existing link:/docs/v1/tech/apis/consent[Consent].

[field]#field.control# [type]#[String]# [optional]#Optional# [default]#See description for default information#::
The Form Field control. The possible values are:
+
 * `checkbox`
 * `number`
 * `password`
 * `radio`
 * `select`
 * `textarea`
 * `text`
+
When a predefined [field]#key# field is used, [field]#control# will be defaulted. `user.password` defaults to `password`. All other [field]#key# values default to `text`.

[field]#field.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the Form Field that should be persisted.
This may be useful to add additional meta data to the field that will help you style or render the Form Field. For example, in the JSON examples provided for this API you will see an attribute added to this data field as follows:
+
```
"data": {
 "leftAddOn": "user"
}
```
This additional meta data is then used to render an icon on the Form Field. Use of this additional data is optional and not required to render the field.

[field]#field.description# [type]#[String]# [optional]#Optional#::
A description of the Form Field.

[field]#field.key# [type]#[String]# [required]#Required#::
The key is the path to the value in the `user` or `registration` object.
+
*Predefined keys*
+
 * `registration.username`
 * `user.birthDate`
 * `user.email`
 * `user.firstname`
 * `user.fullName`
 * `user.lastName`
 * `user.middleName`
 * `user.mobilePhone`
 * `user.password`
 * `user.username`
+
*Custom Keys*
+
When defining a key to store custom data, you may use one of the following prefixes:
+
 * `user.data`
 * `registration.data`.
+
For example, in order to store a custom value on the user object to collect the User's favorite color, set the key value equal to `user.data.favoriteColor`.
+
A valid key name must not contain spaces or special characters. An array may be specified by using the array syntax of `[0]` to indicate the first position in an array. Nested objects may be specified by using the object syntax of `['foo']` to indicate the named property of the object named foo.
+
 * `user.data.preferences['color']` would store the value in an object named preferences with a key of color.
 * `user.data.preferences[0]` would store the value in the first position of an array named preferences.
+
*Translations*
+
You may translate the displayed value of this key during registration by adding the key to your theme.
For example, if you specify the key value of `user.data.favoriteColor` this will be rendered in the UI.
+
If you were to add the following messages to your theme, the translated form of the values will be shown to the end user. This allows you optionally localize the displayed value as well.
+
```
user.data.favoriteColor=Favorite color
```

[field]#field.name# [type]#[String]# [required]#Required#::
The unique name of the Form Field.

[field]#field.options# [type]#[Array<String>]# [optional]#Optional#::
A list of options that are applied to `checkbox`, `radio`, or `select` controls.
+
You may translate the displayed values during registration by adding these values to your theme.
+
For example, if you specify the values `["red", "green", "blue"]` as the field options, these will be stored on the user in this lowercase form. By default the values `red`, `green` and `blue` will be rendered in the UI.
+
If you were to add the following messages to your theme, the capitalized form of the values will be shown to the end user. This allows you optionally localize the displayed values as well.
+
```
red=Red
green=Green
blue=Blue
```
+
```
red=Roja
green=Verde
blue=Azul
```

[field]#field.required# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if a value is required for the Form Field.

[field]#field.type# [type]#[String]# [optional]#Optional# [default]#defaults to `string`, unless `user.birthDate`, then `date`, or if `user.email` then `email`.#::
The data type used to store the value in FusionAuth. The possible values are:
+
 * `bool`
 * `consent`
 * `date`
 * `email`
 * `number`
 * `string`
+
If the value provided by the user cannot be converted to the requested data type a validation error will occur.
+
When using the `date` type, the only supported data format is ISO-8601 or `YYY-MM-DD`. You may want to use a JavaScript data picker that can convert the selected value to this format.
+
When using the `consent` type, the field [field]#consentId# must be included in the request.

[field]#field.validator.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if user input should be validated.

[field]#field.validator.expression# [type]#[String]# [optional]#Optional#::
A regular expression used to validate user input.

[source,json]
.Example Request JSON
----
include::../../../src/json/form-fields/request.json[]
----
