==== {response_body_title}

[.api]

[field]#field.confirm# [type]#[Boolean]#::
Determines if the `control` field should be verified. If `true`, a confirmation field is included.

[field]#field.consentId# [type]#[UUID]#::
The Id of an existing link:/docs/v1/tech/apis/consent[Consent].

[field]#field.control# [type]#[String]#::
The Form Field control. The possible values are:
+
* `checkbox`
* `number`
* `password`
* `radio`
* `select`
* `textarea`
* `text`

[field]#field.data# [type]#[Object]#::
An object that can hold any information about the Form Field that should be persisted.

[field]#field.description# [type]#[String]#::
A description of the Form Field.

[field]#field.id# [type]#[UUID]#::
The unique Id of the form field.

[field]#field.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the form field was added to the FusionAuth database.

[field]#field.key# [type]#[String]#::
The key is the path to the value in the `user` or `registration` object.
The possible values include:
+
* `registration.username`
* `user.birthDate`
* `user.email`
* `user.firstname`
* `user.fullName`
* `user.lastName`
* `user.middleName`
* `user.mobilePhone`
* `user.password`
* `user.username`
* `registration.data.*`
* `user.data.*`

[field]#field.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the form field was last updated in the FusionAuth database.

[field]#field.name# [type]#[String]#::
The unique name of the Form Field.

[field]#field.options# [type]#[Array<String>]#::
A list of options that are applied to `checkbox`, `radio`, `select`, or `textarea` controls.

[field]#field.required# [type]#[Boolean]#::
Determines if a value is required for the Form Field.

[field]#field.type# [type]#[String]#::
The data type used to store the value in FusionAuth. The possible values are:
+
* `bool`
* `consent`
* `date`
* `email`
* `number`
* `string`

[field]#field.validator# [type]#[Object]#::
When enabled, user input will be evaluated against the `expression`.

[field]#field.validator.enabled# [type]#[Boolean]#::
Determines if user input should be validated.

[field]#field.validator.expression# [type]#[String]#::
A regular expression used to validate user input.

[source,json]
.Example Response JSON
----
include::../../../src/json/form-fields/response.json[]
----
