==== Response Body

[.api]
[field]#groups# [type]#[Array]#::
The list of Group objects.

[field]#groups``[x]``.data# [type]#[Object]#::
An object that can hold any information about the Group that should be persisted.

[field]#groups``[x]``.id# [type]#[UUID]#::
The name of the Group.

[field]#groups``[x]``.name# [type]#[String]#::
The name of the Group.

[field]#groups``[x]``.roles# [type]#[Map<UUID, List<Object>]#::
The roles assigned to this Group. The map key is the Application Id, the value is an array of Application Roles.

[field]#groups``[x]``.roles``[applicationId]````[x]``.description# [type]#[String]#::
The description of the role.

[field]#groups``[x]``.roles``[applicationId]````[x]``.id# [type]#[UUID]#::
The Application Role Unique Id

[field]#groups``[x]``.roles``[applicationId]````[x]``.name# [type]#[String]#::
The name of the Group.

[field]#groups``[x]``.roles``[applicationId]````[x]``.isDefault# [type]#[Boolean]#::
Whether or not the Role is a default role. A default role is automatically assigned to a user during registration if no roles are provided.

[field]#groups``[x]``.roles``[applicationId]````[x]``.isSuperRole# [type]#[Boolean]#::
Whether or not the Role is a considered to be a super user role. This is a marker to indicate that it supersedes all other roles. FusionAuth will attempt to enforce this contract when using the web UI, it is not enforced programmatically when using the API.

[source,json]
.Example Response JSON
----
include::../../../src/json/groups/responses.json[]
----
