==== Response Body

[.api]
[field]#group.data# [type]#[Object]#::
An object that can hold any information about the Group that should be persisted.

[field]#group.id# [type]#[UUID]#::
The unique Id of the Group.

[field]#group.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Group was added to the FusionAuth database.

[field]#group.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Group was updated in the FusionAuth database.

[field]#group.name# [type]#[String]#::
The name of the Group.

[field]#group.roles# [type]#[Map<UUID, List<Object>]#::
The roles assigned to this Group. The map key is the Application Id, the value is an array of Application Roles.

[field]#group.roles``[applicationId]````[x]``.description# [type]#[String]#::
The description of the role.

[field]#group.roles``[applicationId]````[x]``.id# [type]#[UUID]#::
The Application Role Unique Id

[field]#group.roles``[applicationId]````[x]``.name# [type]#[String]#::
The name of the Group.

[field]#group.roles``[applicationId]````[x]``.isDefault# [type]#[Boolean]#::
Whether or not the Role is a default role. A default role is automatically assigned to a user during registration if no roles are provided.

[field]#group.roles``[applicationId]````[x]``.isSuperRole# [type]#[Boolean]#::
Whether or not the Role is a considered to be a super user role. This is a marker to indicate that it supersedes all other roles. FusionAuth will attempt to enforce this contract when using the web UI, it is not enforced programmatically when using the API.

[source,json]
.Example Response JSON
----
include::../../../src/json/groups/response.json[]
----
