==== Request Body

[.api]
[field]#credentials# [type]#[Array]# [required]#Required#::
The list of passkeys to import.

[field]#credentials``[x]``.algorithm# [type]#[Long]# [required]#Required#::
The identifier for the signing algorithm used with the passkey. These values are defined by https://www.rfc-editor.org/rfc/rfc9053[RFC 9053]. FusionAuth supports a subset of these algorithms.

[field]#credentials``[x]``.attestationType# [type]#[String]# [optional]#Optional# [default]#defaults to `none`#::
The attestation type provided when the passkey was registered. FusionAuth cannot validate the attestation on import. This is for record keeping only.

[field]#credentials``[x]``.authenticatorSupportsUserVerification# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Indicates whether user verification was provided at the time the passkey was registered.

[field]#credentials``[x]``.credentialId# [type]#[String]# [required]#Required#::
The credential Id generated by the authenticator stored as a base64URL-encoded string. This value is used by authenticators to look up a passkey during an authentication ceremony.

[field]#credentials``[x]``.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the passkey that should be persisted.

[field]#credentials``[x]``.discoverable# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Indicates whether the passkey is "client-side discoverable." Discoverable passkeys can be used in authentication ceremonies without first identifying the user (e.g. by requiring the user to complete a form field).

[field]#credentials``[x]``.displayName# [type]#[String]# [required]#Required#::
The display name for the passkey selected during registration.

[field]#credentials``[x]``.id# [type]#[UUID]# [optional]#Optional# [default]#defaults to secure random UUID#::
The Id of the passkey. If not specified a secure random UUID will be generated.

[field]#credentials``[x]``.insertInstant# [type]#[Long]# [optional]#Optional# [default]#defaults to now#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when passkey was created.

[field]#credentials``[x]``.lastUseInstant# [type]#[Long]# [optional]#Optional# [default]#defaults to now#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when passkey was last used.

[field]#credentials``[x]``.name# [type]#[String]# [optional]#Optional# [default]#defaults to **[see description]**#::
A unique name meant to disambiguate passkeys with the same [field]#credential.displayName#. If this value is omitted, a string of four alphabetic characters will be generated. The combination of characters will be unique among the passkeys in this bulk import request.

[field]#credentials``[x]``.publicKey# [type]#[String]# [required]#Required#::
The passkey's public key, encoded in PEM format.

[field]#credentials``[x]``.relyingPartyId# [type]#[String]# [required]#Required#::
The Relying Party Id used at the time the passkey was registered.
+
[WARNING]
====
This value **must** match the `rpId` value when the passkey was created, _and_ the browser origin during WebAuthn authentication in FusionAuth must be compatible with that Relying Party Id.
====

[field]#credentials``[x]``.signCount# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The last known signature count for the passkey.

[field]#credentials``[x]``.transports# [type]#[List<String>]# [optional]#Optional# [default]#defaults to ``[ ]``#::
A list of transport types supported by the authenticator that generated the passkey. This value is used as a hint during the WebAuthn authentication ceremony to help identify eligible authenticators.

[field]#credentials``[x]``.userAgent# [type]#[String]# [optional]#Optional#::
The user agent at the time the passkey was registered. This can be useful for troubleshooting WebAuthn passkey issues.

[field]#credentials``[x]``.userId# [type]#[UUID]# [required]#Required#::
The Id of the user that this passkey belongs to.

[field]#validateDbConstraints# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Set this value to `true` in order to perform additional validation of the request.
+
The import request is intended to be used to migrate existing users' passkeys from one system to another, this means FusionAuth expects all user Ids from the request to exist for the requested tenant. If a non-existent user Id is encountered a `500` will be returned without this additional validation.
+
In order to get additional details about database constraint violations on import set this value to `true` and a `400` response will be returned with JSON body indicating the missing values encountered.
+
Setting this value to `true` will dramatically decrease the performance of this request. If importing large numbers of passkeys in a single request you may need to increase request timeouts to ensure this request does not timeout before it has completed.

[source,json]
.Example Request JSON
----
include::../../../src/json/webauthn/import-request.json[]
----