==== Request Body

[.api]
[field]#credentials# [type]#[Array]# [required]#Required#::
The list of passkeys to import.

[field]#credentials``[x]``.algorithm# [type]#[Long]# [required]#Required#::
The identifier for the signing algorithm used with the passkey. These values are defined by the https://www.iana.org/assignments/cose/cose.xhtml[IANA COSE Algorithms registry]. FusionAuth supports a subset of these algorithms.
+
include::_webauthn-supported-algorithms.adoc[]

[field]#credentials``[x]``.attestationType# [type]#[String]# [optional]#Optional# [default]#defaults to `none`#::
The attestation type provided when the passkey was registered. FusionAuth doesn't validate the attestation on import. Supported values are:
+
 * `anonymization-ca`
 * `attestation-ca`
 * `basic`
 * `none`
 * `self`
+
Passkeys registered in FusionAuth currently only support the `none` option, but another value can be supplied during passkey import.

[field]#credentials``[x]``.authenticatorSupportsUserVerification# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Indicates whether this authenticator supports user verification. User verification ensures that the user is authorized to use the authenticator.

[field]#credentials``[x]``.credentialId# [type]#[String]# [required]#Required#::
The credential Id generated by the authenticator is stored as a base64url-encoded string. This value is used by authenticators to look up a passkey during an authentication ceremony.

[field]#credentials``[x]``.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the passkey that should be persisted.

[field]#credentials``[x]``.discoverable# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Indicates whether the passkey is "client-side discoverable." Discoverable passkeys can be used in authentication ceremonies without first identifying the user (e.g. by requiring the user to provide their username).

[field]#credentials``[x]``.displayName# [type]#[String]# [required]#Required#::
The display name for the passkey.

[field]#credentials``[x]``.id# [type]#[UUID]# [optional]#Optional# [default]#defaults to secure random UUID#::
The Id of the passkey. If not specified a secure random UUID will be generated.

[field]#credentials``[x]``.insertInstant# [type]#[Long]# [optional]#Optional# [default]#defaults to now#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the passkey was created.

[field]#credentials``[x]``.lastUseInstant# [type]#[Long]# [optional]#Optional# [default]#defaults to now#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the passkey was last used.

[field]#credentials``[x]``.name# [type]#[String]# [required]#Required#::
A unique name meant to disambiguate passkeys with the same [field]#credential.displayName#.
+
Prior to version `1.42.0` this field was optional.

[field]#credentials``[x]``.publicKey# [type]#[String]# [required]#Required#::
The passkey's public key, encoded in PEM format.

[field]#credentials``[x]``.relyingPartyId# [type]#[String]# [required]#Required#::
The Relying Party Id used at the time the passkey was registered.
+
[WARNING.warning]
====
This value **must** match the `rpId` value when the passkey was created, _and_ the browser origin during WebAuthn authentication in FusionAuth must be compatible with that Relying Party Id.
====

[field]#credentials``[x]``.signCount# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The last known signature count for the passkey.

[field]#credentials``[x]``.transports# [type]#[List<String>]# [optional]#Optional# [default]#defaults to ``[ ]``#::
A list of transport types supported by the authenticator that generated the passkey. This value is used as a hint during the WebAuthn authentication ceremony to help identify eligible authenticators.
+
include::_webauthn-transports.adoc[]
+
The default value is the empty set, which means that no hints are provided. This does not negatively impact the authentication ceremony.

[field]#credentials``[x]``.userAgent# [type]#[String]# [optional]#Optional#::
The user agent at the time the passkey was registered. This can be useful for troubleshooting WebAuthn passkey issues.

[field]#credentials``[x]``.userId# [type]#[UUID]# [required]#Required#::
The Id of the user to which this passkey belongs.

[field]#validateDbConstraints# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Set this value to `true` in order to perform additional validation of the request.
+
The import request is intended to be used to migrate existing users' passkeys from one system to another, this means FusionAuth expects all user Ids from the request to exist for the provided tenant. If a non-existent user Id is encountered a `500` will be returned unless this field is set to `true`.
+
In order to get additional details about database constraint violations on import, set this value to `true` and a `400` response will be returned with a JSON body indicating the missing values encountered.
+
Setting this value to `true` will dramatically decrease the performance of this request. If importing large numbers of passkeys in a single request you may need to increase request timeouts to ensure this request does not timeout before it has completed.

[source,json]
.Example Request JSON
----
include::../../../src/json/webauthn/import-request.json[]
----