==== Response Body

[.api]
[field]#keys# [type]#[Array]#::
The list of Key objects.

[field]#keys``[x]``.algorithm# [type]#[String]#::
The algorithm used to encrypt the key.

[field]#keys``[x]``.certificate# [type]#[String]#::
The RSA or EC X.509 certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation# [type]#[Map<String, Object]#::
The RSA or EC certificate information.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation.issuer# [type]#[String]#::
The issuer of the RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation.md5Fingerprint# [type]#[String]#::
The md5 fingerprint of the RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation.serialNumber# [type]#[String]#::
The serial number of the RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation.sha1Fingerprint# [type]#[String]#::
The SHA-1 fingerprint of the RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation.sha1Thumbprint# [type]#[String]#::
The SHA-1 thumbprint of the RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation.sha256Fingerprint# [type]#[String]#::
The SHA-256 fingerprint of the RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation.sha256Thumbprint# [type]#[String]#::
The SHA-256 thumbprint of the RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation.subject# [type]#[String]#::
The subject of the RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation.validFrom# [type]#[Integer]#::
The UNIX time in milliseconds marking the start of the RSA or EC certificate validity period.  This field is omitted for HMAC key types.

[field]#keys``[x]``.certificateInformation.validTo# [type]#[Integer]#::
The UNIX time in milliseconds marking the expiration RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.expirationInstant# [type]#[Integer]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] marking the expiration RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.hasPrivateKey# [type]#[Boolean]#::
Because the private key will never be returned in the API response, this value will indicate if the private key is stored in FusionAuth. This field is omitted for HMAC key types.

[field]#keys``[x]``.id# [type]#[UUID]#::
The Id of the Key.

[field]#keys``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the key was added to the FusionAuth database.

[field]#keys``[x]``.issuer# [type]#[String]#::
The issuer of the RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.kid# [type]#[String]#::
The key identifier 'kid'.

[field]#keys``[x]``.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the key was updated in the FusionAuth database.

[field]#keys``[x]``.length# [type]#[String]#::
The length  of the RSA or EC certificate.  This field is omitted for HMAC key types.

[field]#keys``[x]``.name# [type]#[String]#::
The name of the key.

[field]#keys``[x]``.publicKey# [type]#[String]#::
The RSA or EC certificate public key.  This field is omitted for HMAC key types.

[field]#keys``[x]``.type# [type]#[String]#::
The key type.  The possible values are:
+
* `EC`
* `RSA`
* `HMAC`

[source,json]
.Example Response JSON
----
include::../../../src/json/keys/responses.json[]
----
