// keep in sync with login.adoc
[cols="1,9a"]
.Response Codes
|===
|Code |Description

|200
|The authentication was successful. The response will contain the User object that was authenticated.

|202
|The user was authenticated successfully. The user is not registered for the application specified by the `applicationId` on the request.
The response will contain the User object that was authenticated.

|203
|The user was authenticated successfully. The user is required to change their password, the response will contain the `changePasswordId` to be used
on the link:/docs/v1/tech/apis/users#change-a-users-password[Change Password] API.  Since version `1.15.0`, the response will also contain a `changePasswordReason` field which can have one of the following values:

* `Administrative` - An administrator has required this user to change their password.
* `Breached` - The password has been found to have belonged to a breached dataset and must be changed, per the Reactor configuration.
* `Expired` - The password has expired, per the expiration setting in the tenant configuration.
* `Validation` - The password fails the validation rules configured in the tenant password settings.

[source,json]
.Example Response JSON
----
include::../../../src/json/login/login-change-password-response.json[]
----

|212
|The user's email address has not yet been verified. The response will contain the User object that was authenticated.

|242
|The user was authenticated successfully. The user has two factor authentication enabled, the response will contain the `twoFactorId` to be used
on the link:/docs/v1/tech/apis/login#complete-two-factor-authentication[Complete Two Factor Authentication] API.

[source,json]
.Example Response JSON
----
include::../../../src/json/login/login-two-factor-response.json[]
----

|400
|The request was invalid and/or malformed. The response will contain an link:/docs/v1/tech/apis/errors/[Errors] JSON Object with the specific errors.

ifdef::auth_optional[]
|401
|You did not supply a valid Authorization header. The header was omitted or your API key was not valid. The response will be empty. See link:/docs/v1/tech/apis/authentication/[Authentication].

By default, this API will require authentication when called with an `applicationId`.

Authentication may be disabled per Application, see `application.loginConfiguration.requireAuthentication` in the Application API or the Security tab in the Application configuration. Prior to version `1.5.0` this API never require an API key.
endif::[]

|404
|The user was not found or the password was incorrect. The response will be empty.

|409
|The user is currently in an action that has prevented login. The response will contain the actions that prevented login.

[source,json]
.Example Response JSON
----
include::../../../src/json/login/login-prevented-response.json[]
----

|410
|The user has expired. The response will be empty.


|423
|

The user is locked and cannot login. The response will be empty.

Prior to version 1.9.0 a 404 status code will be returned instead.

|500
|There was an internal error. A stack trace is provided and logged in the FusionAuth log files. The response will be empty.

|503
|The search index is not available or encountered an exception so the request cannot be completed. The response will contain a JSON body.
|===
