[api]
ifeval::["{base_field_name}" != "{base_field_name}"]
[field]#{base_field_name}# [type]#[Array]#::
The list of Message Template objects.
endif::[]

[.api]
[field]#{base_field_name}.data# [type]#[Object]#::
An object that can hold any information about the Message Template that should be persisted.

[field]#{base_field_name}.defaultTemplate# [type]#[String (FreeMarker Enabled)]#::
The default Message Template.

[field]#{base_field_name}.id# [type]#[UUID]#::
The unique identifier for this Message Template.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Application was added to the FusionAuth database.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the Application was last updated in the FusionAuth database.
[field]#{base_field_name}.localizedTemplates# [type]#[Map<Locale,String (FreeMarker Enabled)>]#::
The Message Template used when sending messages to users who speak other languages. This overrides the default Message Template based on the user's list of preferred languages.

[field]#{base_field_name}.name# [type]#[String]#::
A descriptive name for the message template.

[field]#{base_field_name}.type# [type]#[String]#::
The type of the template. This will have the value `SMS`.

ifeval::["{base_field_name}" == "messageTemplate"]
[source,json]
.Example Response JSON for a Single Message Template
----
include::../../../src/json/message-templates/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "messageTemplate"]
[source,json]
.Example Response JSON for all Message Templates
----
include::../../../src/json/message-templates/responses.json[]
----
endif::[]
