==== Response Body

[.api]
[field]#metrics.breachedPasswordMetrics# [type]#[Map<UUID, List<Object>]#::
The breached password metrics. The map key is the Tenant Id.

[field]#metrics.breachedPasswordMetrics``[tenantId]``.actionRequired# [type]#[Integer]#::
The total number of user accounts where action is required.

[field]#metrics.breachedPasswordMetrics``[tenantId]``.matchedCommonPasswordCount# [type]#[Integer]#::
The total number of matched user accounts with a commonly compromised password.

[field]#metrics.breachedPasswordMetrics``[tenantId]``.matchedExactCount# [type]#[Integer]#::
The total number of matched user accounts with a compromised password exact match.

[field]#metrics.breachedPasswordMetrics``[tenantId]``.matchedPasswordCount# [type]#[Integer]#::
The total number of user accounts with matched passwords.

[field]#metrics.breachedPasswordMetrics``[tenantId]``.matchedSubAddressCount# [type]#[Integer]#::
The total number of sub-email user accounts that match a compromised password.

[field]#metrics.breachedPasswordMetrics``[tenantId]``.passwordsCheckedCount# [type]#[Integer]#::
The total number of user account passwords checked.

[field]#status.advancedIdentityProviders# [type]#[String]#::
The status for Advanced Identity Providers.
+
include::_reactor-status-values.adoc[]

[field]#status.advancedMultiFactorAuthentication# [type]#[String]#::
The status for link:/docs/v1/tech/guides/multi-factor-authentication[Advanced Multi-Factor Authentication].
+
include::_reactor-status-values.adoc[]

[field]#status.advancedRegistration# [type]#[String]#::
The status for link:/docs/v1/tech/guides/advanced-registration-forms[Advanced Registration Forms].
+
include::_reactor-status-values.adoc[]

[field]#status.applicationThemes# [type]#[String]#::
The status for Application Themes.
+
include::_reactor-status-values.adoc[]

[field]#status.breachedPasswordDetection# [type]#[String]#::
The status for link:/docs/v1/tech/guides/breached-password-detection[Breached Password Detection].
+
include::_reactor-status-values.adoc[]
* `ACTIVE` - the feature is active
* `DISCONNECTED` - the feature is currently disconnected
* `PENDING` - the feature is pending while waiting to complete key exchange with Reactor
* `UNKNOWN` - the status of the feature is unknown

[field]#status.connectors# [type]#[String]#::
The status for link:/docs/v1/tech/connectors[Connectors].
+
include::_reactor-status-values.adoc[]

[field]#status.entityManagement# [type]#[String]#::
The status for link:/docs/v1/tech/core-concepts/entity-management[Entity Management].
+
include::_reactor-status-values.adoc[]

[field]#status.licensed# [type]#[Boolean]#::
Whether or not the FusionAuth Reactor has been activated with a valid license. This is synonymous with a licensed instance of FusionAuth.

[source,json]
.Example Response JSON
----
include::../../../src/json/reactor/response.json[]
----