==== Response Body

[.api]
[field]#status.advancedIdentityProviders# [type]#[String]#::
The status for Advanced Identity Providers.
+
include::_reactor-status-values.adoc[]

[field]#status.advancedLambdas# [type]#[String]# [since]#Available since 1.35.0#::
The status for Advanced lambda features such Lambda HTTP Connect.
+
include::_reactor-status-values.adoc[]

[field]#status.advancedMultiFactorAuthentication# [type]#[String]#::
The status for link:/docs/v1/tech/guides/multi-factor-authentication[Advanced Multi-Factor Authentication].
+
include::_reactor-status-values.adoc[]

[field]#status.advancedRegistration# [type]#[String]#::
The status for link:/docs/v1/tech/guides/advanced-registration-forms[Advanced Registration Forms].
+
include::_reactor-status-values.adoc[]

[field]#status.applicationMultiFactorAuthentication# [type]#[String]# [since]#Available since 1.37.0#::
The status for Application scoped Multi-Factor authentication configuration.
+
include::_reactor-status-values.adoc[]

[field]#status.applicationThemes# [type]#[String]#::
The status for Application Themes.
+
include::_reactor-status-values.adoc[]

[field]#status.breachedPasswordDetection# [type]#[String]#::
The status for link:/docs/v1/tech/guides/breached-password-detection[Breached Password Detection]. The possible following values:
+
* `ACTIVE` - the feature is active
* `DISCONNECTED` - the feature is currently disconnected
* `PENDING` - the feature is pending while waiting to complete key exchange with Reactor
* `UNKNOWN` - the status of the feature is unknown

[field]#status.connectors# [type]#[String]#::
The status for link:/docs/v1/tech/connectors[Connectors].
+
include::_reactor-status-values.adoc[]

[field]#status.entityManagement# [type]#[String]#::
The status for link:/docs/v1/tech/core-concepts/entity-management[Entity Management].
+
include::_reactor-status-values.adoc[]

[field]#status.expiration# [type]#[String]# [since]#Available since 1.36.0#::
If the license is configured to be air-gapped, this value will be returned to indicate the license expiration. An air-gapped license is one that does not require egress network connectivity to the FusionAuth license server. If the license is not configured to be air-gapped, then this field will not be returned in the response.
+
The expiration string is formatted as an `ISO-8601` string in the form `YYYY-MM-DD`.

[field]#status.licenseAttributes# [type]#[Map<String, String>]# [since]#Available since 1.37.0#::
A set of attributes describing the license, this is primarily used for internal use and may help describe the license. The values returned in this object are subject to change.

[field]#status.licensed# [type]#[Boolean]#::
Whether or not the FusionAuth Reactor has been activated with a valid license. This is synonymous with a licensed instance of FusionAuth.

[field]#status.scimServer# [type]#[String]# [since]#Available since 1.36.0#::
The status for the SCIM Server features.
+
include::_reactor-status-values.adoc[]

[field]#status.threatDetection# [type]#[String]# [since]#Available since 1.30.0#::
The status for the Threat Detection feature set.
+
include::_reactor-status-values.adoc[]

[source,json]
.Example Response JSON
----
include::../../../src/json/reactor/status/response.json[]
----