[.api]
ifeval::["{base_field_name}" != "refreshToken"]
[field]#refreshTokens# [type]#[Array]#::
An array of Refresh Tokens
endif::[]

[field]#{base_field_name}.applicationId# [type]#[String]#::
The Id of the Application for which this token is authorized to be exchanged for a new Access Token.

[field]#{base_field_name}.device# [type]#[String]# [deprecated]#Deprecated#::
A unique device identifier to represent the device for which this Refresh Token was issued.
+
[deprecated]#Removed in version 1.5.0# This parameter will no longer be returned in the response body.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] this Refresh Token was issued.

[field]#{base_field_name}.id# [type]#[Long]#::
The Id of the Refresh Token.

[field]#{base_field_name}.metaData.device.description# [type]#[String]#::
A description of the device. For example, `Hooli Phone 8GB Work Phone`.

[field]#{base_field_name}.metaData.device.lastAccessedAddress# [type]#[String]#::
The IP address of the device when this Refresh Token was last used.

[field]#{base_field_name}.metaData.device.lastAccessedInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] this Refresh Token was last used.

[field]#{base_field_name}.metaData.device.name# [type]#[String]#::
The name of the device, for example `Richard's Hooli Phone`.

[field]#{base_field_name}.metaData.device.type# [type]#[String]#::
The type of device represented by the `device` parameter. The following are possible types:
+
include::docs/v1/tech/apis/_device-type-list.adoc[]

[field]#{base_field_name}.metaData.scopes# [type]#[Array<String>]#::
The scopes associated with this Refresh Token. These are set at authentication when when the Refresh Token is first created.

[field]#{base_field_name}.startInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] of the start of this Refresh Token. This value will be used to calculate token expiration.

[field]#{base_field_name}.token# [type]#[String]#::
The string representation of the encoded Refresh Token. This value should be kept in some sort of secure storage and treated as sensitive information.

[field]#{base_field_name}.userId# [type]#[UUID]#::
The User Id of the user for which this Refresh Token was issued.

ifeval::["{base_field_name}" == "refreshToken"]
[source,json]
.Example Response JSON For a Single Refresh Token
----
include::../../../src/json/jwt/refresh-token-get-response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "refreshToken"]
[source,json]
.Example Response JSON For All Refresh Tokens For a User
----
include::../../../src/json/jwt/refresh-tokens-get-response.json[]
----
endif::[]
