This report retrieves the number of {reportType} for a given application or across all applications. You must specify a date range for the report. {reportDescription}

=== Request

ifeval::["{reportURI}" == "login"]
[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Generates the {reportType} report
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/report/{reportURI}``?start=\{start\}&end=\{end\}&applicationId=\{applicationId\}``#
--

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Generates the {reportType} report for an individual user by username or email address
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/report/{reportURI}``?start=\{start\}&end=\{end\}&applicationId=\{applicationId\}&loginId=\{loginId\}``#
--

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Generates the {reportType} report for an individual user by unique Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/report/{reportURI}``?start=\{start\}&end=\{end\}&applicationId=\{applicationId\}&userId=\{userId\}``#
--
endif::[]
ifeval::["{reportURI}" != "login"]
[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Generates the {reportType} report
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/report/{reportURI}``?start=\{start\}&end=\{end\}&applicationId=\{applicationId\}``#
--
endif::[]

==== Request Parameters
[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
A specific application to query for. If not provided a "Global" (across all applications) {reportType} report will be returned.

[field]#end# [type]#[Long]# [required]#Required#::
The end of the query range. This is an link:/docs/v1/tech/reference/data-types#instants[instant] but it is truncated to {reportUnit} in the report timezone (which is set in the system settings).

[field]#start# [type]#[Long]# [required]#Required#::
The start of the query range. This is an link:/docs/v1/tech/reference/data-types#instants[instant] but it is truncated to {reportUnit} in the report timezone (which is set in the system settings).

ifeval::["{reportURI}" == "login"]
[field]#loginId# [type]#[String]# [optional]#Optional# [since]#Available since 1.4.0#::
When this parameter is provided it will reduce the scope of the report to a single user with the requested email or username specified by this parameter.
+
This parameter is mutually exclusive with `userId`, if both are provided, the `loginId` will take precedence.

[field]#userId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.4.0#::
When this parameter is provided it will reduce the scope of the report to a single user with the requested unique Id.
+
This parameter is mutually exclusive with `loginId`, if both are provided, the `loginId` will take precedence.
endif::[]

=== Response

The response for this API contains the generated {reportType} report.

include::_standard-get-response-codes.adoc[]

==== Response Body

[.api]
[field]#{reportPrefix}# [type]#Array#::
The list of {reportType} counts.

[field]#{reportPrefix}``[x]``.interval# [type]#[Integer]#::
The interval for this count. The interval values for the {reportType} report are the number of {reportUnit} since Epoch UTC shifted to the report timezone.

[field]#{reportPrefix}``[x]``.count# [type]#[Integer]#::
The number of {reportType} for this count.

[field]#total# [type]#[Integer]#::
The total (sum) of each count across the query range.

[source,json]
.Example Response JSON
----
include::../../../src/json/reports/{reportJSON}[]
----
