==== Response Body

[.api]
[field]#anonymousResults# [type]#[Map<String,Object>]# [since]#Available since 1.28.0#::
This is a Mapping between the email address that had errors and the errors that were encountered. This mapping is used for errors that occur when using the [field]#toAddresses# field on the send request.

[field]#anonymousResults[email].parseErrors# [type]#[Map<String,String>]# [since]#Available since 1.28.0#::
Contains any parse errors that occurred while parsing the Email Template parts. The key of the Map is the field that failed (i.e. **from**) and the value is the error message.

[field]#anonymousResults[email].renderErrors# [type]#[Map<String,String>]# [since]#Available since 1.28.0#::
Contains any template errors that occurred while executing the Email Template parts. The key of the Map is the field that failed (i.e. **from**) and the value is the error message.

[field]#results# [type]#[Map<UUID,Object>]#::
This is a Mapping between the User Ids that had errors and the errors that were encountered.

[field]#results[userId].parseErrors# [type]#[Map<String,String>]#::
Contains any parse errors that occurred while parsing the Email Template parts. The key of the Map is the field that failed (i.e. **from**) and the value is the error message.

[field]#results[userId].renderErrors# [type]#[Map<String,String>]#::
Contains any template errors that occurred while executing the Email Template parts. The key of the Map is the field that failed (i.e. **from**) and the value is the error message.

[source,json]
.Example Response JSON
----
include::../../../src/json/email-templates/send-response.json[]
----
