==== Request Body

[.api]
[field]#systemConfiguration.auditLogConfiguration.delete.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Whether or not FusionAuth should delete the Audit Log based upon this configuration. When `true` the [field]#auditLogConfiguration.delete.numberOfDaysToRetain# will be used to identify audit logs that are eligible for deletion. When this value is set to `false` audit logs will be preserved forever.

[field]#systemConfiguration.auditLogConfiguration.delete.numberOfDaysToRetain# [type]#[Integer]# [optional]#Optional# [default]#defaults to `365`#::
The number of days to retain the Audit Log. Required when [field]#auditLogConfiguration.delete.enabled# is set to `true`.
+
Prior to version `1.30.0`, this value was required when [field]#delete.enabled# was equal to `true`.

[field]#systemConfiguration.corsConfiguration.allowCredentials# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
The `Access-Control-Allow-Credentials` response header values as described by https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials[MDN Access-Control-Allow-Credentials].

[field]#systemConfiguration.corsConfiguration.allowedHeaders# [type]#[Array<String>]# [optional]#Optional#::
The `Access-Control-Allow-Headers` response header values as described by https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers[MDN Access-Control-Allow-Headers].

[field]#systemConfiguration.corsConfiguration.allowedMethods# [type]#[Array<String>]# [optional]#Optional#::
The `Access-Control-Allow-Methods` response header values as described by https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods[MDN Access-Control-Allow-Methods].

[field]#systemConfiguration.corsConfiguration.allowedOrigins# [type]#[Array<String>]# [optional]#Optional#::
The `Access-Control-Allow-Origin` response header values as described by https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin[MDN Access-Control-Allow-Origin]. If the wildcard `*` is specified, no additional domains may be specified.

[field]#systemConfiguration.corsConfiguration.debug# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Whether or not FusionAuth will log debug messages to the event log. This is primarily useful for identifying why the FusionAuth CORS filter is rejecting a request and returning an HTTP response status code of `403`.

[field]#systemConfiguration.corsConfiguration.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Whether the FusionAuth CORS filter will process requests made to FusionAuth.

[field]#systemConfiguration.corsConfiguration.exposedHeaders# [type]#[Array<String>]# [optional]#Optional#::
The `Access-Control-Expose-Headers` response header values as described by https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers[MDN Access-Control-Expose-Headers].

[field]#systemConfiguration.corsConfiguration.preflightMaxAgeInSeconds# [type]#[Integer]# [optional]#Optional#::
The `Access-Control-Max-Age` response header values as described by https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age[MDN Access-Control-Max-Age].

[field]#systemConfiguration.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the System that should be persisted.

[field]#systemConfiguration.eventLogConfiguration.numberToRetain# [type]#[Integer]# [optional]#Optional# [default]#defaults to `10,000`#::
The number of events to retain. Once the the number of event logs exceeds this configured value they will be deleted starting with the oldest event logs.

[field]#systemConfiguration.loginRecordConfiguration.delete.enabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Whether or not FusionAuth should delete the login records based upon this configuration. When `true` the [field]#loginRecordConfiguration.delete.numberOfDaysToRetain# will be used to identify login records that are eligible for deletion. When this value is set to `false` login records will be preserved forever.

[field]#systemConfiguration.loginRecordConfiguration.delete.numberOfDaysToRetain# [type]#[Integer]# [optional]#Optional# [default]#defaults to `365`#::
The number of days to retain login records. Required when [field]#loginRecordConfiguration.delete.enabled# is set to `true`.
+
Prior to version `1.30.0`, this value was required when [field]#delete.enabled# was equal to `true`.

[field]#systemConfiguration.reportTimezone# [type]#[String]# [required]#Required#::
The link:/docs/v1/tech/reference/data-types#time-zone[time zone] used to adjust the stored UTC time when generating reports. Since reports are usually rolled up hourly, this timezone will be used for demarcating the hours.
+
For example:
+
[quote]
`America/Denver` or `US/Mountain`

[field]#systemConfiguration.uiConfiguration.headerColor# [type]#[String]# [optional]#Optional#::
A hexadecimal color to override the default menu color in the user interface.
+
[quote]
Example: `000000` would set the menu color to black.

[field]#systemConfiguration.uiConfiguration.logoURL# [type]#[String]# [optional]#Optional#::
A URL of a logo to override the default FusionAuth logo in the user interface.

[field]#systemConfiguration.uiConfiguration.menuFontColor# [type]#[String]# [optional]#Optional#::
A hexadecimal color to override the default menu font color in the user interface.
+
[quote]
Example: `FFFFFF` would set the menu font color to white.

[source,json]
.Example Request JSON
----
include::../../../src/json/system-configuration/request.json[]
----
