[api]
ifeval::[{base_field_name}!=tenant]
[field]#tenants# [type]#[Array]#::
The list of Tenant objects.
endif::[]

<<<<<<< HEAD
[field]#{base_field_name}.connectorPolicies# [type]#[Array]# [since]#Available since 1.18.0#::
A list of Connector policies. Users will be authenticated against Connectors in order. Each Connector can be included in this list at most once and must exist.

[field]#{base_field_name}.connectorPolicies``[x]``.connectorId# [type]#[UUID]# [since]#Available since 1.18.0#::
The identifier of the Connector to which this policy refers.

[field]#{base_field_name}.connectorPolicies``[x]``.domains# [type]#[String]# [since]#Available since 1.18.0#::
An list of email domains to which this connector should apply. 
+
A value of `["*"]` indicates this connector applies to all users.

[field]#{base_field_name}.connectorPolicies``[x]``.migrate# [type]#[Boolean]# # [since]#Available since 1.18.0#::
If true, the user's data will be migrated to FusionAuth at first successful authentication; subsequent authentications will occur against the FusionAuth datastore. If false, the Connector's source will be treated as authoritative.

[field]#{base_field_name}.data# [type]#[Object]#::
An object that can hold any information about the Tenant that should be persisted.

[field]#{base_field_name}.emailConfiguration.enabled# [type]#[Boolean]# [deprecated]#Deprecated#::
When this value is set to true the email configuration provided by this tenant will take precedence over the configuration by the System Configuration.
+
&nbsp;
+
[deprecated]#Removed in version 1.8.0# In version 1.8.0 and beyond, a Tenant's email configuration is enabled upon configuration.

[field]#{base_field_name}.emailConfiguration.defaultFromEmail# [type]#[String]# [since]#Available since 1.16.0#::
The default email address that emails will be sent from when a from address is not provided on an individual email template. This is the address part email address (i.e.  Jared Dunn  <**jared@piedpiper.com**>).

[field]#{base_field_name}.emailConfiguration.defaultFromName# [type]#[String]# [since]#Available since 1.16.0#::
The default From Name used in sending emails when a from name is not provided on an individual email template. This is the display name part of the email address ( i.e. **Jared Dunn**  <jared@piedpiper.com>).

[field]#{base_field_name}.emailConfiguration.forgotPasswordEmailTemplateId# [type]#[UUID]#::
The Id of the Email Template that is used when a user is sent a forgot password email.

[field]#{base_field_name}.emailConfiguration.host# [type]#[String]# [since]#Available since 1.8.0#::
The host name of the SMTP server that FusionAuth will use.

[field]#{base_field_name}.emailConfiguration.password# [type]#[String]# [since]#Available since 1.8.0#::
An optional password FusionAuth will use to authenticate with the SMTP server.

[field]#{base_field_name}.emailConfiguration.passwordlessEmailTemplateId# [type]#[UUID]# [since]#Available since 1.8.0#::
The Id of the Passwordless Email Template.

[field]#{base_field_name}.emailConfiguration.port# [type]#[Integer]# [since]#Available since 1.8.0#::
The port of the SMTP server that FusionAuth will use.

[field]#{base_field_name}.emailConfiguration.properties# [type]#[String]# [since]#Available since 1.8.0#::
Additional Email Configuration in a properties file formatted String.

[field]#{base_field_name}.emailConfiguration.security# [type]#[String]# [since]#Available since 1.8.0#::
The type of security protocol FusionAuth will use when connecting to the SMTP server. The possible values are:
+
* `NONE` - no security will be used. All communications will be sent plaintext.
* `SSL` - SSL will be used to connect to the SMTP server. This protocol is not recommended unless it is the only one your SMTP server supports.
* `TLS` - TLS will be used to connect to the SMTP server. This is the preferred protocol for all SMTP servers.

[field]#{base_field_name}.emailConfiguration.setPasswordEmailTemplateId# [type]#[UUID]#::
The Id of the Email Template that is used when a user had their account created for them and they must set their password manually and they are sent an email to set their password.

[field]#{base_field_name}.emailConfiguration.username# [type]#[String]# [since]#Available since 1.8.0#::
An optional username FusionAuth will to authenticate with the SMTP server.

[field]#{base_field_name}.emailConfiguration.verificationEmailTemplateId# [type]#[UUID]#::
The If of the Email Template that is used to send the verification emails to users. These emails are used to verify that a user's email address is valid. If either the `verifyEmail` or `verifyEmailWhenChanged` fields are `true` this field is required.

[field]#{base_field_name}.emailConfiguration.verifyEmail# [type]#[Boolean]#::
Whether the user's email addresses are verified when the registers with your application.

[field]#{base_field_name}.emailConfiguration.verifyEmailWhenChanged# [type]#[Boolean]#::
Whether the user's email addresses are verified when the user changes them.

[field]#{base_field_name}.eventConfiguration.events# [type]#[Object]# [since]#Available since 1.8.0#::
A mapping of the configuration for each event type that FusionAuth sends. The event types that are the keys into this Object are:
+
include::_event-types.adoc[]

[field]#{base_field_name}.eventConfiguration.events``[type]``.enabled# [type]#[Boolean]# [since]#Available since 1.8.0#::
Whether or not FusionAuth should send these types of events to any configured Webhooks.

[field]#{base_field_name}.eventConfiguration.events``[type]``.transactionType# [type]#[String]# [since]#Available since 1.8.0#::
The transaction type that FusionAuth uses when sending these types of events to any configured Webhooks. The transaction types are:
+
include::_transaction-types.adoc[]

[field]#{base_field_name}.externalIdentifierConfiguration.authorizationGrantIdTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The time in seconds until a OAuth authorization code in no longer valid to be exchanged for an access token. This is essentially the time allowed between the start of an Authorization request during the Authorization code grant and when you request an access token using this authorization code on the Token endpoint.
+
Value must be greater than 0 and less than or equal to 600.

[field]#{base_field_name}.externalIdentifierConfiguration.changePasswordIdGenerator.length# [type]#[Integer]# [since]#Available since 1.8.0#::
+
:generator_type: changePasswordIdGenerator
:generator_display_name: change password Id
include::_tenant-generator-length-config-rules.adoc[]
:generator_type!:
:generator_display_name!:
+

[field]#{base_field_name}.externalIdentifierConfiguration.changePasswordIdGenerator.type# [type]#[String]# [since]#Available since 1.8.0#::
+
:generator_display_name: change password Id
include::_tenant-generator-type-config-rules.adoc[]
:generator_display_name!:

[field]#{base_field_name}.externalIdentifierConfiguration.changePasswordIdTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The time in seconds until a change password Id is no longer valid and cannot be used by the Change Password API. Value must be greater than 0.

[field]#{base_field_name}.externalIdentifierConfiguration.deviceCodeTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.11.0#::
The time in seconds until a device code Id is no longer valid and cannot be used by the Token API. Value must be greater than 0.

[field]#{base_field_name}.externalIdentifierConfiguration.deviceUserCodeIdGenerator.length# [type]#[Integer]# [since]#Available since 1.11.0#::
+
:generator_type: deviceCodeTimeToLiveInSeconds
:generator_display_name: device code Id
include::_tenant-generator-length-config-rules.adoc[]
:generator_type!:
:generator_display_name!:
+

[field]#{base_field_name}.externalIdentifierConfiguration.deviceUserCodeIdGenerator.type# [type]#[String]# [since]#Available since 1.11.0#::
+
:generator_display_name: device code Id
include::_tenant-generator-type-config-rules.adoc[]
:generator_display_name!:

[field]#{base_field_name}.externalIdentifierConfiguration.emailVerificationIdGenerator.length# [type]#[Integer]# [since]#Available since 1.8.0#::
+
:generator_type: emailVerificationIdGenerator
:generator_display_name: the email verification Id
include::_tenant-generator-length-config-rules.adoc[]
:generator_type!:
:generator_display_name!:
+

[field]#{base_field_name}.externalIdentifierConfiguration.emailVerificationIdGenerator.type# [type]#[String]# [since]#Available since 1.8.0#::
+
:generator_display_name: email verification Id
include::_tenant-generator-type-config-rules.adoc[]
:generator_display_name!:

[field]#{base_field_name}.externalIdentifierConfiguration.emailVerificationIdTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The time in seconds until a email verification Id is no longer valid and cannot be used by the Verify Email API. Value must be greater than 0.

[field]#{base_field_name}.externalIdentifierConfiguration.externalAuthenticationIdTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.12.0#::
The time in seconds until an external authentication Id is no longer valid and cannot be used by the Token API. Value must be greater than 0.

[field]#{base_field_name}.externalIdentifierConfiguration.oneTimePasswordTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The time in seconds until a One Time Password is no longer valid and cannot be used by the Login API. Value must be greater than 0.

[field]#{base_field_name}.externalIdentifierConfiguration.passwordlessLoginGenerator.length# [type]#[Integer]# [since]#Available since 1.8.0#::
+
:generator_type: passwordlessLoginGenerator
:generator_display_name: passwordless login
include::_tenant-generator-length-config-rules.adoc[]
:generator_type!:
:generator_display_name!:
+

[field]#{base_field_name}.externalIdentifierConfiguration.passwordlessLoginGenerator.type# [type]#[String]# [since]#Available since 1.8.0#::
+
:generator_display_name: passwordless login
include::_tenant-generator-type-config-rules.adoc[]
:generator_display_name!:

[field]#{base_field_name}.externalIdentifierConfiguration.passwordlessLoginTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The time in seconds until a passwordless code is no longer valid and cannot be used by the Passwordless API. Value must be greater than 0.

[field]#{base_field_name}.externalIdentifierConfiguration.registrationVerificationIdGenerator.length# [type]#[Integer]# [since]#Available since 1.8.0#::
+
:generator_type: registrationVerificationIdGenerator
:generator_display_name: registration verification Id
include::_tenant-generator-length-config-rules.adoc[]
:generator_type!:
:generator_display_name!:
+

[field]#{base_field_name}.externalIdentifierConfiguration.registrationVerificationIdGenerator.type# [type]#[String]# [since]#Available since 1.8.0#::
+
:generator_display_name: registration verification Id
include::_tenant-generator-type-config-rules.adoc[]
:generator_display_name!:

[field]#{base_field_name}.externalIdentifierConfiguration.registrationVerificationIdTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The time in seconds until a registration verification Id is no longer valid and cannot be used by the Verify Registration API. Value must be greater than 0.

[field]#{base_field_name}.externalIdentifierConfiguration.setupPasswordIdGenerator.length# [type]#[Integer]# [since]#Available since 1.8.0#::
+
:generator_type: setupPasswordIdGenerator
:generator_display_name: setup password Id
include::_tenant-generator-length-config-rules.adoc[]
:generator_type!:
:generator_display_name!:
+

[field]#{base_field_name}.externalIdentifierConfiguration.setupPasswordIdGenerator.type# [type]#[String]# [since]#Available since 1.8.0#::
+
:generator_display_name: setup password Id
include::_tenant-generator-type-config-rules.adoc[]
:generator_display_name!:

[field]#{base_field_name}.externalIdentifierConfiguration.setupPasswordIdTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The time in seconds until a setup password Id is no longer valid and cannot be used by the Change Password API. Value must be greater than 0.

[field]#{base_field_name}.externalIdentifierConfiguration.twoFactorIdTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The time in seconds until a two factor Id is no longer valid and cannot be used by the Two Factor Login API. Value must be greater than 0.

[field]#{base_field_name}.externalIdentifierConfiguration.twoFactorTrustIdTimeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The time in seconds until an issued Two Factor trust Id is no longer valid and the User will be required to complete Two Factor authentication
during the next authentication attempt. Value must be greater than 0.

[field]#{base_field_name}.failedAuthenticationConfiguration.actionDuration# [type]#[Long]# [since]#Available since 1.8.0#::
The duration of the User Action. This value along with the `actionDurationUnit` will be used to set the duration of the User Action. Value must be greater than 0.

[field]#{base_field_name}.failedAuthenticationConfiguration.actionDurationUnit# [type]#[String]# [since]#Available since 1.8.0#::

include::_expiry_unit.adoc[]

[field]#{base_field_name}.failedAuthenticationConfiguration.resetCountInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The length of time in seconds before the failed authentication count will be reset. Value must be greater than 0.
+
For example, if `tooManyAttempts` is set to `5` and you fail to authenticate `4` times in a row, waiting for the duration specified here will cause your fifth attempt to start back at `1`.

[field]#{base_field_name}.failedAuthenticationConfiguration.tooManyAttempts# [type]#[Integer]# [since]#Available since 1.8.0#::
The number of failed attempts considered to be too many. Once this threshold is reached the specified User Action will be applied to the user for the duration specified. Value must be greater than 0.

[field]#{base_field_name}.failedAuthenticationConfiguration.userActionId# [type]#[UUID]# [since]#Available since 1.8.0#::
The Id of the User Action that is applied when the threshold is reached for too many failed authentication attempts.

[field]#{base_field_name}.familyConfiguration.allowChildRegistrations# [type]#[Boolean]# [since]#Available since 1.8.0#::
Whether to allow child registrations.

[field]#{base_field_name}.familyConfiguration.confirmChildEmailTemplateId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique Id of the email template to use when confirming a child.

[field]#{base_field_name}.familyConfiguration.deleteOrphanedAccounts# [type]#[Boolean]# [since]#Available since 1.8.0#::
Indicates that child users without parental verification will be permanently deleted after [field]#{base_field_name}.familyConfiguration.deleteOrphanedAccountsDays# days.

[field]#{base_field_name}.familyConfiguration.deleteOrphanedAccountsDays# [type]#[Integer]# [since]#Available since 1.8.0#::
The number of days from creation child users will be retained before being deleted for not completing parental verification. Value must be greater than 0.

[field]#{base_field_name}.familyConfiguration.enabled# [type]#[Boolean]# [since]#Available since 1.8.0#::
Whether family configuration is enabled.

[field]#{base_field_name}.familyConfiguration.familyRequestEmailTemplateId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique Id of the email template to use when a family request is made.

[field]#{base_field_name}.familyConfiguration.maximumChildAge# [type]#[Integer]# [since]#Available since 1.8.0#::
The maximum age of a child. Value must be greater than 0.

[field]#{base_field_name}.familyConfiguration.minimumOwnerAge# [type]#[Integer]# [since]#Available since 1.8.0#::
The minimum age to be an owner. Value must be greater than 0.

[field]#{base_field_name}.familyConfiguration.parentEmailRequired# [type]#[Boolean]# [since]#Available since 1.8.0#::
Whether a parent email is required.

[field]#{base_field_name}.familyConfiguration.parentRegistrationEmailTemplateId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique Id of the email template to use for parent registration.

[field]#{base_field_name}.httpSessionMaxInactiveInterval# [type]#[Integer]# [since]#Available since 1.8.0#::
Time in seconds until an inactive session will be invalidated. Used when creating a new session in the FusionAuth OAuth frontend.

[field]#{base_field_name}.id# [type]#[UUID]#::
The unique identifier for this Tenant.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Tenant was added to the FusionAuth database.

[field]#{base_field_name}.issuer# [type]#[String]# [since]#Available since 1.8.0#::
The named issuer used to sign tokens, this is generally your public fully qualified domain.

[field]#{base_field_name}.jwtConfiguration.accessTokenKeyId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique id of the signing key used to sign the access token.

[field]#{base_field_name}.jwtConfiguration.idTokenKeyId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique id of the signing key used to sign the Id token.

[field]#{base_field_name}.jwtConfiguration.refreshTokenExpirationPolicy# [type]#[String]# [since]#Available since 1.17.0#::
The refresh token expiration policy. The following are valid values:

* `Fixed` - the expiration is calculated from the time the token is issued.
* `SlidingWindow` - the expiration is calculated from the last time the token was used.

[field]#{base_field_name}.jwtConfiguration.refreshTokenRevocationPolicy.onLoginPrevented# [type]#[Boolean]# [since]#Available since 1.17.0#::
When enabled, the refresh token will be revoked when a user action, such as locking an account based on a number of failed login attempts, prevents user login.

[field]#{base_field_name}.jwtConfiguration.refreshTokenRevocationPolicy.onPasswordChanged# [type]#[Boolean]# [since]#Available since 1.17.0#::
When enabled, the refresh token will be revoked when a user changes their password. 

[field]#{base_field_name}.jwtConfiguration.refreshTokenTimeToLiveInMinutes# [type]#[Integer]# [since]#Available since 1.8.0#::
The length of time in minutes a Refresh Token is valid from the time it was issued. Value must be greater than 0.

[field]#{base_field_name}.jwtConfiguration.refreshTokenUsagePolicy# [type]#[String]# [since]#Available since 1.17.0#::
The refresh token usage policy. The following are valid values:

* `Reusable` - the token does not change after it was issued.
* `OneTimeUse` - the token value will be changed each time the token is used to refresh a JWT. The client must store the new value after each usage.

[field]#{base_field_name}.jwtConfiguration.timeToLiveInSeconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The length of time in seconds this JWT is valid from the time it was issued. Value must be greater than 0.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Tenant was last updated in the FusionAuth database.

[field]#{base_field_name}.logoutURL# [type]#[String]# [since]#Available since 1.8.0#::
The logout redirect URL when sending the user's browser to the `/oauth2/logout` URI of the FusionAuth Front End. This value is only used when a logout URL is not defined in your Application.

[field]#{base_field_name}.maximumPasswordAge.days# [type]#[Integer]# [since]#Available since 1.8.0#::
The password maximum age in days. The number of days after which FusionAuth will require a user to change their password. Required when `systemConfiguration.maximumPasswordAge.enabled` is set to `true`.

[field]#{base_field_name}.maximumPasswordAge.enabled# [type]#[Boolean]# [since]#Available since 1.8.0#::
Indicates that the maximum password age is enabled and being enforced.

[field]#{base_field_name}.minimumPasswordAge.seconds# [type]#[Integer]# [since]#Available since 1.8.0#::
The password minimum age in seconds. When enabled FusionAuth will not allow a password to be changed until it reaches this minimum age. Required when [field]#systemConfiguration.minimumPasswordAge.enabled# is set to `true`.

[field]#{base_field_name}.minimumPasswordAge.enabled# [type]#[Boolean]# [since]#Available since 1.8.0#::
Indicates that the minimum password age is enabled and being enforced.

[field]#{base_field_name}.name# [type]#[String]#::
The unique name of the Tenant.

[field]#{base_field_name}.passwordEncryptionConfiguration.encryptionScheme# [type]#[String]# [since]#Available since 1.8.0#::
The default method for encrypting the User's password. The following encryptors are provided with FusionAuth:
+
* `link:../reference/password-encryptors#salted-md5[salted-md5]`
* `link:../reference/password-encryptors#salted-sha-256[salted-sha256]`
* `link:../reference/password-encryptors#salted-hmac-sha-256[salted-hmac-sha256]`
* `link:../reference/password-encryptors#salted-pbkdf2-hmac-sha-256[salted-pbkdf2-hmac-sha256]`
* `link:../reference/password-encryptors#salted-bcrypt[bcrypt]`

[field]#{base_field_name}.passwordEncryptionConfiguration.encryptionSchemeFactor# [type]#[Integer]# [since]#Available since 1.8.0#::
The factor used by the password encryption scheme. If not provided, the `PasswordEncryptor` provides a default value. Generally this will be used as an iteration count to generate the hash. The actual use of this value is up to the `PasswordEncryptor` implementation.

[field]#{base_field_name}.passwordEncryptionConfiguration.modifyEncryptionSchemeOnLogin# [type]#[Boolean]# [since]#Available since 1.8.0#::
When enabled a user's hash configuration will be modified to match these configured settings. This can be useful to increase a password hash strength over time or upgrade imported users to a more secure encryption scheme after an initial import.

[field]#{base_field_name}.passwordValidationRules.breachDetection.enabled# [type]#[Boolean]# [since]#Available since 1.15.0#::
Whether to enable Reactor breach detection. Requires an activated license.

[field]#{base_field_name}.passwordValidationRules.breachDetection.matchMode# [type]#[String]# [since]#Available since 1.15.0#::
The level of severity where Reactor will consider a breach. The following are valid values:
+
* `High` Only requires a password match, this is the most secure and is recommended
* `Medium` Exact match on username, email address or email sub-address
* `Low` Exact match on an email or username, or the password is a common breached value

[field]#{base_field_name}.passwordValidationRules.breachDetection.notifyUserEmailTemplateId# [type]#[UUID]# [since]#Available since 1.15.0#::
The Id of the email template to use when notifying user of breached password.

[field]#{base_field_name}.passwordValidationRules.breachDetection.onLogin# [type]#[String]# [since]#Available since 1.15.0#::
The behavior when detecting breaches at time of user login. The following are valid values:
+
* `Off` Do not perform breach detection at login
* `RecordOnly` Only record the result, take no action
* `NotifyUser` Notify the end user via email
* `RequireChange` Require immediate password change

[field]#{base_field_name}.passwordValidationRules.maxLength# [type]#[Integer]# [since]#Available since 1.8.0#::
The maximum length of a password when a new user is created or a user requests a password change.

[field]#{base_field_name}.passwordValidationRules.minLength# [type]#[Integer]# [since]#Available since 1.8.0#::
The minimum length of a password when a new user is created or a user requests a password change.

[field]#{base_field_name}.passwordValidationRules.rememberPreviousPasswords.count# [type]#[Integer]# [since]#Available since 1.8.0#::
The number of previous passwords to remember. Value must be greater than 0.

[field]#{base_field_name}.passwordValidationRules.rememberPreviousPasswords.enabled# [type]#[Boolean]# [since]#Available since 1.8.0#::
Whether to prevent a user from using any of their previous passwords.

[field]#{base_field_name}.passwordValidationRules.requiredMixedCase# [type]#[Boolean]# [since]#Available since 1.8.0#::
Whether to force the user to use at least one uppercase and one lowercase character.

[field]#{base_field_name}.passwordValidationRules.requireNonAlpha# [type]#[Boolean]# [since]#Available since 1.8.0#::
Whether to force the user to use at least one non-alphanumeric character.

[field]#{base_field_name}.passwordValidationRules.requireNumber# [type]#[Boolean]# [since]#Available since 1.8.0#::
Whether to force the user to use at least one number.

[field]#{base_field_name}.passwordValidationRules.validateOnLogin# [type]#[Boolean]# [since]#Available since 1.15.0#::
When enabled the user's password will be validated during login. If the password does not meet the currently configured validation rules the user will be required to change their password.

[field]#{base_field_name}.themeId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique Id of the theme to be used to style the login page and other end user templates.

[field]#{base_field_name}.userDeletePolicy.unverified.enabled# [type]#[Boolean]# [since]#Available since 1.13.0#::
Indicates that users without a verified email address will be permanently deleted after [field]#{base_field_name}.userDeletePolicy.unverified.numberOfDaysToRetain# days.

[field]#{base_field_name}.userDeletePolicy.unverified.numberOfDaysToRetain# [type]#[Integer]# [since]#Available since 1.13.0#::
The number of days from creation users will be retained before being deleted for not completing email verification. Value must be greater than 0.

[source,json]
.Example Response JSON
----
include::../../../src/json/tenants/response.json[]
----
