==== Request Body

[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
An application Id. If this is not provided and there are multiple tenants, the [field]#X-FusionAuth-TenantId# header is required.

[field]#code# [type]#[String]# [optional]#Optional#::
A valid Multi-Factor verification code. When this value is omitted, one will be generated. 
+
Providing a code allows you to control the delivery mechanism if needed or to specify a code string that meets your needs.

[field]#loginId# [type]#[String]# [required]#Required#::
The email or the username of the User.

[field]#state# [type]#[Object]# [optional]#Optional#::
Additional data to be passed through this Multi-Factor request. After successful login, the [field]#state# field in the response will contain this data.

[field]#trustChallenge# [type]#[String]# [optional]#Optional# [since]#Available since 1.30.0#::
This value may be optionally used to bind a Two-Factor login request to a particular trusted action. For example, if you are using this API to complete a Two-Factor Login in order to obtain a `trustToken` to make an API request that requires a `trustToken` you may optionally provide this value to bind this request to the intended usage of the `trustToken` returned in the API response.`

[field]#userId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.30.0#::
The unique User Id of the User, this value will be preferred over the [field]#loginId# if both values are provided.

[source,json]
.Example Request JSON
----
include::../../../src/json/two-factor/start/request.json[]
----
