==== Request Body

[.api]
[field]#code# [type]#[String]# [required]#Required#::
A valid Two Factor verification code. This value should be provided by the User to verify they are able to produce codes using
an application or receive them using their mobile phone.

[field]#delivery# [type]#[String]# [required]#Required#::
The User's preferred delivery for verification codes during a two factor login request.
+
The possible values are:
+
* `None`
* `TextMessage`
+
When using `TextMessage` the User will also need a valid `mobilePhone`. The User's mobile phone is not validated during this request. Because the `code` is provided on this request it is assumed the User has been able to receive a `code` on their mobile phone when setting the delivery to `TextMessage`.

[field]#secret# [type]#[String]# [optional]#Optional#::
A base64 encoded secret.
+
You may optionally use the [field]#secret# value returned by the link:/docs/v1/tech/apis/two-factor#generate-a-secret[Two Factor Secret] API instead of generating this value yourself. This value is a secure random byte array that is Base-64 encoded.
+
If you omit this field, then [field]#secretBase32Encoded# is required.

[field]#secretBase32Encoded# [type]#[String]# [optional]#Optional#::
A base32 encoded secret.
+
You may optionally use the [field]#secretBase32Encoded# value returned by the link:/docs/v1/tech/apis/two-factor#generate-a-secret[Two Factor Secret] API instead of generating this value yourself. This value is a secure random byte array that is Base-32 encoded.
+
If you omit this field, then [field]#secret# is required.


[source,json]
.Example Request JSON
----
include::../../../src/json/two-factor/request.json[]
----
