==== Response Body

[.api]
[field]#code# [type]#[String]#::
A valid Two Factor verification code. 

[field]#methods# [type]#[Array]#::
A list of configured authentication factors. This field will be omitted if none have been configured.

[field]#methods``[x]``.id# [type]#[String]#::
The identifier for this factor.

[field]#methods``[x]``.lastUsed# [type]#[Boolean]#::
`true` if this method was used most recently.

[field]#methods``[x]``.method# [type]#[String]#::
The type of this factor. There will also be an object with the same value containing additional information about this method.  The possible values are:
+
* `authenticator`
* `email`
* `sms`

[field]#methods``[x]``.authenticator# [type]#[Object]#::
An object with additional configuration for TOTP authentication factors. Only present if [field]#methods``[x]``.method# is `authenticator`. 

[field]#methods``[x]``.authenticator.algorithm# [type]#[String]#::
The algorithm used by the TOTP authenticator. The possible values are:
+
* `HmacSHA1`
* `HmacSHA256`
* `HmacSHA512`

[field]#methods``[x]``.authenticator.codeLength# [type]#[Integer]#::
The length of code generated by the TOTP.

[field]#methods``[x]``.authenticator.timeStep# [type]#[Integer]#::
The time-step size in seconds. 

[field]#methods``[x]``.email# [type]#[String]#::
The value of the email address for this factor. Only present if [field]#methods``[x]``.method# is `email`. 

[field]#methods``[x]``.mobilePhone# [type]#[String]#::
The value of the mobile phone for this factor. Only present if [field]#methods``[x]``.method# is `sms`. 

[field]#twoFactorId# [type]#[String]#::
The twoFactorId to be provided to the Login endpoint or the Send endpoint. TBD

[source,json]
.Example Response JSON With Methods Configured
----
include::../../../src/json/two-factor/start/response-with-methods.json[]
----

[source,json]
.Example Request JSON With No Methods Configured
----
include::../../../src/json/two-factor/start/response-with-no-methods.json[]
----

