==== Request Body

[.api]
[field]#code# [type]#[String]# [required]#Required#::
A valid Two Factor verification code. This value should be provided by the User to verify they are able to produce codes using
an application or receive them using their mobile phone.

[field]#method# [type]#[String]# [required]#Required#::
The User's delivery method for verification codes during a two factor login request. You can enable multiple methods with multiple requests.
+
The possible values are:
+
* `authenticator`
* `email`
* `sms`

[field]#email# [type]#[String]# [optional]#Optional#::
The email address used for this factor of authentication.
+
If [field]#method# is `email`, this field is required.

[field]#mobilePhone# [type]#[String]# [optional]#Optional#::
The mobile phone number used for this factor of authentication.
+
If [field]#method# is `sms`, this field is required.

[field]#secret# [type]#[String]# [optional]#Optional#::
A base64 encoded secret. 
+
You may optionally use the [field]#secret# value returned by the link:/docs/v1/tech/apis/two-factor#generate-a-secret[Two Factor Secret] API instead of generating this value yourself. This value is a secure random byte array that is Base-64 encoded.
+
If [field]#method# is `authenticator` and you omit this field, then [field]#secretBase32Encoded# is required.

[field]#secretBase32Encoded# [type]#[String]# [optional]#Optional#::
A base32 encoded secret.
+
You may optionally use the [field]#secretBase32Encoded# value returned by the link:/docs/v1/tech/apis/two-factor#generate-a-secret[Two Factor Secret] API instead of generating this value yourself. This value is a secure random byte array that is Base-32 encoded.
+
If [field]#method# is `authenticator` and you omit this field, then [field]#secret# is required.


[source,json]
.Example Request JSON Enabling TOTP Factor
----
include::../../../src/json/two-factor/enable-authenticator-request.json[]
----

[source,json]
.Example Request JSON Enabling Email
----
include::../../../src/json/two-factor/enable-email-request.json[]
----

