==== Request Body

[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
An application Id. If this is not provided and there are multiple tenants, the [field]#X-FusionAuth-TenantId# header is required.

[field]#code# [type]#[String]# [optional]#Optional#::
A valid Multi-Factor verification code.
When this value is omitted, one will be generated. 
+
Providing a code allows you to choose an alternative delivery mechanism if needed, such as a chat message.
It also allows you to to specify a code string that meets your needs.
+
Do not provide the code if the user is expected to use an authenticator/TOTP MFA method.

[field]#loginId# [type]#[String]# [optional]#Optional#::
The email or the username of the User.
+
This field is marked optional, but you must provide either the [field]#loginId# or the [field]#userId# to complete this API. If both fields are provided in the request body, the [field]#userId# will be utilized.
+
Prior to version `1.33.0`, this field was always required because the [field]#userId# was not available as an option.

[field]#state# [type]#[Object]# [optional]#Optional#::
Additional data to be passed through this Multi-Factor request. After successful login, the [field]#state# field in the response will contain this data.

[field]#trustChallenge# [type]#[String]# [optional]#Optional# [since]#Available since 1.33.0#::
This value may be used to bind a Two-Factor login request to a particular trusted action.
+
For example, if you are using this API to complete a Two-Factor Login in order to obtain a `trustToken` you may optionally provide this value to bind this request to the intended usage of the `trustToken` returned in the API response.

[field]#userId# [type]#[UUID]# [optional]#Optionally Required# [since]#Available since 1.33.0#::
The unique User Id of the User.
+
This field is marked optional, but you must provide either the [field]#loginId# or the [field]#userId# to complete this API. If both fields are provided in the request body, the [field]#userId# will be utilized.

[source,json]
.Example Request JSON
----
include::../../../src/json/two-factor/start/request.json[]
----
