==== Request Parameters

[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional# [since]#Coming in 1.45.0#::
An application Id. This parameter is optional, and when provided it will cause application specific configuration to be used when available.
+
For example, to use an application specific email template to notify the user when multi-factor has been enabled, this parameter will be required. When this parameter is omitted, the tenant configuration will be used.
+
To learn more about overriding email templates, see the link:/docs/v1/tech/guides/configuring-application-specific-email-templates[Application Specific Email Templates] guide.

[field]#code# [type]#[String]# [required]#Required#::
A valid multi-factor verification code. The User will obtain this code using an existing multi-factor method which may include an authenticator (TOTP) app, sms or email. This procedure is the same as if the user was completing a multi-factor challenge during login.
+
This may also be a recovery code. If one is provided, all methods are removed. If, after that, a multi-factor method is added, a new set of recovery codes will be generated.

[field]#methodId# [type]#[String]# [required]#Required#::
The Id of the multi-factor method to be disabled.
+
If a recovery code is provided, this can be any valid method Id.

