==== Request Body

[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
The Id of the application. If valid, the email template configured in the Application settings will be used, if present. If not present, the email template configured in the Tenant settings will be used. In either case, the corresponding Application object will be available to the template.
To learn more about overriding email templates, read our link:/docs/v1/tech/guides/configuring-application-specific-email-templates[Configure Application Email Templates] guide.

[field]#code# [type]#[String]# [required]#Required#::
A valid Multi-Factor verification code. This value should be provided by the User to verify they are able to produce codes.
+
This may also be a recovery code. If one is provided, all methods are removed. If, after that, a Multi-Factor method is added, a new set of recovery codes will be generated.

[field]#methodId# [type]#[String]# [required]#Required#::
The Id of the Multi-Factor method to be disabled.
+
If a recovery code is provided, this can be any valid method Id.