This request requires that you specify both the User object and the User Registration object in the request body. The fields for each are listed below.

==== Request Body

[.api]
[field]#generateAuthenticationToken# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if FusionAuth should generate an Authentication Token for this registration.

[field]#registration.applicationId# [type]#[UUID]# [required]#Required#::
The Id of the Application that this registration is for.

[field]#registration.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about the User for this registration that should be persisted.

[field]#registration.preferredLanguages# [type]#[Array<String>]# [optional]#Optional#::
An array of locale strings that give, in order, the User's preferred languages for this registration. These are important for email templates and other localizable text. See link:/docs/v1/tech/reference/data-types#locales[Locales].

[field]#registration.id# [type]#[UUID]# [optional]#Optional#::
The Id of this registration. If this is not specified, FusionAuth will create a random UUID for you.

[field]#registration.roles# [type]#[Array<String>]# [optional]#Optional#::
The list of roles that the User has for this Application.

[field]#registration.timezone# [type]#[String]# [optional]#Optional#::
The User's preferred timezone for this Application registration. The format is not enforced, however it is recommended to use a timezone in the TZ format such as
+
[quote]
`America/Denver` or `US/Mountain`

[field]#registration.username# [type]#[String]# [optional]#Optional#::
The username of the User for this Application only.

[field]#sendSetPasswordEmail# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Whether or not the User is sent an email asking them to setup their password. This is useful if someone else is creating an account for a User with an Application.
+
The Email Template that is used is configured in the System Configuration setting for **Set Password Email Template**.
+
If you have also enabled email verification and do not select to skip verification using the `skipVerification` parameter, only the setup password email will be sent to the user. Setting up the password using the email sent during this user create operation will implicitly verify the User's email if it is not already verified.
+
If the SMTP email configuration is not complete, or disabled, this value is ignored.

[field]#skipRegistrationVerification# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Indicates to FusionAuth that it should skip registration verification even if it is enabled for the Application.

[field]#skipVerification# [type]#[String]# [optional]#Optional# [default]#defaults to `false`#::
Whether or not email verification should be skipped or not. In some cases, you might want to verify User's emails and in other cases you won't. This flag controls that behavior.

[field]#user.birthDate# [type]#[String]# [optional]#Optional#::
An `ISO-8601` formatted date of the User's birthdate such as `YYYY-MM-DD`.

[field]#user.data# [type]#[Object]# [optional]#Optional#::
An object that can hold any information about a User that should be persisted.

[field]#user.email# [type]#[String]# [optional]#Optional#::
The User's email address. An email address is a unique in FusionAuth and stored in lower case.

[field]#user.encryptionScheme# [type]#[String]# [optional]#Optional# [default]#defaults to `salted-pbkdf2-hmac-sha256`#::
The method for encrypting the User's password. The following encryptors are provided with FusionAuth:
+
* `link:../reference/password-encryptors#salted-md5[salted-md5]`
* `link:../reference/password-encryptors#salted-sha-256[salted-sha256]`
* `link:../reference/password-encryptors#salted-hmac-sha-256[salted-hmac-sha256]`
* `link:../reference/password-encryptors#salted-pbkdf2-hmac-sha-256[salted-pbkdf2-hmac-sha256]`
* `link:../reference/password-encryptors#salted-bcrypt[bcrypt]`
+
You can also create your own password encryptor. See the link:../plugins/password-encryptors[Password Encryptors] section for more information.

[field]#user.expiry# [type]#[Long]# [optional]#Optional#::
The expiration link:/docs/v1/tech/reference/data-types#instants[instant] of the User's account. An expired user is not permitted to login.

[field]#user.factor# [type]#[String]# [optional]#Optional#::
The factor used by the password encryption scheme. If not provided, the `PasswordEncryptor` provides a default value. Generally this will be used as an iteration count to generate the hash. The actual use of this value is up to the `PasswordEncryptor` implementation.

[field]#user.firstName# [type]#[String]# [optional]#Optional#::
The first name of the User.

[field]#user.fullName# [type]#[String]# [optional]#Optional#::
The User's full name as a separate field that is not calculated from [field]#firstName# and [field]#lastName#.

[field]#user.imageUrl# [type]#[String]# [optional]#Optional#::
The URL that points to an image file that is the User's profile image.

[field]#user.lastName# [type]#[String]# [optional]#Optional#::
The User's last name.

[field]#user.middleName# [type]#[String]# [optional]#Optional#::
The User's middle name.

[field]#user.mobilePhone# [type]#[String]# [optional]#Optional#::
The User's mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.

[field]#user.password# [type]#[String]# [optional]#Optional#::
The User's plain texts password. This password will be hashed and the provided value will never be stored and cannot be retrieved.
+
This field is optional only if `sendSetPasswordEmail` is set to `true`. By default `sendSetPasswordEmail` is `false`, and then this field will be required.

[field]#user.passwordChangeRequired# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Indicates that the User's password needs to be changed during their next login attempt.

[field]#user.preferredLanguages# [type]#[Array<String>]# [optional]#Optional#::
An array of locale strings that give, in order, the User's preferred languages. These are important for email templates and other localizable text. See link:/docs/v1/tech/reference/data-types#locales[Locales].

[field]#user.timezone# [type]#[String]# [optional]#Optional#::
The User's preferred timezone. The string must be in an https://www.iana.org/time-zones[IANA] time zone format. For example:
+
[quote]
`America/Denver` or `US/Mountain`

[field]#users.twoFactorDelivery# [type]#[String]# [optional]#Optional# [default]#defaults to `None`#::
The User's preferred delivery for verification codes during a two factor login request.
+
The possible values are:
+
* `None`
* `TextMessage`
+
When using `TextMessage` the User will also need a valid `mobilePhone`.

[field]#user.twoFactorEnabled# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Determines if the User has two factor authentication enabled for their account or not.
+
See the link:../apis/two-factor#enable-two-factor[Enable Two Factor] and link:../apis/two-factor#disable-two-factor[Disable Two Factor] APIs as an alternative to performing this action using the User API.

[field]#user.twoFactorSecret# [type]#[String]# [optional]#Optional#::
The Base64 encoded secret used to generate Two Factor verification codes.
+
You may optionally use value provided in the `secret` field returned by the link:../apis/two-factor#generate-a-secret[Two Factor Secret] API instead of generating this value yourself.
+
Unless you are using `TextMessage` as your delivery type, ensure you are able to share the secret with the User before enabling Two Factor authentication. Beginning in version 1.17.0, if you do create a User with `TextMessage` set as the `twoFactorDelivery` type and you omit this value, the secret will be generated for you. The secret can be generated because it is not necessary to share the secret with the User for this delivery method.
+
When using `None` as the `twoFactorDelivery` this value will be required.

[field]#user.username# [type]#[String]# [optional]#Optional#::
The username of the User.

[source,json]
.Example Request JSON
----
include::../../../src/json/user-registrations/combined-request.json[]
----
