==== Request Body

[.api]
[field]#search.ids# [type]#[Array<UUID>]# [optional]#Optional#::
A list of User Ids to retrieve. When using this parameter, the results are not paginated or sorted using the `sortFields`. The [field]#ids#, [field]#query#, and [field]#queryString#  parameters are mutually exclusive, they are listed here in order of precedence.
+
Using this parameter will not hit the Elasticsearch index, instead it will cause users to be retrieved by Id only.

[field]#search.numberOfResults# [type]#[Integer]# [optional]#Optional# [default]#defaults to `25`#::
The number of search results to return. Used for pagination.

[field]#search.query# [type]#[String]# [optional]#Optional# [since]#Available Since 1.13.0#::
The raw JSON Elasticsearch query that is used to search for Users.  The [field]#ids#, [field]#query#, and [field]#queryString#  parameters are mutually exclusive, they are listed here in order of precedence.
+
It is necessary to use the [field]#search.query# parameter when querying against `registrations` in order to achieve expected results, as this field is defined as a link:https://www.elastic.co/guide/en/elasticsearch/reference/6.3/nested.html[nested datatype] in the ElasticSearch mapping.
+
[note]#Database search engine#
This parameter is not compatible with the database search engine, it may only be used when Elasticsearch is configured as the user search engine.

[field]#search.queryString# [type]#[String]# [optional]#Optional#::
The Elasticsearch query string that is used to search for Users.  The [field]#ids#, [field]#query#, and [field]#queryString#  parameters are mutually exclusive, they are listed here in order of precedence.
+
[note]#Database search engine#
The Elasticsearch query string DSL is not supported for the database search engine.  Database search limits effective queries to single search terms that may match the following fields on the User:
+
  * `first_name`
  * `last_name`
  * `full_name`
  * `email`
  * `username`
+
The following is an example search request with a `queryString` value that is compatible with the database search engine:
+
``GET /api/user/search?queryString=jared%40fusionauth.io``

[field]#search.sortFields# [type]#[Array]# [optional]#Optional#::
An array of sort fields used to sort the result. The order the sort fields are provided will be maintained in the sorted output.
+
[note]#Database search engine#
This parameter has no effect when the database is configured as the user search engine.

[field]#search.sortFields[``x``].missing# [type]#[String]# [optional]#Optional# [default]#defaults to `_last`#::
The value to substitute if this field is not defined. Two special values may be used:
+
* `_first` When the field is not defined sort this record first.
* `_last` When the field is not defined sort this record last.

[field]#search.sortFields[``x``].name# [type]#[String]# [required]#Required#::
The name of the field to sort.
+
Due to how the search index is structured not all fields on the user are sortable. The following field names are currently supported.
+
* `birthDate`
* `email`
* `fullName`
* `id`&nbsp; [since]#Available Since 1.13.0#
* `insertInstant`
* `lastLoginInstant` &nbsp; [since]#Available Since 1.13.0#
* `login`
* `registrations.applicationId` &nbsp; [since]#Available Since 1.13.0#
* `registrations.id` &nbsp; [since]#Available Since 1.13.0#
* `registrations.insertInstant` &nbsp; [since]#Available Since 1.13.0#
* `registrations.lastLoginInstant` &nbsp; [since]#Available Since 1.13.0#
* `registrations.roles` &nbsp; [since]#Available Since 1.13.0#
* `tenantId`
* `username`

[field]#search.sortFields[``x``].order# [type]#[String]# [optional]#Optional# [default]#defaults to `asc`#::
The possible values are:
+
* `asc`
* `desc`

[field]#search.startRow# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The start row within the search results to return. Used for pagination.

[source,json]
.Example Request JSON searching by [field]#ids#
----
include::../../../src/json/users/search-ids-request.json[]
----

[source,json]
.Example JSON for the `query` parameter to search for users with unverified registrations to a specific application
----
include::../../../src/json/users/unverified-registrations-query.json[]
----

[source,json]
.Example Request JSON searching by [field]#query# for users with unverified registrations to a specific application
----
include::../../../src/json/users/search-query-request.json[]
----

[source,json]
.Example JSON for the `query` parameter to search for users with a specific role
----
include::../../../src/json/users/role-query.json[]
----

[source,json]
.Example JSON searching by `query` for users with with a specific role
----
include::../../../src/json/users/search-role-query-request.json[]
----

[source,json]
.Example Request JSON searching by [field]#queryString# for users with an email address matching a pattern
----
include::../../../src/json/users/search-queryString-email-request.json[]
----

[source,json]
.Example Request JSON searching by [field]#queryString# for users belonging to a specific group
----
include::../../../src/json/users/search-queryString-group-request.json[]
----

[source,json]
.Example Request JSON searching by `queryString` for users of a specific tenant. A global API key must be used, and you may not use the `X-FusionAuth-TenantId` header when the search parameters include `tenantId`
----
include::../../../src/json/users/search-queryString-tenant-request.json[]
----
