
// parameter_prefix is either blank for parameters or "search." for body

[.api]

[field]#{parameter_prefix}comment# [type]#[String]# [optional]#Optional#::
The case-insensitive string to search for in the User Comment text. This can contain wildcards using the asterisk character (`*`). If no wildcards are present, the search criteria will be interpreted as `pass:[*value*]`. If this field is omitted, no filtering will be applied to the `comment` field.

[field]#{parameter_prefix}numberOfResults# [type]#[Integer]# [optional]#Optional# [default]#defaults to `25`#::
The number of results to return from the search.

[field]#{parameter_prefix}orderBy# [type]#[String]# [optional]#Optional# [default]#defaults to `name ASC`#::
The field to order the search results as well as an order direction.
+
The possible values are:
+
 * `comment` - the User Comment text
 * `id` - the UUID of the user Comment
 * `insertInstant` - the link:/docs/v1/tech/reference/data-types#instants[instant] when the User Comment was created
 * `tenantId` - the UUID of the Tenant to which the User Comment belongs
 * `userId` - the UUID of the User to which the User Comment belongs
+
The order direction  is optional. Possible values of the order direction are `ASC` or `DESC`. If omitted, the default sort order is `ASC`.
+
For example, to order the results by the insert instant in a descending order, use `insertInstant DESC`.

[field]#{parameter_prefix}startRow# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The offset into the total results. In order to paginate the results, increment this value by the [field]#numberOfResults# for subsequent requests.

[field]#{parameter_prefix}tenantId# [type]#[UUID]# [optional]#Optional#::
Restricts the results to User Comments belonging to the given Tenant. This parameter will be overridden if the request contains an `X-FusionAuth-TenantId` header, or if the supplied API key is scoped to a specific Tenant.

[field]#{parameter_prefix}userId# [type]#[UUID]# [optional]#Optional#::
Restricts the results to User Comments belonging to the given User.


ifeval::["{parameter_prefix}" == "search."]
[source,json]
.Example Request JSON
include::../../../src/json/user-comments/search-post-request.json[]
endif::[]

