==== Response Body

[.api]
ifdef::search_result[]
[field]#total# [type]#[Long]#::
The number of users that matched the search criteria. The number of results in the response will be equal to the `numberOfResults` provided on the request, if not provided the default number of results will be returned.
endif::[]

[field]#users# [type]#[Array]#::
The list of Users.

[field]#users``[x]``.active# [type]#[Boolean]#::
True if the User is active. False if the User has been deactivated. Deactivated Users will not be able to login.

[field]#users``[x]``.birthDate# [type]#[String]#::
YYYY-MM-DD formatted date of the User's birth.

[field]#users``[x]``.cleanSpeakId# [type]#[UUID]#::
This Id is used by FusionAuth when the User's username is sent to CleanSpeak to be moderated (filtered and potentially sent to the approval queue). It is the **content Id** of the username inside CleanSpeak.

[field]#users``[x]``.data# [type]#[Object]#::
An object that can hold any information about the User that should be persisted.

[field]#users``[x]``.email# [type]#[String]#::
The User's email address.

[field]#users``[x]``.expiry# [type]#[Long]#::
The expiration link:/docs/v1/tech/reference/data-types/#instants[instant] of the User's account. After this instant is reached, the User's account will automatically be deactivated.

[field]#users``[x]``.firstName# [type]#[String]#::
The first name of the User.

[field]#users``[x]``.fullName# [type]#[String]#::
The User's full name as a separate field that is not calculated from [field]#firstName# and [field]#lastName#.

[field]#users``[x]``.id# [type]#[UUID]#::
The User's unique Id.

[field]#users``[x]``.imageUrl# [type]#[String]#::
The URL that points to an image file that is the User's profile image.

[field]#users``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when user was created.

[field]#users``[x]``.lastLoginInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the User logged in last.

[field]#users``[x]``.lastName# [type]#[String]#::
The User's last name.

[field]#users``[x]``.memberships# [type]#[Array]#::
The list of memberships for the User.

[field]#users``[x]``.memberships``[x]``.data# [type]#[Object]#::
An object that can hold any information about the User for this membership that should be persisted.

[field]#users``[x]``.memberships``[x]``.groupId# [type]#[UUID]#::
The Id of the Group of this membership.

[field]#users``[x]``.memberships``[x]``.id# [type]#[UUID]#::
The unique Id of this membership.

[field]#users``[x]``.memberships``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the membership was created.

[field]#users``[x]``.middleName# [type]#[String]#::
The User's middle name.

[field]#users``[x]``.mobilePhone# [type]#[String]#::
The User's mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.

[field]#users``[x]``.passwordChangeRequired# [type]#[Boolean]#::
Indicates that the User's password needs to be changed during their next login attempt.

[field]#users``[x]``.passwordLastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the User last changed their password.

[field]#users``[x]``.preferredLanguages# [type]#[Array<String>]#::
An array of locale strings that give, in order, the User's preferred languages. These are important for email templates and other localizable text. See link:/docs/v1/tech/reference/data-types/#locales[Locales].

[field]#users``[x]``.registrations# [type]#[Array]#::
The list of registrations for the User.

[field]#users``[x]``.registrations``[x]``.applicationId# [type]#[UUID]#::
The Id of the Application that this registration is for.

[field]#users``[x]``.registrations``[x]``.authenticationToken# [type]#[String]#::
The Authentication Token for this registration (if one exists).

[field]#users``[x]``.registrations``[x]``.cleanSpeakId# [type]#[UUID]#::
This Id is used by FusionAuth when the User's username for this registration is sent to CleanSpeak to be moderated (filtered and potentially sent to the approval queue). It is the **content Id** of the username inside CleanSpeak.

[field]#users``[x]``.registrations``[x]``.data# [type]#[Object]#::
An object that can hold any information about the User for this registration that should be persisted.

[field]#users``[x]``.registrations``[x]``.id# [type]#[UUID]#::
The Id of this registration.

[field]#users``[x]``.registrations``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that this registration was created.

[field]#users``[x]``.registrations``[x]``.lastLoginInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the User last logged into the Application for this registration.

[field]#users``[x]``.registrations``[x]``.preferredLanguages# [type]#[Array<String>]#::
An array of locale strings that give, in order, the User's preferred languages for this registration. These are important for email templates and other localizable text. See link:/docs/v1/tech/reference/data-types/#locales[Locales].

[field]#users``[x]``.registrations``[x]``.roles# [type]#[Array<String>]#::
The list of roles that the User has for this registration.

[field]#users``[x]``.registrations``[x]``.timezone# [type]#[String]#::
The User's preferred timezone for this registration. The string will be in an https://www.iana.org/time-zones[IANA] time zone format.

[field]#users``[x]``.registrations``[x]``.tokens# [type]#[Map<String,String>]# [since]#Available since 1.1.0#::
A map that contains tokens returned from identity providers.
+
For example, if this user has authenticated using the Facebook Identity Provider, the Facebook access token will be available in this map, keyed by name `Facebook`. For an OpenID Connect Identity provider, or other generic providers, if a token is stored it will be keyed by the Identity Provider unique Id.

[field]#users``[x]``.registrations``[x]``.username# [type]#[String]#::
The username of the User for this registration only.

[field]#users``[x]``.registrations``[x]``.usernameStatus# [type]#[String]#::

include::_moderation_status_response.adoc[]

[field]#users``[x]``.registrations``[x]``.verified# [type]#[Boolean]#::
This value indicates if this User's registration has been verified.

[field]#users``[x]``.tenantId# [type]#[UUID]#::
The Id of the Tenant that this User belongs to.

[field]#users``[x]``.timezone# [type]#[String]#::
The User's preferred timezone. This can be used as a default to display instants, and it is recommended that you allow User's to change this per-session. The string will be in an https://www.iana.org/time-zones[IANA] time zone format.

[field]#users``[x]``.twoFactorDelivery# [type]#[String]#::
The User's preferred delivery for verification codes during a two factor login request.
+
The possible values are:
+
* `None`
* `TextMessage`

[field]#users``[x]``.twoFactorEnabled# [type]#[Boolean]#::
Determines if the User has two factor authentication enabled for their account or not.

[field]#users``[x]``.username# [type]#[String]#::
The username of the User.

[field]#users``[x]``.usernameStatus# [type]#[String]#::

include::_moderation_status_response.adoc[]

[field]#users``[x]``.verified# [type]#[Boolean]#::
Whether or not the User's email has been verified.

[source,json]
.Example Response JSON
----
include::../../../src/json/users/users-response.json[]
----
