==== Response Body

[.api]
[field]#userConsents``[x]``.consent# [type]#[Object]#::
The Consent object represented by the [field]#consentId# field.

[field]#userConsents``[x]``.consentId# [type]#[UUID]#::
The Id of the Consent being granted to the User.

[field]#userConsents``[x]``.giverUserId# [type]#[UUID]#::
The Id of the User giving consent. When providing self-consent the [field]#giverUserId# will be the same as the [field]#userId#.

[field]#userConsents``[x]``.id# [type]#[UUID]#::
The unique Id of the User consent.

[field]#userConsents``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the User consent was granted.

[field]#userConsents``[x]``.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the User consent was last updated.

[field]#userConsents``[x]``.status# [type]#[String]#::
The current status of the User consent. Possible values are:
+
- `Active`
- `Revoked`

[field]#userConsents``[x]``.userId# [type]#[UUID]#::
The Id of the User receiving consent. When providing self-consent the [field]#giverUserId# will be the same as the [field]#userId#.

[field]#userConsents``[x]``.values# [type]#[Array<String>]#::
The consent values to be associated with this User consent.

[source,json]
.Example Response JSON
----
include::../../../src/json/user-consent/responses.json[]
----

