==== Request Body

[.api]
[field]#dryRun# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
To preview the user Ids to be deleted by the request without applying the requested action set this value to `true`.

[field]#hardDelete# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
To Permanently delete a user from FusionAuth set this value to `true`. Once a user has been permanently deleted, the action cannot be undone. When this value is set to `false` the user is marked as inactive and the user will be unable log into FusionAuth. This action may be undone by reactivating the user.

[field]#query# [type]#[String]# [optional]#Optional# [since]#Available Since 1.13.0#::
The raw JSON Elasticsearch query that is used to search for Users. The [field]#userIds#, [field]#query#, and [field]#queryString#  parameters are mutually exclusive, they are listed here in order of precedence.
+
It is necessary to use the [field]#query# parameter when querying against `registrations` in order to achieve expected results, as this field is defined as a link:https://www.elastic.co/guide/en/elasticsearch/reference/6.3/nested.html[nested datatype] in the ElasticSearch mapping.
+
[note]#Database search engine#
This parameter is not compatible with the database search engine, it may only be used when Elasticsearch is configured as the user search engine.

[field]#queryString# [type]#[String]# [optional]#Optional# [since]#Available Since 1.13.0#::
The Elasticsearch query string that is used to search for Users to be deleted. The [field]#userIds#, [field]#query#, and [field]#queryString#  parameters are mutually exclusive, they are listed here in order of precedence.
+
[note]#Database search engine#
The Elasticsearch query string DSL is not supported for the database search engine.  Database search limits effective queries to single search terms that may match the following fields on the User:
+
  * `first_name`
  * `last_name`
  * `full_name`
  * `email`
  * `username`
+
The following is an example bulk delete request with a `queryString` value that is compatible with the database search engine:
+
``DELETE /api/user/bulk?queryString=jared%40fusionauth.io``

[field]#userIds# [type]#[Array]# [optional]#Optional#::
An array of User Ids to delete. The [field]#userIds#, [field]#query#, and [field]#queryString#  parameters are mutually exclusive, they are listed here in order of precedence.

[source,json]
.Example Request JSON searching by `userIds`
----
include::../../../src/json/users/bulk-delete-ids-request.json[]
----

[source,json]
.Example JSON for the `query` parameter to search for users with unverified registrations to a specific application
----
include::../../../src/json/users/unverified-registrations-query.json[]
----

[source,json]
.Example JSON searching by `query` for users with unverified registrations to a specific application
----
include::../../../src/json/users/bulk-delete-query-request.json[]
----

[source,json]
.Example JSON for the `query` parameter to search for users with a specific role
----
include::../../../src/json/users/role-query.json[]
----

[source,json]
.Example JSON searching by `query` for users with with a specific role
----
include::../../../src/json/users/bulk-delete-role-query-request.json[]
----

[source,json]
.Example Request JSON searching by `queryString` for users with an email address matching a pattern
----
include::../../../src/json/users/bulk-delete-queryString-email-request.json[]
----

[source,json]
.Example Request JSON searching by `queryString` for users belonging to a specific group
----
include::../../../src/json/users/bulk-delete-queryString-group-request.json[]
----

[source,json]
.Example Request JSON searching by `queryString` for users of a specific tenant. A global API key must be used, and you may not use the `X-FusionAuth-TenantId` header when the search parameters include `tenantId`
----
include::../../../src/json/users/bulk-delete-queryString-tenant-request.json[]
----