==== Response Body

[.api]
ifdef::login_response,passwordless_login_response[]
[field]#refreshToken# [type]#[String]#::
The refresh token that can be used to obtain a new access token once the provide one has expired.
+
Because a refresh token is per user and per application, this value will only be returned when an [field]#applicationId# was provided on the login request.
+
You must explicitly allow generation of refresh tokens when using the Login API. Configure the [field]#application.loginConfiguration.generateRefreshTokens# setting via the API or enable the setting by navigating to the [breadcrumb]#Application -> My Application -> Security# tab.

ifdef::login_response[]
[field]#state# [type]#[Object]#::
If authenticated using a One Time Password and state was provided during the Change Password request this value will be returned exactly as it was provided.
endif::[]

ifdef::passwordless_login_response[]
[field]#state# [type]#[Object]#::
If state was provided during the passwordless login send request this value will be returned exactly as it was provided.
endif::[]
endif::[]

ifdef::two_factor_login_response[]
[field]#twoFactorTrustId# [type]#[String]#::
The Two Factor Trust identifier. This value is returned when `trustComputer` was set to `true` on the request. This value can be used by
subsequent login requests to bypass the Two Factor challenge.
endif::[]

[field]#token# [type]#[String]# [since]#Available since 1.16.0#::
The access token, this string is an encoded JSON Web Token (JWT).

[field]#user.active# [type]#[Boolean]#::
True if the User is active. False if the User has been deactivated. Deactivated Users will not be able to login.

[field]#user.birthDate# [type]#[String]#::
The User's birthdate formatted as `YYYY-MM-DD`

[field]#user.connectorId# [type]#[UUID]#::
The connector associated with the data source used to authenticate the user.  The link:/docs/v1/tech/connectors/fusionauth-connector[FusionAuth Connector] is the default.

[field]#user.cleanSpeakId# [type]#[UUID]#::
This Id is used by FusionAuth when the User's username is sent to CleanSpeak to be moderated (filtered and potentially sent to the approval queue). It is the **content Id** of the username inside CleanSpeak.

[field]#user.data# [type]#[Object]#::
An object that can hold any information about the User that should be persisted.

[field]#user.email# [type]#[String]#::
The User's email address.

ifdef::retrieve_user[]
[field]#user.encryptionScheme# [type]#[String]# [since]#Available since 1.20.1#::
The encryption scheme used to hash the password for this user. This value is only returned when the user is retrieved using an API key.
endif::[]

[field]#user.expiry# [type]#[Long]#::
The expiration link:/docs/v1/tech/reference/data-types/#instants[instant] of the User's account. An expired user is not permitted to login.

[field]#user.firstName# [type]#[String]#::
The first name of the User.

[field]#user.fullName# [type]#[String]#::
The User's full name as a separate field that is not calculated from [field]#firstName# and [field]#lastName#.

[field]#user.id# [type]#[UUID]#::
The User's unique Id.

[field]#user.imageUrl# [type]#[String]#::
The URL that points to an image file that is the User's profile image.

[field]#user.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when user was created.

[field]#user.lastLoginInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the User logged in last.

[field]#user.lastName# [type]#[String]#::
The User's last name.

ifndef::create_user[]
[field]#user.memberships# [type]#[Array]#::
The list of memberships for the User.

[field]#user.memberships``[x]``.data# [type]#[Object]#::
An object that can hold any information about the User for this membership that should be persisted.

[field]#user.memberships``[x]``.groupId# [type]#[UUID]#::
The Id of the Group of this membership.

[field]#user.memberships``[x]``.id# [type]#[UUID]#::
The unique Id of this membership.

[field]#user.memberships``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the membership was created.
endif::[]

[field]#user.middleName# [type]#[String]#::
The User's middle name.

[field]#user.mobilePhone# [type]#[String]#::
The User's mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.

[field]#user.parentEmail# [type]#[String]# [since]#Available since 1.7.0#::
The email address of the user's parent or guardian. If this value was provided during a create or update operation, this value value will only remain until the child is claimed by a parent.

[field]#user.passwordChangeRequired# [type]#[Boolean]#::
Indicates that the User's password needs to be changed during their next login attempt.

[field]#user.passwordLastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the User last changed their password.

[field]#user.preferredLanguages# [type]#[Array<String>]#::
An array of locale strings that give, in order, the User's preferred languages. These are important for email templates and other localizable text. See link:/docs/v1/tech/reference/data-types/#locales[Locales].

[field]#user.registrations# [type]#[Array]#::
The list of registrations for the User.

[field]#user.registrations``[x]``.applicationId# [type]#[UUID]#::
The Id of the Application that this registration is for.

[field]#user.registrations``[x]``.authenticationToken# [type]#[String]#::
The Authentication Token for this registration (if one exists).

[field]#user.registrations``[x]``.cleanSpeakId# [type]#[UUID]#::
This Id is used by FusionAuth when the User's username for this registration is sent to CleanSpeak to be moderated (filtered and potentially sent to the approval queue). It is the **content Id** of the username inside CleanSpeak.

[field]#user.registrations``[x]``.data# [type]#[Object]#::
An object that can hold any information about the User for this registration that should be persisted.

[field]#user.registrations``[x]``.id# [type]#[UUID]#::
The Id of this registration.

[field]#user.registrations``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that this registration was created.

[field]#user.registrations``[x]``.lastLoginInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the User last logged into the Application for this registration.

[field]#user.registrations``[x]``.preferredLanguages# [type]#[Array<String>]#::
An array of locale strings that give, in order, the User's preferred languages for this registration. These are important for email templates and other localizable text.

[field]#user.registrations``[x]``.roles# [type]#[Array<String>]#::
The list of roles that the User has for this registration.

[field]#user.registrations``[x]``.timezone# [type]#[String]#::
The User's preferred timezone for this registration. The string will be in an https://www.iana.org/time-zones[IANA] time zone format.

[field]#user.registrations``[x]``.tokens# [type]#[Map<String,String>]# [since]#Available since 1.1.0#::
A map that contains tokens returned from identity providers.
+
For example, if this user has authenticated using the Facebook Identity Provider, the Facebook access token will be available in this map, keyed by name `Facebook`. For an OpenID Connect Identity provider, or other generic providers, if a token is stored it will be keyed by the Identity Provider unique Id.

[field]#user.registrations``[x]``.username# [type]#[String]#::
The username of the User for this registration only.

[field]#user.registrations``[x]``.usernameStatus# [type]#[String]#::
include::_moderation_status_response.adoc[]

[field]#user.registrations``[x]``.verified# [type]#[Boolean]#::
This value indicates if this User's registration has been verified.

[field]#user.tenantId# [type]#[UUID]#::
The Id of the Tenant that this User belongs to.

[field]#user.timezone# [type]#[String]#::
The User's preferred timezone. This can be used as a default to display instants, and it is recommended that you allow User's to change this per-session. The string will be in an https://www.iana.org/time-zones[IANA] time zone format.

[field]#user.twoFactorDelivery# [type]#[String]#::
The User's preferred delivery for verification codes during a two factor login request.
+
The possible values are:
+
* `None`
* `TextMessage`

[field]#user.twoFactorEnabled# [type]#[Boolean]#::
Determines if the User has two factor authentication enabled for their account or not.

[field]#user.username# [type]#[String]#::
The username of the User.

[field]#user.usernameStatus# [type]#[String]#::
include::_moderation_status_response.adoc[]

[field]#user.verified# [type]#[Boolean]#::
Whether or not the User's email has been verified.
+
ifdef::login_response[]
[source,json]
.Example Response JSON
----
include::../../../src/json/users/login-response.json[]
----
endif::[]
+
ifdef::passwordless_login_response[]
[source,json]
.Example Response JSON
----
include::../../../src/json/users/passwordless-login-response.json[]
----
endif::[]
+
ifndef::login_response,passwordless_login_response[]
[source,json]
.Example Response JSON
----
include::../../../src/json/users/response.json[]
----
endif::[]

