==== Response Body

[.api]
[field]#refreshToken# [type]#[String]# [since]#Available since 1.17.0#::
The refresh token that can be used to obtain a new access token once the provide one has expired.

[field]#registration.applicationId# [type]#[UUID]#::
The Id of the Application that this registration is for.

[field]#registration.authenticationToken# [type]#[String]#::
The authentication token that may be used in place of the User's password when authenticating against this application represented by this registration.

[field]#registration.cleanSpeakId# [type]#[UUID]#::
This Id is used by FusionAuth when the User's username for this registration is sent to CleanSpeak to be moderated (filtered and potentially sent to the approval queue). It is the **content Id** of the username inside CleanSpeak.

[field]#registration.data# [type]#[Object]#::
An object that can hold any information about the User for this registration that should be persisted.

[field]#registration.id# [type]#[UUID]#::
The Id of this registration.

[field]#registration.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that this registration was created.

[field]#registration.lastLoginInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the User last logged into the Application for this registration.

[field]#registration.preferredLanguages# [type]#[Array<String>]#::
An array of locale strings that give, in order, the User's preferred languages for this registration. These are important for email templates and other localizable text. See link:/docs/v1/tech/reference/data-types/#locales[Locales].

[field]#registration.roles# [type]#[Array<String>]#::
The list of roles that the User has for this registration.

[field]#registration.timezone# [type]#[String]#::
The User's preferred timezone. The string will be in an https://www.iana.org/time-zones[IANA] time zone format.

[field]#registration.tokens# [type]#[Map<String,String>]# [since]#Available since 1.1.0#::
A map that contains tokens returned from identity providers.
+
For example, if this user has authenticated using the Facebook Identity Provider, the Facebook access token will be available in this map, keyed by name `Facebook`. For an OpenID Connect Identity provider, or other generic providers, if a token is stored it will be keyed by the Identity Provider unique Id.

[field]#registration.username# [type]#[String]#::
The username of the User for this registration only.

[field]#registration.verified# [type]#[Boolean]#::
This value indicates if this User's registration has been verified.

[field]#registration.usernameStatus# [type]#[String]#::

include::_moderation_status_response.adoc[]

[field]#token# [type]#[String]# [since]#Available since 1.16.0#::
The access token, this string is an encoded JSON Web Token (JWT).

[field]#user.birthDate# [type]#[String]#::
The User's birthdate formatted as `YYYY-MM-DD`

[field]#user.cleanSpeakId# [type]#[UUID]#::
This Id is used by FusionAuth when the User's username is sent to CleanSpeak to be moderated (filtered and potentially sent to the approval queue). It is the **content Id** of the username inside CleanSpeak.

[field]#user.data# [type]#[Object]#::
An object that can hold any information about the User that should be persisted.

[field]#user.email# [type]#[String]#::
The User's email address.

[field]#user.expiry# [type]#[Long]#::
The expiration link:/docs/v1/tech/reference/data-types/#instants[instant] of the User's account. An expired user is not permitted to login.

[field]#user.firstName# [type]#[String]#::
The first name of the User.

[field]#user.fullName# [type]#[String]#::
The User's full name as a separate field that is not calculated from [field]#firstName# and [field]#lastName#.

[field]#user.id# [type]#[UUID]#::
The User's unique Id.

[field]#user.imageUrl# [type]#[String]#::
The URL that points to an image file that is the User's profile image.

[field]#user.lastLoginInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the User logged in last.

[field]#user.lastName# [type]#[String]#::
The User's last name.

[field]#user.middleName# [type]#[String]#::
The User's middle name.

[field]#user.mobilePhone# [type]#[String]#::
The User's mobile phone number. This is useful is you will be sending push notifications or SMS messages to the User.

[field]#user.passwordChangeRequired# [type]#[Boolean]#::
Indicates that the User's password needs to be changed during their next login attempt.

[field]#user.passwordLastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the User last changed their password.

[field]#user.preferredLanguages# [type]#[Array<String>]#::
An array of locale strings that give, in order, the User's preferred languages. These are important for email templates and other localizable text. See link:/docs/v1/tech/reference/data-types/#locales[Locales].

[field]#user.timezone# [type]#[String]#::
The User's preferred timezone. The string will be in an https://www.iana.org/time-zones[IANA] time zone format.

[field]#user.twoFactor.methods``[x]``.authenticator.algorithm# [type]#[String]#::
The algorithm used by the TOTP authenticator. With the current implementation, this will always be `HmacSHA1`.

[field]#user.twoFactor.methods``[x]``.authenticator.codeLength# [type]#[Integer]#::
The length of code generated by the TOTP. With the current implementation, this will always be `6`.

[field]#user.twoFactor.methods``[x]``.authenticator.timeStep# [type]#[Integer]#::
The time-step size in seconds. With the current implementation, this will always be 30.

[field]#user.twoFactor.methods``[x]``.email# [type]#[String]#::
The value of the email address for this method. Only present if [field]#user.twoFactor.methods``[x]``.method# is `email`.

[field]#user.twoFactor.methods``[x]``.id# [type]#[String]#::
The unique Id of the method.

[field]#user.twoFactor.methods``[x]``.lastUsed# [type]#[Boolean]#::
`true` if this method was used most recently.

[field]#user.twoFactor.methods``[x]``.method# [type]#[String]#::
The type of this method. There will also be an object with the same value containing additional information about this method.  The possible values are:
+
* `authenticator`
* `email`
* `sms`

[field]#user.twoFactor.methods``[x]``.mobilePhone# [type]#[String]#::
The value of the mobile phone for this method. Only present if [field]#user.twoFactor.methods``[x]``.method# is `sms`.

[field]#user.twoFactor.methods``[x]``.secret# [type]#[String]#::
A base64 encoded secret

[field]#user.twoFactorDelivery# [type]#[String]# [deprecated]#Deprecated#::
The User's preferred delivery for verification codes during a two factor login request.
+
The possible values are:
+
* `None`
* `TextMessage`
+
[deprecated]#Removed in version 1.26.0#

[field]#user.twoFactorEnabled# [type]#[Boolean]# [deprecated]#Deprecated#::
Determines if the User has two factor authentication enabled for their account or not.
+
[deprecated]#Removed in version 1.26.0#

[field]#user.username# [type]#[String]#::
The username of the User.

[field]#user.usernameStatus# [type]#[String]#::

include::_moderation_status_response.adoc[]

[field]#user.verified# [type]#[Boolean]#::
Whether or not the User's email has been verified.

[source,json]
.Example Response JSON
----
include::../../../src/json/user-registrations/combined-response.json[]
----
