
====== Search Using Ids

[source,json]
.Example Request JSON searching by [field]#ids#
----
include::../../../src/json/users/search-ids-request.json[]
----

====== Search Using A Query String

[source,json]
.Example Request JSON searching by [field]#queryString# for users with an email address matching a pattern
----
include::../../../src/json/users/search-queryString-email-request.json[]
----

[source,json]
.Example Request JSON searching by [field]#queryString# for users belonging to a specific group
----
include::../../../src/json/users/search-queryString-group-request.json[]
----

[source,json]
.Example Request JSON searching by [field]#queryString# for users of a specific tenant. A global API key must be used, and you may not use the `X-FusionAuth-TenantId` header when the search parameters include `tenantId`
----
include::../../../src/json/users/search-queryString-tenant-request.json[]
----

[source,json]
.Example Request JSON searching by [field]#queryString# for active users with a certain email address without MFA enabled
----
include::../../../src/json/users/search-queryString-complex-request.json[]
----

====== Search Using A Query

Searches using `query` have two parts. You must build the JSON [field]#query# parameter, then escape it and include it in a request.

A request includes not only a query, but also additional search parameters, such as sorting or pagination. For more, see the link:/docs/v1/tech/guides/user-search-with-elasticsearch[Searching Users With Elasticsearch] guide.

====== Unverified Registrations

To search for users with unverified Registrations for a specific Application, you'd use this JSON for the query:

[source,json]
.Query JSON 
----
include::../../../src/json/users/unverified-registrations-query.json[]
----

And then escape and include it in this request JSON:

[source,json]
.Request JSON
----
include::../../../src/json/users/search-query-request.json[]
----

====== Specific Role

To search for users with a Role in an Application, you'd use this JSON for the query:

[source,json]
.Query JSON 
----
include::../../../src/json/users/role-query.json[]
----

And then escape and include it in this request JSON:

[source,json]
.Request JSON
----
include::../../../src/json/users/search-role-query-request.json[]
----

====== Specific Email Address

To search for users with a certain email address, you'd use this JSON for the query:

[source,json]
.Query JSON
----
include::../../../src/json/users/search-email-address-query.json[]
----

And then escape and include it in this request JSON:

[source,json]
.Request JSON
----
include::../../../src/json/users/search-email-address-query-request.json[]
----

====== Boolean User Data Attribute

To search for users with custom user data attribute of `dataMigrated` with a value equal to `true`, you'd use this JSON for the query:

[source,json]
.Query JSON
----
include::../../../src/json/users/search-user-data-query.json[]
----

And then escape and include it in this request JSON:

[source,json]
.Request JSON
----
include::../../../src/json/users/search-user-data-query-request.json[]
----

====== Additional Query Examples

Below are additional [field]#query# examples. The request JSON, in which the [field]#query# must be escaped and included, is omitted.

[source,json]
.Example JSON for the [field]#query# parameter to search for users with a price range in their registration data
----
include::../../../src/json/users/search-registration-data-range-query.json[]
----

[source,json]
.Example JSON for the [field]#query# parameter to search for users with any value for `userMigrated`
----
include::../../../src/json/users/search-data-exists-query.json[]
----

[source,json]
.Example Request JSON searching by [field]#nextResults# for users using a token returned in a previous search response
----
include::../../../src/json/users/search-nextResults-request.json[]
----

