==== Response Body

[.api]
[field]#userActions# [type]#[Array]#::
The list of User Action objects.

[field]#userActions``[x]``.active# [type]#[Boolean]#::
Whether or not this User Action is active.

[field]#userActions``[x]``.cancelEmailTemplateId# [type]#[UUID]#::
The Id of the Email Template that is used when User Actions are canceled.

[field]#userActions``[x]``.endEmailTemplateId# [type]#[UUID]#::
The Id of the Email Template that is used when User Actions expired automatically (end).

[field]#userActions``[x]``.id# [type]#[UUID]#::
The Id of the User Action.

[field]#userActions``[x]``.includeEmailInEventJSON# [type]#[Boolean]#::
Whether to include the email information in the JSON that is sent to the Webhook when a user action is taken.

[field]#userActions``[x]``.localizedNames# [type]#[Map<Locale, String>]#::
A mapping of localized names for this User Action. The key is the Locale and the value is the name of the User Action for that language.

[field]#userActions``[x]``.modifyEmailTemplateId# [type]#[UUID]#::
The Id of the Email Template that is used when User Actions are modified.

[field]#userActions``[x]``.modifyEmailTemplateId# [type]#[String]#::
The name of this User Action.

[field]#userActions``[x]``.options# [type]#[Array]#::
The list of User Action Options.

[field]#userActions``[x]``.options``[x]``.localizedNames# [type]#[Map<Locale, String>]#::
A mapping of localized names for this User Action Option. The key is the Locale and the value is the name of the User Action Option for that language.

[field]#userActions``[x]``.options``[x]``.name# [type]#[String]#::
The name of this User Action Option.

[field]#userActions``[x]``.preventLogin# [type]#[Boolean]#::
Whether or not this User Action will prevent the User from logging in.

[field]#userActions``[x]``.sendEndEvent# [type]#[Boolean]#::
Whether or not FusionAuth will send events to any registered Webhooks when this User Action expires.

[field]#userActions``[x]``.startEmailTemplateId# [type]#[UUID]#::
The Id of the Email Template that is used when User Actions are started (created).

[field]#userActions``[x]``.temporal# [type]#[Boolean]#::
Whether or not this User Action is time-based (temporal). Time based actions are temporary and once expired the action will no longer be considered active and will not affect the user.

[field]#userActions``[x]``.userEmailingEnabled# [type]#[Boolean]#::
Whether or not email is enabled for this User Action. If this is true, a checkbox will appear in the FusionAuth UI for this User Action that allows admins to specify that they want to email the User.

[field]#userActions``[x]``.userNotificationsEnabled# [type]#[Boolean]#::
Whether or not user notifications are enabled for this User Action. If this is true, a checkbox will appear in the FusionAuth UI for this User Action that allows admins to specify that they want to "notify users". What is does is send an additional flag named **notifyUser** in the event JSON that is sent to any registered Webhooks.

[source,json]
.Example Response JSON for all the User Actions
----
include::../../../src/json/user-actions/responses.json[]
----
