==== Request Body

[.api]
[field]#refreshTokens# [type]#[Array]# [required]#Required#::
The list of refresh tokens to import.

[field]#refreshTokens``[x]``.applicationId# [type]#[UUID]# [required]#Required#::
The unique Application Id that corresponds to the User Registration for this refresh token.

[field]#metaData.device.description# [type]#[String]# [optional]#Optional#::
A human readable description of the device represented by the `device` parameter.

[field]#metaData.device.lastAccessedAddress# [type]#[String]# [optional]#Optional#::
The IP address of this login request.

[field]#metaData.device.name# [type]#[String]# [optional]#Optional#::
A human readable name of the device represented by the `device` parameter.

[field]#metaData.device.type# [type]#[String]# [optional]#Optional#::
The type of device represented by the `device` parameter. The following types may be specified:
+
* `BROWSER`
* `DESKTOP`
* `LAPTOP`
* `MOBILE`
* `OTHER`
* `SERVER`
* `TABLET`
* `TV`
* `UNKNOWN`

[field]#refreshTokens``[x]``.startInstant# [type]#[String]# [required]#Required#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] of the start of this token. This value will be used to calculate the token expiration.

[field]#refreshTokens``[x]``.token# [type]#[String]# [required]#Required#::
The string representation of the refresh token.

[field]#refreshTokens``[x]``.userId# [type]#[UUID]# [required]#Required#::
The unique user Id of the refresh token owner.

[field]#validateDbConstraints# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Set this value to `true` in order to perform additional validation of the request. This validation includes, among other things, confirming that a user exists and is registered for the application which this `refreshToken` was created for.
+
If this is `false`, any errors such as duplicated refresh token values will return a `500` error without any additional messages.  If this is `true`, additional validation will be performed on the input request and a `400` response will be returned with JSON body indicating duplicate values or other error conditions encountered.
+
Setting this value to `true` will dramatically decrease the performance of this request. If importing large numbers of tokens in a single request you may need to increase request timeouts to ensure this request does not timeout before it has completed. 

[source,json]
.Example Request JSON
----
include::../../../src/json/users/refresh-tokens/import-request.json[]
----
