==== Response Body

The response body contains `options` to be passed to the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API]. The [field]#options.challenge#, [field]#options.user.id#, and [field]#options.excludeCredentials``[x]``.id# fields must be converted to ``ArrayBuffer``s for the `navigator.credentials.create()` request. See link:/docs/v1/tech/apis/webauthn#webauthn-javascript-api-binary-format[WebAuthn JavaScript API Binary Format] for details.

[.api]
[field]#options# [type]#[Object]#::
The WebAuthn public key credential creation options. This object is passed to the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] to create a new passkey.

[field]#options.attestation# [type]#[String]#::
The Relying Party's attestation conveyance preference. Currently supported values include:
+
 * `none` - The Relying Party is not interested in authenticator attestation.
+

[field]#options.authenticatorSelection.authenticatorAttachment# [type]#[String]#::
The Relying Party's authenticator attachment preference. Authenticators eligible for the current registration ceremony will be limited according to this requested attachment preference. Possible values are:
+
 * `platform` - The authenticator is integrated with the current device. These typically use the device's unlock mechanism for user verification (e.g. Touch ID, PIN, pattern).
 * `cross-platform` - The authenticator can be used between multiple devices such as a USB security key or Bluetooth-connected phone.
 * `null` (or omitted) - The Relying Party has no attachment preference. Any attachment will be allowed.

[field]#options.authenticatorSelection.userVerification# [type]#[String]#::
The Relying Party's user verification requirement. Eligible authenticators will be filtered according to this preference. Possible values are:
+
 * `discouraged` - The Relying Party does not want user verification to be used.
 * `preferred` - The Relying Party prefers that user verification is used if available but will not fail the ceremony if it is not provided.
 * `required` - The Relying Party requires user verification for the operation.

[field]#options.challenge# [type]#[String]#::
This field contains a base64url-encoded string that acts as a one-time challenge for the ceremony. This makes WebAuthn resistant to certain kinds of replay attacks.
+
See link:/docs/v1/tech/apis/webauthn#converting-base64url-encoded-string-to-arraybuffer[Converting base64url-encoded String to ArrayBuffer] for details on converting this value for the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] call.

[field]#options.excludeCredentials# [type]#[Array]#::
A list of passkeys whose generating authenticators should be excluded from the current registration ceremony. This is meant to prevent a user creating multiple passkeys for the same account on the same authenticator.

[field]#options.excludeCredentials``[x]``.id# [type]#[String]#::
The credential Id generated by the authenticator as a base64url-encoded string. An available authenticator that owns any passkey with one of these Ids is excluded from the current ceremony.
+
See link:/docs/v1/tech/apis/webauthn#converting-base64url-encoded-string-to-arraybuffer[Converting base64url-encoded String to ArrayBuffer] for details on converting these values for the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] call.

[field]#options.excludeCredentials``[x]``.transports# [type]#[List<String>]#::
A list of transport types supported by the authenticator that generated the passkey. This value is used as a hint to help identify authenticators containing one of the [field]#options.excludeCredentials#.
+
include::_webauthn-transports.adoc[]

[field]#options.excludeCredentials``[x]``.type# [type]#[String]#::
The credential type the current passkey refers to. The only value supported by WebAuthn is `public-key`.

[field]#options.extensions.credProps# [type]#[Boolean]#::
If `true`, the Relying Party will request the client to report on whether the new passkey is a client-side discoverable credential.

[field]#options.pubKeyCredParams# [type]#[Array]#::
A list of the Relying Party's acceptable options for the type of passkey and its signing algorithm in order of preference.

[field]#options.pubKeyCredParams``[x]``.alg# [type]#[Long]#::
The identifier for the signing algorithm to be used with the passkey. These values are defined by the https://www.iana.org/assignments/cose/cose.xhtml[IANA COSE Algorithms registry]. FusionAuth supports a subset of these algorithms.

[field]#options.pubKeyCredParams``[x]``.type# [type]#[String]#::
The credential type the current passkey refers to. The only value supported by WebAuthn is `public-key`.

[field]#options.rp.id# [type]#[String]#::
The Relying Party Id for this registration ceremony. Passkeys can only be used to authenticate on sites using the same Relying Party Id they were registered with.
+
If this value is `null` or omitted, the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] will use the browser origin as the Relying Party Id.

[field]#options.rp.name# [type]#[String]#::
The name of the Relying Party requesting a new passkey to be created. This value is intended for display during WebAuthn ceremonies.

[field]#options.timeout# [type]#[Long]#::
The number of milliseconds the Relying Party is willing to wait for the ceremony to complete. This value is treated as a hint and may be overridden by the client. This is an unsigned value.

[field]#options.user.displayName# [type]#[String]#::
A human-readable display name for the new passkey. This value may be displayed during the current and future WebAuthn ceremonies.

[field]#options.user.id# [type]#[String]#::
A user handle that can be used by the Relying Party to uniquely identify the user registering the passkey. FusionAuth uses the base64url-encoded unique Id for the user.
+
See link:/docs/v1/tech/apis/webauthn#converting-base64url-encoded-string-to-arraybuffer[Converting base64url-encoded String to ArrayBuffer] for details on converting this value for the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] call.

[field]#options.user.name# [type]#[String]#::
A human-readable name for the passkey intended for display. This value is meant to disambiguate between passkeys with a similar [field]#displayName#.


[source,json]
.Example Response JSON
----
include::../../../src/json/webauthn/register-start-response.json[]
----