==== Request Body

The [field]#credential# in the request body contains data returned by the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn client API] call. The [field]#credential.response.attestationObject# and [field]#credential.response.clientDataJSON# fields must be converted to base64url-encoded strings for the FusionAuth API request. See link:/docs/v1/tech/apis/webauthn#webauthn-javascript-api-binary-format[WebAuthn JavaScript API Binary Format] for details.

[.api]
[field]#credential.clientExtensionResults.credProps.rk# [type]#[Boolean]# [optional]#Optional#::
If `true`, the new passkey is "client-side discoverable," meaning that it can be used in authentication ceremonies without first identifying the user (e.g. by requiring the user to complete a form field). If `false`, or the [field]#credential.clientExtensionResults.credProps# field is omitted, the passkey should be treated as if it were _not_ client-side discoverable. FusionAuth does not currently support discoverable credentials (sometimes referred to as "resident keys").

[field]#credential.id# [type]#[String]# [required]#Required#::
A base64url-encoded version of the credential Id generated by the authenticator for this passkey.

[field]#credential.rpId# [type]#[String]# [optional]#Optional#::
If the tenant configuration overrides the Relying Party Id, this parameter should match [field]#tenant.webAuthnConfiguration.relyingPartyId#, otherwise the value should be omitted from the request object.

[field]#credential.response.attestationObject# [type]#[String]# [required]#Required#::
The base64url-encoded attestation data from the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn client API] response, which includes information on the new passkey and other data important for validation. See link:/docs/v1/tech/apis/webauthn#converting-arraybuffer-to-base64url-encoded-string[Converting ArrayBuffer to base64url-encoded String] for details on converting this value for the FusionAuth API request.

[field]#credential.response.clientDataJSON# [type]#[String]# [required]#Required#::
The base64url-encoded client data from the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn client API] response. This contains important information for the WebAuthn registration validation process, including the one-time challenge generated when the registration ceremony began. See link:/docs/v1/tech/apis/webauthn#converting-arraybuffer-to-base64url-encoded-string[Converting ArrayBuffer to base64url-encoded String] for details on converting this value for the FusionAuth API request.

[field]#credential.transports# [type]#[List<String>]# [optional]#Optional#::
A list of transport types supported by the authenticator that generated the passkey. This value is used as a hint during to help identify eligible authenticators during a WebAuthn ceremony.
+
include::_webauthn-transports.adoc[]

[field]#credential.type# [type]#[String]# [required]#Required#::
The credential type of the new passkey. The only value supported by WebAuthn is `public-key`.

[field]#origin# [type]#[String]# [required]#Required#::
The browser request origin during the registration ceremony.

[field]#rpId# [type]#[String]# [required]#Required#::
If the tenant configuration overrides the Relying Party Id, this parameter should match [field]#tenant.webAuthnConfiguration.relyingPartyId#, otherwise the value should be the browser request origin's effective domain during the ceremony.

[field]#userId# [type]#[UUID]# [required]#Required#::
The unique Id of the user registering this new passkey.

[source,json]
.Example Request JSON
----
include::../../../src/json/webauthn/register-complete-request.json[]
----
