[.api]
ifdef::include_total[]
[field]#total# [type]#[Integer]#::
The total number of Webhooks matching the search criteria. Use this value along with the [field]#numberOfResults# and [field]#startRow# in the search request to perform pagination.
endif::[]

[field]#{base_field_name}.applicationIds# [type]#[Array<UUID>]# [optional]#Optional# [deprecated]#Deprecated#::
The Ids of the Applications that this Webhook is associated with. If no Ids are returned and the [field]#global# field is `false`, this Webhook is not used. Typically [field]#global# should be set to `true`.
+
[deprecated]#Removed in version 1.37.0# In version 1.37.0 and beyond, Webhooks are optionally associated with Tenants instead of Applications. See new field [field]#tenantIds#.

[field]#{base_field_name}.connectTimeout# [type]#[Integer]#::
The connection timeout in milliseconds used when FusionAuth sends events to the Webhook.

[field]#{base_field_name}.data# [type]#[Object]# [since]#Available since 1.15.0#::
An object that can hold any information about the Webhook that should be persisted.

[field]#{base_field_name}.description# [type]#[String]#::
A description of the Webhook. This is used for display purposes only.

[field]#{base_field_name}.eventsEnabled# [type]#[Object]#::
A mapping for the events that are enabled for this Webhook. The key of the Object property is the name of the event and the value is a boolean. It should look like this:
+
[source,json]
----
{
  "user.create": true,
  "user.delete": false
}
----
+
The possible event types are:
+
include::_event-types.adoc[]

[field]#{base_field_name}.global# [type]#[Boolean]#::
Whether or not this Webhook is used for all Tenants or just for specific Tenants.
+
[since]#Before 1.37.0#
Whether or not this Webhook is used for all events or just for specific Applications.

[field]#{base_field_name}.headers# [type]#[Map<String, String>]#::
An object that contains headers that are sent as part of the HTTP request for the events.

[field]#{base_field_name}.httpAuthenticationPassword# [type]#[String]#::
The HTTP basic authentication password that is sent as part of the HTTP request for the events.

[field]#{base_field_name}.httpAuthenticationUsername# [type]#[String]#::
The HTTP basic authentication username that is sent as part of the HTTP request for the events.

[field]#{base_field_name}.id# [type]#[UUID]#::
The Id of the Webhook.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Webhook was added to the FusionAuth database.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Webhook was last updated in the FusionAuth database.

[field]#{base_field_name}.readTimeout# [type]#[Integer]#::
The read timeout in milliseconds used when FusionAuth sends events to the Webhook.

[field]#{base_field_name}.sslCertificate# [type]#[String]# [deprecated]#Deprecated#::
An SSL certificate in PEM format that is used to establish the SSL (TLS specifically) connection to the Webhook.
+
[deprecated]#Deprecated in version 1.48.0#
In version 1.48.0 and beyond, the webhook SSL certificate can be managed via [field]#{base_field_name}.sslCertificateKeyId#.

[field]#{base_field_name}.sslCertificateKeyId# [type]#[UUID]# [since]#Available since 1.48.0#::
The Id of an existing link:/docs/v1/tech/apis/keys[Key]. The X.509 certificate is used for client certificate authentication in requests to the Webhook.

[field]#{base_field_name}.tenantIds# [type]#[Array<UUID>]# [optional]#Optional# [since]#Available since 1.37.0#::
The Ids of the Tenants that this Webhook is associated with. If no Ids are returned and the [field]#global# field is `false`, this Webhook is not used.

[field]#{base_field_name}.url# [type]#[String]#::
The fully qualified URL of the Webhook's endpoint that will accept the event requests from FusionAuth.

ifeval::["{base_field_name}" == "webhook"]
[source,json]
.Example Response JSON for a Single Webhook
----
include::../../../src/json/webhooks/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "webhook"]
ifdef::include_total[]
[source,json]
.Example Response JSON
----
include::../../../src/json/webhooks/search-response.json[]
----
endif::[]
ifndef::include_total[]
[source,json]
.Example Response JSON for all the Webhooks
----
include::../../../src/json/webhooks/responses.json[]
----
endif::[]
endif::[]
