==== Request Body

The [field]#credential# in the request body contains data returned by the WebAuthn client API call. The [field]#credential.response.attestationObject# and [field]#credential.response.clientDataJSON# fields are returned as ``ArrayBuffer``s by the WebAuthn client API and must be converted to base64URL-encoded strings for the FusionAuth API request.

[.api]
[field]#credential.clientExtensionResults.credProps.rk# [type]#[Boolean]# [optional]#Optional#::
If `true`, the new passkey is "client-side discoverable," meaning that it can be used in authentication ceremonies without first identifying the user (e.g. by requiring the user to complete a form field). If `false`, or the [field]#credential.clientExtensionResults.credProps# field is omitted, the passkey should be treated as if it were _not_ client-side discoverable. FusionAuth does not currently support discoverable credentials (sometimes referred to as "resident keys").

[field]#credential.id# [type]#[String]# [required]#Required#::
A base64URL-encoded version of the credential Id generated by the authenticator for this passkey.

[field]#credential.rpId# [type]#[String]# [optional]#Optional#::
If the tenant configuration overrides the Relying Party Id, this parameter should match [field]#tenant.webAuthnConfiguration.relyingPartyId#, otherwise the value should be omitted from the request object.

[field]#credential.response.attestationObject# [type]#[String]# [required]#Required#::
The base64URL-encoded attestation data from the WebAuthn client API response, which includes information on the new passkey and other data important for validation. The authenticator returns this object as CBOR-encoded binary data in an ``ArrayBuffer``. This value must be converted to a base64URL-encoded string for the API request.

[field]#credential.response.clientDataJSON# [type]#[String]# [required]#Required#::
The base64URL-encoded client data from the WebAuthn client API response. This contains important information for the WebAuthn registration validation process, including the one-time challenge generated when the registration ceremony began. The authenticator returns this object as a UTF-8 encoded JSON string in an ``ArrayBuffer``, which must be converted to a base64URL-encoded string for the API request.

[field]#credential.transports# [type]#[List<String>]# [optional]#Optional#::
A list of transport types supported by the authenticator that generated the passkey. This value is used as a hint during to help identify eligible authenticators during a WebAuthn ceremony.

[field]#credential.type# [type]#[String]# [required]#Required#::
The credential type of the new passkey. The only value supported by WebAuthn is `public-key`.

[field]#origin# [type]#[String]# [required]#Required#::
The browser request origin during the registration ceremony.

[field]#rpId# [type]#[String]# [required]#Required#::
If the tenant configuration overrides the Relying Party Id, this parameter should match [field]#tenant.webAuthnConfiguration.relyingPartyId#, otherwise the value should be the browser request origin during the ceremony.

[field]#userId# [type]#[UUID]# [required]#Required#::
The unique Id of the user registering this new passkey.

// TODO : WebAuthn - sample request JSON
