==== Request Body

[.api]
[field]#applicationId# [type]#[UUID]# [required]#Required#::
The unique Id for the application the user wishes to authenticate to.

[field]#credentialId# [type]#[UUID]# [optional]#Optional#::
The unique database Id for one of a user's passkeys. If this parameter is provided, the authentication ceremony will be limited to the corresponding passkey.

[field]#loginId# [type]#[String]# [optional]#Optional#::
The email or the username of the authenticating user.
+
This field is marked optional, but you must provide either the [field]#loginId# or the [field]#userId# to complete this API. If both fields are provided in the request body, the [field]#userId# will be utilized.

[field]#state# [type]#[Object]# [optional]#Optional#::
Additional data to be passed through this WebAuthn authentication request. After successful login, the [field]#state# field in the response will contain this data.

[field]#userId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the authenticating user.
+
This field is marked optional, but you must provide either the [field]#loginId# or the [field]#userId# to complete this API. If both fields are provided in the request body, the [field]#userId# will be utilized.

[field]#workflow# [type]#[String]# [required]#Required#::
The WebAuthn workflow for the current authentication ceremony. The selected workflow will change the passkey request options on the response based on the tenant configuration. The workflow must be enabled at the tenant level and not overridden at the application level. The possible values are:
+
* `bootstrap` - The user is authenticating using a WebAuthn passkey after providing their email or username.
* `reauthentication` - The user is reauthenticating on a device they have previously authenticated from.

[source,json]
.Example Request JSON
----
include::../../../src/json/webauthn/authenticate-start-request.json[]
----
