==== Request Body

[.api]
[field]#webhook.applicationIds# [type]#[Array<UUID>]# [optional]#Optional# [deprecated]#Deprecated#::
The Ids of the Applications that this Webhook should be associated with. If no Ids are specified and the [field]#global# field is `false`, this Webhook will not be used. Typically [field]#global# should be set to `true`.
+
[deprecated]#Removed in version 1.37.0# In version 1.37.0 and beyond, Webhooks are optionally associated with Tenants instead of Applications. See new field [field]#tenantIds#.

[field]#webhook.connectTimeout# [type]#[Integer]# [required]#Required#::
The connection timeout in milliseconds used when FusionAuth sends events to the Webhook.

[field]#webhook.data# [type]#[Object]# [optional]#Optional# [since]#Available since 1.15.0#::
An object that can hold any information about the Webhook that should be persisted.

[field]#webhook.description# [type]#[String]# [optional]#Optional#::
A description of the Webhook. This is used for display purposes only.

[field]#webhook.eventsEnabled# [type]#[Object]# [optional]#Optional#::
A mapping for the events that are enabled for this Webhook. The key of the Object property is the name of the event and the value is a boolean. It should look like this:
+
[source,json]
----
{
  "user.create": true,
  "user.delete": false
}
----
+
The possible event types are:
+
include::_event-types.adoc[]

[field]#webhook.global# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Whether or not this Webhook is used for all Tenants or just for specific Tenants.
+
[since]#Before 1.37.0#
Whether or not this Webhook is used for all events or just for specific Applications. In almost all cases you want to set this field to `true` and filter on the application Id when processing the webhook.

[field]#webhook.headers# [type]#[Map<String, String>]# [optional]#Optional#::
An object that contains headers that are sent as part of the HTTP request for the events.

[field]#webhook.httpAuthenticationPassword# [type]#[String]# [optional]#Optional#::
The HTTP basic authentication password that is sent as part of the HTTP request for the events.

[field]#webhook.httpAuthenticationUsername# [type]#[String]# [optional]#Optional#::
The HTTP basic authentication username that is sent as part of the HTTP request for the events.

[field]#webhook.readTimeout# [type]#[Integer]# [required]#Required#::
The read timeout in milliseconds used when FusionAuth sends events to the Webhook.

[field]#webhook.sslCertificate# [type]#[String]# [optional]#Optional#::
An SSL certificate in PEM format that is used to establish the SSL (TLS specifically) connection to the Webhook.

[field]#webhook.sslCertificateKeyId# [type]#[UUID]# [optional]#Optional# [since]#Available since 1.48.0#::
The Id of an existing link:/docs/v1/tech/apis/keys[Key]. The X.509 certificate is used for client certificate authentication in requests to the Webhook.
+
If a request contains both [field]#webhook.sslCertificate# and [field]#webhook.sslCertificateKeyId#, the webhook will be configured using the existing Key rather than the provided PEM-encoded certificate.

[field]#webhook.tenantIds# [type]#[Array<UUID>]# [optional]#Optional# [since]#Available since 1.37.0#::
The Ids of the Tenants that this Webhook should be associated with. If no Ids are specified and the [field]#global# field is `false`, this Webhook will not be used.

[field]#webhook.url# [type]#[String]# [required]#Required#::
The fully qualified URL of the Webhook's endpoint that will accept the event requests from FusionAuth.

[source,json]
.Example Request JSON
----
include::../../../src/json/webhooks/request.json[]
----
