[.api]
[field]#{base_field_name}.applicationIds# [type]#[Array<UUID>]#::
The Ids of the Applications that this Webhook should be associated with. If no Ids are specified and the `global` field is false, this Webhook will not be used.

[field]#{base_field_name}.connectTimeout# [type]#[Integer]#::
The connection timeout in milliseconds used when FusionAuth sends events to the Webhook.

[field]#{base_field_name}.data# [type]#[Object]# [since]#Available since 1.15.0#::
An object that can hold any information about the Webhook that should be persisted.

[field]#{base_field_name}.description# [type]#[String]#::
A description of the Webhook. This is used for display purposes only.

[field]#{base_field_name}.eventsEnabled# [type]#[Object]#::
A mapping for the events that are enabled for this Webhook. The key of the Object property is the name of the event and the value is a boolean. It should look like this:
+
[source,json]
----
{
  "user.create": true,
  "user.delete": false
}
----
+
The possible event types are:
+
include::_event-types.adoc[]

[field]#{base_field_name}.global# [type]#[Boolean]#::
Whether or not this Webhook is used for all events or just for specific Applications.

[field]#{base_field_name}.headers# [type]#[Map<String, String>]#::
An object that contains headers that are sent as part of the HTTP request for the events.

[field]#{base_field_name}.httpAuthenticationPassword# [type]#[String]#::
The HTTP basic authentication password that is sent as part of the HTTP request for the events.

[field]#{base_field_name}.httpAuthenticationUsername# [type]#[String]#::
The HTTP basic authentication username that is sent as part of the HTTP request for the events.

[field]#{base_field_name}.id# [type]#[UUID]#::
The Id of the Webhook.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Webhook was added to the FusionAuth database.

[field]#{base_field_name}.lastUpdateInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the Webhook was last updated in the FusionAuth database.

[field]#{base_field_name}.readTimeout# [type]#[Integer]#::
The read timeout in milliseconds used when FusionAuth sends events to the Webhook.

[field]#{base_field_name}.sslCertificate# [type]#[String]#::
An SSL certificate in PEM format that is used to establish the SSL (TLS specifically) connection to the Webhook.

[field]#{base_field_name}.url# [type]#[String]#::
The fully qualified URL of the Webhook's endpoint that will accept the event requests from FusionAuth.

ifeval::["{base_field_name}" == "webhook"]
[source,json]
.Example Request JSON for a Single Webhook
----
include::../../../src/json/webhooks/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "webhook"]
[source,json]
.Example Request JSON for all the Webhooks
----
include::../../../src/json/webhooks/responses.json[]
----
endif::[]
