
// parameter_prefix is either blank for parameters or "search." for body

[.api]

[field]#{parameter_prefix}description# [type]#[String]# [optional]#Optional#::
The case-insensitive string to search for in the Webhook description. This can contain wildcards using the asterisk character (`*`). If no wildcards are present, this parameter value will be interpreted as `pass:[*value*]`.

[field]#{parameter_prefix}numberOfResults# [type]#[Integer]# [optional]#Optional# [default]#defaults to `25`#::
The number of results to return from the search.

[field]#{parameter_prefix}orderBy# [type]#[String]# [optional]#Optional# [default]#defaults to `name ASC`#::
The field to order the search results as well as an order direction.
+
The possible values are:
+
 * `description` - the description of the Webhook
 * `id` - the UUID of the Webhook
 * `insertInstant` - the link:/docs/v1/tech/reference/data-types#instants[instant] when the Webhook was created
 * `url` - the Webhook URL
+
The order direction is optional. Possible values of the order direction are `ASC` or `DESC`. If omitted, the default sort order is `ASC`.
+
For example, to order the results by the insert instant in a descending order, use `insertInstant DESC`.

[field]#{parameter_prefix}startRow# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The offset into the total results. In order to paginate the results, increment this value by the [field]#numberOfResults# for subsequent requests.
+
For example, if the total search results are greater than the page size designated by [field]#numberOfResults#, set this value to `25` to retrieve results `26-50`, assuming the default page size.

[field]#{parameter_prefix}tenantId# [type]#[UUID]# [optional]#Optional#::
Restricts the results to Webhooks associated with the given Tenant and all global Webhooks.

[field]#{parameter_prefix}url# [type]#[String]# [optional]#Optional#::
The case-insensitive string to search for in the Webhook URL. This can contain wildcards using the asterisk character (`*`). If no wildcards are present, this parameter value will be interpreted as `pass:[*value*]`.

ifeval::["{parameter_prefix}" == "search."]
[source,json]
.Example Request JSON
include::../../../src/json/webhooks/search-post-request.json[]
endif::[]

