==== Response Body

[.api]
[field]#webhook.applicationIds# [type]#[Array<UUID>]#::
The Ids of the Applications that this Webhook should be associated with. If no Ids are specified and the `global` field is false, this Webhook will not be used.

[field]#webhook.connectTimeout# [type]#[Integer]#::
The connection timeout in milliseconds used when FusionAuth sends events to the Webhook.

[field]#webhook.description# [type]#[String]#::
A description of the Webhook. This is used for display purposes only.

[field]#webhook.eventsEnabled# [type]#[Object]#::
A mapping for the events that are enabled for this Webhook. The key of the Object property is the name of the event and the value is a boolean. It should look like this:
+
[source,json]
----
{
  "user.create": true,
  "user.delete": false
}
----
+
The possible event types are:
+
include::_event-types.adoc[]

[field]#webhook.global# [type]#[Boolean]#::
Whether or not this Webhook is used for all events or just for specific Applications.

[field]#webhook.headers# [type]#[Map<String, String>]#::
An object that contains headers that are sent as part of the HTTP request for the events.

[field]#webhook.httpAuthenticationPassword# [type]#[String]#::
The HTTP basic authentication password that is sent as part of the HTTP request for the events.

[field]#webhook.httpAuthenticationUsername# [type]#[String]#::
The HTTP basic authentication username that is sent as part of the HTTP request for the events.

[field]#webhook.id# [type]#[UUID]#::
The Id of the Webhook.

[field]#webhook.readTimeout# [type]#[Integer]#::
The read timeout in milliseconds used when FusionAuth sends events to the Webhook.

[field]#webhook.sslCertificate# [type]#[String]#::
An SSL certificate in PEM format that is used to establish the SSL (TLS specifically) connection to the Webhook.

[field]#webhook.url# [type]#[String]#::
The fully qualified URL of the Webhook's endpoint that will accept the event requests from FusionAuth.

[source,json]
.Example Request JSON for a Single Webhook
----
include::../../../src/json/webhooks/response.json[]
----
