==== Request Body

The [field]#credential# in the request body contains data returned by the WebAuthn client API call. The [field]#credential.response.authenticatorData#, [field]#credential.response.clientDataJSON#, [field]#credential.response.signature#, and [field]#credential.response.userHandle# fields are returned as ``ArrayBuffer``s by the WebAuthn client API and must be converted to base64url-encoded strings for the FusionAuth API request.

[.api]
[field]#credential.clientExtensionResults# [type]#[Object]# [optional]#Optional#::
The results for WebAuthn extensions requested during authentication. FusionAuth does not currently support any WebAuthn authentication extensions.

[field]#credential.id# [type]#[String]# [required]#Required#::
A base64url-encoded version of the credential Id used by the authenticator for this ceremony.

[field]#credential.rpId# [type]#[String]# [optional]#Optional#::
If the tenant configuration overrides the Relying Party Id, this parameter should match [field]#tenant.webAuthnConfiguration.relyingPartyId#, otherwise the value should be omitted from the request object.

[field]#credential.response.authenticatorData# [type]#[String]# [required]#Required#::
The base64url-encoded authenticator data from the WebAuthn client API response, which includes information on the passkey used to complete the ceremony and other data important for validation. The authenticator returns this object as CBOR-encoded binary data in an ``ArrayBuffer``. This value must be converted to a base64url-encoded string for the API request.

[field]#credential.response.clientDataJSON# [type]#[String]# [required]#Required#::
The base64url-encoded client data from the WebAuthn client API response. This contains important information for the WebAuthn authentication validation process, including the one-time challenge generated when the registration ceremony began. The authenticator returns this object as a UTF-8 encoded JSON string in an ``ArrayBuffer``, which must be converted to a base64url-encoded string for the API request.

[field]#credential.response.signature# [type]#[String]# [required]#Required#::
The base64url-encoded signature from the WebAuthn client API response. The authenticator generates the signature using the selected passkey's private key by signing over the binary concatenation of [field]#credential.response.authenticatorData# and the SHA-256 hash of [field]#credential.response.clientDataJSON# before they are converted to base64url-encoded strings. The authenticator returns this as binary data in an ``ArrayBuffer``. This value must be converted to a base64url-encoded string for the API request.

[field]#credential.response.userHandle# [type]#[String]# [optional]#Optional#::
The base64url-encoded user handle from the WebAuthn client API response. This field is only required when the user was not identified prior to the authentication ceremony through the use of a client-side discoverable passkey. The authenticator returns this as binary data in an ``ArrayBuffer``, which must be converted to a base64url-encoded string for the API request.

[field]#credential.type# [type]#[String]# [required]#Required#::
The credential type of the passkey. The only value supported by WebAuthn is `public-key`.

[field]#origin# [type]#[String]# [required]#Required#::
The browser request origin during the authentication ceremony. For example, `example.com`.

[field]#rpId# [type]#[String]# [required]#Required#::
If the tenant configuration overrides the Relying Party Id, this parameter should match [field]#tenant.webAuthnConfiguration.relyingPartyId#, otherwise the value should be the browser request origin's effective domain during the ceremony.

[field]#twoFactorTrustId# [type]#[String]# [optional]#Optional#::
The Multi-Factor Trust identifier returned by the Multi-Factor Login API response. This value be may be provided to bypass the Multi-Factor challenge when a User has Multi-Factor enabled.

[source,json]
.Example Request JSON
----
include::../../../src/json/webauthn/authenticate-complete-request.json[]
----
