==== Response Body

[.api]
[field]#options# [type]#[Object]#::
The WebAuthn public key credential request options. This object is passed to the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn client API] to generate an assertion using an available passkey.

[field]#options.allowCredentials# [type]#[Array]#::
An array containing identifying information for passkeys that are allowed to complete this authentication ceremony, ordered from most to least preferred.

[field]#options.allowCredentials``[x]``.id# [type]#[String]#::
The credential Id generated by the authenticator as a base64url-encoded string. This value is used to locate an authenticator that can complete the ceremony.
+
These values must be converted to JavaScript ``ArrayBuffer``s before the [field]#options# are passed to the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn client API].

[field]#options.allowCredentials``[x]``.transports# [type]#[List<String>]#::
A list of transport types supported by the authenticator that generated the passkey. This value is used as a hint to help identify authenticators containing one of the [field]#options.allowCredentials#.
+
include::_webauthn-transports.adoc[]

[field]#options.allowCredentials``[x]``.type# [type]#[String]#::
The credential type the current passkey refers to. The only value supported by WebAuthn is `public-key`.

[field]#options.challenge# [type]#[String]#::
This field contains a base64url-encoded string that acts as a one-time challenge for the ceremony. This makes WebAuthn resistant to certain kinds of replay attacks.
+
This value must be converted to a JavaScript `ArrayBuffer` before the [field]#options# are passed to the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn client API].

[field]#options.rpId# [type]#[String]#::
The Relying Party Id for this authentication ceremony. Passkeys can only be used to authenticate on sites with the same Relying Party Id with which the passkeys were registered.
+
If this value is `null` or omitted, the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn client API] will use the browser origin as the Relying Party Id.

[field]#options.timeout# [type]#[Long]#::
The number of milliseconds the Relying Party is willing to wait for the ceremony to complete. This value is treated as a hint and may be overridden by the client. This is an unsigned value.

[field]#options.userVerification# [type]#[String]#::
The Relying Party's user verification requirement. Eligible authenticators will be filtered according to this preference. Possible values are:
+
* `discouraged` - The Relying Party does not want user verification to be used.
* `preferred` - The Relying Party prefers that user verification is used if available but will not fail the ceremony if it is not provided.
* `required` - The Relying Party requires user verification for the operation.

[source,json]
.Example Response JSON
----
include::../../../src/json/webauthn/authenticate-start-response.json[]
----