[api]
ifeval::["{base_field_name}" != "credential"]
[field]#{base_field_name}# [type]#[Array]#::
The list of WebAuthn Passkey objects.
endif::[]

[field]#{base_field_name}.algorithm# [type]#[Long]#::
The identifier for the signing algorithm used with the passkey. These values are defined by the https://www.iana.org/assignments/cose/cose.xhtml[IANA COSE Algorithms registry]. FusionAuth supports a subset of these algorithms.
+
include::_webauthn-supported-algorithms.adoc[]

[field]#{base_field_name}.attestationType# [type]#[String]#::
The type of attestation provided when the passkey was registered. Passkeys registered in FusionAuth will have a value of `none`. Imported passkeys may have another value.

[field]#{base_field_name}.authenticatorSupportsUserVerification# [type]#[Boolean]#::
Indicates whether this authenticator supports user verification. User verification ensures that the user is authorized to use the authenticator.
+
This value is currently determined by whether user verification occurred during the registration of this passkey rather than by other means, such as examining FIDO authenticator metadata.

[field]#{base_field_name}.credentialId# [type]#[String]#::
The credential Id generated by the authenticator stored as a base64url-encoded string. This value is used by authenticators to look up a passkey during an authentication ceremony and to prevent multiple passkeys from being registered on the same authenticator for a single user.

[field]#{base_field_name}.data# [type]#[Object]#::
An object that can hold any information about the passkey that should be persisted.

[field]#{base_field_name}.discoverable# [type]#[Boolean]#::
Indicates whether the passkey is "client-side discoverable." Discoverable passkeys can be used in authentication ceremonies without first identifying the user (e.g. by requiring the user to complete a form field).

[field]#{base_field_name}.displayName# [type]#[String]#::
The display name for the passkey selected during registration. This value should have been selected by the user.

[field]#{base_field_name}.id# [type]#[UUID]#::
The unique identifier for this passkey.

[field]#{base_field_name}.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the passkey was added to the FusionAuth database.

[field]#{base_field_name}.lastUseInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] that the passkey was last used to complete a WebAuthn ceremony.

[field]#{base_field_name}.name# [type]#[String]#::
A unique name meant to disambiguate passkeys with the same [field]#credential.displayName#.

[field]#{base_field_name}.publicKey# [type]#[String]#::
The passkey's public key, encoded in PEM format.

[field]#{base_field_name}.relyingPartyId# [type]#[String]#::
The Relying Party Id used at the time the passkey was registered.

[field]#{base_field_name}.signCount# [type]#[Integer]#::
A signature counter for the passkey. The signature count can be used by a Relying Party to identify a cloned or malfunctioning authenticator.

[field]#{base_field_name}.tenantId# [type]#[UUID]#::
The Id of the tenant to which this passkey belongs.

[field]#{base_field_name}.transports# [type]#[List<String>]#::
A list of transport types supported by the authenticator that generated the passkey. This value is used as a hint during to help identify eligible authenticators during a WebAuthn ceremony.
+
include::_webauthn-transports.adoc[]

[field]#{base_field_name}.userAgent# [type]#[String]#::
The user agent at the time the passkey was registered. This can be useful for troubleshooting purposes.

[field]#{base_field_name}.userId# [type]#[UUID]#::
The Id of the user that this passkey belongs to.


ifeval::["{base_field_name}" == "credential"]
[source,json]
.Example Response JSON
----
include::../../../src/json/webauthn/response.json[]
----
endif::[]

ifeval::["{base_field_name}" != "credential"]
[source,json]
.Example Response JSON
----
include::../../../src/json/webauthn/responses.json[]
----
endif::[]
