==== Request Body

[.api]
[field]#applicationId# [type]#[UUID]# [required]#Required#::
The Id for the application to which the user wishes to authenticate.

[field]#credentialId# [type]#[UUID]# [optional]#Optional#::
The unique database Id for one of a user's passkeys. If this parameter is provided, the authentication ceremony will be limited to the corresponding passkey.

[field]#loginId# [type]#[String]# [optional]#Optional#::
The email or the username of the authenticating user.
+
Required if [field]#userId# is not present. If both fields are provided in the request body, the [field]#userId# will be utilized.

[field]#state# [type]#[Object]# [optional]#Optional#::
An optional object that will be returned un-modified when you complete the WebAuthn authentication request. This may be useful to return the user to a particular state once they complete the authentication.

[field]#userId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the authenticating user.
+
This field is marked optional, but you must provide either the [field]#loginId# or the [field]#userId# to complete this API. If both fields are provided in the request body, the [field]#userId# will be utilized.

[field]#workflow# [type]#[String]# [required]#Required#::
The WebAuthn workflow for the current authentication ceremony. The value changes the passkey request options on the response based on the tenant configuration. The possible values are:
+
* `bootstrap` - The user is authenticating using a WebAuthn passkey after providing their email or username.
* `reauthentication` - The user is reauthenticating on a device they have previously authenticated from.

[source,json]
.Example Request JSON
----
include::../../../src/json/webauthn/authenticate-start-request.json[]
----
