---
layout: doc
title: Actioning Users
description: Learn how the FusionAuth API can be used to take actions on users
---

== Overview

This page contains the APIs that are used for actioning users. Once you have created the User Actions, you use this API to invoke a User Action on a User.

* <<Take an Action on a User>>
* <<Retrieve a Previously Taken Action>>
* <<Update a Previously Taken Action>>
* <<Cancel a Previously Taken Action>>


== Take an Action on a User

This API is used to take a User Action on a User. User Actions are the method that FusionAuth uses to discipline, reward and interact with Users.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[type=fas]] Take an action on a User
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/user/action#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

include::docs/v1/tech/apis/_action-user-request-body.adoc[]

=== Response

The response for this API contains the User Action along with any event and email information that was generated by FusionAuth.

:webhook_event:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:webhook_event!:

:userActionIncludeHistory: false
:userActionJSONFile: take-response.json
include::docs/v1/tech/apis/_action-user-response-body.adoc[]


== Retrieve a Previously Taken Action

This API is used to retrieve a User Action that was previously taken on a User, this can be thought of as the log or historical record.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[type=fas]] Retrieve a specific User Action Log by Id.
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/user/action/`\{actionId\}`#
--

==== Request Parameters

[.api]
[field]#actionId# [type]#[UUID]# [required]#Required#::
The unique Id of the Action to retrieve.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[type=fas]] Retrieve all the Actions for a specific User by the User Id.
[.endpoint]

.URI
--
[method]#GET# [uri]#/api/user/action``?userId=\{userId\}&active=\{active\}&preventingLogin=\{preventingLogin\}``#
--

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The unique Id of the User for which to retrieve all of the Actions.

[field]#active# [type]#[Boolean]# [optional]#Optional#::
When this parameter is provided and set to `true`, only active actions will be returned. When this parameter is provided and set to `false`, only the inactive actions will be returned. When this parameter is omitted, all actions will be returned.
+
An active action is a time based action that has not yet expired or been canceled. An inactive action is either a time based action that has expired, canceled or an action that is not time based.
+
This parameter and `preventingLogin` are mutually exclusive.

[field]#preventingLogin# [type]#[Boolean]# [optional]#Optional# [since]#Available since 1.4.0#::
When this value is provided and set to `true`, only active actions that are preventing the user from login will be returned. Omitting this parameter, or setting this parameter to `false` does not affect the API behavior.
+
This parameter and `active` are mutually exclusive because an action that is preventing login is always active.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

=== Response

The response for this API contains either a single User Action Log or a list of User Actions Logs for a User. If you specified an `actionId` on the URI the response will contain the User Action Log for that Id. If you pass in a `userId` as a URL parameter the response will contain all of the User Action Logs for that User. Both responses are defined below along with an example JSON response.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

:userActionIncludeHistory: true
:userActionJSONFile: response.json
include::docs/v1/tech/apis/_action-user-response-body.adoc[]

include::docs/v1/tech/apis/_action-user-list-response-body.adoc[]


== Update a Previously Taken Action

This API is used to update a User Action that was previously taken on a User. User Actions are the method that FusionAuth uses to discipline, reward and interact with Users.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[type=fas]] Update an in progress Action by Id
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/user/action/`\{actionId\}`#
--

==== Request Parameters

[.api]
[field]#actionId# [type]#[UUID]# [required]#Required#::
The Id of the User Action being updated.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

:userActionJSONFile: update-request.json
include::docs/v1/tech/apis/_action-user-update-request-body.adoc[]

=== Response

The response for this API contains the User Action along with any event and email information that was generated by FusionAuth.

:webhook_event:
include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]
:webhook_event!:

:userActionIncludeHistory: true
:userActionJSONFile: response.json
include::docs/v1/tech/apis/_action-user-response-body.adoc[]


== Cancel a Previously Taken Action

This API is used to cancel a User Action that was previously taken on a User. User Actions are the method that FusionAuth uses to discipline, reward and interact with Users.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[type=fas]] Cancel in progress Action by Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/user/action/`\{actionId\}`#
--

==== Request Parameters

[.api]
[field]#actionId# [type]#[UUID]# [required]#Required#::
The Id of the User Action being canceled.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

:userActionJSONFile: cancel-request.json
include::docs/v1/tech/apis/_action-user-update-request-body.adoc[]

=== Response

The response for this API contains the User Action along with any event and email information that was generated by FusionAuth.

:webhook_event:
include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]
:webhook_event!:

:userActionIncludeHistory: true
:userActionJSONFile: cancel-response.json
include::docs/v1/tech/apis/_action-user-response-body.adoc[]

