---
layout: doc
title: API Explorer
description: Explore the API for FusionAuth
---

++++
<link rel="stylesheet" type="text/css" href="./swagger-ui.css" />
<style>

/* overrides docs css that causes code text to be dark */
code.language-json  p {
color: #FFFFFF;
}
code.language-json  span {
color: #FFFFFF;
}
code.language-bash  p {
color: #FFFFFF;
}
code.language-bash  span {
color: #FFFFFF;
}

pre.microlight span.headerline {
color: #FFFFFF;
}

/* hides image */
.topbar-wrapper a.link {
display:none;
}
</style>
++++

== Overview

This tool uses the https://github.com/fusionauth/fusionauth-openapi[FusionAuth OpenAPI specification] to let you explore APIs FusionAuth offers.

== Configuration

This tool defaults to using the latest version of the FusionAuth API. If you are using a different version, find the https://github.com/FusionAuth/fusionauth-openapi/tags[correct version] and update the URL in the input box.

For example, to view the 1.40.0 release, put `https://raw.githubusercontent.com/FusionAuth/fusionauth-openapi/1.40.0/openapi.yaml` in the YAML file input box.

If you want to use the in-browser API explorer, you must enable CORS on your FusionAuth instance. To do so: 

* Navigate to [breadcrumb]#Settings ->System#
* Enable [field]#CORS#
* Update [field]#Allowed headers# to include `authorization`, `accept` and `content-type` headers.

== Explorer

++++
<div id="swagger-ui"></div>
<script src="./swagger-ui-bundle.js" charset="UTF-8"> </script>
<script src="./swagger-ui-standalone-preset.js" charset="UTF-8"> </script>
<script src="./swagger-initializer.js" charset="UTF-8"> </script>
++++
