---
layout: doc
title: API Key APIs
description: APIs for creating, retrieving, updating and deleting API Keys
---

== Overview

[NOTE.since]
====
This API has been available since 1.26.0
====

The FusionAuth APIs are primarily secured using API keys. This API can only be accessed using an API key that is set as a keyManager. In order to retrieve, update or delete an API key, an API key with equal or greater permissions must be used. A "tenant-scoped" API key can retrieve,     create, update or delete an API key for the same tenant. This page describes APIs that are used to manage API keys.

* <<Retrieve an API Key>>
* <<Create an API Key>>
* <<Create a New API Key From an Existing API Key>>
* <<Update an API Key>>
* <<Delete an API Key>>

== Retrieve an API Key

This API is used to retrieve a single API Key by unique Id. To retrieve a key, an API key with equal or greater permissions must be used.


=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve an API Key by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/api-key/`\{apiKeyId\}`#
--

==== Request Parameters

[.api]
[field]#apiKeyId# [type]#[UUID]# [required]#Required#::
The unique Id of the API Key to retrieve.

=== Response

The response for this API contains a single API Key. The response is defined below along with an example JSON response.

:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/_apikey-response-body.adoc[]


== Create an API Key

This API is used to create a new API Key. An API key with key manager permission set to true can create keys. A key with key manager permissions can not be created using this API. Only through admin UI or kickstart, it is possible to create such a key. An API key that is tenant scoped, can create another key for the same tenant.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Create a new Key with the provided unique Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/api-key/`\{apiKeyId\}`#
--

==== Request Parameters

[.api]
[field]#apiKeyId# [type]#[UUID]# [optional]#Optional# [default]#defaults to a generated UUID#::
The unique Id of the API Key to create. If not specified a secure random UUID will be generated.

include::docs/v1/tech/apis/_apikey-put-request-body.adoc[]

=== Response

The response for this API contains the Key that was updated.

:never_search_error:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/_apikey-post-response-body.adoc[]


== Create a New API Key From an Existing API Key

This API is used to create a New API Key based on an existing API Key (source key). The API key that is being copied must not be set as a key manager, if it is, this API will return an error. The resulting new key will have same permissions as the source key.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Create a new Key from an Existing Key
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/api-key/#
--

.Example API Key request JSON
[source,json]
{
  "sourceKeyId": "48b5762e-6829-4d7e-b53d-f7db5f5d3d1f"
}


=== Response

The response for this API contains the Key that was created.

:never_search_error:
include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/_apikey-response-body.adoc[]


== Update an API Key

This API is used to update an existing API Key. A tenant-scoped API key can update another API key for the same tenant.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Update the Key with the given Id
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/api-key/`\{apiKeyId\}`#
--

=== Request Parameters

[.api]
[field]#keyId# [type]#[UUID]# [required]#Required#::
The unique Id of the API Key to update.

include::docs/v1/tech/apis/_apikey-put-request-body.adoc[]

=== Response

The response for this API contains the Key that was updated.

:never_search_error:
include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/_apikey-update-response-body.adoc[]


== Delete an API Key

This API is used to delete a Key. Deletion is possible only with another API key with equal or greater permissions. A tenant-scoped API key of can delete another API key for the same tenant.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Delete the API Key with the given Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/api-key/`\{apiKeyId\}`#
--

=== Request Parameters

[.api]
[field]#apiKeyId# [type]#[UUID]# [required]#Required#::
The unique Id of the API Key to delete.

=== Response

This API does not return a JSON response body.

:never_search_error:
include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]
:never_search_error!:


