---
layout: doc
title: Audit Logs
description: The APIs for add entries to and searching the audit log
---

== Overview

This page contains the APIs that are used to manage the Audit Log. Here are the APIs:

* <<Add an Entry to the Audit Log>>
* <<Retrieve an Audit Log>>
* <<Search the Audit Log>>
* <<Export Audit Logs>>


== Add an Entry to the Audit Log

This API allows you to insert an Audit Log. Generally, Audit Logs are created automatically whenever an admin does something from the FusionAuth UI. However, you can use this API to insert Audit Logs directly if you need.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Create an Audit Log
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/system/audit-log#
--

==== Request Body

[.api]
[field]#auditLog.data# [type]#[Object]# [optional]#Optional#::
An object that can hold additional details of an audit log.

[field]#auditLog.newValue# [type]#[String]# [optional]#Optional#::
Intended to be utilized during a change to record the new value.

[field]#auditLog.oldValue# [type]#[String]# [optional]#Optional#::
Intended to be utilized during a change to record the old value prior to the change.

[field]#auditLog.reason# [type]#[String]# [optional]#Optional#::
Intended to be utilized during a change to indicate the reason for the modification.

[field]#auditLog.insertUser# [type]#[String]# [required]#Required#::
The user that took the action that is being written to the Audit Logs. We suggest you use email addresses for this field.

[field]#auditLog.message# [type]#[String]# [required]#Required#::
The message of the Audit Log.

[source,json]
.Example Request JSON
----
include::docs/src/json/audit-logs/create-request.json[]
----

=== Response

The response for this API does not contain a body. It only contains a status code.

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

== Retrieve an Audit Log

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Retrieve an Audit Log by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/system/audit-log/`\{logId\}`#
--

==== Request Parameters

[.api]
[field]#logId# [type]#[Long]# [required]#Required#::
The unique Id of the Audit Log to retrieve.

=== Response

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

==== Response Body

[.api]
[field]#auditLog.data# [type]#[Object]#::
Additional details of an audit log.

[field]#auditLog.newValue# [type]#[String]#::
The new value of a changed object.

[field]#auditLog.oldValue# [type]#[String]#::
The previous value of a changed object.

[field]#auditLog.reason# [type]#[String]#::
The reason why the audit log was created.

[field]#auditLog.id# [type]#[Long]#::
The Audit Log unique Id.

[field]#auditLog.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the Audit Log was created.

[field]#auditLog.insertUser# [type]#[String]#::
The user that created the Audit Log.

[field]#auditLog.message# [type]#[String]#::
The message of the Audit Log.

[source,json]
.Example JSON Response
----
include::docs/src/json/audit-logs/response.json[]
----

== Search the Audit Log

This API allows you to search and paginate through the Audit Logs.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Searches the Audit Logs using the given search criteria
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/system/audit-log/search``?message=\{message\}&start=\{start\}&end=\{end\}&user=\{user\}``#
--

When calling the API using a `GET` request you will send the search criteria on the URL using request parameters. In order to simplify the example URL above, not every possible parameter is shown, however using the provided pattern you may add any of the documented request parameters to the URL.

==== Request Parameters

[.api]
[field]#end# [type]#[Long]# [optional]#Optional#::
The end link:/docs/v1/tech/reference/data-types#instants[instant] of the date/time range to search within.

[field]#message# [type]#[String]# [optional]#Optional#::
The string to search in the Audit Log message for. This can contain wildcards using the asterisk or percent characters (* or %).

[field]#numberOfResults# [type]#[Integer]# [optional]#Optional# [default]#defaults to `25`#::
The number of results to return from the search.

[field]#orderBy# [type]#[String]# [optional]#Optional# [default]#defaults to `insert_instant DESC`#::
The database column to order the search results on plus the order direction.

The columns you can use for this are:

* `insert_instant` - the link:/docs/v1/tech/reference/data-types#instants[instant] when the Audit Log was created
* `insert_user` - the user that create the Audit Log
* `message` - the message of the Audit Log

For example, to order the results by the insert instant in a descending order, the value would be provided as `insert_instant DESC`. The final string is optional can be set to `ASC` or `DESC`.

[field]#start# [type]#[Long]# [optional]#Optional#::
The start link:/docs/v1/tech/reference/data-types#instants[instant] of the date/time range to search within.

[field]#startRow# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The offset row to return results from. If the search has 200 records in it and this is 50, it starts with row 50.

[field]#user# [type]#[String]# [optional]#Optional#::
The string to search in the Audit Log user for. This can contain wildcards using the asterisk or percent characters (* or %).

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Searches the Audit Logs using the given search criteria
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/system/audit-log/search#
--

When calling the API using a `POST` request you will send the search criteria in a JSON request body.

==== Request Body

[.api]
[field]#search.end# [type]#[Long]# [optional]#Optional#::
The end link:/docs/v1/tech/reference/data-types#instants[instant] of the date/time range to search within.

[field]#search.message# [type]#[String]# [optional]#Optional#::
The string to search in the Audit Log message for. This can contain wildcards using the asterisk or percent characters (* or %).

[field]#search.numberOfResults# [type]#[Integer]# [optional]#Optional# [default]#defaults to `25`#::
The number of results to return from the search.

[field]#search.orderBy# [type]#[String]# [optional]#Optional# [default]#defaults to `insert_instant DESC`#::
The database column to order the search results on plus the order direction.
+
The columns you can use for this are:
+
* `insert_instant` - the link:/docs/v1/tech/reference/data-types#instants[instant] when the Audit Log was created
* `insert_user` - the user that create the Audit Log
* `message` - the message of the Audit Log
+
For example, to order the results by the insert instant in a descending order, the value would be provided as `insert_instant DESC`. The final string is optional can be set to `ASC` or `DESC`.

[field]#search.start# [type]#[Long]# [optional]#Optional#::
The start link:/docs/v1/tech/reference/data-types#instants[instant] of the date/time range to search within.

[field]#search.startRow# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The offset row to return results from. If the search has 200 records in it and this is 50, it starts with row 50.

[field]#search.user# [type]#[String]# [optional]#Optional#::
The string to search in the Audit Log user for. This can contain wildcards using the asterisk or percent characters (* or %).

=== Response

The response for this API contains the Audit Logs matching the search criteria in paginated format.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

==== Response Body

[.api]
[field]#auditLogs# [type]#[Array]#::
The list of Audit Logs returned by the search.

[field]#auditLogs``[x]``.data# [type]#[Object]#::
Additional details of an audit log.

[field]#auditLogs``[x]``.data.newValue# [type]#[String]#::
The new value of a changed object.

[field]#auditLogs``[x]``.data.oldValue# [type]#[String]#::
The previous value of a changed object.

[field]#auditLogs``[x]``.data.reason# [type]#[String]#::
The reason why the audit log was created.

[field]#auditLogs``[x]``.id# [type]#[Long]#::
The Audit Log unique Id.

[field]#auditLogs``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the Audit Log was created.

[field]#auditLogs``[x]``.insertUser# [type]#[String]#::
The user that created the Audit Log.

[field]#auditLogs``[x]``.message# [type]#[String]#::
The message of the Audit Log.

[field]#total# [type]#[Integer]#::
The total number of Audit Logs in the search. This can help with pagination.

[source,json]
.Example JSON Response
----
include::docs/src/json/audit-logs/search-response.json[]
----

== Export Audit Logs

[NOTE.since]
====
Available Since Version 1.7.0
====

This API is used to export the Audit Logs, the response will be a compressed zip archive.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Export the Audit Logs matching the criteria
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/system/audit-log/export``?message=\{message\}&start=\{start\}&end=\{end\}&user=\{user\}``#
--

When calling the API using a `GET` request you will send the export criteria on the URL using request parameters. In order to simplify the example URL above, not every possible parameter is shown, however using the provided pattern you may add any of the documented request parameters to the URL.

==== Request Parameters

[.api]
[field]#dateTimeSecondsFormat# [type]#[String]#  [optional]#Optional# [default]#defaults to **[see description]**#::
The format string used to format the date and time columns in the export result.
+
When this parameter is omitted a default format of `M/d/yyyy hh:mm:ss a z` will be used. See the https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html[DateTimeFormatter patterns] for additional examples.

[field]#end# [type]#[Long]# [optional]#Optional#::
The end link:/docs/v1/tech/reference/data-types#instants[instant] of the date/time range to search within.

[field]#message# [type]#[String]# [optional]#Optional#::
The string to search in the Audit Log message for. This can contain wildcards using the asterisk or percent characters (* or %).

[field]#start# [type]#[Long]# [optional]#Optional#::
The start link:/docs/v1/tech/reference/data-types#instants[instant] of the date/time range to search within.

[field]#user# [type]#[String]# [optional]#Optional#::
The string to search in the Audit Log user for. This can contain wildcards using the asterisk or percent characters (* or %).

[field]#zoneId# [type]#[String]# [optional]#Optional# [default]#defaults to **[see description]**#::
The link:/docs/v1/tech/reference/data-types#time-zone[time zone] used to adjust the stored UTC time in the export result.
+
For example:
+
[quote]
`America/Denver` or `US/Mountain`
+
&nbsp;
+
When this parameter is omitted the configured default report time zone will be used. See [field]#reportTimezone# in the link:../apis/system[System Configuration API].

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=fas]] Export the Audit Logs matching the criteria
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/system/audit-log/export#
--

When calling the API using a `POST` request you will send the export criteria in a JSON request body.

==== Request Body

[.api]
[field]#criteria.end# [type]#[Long]# [optional]#Optional#::
The end link:/docs/v1/tech/reference/data-types#instants[instant] of the date/time range to include in the export.

[field]#criteria.message# [type]#[String]# [optional]#Optional#::
The string to search in the Audit Log message for. This can contain wildcards using the asterisk or percent characters (* or %).

[field]#criteria.start# [type]#[Long]# [optional]#Optional#::
The start link:/docs/v1/tech/reference/data-types#instants[instant] of the date/time range to include in the export.

[field]#criteria.user# [type]#[String]# [optional]#Optional#::
The string to search in the Audit Log user for. This can contain wildcards using the asterisk or percent characters (* or %).

[field]#dateTimeSecondsFormat# [type]#[String]#  [optional]#Optional# [default]#defaults to **[see description]**#::
The format string used to format the date and time columns in the export result.
+
When this parameter is omitted a default format of `M/d/yyyy hh:mm:ss a z` will be used. See the https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html[DateTimeFormatter patterns] for additional examples.

[field]#zoneId# [type]#[String]# [optional]#Optional# [default]#defaults to **[see description]**#::
The link:/docs/v1/tech/reference/data-types#time-zone[time zone] used to adjust the stored UTC time in the export result.
+
For example:
+
[quote]
`America/Denver` or `US/Mountain`
+
&nbsp;
+
When this parameter is omitted the configured default report time zone will be used. See [field]#reportTimezone# in the link:../apis/system[System Configuration API].

=== Response

The response for this API will contain a compressed zip of the audit logs.

:success_code: 200
:success_message: pass:normal[The request was successful. The response will be a compressed archive byte stream with a `Content-Type` of `application/zip`.]
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:success_code!:
:success_message!: