---
layout: doc
title: IP Access Control List APIs
description: APIs for creating, retrieving, updating and deleting IP Access Control Lists
---
:page-liquid:

== Overview

[NOTE.since]
====
This API has been available since 1.30.0
====

An IP ACL (Access Control List) is a list of IP ranges that are either Allowed or Blocked. Along with one entry that defines a start IP address of `*` (wild) that defines the default behavior when an IP address does not match any other range in the list. This means an IP ACL will have a default action of either Allow or Block. The IP address start and end entries for ranges currently only support IPv4.

An IP ACL may be assigned to an API Key, a Tenant or an Application.

When an IP ACL is assigned to an API key, the IP ACL will restrict the usage of the API key based upon the request originating IP address. If a request is made using an API key with an assigned IP ACL and the IP address is found to be blocked, a 401 status code will be returned. The user of this API key will not be able to tell the difference between an invalid API key and an API key that is blocked due to the IP ACL.

When an IP ACL is assigned to a Tenant or Application, it is used to restrict access to the FusionAuth SSO. This means it will be used to restrict access to endpoints that begin with `/oauth2/`, `/account/`, `/email/`, `/password/`, `/registration/` and any other user accessible themed pages. It will not be used to restrict access to the FusionAuth admin UI except when accessed through SSO, or the FusionAuth API.

If two IP ACLs are assigned one to a Tenant and the other to an Application, the Application IP ACL will take precedence.

The IP address used to test against the IP ACL is resolved by using the first value in the `X-Forwarded-For` HTTP header. If this header is not found, then the IP address reported by the HTTP Servlet request as the remote address will be used. If you are accessing FusionAuth through a proxy it is important that you trust your edge proxy to set the correct value in the `X-Forwarded-For` HTTP header. Because this header can be set by any HTTP client, it is only secure or trustworthy when managed by a trusted edge proxy. You should not rely upon this feature alone to restrict access to an API key.

The following APIs are provided to manage IP ACLs.

* <<Create an IP ACL>>
* <<Retrieve an IP ACL>>
* <<Search for IP ACLs>>
* <<Update an IP ACL>>
* <<Delete an IP ACL>>

== Create an IP ACL

This API is used to create a new IP ACL.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Create an IP ACL with a randomly generated Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/ip-acl#
--

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Create an IP ACL with the provided unique Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/ip-acl/`{ipAccessControlListId}`#
--

==== Request Parameters

[.api]
[field]#ipAccessControlListId# [type]#[UUID]# [optional]#Optional# [default]#defaults to secure random UUID#::
The Id to use for the new IP ACL. If not specified a secure random UUID will be generated.

include::docs/v1/tech/apis/_ip-acl-request-body.adoc[]

=== Response

The response for this API contains the IP ACL that was created.

:never_search_error:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/_ip-acl-response-body.adoc[]

== Retrieve an IP ACL

This API is used to retrieve a single IP ACL by unique Id.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve an IP ACL by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/ip-acl/`{ipAccessControlListId}`#
--

==== Request Parameters

[.api]
[field]#ipAccessControlListId# [type]#[UUID]# [required]#Required#::
The unique Id of the IP ACL to retrieve.

=== Response

:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/_ip-acl-response-body.adoc[]

== Search for IP ACLs

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Searches the IP ACLs using the given search criteria
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/ip-acl/search``?name=\{name\}``#
--

When calling the API using a `GET` request you will send the search criteria on the URL using request parameters. In order to simplify the example URL above, only the IP ACL specific parameter is shown, however you may add any of the documented request parameters to the URL.

==== Request Parameters

[.api]
[field]#name# [type]#[String]# [optional]#Optional#::
The string to match all or part of the IP ACL name. This can contain wildcards using the asterisk or percent characters (* or %).

[field]#numberOfResults# [type]#[Integer]# [optional]#Optional# [default]#defaults to `25`#::
The number of results to return from the search.

[field]#orderBy# [type]#[String]# [optional]#Optional# [default]#defaults to `name ASC`#::
The database column to order the search results on plus the order direction.
+
The possible values are:
+
* `id` - the id of the IP ACL
* `insertInstant` - the link:/docs/v1/tech/reference/data-types#instants[instant] when the IP ACL was created
* `lastUpdateInstant` - the last link:/docs/v1/tech/reference/data-types#instants[instant] that the IP ACL was updated
* `name` - the name of the IP ACL
+
For example, to order the results by the insert instant in descending order, the value would be provided as `insertInstant DESC`. The final string is optional, can be set to `ASC` or `DESC`, or omitted and will default to `ASC`.

[field]#startRow# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The offset row to return results from. If the search has 200 records in it and this is 50, it starts with row 50.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Searches the IP ACLs using the given search criteria
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/ip-acl/search#
--

When calling the API using a `POST` request you will send the search criteria in a JSON request body.

==== Request Body

[.api]
[field]#search.name# [type]#[String]# [optional]#Optional#::
The string to match all or part of the IP ACL name. This can contain wildcards using the asterisk or percent characters (* or %).

[field]#search.numberOfResults# [type]#[Integer]# [optional]#Optional# [default]#defaults to `25`#::
The number of results to return from the search.

[field]#search.orderBy# [type]#[String]# [optional]#Optional# [default]#defaults to `insertInstant DESC`#::
The database column to order the search results on plus the order direction.
+
The possible values are:
+
* `id` - the id of the IP ACL
* `insertInstant` - the link:/docs/v1/tech/reference/data-types#instants[instant] when the IP ACL was created
* `lastUpdateInstant` - the last link:/docs/v1/tech/reference/data-types#instants[instant] that the IP ACL was updated
* `name` - the name of the IP ACL
+
For example, to order the results by the insert instant in descending order, the value would be provided as `insertInstant DESC`. The final string is optional, can be set to `ASC` or `DESC`, or omitted and will default to `ASC`.

[field]#search.startRow# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The offset row to return results from. If the search has 200 records in it and this is 50, it starts with row 50.

=== Response

The response for this API contains the IP ACLs matching the search criteria in paginated format.

:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/_ip-acl-response-body-search.adoc[]

== Update an IP ACL

:capitalized_object_name: IP ACL
include::docs/v1/tech/apis/_generic-update-explanation-fragment.adoc[]
:capitalized_object_name!:

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Update the IP ACL with the given Id
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/ip-acl/`{ipAccessControlListId}`#
--

:api_endpoint: pass:normal[/api/ip-acl/`{ipAccessControlListId}`]
include::docs/v1/tech/apis/_patch-support.adoc[]

==== Request Parameters

[.api]
[field]#ipAccessControlListId# [type]#[UUID]# [required]#Required#::
The Id of the IP ACL to update.

include::docs/v1/tech/apis/_ip-acl-request-body.adoc[]

=== Response

The response for this API contains the IP ACL that was updated.

:never_search_error:
include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]
:never_search_error!:

include::docs/v1/tech/apis/_ip-acl-response-body.adoc[]

== Delete an IP ACL

This API is used to permanently delete an IP ACL. Deleting an IP ACL will remove it from any tenants and/or applications it was assigned. Delete will fail with a validation error if the IP ACL is still in use.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Delete an IP ACL by Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/ip-acl/`{ipAccessControlListId}`#
--

==== Request Parameters

[.api]
[field]#ipAccessControlListId# [type]#[UUID]# [required]#Required#::
The unique Id of the IP ACL to delete.

=== Response

This API does not return a JSON response body.

:never_search_error:
include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]
:never_search_error!:
