---
layout: doc
title: JWT & Refresh Token APIs
description: APIs that allow you to manage Refresh Tokens, verify Access Tokens and retrieve public keys used for verifying JWT signatures.
---

== Overview

JSON Web Tokens (JWTs) are portable identity tokens. A JWT is issued after completing a link:/docs/v1/tech/apis/login#authenticate-a-user[Login] request and is used to identify a user. JWTs can be used to call various FusionAuth APIs or they can be used to authenticate and authorize your APIs. In this document the term JWT and access token are used interchangeably.

* <<Issue a JWT>>
* <<Reconcile a JWT>>
* <<Refresh a JWT>>
* <<Validate a JWT>>
* <<Retrieve Public Keys>>
* <<Retrieve Refresh Tokens>>
* <<Revoke Refresh Tokens>>


== Issue a JWT
This API is used to issue a new access token (JWT) using an existing access token (JWT).

This API provides the single signon mechanism for access tokens. For example you have an access token for application A and you need an access
token for application B. You may use this API to request an access token to application B with the authorized token to application A. The returned access token will have the same expiration of the one provided.

This API will use a JWT as authentication. See link:/docs/v1/tech/apis/authentication#jwt-authentication[JWT Authentication] for examples of how you can send the JWT to FusionAuth.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#jwt-authentication[icon:id-badge[type=fas]] Issue an Access Token
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/jwt/issue``?applicationId=\{applicationId\}&refreshToken=\{refreshToken\}``#
--

==== Request Parameters

[.api]
[field]#applicationId# [type]#[UUID]# [required]#Required#::
The Id of the application for which authorization is being requested.

[field]#refreshToken# [type]#[String]# [optional]#Optional#::
An existing refresh token used to request a refresh token in addition to a JWT in the response. If the cookie `refresh_token` is also on the request it will take precedence over this value.
+
The target application represented by the [field]#applicationid# request parameter must have refresh tokens enabled in order to receive a refresh token in the response.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Cookies

[.api]
[field]#refresh_token# [type]#[String]# [optional]#Optional#::
The refresh token to be used to exchange for a refresh token in the application represented by the [field]#applicationid# request parameter.

[source,shell]
.Example HTTP Request using cookie
----
include::docs/src/requests/jwt/issue-get-request.http[]
----

=== Response

:authorization_message: You did not supply a valid Authorization header, the header was omitted or your access token is expired. The response will be empty. See link:/docs/v1/tech/apis/authentication[Authentication].
:not_registered:
:never_missing:
:no_errors:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:no_errors!:
:never_missing!:
:not_registered!:
:authorization_message!:

==== Response Body

[.api]
[field]#token# [type]#[String]#::
The encoded access token.

[field]#refreshToken# [type]#[String]#::
The refresh token. This value will only be returned if a valid non-expired refresh token was provided on the request and [field]#application.loginConfiguration.generateRefreshTokens# is `true`. The returned refresh token will share the same creation time as the original refresh token in regards to how the token expiration is calculated.
+
The refresh token expiration policy as defined by [field]#jwtConfiguration.refreshTokenExpirationPolicy# must be the same as the source application, if the policies are different a refresh token will not be returned.
[source,json]
.Example Response JSON
----
include::docs/src/json/jwt/issue-get-response.json[]
----

== Reconcile a JWT
The Reconcile API is used to take a JWT issued by a third party identity provider as described by an link:/docs/v1/tech/apis/identity-providers/[Identity Provider]
configuration and reconcile the User represented by the JWT to FusionAuth.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Reconcile a JWT
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/jwt/reconcile#
--

==== Request Headers

[.api]
[field]#X-Forwarded-For# [type]#[String]# [optional]#Optional#::
The IP address of a client requesting authentication. If the IP address is provided it will be stored for login history of the user. It is
generally preferred to specify the IP address in the request body. If it is not provided in the request body this header value will be used
if available, the request body value will take precedence.
include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation-row-only.adoc[]

include::docs/v1/tech/apis/_reconcile-request-body.adoc[]

=== Response

The response for this API contains the User object.

[cols="1,9a"]
.Response Codes
|===
|Code |Description

|200
|The reconcile was successful. The response will contain the User object that was authenticated.

|400
|The request was invalid and/or malformed. The response will contain an link:/docs/v1/tech/apis/errors[Errors] JSON Object with the specific errors.

|401
|The request cannot be completed. The `identityProviderId` is invalid, the JWT signature cannot be validated, the JWT does not contain a claim
identified by the `uniqueIdentityClaim` property in the Identity Provider configuration, or the domain of the email address claim in the JWT
is not managed by the Identity Provider Configuration.

|404
|The user was not found or the password was incorrect. The response will be empty.

|500
|There was an internal error. A stack trace is provided and logged in the FusionAuth log files. The response will be empty.

|503
|The search index is not available or encountered an exception so the request cannot be completed. The response will contain a JSON body.
|===

:login_response:
include::docs/v1/tech/apis/_user-response-body.adoc[]
:login_response!:

==== Response Cookies

[.api]
[field]#access_token# [type]#[String]#::
The encoded access token. This cookie is written in the response as an `HTTPOnly` session cookie.

[field]#refresh_token# [type]#[String]#::
The refresh token. This cookie is written in the response as an `HTTPOnly` persistent cookie. The cookie expiration is configured in the JWT
configuration for the application or the global JWT configuration.

== Retrieve Public Keys

This API is used to retrieve Public Keys generated by FusionAuth, used  used to cryptographically verify JWT signatures signed using the corresponding RSA or ECDSA private key.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Retrieve all Public Keys
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/jwt/public-key#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Retrieve a single Public Key for a specific Application by Application Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/jwt/public-key``?applicationId=\{applicationId\}``#
--

==== Request Parameters

[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
The Application Id is used to retrieve a specific Public Key. This will return the Public Key that has been specifically configured for the provided Application to sign the access token.
+
A public key may not be available for an Application if it is configured to use the global JWT configuration or a HMAC is the configured algorithm for JWT signing.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]


[NOTE.since]
====
This API has been available since 1.8.0
====

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Retrieve a single Public Key by Key Identifier
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/jwt/public-key``?kid=\{kid\}``#
--

==== Request Parameters

[.api]
[field]#kid# [type]#[String# [optional]#Optional#::
The Key Id used to retrieve a specific Public Key. This will return the Public Key associated with the Key Id.

=== Response

:no_errors:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:no_errors!:

==== Response Body

[.api]
[field]#publicKeys# [type]#[Map<String, String>]#::
The public keys keyed by the [field]#kid#.

[source,json]
.Example Response JSON for all Public Keys
----
include::docs/src/json/jwt/public-keys-response.json[]
----

==== Response Body

[.api]
[field]#publicKey# [type]#[String]#::
The public key configured for the specified Application.

[source,json]
.Example Response JSON for a single Public Key
----
include::docs/src/json/jwt/public-key-response.json[]
----

== Refresh a JWT

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Request a new Access Token by presenting a valid Refresh Token.
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/jwt/refresh#
--

The refresh token may be provided either in the HTTP request body or as a cookie. If both are provided, the cookie will take precedence.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Cookies

[.api]
[field]#refresh_token# [type]#[String]# [optional]#Optional#::
The refresh token to be used to obtain a new access token.
+
This value is required but optional as a cookie. It must be provided in either the request body or as a cookie.

[field]#access_token# [type]#[String]# [optional]#Optional#::
The previously issued encoded access token.  When provided on the request, this value will be relayed in the related JWT Refresh webhook event within the `original` field.

==== Request Body

[.api]
[field]#refreshToken# [type]#[String]# [optional]#Optional#::
The refresh token to be used to obtain a new access token.
+
This value is required but optional in the request body. It must be provided in either the request body or as a cookie.

[field]#token# [type]#[String]# [optional]#Optional#::
The previously issued encoded access token.  When provided on the request, this value will be relayed in the related JWT Refresh webhook event within the `original` field.

[source,json]
.Example Request JSON
----
include::docs/src/json/jwt/refresh-post-request.json[]
----

[source,shell]
.Example POST HTTP Request containing Cookie Header
----
include::docs/src/requests/jwt/refresh-post-request.http[]
----

=== Response

:no_errors:
:authorization_message: The provided Refresh Token is either expired or has been revoked.
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:no_errors!:
:authorization_message!:

==== Response Body

[.api]
[field]#refreshToken# [type]#[String]#::
The refresh token.
+
When [field]#jwtConfiguration.refreshTokenUsagePolicy# is equal to `Reusable` this will be equal to the refresh token provided in the request. When [field]#jwtConfiguration.refreshTokenUsagePolicy# is equal to `OneTimeUse` a new value will be returned and the previous refresh token value will no longer be valid.
+
The [field]#jwtConfiguration.refreshTokenUsagePolicy# is configured at the tenant, and optionally per application.

[field]#token# [type]#[String]#::
The encoded access token.

[source,json]
.Example Response JSON
----
include::docs/src/json/jwt/refresh-post-response.json[]
----

==== Response Cookies

[.api]
[field]#access_token# [type]#[String]#::
The encoded access token. This cookie is written in the response as an `HTTPOnly` session cookie.

[field]#refresh_token# [type]#[String]#::
The encoded refresh token.
+
This cookie is written in the response as an `HTTPOnly` cookie. When [field]#jwtConfiguration.refreshTokenUsagePolicy# is equal to `Reusable` this will be equal to the refresh token provided in the request. When [field]#jwtConfiguration.refreshTokenUsagePolicy# is equal to `OneTimeUse` a new value will be returned and the previous refresh token value will no longer be valid.
+
The [field]#jwtConfiguration.refreshTokenUsagePolicy# is configured at the tenant, and optionally per application.

== Retrieve Refresh Tokens

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve Refresh Tokens issued to a User
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/jwt/refresh``?userId=\{userId\}``#
--

=== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The Id of the user to retrieve issued Refresh Tokens.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

[.api-authentication]
link:/docs/v1/tech/apis/authentication#jwt-authentication[icon:id-badge[type=fas]] Retrieve Refresh Tokens issued to a User
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/jwt/refresh#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

=== Response

:no_errors:
:never_missing:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:no_errors!:
:never_missing!:

==== Response Body

[.api]
[field]#refreshTokens# [type]#[Array]#::
An array of Refresh Tokens

[field]#refreshTokens``[x]``.applicationId# [type]#[String]#::
The Id of the Application for which this token is authorized to be exchanged for a new Access Token.

[field]#refreshTokens``[x]``.device# [type]#[String]# [deprecated]#Deprecated#::
A unique device identifier to represent the device for which this Refresh Token was issued.
+
[deprecated]#Removed in version 1.5.0# This parameter will no longer be returned in the response body.

[field]#refreshTokens``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] this Refresh Token was issued.

[field]#refreshTokens``[x]``.metaData.device.description# [type]#[String]#::
A description of the device. For example, `iPhone 6S 32GB Work Phone`.

[field]#refreshTokens``[x]``.metaData.device.lastAccessedAddress# [type]#[String]#::
The IP address of the device when this Refresh Token was last used.

[field]#refreshTokens``[x]``.metaData.device.name# [type]#[String]#::
The name of the device, for example `Mary's iPhone`.

[field]#refreshTokens``[x]``.metaData.device.type# [type]#[String]#::
The type of device represented by the `device` parameter. The following are possible types:
+
* `BROWSER`
* `DESKTOP`
* `LAPTOP`
* `MOBILE`
* `OTHER`
* `SERVER`
* `TABLET`
* `TV`
* `UNKNOWN`

[field]#refreshTokens``[x]``.token# [type]#[String]#::
The string representation of the encoded Refresh Token. This value should be kept in some sort of secure storage and treated as sensitive information.

[field]#refreshTokens``[x]``.userId# [type]#[UUID]#::
The User Id of the user for which this Refresh Token was issued.


[source,json]
.Example Response JSON
----
include::docs/src/json/jwt/refresh-get-response.json[]
----

== Revoke Refresh Tokens

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Revoke all Refresh Tokens for an entire Application
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/jwt/refresh``?applicationId=\{applicationId\}``#
--

=== Request Parameters

[.api]
[field]#applicationId# [type]#[UUID]# [required]#Required#::
The Id of the application to revoke all issued Refresh Tokens. This will result in any user issued a Refresh Token for this application being required to be issued a new Refresh Token, in other words they'll need to be authenticated again.
+
This essentially provides a kill switch for all Refresh Tokens scoped to the application.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Revoke all Refresh Tokens issued to a User
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/jwt/refresh``?userId=\{userId\}``#
--

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The Id of the user to revoke issued Refresh Tokens.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Revoke a single Refresh Token
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/jwt/refresh``?token=\{token\}``#
--
This API may be authenticated using an Access Token. See link:/docs/v1/tech/apis/authentication[Authentication] for examples of authenticating using an Access Token. The token owner must match the identity in the access token if provided to be successful.

==== Request Parameters

[.api]
[field]#token# [type]#[String]# [required]#Required#::
The refresh token in string form that is to be revoked. This string may contain characters such as a plus sign that need to be encoded to be valid on the URL. If you're manually building this request ensure you are properly URL encoding this value.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

=== Response
This API does not return a JSON response body.

:no_errors:
include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]
:no_errors!:

== Validate a JWT

This API is used to validate a JSON Web Token. A valid JWT indicates the signature is valid and the payload has not be tampered with and the token is not expired.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Validate Access Token.
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/jwt/validate#
--

The access token can be provided to the API using an HTTP request header, or a cookie. The response body will contain the decoded JWT payload.

==== Request Headers

[.api]
[field]#Authorization# [type]#[String]# [optional]#Optional#::
The encoded JWT to validate sent in on the Authorization request header.
+
The header is expected be in the following form: `Authorization: JWT <encoded_access_token>`
+
See link:/docs/v1/tech/apis/authentication[Authentication] for additional examples.

==== Request Cookies

[.api]
[field]#access_token# [type]#[String]# [optional]#Optional#::
The encoded JWT. This cookie is written to the client by the Login API.

[cols="1,9"]
.Response Codes
|===
|Code |Description

|200
|The request was successful. The response will contain a JSON body.

|401
|The access token is not valid. A new access token may be obtained by authentication against the Login API, the Token Endpoint or by utilizing a Refresh Token.

|500
|There was an internal error. A stack trace is provided and logged in the FusionAuth log files. The response will be empty.
|===

==== Response Body

[.api]
[field]#jwt# [type]#[Object]#::
The decoded JWT payload. The payload contains the identity claims for the user.

[source,json]
.Example Response JSON
----
include::docs/src/json/jwt/validate-response.json[]
----
