---
layout: doc
title: Keys APIs
description: APIs for generating, importing, retrieving, updating and deleting keys
---

== Overview

[NOTE.since]
====
This API has been available since 1.6.0
====

Cryptographic keys are used in signing and verifying JWTs and verifying responses for third party identity providers. It is more likely you will interact with keys using the FusionAuth UI in the Key Master menu. If you do have a need to retrieve or manage keys using the API the following APIs have been provided.

* <<Retrieve a Key>>
* <<Update a Key>>
* <<Delete a Key>>
* <<Generate a Key>>
* <<Import a Key>>

== Retrieve a Key

This API is used to retrieve a single Key by unique Id or all of the configured Keys.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve all of the Keys
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/key#
--

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve a Key by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/key/`\{keyId\}`#
--

==== Request Parameters

[.api]
[field]#keyId# [type]#[UUID]# [required]#Required#::
The unique Id of the Key to retrieve.

=== Response

The response for this API contains either a single Key or all of the Keys. When you call this API with an Id the response will contain a single Key. When you call this API without an Id the response will contain all of the Keys. Both response types are defined below along with an example JSON response.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/_key-response-body.adoc[]

include::docs/v1/tech/apis/_key-responses-body.adoc[]

== Update a Key

This API method is used to update an existing Key. Only the name of the Key may be changed; all other fields will remain the same. If you need to update a Key with a new certificate, algorithm or other attributes, please <<Import a Key>>.

For example, if you have a Key with an associated expiring certificate, you'll need to follow the steps similar to those outlined in the link:/docs/v1/tech/tutorials/key-rotation#jwt-signing-key-rotation[JWT signing key rotation documentation]:

* Import this key into FusionAuth.
* Update the appropriate configuration with this new Key (JWT signing configuration, SAML validation configuration, etc).
* Once the configured, remove the expired, previous Key. 

Note that validation rules will prevent you from removing an in-use key.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Update the Key with the given Id
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/key/`\{keyId\}`#
--

=== Request Parameters

[.api]
[field]#keyId# [type]#[UUID]# [required]#Required#::
The unique Id of the Key to update.

include::docs/v1/tech/apis/_key-put-request-body.adoc[]

=== Response

The response for this API contains the Key that was updated.

include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]

include::docs/v1/tech/apis/_key-response-body.adoc[]

== Delete a Key

This API is used to delete a Key.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Delete the Key with the given Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/key/`\{keyId\}`#
--

=== Request Parameters

[.api]
[field]#keyId# [type]#[UUID]# [required]#Required#::
The unique Id of the Key to delete.

=== Response

This API does not return a JSON response body.

include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]

== Generate a Key

This API is used to generate a new Key.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Generate a new Key with a randomly generated Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/key/generate#
--

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Generate a new Key with the provided unique Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/key/generate/`\{keyId\}`#
--

=== Request Parameters

[.api]
[field]#keyId# [type]#[UUID]# [optional]#Optional# [default]#defaults to secure random UUID#::
The Id to use for the new key. If not specified a secure random UUID will be generated.

include::docs/v1/tech/apis/_key-generate-post-request-body.adoc[]

=== Response

The response for this API contains the Key that was generated.

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

include::docs/v1/tech/apis/_key-response-body.adoc[]

== Import a Key

This API is used to import an existing Key into FusionAuth. 

For RSA pairs, possible key lengths are: `1024` (only valid when importing a public key for signature verification), `2048`, `3072` or `4096`.

For EC pairs, possible key lengths are: `256`, `384`, or `521`.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Import an existing Key with a randomly generated Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/key/import#
--

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Import an existing Key with the provided unique Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/key/import/`\{keyId\}`#
--

=== Request Parameters

[.api]
[field]#keyId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the Key. Use if you want to specify a known UUID. This is useful if you are migrating from an existing system or will otherwise depend on having a known key Id.

include::docs/v1/tech/apis/_key-import-post-request-body.adoc[]

=== Response

The response for this API contains the Key that was imported.

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

include::docs/v1/tech/apis/_key-response-body.adoc[]
