---
layout: doc
title: Login APIs
description: APIs for authenticating users (logging them in) or tracking an SSO login (login ping) and two factor authentication
---

== Overview

The following APIs are used to authenticate and track user logins.

* <<Authenticate a User>>
* <<Authenticate a User with a one time password>>
* <<Complete Two Factor Authentication>>
* <<Update Login Instant>>
* <<Logout a User>>

The following APIs allow you to search and export historical login records.

* <<Search Login Records>>
* <<Export Login Records>>

== Authenticate a User

The Login API is used authenticate a user in FusionAuth. The issuer of the One Time Password will dictate if a JWT or a Refresh Token may be issued in the API response.

=== Request

By default, this API will require authentication when called with an [field]#applicationId#. Authentication may be disabled per Application, see [field]#application.loginConfiguration.requireAuthentication# in the link:/docs/v1/tech/apis/applications/[Application API] or navigate to [breadcrumb]#Applications -> Edit -> Security# in the user interface.


Prior to version `1.5.0` this API did not accept an API key and never required authentication.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:lock[type=fas]] Authenticate a User
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/login#
--

==== Request Headers

[.api]
[field]#X-Forwarded-For# [type]#[String]# [optional]#Optional#::
The IP address of a client requesting authentication. If the IP address is provided it will be stored for login history of the user. It is
generally preferred to specify the IP address in the request body. If it is not provided in the request body this header value will be used
if available, the request body value will take precedence.
include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation-row-only.adoc[]

==== Request Cookies

[.api]
[field]#fusionauth.trust# [type]#[String]# [optional]#Optional#::
The Two Factor Trust identifier returned by the Two Factor Login API response. This value be may be provided to bypass the Two Factor challenge when a User has Two Factor enabled. When this cookie exists on the request it will take precedence over the [field]#twoFactorTrustId# if provided in the request body.

==== Request Body

[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
The Id of the Application the user is to be logged into. This parameter is optional but there is not likely a production use case where you want to omit the value.
+
Because a refresh token is per user and per application, when this parameter is not provided a refresh token will not be returned.

[field]#ipAddress# [type]#[String]# [optional]#Optional#::
The IP address of the end-user that is logging into FusionAuth. If this value is omitted FusionAuth will attempt to obtain the IP address of
the client, the value will be that of the `X-Forwarded-For` header if provided or the last proxy that sent the request. The IP address will
be stored in the User login history.

[field]#loginId# [type]#[String]# [required]#Required#::
The login identifier of the user. The login identifier can be either the [field]#email# or the [field]#username#.

[field]#metaData.device.description# [type]#[String]# [optional]#Optional#::
A human readable description of the device used during login. This meta data is used to describe the refresh token that may be generated for this login request.

[field]#metaData.device.name# [type]#[String]# [optional]#Optional#::
A human readable name of the device used during login.  This meta data is used to describe the refresh token that may be generated for this login request.

[field]#metaData.device.type# [type]#[String]# [optional]#Optional#::
The type of device used during login. The following types may be specified:
+
* `BROWSER`
* `DESKTOP`
* `LAPTOP`
* `MOBILE`
* `OTHER`
* `SERVER`
* `TABLET`
* `TV`
* `UNKNOWN`
+
This meta data is used to describe the refresh token that may be generated for this login request.

[field]#noJWT# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
When this value is set to true a JWT will not be issued as part of this request. The response body will not contain the `token` or `refreshToken` fields, and the `access_token` and `refresh_token` cookies will not be written to the HTTP response.
+
This optional parameter may be helpful when performing high volume authentication requests and the JWT is not being utilized, in this scenario removing the additional latency required to issue and sign the JWT may have a measurable cumulative effect on performance.

[field]#password# [type]#[String]# [required]#Required#::
The user's password or an Application specific link:/docs/v1/tech/tutorials/application-authentication-tokens/[Authentication Token].

[field]#twoFactorTrustId# [type]#[String]# [optional]#Optional#::
The Two Factor Trust identifier returned by the Two Factor Login API response. This value be may be provided to bypass the Two Factor challenge when a User has Two Factor enabled.

[source,json]
.Example Request JSON
----
include::docs/src/json/login/request.json[]
----

=== Response

The response for this API contains the User object.

:auth_optional:
include::docs/v1/tech/apis/_login-response-codes.adoc[]
:auth_optional!:

:login_response:
include::docs/v1/tech/apis/_user-response-body.adoc[]
:login_response!:

==== Response Cookies

[.api]
[field]#access_token# [type]#[String]#::
The encoded access token. This cookie is written in the response as an HTTP Only session cookie.

[field]#refresh_token# [type]#[String]#::
The refresh token. This cookie is written in the response as an HTTP only persistent cookie. The cookie expiration is configured in the JWT
configuration for the application or the global JWT configuration.

== Authenticate a User with a one time password

This API is used to login using a One Time Password that has been returned from the Change Password API. The login request is nearly identical, however the `oneTimePasswordId` will take the place of both the `loginId` and the `password` properties.

=== Request

By default, this API will require authentication when called with an [field]#applicationId#. Authentication may be disabled per Application, see [field]#application.loginConfiguration.requireAuthentication# in the link:/docs/v1/tech/apis/applications/[Application API] or navigate to [breadcrumb]#Applications -> Edit -> Security# in the user interface.


[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:lock[type=fas]] Authenticate a User
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/login#
--

==== Request Headers

[.api]
[field]#X-Forwarded-For# [type]#[String]# [optional]#Optional#::
The IP address of a client requesting authentication. If the IP address is provided it will be stored for login history of the user. It is
generally preferred to specify the IP address in the request body. If it is not provided in the request body this header value will be used
if available, the request body value will take precedence.
include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation-row-only.adoc[]

==== Request Body

[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
The Id of the Application the user is to be logged into. If this parameter is omitted the user will still be authenticated but a login
count will not be recorded for an Application.

[field]#ipAddress# [type]#[String]# [optional]#Optional#::
The IP address of the end-user that is logging into FusionAuth. If this value is omitted FusionAuth will attempt to obtain the IP address of
the client, the value will be that of the `X-Forwarded-For` header if provided or the last proxy that sent the request. The IP address will
be stored in the User login history.

[field]#oneTimePassword# [type]#[String]# [required]#Required#::
The one time password returned by the Change Password API. This value takes the place of the [field]#loginId# and the [field]#password# fields.

[field]#metaData.device.description# [type]#[String]# [optional]#Optional#::
A human readable description of the device used during login. This meta data is used to describe the refresh token that may be generated for this login request.

[field]#metaData.device.name# [type]#[String]# [optional]#Optional#::
A human readable name of the device used during login.  This meta data is used to describe the refresh token that may be generated for this login request.

[field]#metaData.device.type# [type]#[String]# [optional]#Optional#::
The type of device used during login. The following types may be specified:
+
* `BROWSER`
* `DESKTOP`
* `LAPTOP`
* `MOBILE`
* `OTHER`
* `SERVER`
* `TABLET`
* `TV`
* `UNKNOWN`
+
This meta data is used to describe the refresh token that may be generated for this login request.

[field]#noJWT# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
When this value is set to true a JWT will not be issued as part of this request. The response body will not contain the `token` or `refreshToken` fields, and the `access_token` and `refresh_token` cookies will not be written to the HTTP response.
+
This optional parameter may be helpful when performing high volume authentication requests and the JWT is not being utilized, in this scenario removing the additional latency required to issue and sign the JWT may have a measurable cumulative effect on performance.

[field]#twoFactorTrustId# [type]#[String]# [optional]#Optional#::
The Two Factor Trust identifier returned by the Two Factor Login API response. This value be may be provided to bypass the Two Factor challenge when a User has Two Factor enabled.

[source,json]
.Example Request JSON
----
include::docs/src/json/login/request-one-time-password.json[]
----

=== Response

The response for this API contains the User object.

:auth_optional:
include::docs/v1/tech/apis/_login-response-codes.adoc[]
:auth_optional!:

:login_response:
include::docs/v1/tech/apis/_user-response-body.adoc[]
:login_response!:

==== Response Cookies

[.api]
[field]#access_token# [type]#[String]#::
The encoded access token. This cookie is written in the response as an HTTP Only session cookie.

[field]#refresh_token# [type]#[String]#::
The refresh token. This cookie is written in the response as an HTTP only persistent cookie. The cookie expiration is configured in the JWT
configuration for the application or the global JWT configuration.

== Complete Two Factor Authentication

The Two Factor Login API is used to complete the authentication process when a `242` is returned by the Login API.

=== Request

Complete a login request when a User has Two Factor authentication enabled.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Complete a Two Factor Login
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/two-factor/login#
--

==== Request Headers

[.api]
[field]#X-Forwarded-For# [type]#[String]# [optional]#Optional#::
The IP address of a client requesting authentication. If the IP address is provided it will be stored for login history of the user. It is
generally preferred to specify the IP address in the request body. If it is not provided in the request body this header value will be used
if available, the request body value will take precedence.
include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation-row-only.adoc[]

==== Request Body

[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
The Id of the Application the user is to be logged into. If this parameter is omitted the user will still be authenticated but a login
count will not be recorded for an Application.

[field]#code# [type]#[String]# [required]#Required#::
The time based one time use password, also called a Two Factor verification code.

[field]#ipAddress# [type]#[String]# [optional]#Optional#::
The IP address of the end-user that is logging into FusionAuth. If this value is omitted FusionAuth will attempt to obtain the IP address
of the client, the value will be that of the `X-Forwarded-For` header if provided or the last proxy that sent the request. The IP address
will be stored in the User login history.

[field]#metaData.device.description# [type]#[String]# [optional]#Optional#::
A human readable description of the device represented by the `device` parameter.

[field]#metaData.device.lastAccessedAddress# [type]#[String]# [optional]#Optional#::
The IP address of this login request.

[field]#metaData.device.name# [type]#[String]# [optional]#Optional#::
A human readable name of the device represented by the `device` parameter.

[field]#metaData.device.type# [type]#[String]# [optional]#Optional#::
The type of device represented by the `device` parameter. The following types may be specified:
+
* `BROWSER`
* `DESKTOP`
* `LAPTOP`
* `MOBILE`
* `OTHER`
* `SERVER`
* `TABLET`
* `TV`
* `UNKNOWN`

[field]#noJWT# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
When this value is set to true a JWT will not be issued as part of this request. The response body will not contain the `token` field,
and the `access_token` and `refresh_token` cookies will not be written to the HTTP response.

[field]#trustComputer# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
When this value is set to true the response will contain a Two Factor Trust identifier. This can be used on subsequent Login requests to
allow the Two Factor challenge to be bypassed.

[field]#twoFactorId# [type]#[String]# [required]#Required#::
The two factor Id generated and returned in the response body during the initial authentication attempt.
+
The default duration of this identifier is 5 minutes. This means that you have 5 minutes to complete the request to this API after calling the Login API. Once the identifier has expired you will need to call the Login API again to restart the process.
+
This duration can be modified using the System Configuration API or in the FusionAuth UI.

[source,json]
.Example Request JSON
----
include::docs/src/json/login/two-factor/request.json[]
----

=== Response

The response for this API contains the User object.
// keep in sync with _login-response-codes.adoc

[cols="1,9a"]
.Response Codes
|===
|Code |Description

|200
|The authentication was successful. The response will contain the User object that was authenticated.

|202
|The user was authenticated successfully. The user is not registered for the application specified by `applicationId` on the request.
The response will contain the User object that was authenticated.

|203
|The user was authenticated successfully. The user is required to change their password, the response will contain the `changePasswordId` to be used
on the link:/docs/v1/tech/apis/users#change-a-users-password[Change Password] API. Since version `1.15.0`, the response will also contain a `changePasswordReason` field which can have one of the following values:

* `Administrative` - An administrator has required this user to change their password.
* `Breached` - The password has been found to have belonged to a breached dataset and must be changed, per the Reactor configuration.
* `Expired` - The password has expired, per the expiration setting in the tenant configuration.
* `Validation` - The password fails the validation rules configured in the tenant password settings.

[source,json]
.Example Response JSON
----
include::docs/src/json/login/login-change-password-response.json[]
----

|212
|The user's email address has not yet been verified. The response will contain the User object that was authenticated.

|400
|The request was invalid and/or malformed. The response will contain an link:/docs/v1/tech/apis/errors/[Errors] JSON Object with the specific errors.

|404
|The `twoFactorId` was invalid or expired. You will need to authenticate again using the link:#authenticate-a-user[Login] API. The response will be empty.

|409
|The user is currently in an action that has prevented login. The response will contain the actions that prevented login.

[source,json]
.Example Response JSON
----
include::docs/src/json/login/login-prevented-response.json[]
----

|410
|The user has expired. The response will be empty.

|421
|The `code` request parameter is not valid. The response will be empty.

|500
|There was an internal error. A stack trace is provided and logged in the FusionAuth log files. The response will be empty.

|503
|The search index is not available or encountered an exception so the request cannot be completed. The response will contain a JSON body.
|===

:login_response:
:two_factor_login_response:
include::docs/v1/tech/apis/_user-response-body.adoc[]
:login_response!:
:two_factor_login_response!:

==== Response Cookies

[.api]
[field]#access_token# [type]#[String]#::
The encoded access token. This cookie is written in the response as an HTTP Only session cookie.

[field]#refresh_token# [type]#[String]#::
The refresh token. This cookie is written in the response as an HTTP Only persistent cookie. The cookie expiration is configured in the
JWT configuration for the application or the global JWT configuration.

[field]#fusionauth.trust# [type]#[String]#::
The Two Factor Trust identifier. This value is returned when `trustComputer` was set to `true` on the request. This value can be used by
 subsequent login requests to bypass the Two Factor challenge. This cookie is written in the response as an HTTP Only persistent cookie.

== Update Login Instant

Sends a ping to FusionAuth indicating that the user has authenticated, and (optionally) automatically logged into an application.
When using FusionAuth's SSO or your own, you should call this if the user is already logged in centrally, but accesses an
application where they no longer have a session. This helps correctly track login counts, times and helps with reporting.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Update the login instant for a given User and Application
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/login/``\{userId\}/\{applicationId\}?ipAddress=\{ipAddress\}``#
--

==== Request Headers

[.api]
[field]#X-Forwarded-For# [type]#[String]# [optional]#Optional#::
The IP address of a client requesting authentication. If the IP address is provided it will be stored for login history of the user. It is
generally preferred to specify the IP address in the request body. If it is not provided in the request body this header value will be used
if available, the request body value will take precedence.
include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation-row-only.adoc[]

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The Id of the user logging in.

[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
The Id of the Application the user is logging into. If this parameter is omitted the user will still be authenticated but a login count will not be recorded for an Application.

[field]#ipAddress# [type]#[String]# [optional]#Optional#::
The IP address of the end-user that is logging into FusionAuth. If this value is omitted FusionAuth will attempt to obtain the IP address of
the client, the value will be that of the `X-Forwarded-For` header if provided or the last proxy that sent the request. The IP address will
be stored in the User login history.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#jwt-authentication[icon:id-badge[type=fas]] Update the login instant for a given User and Application using a JWT
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/login``?ipAddress=\{ipAddress\}``#
--

The `userId` is not required on the request. The `userId` and `applicationId` values will be retrieved from the identity claims in the JWT payload.

==== Request Parameters

[.api]
[field]#ipAddress# [type]#[String]# [optional]#Optional#::
The IP address of the end-user that is logging into FusionAuth. If this value is omitted FusionAuth will attempt to obtain the IP address of
the client, the value will be that of the `X-Forwarded-For` header if provided or the last proxy that sent the request. The IP address will
be stored in the User login history.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

=== Response

This API does not return a JSON response body.

[cols="1,9"]
.Response Codes
|===
|Code |Description

|200
|The update was successful.

|202
|The user exists but is not registered for the application specified by applicationId on the request.

|400
|The request was invalid and/or malformed. The response will contain an link:/docs/v1/tech/apis/errors/[Errors] JSON Object with the specific errors.

|401
|You did not supply a valid Authorization header. The header was omitted or your API key was not valid. The response will be empty. See link:/docs/v1/tech/apis/authentication/[Authentication].

|404
|The user was not found.

|500
|There was an internal error. A stack trace is provided and logged in the FusionAuth log files.

|503
|The search index is not available or encountered an exception so the request cannot be completed. The response will contain a JSON body.
|===

== Logout a User

The Logout API is intended to be used to remove the refresh token and access token cookies if they exist on the client and revoke the refresh token. This
API does nothing if the request does not contain an access token or refresh token cookies.

The refresh token is only revoked if the request contains the `refresh_token` cookie or the `refreshToken` request parameter.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Remove the `access_token` and `refresh_token` cookies if they exist on the client.
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/logout``?global=\{global\}&refreshToken=\{refreshToken\}``#
--

==== Request Cookies

[.api]
[field]#access_token# [type]#[String]# [optional]#Optional#::
The access token cookie. When this cookie available in the request it will be deleted from the client.

[field]#refresh_token# [type]#[String]# [optional]#Optional#::
The refresh token cookie. When this cookie available in the request it will be deleted from the client and revoked in FusionAuth.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Parameters

[.api]
[field]#global# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
When this value is set to true all of the refresh tokens issued to the owner of the provided refresh token will be revoked. If no refresh token is provided on the request no refresh tokens will be revoked.

[field]#refreshToken# [type]#[String]# [optional]#Optional#::
The `refresh_token` as a request parameter instead of coming in via a cookie. If provided this takes precedence over the cookie.

=== Response

This API does not return a JSON response body.

[cols="1,9"]
.Response Codes
|===
|Code |Description

|200
|The update was successful.

|500
|There was an internal error. A stack trace is provided and logged in the FusionAuth log files.
|===

== Search Login Records

[NOTE.since]
====
Available Since Version 1.7.0
====

This API allows you to search and paginate through the Login Records.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Searches for Login Records given search criteria
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/system/login-record/search``?applicationId=\{applicationId\}&start=\{start\}&end=\{end\}&userId=\{userId\}``#
--

When calling the API using a `GET` request you will send the search criteria on the URL using request parameters. In order to simplify the example URL above, not every possible parameter is shown, however using the provided pattern you may add any of the documented request parameters to the URL.

==== Request Parameters

[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the Application used to narrow the search results to logins for a particular application.

[field]#end# [type]#[Long]# [optional]#Optional#::
The end link:/docs/v1/tech/reference/data-types/#instants[instant] of the date/time range to search within.

[field]#numberOfResults# [type]#[Integer]# [optional]#Optional# [default]#defaults to `25`#::
The number of results to return from the search.

[field]#retrieveTotal# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Set this to `true` if you want the total possible results returned in the response. With a very large number of login records settings this value to `true` will increase the response time of this request.

[field]#start# [type]#[Long]# [optional]#Optional#::
The start link:/docs/v1/tech/reference/data-types/#instants[instant] of the date/time range to search within.

[field]#startRow# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The offset into the total results. In order to paginate the results, increment this value by the [field]#numberOfResults# for subsequent requests.

[field]#userId# [type]#[String]# [optional]#Optional#::
The unique Id of the User used to narrow the search results to login records for a particular user.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Searches for Login Records given search criteria
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/system/login-record/search#
--

When calling the API using a `POST` request you will send the search criteria in a JSON request body.

==== Request Body

[.api]
[field]#retrieveTotal# [type]#[Boolean]# [optional]#Optional# [default]#defaults to `false`#::
Set this to `true` if you want the total possible results returned in the response. With a very large number of login records settings this value to `true` will increase the response time of this request.

[field]#search.applicationId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the Application used to narrow the search results to logins for a particular application.

[field]#search.end# [type]#[Long]# [optional]#Optional#::
The end link:/docs/v1/tech/reference/data-types/#instants[instant] of the date/time range to search within.

[field]#search.numberOfResults# [type]#[Integer]# [optional]#Optional# [default]#defaults to `25`#::
The number of results to return from the search.

[field]#search.start# [type]#[Long]# [optional]#Optional#::
The start link:/docs/v1/tech/reference/data-types/#instants[instant] of the date/time range to search within.

[field]#search.startRow# [type]#[Integer]# [optional]#Optional# [default]#defaults to `0`#::
The offset into the total results. In order to paginate the results, increment this value by the [field]#numberOfResults# for subsequent requests.

[field]#search.userId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the User used to narrow the search results to login records for a particular user.

=== Response

The response for this API will contain all login records matching the search criteria in paginated format.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

==== Response Body

[.api]
[field]#logins# [type]#[Array]#::
The list of Login Records returned by the search.

[field]#logins``[x]``.applicationId# [type]#[UUID]#::
The unique Id of the application.

[field]#logins``[x]``.applicationName# [type]#[String]#::
The name of the application. Because the application name may be modified after the login event occurred, only the [field]#applicationId# should be considered immutable for historical purposes when identifying the application.

[field]#logins``[x]``.loginId# [type]#[String]#::
The email or username of the user. Because email or username may be modified after the login event occurred, only the [field]#userId# and the should be considered immutable for historical purposes when identifying the user.

[field]#logins``[x]``.instant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] when the login occurred.

[field]#logins``[x]``.ipAddress# [type]#[String]#::
The recorded IP address for this login record.

[field]#logins``[x]``.userId# [type]#[UUID]#::
The unique Id of the user.

[field]#total# [type]#[Long]#::
The total number of login records available. This will only be provided in the response when [field]#retrieveTotal# was set to `true` on the request.

[source,json]
.Example JSON Response
----
include::docs/src/json/login-records/search/response.json[]
----

== Export Login Records

[NOTE.since]
====
Available Since Version 1.7.0
====

This API is used to export Login Records, the response will be a compressed zip archive.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Export the Login Records matching the criteria
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/system/login-record/export``?applicationId=\{applicationId\}&start=\{start\}&end=\{end\}&userId=\{userId\}``#
--

When calling the API using a `GET` request you will send the export criteria on the URL using request parameters. In order to simplify the example URL above, not every possible parameter is shown, however using the provided pattern you may add any of the documented request parameters to the URL.


==== Request Parameters

[.api]
[field]#applicationId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the Application used to reduce the export result to logins for a particular application.

[field]#dateTimeSecondsFormat# [type]#[String]#  [optional]#Optional# [default]#defaults to **[see description]**#::
The format string used to format the date and time columns in the export result.
+
When this parameter is omitted a default format of `M/d/yyyy hh:mm:ss a z` will be used. See the https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html[DateTimeFormatter patterns] for additional examples.

[field]#end# [type]#[Long]# [optional]#Optional#::
The end link:/docs/v1/tech/reference/data-types/#instants[instant] of the date/time range to search within.

[field]#start# [type]#[Long]# [optional]#Optional#::
The start link:/docs/v1/tech/reference/data-types/#instants[instant] of the date/time range to search within.

[field]#userId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the User used to reduce the export result to logins for a particular user.

[field]#zoneId# [type]#[String]# [optional]#Optional# [default]#defaults to **[see description]**.#::
The link:/docs/v1/tech/reference/data-types#time-zone[time zone] used to adjust the stored UTC time in the export result.
+
For example:
+
[quote]
`America/Denver` or `US/Mountain`
+
&nbsp;
+
When this parameter is omitted the configured default report time zone will be used. See [field]#reportTimezone# in the link:/docs/v1/tech/apis/system/[System Configuration API].

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Export the Login Records matching the criteria
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/system/login-record/export#
--

When calling the API using a `POST` request you will send the export criteria in a JSON request body.

==== Request Body

[.api]
[field]#criteria.applicationId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the Application used to reduce the export result to logins for a particular application.

[field]#criteria.end# [type]#[Long]# [optional]#Optional#::
The end link:/docs/v1/tech/reference/data-types/#instants[instant] of the date/time range to include in the export.

[field]#criteria.start# [type]#[Long]# [optional]#Optional#::
The start link:/docs/v1/tech/reference/data-types/#instants[instant] of the date/time range to include in the export.

[field]#criteria.userId# [type]#[UUID]# [optional]#Optional#::
The unique Id of the User used to reduce the export result to logins for a particular user.

[field]#dateTimeSecondsFormat# [type]#[String]#  [optional]#Optional# [default]#defaults to **[see description]**#::
The format string used to format the date and time columns in the export result.
+
When this parameter is omitted a default format of `M/d/yyyy hh:mm:ss a z` will be used. See the https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html[DateTimeFormatter patterns] for additional examples.

[field]#zoneId# [type]#[String]# [optional]#Optional# [default]#defaults to **[see description]**#::
The link:/docs/v1/tech/reference/data-types#time-zone[time zone] used to adjust the stored UTC time in the export result.
+
For example:
+
[quote]
`America/Denver` or `US/Mountain`
+
&nbsp;
+
When this parameter is omitted the configured default report time zone will be used. See [field]#reportTimezone# in the link:/docs/v1/tech/apis/system/[System Configuration API].

=== Response

The response for this API will contain a compressed zip of the audit logs.

:success_code: 200
:success_message: pass:normal[The request was successful. The response will be a compressed archive byte stream with a `Content-Type` of `application/zip`.]
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:success_code!:
:success_message!:
