---
layout: doc
title: Status API
description: API to retrieve the status of a FusionAuth server
---

== Overview

This page contains the APIs for managing server status.

* <<Retrieve Status>>

== Retrieve Status

The Status API is used to retrieve the current status and metrics for the server. This is useful for health checks and monitoring.

=== Request

[.api-authentication]
link:authentication#no-authentication-required[icon:unlock-alt[role=green]] Return the Server Status.
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/status#
--

=== Response
The JSON response from the Status API is complex and subject to change. The specific contents of the JSON body are not documented here. If you choose to use this API for monitoring purposes you should primarily use the response code to indicate server health. If you receive a `200` you may consider FusionAuth in a healthy state. The response body is intended for use by FusionAuth support.

[cols="1,9"]
.Response Codes
|===
|Code |Description

|200
|The FusionAuth server is functioning properly

|500
|The FusionAuth server is not functioning properly. This could indicate that the database connectivity failed or one or more services within FusionAuth failed. Consult the FusionAuth link:../troubleshooting/[Troubleshooting] to learn more about the failure or contact FusionAuth support for assistance.
|===
