---
layout: doc
title: Pre 1.26 Two Factor APIs (Deprecated)
description: APIs for enabling and disabling Two Factor Authentication
---

== Overview

[WARNING.deprecated]
====
This documentation is for version 1.25 and earlier. Breaking changes were introduced to this API in 1.26. 

Do not use this API unless you are on a version of FusionAuth earlier than 1.26. You can view the link:../two-factor[current two factor documentation if you are on version 1.26 or higher].
====

* <<Enable Two Factor>>
* <<Disable Two Factor>>
* <<Send a Two Factor Code>>
* <<Generate a Secret>>

== Enable Two Factor

This API is used to enable Two Factor authentication for a single User. To use this API the User must provide a valid
Two Factor verification code.

To enable using `TextMessage` delivery, you may use the link:/docs/v1/tech/apis/two-factor#send-a-two-factor-code[Two Factor Send] API to deliver a
code to the User, the User will then provide this code as input.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Enable Two Factor Authentication
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/user/two-factor/`{userId}`#
--

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The Id of the User to enable Two Factor authentication.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

[.api-authentication]
link:/docs/v1/tech/apis/authentication#jwt-authentication[icon:id-badge[type=fas]] Enable Two Factor Authentication
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/user/two-factor#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Body

[.api]
[field]#code# [type]#[String]# [required]#Required#::
A valid Two Factor verification code. This value should be provided by the User to verify they are able to produce codes using
an application or receive them using their mobile phone.

[field]#delivery# [type]#[String]# [required]#Required#::
The User's preferred delivery for verification codes during a two factor login request.
+
The possible values are:
+
* `None`
* `TextMessage`
+
When using `TextMessage` the User will also need a valid `mobilePhone`. The User's mobile phone is not validated during this request. Because the `code` is provided on this request it is assumed the User has been able to receive a `code` on their mobile phone when setting the delivery to `TextMessage`.

[field]#secret# [type]#[String]# [optional]#Optional#::
A base64 encoded secret.
+
You may optionally use the [field]#secret# value returned by the link:/docs/v1/tech/apis/two-factor#generate-a-secret[Two Factor Secret] API instead of generating this value yourself. This value is a secure random byte array that is Base-64 encoded.
+
If you omit this field, then [field]#secretBase32Encoded# is required.

[field]#secretBase32Encoded# [type]#[String]# [optional]#Optional#::
A base32 encoded secret.
+
You may optionally use the [field]#secretBase32Encoded# value returned by the link:/docs/v1/tech/apis/two-factor#generate-a-secret[Two Factor Secret] API instead of generating this value yourself. This value is a secure random byte array that is Base-32 encoded.
+
If you omit this field, then [field]#secret# is required.


[source,json]
.Example Request JSON
----
include::../../../src/json/two-factor/request-pre-1-26.json[]
----

=== Response

[cols="1,9"]
.Response Codes
|===
|Code |Description

|200
|The request was successful. Two Factor has been enabled for the User.

|400
|The request was invalid and/or malformed. The response will contain an link:/docs/v1/tech/apis/errors/[Errors] JSON Object with the specific errors.

|401
|You did not supply a valid Authorization header. The header was omitted or your API key was not valid. The response will be empty. See link:/docs/v1/tech/apis/authentication/[Authentication].

|404
|The User does not exist. The response will be empty.

|421
|The `code` request parameter is not valid. The response will be empty.

|500
|There was an internal error. A stack trace is provided and logged in the FusionAuth log files. The response will be empty.

|503
|The search index is not available or encountered an exception so the request cannot be completed. The response will contain a JSON body.
|===

== Disable Two Factor

This API is used to disable Two Factor authentication for a single User. To use this API the User must provide a valid
Two Factor verification code.

If the User has configured `TextMessage` delivery, you may use the link:/docs/v1/tech/apis/two-factor#send-a-two-factor-code[Two Factor Send] API to deliver a
code to the User, the User will then provide this code as input.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Disable Two Factor Authentication
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/user/two-factor/`{userId}?code={code}`#
--

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The Id of the User to enable Two Factor authentication.

[field]#code# [type]#[String]# [required]#Required#::
The time based one time use password, also called a Two Factor verification code.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

[.api-authentication]
link:/docs/v1/tech/apis/authentication#jwt-authentication[icon:id-badge[type=fas]] Disable Two Factor Authentication
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/user/two-factor``?code={code}``#
--

==== Request Parameters

[.api]
[field]#code# [type]#[String]# [required]#Required#::
The time based one time use password, also called a Two Factor verification code.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

=== Response

[cols="1,9"]
.Response Codes
|===
|Code |Description

|200
|The request was successful. Two Factor has been disabled for the User.

|400
|The request was invalid and/or malformed. The response will contain an link:/docs/v1/tech/apis/errors/[Errors] JSON Object with the specific errors.

|401
|You did not supply a valid Authorization header. The header was omitted or your API key was not valid. The response will be empty. See link:/docs/v1/tech/apis/authentication/[Authentication].

|404
|The User does not exist. The response will be empty.

|421
|The `code` request parameter is not valid. The response will be empty.

|500
|There was an internal error. A stack trace is provided and logged in the FusionAuth log files. The response will be empty.

|503
|The search index is not available or encountered an exception so the request cannot be completed. The response will contain a JSON body.
|===

== Send a Two Factor Code

This API is used to send a Two Factor verification code to a User. This may be useful during Two Factor authentication if the initial
code is no longer valid. It may be also used to send a code to a User to assist in enabling or disabling Two Factor authentication.

To send a code to a User that already has Two Factor enabled, it is not required they have `TextMessage` set as their preferred delivery.
As long as the User has a mobile phone defined you may send the User a code.

This API requires that the link:/docs/v1/tech/integrations/twilio/[Twilio] integration is enabled and configured properly.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Send a Two Factor code to an existing User by Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/two-factor/send#
--

This request is intended to be used to send a Two Factor code to a User that already has enabled Two Factor authentication to assist in disabling Two Factor authentication. The User must already have Two Factor enabled and have a valid mobile phone for this to succeed.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Body

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The User Id of the User to send a Two Factor verification code. This User is expected to already have Two Factor enabled.

[source,json]
.Example Request JSON
----
include::docs/src/json/two-factor/send/request_userId-pre-1-26.json[]
----

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Send a Two Factor code to a mobile phone
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/two-factor/send#
--

This request is intended to be used to send a Two Factor code to a User to assist in enabling Two Factor authentication.

==== Request Body

[.api]
[field]#mobilePhone# [type]#[String]# [required]#Required#::
A mobile phone to send the Two Factor verification code.

[field]#secret# [type]#[String]# [required]#Required#::
The Two Factor secret used to generate a Two Factor verification code to send to the provided mobile phone.
+
You may optionally use value provided in the `secret` field returned by the link:/docs/v1/tech/apis/two-factor#generate-a-secret[Two Factor Secret] API instead of generating this value yourself.

[source,json]
.Example Request JSON
----
include::docs/src/json/two-factor/send/request-pre-1-26.json[]
----

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Send a Two Factor code to complete Two Factor Login
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/two-factor/send/`{twoFactorId}`#
--

This request is intended to send additional messages to the User's mobile phone during login.

==== Request Parameters

[.api]
[field]#twoFactorId# [type]#[String]# [required]#Required#::
The `twoFactorId` returned by the Login API.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

[.api-authentication]
link:/docs/v1/tech/apis/authentication#jwt-authentication[icon:id-badge[type=fas]] Send a Two Factor code to an authenticated User using a JWT
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/two-factor/send#
--

This request is intended to be used to send a Two Factor code to a User that already has enabled Two Factor authentication to assist
in disabling Two Factor authentication. When using JWT authentication the User's Id is retrieved from the JWT. The User must already have
Two Factor enabled and have a valid mobile phone for this to succeed.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

=== Response

:success_code: 200
:success_message: The request was successful.
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:success_code!:
:success_message!:

== Generate a Secret

This API is used to generate a new Two Factor secret for use when enabling Two Factor authentication for a User. This is provided
as a helper to assist you in enabling Two Factor authentication.

If this secret will be used with a QR code to allow the User to scan the value it will need utilize the Base32 encoded value returned in
the response.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Generate a Two Factor Secret
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/two-factor/secret#
--

[.api-authentication]
link:/docs/v1/tech/apis/authentication#jwt-authentication[icon:id-badge[type=fas]] Generate a Two Factor Secret
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/two-factor/secret#
--

=== Response

The response for this API contains the a Two Factor secret.

:never_missing:
:no_errors:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:no_errors!:
:never_missing!:

==== Response Body

[.api]
[field]#secret# [type]#[String]#::
A Base64 encoded secret that may be used to enable Two Factor authentication.

[field]#secretBase32Encoded# [type]#[String]#::
A Base32 encoded form of the provided secret. This useful if you need to provide a QR code to the User to enable Two Factor authentication.

[source,json]
.Example Response JSON
----
include::docs/src/json/two-factor/secret/response-pre-1-26.json[]
----
