---
layout: doc
title: User Comment APIs
description: APIs for creating and retrieving comments on users
---

== Overview

This page contains the APIs that are used for managing comments left by admins on user accounts.

* <<Add a Comment to a User>>
* link:#retrieve-a-users-comments[Retrieve a User's Comments]


== Add a Comment to a User

This API is used to add a User Comment to a User's account. User Comments are used to allow administrators and moderators the ability to take notes on Users.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=far]] Add a User Comment
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/user/comment#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Body

[.api]
[field]#userComment.comment# [type]#[String]# [required]#Required#::
The text of the User Comment.

[field]#userComment.commenterId# [type]#[UUID]# [required]#Required#::
The Id of the User that wrote the User Comment.

[field]#userComment.userId# [type]#[UUID]# [required]#Required#::
The Id of the User that the User Comment was written for.

[source,json]
.Example Request JSON
----
include::docs/src/json/user-comments/request.json[]
----

=== Response

The response for this API contain the User Comment that was added to the User's account.

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

==== Response Body

[.api]
[field]#userComment.comment# [type]#[String]#::
The text of the User Comment.

[field]#userComment.commenterId# [type]#[UUID]#::
The Id of the User that wrote the User Comment.

[field]#userComment.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the comment was written.

[field]#userComment.id# [type]#[UUID]#::
The Id of the User Comment.

[field]#userComment.userId# [type]#[UUID]#::
The Id of the User that the User Comment was written for.

[source,json]
.Example Response JSON
----
include::docs/src/json/user-comments/response.json[]
----


== Retrieve a User's Comments

This API is used to retrieve all of the User Comments on a User's account. User Comments are used to allow administrators and moderators the ability to take notes on Users.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red,type=far]] Retrieve all Comments for a User by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/user/comment/``\{userId\}``#
--

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The Id of the User to retrieve the User Comments for.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

=== Response

The response for this API contains all of the User Comments for the User.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

==== Response Body

[.api]
[field]#userComments# [type]#[Array]#::
The list of User Comment objects.

[field]#userComments``[x]``.comment# [type]#[String]#::
The text of the User Comment.

[field]#userComments``[x]``.commenterId# [type]#[UUID]#::
The Id of the User that wrote the User Comment.

[field]#userComments``[x]``.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the comment was written.

[field]#userComments``[x]``.id# [type]#[UUID]#::
The Id of the User Comment.

[field]#userComments``[x]``.userId# [type]#[UUID]#::
The Id of the User that the User Comment was written for.

[source,json]
.Example Response JSON
----
include::docs/src/json/user-comments/responses.json[]
----

