---
layout: doc
title: User Comment APIs
description: APIs for creating and retrieving comments on users
---

== Overview

This page contains the APIs that are used for managing comments left by admins on user accounts.

* <<Add a Comment to a User>>
* link:#retrieve-a-users-comments[Retrieve a User's Comments]
* <<Search for User Comments>>


== Add a Comment to a User

This API is used to add a User Comment to a User's account. User Comments are used to allow administrators and moderators the ability to take notes on Users.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Add a User Comment
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/user/comment#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Body

[.api]
[field]#userComment.comment# [type]#[String]# [required]#Required#::
The text of the User Comment.

[field]#userComment.commenterId# [type]#[UUID]# [required]#Required#::
The Id of the User that wrote the User Comment.

[field]#userComment.userId# [type]#[UUID]# [required]#Required#::
The Id of the User that the User Comment was written for.

[source,json]
.Example Request JSON
----
include::docs/src/json/user-comments/request.json[]
----

=== Response

The response for this API contain the User Comment that was added to the User's account.

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

==== Response Body

[.api]
[field]#userComment.comment# [type]#[String]#::
The text of the User Comment.

[field]#userComment.commenterId# [type]#[UUID]#::
The Id of the User that wrote the User Comment.

[field]#userComment.createInstant# [type]#[Long]# [deprecated]#Deprecated#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the comment was written. This was deprecated in 1.18.0. Use `insertInstant` instead.

[field]#userComment.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the comment was written.

[field]#userComment.id# [type]#[UUID]#::
The Id of the User Comment.

[field]#userComment.userId# [type]#[UUID]#::
The Id of the User that the User Comment was written for.

[source,json]
.Example Response JSON
----
include::docs/src/json/user-comments/response.json[]
----


== Retrieve a User's Comments

This API is used to retrieve all of the User Comments on a User's account. User Comments are used to allow administrators and moderators the ability to take notes on Users.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve all Comments for a User by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/user/comment/``\{userId\}``#
--

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The Id of the User to retrieve the User Comments for.

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

=== Response

The response for this API contains all of the User Comments for the User.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

==== Response Body

[.api]
[field]#userComments# [type]#[Array]#::
The list of User Comment objects.

[field]#userComments``[x]``.comment# [type]#[String]#::
The text of the User Comment.

[field]#userComments``[x]``.commenterId# [type]#[UUID]#::
The Id of the User that wrote the User Comment.

[field]#userComments``[x]``.createInstant# [type]#[Long]# [deprecated]#Deprecated#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the comment was written. This was deprecated in 1.18.0. Use `insertInstant` instead.

[field]#userComments``[x]``.id# [type]#[UUID]#::
The Id of the User Comment.

[field]#userComments``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the comment was written.

[field]#userComments``[x]``.userId# [type]#[UUID]#::
The Id of the User that the User Comment was written for.

[source,json]
.Example Response JSON
----
include::docs/src/json/user-comments/responses.json[]
----

== Search for User Comments

[NOTE.since]
====
This API has been available since 1.44.0
====

This API is used to search for User Comments and may be called using the `GET` or `POST` HTTP methods. Examples of each are provided below. The `POST` method is provided to allow for a richer request object without worrying about exceeding the maximum length of a URL. Calling this API with either the `GET` or `POST` HTTP method will provide the same search results given the same query parameters.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Search for User Comments by comment text
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/user/comment/search``?comment=\{comment\}``#
--

=== Request Parameters

:parameter_prefix:
include::docs/v1/tech/apis/_user-comment-search-request-parameters.adoc[]
:parameter_prefix!:

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Search for User Comments
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/user/comment/search#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

When calling the API using a `POST` request you will send the search criteria in a JSON request body.

=== Request Body

:parameter_prefix: search.
include::docs/v1/tech/apis/_user-comment-search-request-parameters.adoc[]
:parameter_prefix!:


=== Response

The response for this API contains the User Comments matching the search criteria in paginated format and the total number of results matching the search criteria.

:never_missing:
:never_search_error:
include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]
:never_missing!:
:never_search_error!:

==== Response Body

[.api]
[field]#total# [type]#[Integer]#::
The total number of User Comments matching the search criteria. Use this value along with the [field]#numberOfResults# and [field]#startRow# in the search request to perform pagination.

[field]#userComments# [type]#[Array]#::
The list of User Comment objects.

[field]#userComments``[x]``.comment# [type]#[String]#::
The text of the User Comment.

[field]#userComments``[x]``.commenterId# [type]#[UUID]#::
The Id of the User that wrote the User Comment.

[field]#userComments``[x]``.id# [type]#[UUID]#::
The Id of the User Comment.

[field]#userComments``[x]``.insertInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types#instants[instant] when the comment was written.

[field]#userComments``[x]``.userId# [type]#[UUID]#::
The Id of the User that the User Comment was written for.

[source,json]
.Example Response JSON
----
include::docs/src/json/user-comments/search-response.json[]
----

