---
layout: doc
title: WebAuthn APIs
description: APIs for starting and completing WebAuthn ceremonies and retrieving, importing and deleting WebAuthn passkeys
---

include::docs/v1/tech/shared/_advanced-edition-blurb.adoc[]

== Overview

[NOTE.since]
====
This API has been available since 1.41.0
====

This page contains all of the APIs for managing WebAuthn passkeys, sometimes referred to as credentials, and starting and completing WebAuthn ceremonies.

The following APIs are provided to manage WebAuthn passkeys.

* <<Retrieve a Passkey>>
* <<Delete a Passkey>>
* <<Import Passkeys>>

=== WebAuthn Ceremonies
* <<WebAuthn JavaScript API Binary Format>>

==== WebAuthn Registration Ceremony
* <<Start a WebAuthn Passkey Registration>>
* <<Complete a WebAuthn Passkey Registration>>

==== WebAuthn Authentication Ceremony
* <<Start a WebAuthn Passkey Assertion or Authentication>>
* <<Complete a WebAuthn Passkey Authentication>>
* <<Complete a WebAuthn Passkey Assertion>>

== Retrieve a Passkey

This API is used to retrieve information about a single WebAuthn passkey or all of a user's registered passkeys.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve a single Passkey by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/webauthn/`\{id\}`#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Parameters

[.api]
[field]#id# [type]#[UUID]# [required]#Required#::
The unique Id of the WebAuthn passkey to retrieve.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve all Passkeys belonging to a User
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/webauthn/``?userId=\{userId\}``#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The unique Id of the User to retrieve WebAuthn passkeys for.

=== Response

The response for this API contains either a single Passkey or all of the Passkeys belonging to a User. When you call this API with an Id, the response will contain just that Passkey. When you call this API without an Id and provide a User Id in the query string, the response will contain all of the Passkeys belonging to that User. Both response types are defined below along with an example JSON response.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/_webauthn-response-body.adoc[]

include::docs/v1/tech/apis/_webauthns-response-body.adoc[]

== Delete a Passkey

This API is used to delete a single WebAuthn passkey or all of a user's registered passkeys.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Delete a single Passkey by Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/webauthn/`\{id\}`#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Parameters

[.api]
[field]#id# [type]#[UUID]# [required]#Required#::
The unique Id of the WebAuthn passkey to delete.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Delete all Passkeys belonging to a User
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/webauthn/``?userId=\{userId\}``#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The unique Id of the User to delete WebAuthn passkeys for.

=== Response

This API does not return a JSON response body.

include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]

== Import Passkeys

This API is used to bulk import multiple passkeys into FusionAuth. Reasonable defaults are provided for optional fields. This request is useful for migrating data from an existing database into FusionAuth.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Import Multiple Passkeys
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/webauthn/import#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-required.adoc[]

include::docs/v1/tech/apis/_import-webauthn-request-body.adoc[]

=== Response

Only a status code is available on the Import API, no JSON body will be returned.

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

== WebAuthn JavaScript API Binary Format
The https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] `navigator.credentials.create()` and `navigator.credentials.get()` expect to receive fields containing binary data on the `options` object as a JavaScript https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer[``ArrayBuffer``] and will return binary fields as ``ArrayBuffer``s. In order to prevent encoding issues on the FusionAuth API, these fields are passed over the network as base64url-encoded strings.

Select fields on the `options` JSON object that is passed to the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] must be converted from base64url-encoded strings to ``ArrayBuffer``s after receiving `options` from the FusionAuth API. Likewise, certain fields on https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] responses must be converted from ``ArrayBuffer``s to base64url-encoded strings before calling FusionAuth's APIs to complete the ceremony.

=== Converting base64url-encoded String to `ArrayBuffer`
Converting a base64url-encoded strings to ``ArrayBuffer``s is required before the `options` JSON object from <<Start a WebAuthn Passkey Registration>> or <<Start a WebAuthn Passkey Assertion or Authentication>> responses are passed to the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API]. The FusionAuth hosted pages will perform this conversion as necessary. If you need to perform this conversion yourself, you can use the following JavaScript function.

[source,javascript]
.Function to convert a base64url-encoded string to an `ArrayBuffer`
----
include::docs/src/webauthn/base64url-to-buffer.js[]
----

Fields that require this conversion are documented in the <<Start a WebAuthn Passkey Registration>> and <<Start a WebAuthn Passkey Assertion or Authentication>> response sections.

=== Converting `ArrayBuffer` to base64url-encoded String
Converting ``ArrayBuffer``s to base64url-encoded strings is required before the responses from the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript APIs] are sent to FusionAuth's <<Complete a WebAuthn Passkey Registration>>, <<Complete a WebAuthn Passkey Authentication>>, or <<Complete a WebAuthn Passkey Assertion>> APIs. The FusionAuth hosted pages will perform this conversion as necessary. If you need to perform this conversion yourself, you can use the following JavaScript function.

[source,javascript]
.Function to convert an `ArrayBuffer` to a base64url-encoded string
----
include::docs/src/webauthn/buffer-to-base64url.js[]
----

Fields that require this conversion are documented in the <<Complete a WebAuthn Passkey Registration>>, <<Complete a WebAuthn Passkey Authentication>>, and <<Complete a WebAuthn Passkey Assertion>> request sections.

== Start a WebAuthn Passkey Registration

This API is used to start a WebAuthn registration ceremony by providing some details about the current user and the new passkey. The response is a JSON object which is suitable to be passed to the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] `navigator.credentials.create()` function and includes a one-time challenge unique to the current registration ceremony.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Start a WebAuthn Registration Ceremony and Retrieve Passkey Creation Options
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/webauthn/register/start#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

include::docs/v1/tech/apis/_webauthn-register-start-request-body.adoc[]

=== Response

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

include::docs/v1/tech/apis/_webauthn-register-start-response-body.adoc[]

== Complete a WebAuthn Passkey Registration

This API is used to complete a WebAuthn registration ceremony by providing the values returned from the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] call. The API will validate the request against configured passkey requirements for the workflow and the one-time challenge generated and returned by <<Start a WebAuthn Passkey Registration>>.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Complete a WebAuthn Registration Ceremony and Return Passkey Details
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/webauthn/register/complete#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

include::docs/v1/tech/apis/_webauthn-register-complete-request-body.adoc[]

=== Response

:omit_missing_header:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:omit_missing_header!:

include::docs/v1/tech/apis/_webauthn-response-body.adoc[]

== Start a WebAuthn Passkey Assertion or Authentication

This API is used to start a WebAuthn authentication ceremony by providing some details about the current user and the new passkey. The response is a JSON object which is suitable to be passed to the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] `navigator.credentials.get()` function and includes a one-time challenge unique to the current ceremony. This same API is used to start a WebAuthn assertion that validates a passkey signature without authenticating the user.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Start a WebAuthn Authentication Ceremony and Retrieve Passkey Request Options
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/webauthn/start#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

include::docs/v1/tech/apis/_webauthn-authenticate-start-request-body.adoc[]

=== Response

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

include::docs/v1/tech/apis/_webauthn-authenticate-start-response-body.adoc[]

== Complete a WebAuthn Passkey Authentication
This API is used to complete a WebAuthn authentication ceremony by providing the values returned from the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] call. The API will validate the request against configured passkey requirements for the workflow and the one-time challenge generated and returned by <<Start a WebAuthn Passkey Assertion or Authentication>>.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Complete a WebAuthn Authentication Ceremony
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/webauthn/login#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Cookies

[.api]
[field]#fusionauth.trust# [type]#[String]# [optional]#Optional#::
The Multi-Factor Trust identifier returned by the Multi-Factor Login API response. This value may be provided to bypass the Multi-Factor challenge when a User has Multi-Factor enabled. When this cookie exists on the request it will take precedence over the [field]#twoFactorTrustId# if provided in the request body.

include::docs/v1/tech/apis/_webauthn-authenticate-complete-request-body.adoc[]

=== Response
The response for this API contains the User object.

include::docs/v1/tech/apis/_login-response-codes.adoc[]

:login_response:
include::docs/v1/tech/apis/_user-response-body.adoc[]
:login_response!:

== Complete a WebAuthn Passkey Assertion
This API is used to validate a WebAuthn authentication ceremony by providing the values returned from the https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API[WebAuthn JavaScript API] call, but it does not authenticate the user. This API can be used to confirm that a user has access to a particular passkey without authenticating them.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#no-authentication-required[icon:unlock[type=fas]] Assert a WebAuthn Authentication Ceremony
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/webauthn/assert#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

include::docs/v1/tech/apis/_webauthn-authenticate-complete-request-body.adoc[]

=== Response
The response for this API contains the WebAuthn passkey used to complete the assertion.

:omit_missing_header:
include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]
:omit_missing_header!:

include::docs/v1/tech/apis/_webauthn-response-body.adoc[]
