---
layout: doc
title: WebAuthn APIs
description: APIs for starting and completing WebAuthn ceremonies and retrieving, importing and deleting WebAuthn passkeys
---

== Overview

This page contains all of the APIs for managing WebAuthn passkeys, sometimes referred to as credentials, and starting and completing WebAuthn ceremonies.

The following APIs are provided to manage WebAuthn passkeys.

* <<Retrieve a Passkey>>

== Retrieve a Passkey

This API is used to retrieve information about a single WebAuthn passkey or all of a user's registered passkeys.

=== Request

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve a single Passkey by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/webauthn/`\{id\}`#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Parameters

[.api]
[field]#id# [type]#[UUID]# [required]#Required#::
The unique Id of the WebAuthn passkey to retrieve.

[.api-authentication]
link:/docs/v1/tech/apis/authentication#api-key-authentication[icon:lock[type=fas]] Retrieve all Passkeys belonging to a User
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/webauthn/``?userId=\{userId\}``#
--

include::docs/v1/tech/apis/_x-fusionauth-tenant-id-header-scoped-operation.adoc[]

==== Request Parameters

[.api]
[field]#userId# [type]#[UUID]# [required]#Required#::
The unique Id of the User to retrieve WebAuthn passkeys for.

=== Response

The response for this API contains either a single Passkey or all of the Passkeys belonging to a User. When you call this API with an Id, the response will contain just that Passkey. When you call this API without an Id and provide a User Id in the query string, the response will contain all of the Passkeys belonging to that User. Both response types are defined below along with an example JSON response.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/_application-response-body.adoc[]

include::docs/v1/tech/apis/_applications-response-body.adoc[]