FusionAuth supports SAML both as a SAML Identity Provider (IdP) and as a Service Provider (SP). The SP implementation has certain limitations. 

Version `2.0` is supported; other SAML versions are unsupported.

FusionAuth supports the following [field]#NameID format# values by default:

* `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`
* `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`

You may also provide your own format name. To determine the correct value, please examine the supported values of the software package for which you are configuring FusionAuth as the SP.

Map between SAML claims and user claims using a link:/docs/v1/tech/lambdas/samlv2-response-reconcile[reconcile lambda] or link:/docs/v1/tech/identity-providers/samlv2/[FusionAuth SAMLv2 Identity Provider configuration].

[NOTE]
====
Prior to version 1.28, FusionAuth only supported using the name Id for the user's email address. 
====

FusionAuth supports the following SAMLv2 bindings:

* HTTP Redirect 
* HTTP POST

Other bindings are not supported.

