---
layout: passport-doc
title: Search Engine Installation
description: Install the Passport Search Engine bundle.
---

== Overview

This guide will assist you with installing Passport Search Engine on your own server running Linux, Mac OS, or Windows. The search engine
is required by Passport and provides full text search. This service may be horizontally scaled by using Elastic Search clustering.

== Download the Packages

Log into your https://www.inversoft.com/account[Inversoft account] and click Download. Find the Passport Search Engine package for your target platform.

== Red Hat

To install on a Red Hat based system, use the RPM bundle. Execute this command to install the Passport Search Engine RPM (replace `<version>` with
 the correct version number):
[source,shell]
----
$ sudo rpm -i passport-search-engine<version>.rpm
----

== Debian

To install on a Debian based system, use the DEB bundle. Execute this command to install the Passport Search Engine DEB (replace `<version>` with
 the correct version number):

[source,shell]
----
$ sudo dpkg -i passport-search-engine<version>.deb
----

== Mac OS X

To install on Mac OS use the ZIP bundle. Extract the Passport Search Engine ZIP file anywhere on the file system. Remember where you extract the file.
 This location will be referred to as `PASSPORT_HOME`. We suggest extracting this file to a directory such as `/usr/local/inversoft`.

Once the zip bundle has been extracted, the directory structure should look similar to this. If you installed somewhere other the default `PASSPORT_HOME`,
 your directory structure will be different, this is only for shown as an example.

[source,shell]
----
/usr/local/inversoft/config
/usr/local/inversoft/config/keystore
/usr/local/inversoft/config/passport.properties
/usr/local/inversoft/passport-search-engine
----

== Windows

To install on Windows use the ZIP bundle. Extract the Passport Search Engine ZIP file anywhere on the file system. Remember where you extract
 the file. This location will be referred to as `PASSPORT_HOME`. We suggest extracting this file to a directory such as `C:\inversoft` on Windows.

Once the zip bundle has been extracted, the directory structure should look similar to this. If you installed somewhere other the default `PASSPORT_HOME`,
 your directory structure will be different, this is only for shown as an example.

[source,shell]
----
C:\inversoft\config
C:\inversoft\config\keystore
C:\inversoft\config\passport.properties
C:\inversoft\passport-search-engine\
----

Next, install the Windows service by changing to the directory designated as `PASSPORT_HOME` and then running the install command.

[source,shell]
----
C:\> cd C:\inversoft\passport-search-engine\elasticsearch\bin
C:\inversoft\passport-search-engine\elasticsearch\bin> PassportSearchEngine.exe /install
----

== Configuration

If you will be running more than one search engine service, or the search engine is installed on a separate server than the Passport Backend service,
you will need to modify the default configuration in the `passport.properties` file.

If you have installed the Search Engine service on the same server that is running Passport Backend no further configuration is required.

Each server running the Passport Search Engine service will need to be added to the configuration. To do this, you will need to edit the
`passport.properties` configuration file. More information about this configuration file is located in the link:../reference/configuration[Configuration Reference] section.

The following examples assume that Passport Backend and Passport Search Engine can communicate either on `localhost` if running on the same
system, or if running on separate systems that a site local connection exists between both servers. If you require communication between
Passport Backend and Passport Search Engine on a public IP address, you will also need to modify the `passport-search-engine.hosts` property
on the server running Passport Search Engine. The default value will only bind to localhost and site local IP addresses. See the
link:../reference/configuration[Configuration Reference] for more information on configuring the `passport-search-engine.hosts` property.

The following examples also assume the default port as specified by the `passport-search-engine.transport-port` property. If this value has been
modified, adjust the examples accordingly.


=== Example Configuration 1
The following is an example where Passport Search Engine is running on the same server as Passport Backend. This is the default configuration,
if this is how you have your system configured, no change to `passport.properties` is required.

[source,ini]
.passport.properties
----
passport-search-engine.servers=localhost:9020
----


=== Example Configuration 2
The following is an example where the Passport Search Engine is running on a separate system than the Passport Backend and the Passport
Search Engine has an IP Address of `192.168.1.41`.

We'll refer to the server running Passport Backend as System 1, and the server running Passport Search Engine as System 2.

[source,ini]
.passport.properties on System 1
----
passport-search-engine.servers=192.168.1.41:9020
----

[source,ini]
.passport.properties on System 2
----
passport-search-engine.servers=localhost:9020
----

=== Example Configuration 3
The following is an example where Passport Search Engine is running on the same server as Passport Backend, and another server also has
both the Passport Backend and the Passport Search Engine installed.

We will refer to these systems as System 1 and System 2, where System 1 has an IP address of `192.168.1.41` and System 2 has an IP address
of `192.168.1.42`.


[source,ini]
.passport.properties on System 1
----
passport-search-engine.servers=localhost:9020,192.168.1.42:9020
----

[source,ini]
.passport.properties on System 2
----
passport-search-engine.servers=localhost:9020,192.168.1.41:9020
----

== Start Passport Search Engine

Passport Search Engine should now be ready to run. Use the instructions below to start Passport Search Engine. The search engine should be started
first before the Passport Backend service.

[source,shell]
.Linux (RPM or DEB package)
----
$ sudo service passport-search-engine start
----

[source,shell]
.Mac OS X (ZIP package)
----
$ <PASSPORT_HOME>/passport-search-engine/elasticsearch/bin/elasticsearch -d
----

[source,shell]
.Windows (ZIP package)
----
C:\inversoft\passport-search-engine\elasticsearch\bin>elasticsearch.bat
----

[source,shell]
.Windows Service
----
C:\> net start PassportSearchEngine
----
