---
layout: doc
title: Theme Localization
description: FusionAuth Themes Localization
---

:sectnumlevels: 0

== Overview

The FusionAuth theme can be localized to better server your end users. In each theme you may specify one to many language specific message bundles to translate text rendered in a theme into a user's preferred language. 

If you're just looking into localizing your theme, take a look at our https://github.com/FusionAuth/fusionauth-localization[community provided and maintained message bundles].

You may also want to review our link:/docs/v1/tech/core-concepts/localization-and-internationalization[localization and internationalization documentation].

== Messages

In the Messages tab of your theme editor you may specify one to many languages. Once you have specified a key and value the key may be used in any template to display a localized string.

Consider the following message bundle and theme usage example with English and German messages defined.


.English
```properties
greeting=Good day
```

.German
```properties
greeting=Guten Tag
```

.Template
```html
<p>${theme.message('greeting')}</p>
```

If I have selected German as my locale, I will be greeted with `Guten Tag` rendered on the page, if I have English selected I will instead find the greeting `Good day`.

== Locale

The locale is determined by the link:/docs/v1/tech/reference/data-types/#locales[locale] value.  The locale is resolved on each request using the following precedence:

include::docs/v1/tech/shared/_locale_precedence.adoc[]

