---
layout: doc
title: Theme Localization
description: FusionAuth Themes Localization
---

== Overview

The FusionAuth theme can be localized to better server your end users. In each theme you may specify one to many language specific message bundles to translate text rendered in a theme into a user's preferred language. 

If you're just looking into localizing your theme, take a look at our https://github.com/FusionAuth/fusionauth-localization[community provided and maintained message bundles].

You may also want to review our link:/docs/v1/tech/core-concepts/localization-and-internationalization[localization and internationalization documentation].

* <<Messages>>
* <<Locale>>
* <<Identity Provider Login Buttons>>

== Messages

In the Messages tab of your theme editor you may specify one to many languages. Once you have specified a key and value the key may be used in any template to display a localized string.

Consider the following message bundle and theme usage example with English and German messages defined.

[source,properties]
.English
----
greeting=Good day
----

[source,properties]
.German
----
greeting=Guten Tag
----

[source,html]
.Template
----
<p>${theme.message('greeting')}</p>
----

If I have selected German as my locale, I will be greeted with `Guten Tag` rendered on the page, if I have English selected I will instead find the greeting `Good day`.

== Locale

The locale is determined by the link:/docs/v1/tech/reference/data-types#locales[locale] value.  The locale is resolved on each request using the following precedence:

include::docs/v1/tech/shared/_locale_precedence.adoc[]

== Identity Provider Login Buttons

The button text displayed in the login pages for identity providers such as Google, Facebook or SAML, is retrieved from the identity provider configuration. The link:/docs/v1/tech/apis/identity-providers/google[API documentation] documents how to set and retrieve this value, which is `identityProvider.buttonText`.

This text is used in the default theme like so:

[source,html]
.Login Template Excerpt
----
<div class="text">${identityProvider.lookupButtonText(clientId)?trim}</div>
----

The `buttonText` value stored in the identity provider configuration cannot be localized. 

However, you can replace this line in the theme template to pull a localized value from the messages bundle.

First, add the translated text to all messages bundles, including the default bundle:

[source,properties]
.English
----
google-login=Login With Google
----

[source,properties]
.German
----
google-login=Mit Google Einloggen
----

Then, update the relevant templates to display the localized text. Here's an excerpt of an updated login page:

[source,html]
.Updated Login Template Excerpt
----
<div class="text">${theme.message('google-login')}</div>
----

