---
layout: doc
title: Theme Template Variables
description: Detailed documentation about the theme template variables.
---
:page-liquid:

== Overview

Template variables are provided to allow intelligent customization of theme templates. You can use Freemarker to display, hide, or otherwise logically modify what your end users sees based on these values.

Each template has different variables that are available to it. These variables can be used in the template to help with rendering the HTML. There are also a couple of common variables that are available in all of the pages. The common variables and the page specific variables are all listed below.

By default FusionAuth will provide HTML escaping on all values rendered in HTML, this protects you from script injection attacks. If you find a value that is being incorrectly escaped you may need to utilize the FreeMarker built in for no-escape `?no_esc`.

* <<Common Variables>>
* <<Template Specific Variables>>
{% include docs/_theme_variables_toc.liquid %}


// don't update these variables directly.
// update site/_date/templates.yaml (further instructions there)
// update the JSON files in site/docs/src/json/themes/ with the new theme template key
// touch this file to regenerate (if in dev mode)
// that's it. the API and the theme form page will be automatically updated.


== Common Variables

[.api]
[field]#application# [type]#[Application]#::
The application resolved by the provided [field]#client_id# provided on the request. If the request was made without a [field]#client_id# then this variable will be undefined. Ensure you reference it using a null safe strategy if you are using some of the themed pages without a [field]#client_id#.

[field]#client_id# [type]#[String]#::
The OAuth v2.0 `client_id` parameter. This is synonymous with FusionAuth's Application Id.

[field]#currentUser# [type]#[User]# [since]#Available since 1.30.0#::
When there is an active SSO session, this variable will contain the currently logged in user. When an SSO session does not yet exist, this variable will be undefined.

[field]#errorMessages# [type]#[Array<String>]#::
A list of error messages that were generated during the processing of the request.

[field]#fieldMessages# [type]#[Map<String, List<String>>]#::
A map of field messages (usually errors) that were generated during the processing of the request. The key into the map is the name of the form field and the value is a list that contains the errors for that form field.

[field]#locale# [type]#[Locale]#::
The locale used to localize messages.
+
You can find the JavaDoc for this object available here: https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html

[field]#request# [type]#[HttpServletRequest]#::
The HttpServletRequest object that is part of the Java Servlet specification.
+
You can find the JavaDoc for this object available here: https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html

[field]#tenant# [type]#[Tenant]#::
The tenant that has been resolved for this template. This value has either been specified on the request by providing the `tenantId` request parameter or it has been resolved by other request parameters such as the `client_id`.
+
See the link:/docs/v1/tech/apis/tenants[Tenant API] for details on this object.

[field]#tenantId# [type]#[UUID]#::
The unique Tenant identifier, this is equivalent to `tenant.id`.

== Template Specific Variables

In addition to the common variables documented above, each template may have additional variables available to that only make sense in the context of this template. For example, the OAuth Authorize page (the login page) can access the `loginId` template variable, but this variable would make no sense on the email verification template.

// this is all the page specific variables, pulled from the _data/templates.yaml file
{% include docs/_theme_variables_display.liquid %}

