[cols="3a,7a"]
[.api]
.Request Body
|===
|[field]#code# [type]#[String]# [required]#Required#
|A valid Two Factor verification code. This value should be provided by the User to verify they are able to produce codes using
an application or receive them using their mobile phone.

|[field]#delivery# [type]#[String]# [required]#Required#
|The User's preferred delivery for verification codes during a two factor login request.

The possible values are:

* `None`
* `TextMessage`

When using `TextMessage` the User will also need a valid `mobilePhone`. The User's mobile phone is not validated during this request.
Because the `code` is provided on this request it is assumed the User has been able to receive a `code` on their mobile phone
when setting the delivery to `TextMessage`.

|[field]#secret# [type]#[String]# [required]#Required#
|The raw Two Factor secret used to generate the verification code provided on this request. You can technically pass in any value you want here, but in most cases, this is a randomly generate byte array that is Base-64 encoded. If you are bringing over a secret from a third-party system that is Base-32 encoded, you will want to decode that value and Base-64 encode it and pass the Base-64 encoded value in here.

You may optionally use value provided in the `secret` field returned by the link:../apis/two-factor#generate-a-secret[Two Factor Secret] API instead of generating this value yourself. This value is a random byte array that is Base-64 encoded.
|===

[source,json]
.Example Request JSON
----
include::../../../src/json/two-factor/request.json[]
----
