[cols="3a,7a"]
[.api]
.Request Body
|===
|[field]#code# [type]#[String]# [required]#Required#
|A valid Two Factor verification code. This value should be provided by the User to verify they are able to produce codes using
an application or receive them using their mobile phone.

|[field]#delivery# [type]#[String]# [required]#Required#
|The User's preferred delivery for verification codes during a two factor login request.

The possible values are:

* `None`
* `TextMessage`

When using `TextMessage` the User will also need a valid `mobilePhone`. The User's mobile phone is not validated during this request.
Because the `code` is provided on this request it is assumed the User has been able to receive a `code` on their mobile phone
when setting the delivery to `TextMessage`.

|[field]#secret# [type]#[String]# [required]#Required#
|The Two Factor secret used to generate the verification code provided on this request.

You may optionally use value provided in the `secret` field returned by the link:../apis/two-factor#generate-a-secret[Two Factor Secret] API
instead of generating this value yourself.
|===

[source,json]
.Example Request JSON
----
include::../../../src/json/two-factor/request.json[]
----
