---
layout: doc
title: API Authentication
description: Learn how the Passport APIs authenticate requests
---

== API Key Authentication

When an API is marked with a red locked icon such as &nbsp;&nbsp;icon:lock[role=red] it means you are required to provide authentication.
Passport primarily controls access to the API through the use of an API key. All secured APIs by default all APIs will return an `401 Unauthorized` response.

To enable access to a secured API create one or more API keys in the Passport backend management interface. The API key is then supplied in the HTTP
 request using the Authorization header.  See API Keys for more information on adding additional keys.

[.example]
--
The following example demonstrates the HTTP Authorization header with an API key of `2524a832-c1c6-4894-9125-41a9ea84e013`.
[source,properties]
----
Authorization: 2524a832-c1c6-4894-9125-41a9ea84e013
----
--

[.example]
--
The following is a cURL example using the Authorization header using the same API key as above with line breaks and spaces for readability.
[source,shell]
----
curl -H 'Authorization: 2524a832-c1c6-4894-9125-41a9ea84e013'
     https://example-passport.inversoft.io/api/user?email=user@example.com
----
--

== JWT Authentication

When an API is marked with a green identity icon such as &nbsp;&nbsp;icon:id-badge[role=green, title="Supports JWT"]it means you may call this API without
 an API key but instead provide a JSON Web Token (JWT) pronounced "jot". These APIs may be called with a signed token in place of an API key. A JWT is
 obtained from the Login API. The token will also be provided as an HTTP Only Session cookie. If cookies are being managed for you by the browser or some
 other RESTful client, the JWT cookie will automatically be send to Passport on your behalf and you may omit the `Authorization` header.

=== Authorization Header Examples

[.example]
--
The following example demonstrates the HTTP JWT Authorization header.
[source,properties]
----
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0ODUxNDA5ODQsImlhdCI6MTQ4NTEzNzM4NCwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiIyOWFjMGMxOC0wYjRhLTQyY2YtODJmYy0wM2Q1NzAzMThhMWQiLCJhcHBsaWNhdGlvbklkIjoiNzkxMDM3MzQtOTdhYi00ZDFhLWFmMzctZTAwNmQwNWQyOTUyIiwicm9sZXMiOltdfQ.Mp0Pcwsz5VECK11Kf2ZZNF_SMKu5CgBeLN9ZOP04kZo
----
--

[.example]
--
The following is a cURL example using the JWT Authorization header with a line break and spaces for readability.
[source,shell]
----
curl -H 'Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0ODUxNDA5ODQsImlhdCI6MTQ4NTEzNzM4NCwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiIyOWFjMGMxOC0wYjRhLTQyY2YtODJmYy0wM2Q1NzAzMThhMWQiLCJhcHBsaWNhdGlvbklkIjoiNzkxMDM3MzQtOTdhYi00ZDFhLWFmMzctZTAwNmQwNWQyOTUyIiwicm9sZXMiOltdfQ.Mp0Pcwsz5VECK11Kf2ZZNF_SMKu5CgBeLN9ZOP04kZo'
     https://example-passport.inversoft.io/api/user
----
--

=== Cookie Example

[.example]
--
The following is an HTTP GET request with the JWT Access Token provided as a cookie.
[source,shell]
----
GET /api/user HTTP/1.1
Cookie: access_code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0ODUxNDA5ODQsImlhdCI6MTQ4NTEzNzM4NCwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiIyOWFjMGMxOC0wYjRhLTQyY2YtODJmYy0wM2Q1NzAzMThhMWQiLCJhcHBsaWNhdGlvbklkIjoiNzkxMDM3MzQtOTdhYi00ZDFhLWFmMzctZTAwNmQwNWQyOTUyIiwicm9sZXMiOltdfQ.Mp0Pcwsz5VECK11Kf2ZZNF_SMKu5CgBeLN9ZOP04kZo
----
--

== No Authentication Required

When an API that is marked with an unlocked icon such as &nbsp;&nbsp; icon:unlock-alt[role=green, title="No authentication required"] it means that you are not
 required to provide an `Authorization` header as part of the request. The API is either designed to be publicly accessible or the request may take a parameter that is itself secure.