---
layout: doc
title: Consent APIs
description: APIs for creating, retrieving, updating and deleting families
---

== Overview

[NOTE.since]
====
This API has been available since 1.7.0
====

[WARNING]
====
This API is in technical preview and is subject to change.
====

A FusionAuth Consent is a definition of a permission that can be given to a User. At a minimum a consent has a name, and defines the minimum age of self-consent. A consent can then be granted to a User from a family member or optionally a User may self-consent if they meet the minimum age defined by the consent.

The first API allows you to create, delete, update and retrieve a consent. The FusionAuth Consent is the object that defines the consent, the values, minimum ages, etc.

* <<Create a Consent>>
* <<Retrieve a Consent>>
* <<Update a Consent>>
* <<Delete a Consent>>

The second API is the User Consent API, this API allows you to grant consent, revoke consent and update a consent on a User.

* <<Grant a User Consent>>
* <<Revoke a User Consent>>
* <<Update a User Consent>>


== Create a Consent

This API is used to create a new Consent.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red]] Create a new Consent with a randomly generated Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/consent#
--

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red]] Create a new Consent with the provided unique Id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/consent/`\{consentId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#consentId# [type]#[UUID]# [optional]#Optional# [default]#defaults to secure random UUID#
|The Id to use for the new Consent. If not specified a secure random UUID will be generated.
|===

include::docs/v1/tech/apis/_consent-request-body.adoc[]

=== Response

The response for this API contains the Consent that was created.

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

include::docs/v1/tech/apis/_consent-response-body.adoc[]

== Retrieve a Consent

This API is used to retrieve a single Consent by unique Id or all of the configured Consents.

=== Request

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red]] Retrieve all of the Consents
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/consent#
--

[.api-authentication]
link:authentication#api-key-authentication[icon:lock[role=red]] Retrieve a Consent by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/consent/`\{consentId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#consentId# [type]#[UUID]# [required]#Required#
|The unique Id of the Consent to retrieve.
|===

=== Response

The response for this API contains either a single Consent or all of the Consents. When you call this API with an Id the response will contain a single Consent. When you call this API without an Id the response will contain all of the Consents. Both response types are defined below along with an example JSON response.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/_consent-response-body.adoc[]

include::docs/v1/tech/apis/_consents-response-body.adoc[]

== Update a Consent

== Delete a Consent

== Grant a User Consent

== Revoke a User Consent

== Update a User Consent