---
layout: doc
title: Error API Response
description: Learn about the error response that is sent back from Passport APIs
---

== Errors

When Passport encounters an error or finds validation errors in your request, an Errors object is returned in the response body. The Errors object is defined as follows, where [field-code]#fieldName# indicates the field in the request body the message is describing and [field-code]#[x]# indicates the value is part of an array of one or more values.

[cols="3a,7a"]
[.api]
|===
|[field]#generalErrors# [type]#[Array]#
|The list of general error messages.

|[field]#generalErrors``[x]``.code# [type]#[String]#
|The code of the error message.

|[field]#generalErrors``[x]``.message# [type]#[String]#
|A descriptive error message that details the problem that occurred.

|[field]#fieldErrors# [type]#[Object]#
|The list of field error message.

|[field]#fieldErrors``[fieldName]``# [type]#[Array]#
|The list of error messages for that field

|[field]#fieldErrors``[fieldName][x]``.code# [type]#[String]#
|The code of the error message.

|[field]#fieldErrors``[fieldName][x]``.message# [type]#[String]#
|A descriptive error message that details the problem that occurred.
|===

[source,json]
.Example Errors JSON Object
----
include::docs/src/json/errors.json[]
----