---
layout: doc
title: Identity Provider APIs
description: APIs for creating, retrieving, updating and deleting identity providers
---

== Overview

An Identity Provider is a named object that provides configuration to describe an external and/or social identity provider. This configuration will be used to perform an alternative login to the standard FusionAuth local login. FusionAuth current supports a number of different identity provider types:

* <<Facebook>>
* <<Google>>
* <<Twitter>>
* <<Generic OpenId Connect>>
* <<API only via JWTs>>

The type of the identity provider will determine the objects properties as well as the validation that is performed. A complete coverage of each identity provider type is given below.

=== Facebook

This identity provider type will use the Facebook OAuth login API. It will provide a `Login with Facebook` button on FusionAuth's login page that will leverage the Facebook login pop-up dialog. Additionally, this identity provider will call Facebook's Graph API to load additional details about the user and store them FusionAuth. Here are the user details from the Facebook's `/me` Graph API that FusionAuth stores and the User object fields they are stored in:

* `birthday` -> `birthDate`
* `email` -> `email`
* `first_name` -> `firstName`
* `last_name` -> `lastName`
* `middle_name` -> `middleName`
* `name` -> `fullName`

FusionAuth will also call Facebook's `/me/picture` API to load the user's profile image and store it as the `imageUrl` in FusionAuth.

Finally, FusionAuth will call Facebook's `/oauth/access_token` API to exchange the login token for a long-lived Facebook token. This token is stored in the `UserRegistration` object inside the `tokens` Map. This Map stores the tokens from the various identity providers so that you can use them in your application to call their APIs.

=== Google

This identity provider type will use the Google OAuth v2.0 login API. it will provide a `Login with Google` button on FusionAuth's login page that will leverage the Google login pop-up dialog. Additionally, this identity provider will call Google's `/oauth2/v3/tokeninfo` API to load additional details about the user and store them FusionAuth. Here are the user details from the Google JWT that FusionAuth stores and the User object fields they are stored in:

* `email` -> `email`
* `given_name` -> `firstName`
* `family_name` -> `lastName`
* `name` -> `fullName`
* `picture` -> `imageUrl`

FusionAuth will also store the Google `access_token` that is returned from the login pop-up dialog in the `UserRegistration` object inside the `tokens` Map. This Map stores the tokens from the various identity providers so that you can use them in your application to call their APIs.

=== Twitter

This identity provider type will use the Twitter OAuth v1.0 login API. it will provide a `Login with Twitter` button on FusionAuth's login page that will leverage the Twitter login page directly. Additionally, this identity provider will call Twitter's `/1.1/account/verify_credentials.json` API to load additional details about the user and store them FusionAuth. Here are the user details from the Twitter API that FusionAuth stores and the User object fields they are stored in:

* `/email` -> `email`
* `/name` -> `fullName`
* `/profile_image_url_https` -> `imageUrl`
* `/screen_name` -> `username` (this is stored as the `username` in the UserRegistration object since it is not unique)

Twitter does not require a user to have an email address. However, to prevent account hijacking and take-over, FusionAuth prevents users from logging in with Twitter unless they have setup an email address in their Twitter account. Keep this in mind as you enable this identity provider.

Finally, FusionAuth stores the Twitter access token that is returned from the OAuth v1.0 login workflow in the `UserRegistration` object inside the `tokens` Map. This Map stores the tokens from the various identity providers so that you can use them in your application to call their APIs.

=== Generic OpenId Connect

This identity provider type is a generic OpenId Connect login. This type of login will optionally provide a `Login with ...` button on FusionAuth's login page. This button is customizable by using different properties of the identity provider.

Optionally, this identity provider can define one or more domains it is associated with. This is useful for allowing employees to log in with their corporate credentials. As long as the company has an identity solution that provides OpenId Connect, you can leverage this feature. This is referred to as a **Domain Based Identity Provider**. If you enable domains for an identity provider, the `Login with ...` button will not be displayed. Instead, only the `email` form field will be displayed initially on the FusionAuth login page. Once the user types in their email address, FusionAuth will determine if the user is logging in locally or if they should be redirected to this identity provider. This is determined by extracting the domain from their email address and comparing it to the domains associated with the identity provider.

FusionAuth will also leverage the `/userinfo` API that is part of the OpenId Connect specification. This API provides user information that is stored in FusionAuth. Since FusionAuth is also an OpenId Connect provider, it translates most of the OpenId Connect claims over. Here are the OpenId Connect claims that FusionAuth stores from a generic OpenId Connect identity provider and the User object fields they are stored in:

* `birthdate` -> `birthDate`
* `email` -> `email`
* `family_name` -> `lastName`
* `given_name` -> `firstName`
* `locale` -> `preferredLanguages`
* `middle_name` -> `middleName`
* `name` -> `fullName`
* `phone_number` -> `mobilePhone`
* `picture` -> `imageUrl`

If the generic OpenId Connect identity provider returns a refresh token, it will be stored in the `UserRegistration` object inside the `tokens` Map. This Map stores the tokens from the various identity providers so that you can use them in your application to call their APIs.

=== API only via JWTs

This is a special type of identity provider that is only used via the link:jwt#reconcile-a-jwt[JWT Reconcile] API. This identity provider defines the claims inside the incoming JWT and how they map to fields in the FusionAuth User object.

In order for this identity provider to use the JWT, it also needs the public key or HMAC secret that the JWT was signed with. FusionAuth will verify that the JWT is valid and has not expired. Once the JWT has been validated, FusionAuth will reconcile it to ensure that the User exists and is up-to-date.

=== Operations

* <<Create an Identity Provider>>
* <<Retrieve an Identity Provider>>
* <<Update an Identity Provider>>
* <<Delete an Identity Provider>>
* <<Lookup an Identity Provider>>

== Create an Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Create an Identity Provider using the default id (described below)
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider#
--

link:authentication#api-key-authentication[icon:lock[role=red]] Create an Identity Provider with the provided unique id
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#identityProviderId# [type]#[UUID]# [optional]#Optional# [default]#see description for default#
|The Id to use for the new Identity Provider if the identity provider is not a known type. If the identity provider is a known type, then this is ignored and is replaced with one of the following values:

* Facebook - `56abdcc7-8bd9-4321-9621-4e9bbebae494`
* Google - `82339786-3dff-42a6-aac6-1f1ceecb6c46`
* Twitter - `45bb233c-0901-4236-b5ca-ac46e2e0a5a5`

If the identity provider is not a known type and an id is not provided, a secure random UUID is generated.
|===

include::docs/v1/tech/apis/_identity-provider-request-body.adoc[]

=== Response

The response for this API contains the Identity Provider that was created.

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

:response_body_title: Response Body for a single Identity Provider
include::docs/v1/tech/apis/_identity-provider-response-body.adoc[]

== Retrieve an Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Retrieve all of the Identity Providers
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider#
--

link:authentication#api-key-authentication[icon:lock[role=red]] Retrieve an Identity Provider by Id
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#identityProviderId# [type]#[UUID]# [required]#Required#
|The unique Id of the Identity Provider to retrieve.
|===

=== Response

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/_identity-provider-response-body.adoc[]

include::docs/v1/tech/apis/_identity-providers-response-body.adoc[]


== Update an Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Update an Identity Provider
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#identityProviderId# [type]#[UUID]# [required]#Required#
|The unique Id of the Identity Provider to update.
|===

include::docs/v1/tech/apis/_identity-provider-request-body.adoc[]

=== Response

The response for this API contains the Identity Provider that was updated.

include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]

:response_body_title: Response Body
include::docs/v1/tech/apis/_identity-provider-response-body.adoc[]

== Delete an Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Delete an Identity Provider by Id
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/identity-provider/`\{identityProviderId\}`#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#identityProviderId# [type]#[UUID]# [required]#Required#
|The unique Id of the Identity Provider to delete.
|===

=== Response

This API does not return a JSON response body.

include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]

=== Lookup an Identity Provider

The Lookup API is intended to be used during a federated login workflow. For example, during a login you may collect the user's email address, that address or domain
can be sent on the request to lookup which Identity Provider is managing the domain.

=== Request

link:authentication#no-authentication-required[icon:unlock-alt[role=green]] Lookup an Identity Provider by managed domain
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/lookup``?domain={domain}``#
--

[cols="3a,7a"]
[.api]
.Request Parameters
|===
|[field]#domain# [type]#[String]# [required]#Required#
|The email domain or the full email address of the user.

[block-quote]#For example, `jenny@acme.com` and `acme.com` are functionally equivalent.#
|===

=== Response

The Lookup response is a subset of the Identity Provider configuration that would be returned by the <<Retrieve an Identity Provider>>. A `200` response
code indicates the domain is managed and the response will contain a JSON body, a `404` response code indicates it is not managed by a configured Identity Provider.

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/_lookup-response-body.adoc[]