---
layout: doc
title: Status API
description: API to retrieve the status of a Passport server
---

== Retrieve the Status

The Status API is used to retrieve the current status and metrics for the server. This is useful for health checks and monitoring.

=== Request

link:authentication#no-authentication-required[icon:unlock-alt[role=green]] Return the Server Status.
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/status#
--

=== Response
The JSON response from the Status API is complex and subject to change. The specific contents of the JSON body are not documented here. If you choose to use this API for monitoring purposes you should primarily use the response code to indicate server health. If you receive a `200` you may consider CleanSpeak in a healthy state. The response body is intended for use by Inversoft support.

[cols="1,9"]
.Response Codes
|===
|Code |Description

|200
|The Passport server is functioning properly

|500
|The Passport server is not functioning properly. This could indicate that the database connectivity failed or one or more services within Passport failed. Consult the Passport link:../troubleshooting/[Troubleshooting] to learn more about the failure or contact Inversoft support for assistance.
|===
