---
layout: passport-doc
title: Event & Webhook Overview
description: An overview of the Passport Event & Webhook system
---

:sectnumlevels: 0

== Overview

Events and Webhooks are a core architecture feature of Passport. This feature provides a publish-subscribe pattern to developers and integrators of Passport. In this architecture pattern, the Webhook is the subscriber and Passport is the publisher.

This system is designed to provide feedback to your system when events occur within Passport. Events are sent via an HTTP POST using `application/json` data. This is the same style of API that the Passport Backend uses to handle API requests from your application.

See link:../apis/webhooks[Webhook APIs] and link:../tutorials/create-a-webhook[Create a Webhook] tutorial for additional  information on defining and using the Passport Webhook.

Here are the topics in this section:

* link:events[Events] - Covers all of the event types that Passport sends to Webhooks
* link:writing-a-webhook[Writing a Webhook] - Covers how to write a Webhook that will process events from Passport.
