:type: user.bulk.create
== User Bulk Create

This event is generated when multiple users are created. The JSON includes each of the Users that were created.

The final state of the operation which caused the webhook is not persisted to FusionAuth until after the webhook finishes; link:/docs/v1/tech/events-webhooks/writing-a-webhook/#calling-fusionauth-apis-in-webhooks[learn more].

[source,shell]
.Event type
[subs="attributes"]
----
{type}
----

=== Event Scope

include::../_tenant-scoped-event.adoc[]

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

include::_event-info.adoc[]

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `{type}`.

[field]#event.users# [type]#[Array<Object>]#::
The users that have been created. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.

[source,json]
.Example Event JSON
----
include::../../../../src/json/events/user-bulk-create.json[]
----