---
layout: doc
title: Provision Microsoft AKS (Azure Kubernetes Service)
description: Provision an AKS cluster in Microsoft Azure
keywords: docker kubernetes k8s container aws
---

== Overview

This guide will show you how to quickly setup an AKS cluster on Microsoft Azure. When completed, you will have a fully functional Kubernetes cluster ready to deploy FusionAuth as well as a supporting Azure Database for PostgresSQL.
The following method uses the default settings when provisioning an AKS cluster with the required resources and services. It is recommended that you consult link:https://docs.microsoft.com/en-us/azure/aks/[Azure Kubernetes Service] for full AKS documentation.

== Requirements

* A link:https://portal.azure.com/[Microsoft Azure account] with sufficient permissions to create resources.
* `az` - Azure command Line tool used to manage resources on Azure. For installation instructions, see link:https://docs.microsoft.com/en-us/cli/azure/install-azure-cli[How to install the Azure CLI].
* `kubectl` - Command line tool that interacts with the Kubernetes API server and is useful for managing Kubernetes clusters. Before proceeding, follow the installation documentation that corresponds to your platform found link:https://kubernetes.io/docs/tasks/tools/[here].
We will be using version `1.22` for this guide.

== Create an AKS cluster

=== Create a resource group

Before we create the cluster, we need to first create a link:https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview[Resource Group], a logical grouping of Azure resources. A resource group location is where resources will run by default when a region is not provided on creation.

Create a resource group.

[source,shell,title=Create a new resource group]
----
$ az group create --name fusionauthResourceGroup --location westus
----

[source,json,title=JSON output]
----
{
  "id": "/subscriptions/fa2713cf-00cf-45f1-95a4-f87c48947da1/resourceGroups/fusionauthResourceGroup",
  "location": "westus",
  "managedBy": null,
  "name": "fusionauthResourceGroup",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}
----

=== Create the cluster

[source,shell,title=Create a new AKS cluster]
----
$ az aks create \
  --resource-group fusionauthResourceGroup \
  --name fusionauthCluster --node-count 1 \
  --enable-addons monitoring \
  --generate-ssh-keys
----

* `resource-group` - The name of the resource group where the cluster will be created.
* `name` - The name of the cluster.
* `enable-addons` - The Kubernetes addons to enable.
* `generate-ssh-keys` - Generates SSH public and private key files in the ~/.ssh directory.
+
For more information on the link:https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_create[create] command, see link:https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_create[az aks create] documentation.

=== Update Kubernetes configuration

The following retrieves credentials for the newly created cluster and then configures your `~/.kube/config` file so that you can use `kubectl`.

[source,shell,title=Get access credentials and update Kubeconfig]
----
$ az aks get-credentials \
  --resource-group fusionauthResourceGroup \
  --name fusionauthCluster
----

=== Verify Cluster

Execute the link:https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_list[list] command to see AKS clusters that have been configured.

[source,shell,title=Get list of AKS clusters]
----
$ az aks list
----

We now have a fully functional provisioned AKS cluster. For good measure, view the nodes that have been created.
Use `kubectl` to make requests to the Kubernetes API Server.

[source,shell,title=Get list of nodes running on the cluster]
----
$ kubectl get nodes -o wide

NAME                                STATUS   ROLES   AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-nodepool1-13281124-vmss000000   Ready    agent   8m42s   v1.20.9   10.240.0.4    <none>        Ubuntu 18.04.6 LTS   5.4.0-1059-azure   containerd://1.4.9+azure
----

Great! We have a node in a `READY` status.

== Create a Database

For this setup, we will create a Postgres database required for FusionAuth installation.

[source,shell,title=Create a PostgreSQL flexible server]
----
$ az postgres flexible-server create \
  --resource-group fusionauthResourceGroup \
  --name fusionauth-db \
  --location westus \
  --admin-user postgres \
  --admin-password fooBarBaz2021 \
  --version 12 \
  --public-access 0.0.0.0
----

* `resource-group` - The name of the resource group where the cluster will be created.
* `name` - The name of the database.
* `location` - The location.
* `admin-user` - The database admin user.
* `admin-password` - The database admin user password.
* `version` - The version of PostgreSQL to install.
* `public-access` - Determines public access in firewall rules. `0.0.0.0` allows public access from any resources deployed in Azure.

+
For more information on the link:https://docs.microsoft.com/en-us/cli/azure/postgres/flexible-server?view=azure-cli-latest#az_postgres_flexible_server_create[create] command, see link:https://docs.microsoft.com/en-us/cli/azure/postgres/flexible-server?view=azure-cli-latest#az_postgres_flexible_server_create[az postgres flexible-server create] documentation.

Upon successful completion, the response will output a JSON object that contains important information about your newly created database.

[source,json,title=JSON output]
----
{
  "connectionString": "postgresql://postgres:foobarbaz@fusionauth-db-2.postgres.database.azure.com/postgres?sslmode=require",
  "databaseName": "flexibleserverdb",
  "firewallName": "AllowAllAzureServicesAndResourcesWithinAzureIps_2021-10-10_23-34-29",
  "host": "fusionauth-db-2.postgres.database.azure.com",
  "id": "/subscriptions/af1327fc-cf00-45f1-a22b-e78c489741ad/resourceGroups/fusionauthResourceGroup/providers/Microsoft.DBforPostgreSQL/flexibleServers/fusionauth-db-2",
  "location": "West US",
  "password": "foobarbaz",
  "resourceGroup": "fusionauthResourceGroup",
  "skuname": "Standard_D2s_v3",
  "username": "postgres",
  "version": "12"
}
----

== Next Steps

We now have all the necessary infrastructure to deploy containerized applications to AKS.

Next up, link:link:../../[Deploy FusionAuth in Kubernetes].

