---
layout: passport-doc
title: Integration APIs
description: APIs for retrieving and updating integrations
---

== Overview

This page contains the APIs that are used for retrieving and updating integrations. An integration is a third party API that has been integrated into Passport. These APIs are used to enable and configure these third party integration.

* <<Retrieve Integrations>>
* <<Update Integrations>>

== Retrieve Integrations

This API is used to retrieve integrations.

[NOTE.since]
====
Available Since Version 1.11.0
====

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Retrieve Integrations
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/integration#
--

=== Response

The response for this API contains the Integrations.

:no_errors:
:never_missing:
include::docs/passport/apis/_standard-get-response-codes.adoc[]
:never_missing!:
:no_errors!:

include::docs/passport/apis/_integration-response-body.adoc[]


== Update Integrations

This API is used to update the global System Configuration object.

[NOTE.since]
====
Available Since Version 1.11.0
====

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Update Integrations
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/integration#
--

include::docs/passport/apis/_integration-request-body.adoc[]

=== Response

The response for this API contains Integrations.

include::docs/passport/apis/_standard-post-response-codes.adoc[]

include::docs/passport/apis/_integration-response-body.adoc[]
