@startuml
  !include ../../_config.plantuml

participant "API client" as api
participant "Gateway" as gw
participant "Products" as prod
api -> gw : Request products/1
gw -> gw : Generate JWT
gw -> prod : Request products/1 + JWT
prod -> prod : Verify JWT via middleware
prod -> gw : products/1 data
gw -> api : products/1 data
@enduml
