@startuml
  !include ../../_config.plantuml

participant "API client" as api
participant "Gateway" as gw
participant "Products" as prod
api -> gw : Request branches/1/products
gw -> gw : Generate JWT
gw -> prod : Request branches/1/products + JWT
prod -> prod : Verify JWT via middleware
prod -> gw : branches/1/products data
gw -> api : branches/1/products data
@enduml
