---
layout: doc
title: Terraform
description: Manage FusionAuth configuration changes over time with Terraform.
navcategory: admin
prerequisites: FusionAuth
technology: Terraform
---

== Overview

In this section we dig deeper in the the community supported, open source https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/[FusionAuth Terraform provider] with which you will be able to manage FusionAuth using Terraform, an open source infrastructure as code automation tool.

* <<Prerequisites>>
* <<Initial Setup>>
** <<FusionAuth API Key>>
** <<Initializing Terraform Working Directory>>
* <<Terraform Import>>
** <<Terraform Data Source Instead Of Import>>
* <<Terraform Create>>
* <<Terraform Update>>
* <<Terraform Remove>>

== Prerequisites

{% include docs/integration/_prerequisites.md %}

== Initial Setup

ipsum

=== FusionAuth API Key

https://fusionauth.io/docs/v1/tech/apis/api-keys

http://fusionauth-terraform:9011/admin/api-key/
- Copy key (e.g. yqT4LSMCWDYgwbPBA_AxmXHm7_qNFT9jbOi3wL9Jr65ymNkNnFisAvjY)
- Do Not select any endpoint methods to create a super user key. A super user API Key has access to all API endpoints.
- Save

=== Initializing Terraform Working Directory

[source]
----
mkdir your.fusionauth.domain
----

[source]
----
cd your.fusionauth.domain
----

go to https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs
Click USE PROVIDER
Copy Information
create `main.tf`
Add the previously created key as api_key and host as configuration options.
Make sure host is a URL including protocol

[source]
----
terraform {
  required_providers {
    fusionauth = {
      source = "gpsinsight/fusionauth"
      version = "0.1.90"
    }
  }
}

provider "fusionauth" {
  api_key = "yqT4LSMCWDYgwbPBA_AxmXHm7_qNFT9jbOi3wL9Jr65ymNkNnFisAvjY"
  host = "https://your.fusionauth.domain"
}
----

== Terraform Import

If you have existing resources you want to manage via terraform you can import the current configuration via terraform import.
(Additional input for documentation tbd. import cli https://developer.hashicorp.com/terraform/cli/import import config https://developer.hashicorp.com/terraform/language/import https://spacelift.io/blog/importing-exisiting-infrastructure-into-terraform  https://medium.com/swlh/importing-existing-infrastructure-into-terraform-a6ae168ad2bb https://stackoverflow.com/questions/47613926/import-all-resources-defined-in-tf-file https://www.bitslovers.com/terraform-import/)

- User
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/user

- Tenant
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/tenant
why importing default tenant is good practice, to manage fusionauth application related topics it is always in the default tenant, there is not necessarily a need to create a different tenant as you create multiple applications: https://fusionauth.io/community/forum/topic/1725/what-are-the-pros-and-cons-of-using-the-default-tenant

- Application
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/application

=== Terraform Data Source Instead Of Import

Instead of importing a ressource you can use existing configuration as a Data Source

- Tenant
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/data-sources/tenant

- Application
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/data-sources/application

== Terraform Create

To create a new resource you can go through the list of ressources available to you in the provider https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs and pick the ressource you are interested in.

Each resource contains information about required and opitional arguments.

- Application
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/application

- Application Role
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/application_role

- User
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/user

- Registration
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/registration

== Terraform Update

- Tenant
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/tenant

- Application
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/application

- Application Role
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/application_role

- User
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/user

- Registration
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/registration

== Terraform Remove

- Application
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/application

- Application Role
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/application_role

- Registration
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/registration

- User
https://registry.terraform.io/providers/gpsinsight/fusionauth/latest/docs/resources/user
