@startuml
  !include ../_config.plantuml
  !include ../_mobile-participants.plantuml
  !include ../_mobile-intro.plantuml
  !include _initialize.plantuml

  == Login (inside SPA) ==
  Mobile->Store : POST /api/login
  Store->FusionAuth : POST /oauth2/token\n(grant_type=password)
  FusionAuth->Store : (Refresh Token and JWT)
  Store->Mobile : (Refresh Token and JWT)

  !include _shopping-cart-refresh-jwt-load.plantuml

  !include _shopping-cart-refresh-jwt-refresh.plantuml

  !include _shopping-cart-refresh-jwt-relogin.plantuml

  !include ../_mobile-attack-vectors.plantuml

  !include _stolen-refresh-token-refresh-jwt.plantuml

  !include _stolen-jwt-refresh-jwt.plantuml
@enduml
