---
layout: doc
title: Migration Guide
description: How to migrate your users to FusionAuth.
---
:page-liquid:

== Overview

This document assumes you have decided to migrate off of Auth0 and have chose FusionAuth as your new authentication, authorization and user management solution. It also assumes you have installed FusionAuth. If not, please link:/docs/v1/tech/installation-guide/[view the installation guide] and install FusionAuth before you begin. For more general migration guidance, please view the link:/docs/v1/tech/guides/migration/[migration guide].

There are a number of different ways you can integrate with Auth0. This document will focus on exporting your user data from an Auth0 managed user database and importing it into FusionAuth. 

You can use either the Auth0 management API or the Auth0 user interface to export your user data. This guide will use the user interface, but if you have a large number of users, using the https://auth0.com/docs/api/management/v2#!/Users/get_users[API is recommended]. Auth0 also has a https://auth0.com/docs/support/export-data[nice high level export guide] worth reviewing.

Here's a brief video walking through the export process.

video::wQklLZZP_3s[youtube,width=560,height=315]

== Exporting users

To export users using the user interface, log in and go to your dashboard. You need to follow these steps:

1. Add the Import/Export extension, if not present
2. Run the extension
3. Download the exported file

Let's walk through each of these steps.

=== Add the extension

There's a convenient extension that allows you to both import and export users. Add the extension by going to extensions, searching for it and then adding it.

The next step is to run the extension. The first time you run it, you'll be asked to grant needed permissions. 

=== Run the extension

Next, run the extension. Choose the export tab.

This will bring up a screen with information such as what fields you want to export, which connections, and the export file format.

For this guide, we'll export user information as JSON. We'll also choose the default user database. Finally, we don't have any special fields to include, but if you do, ensure you configure them.

=== Download the file

After you run the export, you will download a file. Depending on how many users you have in your database, it may take a while.

At the end of the process, you'll end up with a file like this:

[source,json,title=Sample Auth0 user data export download]
----
{"user_id":"auth0|60425da93519d90068f82966","email":"test@example.com","name":"test@example.com","nickname":"test","created_at":"2021-03-05T16:34:49.518Z","updated_at":"2021-03-05T16:34:49.518Z","email_verified":false}
{"user_id":"auth0|60425dc43519d90068f82973","email":"test2@example.com","name":"test2@example.com","nickname":"test2","created_at":"2021-03-05T16:35:16.786Z","updated_at":"2021-03-05T16:35:16.786Z","email_verified":false}
----

This is half of the data you'll need to import your users. The other is the password hashes. 

## Passwords

Password hashes are sensitive information and Auth0 correctly doesn't export them as part of the general import/export process. You must open a support ticket.

From your dashboard, navigate to support, and then open a ticket. Select the issue and details of your request.

[NOTE]
====
Auth0 requires you to be on a link:https://auth0.com/docs/support/export-data[paid plan] to export your password hashes. You cannot export them if you are on the free tier.

Auth0 makes no commitments about how long a password hash ticket will take.

Plan accordingly.
====

You'll receive an automated message after this ticket is submitted and you can view the progress on the ticket screen. 

At the end of the process, you'll recieve a JSON file containing the password hashes and user ids. It might look a little something like this:

[source,json,title=Sample Auth0 password hash export download]
----
TBD
----

TBD what hashing algorithm is used?

== Importing users

Now you have your user data and your password data. The easiest way to import your data into FusionAuth is to use a provided script from the https://github.com/FusionAuth/fusionauth-import-scripts[FusionAuth GitHub repository].

=== Set up FusionAuth

But first, let's create a tenant and do some other setup. This will be useful if you need to repeat the import process repeatedly.

Navigate to [breadcrumb]#Tenants# and choose the green plus sign.

IMAGE 

Enter any relevant information. Give it a descriptive name like Auth0 import test and save it. Note the Id, which will be something like `25c9d123-8a79-4edd-9f76-8dd9c806b0f3`.

IMAGE

Then, create an API key. Navigate to [breadcrumb]#Settings -> API Keys# in the administrative user interface.

This key needs to have the permission to run a bulk import. In the spirit of the principal of least privilege, allow it `POST` on `/api/user/import` and give it a descriptive name. Record the value, as you'll use it below.

IMAGE 

IMAGE

=== Run the script

The script requires ruby (tested with 2.7) and the FusionAuth ruby client. Please feel free to port it to any other language if you prefer. To get the script, clone the git repository

[source,shell,title=Getting the import script files]
----
git clone https://github.com/FusionAuth/fusionauth-import-scripts
----

Change into the auth0 directory:
[source,shell,title=Go to the correct directory]
----
cd fusionauth-import-scripts/auth0
----

Edit the `import.rb` script and update some key variables.

[source,ruby,title=An excerpt of the import.rb]
----
#!/usr/local/bin/ruby -w

require 'date'
require 'json'
require 'fusionauth/fusionauth_client'

# BEGIN Modify these variables for your Import
users_file = 'users.json'
secrets_file = 'secrets.json'

$fusionauth_url = 'http://localhost:9011'
$fusionauth_api_key = 'bf69486b-4733-4470-a592-f1bfce7af580'

# Optionally specify the target tenant. If only one tenant exists this is optional and the users
# will be imported to the default tenant. When more than one tenant exists in FusionAuth this is required.
$fusionauth_tenant_id = '16970284-4680-4b3c-8a7e-424644ed1090'

# Map Auth0 userId to the FusionAuth User Id as a UUID
$map_auth0_user_id = false

# END Modify these variables for your Import
----

You need to update the following variables.

* `users_file` needs to point to the location of the user export file you obtained.
* `secrets_file` needs to point to the location of the password hash export file you requested.
* `$fusionauth_url` must point to your FusionAuth instance. If you are testing locally, it may be `'http://localhost:9011'`.
* `$fusionauth_api_key` needs to be set to the value of the API you set up above.
* `$fusionauth_tenant_id` should be set to the Id of the testing tenant you created above.
* `$map_auth0_user_id` is a configuration variable you may or may not want to change. If you have external systems relying on the Auth0 user identifier, you should preserve it across your systems. FusionAuth allows you to reuse that identifier, so if you need this, change the value of this variable to `true`.

You also need to ensure the following gems are imported:

* `date`
* `json`
* `fusionauth_client`

If you have bundler installed, you can run `bundle install`, otherwise install the needed gems in whatever way you typically do.

You can now run the import script:

[source,shell,title=Running the import script]
----
ruby ./import.rb
----

You'll see output like:

[source,shell,title=Import script output]
----
TBD
----

The next step is to log in to the FusionAuth administrative interface and review the users.

IMAGE 

=== The destination tenant

After you are done testing, you can choose to import the users into the default tenant or a new tenant. 

Whichever you choose, make sure to update the `$fusionauth_tenant_id` to the correct value before running the import for a final time.

=== A fresh start

If you need to start over because the import failed or you need to tweak a setting, delete the tenant you created. 

This will remove all the users and other configuration for this tenant, giving you a fresh slate.

Navigate to [breadcrumb]#Tenants# and choose the red trashcan icon. 

IMAGE

Confirm your desire to delete the tenant. 

== Other considerations

As mentioned above, there are some other important entities that your running system may need to migrate from Auth0. There are typically fewer of these, so an automated migration may make less sense, but you need to ensure they are moved over for your system to function.

The other difficulty with these is that the functionality may not be the same. You should definitely test FusionAuth before you begin a migration to learn about these differences.

A partial list of the configuration that may need to be migrated, depending on what you use Auth0 for:

* Connections are a source of data for users. FusionAuth calls these link:/docs/v1/tech/identity-providers/[Identity Providers].
* Rules, Hooks and Actions are ways for you to customize the authentication or authorization workflow at various points. FusionAuth has a similar concept called link:/docs/v1/tech/lambdas/[Lambdas].
* APIs, Applications and SSO Integrations are things your users can log in to. They are also called Clients in the Auth0 documentation. FusionAuth refers to these as link:/docs/v1/tech/core-concepts/applications/[Applications]. Read more about the link:/docs/v1/tech/core-concepts/authentication-authorization/[difference between authentication and authorization] in FusionAuth.
* Tenants are a high level construct that groups other entities such as users and applications together. FusionAuth calls these link:/docs/v1/tech/core-concepts/tenants/[Tenants] as well.
* Roles and Permissions are ways to provide information about what your users can do in your custom or off the shelf applications. FusionAuth has link:/docs/v1/tech/core-concepts/roles/[Roles] and they are defined in the Application.

[NOTE]
====
In FusionAuth is that users are mapped to applications with a link:/docs/v1/tech/core-concepts/registrations/[Registration]. 

Auth0, in contrast, gives users access to all applications in a tenant by default. 
====

=== Universal login

Auth0 provides login pages called Universal Login. This is a complex, configurable component that works with SPAs, native applications and web applications. 

FusionAuth's login experience is less complicated. You can choose to build your own login pages or use FusionAuth's hosted login pages. link:/docs/v1/tech/core-concepts/integration-points/#login-options[Read more about these choices].

== What to do next

At a minimum, you'll need to assign your users to the relevant migrated FusionAuth applications. You'll also need to modify and test your applications to ensure that your users can log in to your applications with the appropriate permissions and roles.

You may want to review the list of link:/docs/v1/tech/example-apps/[FusionAuth Example Applications] to see if any accelerate your understanding of the changes needed to integrate. 

If your application uses a standard OAuth, SAML or OIDC library to authenticate with Auth0, the transition should be painless.

== Support

If you need support in your migration beyond what is provided in this guide, you can either:

* post in our link:/community/forums/[community forums] or
* link:/pricing/editions/[purchase a support contract]

