---
layout: doc
title: Families guide
description: What are families in FusionAuth and how are they useful?
---

The family API in FusionAuth is a powerful way to logically group family members. It also pairs nicely with the consent API to manage consents provided to children by parents.

You can review the link:/docs/v1/tech/apis/families[family API documentation] for detailed API call examples.

== Why would you use Families?

There are two main reasons you might want to use the family API. The first is to easily add family relationships to your application. You can have associations and different roles for each type of family member. Based on these roles, your application can offer different functionality. 

These relationships may be complex; for example, a child may be a member of multiple families all headed by different parents.

The second reason to consider using the family API is because you are legally obligated to obtain parental consent due to the age of your users and what you are doing with their data. FusionAuth can help you send emails to verify consent and track the consents given to each user. While restrictions and age limits vary by legal jurisdiction, applications often need some form of parental consent. 

We'll walk through these scenarios below.

== Setting up family management

The first step is to enable the family settings. 

Go to [breadcrumb]#Tenants -> Default -> Family# and enable the family, if you want the functionality to be available to the "Default" tenant.

TBD pic of family settings basic default-family-settings

You'll also want to make sure your "Maximum child age" and "Minimum owner age" are set appropriately. The defaults are correct for the current laws of the USA, but ages will differ according to your legal jurisdiction. If you are serving different countries with different ages, you'll need different tenants, as these values are set on a tenant basis.

Different use cases will require modifying additional Tenant attributes, but for now let's leave the defaults and examine different use cases.

== Use cases

Let's walk through some cases where you might want to use families. 

We'll cover the following

* Family management
* Generic Parental Approval
* COPPA

=== Family management

In this case, you'll be using the Family APIs to create a family and associate users within that family.

Each user account is independent, with its own data, email address or username and password. A family lets you group them together.  Users are associated with the family by actions of the owner, so consent is implied in the act of creation and not captured in the system. Imaging adding a family member to a Netflix or Amazon account. When you are doing so, the consent is in the act.

==== Creating and adding family members 

First, create a FusionAuth application using the link:../apis/applications[Application API] and a user with the link:../apis/users[User API]. Or, use the administration user interface to create these users. Make sure the user's age is greater than the "Minimum owner age" you specified.

Then, create a family associated with this user by calling the link:../apis/families#create-a-family[`/api/user/family`] endpoint. Here's an example of how you might do this using curl.

[source,shell]
.Creating a Family
----
API_KEY=...
REQUEST_PAYLOAD='{...}'
curl -XPOST -H 'Content-type: application/json' -H "Authorization: $API_KEY" https://local.fusionauth.io/api/user/family -d $REQUEST_PAYLOAD
----

The first user of a family must be an adult and an owner. Here's an example request payload:

[source,json]
.Create Family Request JSON
----
include::docs/src/json/family/request.json[]
----

Here's an example response:

[source,json]
.Create Family Response JSON
----
include::docs/src/json/family/response.json[]
----

After family creation, there is only one member, the owner. Your application can then add family members as needed. To do so, ensure they exist, adding them via the API if needed. 

The request to add users to a family is similar to the request to create a family. The main differences are:

* You provide the existing family id
* You use the `PUT` method instead of the `POST` method
* You can add users with any family role

[source,shell]
.Adding a User to a Family
----
API_KEY=...
REQUEST_PAYLOAD='{...}'
curl -XPUT -H 'Content-type: application/json' -H "Authorization: $API_KEY" https://local.fusionauth.io/api/user/family -d $REQUEST_PAYLOAD
----

Here's an example request payload:
[source,json]
.Add A Member To A Family Request JSON
----
include::docs/src/json/family/request-child.json[]
----

After each addition, you'll receive back the entire family object. Here's an example response payload:

[source,json]
.Add A Member To A Family Response JSON
----
include::docs/src/json/family/response-after-child-added.json[]
----

==== Retrieving family members

If you are building a family interface, you'll want to display all the members. You'd make this API call when you wanted to display all the associated accounts, just like in Netflix when you choose which account's shows to watch.

To find family members, you must provide a user id or a family id. Which method to choose depends on what you are trying to do.

If you are looking for related family members, provide the user id of the family member you know. If, on the other hand, you know the family id and are looking for all members, search by family id. 


[source,shell]
.Retrieving a Family By Family Id
----
API_KEY=...
FAMILY_ID=a815b480-d52d-4755-96ac-749c067925d7
curl -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'https://local.fusionauth.io/api/user/family/'$FAMILY_ID
----

[source,shell]
.Retrieving a Family By User Id
----
API_KEY=...
USER_ID=b3360a2d-e81d-4314-b9f1-244a916ca52f
curl -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'https://local.fusionauth.io/api/user/family?userId='$USER_ID
----

Here's an example response payload:

[source,json]
.Retrieve Family Response JSON
----
include::docs/src/json/family/response-after-child-added.json[]
----

You can also see all family members in the administrative user interface. Go to [breadcrumb]#Users# and then view the user details. Navigate to the "Family" tab to see family members. From there, you can manage the details of each family member.

TBD Pic display-family-members-admin-ui


==== Update family members 

You can update information about a family member. You might do this if their family role has changed. FusionAuth does not automatically change the role of a user based on their age.

[source,shell]
.Little e4440a4d Is All Grown Up, Let's Mark Them As a Teenager
----
API_KEY=...
FAMILY_ID=a815b480-d52d-4755-96ac-749c067925d7
REQUEST_PAYLOAD='{...}'
curl -XPUT -H 'Content-type: application/json' -H "Authorization: $API_KEY" https://local.fusionauth.io/api/user/family/
----

Here's an example request payload:

[source,json]
.Update Family Member Request JSON
----
include::docs/src/json/family/request-update-child.json[]
----

Here's an example response payload, indicating that indeed, the user's family role has changed:

[source,json]
.Update Family Member Response JSON
----
include::docs/src/json/family/response-after-child-updated.json[]
----

==== Removing family members and families

You may also remove family members. An example of why you might do this is if someone signed up for their own Netflix account. They then won't need to be associated with the family account.

[source,shell]
.Removing a Family Member 
----
API_KEY=...
FAMILY_ID=a815b480-d52d-4755-96ac-749c067925d7
USER_TO_REMOVE=e4440a4d-b81d-4314-c9f1-844a916ca52f
curl -XDELETE -H "Authorization: $API_KEY" 'https://local.fusionauth.io/api/user/family/'$FAMILY_ID'/'$USER_TO_REMOVE
----

TODO STOPPED here
You can't delete a family object. Similarly to the way it is created implicitly, if you remove all members, the family becomes unavailable. At that point any requests made against that family will fail. For example, if you attempt to retrieve it, a 404 will be returned.

You can delete all the owners and adults from a family and leave a user with a `Child` or `Teen` family role. BUG?

=== Parental Approval

In this scenario, a child creates an account but doesn't have full access until a parent has approved the signup. Depending on your application, you may make limited application functionality available, however. Think of a game aimed at children like Roblox. An example of functionality that may be unlocked by parental approval is in-game chat.

Parents approve signups by receiving an email and clicking on a link. FusionAuth takes care of sending the email, but you need to make sure your application handles the link click.

Note that this scenario is unique in how users are added to a family. Updating and removing family members happen in the same manner as the previous scenario.

A parent may or may not have an account, but if they do not, they'll be prompted to create one. At the end of this scenario, both the parent and child will have FusionAuth accounts.

==== Setting up the email

You'll want to create two email templates. The first is the 
"Confirm child account template" and the second is the "Parent registration request template". The "Confirm child account template"  will be sent when a parent has an account and merely needs to confirm the child's account creation. "Parent registration request template" is sent when the parent must register. 

.Sample Confirm Child Email HTML Template
[source,text]
----
include::docs/src/email/confirm-child.html[]
----

.Sample Parent Registration Request HTML Template
[source,text]
----
include::docs/src/email/parent-registration.html[]
----

You can customize and localize these, please see the link:../email-templates/email-templates[Email Templates documentation] for replacement variables and more information.

At this time you cannot resend these emails. XXX doublecheck


TBD Pic

==== Registering the child

[source,shell]
.Registering a Child With Parental Consent
----
API_KEY=...
REQUEST_PAYLOAD='{...}'
curl -XPUT -H 'Content-type: application/json' -H "Authorization: $API_KEY" https://local.fusionauth.io/api/user -d $REQUEST_PAYLOAD
----

Here's an example request payload:

[source,json]
.Registering a Child With Parental Consent Request JSON
----
{
  "registration": {
    "applicationId": "78bd26e9-51de-4af8-baf4-914ea5825355"
  },
  "user": {
    "parentEmail": "parent@example.com",
    "birthDate": "2016-01-01",
    "email": "child@example.com",
    "password": "password"
  }
}
----

You need to provide the parent's email address and birthday as well as the expected application, email and password information.

As soon as you provide the parent's email address on the registration, emails will be triggered, no matter what the age of the child isXXX BUG?. 

At this point, the flow forks. On one path, the parent has a FusionAuth account. In this case, the "Confirm child account template" email will be sent.

On the other path, the "Parent registration request template" email is sent when the parent must register and create a FusionAuth account. If you never want a parent to be prompted to create an account, you could create a parent account for the given email address via the API. You could then let the parent reset the password when they receive the "Confirm child account template" email.

In both these cases, there's a link in the email. You as a developer are responsible for handling that what happens at that link.

==== Handling the click

When the link in the email is clicked by the parent, they must register or log in to your application.  

After they do so, you present the parent with the list of children to confirm.

You can do this by calling the "Retrieve Pending Family Members" API. 

[source,shell]
.Retrieving Pending Family Members
----
API_KEY=...
PARENT_EMAIL_ADDRESS=parent@example.com

curl -XGET -H "Authorization: $API_KEY" 'http://local.fusionauth.io/api/user/family/pending?parentEmail='$PARENT_EMAIL_ADDRESS
----

This will return a list of User objects which correspond to the unconfirmed children.

You may then add them to the family using the same APIs. Note that once you add them to the family, the `parentEmail` attribute of the user is removed XXX check.

If the parent doesn't have a FusionAuth account, you'll want the send the user to the registration url. If they do, send them to the login url, but in both cases they'll end up at the list of children associated with their email address which they should confirm. You should ensure that this is a protected page.

sample node app

https://github.com/FusionAuth/fusionauth-issues/issues/685 before 1.17.2 issue with the email template

==== After the click

You'll want to capture how the parent gave consent. You have a couple of options:

- You can record it elsewhere in your system. For example, the click handler could call off to another API.
- can add it to the user.data of the child
- you can record a consent 

The important thing to know is that it doesn't happen automatically. 

==== Using consents

Creating a consent is the best way to handle this. You can capture how and when consent is given. Then you can retrieve consents for each child and user. You can even build a user interface to allow a parent to revoke a consent.

Note that you can't give consent until the child has been made part of a family, and only the adults in a family can do so XXX. If a teenager is part of a family, they can self consent.

First, create a consent. Let's do that via the admin UI. I'm going to add a consent called 'Email consent':

Pic TBD

Second, when the parent verifies the child, create a user consent.

We'd do this with the following curl command, though you can of course use the client libraries:

[source,shell]
.Granting Consent 
----
API_KEY=...
REQUEST_PAYLOAD='{...}'

curl -XPOST -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'http://local.fusionauth.io/api/user/consent' -d $REQUEST_PAYLOAD
----

Here's an example request payload:

[source,json]
.Granting Consent Request JSON
----
include::docs/src/json/user-consent/request.json[]
----

Which responds with the following:

[source,json]
.Granting Consent Response JSON
----
include::docs/src/json/user-consent/response-no-email-plus.json[]
----

In your application, you can pull the consents for a given user to know what level of access to allow or for reporting. You can learn more about link:../apis/consent[consents in the API docs].

add in self registration requires email if you enable the birth date field.


==== Unverified Children

If a child registers and the parent never confirms their account, you can optionally have the child accounts automatically deleted after a certain number of days.

Or you can keep the accounts around, if that works better for you.

==== Using the FusionAuth OAuth Interface

While the above documents how to use the APIs to build your own interaces, you can also use the FusionAuth OAuth interface. To do so:
 
. Enable the self service registration on the application
. Enable "Allow child registrations on the tenant"
. Enable "Parent email required during registration" 

These are settings that affect the OAuth registration interface.

In this case, FusionAuth will prompt any user registering with for their birth date.

TBD pic

And then will require the parent email address, if their birth date indicates they are under the maximum child age configured in the Tenant Family tab.

TBD Pic

When a child registers, the parent will be emailed; the template used will be the "Parent registration request template" if they are not registered, but if they are, the "Confirm child account template" email will be sent.

When the parent registers, you'll still have to handle the displaying the pending family members using your own API calls and have the parents approve them. The OAuth registration pages don't provide for that.


==== Updating and Removing Members

There are no differences in updating or removing family members in this scenario.

=== Legal Consent Frameworks 

For some applications specifically targetted at young children, laws come into play. For example [COPPA](https://www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/childrens-online-privacy-protection-rule) in the USA and the [GDPR](https://gdpr-info.eu/art-8-gdpr/) in the EU both have specific requirements around informed consent of parents for certain online activities aimed at children.

FusionAuth allows you to build custom consent frameworks, but also supports COPPA.

If you're building a child-directed game (one aimed at children) in the USA, and you'll be collecting data about them to help with marketing and gameplay improvement, you need to comply with COPPA.

What about family registrations when allow child registrations is off? XXX


==== COPPA Support

There are two different ways for companies to comply with COPPA, according to the FTC, depending on how you're going to use the data. You can use verified parental consent (VPC) or "email plus". While FusionAuth supports both, "email plus" is available out of the box and is more common.

==== COPPA Consent

The only difference between COPPA and Parental Approval is in the consent required. COPPA "email plus" requires two emails to be sent, and FusionAuth has built this workflow.

To enable this, review the COPPA Email+ consent and make any changes needed.

Pic TBD

Then review both the COPPA notice email templates. At the least, you'll want to modify them so that they point to the correct location for the consent clicks.

Here are the sample email templates.

.The Initial COPPA Notice
[source,text]
----
include::docs/src/email/coppa-notice.html[]
----


.The Email Plus COPPA Notice
[source,text]
----
include::docs/src/email/coppa-plus-notice.html[]
----

When a child is verified by a parent and added to the family, as above, create the consent. Here's an example of how you might do so for a child.

[source,shell]
.Granting Consent 
----
API_KEY=...
REQUEST_PAYLOAD='{...}'

curl -XPOST -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'http://local.fusionauth.io/api/user/consent' -d $REQUEST_PAYLOAD
----

Here's an example request payload:

[source,json]
.Granting Consent Request JSON
----
include::docs/src/json/user-consent/request.json[]
----

Which responds with the following:

[source,json]
.Granting Consent Response JSON
----
include::docs/src/json/user-consent/response.json[]
----

For a teenager, you can perform self consent as well. In that case the `giverUserId` and the `userId` for the consent request would be the same `userId`, that of the teenager.

==== Revocation
You must handle the consent revocation. There will be two emails sent, and in either case, the parent can login and and view the consents. They should be able to grant or revoke them for any child in the family.

Here's how you'd revoke a previously granted consent, using curl:

[source,shell]
.Revoking Consent 
----
API_KEY=...

curl -v -XDELETE -H "Authorization: $API_KEY" 'http://local.fusionauth.io/api/user/consent/841d8b33-bf4d-488d-9f2f-2f50d769c3d2' 
----

Here's the response you'll receive on successful revocation:

[source,json]
.Revoked Consent Response JSON 
----
include::docs/src/json/user-consent/response-revoked.json[]
----

And here's how you'd pull a list of consents for a user to determine if they'd been given consent.

[source,shell]
.Listing User Consents
----
API_KEY=...

curl -XGET -H "Authorization: $API_KEY" 'http://local.fusionauth.io/api/user/consent?userId=841d8b33-bf4d-488d-9f2f-2f50d769c3d2'
----

This call responds with this JSON when the consent has been granted.

[source,json]
.Listing Consent Response JSON When Consent Granted
----
include::docs/src/json/user-consent/response.json[]
----


This is the response when consent has been revoked:

[source,json]
.Listing Consent Response JSON When Consent Revoked
----
include::docs/src/json/user-consent/response-revoked.json[]
----

when the consent has been revoked. 

[NOTE]
====
This means that you need to check the value of the consent `status`, not just whether the consent exists.
====

You'd want to call this after the child's login and prevent the child from accessing the application if consent has been revoked.


add the consent

wait for the emails

should you use the other emails (confirm child, parent registration)?

self consent? for teenagers 


== Alternatives

If you don't need to model parent child relationships, but instead simply want a way of grouping users, consider link:/docs/v1/tech/core-concepts/groups[Groups].

If you want to associate permissions within your application to users or groups of users, but don't need to worry about parent child relationships, consider link:/docs/v1/tech/core-concepts/roles[Roles].



== Limitations

There are currently some limitations on the family functionality.

While families display in the administrative UI and there is configuration that is set from the UI, you cannot create or modify families using the admin interface. If you are going to use families, you're going to be writing code against the APIs, either directly or using the client libraries. However, there is support in the FusionAuth provided login screens for the family flows.

There are only three family roles available:

* `Adult`
* `Child`
* `Teen`

While you can control the ages at which these roles take place, there is no relationship between the actual birth date of a user and the role they are assigned. These roles are completely assigned by you and if you want to categorize a 25 year old as a teenager, FusionAuth won't stop you. XXX what are the ages in the family settings screen used for?
Ages are checked for the initial adult created, but no other users. XXX BUG

These family roles have no relationship whatsoever to application roles that are created and managed at the application level.

Family attributes are defined at the tenant level. If you require different configurations, you may need multiple tenants. For example, if the maximum age of a child is 12 for one application and 13 for another, you can't manage them in the same FusionAuth tenant.

A family consists of at least one adult, and an arbitrary number of teens, children and adults.

A family is created by associating an existing user with a family.

Families can have more than one owner, but all owners must be adults. 

Users with the `Child` or `Teen` family roles may belong to more than one family, but a user with the `Adult` role may not belong to more than one family. However, the same user may be added as a `Child` to one family and an `Adult` to another. XXX BUG

=== TODO

Look at casing of code snippet titles.

take pictures
