---
layout: doc
title: Families guide
description: What are families in FusionAuth and how are they useful?
---


The family API in FusionAuth is a powerful way to logically group family members.

You can review the link:/docs/v1/tech/apis/families[family API documentation] for detailed API call examples.

== Why would you use Families?

There are two main reasons you might want to use families. The first is to easily add family relationships to your application. You can have associations and different roles for each type of family member, which can allow access to different functionality within your application. These relationships may be quite complex; for example, a single child may be a member of multiple families headed by different parents.

The second reason is because you are legally obligated to obtain parental consent due to the age of your users and what you are doing with their data, and you want to send and keep track of those consents within FusionAuth. While the ages and restrictions vary in each legal jurisdiction, in general applications need parental consent if children are using them.

We'll walk through these scenarios below.

== Limitations

There are currently some limitations on the family functionality.

While families display in the administrative UI and there is configuration that is set from the UI, you cannot create or modify families using the admin interface. If you are going to use families, you're going to be writing code against the APIs, either directly or using the client libraries. However, there is support in the FusionAuth provided login screens for the family flows.

There are only three family roles available:

* `Adult`
* `Child`
* `Teen`

While you can control the ages at which these roles take place, there is no relationship between the actual birth date of a user and the role they are assigned. These roles are completely assigned by you and if you want to categorize a 25 year old as a teenager, FusionAuth won't stop you. XXX what are the ages in the family settings screen used for?
Ages are checked for the initial adult created, but no other users. XXX BUG

These family roles have no relationship whatsoever to application roles that are created and managed at the application level.

Family attributes are defined at the tenant level. If you require different configurations, you may need multiple tenants. For example, if the maximum age of a child is 12 for one application and 13 for another, you can't manage them in the same FusionAuth tenant.

A family consists of at least one adult, and an arbitrary number of teens, children and adults.

A family is created by associating an existing user with a family.

Families can have more than one owner, but all owners must be adults. 

Users with the `Child` or `Teen` family roles may belong to more than one family, but a user with the `Adult` role may not belong to more than one family. However, the same user may be added as a `Child` to one family and an `Adult` to another. XXX BUG


== Setting up family management

At a minimum, you need to enable the family settings. 

Go to [breadcrumb]#Tenants -> Default -> Family# and enable the family, if you want the functionality to be available to the "Default" tenant.

TBD pic of family settings basic

You'll also want to make sure your "Maximum child age" and "Minimum owner age"XXX bug should change to Minimum adult age are set correctly. The defaults are correct for the current laws of the USA, but ages will differ according to the legal jurisdiction. Note that if you are serving different countries with different ages, you'll need different tenants, as these values are set on a tenant basis.

Different use cases will require modifying additional Tenant attributes, but for now let's leave the defaults and examine different use cases.

== Use cases

Let's walk through some cases where you might want to use families. 

=== Family management

In this scenario, you want associated accounts. This is a simple flow and doesn't use the FusionAuth provided OAuth registration process at ll.

Here, each account is standalone, but may be part of a family. Accounts are added by the owner, so no consent is necessary. This is similar to adding a family member to a Netflix or Amazon account. When you are adding a family member to your Netflix account, there's no need for consent, because the account owner is creating the additional user. The consent is in the act.

==== Creating and adding family members 

First, create a user using the link:../apis/users[User API].

Then, create a family associated with this user by calling the link:../apis/families#create-a-family[`/api/user/family`] endpoint.

[source,shell]
.Creating a Family
----
API_KEY=...
REQUEST_PAYLOAD='{...}'
curl -XPOST -H 'Content-type: application/json' -H "Authorization: $API_KEY" https://local.fusionauth.io/api/user/family -d $REQUEST_PAYLOAD
----

Here's an example request payload:

[source,json]
.Create Family Request JSON
----
include::docs/src/json/family/request.json[]
----

Here's an example response:

[source,json]
.Create Family Response JSON
----
include::docs/src/json/family/response.json[]
----

Then, add new family members as needed. Again, each user must exist before they can be added to the family. This is similar to adding an associated account in Netflix.

The only difference between adding family members and creating a family are:

. You provide the existing family id
. You use the `PUT` method instead of the `POST` method
. You can add users with any family role

[source,shell]
.Adding a User to a Family
----
API_KEY=...
REQUEST_PAYLOAD='{...}'
curl -XPUT -H 'Content-type: application/json' -H "Authorization: $API_KEY" https://local.fusionauth.io/api/user/family -d $REQUEST_PAYLOAD
----

Here's an example request payload:
[source,json]
.Add A Member To A Family Request JSON
----
include::docs/src/json/family/request-child.json[]
----

After each addition, you'll receive back the entire family object. Here's an example response payload:

[source,json]
.Add A Member To A Family Response JSON
----
include::docs/src/json/family/response-after-child-added.json[]
----

==== Retrieving family members

Then you'll want to be able to find all of the members of a family. You'd make this API call if you wanted to display associated accounts on a sign in screen.

You can either provide either a userid or a family id. If you are trying to find related family members, the former method will be useful. If, on the other hand, you know the family id and are looking for members, the latter is better. You'd make this API call when you wanted to display all the associated accounts, just like in Netflix when you choose which account's shows to watch.

[source,shell]
.Retrieving by family id
----
API_KEY=...
FAMILY_ID=a815b480-d52d-4755-96ac-749c067925d7
curl -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'https://local.fusionauth.io/api/user/family/'$FAMILY_ID
----

[source,shell]
.Retrieving by user id
----
API_KEY=...
USER_ID=b3360a2d-e81d-4314-b9f1-244a916ca52f
curl -H 'Content-type: application/json' -H "Authorization: $API_KEY" 'https://local.fusionauth.io/api/user/family?userId='$USER_ID
----

Here's an example response payload:

[source,json]
.Retrieve Family Response JSON
----
include::docs/src/json/family/response-after-child-added.json[]
----

You can also see all family members in the admin UI. Go to [breadcrumb]#Users# and then view the user details and then the "Family" tab to see family members. Note that you can navigate to the User management screens of each family member.

TBD Pic


==== Update family members 

You can update a family member. You might do this if their role or owner status has shifted, if someone is a teenager, for example.

[source,shell]
.Little e4440a4d is all grown up, let's make them a teenager
----
API_KEY=...
FAMILY_ID=a815b480-d52d-4755-96ac-749c067925d7
REQUEST_PAYLOAD='{...}'
curl -XPUT -H 'Content-type: application/json' -H "Authorization: $API_KEY" https://local.fusionauth.io/api/user/family/
----

Here's an example request payload, updating the user with id `e4440a4d-b81d-4314-c9f1-844a916ca52f`:

[source,json]
.Update Family Member Request JSON
----
include::docs/src/json/family/request-update-child.json[]
----

Here's an example response payload:

[source,json]
.Update Family Member Response JSON
----
include::docs/src/json/family/response-after-child-updated.json[]
----

==== Removing family members and families

You can also remove family members. You might do this if someone signed up for their own Netflix account and shouldn't be affiliated with the family's account anymore. 

[source,shell]
.Remo
----
API_KEY=...
FAMILY_ID=a815b480-d52d-4755-96ac-749c067925d7
USER_TO_REMOVE=e4440a4d-b81d-4314-c9f1-844a916ca52f
curl -XDELETE -H "Authorization: $API_KEY" 'https://local.fusionauth.io/api/user/family/'$FAMILY_ID'/'$USER_TO_REMOVE
----

You can't delete a family object. Similarly to the way it is created implicitly, if you remove all members, the family becomes unavailable. At that point any requests made against that family will fail. For example, if you attempt to retrieve it, a 404 will be returned.

You can delete all the owners and adults from a family and leave a user with a `Child` or `Teen` family role. BUG?

=== Parental Approval

In this scenario, a child creates an account but doesn't have full access until a parent has approved the signup. Depending on your application, you may make limited application functionality available, however. Think of a game aimed at children like Roblox. 

Parents approve signups by receiving an email and clicking on a link. FusionAuth takes care of sending the email, but you need to make sure your application handles the link click.

Note that this scenario is unique in how users are added to a family. Updating and removing family members happen in the same manner as the previous scenario.

A parent may or may not have an account, but if they do not, they'll be prompted to create one. At the end of this scenario, both the parent and child will have FusionAuth accounts.

==== Setting up the email

You'll want to create two email templates. The first is the 
"Confirm child account template" and the second is the "Parent registration request template". The "Confirm child account template"  will be sent when a parent has an account and merely needs to confirm the child's account creation. "Parent registration request template" is sent when the parent must register. 

.Sample Confirm Child Email HTML Template
[source,text]
----
include::docs/src/email/confirm-child.html[]
----

.Sample Parent Registration Request HTML Template
[source,text]
----
include::docs/src/email/parent-registration.html[]
----

You can customize and localize these, please see the link:../email-templates/email-templates[Email Templates documentation] for replacement variables and more information.

At this time you cannot resend these emails. XXX doublecheck


TBD Pic
==== Registering the child

[source,shell]
.Registering a Child With Parental Consent
----
API_KEY=...
REQUEST_PAYLOAD='{...}'
curl -XPUT -H 'Content-type: application/json' -H "Authorization: $API_KEY" https://local.fusionauth.io/api/user -d $REQUEST_PAYLOAD
----

Here's an example request payload:

[source,json]
.Registering a Child With Parental Consent Request JSON
----
{
  "registration": {
    "applicationId": "78bd26e9-51de-4af8-baf4-914ea5825355"
  },
  "user": {
    "parentEmail": "parent@example.com",
    "birthDate": "2016-01-01",
    "email": "child@example.com",
    "password": "password"
  }
}
----

You need to provide the parent's email address and birthday as well as the expected application, email and password information.

As soon as you provide the parent's email address on the registration, emails will be triggered, no matter what the age of the child isXXX BUG?. 

At this point, the flow forks. On one path, the parent has a FusionAuth account. In this case, the "Confirm child account template"  will be sent.

On the other path, the "Parent registration request template" is sent when the parent must register and create a FusionAuth account. If you never want this email to be sent, you must create a parent account, even if the human parent doesn't sign in with this account. 

In both these cases, there's a link in the email. You as a developer are responsible for handling that what happens at that link.

==== Handling the click

When the link in the email is clicked, have the parent register or log in.  

Then you present the parent with the list of children to confirm, or you can limit it to the child making the request.

Note that you have to pass some state along, the easiest way to do that is to use the state parameter. Then in the OAuth callback handling code, you can capture that value if needed. For example, if you wanted to only show the child account requesting confirmation, you could pass that along in the state.

http://localhost:9011/oauth2/authorize?client_id=78bd26e9-51de-4af8-baf4-914ea5825355&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth-redirect&state=confirm-child

Then you add them to the family in the same way as above, using the APIs to put them to the family.

If the parent doesn't have a FusionAuth account, you'll want the send the user to the registration url. If they do, send them to the login url, but in both cases they'll end up at the list of children associated with their email address which they should confirm. You should ensure that this is a protected page.

sample node app

https://github.com/FusionAuth/fusionauth-issues/issues/685 before 1.17.2 issue with the email template

==== After the click

You'll want to capture how the parent gave consent. You have a couple of options

- You can record it elsewhere in your system. For example, the click handler could call off to another API.
- can add it to the user.data of the child
- you can record a consent (searchable?

The important thing to know is that it doesn't happen automatically. 

==== Using consents

Creating a consent is the best way to handle this. You can capture how and when consent is given. Then you can retrieve consents for each child and user. You can even build a user interface to allow a parent to revoke a consent.

Note that you can't give consent until the child has been made part of a family, and only the adults in a family can do so XXX. If a teenager is part of a family, they can self consent.

First, create a consent. Let's do that via the admin UI. I'm going to add a consent called 'Email consent':

Second, when the parent accepts the consent, create a user consent.

We'd do this with the following curl command:

// no value

Which responds with the following JSON

You can also see the consent is now associated with the child
XXX should be associated with the parent, but isn't? not sure why


Then, in the application, you can pull the consents for a given user to know what level of access.

You can learn more about consents in the API docs.

add in self registration requires email if you enable the birth date field.

what happens if parent account doesn't exist? they get 'Parent registration request template'

==== aa
What happens if a parent doesn't confirm the child's account?
- delete unverified children

==== Using the FusionAuth OAuth Interface

While the above documents how to use the APIs to build your own interaces, you can also use the FusionAuth OAuth interface. To do so:
 
. Enable the self service registration on the application
. Enable "Allow child registrations on the tenant"
. Enable "Parent email required during registration" 

These are settings that affect the OAuth registration interface.

In this case, FusionAuth will prompt any user registering with for their birth date.

TBD pic

And then will require the parent email address, if their birth date indicates they are under the maximum child age configured in the Tenant Family tab.

TBD Pic

When a child registers, the parent will be emailed; the template used will be the "Parent registration request template" if they are not registered, but if they are, the "Confirm child account template" email will be sent.

When the parent registers, you'll still have to display the pending family members using your own API calls and have the parents approve them. The OAuth registration pages don't provide for that.



==== Updating and Removing Members

This is the same XXX
what about updating role? does that require consent?

=== COPPA Email+


== Alternatives

If you are looking for a way to group users, consider link:/docs/v1/tech/core-concepts/groups[Groups].

TODO

Look at casing of code snippet titles.

take pictures
