---
layout: doc
title: Migration
description: How to migrate your users to FusionAuth.
---
:page-liquid:

== Overview

This guide will help you set up a multi-tenant application in FusionAuth. Tenants are logical separations of users, applications and other entities in FusionAuth.

TOC TODO

== Why Multi-Tenant

There are many reasons why you might be interested in a multi-tenant FusionAuth installation. The overriding reason is the logical separation it provides. While you have only one FusionAuth instance to manage, users, applications, and other entities are logically separated. Even FusionAuth API keys can be tied to tenants. 

You might be interested in building an application which you'll offer as a SaaS (Software as a Service). In this case, you can private label your application using tenants. All user information within each tenant will be entirely separate.

Another use case might be for different environments. For instance, on one FusionAuth instance, you could run integration, user acceptance and developer environments. 

You also might want to provide a tenant for each developer on a dedicated development server. This would allow developers free reign to add, remove and modify entities in their FusionAuth tenant, while keeping them insulated from each other.

There also may be situations where you have settings that need to be different for different sets of users. Examples of such settings include password rules, the look and feel of the login pages, or webhook transaction level.

== Multi-Tenant Concepts

XXX TODO?

To make things a bit more concrete, let's use an example. Let's talk about Pied Piper video chat. It will be so much better than Slack chat with patented middle out compression. This application will have multiple tenants. Every one who signs up will get a domain name like `companyx.piedpiper.com`.

Before this guide covers how to set up multi-tenancy, let's cover what can be configured at the tenant level. There are five general categories of modifiable entities in FusionAuth:

* Tenant scoped entities
* Tenant attached entities
* Application scoped entities
* Application attached entities
* Global "things"

A "scoped" entity is contained within the enclosing entity, and if the latter is deleted, the former will be as well. For instance, a user is scoped to a tenant, and if that tenant is deleted, the user will be as well. 

Scoped entities cannot be shared between multiple entities to which they are scoped. If the Pied Piper chat application needs groups for different user privileges, each tenant would have its own "Admin Group", "Moderator Group" and so on.

An "attached" entity is affiliated with an enclosing entity, but if the latter is deleted, the former will continue to exist. For instance, a signing key is associated with a tenant's JWT configuration. If that tenant is deleted, the signing key's association with the tenant is removed, but the tenant is not. 

Attached entities can be re-used between entities. For example, if the Pied Piper chat application needs to add a user privilege claim to a JWT, the same Lambda can be used.

TODO extract to share with core concepts?

=== Tenant Scoped 

Here is a list of items that are tenant scoped:

* Users
* Groups
* API Keys (optionally)
* Applications
* Entities

=== Tenant Attached 

Here is a partial list of tenant attached items:

* Email templates (some of them)
* Forms (some of them)
* Themes
* Connectors
* Consents
* User actions
* Webhooks

=== Application Scoped

Here is a list of application scoped items.

* Registrations
* Roles

Because an application is tenant scoped, the above entities are also scoped to a tenant. They cannot be used across tenants. For example, if a tenant containing the containing application is deleted, the registrations for a given application will also be deleted.

=== Application Attached

Here is a partial list of application attached things:

* Identity providers
* Email templates (some of them)
* Forms (some of them)
* Lambdas

=== Global Items

There are items global in scope. These are typically scoped under `system` in the API namespace.

* API Keys (optionally)
* Login reports?
* Logs

Additionally, there are configuration settings for CORS which are shared between all the tenants in an instance.

The administrative user interface is also shared between tenants. There is no way to grant access to the FusionAuth administrative user interface but limit the user to a single tenant. There is an https://github.com/FusionAuth/fusionauth-issues/issues/91[open issue].

If you need separation of global configuration, or if you need true physical separation due to different regulatory regimes, you can run multiple FusionAuth instances. If you need to sync configuration between them, script your changes using the API, terraform provider, or client libraries.

== Example Application

Let's continue to build out our Pied Piper video chat application. Let's talk about what this application needs:

* A way for users to sign up to set up a video chat space. This will include their desired hostname: `companyA.chat.piedpiper.com` or `organizationB.chat.piedpiper.com`.
* A way for users to sign up for a given video chat space: `companyA.chat.piedpiper.com`.
* A way for users to log in to a specific video chat space: `companyA.chat.piedpiper.com`.
* Video chat functionality.

This guide will build an application meeting all of these requirements, except for the last one. That is left as an exercise for the reader. Here's https://github.com/FusionAuth/fusionauth-example-python-multi-tenant[the GitHub repo] with working code if you'd like.

=== Prerequisites

This application will be written in using symfony, so you'll need symfony, php and a database. If you don't have that, https://symfony.com/doc/current/setup.html[install symfony], https://www.php.net/manual/en/install.php[php] and https://dev.mysql.com/doc/mysql-installation-excerpt/8.0/en/[mysql]. 

You'll also need to create a mysql user. 


https://stackoverflow.com/questions/53066962/an-exception-occurred-in-driver-sqlstatehy000-2054-the-server-requested-aut
After you create the user, convert their password to the legacy password format

ALTER USER 'username'@'ip_address' IDENTIFIED WITH mysql_native_password BY 'password';

You'll also need a running FusionAuth instance. Visit the link:/docs/v1/tech/installation-guide/[installation guides] and choose one of the many ways to install it.



=== Setting Up 

Create the application.


symfony new piedpipervideochat --full 

set up the connection to the database in your .env.local file


This code is running symfony version 5.2.6, the latest stable release at the time.

cd piedpipervideochat 

require some needed libraries
composer require symfony/orm-pack; composer require --dev symfony/maker-bundle
symfony composer require twig
composer require fusionauth/fusionauth-client
symfony composer require annotations
composer require knpuniversity/oauth2-client-bundle
composer require jerryhopper/oauth2-fusionauth

start a new tab and start the server

symfony server:start

=== Build the Video Application

Let's build the bones of the video application. We won't build a login form, as we'll be using FusionAuth's hosted login pages. But we'll add a home page for the video application, and then a chat page. Building the middle out compression algorithm will be left as an exercise for the user.

Add two controllers to the symfony applicatiion.

symfony add controller home page

symfony add controller chat page

=== Add Login with FusionAuth

add a user class

symfony console make:user

http://localhost:8000/connect/fusionauth/check

Let's add login with FusionAuth, without tenants. We will lay the groundwork for tenants, however.

configure 

Add a tenant model in symfony.

Add an application id, url and a color. As you build this out, you could add logos or custom urls as well.

Set up an application in FusionAuth, and add the application id and the color "gray" to symfony.

add symfony routes to send people to login and logout, and send to chat page

Have a user login by going to the

=== Manually Set up a Tenant

Let's test things out by manually creating a tenant.

Add them to the symfony system
create the tenant object

Do the fusionauth stuff
create a tenant 
create an application
enable self service registration
create a user
copy the theme

modify the color
body { background-color: red; }

update the tenant object

log the user in

add registration link

=== Automate it

do the following steps above by using the api. do a syncrhonous webhook (with note that you might want it to be async later)


END

=== Setting Up FusionAuth Tenants

Let's manage FusionAuth configuration using the php client and doctrine migrations. 

First, log in to FusionAuth and create an API key. You can do this by navigating to [breadcrumb]#Settings -> API Keys#. Add a global API key with unlimited permissions, since any kind of configuration may be set here.

TBD image

Add the value to your .env.local file

```
FUSIONAUTH_API_KEY=...
```

then add the followign to your config/services.yaml

```yaml
parameters:
    fusionauth_api_key: '%env(FUSIONAUTH_API_KEY)%' # new line
```

This lets us pull the API key from the environment, which is less dangerous than checking it in.

FusionAuth ships with a default tenant, but to have full separation, let's add a new tenant. 


generate an empty migration

php bin/console doctrine:migrations:generate 

you should see output like

 Generated new migration class to "/Users/dan/work/fusionauth-example-python-multi-tenant/piedpipervideochat/migrations/Version20210401222131.php"
 
 To run just this migration for testing purposes, you can use migrations:execute --up 'DoctrineMigrations\Version20210401222131'
 
 To revert the migration you can use migrations:execute --down 'DoctrineMigrations\Version20210401222131'

edit migrations/Version20210401222131.php

and add in this code

...

You can then run this to see the status of the migration

php bin/console doctrine:migrations:status

and this to run it:

php bin/console doctrine:migrations:execute

This will let you manage the configuration of your FusionAuth server in a version controlled manner.


New tenant with one application created on registration via webhook, new theme, and update CSS for the theme.

Also map 




Python application handing the tenant hostnames as well as the oauth redirects.

== Tenant Level Customization

Customization available
Pretty much everything. Here are the high points.
Themes
Should probably customize them some.
Registration forms (with advanced reg forms)
Password rules
Social sign on

== Limits
Resources, primarily, but we have people running thousands of tenants in FA. 
Access to fusionauth admin ui
Intermixing of login records/other logs across tenants.
I’m not aware of any other limits

tenant limitations from the limitations doc
social sign on providers (only one of those)

https://fusionauth.io/community/forum/topic/936/newbie-question-on-urls-for-multitenant-applications
https://fusionauth.io/community/forum/topic/900/authentication-for-an-application-with-web-client-and-mobile-front-ends/9

for fusionauth cloud
no, you just send the client id, and we know which tenant to holds that client id
