---
layout: doc
title: Migration
description: How to migrate your users to FusionAuth.
---
:page-liquid:

== Overview

This guide will help you set up a multi-tenant application in FusionAuth. Tenants are logical separations of users, applications and other entities in FusionAuth.

TOC TODO

== Why Multi-Tenant

There are many reasons why you might be interested in a multi-tenant FusionAuth installation. The overriding reason is the logical separation it provides. While you have only one FusionAuth instance to manage, users, applications, and other entities are logically separated. Even FusionAuth API keys can be tied to tenants. 

You might be interested in building an application which you'll offer as a SaaS (Software as a Service). In this case, you can private label your application using tenants. All user information within each tenant will be entirely separate.

Another use case might be for different environments. For instance, on one FusionAuth instance, you could run integration, user acceptance and developer environments. 

You also might want to provide a tenant for each developer on a dedicated development server. This would allow developers free reign to add, remove and modify entities in their FusionAuth tenant, while keeping them insulated from each other.

There also may be situations where you have settings that need to be different for different sets of users. Examples of such settings include password rules, the look and feel of the login pages, or webhook transaction level.

== Multi-Tenant Concepts

XXX TODO?

To make things a bit more concrete, let's use an example. Let's talk about Pied Piper Video Chat (or PPVC for short). It will be so much better than Slack chat with patented middle out compression. This application will have multiple tenants. Every one who signs up will get a domain name like `companyx.piedpiper.com`.

Before this guide covers how to set up multi-tenancy, let's cover what can be configured at the tenant level. There are five general categories of modifiable entities in FusionAuth:

* Tenant scoped entities
* Tenant attached entities
* Application scoped entities
* Application attached entities
* Global "things"

A "scoped" entity is contained within the enclosing entity, and if the latter is deleted, the former will be as well. For instance, a user is scoped to a tenant, and if that tenant is deleted, the user will be as well. 

Scoped entities cannot be shared between multiple entities to which they are scoped. If the Pied Piper chat application needs groups for different user privileges, each tenant would have its own "Admin Group", "Moderator Group" and so on.

An "attached" entity is affiliated with an enclosing entity, but if the latter is deleted, the former will continue to exist. For instance, a signing key is associated with a tenant's JWT configuration. If that tenant is deleted, the signing key's association with the tenant is removed, but the tenant is not. 

Attached entities can be re-used between entities. For example, if the Pied Piper chat application needs to add a user privilege claim to a JWT, the same Lambda can be used.

TODO extract to share with core concepts?

=== Tenant Scoped 

Here is a list of items that are tenant scoped:

* Users
* Groups
* API Keys (optionally)
* Applications
* Entities

=== Tenant Attached 

Here is a partial list of tenant attached items:

* Email templates (some of them)
* Forms (some of them)
* Themes
* Connectors
* Consents
* User actions
* Webhooks

=== Application Scoped

Here is a list of application scoped items.

* Registrations
* Roles

Because an application is tenant scoped, the above entities are also scoped to a tenant. They cannot be used across tenants. For example, if a tenant containing the containing application is deleted, the registrations for a given application will also be deleted.

=== Application Attached

Here is a partial list of application attached things:

* Identity providers
* Email templates (some of them)
* Forms (some of them)
* Lambdas

=== Global Items

There are items global in scope. These are typically scoped under `system` in the API namespace.

* API Keys (optionally)
* Login reports?
* Logs

Additionally, there are configuration settings for CORS which are shared between all the tenants in an instance.

The administrative user interface is also shared between tenants. There is no way to grant access to the FusionAuth administrative user interface but limit the user to a single tenant. There is an https://github.com/FusionAuth/fusionauth-issues/issues/91[open issue].

If you need separation of global configuration, or if you need true physical separation due to different regulatory regimes, you can run multiple FusionAuth instances. If you need to sync configuration between them, script your changes using the API, terraform provider, or client libraries.

== Components of a Multi Tenant Setup

While every application is different, there are common components to any multi tenant application.

* The control plane application
* The data plane application
* FusionAuth tenants and applications
* Data plane application tenant determination 
* Initial and deferred tenant setup component
* The tenant object

Let's look at each of these briefly. I'll continue to use the example of the video chat application built by the Pied Piper corporation (with inside out compression, of course) to illustrate some of these concepts.

=== The Control Plane Application

When you have a multi tenant SaaS application, you need some way to manage those tenants. Unapologetically borrowing from the https://en.wikipedia.org/wiki/Control_plane[network routing analogy], you need to build a control plane application to manage user and tenant creation. This is also where you can integrate billing and general account management if you are charging for your application.

Pied Piper Video Chat has to have an application of this type, which will let users sign up for Pied Piper Video Chat for their company. They need to be able to do other things like set up the PPVC url for their company, customize it, and set up billing. But this application doesn't need to support the chatting interface. This application is essentially a tenant management portal, where users can modify settings of their tenants.

For PPVC, this will likely be a web application, but the actual implementation details don't really matter for the purposes of multitenancy.


=== The Data Plane Application

This is the application that your users want to offer to their users. For PPVC, that is the video chat application. This application will have users with roles and may have payment or other account options as well. But while there may be overlap, the features of this application aren't the same as that of the control plane appliation. For one thing, there is no need to create separate tenants in this application, and the users of the video chat application may be entirely seperate from that of the management application. 

For PPVC, this will likely be a web application, but it could also be a mobile application as well. The actual implementation details don't really matter for the purposes of this document.

Note that the control plane and data plane applications are conceptually different, but do not need to be physically different. You could, in other words, implement them in the same web application. This may make sense to do initially, because there will be database overlap between them. 

As you grow, that may change. They will probably have different SLAs, it might be ok for one of them to have more downtime than the other, and they'll have different features and release cycles. So you can think about splitting them apart at some point. But for an initial implementation, it may be simpler to build them together. That's an implementation choice for you to consider.



=== FusionAuth Tenants and Applications

For each of the web, mobile or other applications that are built, a corresponding FusionAuth entity should be created.

For example, the control plane application will have a corresponding FusionAuth tenant where the users of the control plane application will be stored. It will also have a FusionAuth application to record the configuration needed to login to that application. 

Because you are building a multi tenant application, each data plane application will have a FusionAuth tenant and a FusionAuth application. 

So, for the Pied Piper Video Chat control plane application, there'd be a tenant. Call it the PPVC tenant. This is where users of the SaaS application would sign up and configure their instance of the video chat application. 

Each time a user signed up and created a new instance, there'd also be a new data plane tenant. Let's say that an employee at Raviga signs up for PPVC. A new FusionAuth tenant will be created for Raviga, and within that tenant a new FusionAuth application. This Raviga tenant would be where all Raviga users of the PPVC would be stored. 

This configuration information must be stored somewhere. The best place is in the PPVC database. The creation of the FusionAuth configuration can, however, be automated.

=== Data Plane Application Tenant Determination 

The data plane application needs to differentiate between the different tenants. If everything is hosted at ppvc.com, there are a few ways to do so:

* The hostname: raviga.ppvc.com would point to the Raviga instance of the application. And hooli.ppvc.com would point to the Hooli instsance. This is similiar to how Slack operates.
* User choice: The user logs in and is presented with a list of data plane applications to which they can login (or transparently SSO into). In this case, you can present this option in the control plane application.
* User or request attributes: If there is some way for the system to know which data plane application is associated with the user, the user may not need to be prompted. For instance, if the system can read network or user agent attributes to determine the appropriate data plane application, it should do so. 

In many cases, a hostname is the easiest way to do this differentiation. Using this is memorable to the user, works well with internet standards like cookies, and scales well. That's the approach this document will take.

=== Tenant Setup

When a user signs up in the control plane application and creates a new tenant, there are a number of things that need to happen.

The following configuration needs to occur:

* Hostname setup, which can be handled with DNS wildcarding
* Creation of a FusionAuth tenant and a FusionAuth application. This will allow the new data plane application to let users log in.
* Any needed configuration of the data plane application. For example, the PPVC application might allow users at a premium level to have 10 chat rooms, whereas users at the basic level could only have 2. 

Since the new tenant application isn't usable without these configuration settings, they should take place synchronously. 

There is also some optional configuration:

* Creating a user within the FusionAuth tenant for initial sign in.
* Creating any FusionAuth roles that might be applicable, such as an `admin` role.
* Customizing the theme of the FusionAuth hosted login pages with items like custom colors and logos.

Since the new tenant application is usable without these changes, they can take place asynchronously. 

=== The Tenant Object

Within your control plane application's datastore, you'll want to store metadata about the tenants. This is useful both for the users to modify their information, for the data plane application to deliver proper functionality, and for reporting as your business grows. 

This tenant object could have customization information.

Here are some attributes you might need in your tenant object if you were implementing multitenancy with FusionAuth:

* Owning user id: which user created this tenant. It could be a one to one, or one to many mapping depending on your needs.
* Hostname: the user selected hostname to which users of the PPVC chat application for an organization will go. Something like raviga.ppvc.com
* FusionAuth tenant id: the tenant created in FusionAuth during the setup.
* FusionAuth client id and client secret: these are used during the login process for the data plane application.
* Custom attributes such as a logo or background color for the hosted login pages. 
* An API key and API key id. This is useful if the control plane application needs to modify FusionAuth configuration. This API key could even be exposed to the administrators of the data plane application to, for example, write a script to pull a list of their users.

== Registration and Login Flows

Let's get more concrete. Here are is the registration flow for the control plane application. 

++++
{% plantuml source: _diagrams/docs/guides/control-plane-registration.plantuml, alt: "Registration process for the control plane application." %}
++++

Here's the login flow for a data plane application. Note that apart from the lookup of the tenant configuration by hostname, this is a pretty typical Authorization Code grant.

++++
{% plantuml source: _diagrams/docs/guides/data-plane-login.plantuml, alt: "Login process for the data plane application." %}
++++

== Example Application

Let's continue to build out our Pied Piper video chat application. Let's talk about what this application needs:

* A way for users to sign up to set up a video chat space. This will include their desired hostname: `companyA.chat.piedpiper.com` or `organizationB.chat.piedpiper.com`.
* A way for users to sign up for a given video chat space: `companyA.chat.piedpiper.com`.
* A way for users to log in to a specific video chat space: `companyA.chat.piedpiper.com`.
* An API key, tied to a tenant. This will allow users to automate management of any users within their tenant.
* Video chat functionality.

This guide will build an application meeting all of these requirements, except for the last one. That is left as an exercise for the reader. Here's https://github.com/FusionAuth/fusionauth-example-python-multi-tenant[the GitHub repo TBD] with working code if you'd like.

=== Prerequisites

This application will be written in using symfony, so you'll need symfony, php and a database. If you don't have that, https://symfony.com/doc/current/setup.html[install symfony], https://www.php.net/manual/en/install.php[php] and https://dev.mysql.com/doc/mysql-installation-excerpt/8.0/en/[mysql]. 

You'll also need to create a mysql user. 


https://stackoverflow.com/questions/53066962/an-exception-occurred-in-driver-sqlstatehy000-2054-the-server-requested-aut
After you create the user, convert their password to the legacy password format

ALTER USER 'username'@'ip_address' IDENTIFIED WITH mysql_native_password BY 'password';

You'll also need a running FusionAuth instance. Visit the link:/docs/v1/tech/installation-guide/[installation guides] and choose one of the many ways to install it.



=== Setting Up 

Create the application.


symfony new piedpipervideochat --full 

set up the connection to the database in your .env.local file


This code is running symfony version 5.2.6, the latest stable release at the time.

cd piedpipervideochat 

require some needed libraries
composer require symfony/orm-pack; composer require --dev symfony/maker-bundle
symfony composer require twig
composer require fusionauth/fusionauth-client
symfony composer require annotations
composer require knpuniversity/oauth2-client-bundle
composer require jerryhopper/oauth2-fusionauth

start a new tab and start the server

symfony server:start

=== Build the Video Application

Let's build the bones of the video application. We won't build a login form, as we'll be using FusionAuth's hosted login pages. But we'll add a home page for the video application, and then a chat page. Building the middle out compression algorithm will be left as an exercise for the user.

Add two controllers to the symfony applicatiion.

symfony add controller home page

symfony add controller chat page

=== Add Login with FusionAuth

add a user class

symfony console make:user

Add an authorized redirect URL:

http://localhost:8000/connect/fusionauth/check

Let's add login with FusionAuth, without tenants. 

link https://github.com/FusionAuth/fusionauth-site/pull/699/files

Now that we've logged in with FusionAuth, let's create a form in Symfony to add a tenant. Users can create one tenant.

[NOTE]
====
You could create the tenant automatically on user creation using webhooks as well. This would require capturing additional information at registration, which you could do with link:advanced-registration-forms/[Advanced Registration Forms], a reactor feature.
====

=== Create the Tenant in Symfony

Create an Tenant entity and a one to one relationship between the tenant and the user.
Add an application id, fusionauth tenant id, api key, hostname and a color. As you build this out, you could add logos or other tenant related information. The user will provide the hostname and the color, the other information will be added before the symfony tenant object is saved.

 1222  symfony console make:entity Tenant 
 1223  php bin/console make:migration
 1224  php bin/console doctrine:migrations:migrate

Here's what the Tenant will look like: TBD update!

----
<?php

namespace App\Entity;

use App\Repository\TenantRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TenantRepository::class)
 */
class Tenant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $applicationId;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="string", length=255)
     */
    private $hostname;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="string", length=6)
     */
    private $backgroundColorCode;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="tenant", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fusionAuthTenantId;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $apiKey;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getApplicationId(): ?string
    {
        return $this->applicationId;
    }

    public function setApplicationId(string $applicationId): self
    {
        $this->applicationId = $applicationId;

        return $this;
    }

    public function getHostname(): ?string
    {
        return $this->hostname;
    }

    public function setHostname(string $hostname): self
    {
        $this->hostname = $hostname;

        return $this;
    }

    public function getBackgroundColorCode(): ?string
    {
        return $this->backgroundColorCode;
    }

    public function setBackgroundColorCode(string $backgroundColorCode): self
    {
        $this->backgroundColorCode = $backgroundColorCode;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getFusionAuthTenantId(): ?string
    {
        return $this->fusionAuthTenantId;
    }

    public function setFusionAuthTenantId(string $fusionAuthTenantId): self
    {
        $this->fusionAuthTenantId = $fusionAuthTenantId;

        return $this;
    }

    public function getApiKey(): ?string
    {
        return $this->apiKey;
    }

    public function setApiKey(string $apiKey): self
    {
        $this->apiKey = $apiKey;

        return $this;
    }
}
----

And then add a form

and add the form to the nav when a user is logged in. We'll only be allowing one tenant per user right now.

we'll set up the FusionAuth entities using a pre persist hook, an entity listener and the FusionAuth API.

https://symfony.com/doc/current/doctrine/events.html


login and add a key manager key

Pic TBD

create a blueprint tenant. This is where you can create all the settings for your tenants such as password complexity. These will be modifiable by the copied tenants, but will serve as a shortcut for creation.


Then update your .env.local with the key and your config/services.yaml to add the key as a parameter and restart symfony.




how do we know what tenant to show?
hostname mapping.

then update the tenant success field to show the login page

and also an event to add a user















configure 

Add a tenant model in symfony.


Set up an application in FusionAuth, and add the application id and the color "gray" to symfony.

add symfony routes to send people to login and logout, and send to chat page

Have a user login by going to the

=== Manually Set up a Tenant

Let's test things out by manually creating a tenant.

Add them to the symfony system
create the tenant object

Do the fusionauth stuff
create a tenant 
create an application
create an application
enable self service registration
create a user
create a tenant scoped API key
copy the theme

modify the color
body { background-color: red; }

update the tenant object

log the user in

add registration link

=== Automate it

create a key manager API key
- use this to create a tenant scoped API key
create a none key manager API key
- use this for the automation, and limit the permissions

do the following steps above by using the api. do a syncrhonous webhook (with note that you might want it to be async later)


END

=== Setting Up FusionAuth Tenants

Let's manage FusionAuth configuration using the php client and doctrine migrations. 

First, log in to FusionAuth and create an API key. You can do this by navigating to [breadcrumb]#Settings -> API Keys#. Add a global API key with unlimited permissions, since any kind of configuration may be set here.

TBD image

Add the value to your .env.local file

```
FUSIONAUTH_API_KEY=...
```

then add the followign to your config/services.yaml

```yaml
parameters:
    fusionauth_api_key: '%env(FUSIONAUTH_API_KEY)%' # new line
```

This lets us pull the API key from the environment, which is less dangerous than checking it in.

FusionAuth ships with a default tenant, but to have full separation, let's add a new tenant. 


generate an empty migration

php bin/console doctrine:migrations:generate 

you should see output like

 Generated new migration class to "/Users/dan/work/fusionauth-example-python-multi-tenant/piedpipervideochat/migrations/Version20210401222131.php"
 
 To run just this migration for testing purposes, you can use migrations:execute --up 'DoctrineMigrations\Version20210401222131'
 
 To revert the migration you can use migrations:execute --down 'DoctrineMigrations\Version20210401222131'

edit migrations/Version20210401222131.php

and add in this code

...

You can then run this to see the status of the migration

php bin/console doctrine:migrations:status

and this to run it:

php bin/console doctrine:migrations:execute

This will let you manage the configuration of your FusionAuth server in a version controlled manner.


New tenant with one application created on registration via webhook, new theme, and update CSS for the theme.

Also map 




Python application handing the tenant hostnames as well as the oauth redirects.

== Tenant Level Customization

Customization available
Pretty much everything. Here are the high points.
Themes
Should probably customize them some.
Registration forms (with advanced reg forms)
Password rules
Social sign on

== Limits
Resources, primarily, but we have people running thousands of tenants in FA. 
Access to fusionauth admin ui
Intermixing of login records/other logs across tenants.
I’m not aware of any other limits

tenant limitations from the limitations doc
social sign on providers (only one of those)

https://fusionauth.io/community/forum/topic/936/newbie-question-on-urls-for-multitenant-applications
https://fusionauth.io/community/forum/topic/900/authentication-for-an-application-with-web-client-and-mobile-front-ends/9

for fusionauth cloud
no, you just send the client id, and we know which tenant to holds that client id



api key api

is it multi tenant or multitenant or multi-tenant?
