---
layout: doc
title: Passwordless authentication
description: Learn how to create a passwordless experience for your end users.
---

== What is passwordless

Passwordless authentication is an umbrella term for any auth system where a user doesn't use a password to prove their identity. With FusionAuth, passwordless is by default implemented with a one use, timebound token, delivered by email. By using the passwordless API you can deliver your token via alternative methods like SMS or push notifications if that meets your requirements. 

This guide will walk through FusionAuths' passwordless authentication, including the default implmentation, the APIs you can use to build a custom experience, and settings to be aware of. 


== When does it make sense

Passwordless authentication removes a barrier from the user experience. Rather than having to remember which password they used, the user provides their email address and is authenticated through a one time link.

This also prevent users from using a common password across multiple different applications; no longer do you need to worry about a data breach from another website. Password brute forcing, where an attacker tries to login with many passwords against a system, is also no longer an issue for your application.

You can either use the FusionAuth default UX, or you can customize your passwordless flow using the API. Let's look at each in turn.

== Setting up for passwordless

In either case, you'll want to take the following steps:

* Configure your SMTP server settings under Tenants / Email
* Create an application that you want to enable passwordless authentication for
* Turn on Passwordless under security

== Using FusionAuth UX

If you want a quick easy solution, use the FusionAuth pages. This layers passwordless authentication onto the link:/docs/v1/tech/oauth/#example-authorization-code-grant[authorization code grant]. That means that all of the normal client libraries and frameworks that support this common OAuth grant will work just fine.

TBD kickstart example?

Here's how you would do that in the administration UI:

* Configure the OAuth redirect URL as you would with a normal OAuth application
* Add a user and register them with your application. Make sure you register a valid email address.
* Go to your application login page
* Click the "Login with a magic link" button
* Enter the users email
* Go to your email
* Click on link

As soon as the link is clicked, the user is in a normal Authorization Code grant. You can link:/docs/v1/tech/oauth/#example-authorization-code-grant[consume the authorization code returned from the authorize request] or handle this grant using a library. Whatever you would normally do, you can, as it's just a normal grant.

You can customize how the login pages look using link:/docs/v1/tech/themes[themes]. You can also remove the username/password form if you want. This would require everyone to use passwordless authentication. 

Changing a theme changes it for all applications in a given tenant, however. If you want to require passwordless authentication on an application by application basis, set each application up in a separate tenant.

customize the name of the button

alb issue

== The API flow

You can also use the API. The link:/docs/v1/tech/apis/passwordless[passwordless API reference docs] will come in handy. You'll also want to make sure you set up an link:/docs/v1/tech/apis/authentication[API key] with the appropriate permissions.

There are a couple of reasons you might choose to use the APIs. 

* If you want to control every aspect of the login experience.
* If you want to deliver the one time code via text message, push notification or anything other than email

Note, you'll still need to enable passwordless authentication for your application, as outlined above.

=== Calling the API


==== Starting Login
To use the API, you need to start a passwordless session. You do that with a call to `/api/passwordless/start`. Here's a typical request object:

[source,json]
.Start Passwordless Request JSON
----
include::docs/src/json/passwordless/start-request.json[]
----

The `state` parameter is completely optional, but will be returned to your application on successful login. This can be useful if you want to allow someone to act anonymously on your site and then be able to login and still capture those actions. For example, if you have a shopping site, you may want to allow someone to add items to their cart anonymously. Once someone has logged in, you should associate the previous cart id with the authenticated user. In this example, the state object might look like:

[source,json]
----
"state" : { "cart_id" : 1234 } 
----

This begins the authentication process. It returns:

[source,json]
.Start Passwordless Response JSON 
----
include::docs/src/json/passwordless/start-response.json[]
----

This is the code that the user must enter. Now you want to get that code to your end user however you want. If you want to use FusionAuth to send the code, see <<Sending Email>>

==== Sending email

This is an optional API call. If you want to send the passwordless code via the email server configured in FusionAuth, you may use the `/api/passwordless/send` API endpoint. 

Using this gets you the benefits of the FusionAuth locale-aware email templates and email sending capabilities without requiring you to use the FusionAuth login forms.

==== Completing Login

Once the user has the code, they will want to go to a URL and provide it. This is a page you'll build this page. When the user submits the code, call the `/api/passwordless/login` endpoint and pass the provided string. You can also pass other information such as IP address, but the code is the only required parameter.

[source,json]
.Complete Passwordless Request JSON 
----
include::docs/src/json/passwordless/start-response.json[]
----

If the code is valid, your application will receive available user data and an access token. If you provided any data in the `state` parameter when starting the authentication process, it will also be included in the available user data, under the `state` key.

[source,json]
.Complete Passwordless Response JSON 
----
include::docs/src/json/users/passwordless-login-response.json[]
----

The user is now authenticated. Your application has user data, pre-existing state if provided, and a JWT token which can be used to authenticate with other applications or link:/docs/v1/tech/apis/jwt#validate-a-jwt[validated].

===== Additional complete parameters

The `noJWT` parameter is an optional parameter to the login completion API call.

JWTs are typically passed to other applications such as an API server to enable access to protected resources (link:/learn/expert-advice/tokens/[more about JWTs]). If you are using this passwordless flow and are only interested in the user authentication and data returned, then the JWT is of no use to you. Since creating the JWT and signing it take resources, you can increase the volume of authentication requests for a given FusionAuth configuration by passing the `noJWT` parameter. 

==== Common failure paths

The code provided is only valid for one time use. It also expires. 

If the code has expired or has been used, or there is some other reason preventing login, a 4XX error will be returned. Please consult the link:/docs/v1/tech/apis/passwordless[passwordless API reference docs] for more details.
If the code has been used already or has exp

== Customizing passwordless

There are a number of ways you can configure the passwordless implementation to best meet your application's needs.

=== Templates

You can customize the email template sent when the passwordless authentication process begins. Since the template references "FusionAuth", you almost certainly will want to modify this, or replace it with an entirely different template. You can use any Apache FreeMarker built-ins within the template. Make sure you modify both the HTML and text templates:

TBD move these to more normal includes
.HTML
[source,text]
----
include::docs/src/email/passwordless.html[] 
----

.Text
[source,text]
----
include::docs/src/email/passwordless.txt[]
----

You can localize the templates as well.

TBD image of localization of templates

== Customizing code generation

You can also modify the lifetime of the code sent to users. By default it is 180 seconds, but you can change this per tenant.

TBD image of tenant settings

You can change the type of the code generated, including the length and strategy. You can have the code be digits only, alphanumeric, only alphabetic or encoded bytes. Encoded bytes is the default. You can also set the length of the delivered code based on the strategy.

You may have security requirements that specify a certain length of code. You might want to make such changes if you choose an alternate delivery system, such as a text message. For instance, having a user enter a six digit alphanumeric string that has been sent to them by SMS is a lot easier than a 64 byte string.

== Security

Of course, if the user’s email account is hijacked, the account is compromised. Many organizations have policies and protections around email passwords. XXX And it’s easier to regularly change a password or turn on two factor authentication with one account than across all accounts.

== Conclusion

FusionAuth makes passwordless authentication easy out of the box. But if Passwordless 

TODO


move the email templates to the correct place

create images

blog post -- kickstart, rails 

troubleshooting
- email server

TBD state not needed in template?
If you depend on the state parameter, make sure you preserve the `list` built-in call when you modify the templates:

----
[#list state!{} as key, value][#if key != "tenantId" && value??][#assign url = url + "&" + key?url + "=" + value?url/][/#if][/#list]
----

If you do not, the `state` parameter TBD
