---
layout: doc
title: Passwordless authentication
description: Learn how to create a passwordless experience for your end users.
---

== What is passwordless

Passwordless authentication is an umbrella term for any auth system where a user doesn't use a password to prove their identity. With FusionAuth, passwordless is by default implemented with a one use, timebound token, delivered by email. By using the passwordless API you can deliver your token via alternative methods like SMS or push notifications if that meets your requirements. 

This guide will walk through FusionAuths' passwordless authentication, including the default implmentation, the APIs you can use to build a custom experience, and settings to be aware of. 


== When does it make sense

Passwordless authentication removes a barrier from the user experience. Rather than having to remember which password they used, the user provides their email address and is authenticated through a one time link.

This also prevent users from using a common password across multiple different applications; no longer do you need to worry about a data breach from another website. Password brute forcing, where an attacker tries to login with many passwords against a system, is also no longer an issue for your application.

You can either use the FusionAuth default UX, or you can customize your passwordless flow using the API. Let's look at each in turn.

== Using FusionAuth UX

If you want a quick easy solution, use the FusionAuth pages. This layers passwordless authentication onto the link:/docs/v1/tech/oauth/#example-authorization-code-grant[authorization code grant]. That means that all of the normal client libraries and frameworks that support this common OAuth grant will work just fine.

TBD kickstart example?

Here's how you would do that in the administration UI:

* Configure your SMTP server settings under Tenants / Email
* Create an application that you want to enable passwordless authentication for
* Turn on Passwordless under security
* Configure the OAuth redirect URL as you would with a normal OAuth application
* Add a user and register them with your application. Make sure you register a valid email address.
* Go to your application login page
* Click the "Login with a magic link" button
* Enter the users email
* Go to your email
* Click on link

Boom, you’re into the OAuth authorization code flow. You can link:/docs/v1/tech/oauth/#example-authorization-code-grant["Consume the authorization code returned from the authorize request"] or handle this grant however you normally would.

You can customize how the pages look using link:/docs/v1/tech/themes[themes].If you want to customize the login screen, check out themes. That’s where you can also remove the username/password form if you want to allow only passwordless authentication. Changing a theme changes it for all applications in a given tenant, so if you want to allow only passwordless authentication for an application, it’s suggested you set that up in a separate tenant so that you can continue to use the normal username/password method for the fusionauth administration screens.




customize the name of the button

alb issue

== The API flow

state

== Customizing passwordless

There are a number of ways you can tweak the passwordless implementation.

=== Templates

You can customize the email template sent when the passwordless authentication process begins. Since the template references "FusionAuth", you almost certainly will want to modify this, or replace it with an entirely different template. You can use any Apache FreeMarker built-ins within the template. Make sure you modify both the HTML and text templates:

TBD move these to more normal includes
.HTML
[source,text]
----
include::docs/src/email/passwordless.html[] 
----

.Text
[source,text]
----
include::docs/src/email/passwordless.txt[]
----


If you modify the email templates and depend on the state parameter, make sure you keep that parameter on your URL; that is the list clause.

You can localize the templates as well.

TBD image of localization of templates

=== Code characteristics

You can also modify the lifetime of the code. By default it is 180 seconds, but you can modify that in the tenant settings.

TBD image of tenant settings

You can also change the type of the code generated, including the length and strategy. You can have the code be digits only, alphanumeric, only alphabetic or encoded bytes, the default. Each strategy has different token length limits.


== Security


Of course, if the user’s email account is hijacked, the account is compromised. Many organizations have policies and protections around email passwords. XXX And it’s easier to regularly change a password or turn on two factor authentication with one account than across all accounts.

This tutorial shows you how to migrate user data from a single existing user database into FusionAuth.

In addition to the example code provided here, you may find example code relevant to your migration in our https://github.com/FusionAuth/fusionauth-import-scripts[Import Scripts] GitHub repository.

In many cases, you'll have an existing user database in MySQL, Mongo, or another similar database. In many cases, your user table (or objects) will contain the user information that your application needs in columns or properties. Here's an example table structure for a relational database for a user:

[source,sql]
----
CREATE TABLE user (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  profile_picture_url VARCHAR(255) NOT NULL,
  profile_description TEXT,
  role VARCHAR(255) NOT NULL,
  ...
);
----

This data will be migrated into FusionAuth by exporting it from the existing database and then importing it into FusionAuth.

=== Password Encryption

The first step of the migration process is to determine how passwords are encrypted in your current user database. If they are not encrypted, you can skip this step and FusionAuth will automatically encrypt them for you during the import process. Once you have determined the encryption used in your existing database, you will need to write a password encryptor plugin. The documentation for writing plugins and a password encryptor are located here:

* link:../plugins/writing-a-plugin[Plugins]
* link:../plugins/password-encryptors[Password Encryptors]

=== Create the Applications

Next, you will need to create all of the Applications in FusionAuth that users will be registered with. For example, you might have a website and a forum that are both using the same user database. In this case, you will need to create a FusionAuth Application for your website and another Application for your forum.

Once you have created the Applications, store the IDs for each so that you can use them during the import process.

For our example above, we will assume only a single Application called Website with a UUID of `79a34811-d627-4751-bb9c-9ab148ab8dc9`.

=== Determine FusionAuth Data Locations

FusionAuth has a number of properties on the base User object. You can read about those properties in the link:../apis/users#create-a-user[Create a User] API section. Your existing database might have additional user properties that you need to migrate. These can be stored in the `data` object inside the `User` object. This object is also described in link:../apis/users#create-a-user[Create a User] API section. The `data` object allows completely free-form data to be stored.

Additionally, each user can have 0 or more registrations created during the import. Registrations are used to control access to your application(s) and also provide authorization via roles for each application. Registrations can also have a `data` object to store additional attributes for each user. You will need to determine if you want to store your additional user data on the base User object or the Registration object. The choice might depend on if the data is used globally for all of your applications or just in a single application.

For our example above, we'll place all of our extra data in a Registration object for our `Website` Application.

=== Export/Import the Existing User Data

The simplest way to migrate the data from an existing database to FusionAuth is to write a program or script that reads records from the existing database and batch imports them into FusionAuth. We won't write a complete script here, but here is some pseudo code you can use when building your script:

[source,groovy]
.Migration Script Example
----
def existingUser
def importUsers = []

while ((existingUser = readNextUser()) != null) {
  def fusionauthUser = {
    fullName: existingUser.name,
    email: existingUser.email,
    password: existingUser.password,
    encryptionScheme: "my-custom-encryption-scheme",
    imageURL: existingUser.profilePicture,
    registrations: [
      {
        applicationID: "79a34811-d627-4751-bb9c-9ab148ab8dc9",
        data: {
          profileDescription: existingUser.profileDescription
        }
        roles: [
          existingUser.role
        ]
      }
    ]
  }

  importUsers.add(fusionauthUser)
}

FusionAuthClient client = new FusionAuthClient("http://localhost:9011", "my-api-key")
client.importUsers(new ImportRequest(importUsers))
----

This code reads each user from the existing database, creates a new FusionAuth User object from the existing user data, and then bulk imports all of the users into FusionAuth in one request. Generally speaking this process works for small databases (under 10,000 users). If you have a large database, you will want to import users in blocks of 1,000 or 10,000 to avoid crashing FusionAuth.

This example uses a FusionAuthClient to perform the import. You may also call the link:../apis/users#import-users[Import Users] API directly if you prefer (or if a FusionAuthClient is not available for your language of choice).

If you need further assistance migrating to FusionAuth, please ask a question on https://stackoverflow.com/questions/tagged/fusionauth[Stack Overflow, window="_blank"] or open an issue on https://github.com/FusionAuth/fusionauth-issues/issues/new/choose[Github, window="_blank"] if you have additional questions. If you have a licensed edition you may send a request to support@fusionauth.io.
