---
layout: doc
title: Google Identity Provider APIs
description: APIs for creating, retrieving, updating and disabling the Google identity provider
---

== Overview

[NOTE.since]
====
This API has been available since 1.1.0
====

The Google identity provider type will use the Google OAuth v2.0 login API. it will provide a `Login with Google` button on FusionAuth's login page that will leverage the Google login pop-up dialog. Additionally, this identity provider will call Google's `/oauth2/v3/tokeninfo` API to load additional details about the user and store them in FusionAuth. Here are the user details from the Google JWT that FusionAuth stores and the User object fields they are stored in:

* `email` -> `email`
* `given_name` -> `firstName`
* `family_name` -> `lastName`
* `name` -> `fullName`
* `picture` -> `imageUrl`

FusionAuth will also store the Google `access_token` that is returned from the login pop-up dialog in the `UserRegistration` object inside the `tokens` Map. This Map stores the tokens from the various identity providers so that you can use them in your application to call their APIs.

=== Operations

* <<Create the Google Identity Provider>>
* <<Retrieve the Google Identity Provider>>
* <<Update the Google Identity Provider>>
* <<Delete the Google Identity Provider>>
* <<Complete the Google Login>>

== Create the Google Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Create the Google Identity Provider
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider#
--

The `type` property in the request JSON is used to determine that you are managing the Google identity provider.

include::docs/v1/tech/apis/identity-providers/_google-request-body.adoc[]

=== Response

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_google-response-body.adoc[]

== Retrieve the Google Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Retrieve the Google Identity Provider
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider?type=Google#
--

=== Response

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_google-response-body.adoc[]

== Update the Google Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Update the Google Identity Provider
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/identity-provider/#
--

=== Response

The response for this API contains the Google Identity Provider.

include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_google-response-body.adoc[]

== Delete the Google Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Delete the Google Identity Provider
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/identity-provider/?type=Google#
--

=== Response

This API does not return a JSON response body.

include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]

== Complete the Google Login

This API allows you to complete a Google login after authenticating a user using the Google API. If you are using the FusionAuth login UI with the Google button you will not utilize this API directly.

This API is intended to be used if you want to build your own login page and you have added the Google login button to your own login page and you then need to complete the login with FusionAuth.

For example, if you built your own login page, you could add a Login with Google button and complete the Google authentication. When you complete the Google authentication you will have been returned an id token from Google. Using this API you can pass that id token returned from Google to FusionAuth and we will complete the login workflow and reconcile the user to FusionAuth.

=== Request

link:authentication#no-authentication-required[icon:unlock-alt[role=green]] Complete Google Login
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider/login#
--

:loginProvider: Google
include::docs/v1/tech/apis/identity-providers/_identity-provider-login-request-body.adoc[]
:loginProvider!:

=== Response

The response for this API contains the User object.

:loginProvider: Google
include::docs/v1/tech/apis/identity-providers/_identity-provider-login-response-body.adoc[]
:loginProvider!:
