---
layout: doc
title: Twitter Identity Provider APIs
description: APIs for creating, retrieving, updating and disabling the Twitter identity providers
---

== Overview

[NOTE.since]
====
This API has been available since 1.1.0
====

The Twitter identity provider type will use the Twitter OAuth v1.0 login API. it will provide a `Login with Twitter` button on FusionAuth's login page that will leverage the Twitter login page directly. Additionally, this identity provider will call Twitter's `/1.1/account/verify_credentials.json` API to load additional details about the user and store them FusionAuth. Here are the user details from the Twitter API that FusionAuth stores and the User object fields they are stored in:

* `/email` -> `email`
* `/name` -> `fullName`
* `/profile_image_url_https` -> `imageUrl`
* `/screen_name` -> `username` (this is stored as the `username` in the UserRegistration object since it is not unique)

Twitter does not require a user to have an email address. However, to prevent account hijacking and take-over, FusionAuth prevents users from logging in with Twitter unless they have setup an email address in their Twitter account. Keep this in mind as you enable this identity provider.

Finally, FusionAuth stores the Twitter access token that is returned from the OAuth v1.0 login workflow in the `UserRegistration` object inside the `tokens` Map. This Map stores the tokens from the various identity providers so that you can use them in your application to call their APIs.

=== Operations

* <<Create the Twitter Identity Provider>>
* <<Retrieve the Twitter Identity Provider>>
* <<Update the Twitter Identity Provider>>
* <<Disable the Twitter Identity Provider>>

== Create the Twitter Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Create the Twitter Identity Provider
[.endpoint]
.URI
--
[method]#POST# [uri]#/api/identity-provider#
--

include::docs/v1/tech/apis/identity-providers/_twitter-request-body.adoc[]

=== Response

include::docs/v1/tech/apis/_standard-post-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_twitter-response-body.adoc[]

== Retrieve the Twitter Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Retrieve the Twitter Identity Provider
[.endpoint]
.URI
--
[method]#GET# [uri]#/api/identity-provider/?type=Twitter#
--

=== Response

include::docs/v1/tech/apis/_standard-get-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_twitter-response-body.adoc[]

== Update the Twitter Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Update the Twitter Identity Provider
[.endpoint]
.URI
--
[method]#PUT# [uri]#/api/identity-provider/#
--

include::docs/v1/tech/apis/identity-providers/_twitter-request-body.adoc[]

=== Response

The response for this API contains the Twitter Identity Provider.

include::docs/v1/tech/apis/_standard-put-response-codes.adoc[]

include::docs/v1/tech/apis/identity-providers/_twitter-response-body.adoc[]

== Disable the Twitter Identity Provider

=== Request

link:authentication#api-key-authentication[icon:lock[role=red]] Disable the Twitter Identity Provider
[.endpoint]
.URI
--
[method]#DELETE# [uri]#/api/identity-provider/?type=Twitter#
--

=== Response

This API does not return a JSON response body.

include::docs/v1/tech/apis/_standard-delete-response-codes.adoc[]