---
layout: doc
title: HAProxy API Gateway
description: HAProxy JWT integration
navcategory: developer
---

== Overview

HAProxy is a popular load-balancer that can also be used as an API Gateway. 

You can configure HAProxy to handle authorization to the services through JSON Web Tokens (JWTs) issued on behalf of a user authenticated by an identity provider.

In this document, you'll learn how to set up HAProxy with FusionAuth as the identity provider to protect a simple HTTP service.

== Prerequisites

* A FusionAuth instance running on a publicly accessible URL. You can spin up a link:/pricing[basic FusionAuth Cloud instance] or link:/docs/v1/tech/installation-guide/[install it on any server].
* An HAProxy instance routed to an HTTP service. You can follow the link:https://www.haproxy.com/blog/how-to-run-haproxy-with-docker/[this guide] to get a simple example running on Docker.
** If you have trouble getting the `haproxy` container from the guide to start, make sure your `haproxy.cfg` file ends with a blank line. Even whitespace on the last line will prevent the container from running.

== Restrict Access to your HAProxy Service

After following the HAProxy quickstart guide above, you can execute the following command in the terminal.

[source,shell,title="Curl to test HAProxy setup"]
----
curl -X GET -I http://localhost:80
----

If you have correctly set up HAProxy, this command will return `HTTP/1.1 200 OK`, indicating a successful connection to the service.
