@startuml
  !include ../../_config.plantuml

participant Browser as b
participant "Pied Piper" as pp
participant FusionAuth as f
participant "Azure AD" as aad
b -> pp : Click Login Link
pp -> b : Redirect to FusionAuth
b -> f : Request Login Page
f -> b : Send Login Page
b -> f : Clicks on 'Login With Azure AD'
f -> b : Redirects to Azure AD
b -> aad : Requests Login Page
aad -> b : Sends Login Page
b -> aad : Sends Credentials
aad -> b : Redirects to FusionAuth Redirect URL
b -> f : Requests FusionAuth Redirect URL
f -> f : Processes request, runs lambda, logs user into FusionAuth
f -> b : Redirects to Pied Piper Redirect URL 
b -> pp : Requests Pied Piper Redirect URL
pp -> f : Requests Token
f -> pp : Returns Token
pp -> pp : Stores token (could send it to Browser as cookie as well)
pp -> b : Redirects to Application pages
b -> pp : Makes authenticated request(s)
@enduml
