---
layout: doc
title: Twitter Identity Provider
description: Login with Twitter using the Twitter Identity Provider
---

:sectnumlevels: 0

== Overview

[NOTE]
====
Coming soon!
====

Until this tutorial is available, please find the Twitter Identity provider in the FusionAuth UI by navigating to [breadcrumb]#Settings# icon:chevron-right[role=breadcrumb] [breadcrumb]#Identity Providers# and click `Add provider` and select `Twitter` from the dialog.

There you may fill out the required fields after configuring a Twitter app in your Twitter developer console.


=== Twitter App configuration

https://developer.twitter.com/en/apps

=== App details

In this section, check `Enable Sign in with Twitter` and register the Callback URL.

The FusionAuth callback URL in the `App details` section. This URL will be your publicly available URL of FusionAuth with the `/oauth2/callback` suffix. For example if your publicly available URL is `\https://login.piedpiper.com`, the callback URL you would need to register would be `\https://login.piedpiper.com/oauth2/callback`.

FusionAuth will detect the public URL of your instance at runtime to send to Twitter as the callback URL. If you are behind a proxy, ensure that the `X-Forwarded-Host` and the `X-Forwarded-Proto` headers are added by your proxy if the host or protocol do not match what is behind the proxy. For example, if your public URL is using `https` and your proxy is performing SSL accelerating the URL behind the proxy may be `http`. In this scenario, most proxies will have added the `X-Forwarded-Proto` header to the request which will allow FusionAuth to send the correct URL to Twitter.

=== Keys and tokens

In this section, you will find the `Consumer API keys` which will include the key and secret needed to configure the FusionAuth Identity Provider for Twitter.

=== Permissions

In this section, check `Request email address from users`, without an email address, FusionAuth will not be able to complete the login workflow.