---
layout: doc
title: Twitter Identity Provider
description: Login with Twitter using the Twitter Identity Provider
---

:sectnumlevels: 0

== Overview

[NOTE]
====
Coming soon!
====

Until this tutorial is available, please find the Twitter Identity provider in the FusionAuth UI by navigating to [breadcrumb]#Settings# icon:chevron-right[role=breadcrumb] [breadcrumb]#Identity Providers# and click `Add provider` and select `Twitter` from the dialog.

There you may fill out the required fields after configuring a Twitter app in your Twitter developer console.


=== Twitter App configuration

https://developer.twitter.com/en/apps

=== App details

In this section, check `Enable Sign in with Twitter` and register the Callback URL.

The FusionAuth callback URL in the `App details` section. This URL will be your publicly available URL of FusionAuth with the `/oauth2/callback` suffix. For example if your publicly available URL is `\https://login.piedpiper.com`, the callback URL you would need to register would be `\https://login.piedpiper.com/oauth2/callback`.

=== Keys and tokens

In this section, you will find the `Consumer API keys` which will include the key and secret needed to configure the FusionAuth Identity Provider for Twitter.

=== Permissions

In this section, check `Request email address from users`, without an email address, FusionAuth will not be able to complete the login workflow.