@startuml
  !include ../../_config.plantuml

participant "Original Caller" as c
participant "FusionAuth" as f
participant "Webhook Recipient 1" as w1
participant "Webhook Recipient 2" as w2
participant "Webhook Recipient 3" as w3

c -> f  : Updates user
f -> w1  : Sends payload
f -> w2  : Sends payload
f -> w3  : Sends payload
f -> c  : Success, operation completes

@enduml
