@startuml
  !include ../../../../_config.plantuml

participant "User/Browser" as User
participant App
participant "todos.com" as API1
participant "reminders.com" as API2

  == ... Token Previously Stored In Session ... ==

User -> App : Request Todo Endpoint
App -> API1 : Request Todo Endpoint\nPassing Token From Session\nAlong In Header
API1 -> API1 : Validate Token
API1 -> App : Send Todo Data
App -> User : Send Todo Data
User -> App : Request Reminder Endpoint
App -> API2 : Request Reminder Endpoint\nPassing Token From Session\nAlong In Header
API2 -> API2 : Validate Token
API2 -> App : Send Reminder Data
App -> User : Send Reminder Data
@enduml
