@startuml
  !include ../../_config.plantuml

participant "HR Admin" as h
participant "HR System" as hs
participant "Cloud Computing Provider" as ccp
participant "Source Control System" as scs
participant "Ping Pong Tournament System" as ppts

h -> hs : Add user
hs -> ccp : Provision User
hs -> scs : Provision User
hs -> ppts : Provision User

@enduml
