=== SAML Response Fields

[.api]
[field]#samlResponse.assertion.attributes# [type]#[Map<String, List<String>>]#::
A map of the attributes of the user. This is sometimes call the claims of the user. Since SAML attributes can be multi-valued, you will need to wrap single values in Arrays like this:
+
[source,javascript]
----
samlResponse.assertion.attributes['firstName'] = [user.firstName];
----

[field]#samlResponse.assertion.conditions.audiences# [type]#[Array<String>]#::
A list of the audiences for this SAML response. By default, the `audience` or `issuer`, in that order, from the corresponding SAML identity provider configuration are used.

[field]#samlResponse.assertion.conditions.notBefore# [type]#[Long]#::
The instant that this assertion starts being valid. This is the number of milliseconds since Epoch UTC.

[field]#samlResponse.assertion.conditions.notOnOrAfter# [type]#[Long]#::
The instant that this assertion stops being valid. This is the number of milliseconds since Epoch UTC.

[field]#samlResponse.assertion.issuer# [type]#[String]#::
The issuer of this SAML assertion. This defaults to the `issuser` from the corresponding SAML identity provider configuration.

[field]#samlResponse.assertion.subject.nameID.format# [type]#[String]# [deprecated]#Deprecated#::
The `NameID` format for the id of the subject (user). FusionAuth uses the `emailaddress` format specified by the SAML specifications. It is not recommended that you change this unless you know what you are doing.
+
[deprecated]#Removed in 1.28.0#

[field]#samlResponse.assertion.subject.nameID.id# [type]#[String]# [deprecated]#Deprecated#::
The `NameID` id of the subject (user). This defaults to the user's email address. It is not recommended that you change this unless you know what you are doing.
+
[deprecated]#Removed in 1.28.0#

[field]#samlResponse.assertion.subject.nameIDs# [type]#[Array]# [since]#Available since 1.28.0#::
The array of `NameID` for the subject.
+
Prior to version `1.28.0`, this field was a single entry but has since been converted to an array.

[field]#samlResponse.assertion.subject.nameIDs``[x]``.format# [type]#[String]# [since]#Available since 1.28.0#::
The `NameID` format for the id of the subject (user). FusionAuth uses the `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress` format specified by the SAML specifications by default. It is not recommended that you change this unless you know what you are doing.

[field]#samlResponse.assertion.subject.nameIDs``[x]``.id# [type]#[String]# [since]#Available since 1.28.0#::
The `NameID` id of the subject (user). This defaults to the user's email address. It is not recommended that you change this unless you know what you are doing.

[field]#samlResponse.assertion.subject.confirmation.inResponseTo# [type]#[String]#::
This is the ID from the SAML request. It is not recommended that you change this unless you know what you are doing.

[field]#samlResponse.assertion.subject.confirmation.method# [type]#[String]#::
The confirmation method FusionAuth uses for the subject (user). This default to `Bearer`. It is not recommended that you change this unless you know what you are doing.

[field]#samlResponse.assertion.subject.confirmation.notBefore# [type]#[Long]#::
The instant that this assertion's subject starts being valid. This is the number of milliseconds since Epoch UTC.

[field]#samlResponse.assertion.subject.confirmation.notOnOrAfter# [type]#[Long]#::
The instant that this assertion's subject stops being valid. This is the number of milliseconds since Epoch UTC.

[field]#samlResponse.assertion.subject.confirmation.recipient# [type]#[String]#::
The recipient of the subject. This defaults to the callback URL (ACS).

[field]#samlResponse.destination# [type]#[String]#::
The destination of the SAML response. This defaults to the callback URL (ACS).

[field]#samlResponse.id# [type]#[String]#::
A unique identifier for the SAML response that is generated by FusionAuth.

[field]#samlResponse.inResponseTo# [type]#[String]#::
This is the ID from the SAML request. It is not recommended that you change this unless you know what you are doing.

[field]#samlResponse.issueInstant# [type]#[Long]#::
The instant that this assertion was created. This is the number of milliseconds since Epoch UTC.

[field]#samlResponse.issuer# [type]#[String]#::
This is the issuer of the SAML response. This defaults to the name of this FusionAuth deployment.

[field]#samlResponse.status.code# [type]#[String]#::
The status code of the SAML response. Whenever the lambda is called, this will always be `Success`.

[field]#samlResponse.status.message# [type]#[String]#::
The status message of the SAML response. Whenever the lambda is called, this will always be `null`.
