---
layout: doc
title: Client Credentials JWT Populate lambda
description: An overview of the Client Credentials JWT Populate lambda
---

:sectnumlevels: 0

== Client Credentials JWT Populate lambda

If you would like to augment the claims provided in the JWT before it has been signed you can specify a lambda in the JWT configuration. This lambda will be invoked prior to the token being signed and issued as a result of the client credentials grant, on behalf of an Entity.

When you create a new lambda using the FusionAuth UI we will provide you an empty function for you to implement. If you are using the API to create the lambda you will need to ensure your function has the following signature:

[source,javascript]
----
function populate(jwt, recipientEntity, targetEntities, permissions) {
  // Lambda code goes here
}
----

This lambda must contain a function named `populate` that takes four parameters. The parameters that the lambda is passed are:

* `jwt` - the claims object to be signed and return as the JWT payload
* `recipientEntity` - the Recipient Entity.  Example below.
* `targetEntities` - the Target Entities. Example below.
* `permissions` - the permissions assigned to the Entity. Example below.

The `recipientEntity` and `targetEntities` objects are well documented here in the link:/docs/v1/tech/apis/entity-management/entity-types[Permissions & Entity Types APIs] and link:/docs/v1/tech/apis/entity-management/entities[Entities API] documentation. The JWT object is a JavaScript object containing the JWT payload. See link:/docs/v1/tech/oauth/tokens[OpenID Connect & OAuth 2.0 Token].

You may add or modify anything in the `jwt` object. However, you may not modify the header keys or values of the JWT. FusionAuth also protects certain reserved claims. The following claims are considered reserved and modifications or removal will not be reflected in the final JWT payload:

- `exp`
- `iat`
- `sub`

== Assigning the lambda

Once a lambda is created, you must assign it. See the OAuth tab in the under tenants.

=== Example Entities and Permissions Objects

For these example objects (available in the lambda) there are three entities created (`reminder`, `todo`, and `email`) with an `api` entity type with `read` and `write` user defined permission values.

[source,json]
.Example JSON for `recipientEntity` object.
----
include::docs/v1/tech/lambdas/_recipientEntity.json[]
----

[source,json]
.Example JSON for `targetEntities` object.
----
include::docs/v1/tech/lambdas/_targetEntities.json[]
----

[source,json]
.Example JSON for `permissions` object.
----
include::docs/v1/tech/lambdas/_entityPermissions.json[]
----

=== Related

Related information about Client Credentials Grant can be found link:https://fusionauth.io/docs/v1/tech/oauth/#example-client-credentials-grant/[here].
