---
layout: doc
title: Google Reconcile
description: An overview of the Google Reconcile lambda
---

:sectnumlevels: 0

== Google Reconcile lambda

When an Google identity provider is used to complete a federated login request FusionAuth will use the email address to reconcile user. You may optionally utilize a lambda to customize the user and user registration during this authentication event.

When you create a new lambda using the FusionAuth UI we will provide you an empty function for you to implement.

If you are using the API to create the lambda you will need to ensure your function has the following signature:

[source,javascript]
----
function reconcile(user, registration, idToken) {
  // Lambda code goes here
}
----

This lambda must contain a function named `reconcile` that takes three parameters. The parameters that the lambda is passed are:

* `user` - the FusionAuth User object
* `registration` - the FusionAuth UserRegistration object
* `idToken` - the JSON payload returned by the Google Token Info API

The two FusionAuth objects are well documented here in the link:../apis/users[User API] and link:../apis/registrations[Registration API] documentation. The `jwt` may contain various user claims to utilize during the reconcile process.

== Assigning the lambda

Once a lambda is created, you may assign it to the Google identity provider in the IdP configuration.

== Default lambda

A default Google reconcile lambda is available in FusionAuth that may be used or modified. The default Google lambda function is documented below.

[source,javascript]
----
// This is the default Google reconcile, modify this to your liking.
function reconcile(user, registration, idToken) {

  // Un-comment this line to see the idToken object printed to the event log
  // console.info(JSON.stringify(idToken, null, 2));

  // The idToken is the response from the tokeninfo endpoint
  // https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint
  user.firstName = idToken.given_name;
  user.lastName = idToken.family_name;
  user.fullName = idToken.name;
  user.imageUrl = idToken.picture;
}
----

=== Limitations

The `user.username` field on the user will be ignored if modified by the lambda function. This is to mitigate the risks of an account takeover due to a non globally unique identifier.