---
layout: doc
title: HYPR Reconcile
description: An overview of the HYPR Reconcile lambda
---

:sectnumlevels: 0

== HYPR Reconcile lambda

When an HYPR identity provider is used to complete a federated login request. You may optionally utilize a lambda to customize the user and user registration during this authentication event.

When you create a new lambda using the FusionAuth UI we will provide you an empty function for you to implement.

If you are using the API to create the lambda you will need to ensure your function has the following signature:

[source,javascript]
----
function reconcile(user, registration) {
  // Lambda code goes here
}
----

This lambda must contain a function named `reconcile` that takes three parameters. The parameters that the lambda is passed are:

* `user` - the FusionAuth User object
* `registration` - the FusionAuth UserRegistration object

The two FusionAuth objects are well documented here in the link:/docs/v1/tech/apis/users[User API] and link:/docs/v1/tech/apis/registrations[Registration API] documentation.

== Assigning the lambda

Once a lambda is created, you may assign it to the HYPR identity provider in the IdP configuration.

Navigate to [breadcrumb]#Settings -> Identity Providers# and select your existing HYPR configuration or click [breadcrumb]#Add provider# and select HYPR if it has not yet been configured.

