---
layout: doc
title: LDAP Connector Reconcile
description: An overview of the LDAP Connector Reconcile lambda
---

:sectnumlevels: 0

== LDAP Connector Reconcile lambda

When an LDAP Connector is used to authenticate a user based upon the Tenant connector policies, the LDAP Connector lambda is used to map the LDAP attributes into a FusionAuth user.

When you create a new lambda using the FusionAuth UI we will provide you an empty function for you to implement.

If you are using the API to create the lambda you will need to ensure your function has the following signature:

[source,javascript]
----
function reconcile(user, userAttributes) {
  // Lambda code goes here
}
----

This lambda must contain a function named `reconcile` that takes two parameters. The parameters that the lambda is passed are:

* `user` - the FusionAuth User object
* `userAttributes` - the user attributes returned from LDAP during authentication

The FusionAuth user object is well documented the link:../apis/users[User API] documentation. The `userAttributes` object may contain various values returned by the LDAP server.

=== LDAP Attributes

LDAP attributes can be returned to FusionAuth in a string form or a byte array. Some attributes are considered non-string values and need to be provided in a byte array to be useful in the Lambda function.

A non-string attribute should be requested as a byte array. To request an attribute as a byte array, use the `;binary` LDAP attribute option as a suffix on your requested attribute. For example, instead of requesting `objectGuid`, you will request `objectGuid;binary`.

== Helper Functions

FusionAuth provides helper functions available in the Lambda function under the namespace `FusionAuth`.

=== Active Directory Object GUID to UUID

When using this connector with Microsoft Active Directory, the `objectGuid` attribute will need to be configured to be returned as a byte array. This can be accomplished by appending the suffix `;binary` as an LDAP attribute option to the `objectGuid` in the requested attributes configuration.

Values requested as a byte array will be provided to the lambda function as a Base64 encoded string. Here is an example usage of the FusionAuth helper to convert this base64 encoded string representation of the `objectGuid` to a UUID.

[source,javascript]
----
// Example usage to convert a Bas64 encoded Microsoft Active Directory objectGUID to a UUID
user.id = FusionAuth.ActiveDirectory.b64GuidToString(userAttributes['objectGuid;binary'])
----


== Assigning the lambda

Once a lambda is created, you may use it when adding an LDAP Connector in the Connector configuration.

Navigate to [breadcrumb]#Settings -> Connectors# and click [breadcrumb]#Add# and select LDAP when prompted to select a connector type.

== Example lambda

The following is a simple example of an LDAP Connector reconcile lambda. You will need to modify it to suit your needs.

[source,javascript]
----
// This is an example LDAP Connector reconcile, modify this to your liking.
function reconcile(user, userAttributes) {

  // Un-comment this line to see the userAttributes object printed to the event log
  // console.info(JSON.stringify(userAttributes, null, 2));

  // This assumes the 'uid' attribute is a string form of a UUID in the format
  // `8-4-4-4-12`. It will be necessary to ensure an attribute is returned by your LDAP
  // connection that can be used for the FusionAuth user Id.
  user.id = userAttributes.uid;
  user.active = true;

  user.email = userAttributes.mail;
  user.fullName = userAttributes.cn;

  // In this example, the registration is hard coded, you may also build this
  // dynamically based upon the returned LDAP attributes.
  user.registrations = [{
    applicationId: "5d562fea-9ba9-4d5c-b4a3-e57bb254d6db",
    roles = ['user', 'admin']
  }];

}
----
