---
layout: doc
title: Nintendo Reconcile
description: An overview of the Nintendo Reconcile lambda
---

:sectnumlevels: 0

== Nintendo Reconcile lambda
[NOTE]
====
This IdP is still under active development, but is still not code complete.
====

When an Nintendo identity provider is used to complete a federated login request to reconcile a user. Please note, there are multiple linking strategies when attempting to reconcile the user. Nintendo defaults to `CreatePendingLink`. You may optionally utilize a lambda to customize the user and user registration during this authentication event.

When you create a new lambda using the FusionAuth UI we will provide you an empty function for you to implement.

If you are using the API to create the lambda you will need to ensure your function has the following signature:

[source,javascript]
----
function reconcile(user, registration, userInfo) {
  // Lambda code goes here
}
----

This lambda must contain a function named `reconcile` that takes three parameters. The parameters that the lambda is passed are:

* `user` - the FusionAuth User object
* `registration` - the FusionAuth UserRegistration object
* `userInfo` - the JSON payload returned by the Nintendo Token Info API
// TODO 👆 check above for accuracy

The two FusionAuth objects are well documented here in the link:/docs/v1/tech/apis/users[User API] and link:/docs/v1/tech/apis/registrations[Registration API] documentation. The `userInfo` may contain various user claims depending upon the user's Nintendo configuration.

== Assigning the lambda

Once a lambda is created, you may assign it to the Nintendo identity provider in the IdP configuration.

Navigate to [breadcrumb]#Settings -> Identity Providers# and select your existing Nintendo configuration or click [breadcrumb]#Add provider# and select Nintendo if it has not yet been configured.

== Example lambda

There is not a example Nintendo reconcile lambda provided by FusionAuth. The following is an example lambda you can use as a starting point.

[source,javascript]
----
// Using the response from the Nintendo API, reconcile the User and User Registration.
function reconcile(user, registration, userInfo) {
  //  When writing a lambda we've added a few helpers to make life easier.
  //  console.info('Hello World');         # This will create an EventLog of type Information
  //  console.error('Not good.');          # This will create an EventLog of type Error
  //  console.debug('Step 42 completed.'); # This will create an EventLog of type Debug
  //
  //  To dump an entire object to the EventLog you can use JSON.stringify, for example:
  //  console.info(JSON.stringify(user));

  // Happy coding! Reconcile the User here.

  console.info('Hello World!');
}
----


