---
layout: doc
title: OpenID Connect Reconcile
description: An overview of the OpenID Connect Response Reconcile lambda
---

:sectnumlevels: 0

== OpenID Connect Reconcile lambda

When an OpenID Connect identity provider is used to complete a federated login request FusionAuth will use well known OpenID Connect claims to reconcile user.

It is common that the claims returned from the Userinfo endpoint during an OpenID Connect login request will contain custom claims defined by your identity provider. In order to utilize these custom claims you may wish to use a lambda assist FusionAuth during the login request to reconcile these claims to the FusionAuth user.

When you create a new lambda using the FusionAuth UI we will provide you an empty function for you to implement. If you are using the API to create the lambda you will need to ensure your function has the following signature:

[source,javascript]
----
function reconcile(user, registration, jwt, id_token) {
  // Lambda code goes here
}
----

This lambda must contain a function named `reconcile` that takes at least three parameters, a fourth parameter is optional. The parameters that the lambda is passed are:

* `user` - the FusionAuth User object
* `registration` - the FusionAuth UserRegistration object
* `jwt` - the JSON payload returned from the OpenID Connect Userinfo endpoint
* `id_token` - the JSON payload returned in the `id_token` when available. This parameter may not be provided and will be `undefined` in that case.

The two FusionAuth objects are well documented in the link:/docs/v1/tech/apis/users/[User API] and link:/docs/v1/tech/apis/registrations/[Registration API] documentation. 

The JWT object that contains the payload from the Userinfo endpoint. It may contain well known OpenID Connect registered claims as well as any custom claims defined by the Identity Provider. 

The `id_token` will be provided to the Lambda only:

* when it is returned by the Identity Provider and 
* it has been signed using the `client_secret` and an HMAC algorithm

In particular, if the `id_token` is signed using an asymmetric key-pair, it will not be available to the Lambda.

== Assigning the lambda

Once a lambda is created, you may assign it to one or more OpenID Connect IdPs in the IdP configuration.

Navigate to [breadcrumb]#Settings -> Identity Providers# and select your existing an OpenID Connect configuration or click [breadcrumb]#Add provider# and select OpenID Connect if it has not yet been configured.

== Example lambda

include::docs/v1/tech/lambdas/_openid-connect-example-lambda.adoc[]

=== Workarounds

If the JWT from the OIDC identity provider does not come back with an email claim you can add your own. This claim is `email` by default but may be changed with the `oauth2.emailClaim` as documented in the link:/docs/v1/tech/apis/identity-providers/openid-connect/[API docs].

[NOTE.note]
====
This capability is available beginning in version `1.31.0`. It was also available from `1.17.3` to `1.28.0`.
====

If the Userinfo or Id Token available to you in the lambda has unique user information, you can build a fake email address from it.

Here, the `sub` claim is the unique user id, and we're building an email address:

```javascript
function(user, registration, jwt) {
  // The user's unique Id is the 'sub' claim.
  user.email = jwt.sub + '@no-email-present.example.com';
}
```

Make sure you pick an email address for a domain you control to avoid malicious attacks. Modifying the username or email address will cause your lambda to be run two times.

