---
layout: doc
title: OpenID Connect Reconcile
description: An overview of the OpenID Connect Response Reconcile lambda
---

:sectnumlevels: 0

== OpenID Connect Reconcile lambda

When an OpenID Connect identity provider is used to complete a federated login request FusionAuth will use well known OpenID Connect claims to reconcile user.

It is common that the claims returned from the Userinfo endpoint during an OpenID Connect login request will contain custom claims defined by your identity provider. In order to utilize these custom claims you may wish to use a lambda assist FusionAuth during the login request to reconcile these claims to the FusionAuth user.

When you create a new lambda using the FusionAuth UI we will provide you an empty function for you to implement. If you are using the API to create the lambda you will need to ensure your function has the following signature:

[source,javascript]
----
function reconcile(user, registration, jwt, idToken) {
  // Lambda code goes here
}
----

This lambda must contain a function named `reconcile` that takes three parameters. The parameters that the lambda is passed are:

* `user` - the FusionAuth User object
* `registration` - the FusionAuth UserRegistration object
* `jwt` - the JSON payload returned from the OpenID Connect Userinfo endpoint
* `idToken (optional)` - the JSON id_token returned from the OpenID Connect Token endpoint. It will only be available if it can be validated using the client secret.

The two FusionAuth objects are well documented here in the link:/docs/v1/tech/apis/users/[User API] and link:/docs/v1/tech/apis/registrations/[Registration API] documentation. The JWT object that contains the payload from the Userinfo endpoint may contain well known OpenID Connect registered claims as well as any custom claims defined by the identity provider. The optional idToken object contains the id_token from the Token endpoint. It also contains well known OpenID Connect registered claims as well as any custom claims defined by the identity provider.

== Assigning the lambda

Once a lambda is created, you may assign it to one or more OpenID Connect IdPs in the IdP configuration.

Navigate to [breadcrumb]#Settings -> Identity Providers# and select your existing an OpenID Connect configuration or click [breadcrumb]#Add provider# and select OpenID Connect if it has not yet been configured.

== Example lambda

include::docs/v1/tech/lambdas/_openid-connect-example-lambda.adoc[]

=== Workarounds

If the JWT from the OIDC identity provider does not come back with an email claim you can add your own. This claim is `email` by default but may be changed with the `oauth2.emailClaim` as documented in the link:/docs/v1/tech/apis/identity-providers/openid-connect/[API docs].

If the Userinfo response available to you in the lambda has unique user information, you can build a fake email address from it.

Also, if the id_token from the token endpoint can be validated using the client secret then it will be available and may contain the email as well.

Here, we check for an email in the idToken first, then fallback on using the `sub` claim as the unique user id, and build an email address:

```javascript
function(user, registration, jwt, idToken) {
  // OR you can possibly get it from the idToken if available
  if (idToken && idToken.email) {
    console.info('email from id_token: ' + idToken.email);
    user.email = idToken.email;
  }
  else {
    // The user's unique Id is the 'sub' claim.
    user.email = jwt.sub + '@no-email-present.example.com';
  }

}
```

Make sure you pick an email address for a domain you control to avoid malicious attacks. This will run your lambda twice.

This workaround only is available if you are on version 1.18.7 or greater and if no claim is returned.

=== Limitations

include::docs/v1/tech/lambdas/_idp_limitations.adoc[]
