---
layout: doc
title: Twitch Reconcile
description: An overview of the Twitch Reconcile lambda
---

:sectnumlevels: 0

== Twitch Reconcile lambda

When an Twitch identity provider is used to complete a federated login request FusionAuth will use the email address to reconcile user. You may optionally utilize a lambda to customize the user and user registration during this authentication event.

When you create a new lambda using the FusionAuth UI we will provide you an empty function for you to implement.

If you are using the API to create the lambda you will need to ensure your function has the following signature:

[source,javascript]
----
function reconcile(user, registration, idToken) {
  // Lambda code goes here
}
----

This lambda must contain a function named `reconcile` that takes three parameters. The parameters that the lambda is passed are:

* `user` - the FusionAuth User object
* `registration` - the FusionAuth UserRegistration object
* `idToken` - the JSON payload returned by the Twitch Token Info API
// TODO 👆 check above for accuracy

The two FusionAuth objects are well documented here in the link:/docs/v1/tech/apis/users/[User API] and link:/docs/v1/tech/apis/registrations/[Registration API] documentation. The `idToken` may contain various user claims depending upon the user's Twitch configuration.

== Assigning the lambda

Once a lambda is created, you may assign it to the Twitch identity provider in the IdP configuration.

Navigate to [breadcrumb]#Settings -> Identity Providers# and select your existing Twitch configuration or click [breadcrumb]#Add provider# and select Twitch if it has not yet been configured.

== Default lambda

A default Twitch reconcile lambda is available in FusionAuth that may be used or modified. The default Twitch lambda function is documented below.

[source,javascript]
----
// Using the response from the Twitch API, reconcile the User and User Registration.
function reconcile(user, registration, idToken) {
  //  When writing a lambda we've added a few helpers to make life easier.
  //  console.info('Hello World');         # This will create an EventLog of type Information
  //  console.error('Not good.');          # This will create an EventLog of type Error
  //  console.debug('Step 42 completed.'); # This will create an EventLog of type Debug
  //
  //  To dump an entire object to the EventLog you can use JSON.stringify, for example:
  //  console.info(JSON.stringify(user));

  // Happy coding! Reconcile the User here.

  console.info('Hello World!');
}
----

=== Limitations

include::docs/v1/tech/lambdas/_idp_limitations.adoc[]
