---
layout: doc
title: Twitch Reconcile
description: An overview of the Twitch Reconcile lambda
---

:sectnumlevels: 0

== Twitch Reconcile lambda

This lambda reconciles a user in conjunction with a Twitch IdP.

When you create a new lambda using the FusionAuth UI we will provide you an empty function for you to implement.

If you are using the API to create the lambda you will need to ensure your function has the following signature:

[source,javascript]
----
function reconcile(user, registration, userInfo) {
  // Lambda code goes here
}
----

This lambda must contain a function named `reconcile` that takes three parameters. The parameters that the lambda is passed are:

* `user` - the FusionAuth User object
* `registration` - the FusionAuth UserRegistration object
* `userInfo` - the JSON payload returned by the Twitch Token Info API

The two FusionAuth objects are well documented here in the link:/docs/v1/tech/apis/users[User API] and link:/docs/v1/tech/apis/registrations[Registration API] documentation. The `userInfo` may contain various user claims depending upon the user's Twitch configuration.

== Assigning the lambda

Once a lambda is created, you may assign it to the Twitch identity provider in the IdP configuration.

Navigate to [breadcrumb]#Settings -> Identity Providers# and select your existing Twitch configuration or click [breadcrumb]#Add provider# and select Twitch if it has not yet been configured.

