---
layout: doc
title: Proxy Setup For FusionAuth 
description: You can add a proxy in front of FusionAuth. This documents why and how.
---

:sectnumlevels: 0

== What Is a Proxy

For the purposes of this document, a proxy is a piece of software which sits between your users and FusionAuth. Some or all requests to FusionAuth pass through the proxy.

TODO need diagram here

Proxies can be self-hosted or SaaS. Examples include:

* NGINX
* Apache
* Caddy
* Cloudflare
* CloudFront

FusionAuth should work with any proxy that supports HTTP. If you find a proxy that isn't supported, please https://github.com/fusionauth/fusionauth-issues/issues[open a GitHub issue with details].

== Why Use a Proxy

While you can run FusionAuth without a proxy, there a are a number of reasons why you might want to use one:

* Have different domain names which point to different FusionAuth tenants
* Throttle access
* Cache pages for performance
* Display custom error pages for 4xx or 5xx errors
* Handle TLS termination
* Add additional request processing logic
* Have FusionAuth requests served from a non-standard path such as `/fa/`

== How To Use a Proxy

This section won't cover setting up your proxy or proxy specific configuration. Instead, consult your proxy package's documentation.

What is important is that you are forwarding all requests to FusionAuth and that you are setting the correct headers. 

Here's a list of the headers you must set:

* `X-Forwarded-Proto`: typically this will be `https`. This ensures any redirects are sent with the appropriate scheme. This will be the scheme of the proxy.
* `X-Forwarded-Host`: The original host requested by the client in the `Host` HTTP request header. This will be the hostname of the proxy.
* `X-Forwarded-For`: The originating IP address of the client. This varies by client, but is used for logging IP addresses and link:/docs/v1/tech/apis/ip-acl[enforcing ACLs].
* `X-Forwarded-Server`: The hostname of the proxy server. 

Let's say FusionAuth lives at \https://example.fusionauth.io, and the proxy lives at \https:///auth.example.com. 

In this case, the headers would have the following values.
* `X-Forwarded-Proto`: `https`
* `X-Forwarded-Host`: `auth.example.com`
* `X-Forwarded-For`: The client IP address
* `X-Forwarded-Server`: `auth.example.com`

Proxies may use different formats to set these headers. For example, IIS requires you to use underscores and prepend the header with HTTP: `X-Forwarded-Proto` is converted to `HTTP_X_Forwarded_Proto`. Please consult your proxy's documentation for more details.

=== Common Proxy Configurations

The community has provided a number of example configurations for different proxies. You can https://github.com/FusionAuth/fusionauth-contrib/tree/master/Reverse%20Proxy%20Configurations[view them in the GitHub repo].

=== Chaining Proxies

If needed, you can have multiple proxies for each request. This may be useful if you have one proxy that handles domain name translation and one that handles error pages.

TODO need diagram here

If you do this, ensure that every proxy in the chain has the same value for `X-Forwarded-Host`, that of the original hostname. This allows FusionAuth to set cookies and create redirects correctly.

However, `X-Forwarded-Server` should change as requests pass through each proxy.

=== Locking FusionAuth Down

You may want to allow access to FusionAuth only through the proxy to enhance your defense in depth strategy. There are a few options to do so:

* At the network level, using firewalls.
* Using FusionAuth's IP ACL feature (only available in the Enterprise edition).

In either case, disallow all traffic to FusionAuth not originating from the proxy.

== Limits

There are no limits on using a proxy with FusionAuth.

You can use a proxy with self-hosted FusionAuth or with FusionAuth Cloud.

