---
layout: doc
title: FusionAuth and Proxies
description: You can add a proxy in front of FusionAuth. This page documents why and how.
---

:sectnumlevels: 0
:page-liquid:

== Overview

While FusionAuth doesn't require a proxy, using one offers additional flexibility.

* <<What Is a Proxy>>
* <<Why Use a Proxy>>
* <<How To Use a Proxy>>
** <<Caching>>
** <<Common Proxy Configurations>>
** <<Chaining Proxies>>
** <<Locking FusionAuth Down>>
* <<Troubleshooting>>
* <<Limits>>

== What Is a Proxy

While the term is overloaded, for the purposes of this document, a proxy is any software which sits between your users and FusionAuth. Some or all requests to FusionAuth then pass through the proxy.

++++
{% plantuml source: _diagrams/docs/admin-guide/one-proxy.plantuml, alt: "A typical proxy configuration." %}
++++

Proxies can be self-hosted or SaaS. Examples include:

* NGINX
* Apache
* Caddy
* Cloudflare
* CloudFront

FusionAuth should work with any proxy that supports HTTP. If you find a proxy that isn't supported, please https://github.com/fusionauth/fusionauth-issues/issues[open a GitHub issue with details].

== Why Use a Proxy

While you can run FusionAuth without a proxy, there are a number of reasons why you might want one:

* Have different domain names which point to different FusionAuth tenants; the proxy can map between domain names and tenant Ids
* Block or throttle access based on request characteristics such as user agent
* Cache CSS or other static assets for performance
* Display custom error pages for 4xx or 5xx errors (https://github.com/FusionAuth/fusionauth-issues/issues/404[see this issue for more])
* Terminate TLS before requests reach FusionAuth
* Add additional request processing logic
* Have FusionAuth requests served from a non-standard path such as `/fa/` (https://github.com/FusionAuth/fusionauth-issues/issues/88[see this issue for more])

== How To Use a Proxy

This section won't cover setting up your proxy or proxy specific configuration. Instead, consult your proxy package's documentation. However, you must forward all requests to FusionAuth, and you must also set the correct headers. 

Here's a list of the headers you must set:

* `X-Forwarded-Proto`: typically this will be `https`. This ensures any redirects and cookies are sent with the appropriate scheme. This will be the scheme of the proxy server.
* `X-Forwarded-Host`: The original host requested by the client in the `Host` HTTP request header. This will be the hostname of the proxy server.
* `X-Forwarded-For`: The originating IP address of the client. This varies and is used for logging IP addresses and link:/docs/v1/tech/apis/ip-acl[enforcing ACLs].
* `X-Forwarded-Server`: The hostname of the proxy server.

Let's say FusionAuth lives at \https://example.fusionauth.io, and the proxy lives at \https:///auth.example.com. 

In this case, the headers would have the following values:

* `X-Forwarded-Proto`: `https`
* `X-Forwarded-Host`: `auth.example.com`
* `X-Forwarded-For`: The client IP address
* `X-Forwarded-Server`: `auth.example.com`

Proxies may use different formats to set these headers. For example, IIS requires underscores and you must prepend the header with HTTP. `X-Forwarded-Proto` is `HTTP_X_Forwarded_Proto`. Please consult your proxy server's documentation for more details.

=== Caching

FusionAuth disallows caching of non-static assets such as HTML pages with the https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control[`Cache-control: no-store` header].

Never cache FusionAuth non-static asset responses.

=== Common Proxy Configurations

The community has provided a number of example configurations for different proxies. You can https://github.com/FusionAuth/fusionauth-contrib/tree/master/Reverse%20Proxy%20Configurations[view them in the GitHub repo].

=== Chaining Proxies

If needed, you can have multiple proxies for each request. This may be useful if one proxy handles custom domain names for tenants and another handles error pages.

++++
{% plantuml source: _diagrams/docs/admin-guide/two-proxies.plantuml, alt: "A proxy configuration with multiple proxies." %}
++++

With this pattern, every proxy in the chain must have the same value for `X-Forwarded-Host`, the hostname of the initial proxy. The initial proxy is `Proxy 1` in the diagram above.

Doing so allows FusionAuth to set cookies and create redirects correctly.

However, `X-Forwarded-Server` should change as requests pass through each proxy.

=== Locking FusionAuth Down

You may want to allow access to FusionAuth only through the proxy to enhance a defense in depth strategy. There are a few options to do so:

* At the network level, using firewalls.
* Using FusionAuth's IP ACL feature (only available in the Enterprise edition).

In either case, disallow traffic to FusionAuth not originating from the proxy.

== Troubleshooting

include::docs/v1/tech/admin-guide/_proxy-troubleshooting.adoc[]

== Limits

There are no limits on using a proxy with FusionAuth.

You can use a proxy with self-hosted FusionAuth or with FusionAuth Cloud.

