---
layout: doc
title: Releases
description: How can you see when a new version of FusionAuth is released?
navcategory: admin
---

== Overview

FusionAuth is a single tenant SaaS or downloadable solution. This fact means that you control when upgrades occur, rather than having an upgrade with new functionality and possibly breaking changes forced on you and your team.

[NOTE.note]
====
Authentication and authorization are core dependencies of your application, and we hate forced dependency upgrades.

You and you alone control when you upgrade.
====

* <<Release Notifications>>
* <<Early Access Program>>
** <<EAP Constraints>>
** <<EAP Usage Guidelines>>

== Release Notifications

include::docs/v1/tech/shared/_release-notification.adoc[]

== Early Access Program

[NOTE.since]
====
Available since 1.41.0
====

FusionAuth has an early access program (EAP). The EAP allows you, within certain constraints, to test drive the features and functionality of the next release of FusionAuth. EAP versions differ from typical FusionAuth releases, which are also called generally available (GA) releases or versions.

To allow the community to provide feedback more easily, new features which in a GA release require a license will not require such a license in the EAP version.

You should always run a GA release in production.

=== EAP Constraints

The EAP constraints include:

* You can install FusionAuth only using zip, deb or rpm files. These will be available in your FusionAuth account. If you don't have one, https://account.fusionauth.io/[sign up for free].
* There is no upgrade path from an EAP version to a released version.
* The performance and stability of a FusionAuth instance running an EAP version is not guaranteed.
* In an EAP, new features, functionality and APIs are under development and may change.
* Documentation for new features in an EAP may be lacking.

[WARNING.warning]
====
There is no upgrade path from an EAP version to a GA version.

EAP versions should be used only to test features and integrations in preparation for an upcoming GA release.
====

=== EAP Usage Guidelines

An instance running an EAP version is appropriate for the following purposes:

* testing out features
* verifying the new version won't break your existing integrations
* giving feedback to the FusionAuth team

You **should not use** an EAP to:

* authenticate production users
* load test or verify performance
* test the upgrade process duration

[WARNING.warning]
====
There is no upgrade path from an EAP version to a GA version.

EAP versions should be used only to test features and integrations in preparation for an upcoming GA release.

Seriously.
====

==== Example Use Cases

Testing a new install with existing configuration with the EAP version:

* stand up a new instance with the EAP version
* configure the new instance with your configuration management solution (Terraform, scripts, Kickstart)

Testing a migration from a released version to the EAP version:

* make a copy of the database of your FusionAuth instance running a GA version
* create a new FusionAuth instance running the same version
* upgrade the instance to the EAP version

Multiple EAP releases may be available. To migrate from one EAP release to another:

* make a copy of the database of your FusionAuth instance running a GA version, **not the instance running a previous EAP release**
* create a new FusionAuth instance running the same version
* upgrade the instance to the new EAP version
