---
layout: doc
title: Release Notifications
description: How can you see when a new version of FusionAuth is released?
navcategory: admin
---

== Overview

FusionAuth is a single tenant SaaS or downloadable solution. This fact means that you control when upgrades occur, rather than having an upgrade with new functionality and possibly breaking changes forced on you and your team.

[NOTE.note]
====
Authentication and authorization are core dependencies of your application, and we hate forced dependency upgrades.

You and you alone control when you upgrade.
====

include::docs/v1/tech/shared/_release-notification.adoc[]

== Early Access Program

As of version 1.41, FusionAuth has an early access program (EAP). This allows you, within some constraints, to test drive the features in the next release of FusionAuth. 

[WARNING.warning]
====
There is no guaranteed upgrade path from the early access program installation.

It should be used only to test features and integrations in order to be prepared for an upcoming release.
====

Here are the current constraints of the early access program:

* You can only install via zip, deb or rpm files. These will be available on link:/direct-download[the direct download page].
* There is no supported upgrade path from an EAP versino to a released version.
* The stability of an EAP FusionAuth system is not guaranteed.
* Documentation for EAP feature may be lacking.

While the FusionAuth team will make every effort to not release an EAP until the APIs are stable, they may change. In addition, there is no supported upgrade path from an EAP instance to a released version.

=== EAP Usage

Two typical expected use cases:

Testing a new install with existing configuratoin with the EAP version:

* stand up a new instance
* configure the new instance with your configuration management solution (Terraform, scripts, Kickstart)
* run tests against the new instance

Testing a migration from a released version to the EAP version:

* make a copy of your database
* install a FusionAuth instance at the same released version.
* upgrade to the EAP version
* run tests against the new instance

=== Appropriate Usage

An EAP is appropriate for the following purposes:

* testing out a new feature
* verifying a new FusionAuth version won't break your existing integrations
* load testing to gain performance insights
* running end to end tests against to ensure your applications can be safely upgraded
* migrating a production dataset in a test environment to quantify upgrade durations

You should not use an EAP to:

* authenticate production users

[WARNING.warning]
====
There is no guaranteed upgrade path from the early access program installation.

It should be used only to test features and integrations in order to be prepared for an upcoming release.

Seriously.
====

