---
layout: doc
title: Upgrade FusionAuth
description: Learn how to upgrade FusionAuth using our bundles and migration scripts
navcategory: admin
---

== Upgrading

In order to upgrade FusionAuth to a later version use the following guides. Below you will find steps to follow if you are using `.deb` or `.rpm` package on Linux, or a `.zip` package on macOS, Linux or Windows.

Topics covered in this document:

* <<When to Upgrade>>
* <<Thinking About Upgrades>>
* <<ZIP Packages>>
* <<Linux Packages>>
** <<Troubleshooting Upgrade with RPMs>>
* <<FastPath>>
* <<Database>>
* <<Themes>>
* <<Downtime>>

If you used the FastPath or other installation methods initially, you may prefer to use that same mode to download the latest version of FusionAuth. If you would like to continue by manually downloading the necessary packages, read on.

== When to Upgrade

=== Reasons to Upgrade

Upgrading to a newer version of FusionAuth can provide the following benefits:

. Access to new features and improvements
. Improved performance and stability
. Critical Security updates and patches

=== Reasons Not to Upgrade

You might want to delay upgrading in the following situations:

. Your current version is meeting all your requirements
. You are in the middle of a project or have tight deadlines
. You have concerns about compatibility with customizations or third-party integrations

=== Being Aware of Upgrade Options

You can stay informed about new FusionAuth releases and updates by:

. Monitoring the link:/docs/v1/tech/release-notes[release notes]
. Join the https://fusionauth.io/community[FusionAuth Community site] and https://fusionauth.slack.com/join/shared_invite/zt-6ykfov9u-MTwA1A6ptv0Gr6KcFBVG4w#/shared-invite/email[Slack channel]
. Following FusionAuth on social media platforms, including https://twitter.com/FusionAuth[Twitter] and https://www.linkedin.com/company/fusionauth[LinkedIn].
. Monitoring the https://github.com/FusionAuth/[FusionAuth GitHub repository]

== How to Think About Upgrades

Before upgrading FusionAuth, there are a number of things to consider. Go through each of the points below to see if any of them apply to your situation.

=== Update Contents and Notes

Read the link:/docs/v1/tech/release-notes[release notes].  Release notes help you understand if an update affects you. They include details on new features, improvements, bug fixes, and potential breaking changes.

=== Testing

Before starting the upgrade process on production, test the upgrade in a staging or development environment to identify potential issues. This is particularly important on more complex upgrades involving multiple version jumps, or if you have made customizations to FusionAuth.

=== Downtime and Database Migrations

Plan for any downtime or maintenance windows required for the upgrade. If changes to the database schema are required, this could require more steps and downtime that affects end users. A pure application upgrade on the other hand may only affect admin functionality, and not require any downtime from an end user perspective.

FusionAuth can perform database migrations automatically and silently using called link:/docs/v1/tech/guides/silent-mode[Silent Mode]. 

If you want to interactively (called link:/docs/v1/tech/installation-guide/fusionauth-app#maintenance-mode[Maintenance Mode]), or you can run any needed scripts out of band (meaning directly on the database yourself). With any method, you should perform a backup of your database before upgrading.

The timing of the database upgrade is also important to note. When an upgraded node is added to a FusionAuth cluster, it will lock the database and perform the database upgrade if configured for Silent Mode. This means that the database will be unavailable to other nodes in the cluster until the upgrade is complete. 

=== Connected Applications and Client Libraries

Consider that a FusionAuth server upgrade might mean that you need to upgrade your client libraries as well. Check before upgrading if this is needed, as it will entail a more complex upgrade process, and may require more downtime.

=== Skipping Versions 

Sometimes, you will want to upgrade to a FusionAuth version that is a few versions newer than your current version. This is called a "version jump". FusionAuth migration can run all the necessary database migrations to get you to the latest version. However, we recommend that you don't skip minor versions, and rather migrate from one minor version to the next, step by step. For example, if you want to get to version 1.43, and you are on version 1.37, we recommend that you upgrade to each minor step to 1.43.

=== Migrating Configuration between Environments

There are a number of options you can use to manage the configuration of your FusionAuth instance over time, as well as to promote changes from one environment. These include:

- Script The Changes
- Terraform
- Pulumi
- Manual Configuration via the UI

You can read more at link:/docs/v1/tech/admin-guide/configuration-management[the Configuration Management guide].

=== Themes and Customizations

Review custom themes. If you have made any customizations, you may need to update them to work with the new version of FusionAuth. You can use the https://github.com/FusionAuth/fusionauth-theme-helper[Theme Helper] project to perform diffs on the themes to identify any changes that need to be made.

== Upgrade Options

=== Easiest Route

The easiest upgrade route is to simply stop all your services, upgrade everything, and then bring it all back online. 

This is a good option for single instance development or QA systems, or for systems that can tolerate longer amounts of downtime.

If minimizing downtime is a goal, then rolling upgrades, or a blue/green deployment might be more suitable. 

=== Rolling Upgrade

You can perform a rolling upgrade if you have 3 FusionAuth nodes running behind a load balancer. Each node is upgraded one at a time, and the load balancer is configured to direct traffic to the upgraded nodes as they become available for use. This allows you to upgrade FusionAuth with minimal downtime. 

Because individual nodes are taken offline during the rolling update, the capacity of your installation is reduced during the upgrade.

You can choose to run in-place upgrades on each node, or to replace each node with a new node running the latest version of FusionAuth. In place upgrades are potentially faster, but if something goes wrong, you may need to roll back the upgrade. Replacing nodes may be slower, but if something goes wrong, you can simply revert to the previous version of FusionAuth by pointing the load balancer to the old nodes.

A procedure might look like this:
- Stop the first node, and remove it from the load balancer
- Upgrade FusionAuth on first node. After FusionAuth is update, you can start it up, so that it can perform the database migrations. This will lock the database, and own it while it completes the database upgrade. Note that there will be a schema mismatch between the first node and the other nodes, so the other nodes may error while the first node is being upgraded.
- Start the first node, and add it back to the load balancer
- Stop the second and third nodes, and remove them from the load balancer, and upgrade them. 
- Start the second and third nodes, and add them back to the load balancer

This way there is still some downtime, but it is limited to the time it takes to run the database migration on the upgraded first node. There will be limited capacity during the upgrade, especially while the second and third nodes are upgrading, but the system will be available for use for the majority of the upgrade process.

To maximize available capacity during the upgrade, 

=== Blue / Green Deployment

A blue / green deployment is a technique that reduces downtime and risk by running two identical environments in parallel. A load balancer is used to direct traffic to one of the environments. Using a blue / green deployment instead of performing a rolling upgrade completely isolates the upgrade process from the production environment, reducing impact and risk to the current production environment.

To perform a blue/green deployment with a 3 node cluster, first create 3 entirely new nodes. Add one of these nodes to the existing cluster. At this point, the new node will lock the database, and own it while it completes the database upgrade. The original nodes might start to error - they can be removed. The remaining new nodes can then be added to the cluster. The system will be down for the duration of the database upgrade, but once the database upgrade is complete, the system will be back online with the upgraded version of FusionAuth on the new nodes. 
 
=== Out of Band Database Upgrades



== FAQs

Q: What is runtime mode and how does that affect upgrades?
A: FusionAuth's Runtime mode can either be 'production' or "development". When in the `development`` runtime mode, maintenance mode will interactively assist you configuring the database and connecting to Elasticsearch if configured. Once you move FusionAuth into production, it is recommended that you modify the runtime mode to `production`. When in production runtime mode maintenance mode will no longer be available to you which means you can be certain that your end users will not find themselves on the database upgrade panel during an Upgrade. When in production mode you will either need to leverage Silent Mode to automatically apply database migrations or you will need to apply the database migrations yourself (either by hand or via a script of some sort).For more on runtime modes, see the link:/docs/v1/tech/installation-guide/fusionauth-app#runtime-modes[FusionAuth Installation Guide] for reference.

Q: What is Maintenance Mode?
A: Maintenance Mode is a special admin interface for FusionAuth, which is helpful to interactively upgrade FusionAuth or setup database connections. You can switch to Maintenance mode by switching to the `development` runtime mode, and setting Silent Mode to false. 

Q: What is Silent Mode?
A: link:/docs/v1/tech/guides/silent-mode[Silent Mode] is a feature of FusionAuth that automatically applies database migrations. This is useful for automated deployments, or for when you want to upgrade FusionAuth without using the Maintenance Mode interface. Silent Mode can be enabled in the `development` runtime mode and as of version `1.19.0`, in `production` runtime mode as well. Silent Mode will attempt to perform database migrations on startup. If the database migrations fail, FusionAuth will switch to the manual Maintenance Mode interface.

Q: How many versions can I skip?
A: We recommended migrating from one minor version to the next over. 

Q: How often should I upgrade?
A: You can upgrade whenever you want. It is your dependency and we won't force you. We do recommend staying relatively close to the latest release. In addition, we don't typically backport bug fixes. If you run into an issue with a bug, you'll need to upgrade to get the fix.

Q: How can I find out about new releases?
A: We publish release notes for every release. You can find them here: link:/docs/v1/tech/release-notes[Release Notes]. 


[NOTE]
====
*Readme*

To upgrade to the latest version of FusionAuth using the FastPath installation go link:/docs/v1/tech/installation-guide/fast-path[here].

To upgrade to the latest version of FusionAuth using Homebrew go link:/docs/v1/tech/installation-guide/homebrew[here].

To upgrade to the latest version of FusionAuth using Docker go link:/docs/v1/tech/installation-guide/docker[here].

If you want to use manual mode, download the latest version of FusionAuth and follow the instructions below. See https://fusionauth.io/download[Downloads].
====


== ZIP Packages

FusionAuth is available in a zip package for macOS, Linux and Windows. If you are using the ZIP package, please use this guide to update an existing instance of FusionAuth.

=== macOS and Linux

In this example, we'll assume you have previously installed FusionAuth in `/usr/local/fusionauth` and this directory will be referred to `FUSIONAUTH_HOME`. If you have used a different directory you can adjust the following example accordingly.

[source,title=Example filesystem layout]
----
/usr/local/fusionauth/bin
/usr/local/fusionauth/config
/usr/local/fusionauth/config/keystore
/usr/local/fusionauth/config/fusionauth.properties
/usr/local/fusionauth/data
/usr/local/fusionauth/fusionauth-app
/usr/local/fusionauth/fusionauth-search
/usr/local/fusionauth/java
----

The first step will be to shutdown the FusionAuth services.

[source,title=Shutdown and Uninstall FusionAuth]
----
# Stop Services
/usr/local/fusionauth/bin/shutdown.sh

# Delete or move existing installation
cd /usr/local/fusionauth
rm -rf ./fusionauth-app
rm -rf ./fusionauth-search
rm -rf ./bin
----

During an upgrade, most everything is saved in the database, so it is safe to delete these directories. To preserve your configuration and Elasticsearch index you want to be sure to preserve the following directories:

[source,title=Preserve these directories]
----
/usr/local/fusionauth/config
/usr/local/fusionauth/data
/usr/local/fusionauth/java
/usr/local/fusionauth/logs
----

Extract the new zips and place in `FUSIONAUTH_HOME`. In the following example, we are using the `unzip` command with the `-n` and the `-q` flags. The `-q` flag is optional, it causes the command to be run in quiet mode to reduce the amount of output to the console. The other flag `-n` is a no overwrite flag so that any configuration files are not overwritten.

[source,title=Unzip the new packages with a no overwrite flag]
----
unzip -nq new-fusionauth-app.zip
unzip -nq new-fusionauth-search.zip
----

Finally restart the FusionAuth services.

[source,title=Startup FusionAuth]
----
# Start Services
/usr/local/fusionauth/bin/startup.sh
----

=== Windows

In this example, we'll assume you have previously installed FusionAuth in `\fusionauth` and this directory will be referred to `FUSIONAUTH_HOME`. If you have used a different directory you can adjust the following example accordingly.

[source,title=Example filesystem layout]
----
\fusionauth\bin
\fusionauth\config
\fusionauth\config\keystore
\fusionauth\config\fusionauth.properties
\fusionauth\data
\fusionauth\fusionauth-app
\fusionauth\fusionauth-search
\fusionauth\java
----

The first step will be to shutdown the FusionAuth services and delete the old installation.

[source,title=Shutdown and Uninstall FusionAuth]
----
# Stop Services
net stop FusionAuthApp
net stop FusionAuthSearch

# Uninstall Services
cd \fusionauth\fusionauth-app\bin
FusionAuthApp.exe /uninstall
cd \fusionauth\fusionauth-search\elasticsearch\bin
FusionAuthSearch.exe /uninstall

# Delete or move existing installation
cd \fusionauth
move fusionauth-app fusionauth-app-old
move fusionauth-search fusionauth-search-old
----

[NOTE]
====
Prior to version `1.37.0` the executable will be found in the `apache-tomcat` directory. For example,

`\fusionauth\fusionauth-app\apache-tomcat\bin\FusionAuthApp.exe`

Versions 1.37.0 through 1.39.0 do not support native Windows installation.
====

During an upgrade, most everything is saved in the database, so it is safe to delete these directories. To preserve your configuration and Elasticsearch index you want to be sure to preserve the following directories:

[source,title=Preserve these directories]
----
\fusionauth\config
\fusionauth\data
\fusionauth\java
\fusionauth\logs
----

Extract the new zips and place in `FUSIONAUTH_HOME`. You may do this using Windows File Explorer or other command line tools to unpack the zip archive. In this next step, ensure you delete or move the existing directories to ensure you do not unzip the new version on top of the existing version. If you do this, you will end up with duplicate libraries in the classpath that will lead to runtime errors.

After you have extracted the new packages, re-install the Windows services and start them.

[source,title=Install and Start FusionAuth]
----
# Install Windows Services
cd \fusionauth\fusionauth-app\bin
FusionAuthApp.exe /install
cd \fusionauth\fusionauth-search\elasticsearch\bin
FusionAuthSearch.exe /install

# Startup Services
net start FusionAuthSearch
net start FusionAuthApp
----

[NOTE]
====
Prior to version 1.37.0 you can find `FusionAuthApp.exe` at

`\fusionauth\fusionauth-app\apache-tomcat\bin\FusionAuthApp.exe`

Versions 1.37.0 through 1.39.0 do not support native Windows installation.
====

That is it, you're done!

== Linux Packages

Updating your application is easy if you installed using the RPM or Debian packages. All you need to do is to issue an update command to the dpkg or rpm program and specify the new package file. Here is an example:

[NOTE]
====
Running the update script will shut down the FusionAuth service if they have not yet been stopped The service will need to be restarted after the update is finished.
====

[source,title=Shutdown FusionAuth]
----
sudo service fusionauth-app stop
sudo service fusionauth-search stop
----

[source,shell,title=Upgrade FusionAuth using Debian bundles]
----
sudo dpkg -i fusionauth-search-<version>.deb
sudo dpkg -i fusionauth-app-<version>.deb
----

[source,shell,title=Upgrade FusionAuth using RPM bundles]
----
sudo rpm -U fusionauth-search-<version>.rpm
sudo rpm -U fusionauth-app-<version>.rpm
----

[source,title=Start FusionAuth]
----
sudo systemctl start fusionauth-search
sudo systemctl start fusionauth-app
----

=== Troubleshooting Upgrade with RPMs

include::docs/v1/tech/shared/_troubleshooting-uninstall-upgrade-reinstall-rpm.adoc[]

=== FastPath

While FastPath is an option to perform an upgrade, the FastPath process limits the flexibility of installation in order to get up and running quickly. Therefore it is not recommended to use FastPath install scripts in a Production Environment.

When in a production environment please utilize `.deb` or `.rpm` packages when on Linux. If you your production platform is macOS or Windows, please manually manage the upgrade using the `.zip` bundles.

== Database

[NOTE]
====
If you want FusionAuth to upgrade the database automatically, use the link:/docs/v1/tech/guides/silent-mode[Silent Mode] process, which will perform an automated upgrade.

If you want to use Maintenance Mode, ensure your runtime mode is set to `development` and silent mode is set to `false`.

If you want to upgrade the database manually, follow the instructions below.

For more on runtime modes, see the link:/docs/v1/tech/installation-guide/fusionauth-app#runtime-modes[FusionAuth Installation Guide] for reference.

For more information on the various configuration options, see the link:/docs/v1/tech/reference/configuration[Configuration Reference].
====

[NOTE]
====
You should always backup your database prior to upgrading using Maintenance Mode.
====

Depending on your current version and the new version you will be updating to you might need to execute one or more SQL scripts to update your database. These scripts are located in the migrations folder inside the Database Schema ZIP file. This file can be downloaded by finding the database zip on the https://fusionauth.io/direct-download[Direct Downloads] page.

[WARNING]
====
When upgrading your database from a previous version, be sure to only run the scripts located in the `migrations` folder, the base files
 `mysql.sql` and `postgresql.sql` should only be used during a clean installation when no database schema is present.
====

Inside of the database schema zip file, you will find the FusionAuth migrations. Run them in order, starting with the first migration greater than the version you are coming from, and ending with the version that is less than or equal to the target upgrade version.

For example, if upgrading from version `1.19.1` to `1.22.0`, run the following SQL migrations in this order:

* `1.20.0.sql`
* `1.21.0.sql`
* `1.22.0.sql`

[source]
----
fusionauth-database-schema/
|-- migrations/
    |--  [mysql | postgresql]/
      |-- 1.1.0.sql
      |-- 1.2.0.sql
      |-- 1.3.0.sql
      |-- 1.3.1.sql
      |-- 1.5.0.sql
      |-- 1.6.0.sql
      |-- 1.7.0.sql
      |-- 1.7.1.sql
      |-- 1.8.0-RC.1.sql
      |-- 1.8.1-RC.1.sql
      |-- 1.11.0.sql
      |-- 1.12.0.sql
      |-- 1.13.0.sql
      |-- 1.14.0.sql
      |-- 1.15.0.sql
      |-- 1.15.3.sql
      |-- 1.16.0-RC.1.sql
      |-- 1.16.0.sql
      |-- 1.17.0.sql
      |-- 1.17.3.sql
      |-- 1.18.0.sql
      |-- 1.18.2.sql
      |-- 1.19.0.sql
      |-- 1.20.0.sql
      |-- 1.21.0.sql
      |-- 1.22.0.sql
      |-- 1.23.0.sql
      |-- 1.25.0.sql
      |-- 1.26.0.sql
      |-- 1.27.0.sql
      |-- 1.28.0.sql
      |-- 1.28.1.sql
      |-- 1.29.1.sql
      |-- 1.30.0.sql
      |-- 1.30.1.sql
      |-- 1.30.2.sql
      |-- 1.32.0.sql
      |-- 1.33.0.sql
      |-- 1.35.0.sql
      |-- 1.36.0.sql
      |-- 1.37.0.sql
      |-- 1.40.1.sql
      |-- 1.41.0.sql
      |-- 1.43.0.sql
      |-- 1.44.0.sql
----

== Themes

include::docs/v1/tech/installation-guide/_theme-upgrade.adoc[]

== Downtime

include::docs/v1/tech/installation-guide/_downtime-upgrade-limitation.adoc[]
