---
layout: doc
title: Upgrade FusionAuth
description: Learn how to upgrade FusionAuth using our bundles and migration scripts
navcategory: admin
---

== Upgrading FusionAuth

This guide will help you upgrade FusionAuth, focusing on self-hosted, RPM/DEB/ZIP-based installations. It covers the reasons to upgrade or not, being aware of upgrade options, and various aspects of the upgrade process.

* <<Reasons to Upgrade>>
* <<Access to new features and functionality>>
* <<Receive bug fixes and security patches>>
* <<Improve performance and efficiency>>
* <<Maintain compatibility with client libraries>>
* <<Reasons to Not Upgrade>>
* <<Stability concerns>>
* <<Time and resource constraints>>
* <<Customizations that may break in newer versions>>
* <<Being Aware of Upgrade Options and Notifications>>
* <<Subscribe to release notifications>>
* <<Monitor FusionAuth's official blog or social media channels>>
* <<Stay informed about the latest releases through FusionAuth's documentation and resources>>
* <<Thinking About Upgrades>>
* <<Read the Release Notes>>


== Reasons to Upgrade

Upgrading to a newer version of FusionAuth can provide the following benefits:

. Access to new features and improvements
. Improved performance and stability
. Critical Security updates and patches

== Reasons Not to Upgrade

You might want to delay upgrading in the following situations:

. Your current version is meeting all your requirements
. You are in the middle of a project or have tight deadlines
. You have concerns about compatibility with customizations or third-party integrations

== Being Aware of Upgrade Options

Stay informed about new FusionAuth releases and updates by:

. Monitoring the link:/docs/v1/tech/release-notes[release notes]
. Subscribing to the FusionAuth newsletter
. Following FusionAuth on social media platforms
. Monitoring the FusionAuth GitHub repository
. Participating in the FusionAuth community forum

== How to Think About Upgrades

Before upgrading FusionAuth, consider the following:

. Read the link:/docs/v1/tech/release-notes[release notes].  Release notes help you understand if an update affects you. They include details on new features, improvements, bug fixes, and potential breaking changes.
. Test the upgrade in a staging or development environment to identify potential issues
. Plan for any downtime or maintenance windows required for the upgrade
. Review custom themes, client libraries, and configuration settings for compatibility with the new version
. Consider using blue/green deployments or rolling upgrades to minimize downtime

== Upgrading Custom Themes

To upgrade your custom theme, you need to do a diff of theme changes across versions. Consider starting a project that pulls down the default theme from each released version of FusionAuth and commits it to a GitHub repository. You can use the FusionAuth Theme Helper as a starting point.

== Migrating FusionAuth Configuration Changes Between Environments

Refer to the Configuration Management guide for information on migrating configuration changes between environments.

== Upgrading Your Database with Minimal Downtime

Upgrade your database with minimal downtime by following the instructions in the Database section below.

== Switching Out Nodes in a Cluster

If you're running FusionAuth in a cluster, you'll need to switch out nodes one by one during the upgrade. The first node switched out checks for the correct schema and upgrades if needed.

== Handling Main Use Cases

The upgrade process may vary depending on whether you're in a development environment, using Docker or Kubernetes, or running in a cluster.

== Upgrading Versions

If you're upgrading from version 1.37 to 1.43, consider upgrading step-by-step through each minor version to ensure compatibility and reduce potential issues.

== Downtime

Determine if an upgrade will cause downtime by using a staging environment or checking if a database migration is necessary. If a database migration is required, there will likely be downtime. The duration of the downtime depends on your specific architecture.

Differentiate between upgrades affecting admin functionality and those impacting end-user login functionality.

== Upgrading Cloud Instances

For upgrading cloud instances, refer to the relevant section in the cloud installation guide.

== Node Readiness

Determine if a node is ready to serve traffic by checking /api/status. Additional guidance may be needed for Helm charts.

== Silent Mode

Silent mode is used for maintenance mode and provides no prompts. In contrast, non-silent mode displays a GUI asking for database connection information.

Upgrade Options
Easiest Path

Take everything down.
Upgrade everything.
Start everything back up.
FusionAuth owns the schema, resulting in a full outage.
Rolling Upgrade

For a three-node cluster:

Upgrade one node at a time behind a load balancer.
Before adding an upgraded node to the load balancer, ensure node 1 is upgraded.
Alternatively, upgrade nodes 2 and 3 simultaneously, losing capacity but avoiding schema mismatches.
You can perform in-place upgrades using dpkg -i or stand up entirely new infrastructure.
Blue/Green Deployment

For a three-node cluster:

Stand up three new nodes with the new version.
Add node 4 to the cluster. It will lock the database and own it.
Nodes 1, 2, and 3 may encounter errors