---
layout: doc
title: FusionAuth Vulnerabilities
description: Learn more about known CVEs and how they affect FusionAuth
navcategory: admin
---

:sectnumlevels: 0

== Vulnerabilities

This page is provided to help a FusionAuth administrator understand what CVEs or other documented vulnerabilities affect FusionAuth.

The FusionAuth development team continually monitors for known vulnerabilities in

== CVEs

The Common Vulnerabilities and Exposures or CVE as it is referred to is a public database that allows software vendors and software consumers find and report on software vulnerabilities.

https://www.cve.org/

The purpose of this listing is to provide you a reference of CVEs that are known to exist in one or more versions of FusionAuth with information regarding to the affected versions, migration steps, or an explanation of why a CVE may show up in a scan, but does not affect FusionAuth.


==== CVE-2022-34169

* https://www.cve.org/CVERecord?id=CVE-2022-34169[CVE-2022-34169]

*Why am I seeing this CVE show up in a security scan?*

The version Java that is packaged with FusionAuth contains the Apache Xalan XSLT library.

*Is FusionAuth affected?*

No. FusionAuth is not using the XSLT compiler to compile the style sheets. This CVE does not affect FusionAuth.

*Fixed in version:*

N/A


