---
layout: passport-doc
title: Register a User & Login
description: Learn how to register a User and log them in via the Passport API
---

== Overview

This tutorial guides you through the basics of registering users and logging them into Applications using the Passport APIs.


== Register a User

In order to register a User, you must have first created an Application by following the link:create-an-application[Create an Application] tutorial. Once the Application has been created, you are ready to call the API to register a User.

There are two APIs that can be used to create the User and then create a Registration for that User in the Application you create. In most cases you will want to create the User and register them in a single step. This can be accomplished by calling the link:../apis/registrations#create-a-user-and-registration-combined[/api/user/register (combined) API].

However, you can also create the User and then register them for the Application in separate API calls. This method would make use of the link:../apis/users#create-a-user[/api/user API] followed by a call to the link:../apis/registrations#create-a-user-registration-for-an-existing-user[/api/user/register (for an existing user) API]. We recommend using the single API call, but in some cases, calling the APIs separately is preferred.


== Login a User

Once you have create a User and registered them for an Application, you can authenticate them by calling the link:../apis/login[Login API].

