---
layout: passport-doc
title: Start and Stop Passport
description: Learn how to start and stop the Passport services
---

== Start and Stop Passport

If you are using the Passport server version, may need to manually start or stop Passport periodically. If you find yourself in this situation you'll be glad you know how.

[NOTE]
====
Unless you are hosting and managing Passport these instructions do not apply to you. Inversoft manages and monitors instances hosted in our private cloud and will restart Passport if necessary.
====


[NOTE]
====
*Note* that you *MUST* start the Passport Search Engine before starting the Passport Backend service. You should also shutdown the Search Engine last. Passport utilizes the Search Engine and database for persisting and retrieving users.
====

The following examples will make the assumption that all of the services are running on the same server. Based upon how you have installed Passport you may or may not have all of the services running on the same server.

The Mac OS X and Windows instructions assume an installation directory of `/usr/local/inversoft` and `\inversoft` respectively. Please adjust to your specific installation directory. We'll refer to this directory as `PASSPORT_HOME`.

=== Linux
When you install Passport using our Debian or RPM packages a service is registered. It is recommended you utilize these services to start and stop Passport. If the version of Linux your using supports `systemd` you may use the `systemctl` command as well to manage services.

The service names are as follows:

* `passport-search-engine`
* `passport-backend`

[source,shell]
.Start Passport
----
$ sudo service passport-search-engine start
$ sudo service passport-backend start
----

[source,shell]
.Stop Passport
----
$ sudo service passport-backend stop
$ sudo service passport-search-engine stop
----

If you'd like to use the `systemctl` command instead, the syntax is similar to the `service` command. For example, to check the status, stop and then start the Passport Backend service using the `systemctl` command

[source,shell]
.Check Status, then Stop and Start Passport Backend
----
$ systemctl status passport-backend.service
$ systemctl stop passport-backend.service
$ systemctl start passport-backend.service
----

If you'd prefer to use the native Elastic and Tomcat scripts you may follow the Mac OS X instructions, the same scripts may be executed on Linux.

=== Mac OS X

*Start and Stop services using the native Elastic and Tomcat scripts*

Prior to version 1.8.1 the Apache Tomcat directory will be named `apache-tomcat-8.0.12` instead of `apache-tomcat` and the ElasticSearch Engine directory will be named `elasticsearch-1.3.4` instead of `elasticsearch`.

[source,shell]
.Start Passport
----
$ /usr/local/inversoft/passport-search-engine/elasticsearch/bin/elasticsearch
$ /usr/local/inversoft/passport-backend/apache-tomcat/bin/catalina.bat start
----

[source,shell]
.Stop Passport
----
$ /usr/local/inversoft/passport-backend/apache-tomcat/bin/catalina.bat stop
----

Elastic Search should be stopped last. If you started Elastic Search using the `elasticsearch` script then you may simply kill the terminal where the service is running to initiate shutdown.

=== Windows

*Start and Stop services using the native Elastic and Tomcat scripts*

Prior to version 1.8.1 the Apache Tomcat directory will be named `apache-tomcat-8.0.12` instead of `apache-tomcat` and the ElasticSearch Engine directory will be named `elasticsearch-1.3.4` instead of `elasticsearch`.

[source,shell]
.Start CleanSpeak
----
> \inversoft\passport-search-engine\elasticsearch\bin\elasticsearch.bat
> \inversoft\passport-backend\apache-tomcat\bin\catalina.bat start
----

[source,shell]
.Stop Passport
----
> \inversoft\psasport-backend\apache-tomcat\bin\catalina.bat stop
----

Elastic Search should be stopped last. If you started Elastic Search using the `elasticsearch.bat` script then you may simply close the command window where the service is running to initiate shutdown.

*Start and Stop services using Windows Services*

We also provide support for running Passport as a Windows service.

[source,shell]
.Register Windows Services
----
> \inversoft\passport-search-engine\elasticsearch\bin\PassportSearchEngine.exe /install
> \inversoft\passport-backend\apache-tomcat\bin\PassportBackend.exe /install
----

[source,shell]
.Unregister Windows Services
----
> \inversoft\passport-backend\apache-tomcat\bin\PassportBackend.exe /uninstall
> \inversoft\passport-search-engine\elasticsearch\bin\PassportSearchEngine.exe /uninstall
----

[source,shell]
.Start Services
----
> net start PassportSearchEngine
> net start PassportBackend
----

[source,shell]
.Stop Services
----
> net stop PassportBackend
> net stop PassportSearchEngine
----