files:
  - AuditLog
  - Lambda
  - Webhook
  - APIKey
  - Application
  - domain.Consent # pick up other consent objects w/o prefix
  - Form
  - FormField
  - Group
  - domain.Key # without the prefix, matches other objects containing Key
  - EventLog
  - domain.Tenant
  - GenericConnectorConfiguration
  - LDAPConnectorConfiguration
  - domain.email.EmailTemplate
  - domain.User
  - UserComment
  - Family
  - Theme
  - EntityType
  - Entity
  - EntityGrant
  - SAMLv2IdentityProvider
  - SAMLv2IdPInitiatedIdentityProvider

# events
  - AuditLogCreateEvent
  - EventLogCreateEvent
  - JWTPublicKeyUpdateEvent
  - JWTRefreshEvent
  - JWTRefreshTokenRevokeEvent
  #- KickstartSuccessEvent
  - GroupCreateEvent
  - GroupUpdateEvent
  - GroupDeleteEvent
  - GroupCreateEventComplete
  - GroupDeleteEventComplete
  - GroupMemberAddEvent
  - GroupMemberRemoveEvent
  - GroupMemberUpdateEvent
  - GroupMemberAddEventComplete
  - GroupMemberRemoveEventComplete
  - GroupMemberUpdateEventComplete
  - UserActionEvent
  - UserBulkCreateEvent
  - UserCreateEvent
  - UserCreateCompleteEvent
  - UserDeactivateEvent
  - UserDeleteEvent
  - UserDeleteCompleteEvent
  - UserEmailUpdateEvent
  - UserEmailVerifiedEvent
  - UserIdentityProviderLinkEvent
  - UserIdentityProviderUnlinkEvent
  - UserLoginFailedEvent
  - UserLoginIdDuplicateOnCreateEvent
  - UserLoginIdDuplicateOnUpdateEvent
  - UserLoginNewDeviceEvent
  - UserLoginSuccessEvent
  - UserLoginSuspiciousEvent
  - UserPasswordBreachEvent
  - UserPasswordResetSendEvent
  - UserPasswordResetStartEvent
  - UserPasswordResetSuccessEvent
  - UserPasswordUpdateEvent
  - UserReactivateEvent
  - UserRegistrationCreateCompleteEvent
  - UserRegistrationCreateEvent
  - UserRegistrationDeleteCompleteEvent
  - UserRegistrationDeleteEvent
  - UserRegistrationUpdateCompleteEvent
  - UserRegistrationUpdateEvent
  - UserRegistrationVerifiedEvent
  - UserTwoFactorMethodAddEvent
  - UserTwoFactorMethodRemoveEvent
  - UserUpdateCompleteEvent
  - UserUpdateEvent
# not events

# thorny cases
# - UserConsent
# 2 issues. The doc lives in the Consents doc. And it has a consent object. We don't want to crawl that object, but if we exclude it when we crawl UserConsent, we exclude it when we crawl Consent as well. Need to be more sophisticated about if we should crawl.
# - Reactor
# doesn't appear to follow the pattern
# email template preview, not sure if we are checking that
# entity is kinda weird because it takes an entity.type.id and returns an entity.type
# KickstartSuccessEvent has eventInfo and stuff because it extends baseevent, but doesn't seem to hydrate those values
