@startuml
  !include ../_config.plantuml

participant "Application" as app
participant API
app -> API : Present Credentials (API Key Or Other)
API -> API : Verify Credentials
API -> app : Resources Or Functionality
@enduml
