@startuml
  !include ../_config.plantuml

participant "Application" as app
participant FusionAuth
participant API
app -> FusionAuth : Request Token (Via Grant)
FusionAuth -> app : Present Token
app -> app : Store Token
app -> API : Present Token
API -> API : Verify Token Signature
API -> API : Verify Token Claims
API -> app : Resources Or Functionality
@enduml
