@startuml
  !include ../_config.plantuml

participant User
participant "Application" as app
participant "API" as api
User -> app : View Homepage
User -> app : Click Login Link
app -> User : Show Login Form
User -> app : Fill Out and Submit Login Form
app -> api : Submit Login Data
api -> api : Verifies User
api -> app : Return User's Account or Other Info
app -> User : Display User's Account or Other Info
@enduml
