@startuml
  !include ../_config.plantuml

participant User
participant "Application" as app
participant FusionAuth
User -> app : View Homepage
User -> app : Click Login Link (to FusionAuth)
User -> FusionAuth : View Login Form
FusionAuth -> User : Show Login Form
User -> FusionAuth : Fill Out and Submit Login Form
FusionAuth -> FusionAuth : Authenticates User
FusionAuth -> User: Go to Redirect URI
User -> app: Request the Redirect URI
app -> FusionAuth : Is User Authenticated?
FusionAuth -> app : User is Authenticated
app -> User : Display User's Account or Other Info
@enduml
