FusionAuth supports SAML both as an Identity Provider (IdP) and as a Service Provider (SP). The IdP implementation has certain limitations. 

Version `2.0` is supported; other SAML versions are unsupported.

Please examine the documented `NameIDPolicy` of the software package for which you are configuring FusionAuth to act as the IdP to determine the correct value. FusionAuth won't fail validation on any `NameIDPolicy` value, however if the requested `NameIDPolicy` is `persistent`, FusionAuth will use that, otherwise it will use `email` for the name Id.

Therefore, FusionAuth supports the following `NameIDPolicy` values:

* `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`
* `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`
* `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`

[NOTE]
====
Prior to version 1.28, FusionAuth supported two `NameIDPolicy` values:

* `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`
* `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`
====

FusionAuth supports the following SAMLv2 bindings:

* HTTP Redirect 
* HTTP POST

Other bindings are not supported.
