---
layout: doc
title: SAML v2 & PagerDuty
description: Setting up PagerDuty to login using FusionAuth via SAML v2
navcategory: login-methods
---

== PagerDuty + FusionAuth Integration Benefits

* Simplify user experience and maintain control using FusionAuth Single
Sign-on (SSO) to grant access to your PagerDuty application

== How it Works

* When a user reaches your PagerDuty login screen, it will have the
option to sign in using their credentials from your FusionAuth
application
** All user management will being handled by your FusionAuth service,
giving you a unique location to manage their access

== Requirements

*In PagerDuty:* you must have a
https://www.pagerduty.com/pricing/[Business or Digital Operations plan]
and be the *Account Owner* in order to enable Single Sign-On. For more
information about this feature, please visit their
https://support.pagerduty.com/docs/sso[SSO support page].

*In FusionAuth:* you need to have administrator access to the console.

== Support

If you need help with this integration, please visit our
https://fusionauth.io/docs/v1/tech/admin-guide/technical-support[Technical
Support page].

== Integration Walkthrough

=== In PagerDuty

. The _Account Owner_ can access SSO settings by navigating to the *User
Icon* > *Account Settings* > *Single Sign-On*
. Select the *SAML* radio button
. Copy the *SAML Endpoint URL*

_________________________________________________________________________________________________
For more details, please visit
https://support.pagerduty.com/docs/sso[PagerDuty SSO support page]
_________________________________________________________________________________________________

=== In FusionAuth

. Click the *Applications* link in the sidebar
. Create a new Application by clicking the green *+* button in the top
right corner of the page
. Enter a name for the app and then click on the *SAML* tab
. Click the *Enabled* switch to turn the integration on and…
* Define the *Issuer* as `\https://YOUR-SUBDOMAIN.pagerduty.com`
* Leave the *Audience* blank
* Paste the *SAML Endpoint URL* you copied from PagerDuty into
*Authorized redirect URLs*
. Save the application by clicking the blue floppy disk icon in the top
right corner of the page
. When redirected back to the *Applications* page, view your application
details by clicking the magnifier green icon
* In the dialog that opened, scroll down to *SAML v2 Integration
details* and…
** Copy the *Entity Id* URL and open it a new tab
** Copy the contents of the `X509Certificate` element and paste them
into PagerDuty’s *X.509 Certificate* field
*** You should paste the contents enclosed between
`-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`
**** Example:
+
[source,crt]
....
-----BEGIN CERTIFICATE-----
MIIDvzCCAqegAwIBAgIUbx1CGONbsu0XWYKWTUaq1CnUF2swDQYJKoZIhvcNAQEL
..................................... <rest of your certificate>
-----END CERTIFICATE-----
....
*** _Tip: If your browser doesn’t automatically format that file, you
can copy everything and use https://xmlviewer.org/[an online XML
beautifier]_
* Copy the *Login URL* from FusionAuth and paste it in PagerDuty’s own
*Login URL* field
. In PagerDuty, click *Save Changes* at the bottom of the screen
. To test the integration, open your PagerDuty application address in
another browser or in private mode
* Below the login form, click the blue *Sign In With Your Identity
Provider* button to navigate to the FusionAuth login screen
* After logging in, you should be automatically redirected to your
PagerDuty application already signed in with that same account

== How to Uninstall

. In PagerDuty, the _Account Owner_ can disable SSO settings by
navigating to the *User Icon* > *Account Settings* > *Single Sign-On*
and choosing the *PagerDuty* radio button
