---
layout: doc
title: SAML v2 & PagerDuty
description: Setting up PagerDuty to login using FusionAuth via SAML v2
navcategory: login-methods
---

== PagerDuty + FusionAuth Integration Benefits

* Simplify the user login experience because each user only has to remember one set of credentails.
* Maintain centralized control of who has access to your Pager Duty account.
* Authorized users gain transparent access between all applications using FusionAuth as an identity provider.
* Increase security and flexibility of login credentials, including using passkeys and multi-factor authentication

== How it Works

* When a user reaches the PagerDuty login screen, they can sign in using their credentials from FusionAuth.
* User management and access is managed by FusionAuth.

== Requirements

*In PagerDuty:* you must have a https://www.pagerduty.com/pricing/[Business or Digital Operations plan] and be the *Account Owner* in order to enable Single Sign-On. For more information about this feature, please visit their https://support.pagerduty.com/docs/sso[SSO support page]. If you do not have this role, please reach out to the **Account Owner** within your organization to configure the integration.

*In FusionAuth:* you need to be able to configure a SAML connection on an application. This can be done manually with a user account assigned either the `admin` or `application_manager` role. It can also be done with an API key that has the `application` permission.

== Support

If you need help with this integration, you can request assistance in one of two ways.

* If you have a plan which includes technical support, please https://account.fusionauth.io/account/support/[open a support ticket].
* If you do not have a plan which includes technical support, link:/community/forum/[please create a forum post].

You can review our link:/docs/v1/tech/admin-guide/technical-support[Technical Support documentation] for more details.

== Integration Walkthrough

=== In PagerDuty

. The _Account Owner_ can configure the SSO settings by navigating to [breadcrumb]#User Icon -> Account Settings -> Single Sign-On#.
. Select the *SAML* radio button.
. Copy the *SAML Endpoint URL*.

_________________________________________________________________________________________________
For more details, please visit
https://support.pagerduty.com/docs/sso[PagerDuty SSO support page]
_________________________________________________________________________________________________

=== In FusionAuth

. Click the [uielement]#Applications# link in the sidebar.
. Create a new Application by clicking the green *+* button in the top right corner of the page.
. Enter a name, such as *PagerDuty*, for the app and then click on the [breadcrumb]#SAML# tab.
. Set the [field]#Enabled# field to true to turn the integration on.
. Configure SAML functionality to integrate with your PagerDuty account.
* Set the [field]#Issuer# value to `\https://YOUR-SUBDOMAIN.pagerduty.com`, where `YOUR-SUBDOMAIN` is the value of your PagerDuty subdomain.
* Leave the [field]#Audience# blank.
* Paste the [uielement]#SAML Endpoint URL# you copied from PagerDuty into the [field]#Authorized redirect URLs# field. The value in this field will be blue when entered.
. Save the application by clicking the *blue floppy disk icon* in the top right corner of the page.
. When redirected back to the [breadcrumb]#Applications# page, view your application details by clicking the magnifier green icon.
* In the dialog, scroll down to the [uielement]#SAML v2 Integration details# section.
* Copy the [uielement]#Entity Id# URL and open it in a new browser tab. This will contain configuration you'll need shortly.
** _Note: This address contains an XML file. If your browser doesn’t automatically format it, you can copy everything and use https://xmlviewer.org/[an online XML beautifier]_.
** Copy the contents of the `X509Certificate` element from the XML file and paste them in PagerDuty.
*** You should paste the contents enclosed between `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`, like the example below:
+
[source,crt]
....
-----BEGIN CERTIFICATE-----
<contents of X509Certificate copied from FusionAuth>
-----END CERTIFICATE-----
....
* Copy the *Login URL* from FusionAuth [uielement]#SAML v2 Integration details# section and paste it in PagerDuty’s own *Login URL* field.
. In PagerDuty, click *Save Changes* at the bottom of the screen.

=== Testing

. To test the integration, open your PagerDuty application address in another browser or in private mode.
* Below the login form, click the blue *Sign In With Your Identity Provider* button to navigate to the FusionAuth login screen.
* After logging in, you should be automatically redirected to your PagerDuty application already signed in with that same account.

== How to Uninstall

In PagerDuty, the _Account Owner_ can disable SSO settings by navigating to the [breadcrumb]#User Icon -> Account Settings -> Single Sign-On# and choosing the *PagerDuty* radio button.
