---
layout: doc
title: Users
description: An overview of Users and core FusionAuth concepts
---

:sectnumlevels: 0

== Overview

FusionAuth is all about users, and it is helpful to fully understand how FusionAuth understands users to fully leverage all of the features FusionAuth offers.

The User itself is easy enough to understand, it represents your end user, your employee or your client. In order to help you manage users and what resources they are authorized to access we have built a few other concepts.

These are applications, groups and tenants. A tenant is a top level object that contains users, applications and groups. You may or may not have a use for Groups or Tenants, but it will be helpful to know how they work in case you have a future need.

* link:applications[Applications]
* link:groups[Groups]
* link:tenants[Tenants]

=== User scope

A User is scoped to a Tenant.  A User existing within a Tenant can be registered to, and use the same credentials to authenticate to multiple applications within that Tenant.
