---
layout: doc
title: Editions and Features
description: An explanation of editions and features
---
:page-liquid:

:sectnumlevels: 0

== Introduction

include::docs/v1/tech/shared/_licensing-premium-features-intro.adoc[]

== Editions and Features

There are four different editions.


* `Community` has all features not otherwise labelled.
* `Starter` has all premium features, but some may have some numeric limits.
* `Essentials` has all advanced and premium features, but some may have some numeric limits.
* `Enterprise` has all enterprise, advanced and premium features and no limits.

Please check the link:/pricing[pricing page] for more on features and editions.

== Feature List

=== Premium Features

// Don't add a new feature here. Add it to the site/_data/premiumfeatures.yaml file and the list will be generated.
{% include docs/_premium_features.liquid %}

=== Advanced Features

// Don't add a new feature here. Add it to the site/_data/premiumfeatures.yaml file and the list will be generated.
{% include docs/_advanced_features.liquid %}

=== Enterprise Features

// Don't add a new feature here. Add it to the site/_data/premiumfeatures.yaml file and the list will be generated.
{% include docs/_enterprise_features.liquid %}

== Documenting of Features

The FusionAuth documentation calls out features not part of the community edition so you can make an informed decision about which edition works for you.

You also may encounter an error message in the administrative user interface or an API message if a feature you are using requires a license.

=== Premium Features

Throughout the documentation, you'll see premium features marked like so:

include::docs/v1/tech/shared/_premium-edition-blurb.adoc[]

In the API documentation, you'll see premium features marked like this:

include::docs/v1/tech/shared/_premium-edition-blurb-api.adoc[]

=== Advanced Features

Throughout the documentation, you'll see advanced features marked like so:

include::docs/v1/tech/shared/_advanced-edition-blurb.adoc[]

In the API documentation, you'll see advanced features marked like this:

:advanced_feature: feature
include::docs/v1/tech/shared/_advanced-edition-blurb-api.adoc[]

:advanced_feature!:


=== Enterprise Features

Throughout the documentation, you'll see enterprise features marked like so:

include::docs/v1/tech/shared/_enterprise-edition-blurb.adoc[]

In the API documentation, you'll see enterprise features marked like this:

:enterprise_feature: feature
include::docs/v1/tech/shared/_enterprise-edition-blurb-api.adoc[]

:enterprise_feature!:

