---
layout: doc
title: Core Concepts
description: An overview of core FusionAuth concepts
---

:sectnumlevels: 0

== Overview

FusionAuth is all about users, and it is helpful to fully understand how FusionAuth understands users to fully leverage all of the features FusionAuth offers.

The User itself is easy enough to understand, it represents your end user, your employee or your client. In order to help you manage users and what resources they are authorized to access we have built a few other entities.

These are applications, roles, groups, registrations and tenants. A tenant is a top level object that contains users, applications and groups. Applications contain roles. Users have registrations with applications. 

You may or may not have a use for Groups or Tenants at present, but it will be helpful to know how they work in case you have a future need.

* link:/docs/v1/tech/core-concepts/users/[Users]
* link:/docs/v1/tech/core-concepts/roles/[Roles]
* link:/docs/v1/tech/core-concepts/groups/[Groups]
* link:/docs/v1/tech/core-concepts/registrations/[Registrations]
* link:/docs/v1/tech/core-concepts/applications/[Applications]
* link:/docs/v1/tech/core-concepts/tenants/[Tenants]
