---
layout: doc
title: Integration Points
description: FusionAuth easily integrates with existing or new applications
navcategory: getting-started
---

:sectnumlevels: 0

== Overview

You typically integrate FusionAuth into one or more applications. User data will live in FusionAuth (possibly synced with other data stores) and users will auth against it.

FusionAuth is a developer first platform and there are a large number of ways to integrate it into your new or existing applications.

* <<Login Options>>
** <<OAuth/OIDC/SAML>>
** <<Login API>>
** <<Federated Authentication>>
* <<JSON Web Tokens>>
** <<JWT Storage>>
* <<FusionAuth APIs>>
* <<Hosted Login Pages>>
* <<Hosted Backend>>
* <<SAML Integration Options>>
* <<Client Side API Usage>>
* <<Other Integration Points>>

== Login Options

There are three main ways to have your users sign in: OAuth/OIDC/SAML, the Login API, or federated authentication.

=== OAuth/OIDC/SAML

The first option is to use OAuth/OIDC/SAML. These are standards and FusionAuth should work with any library or application which supports them. If you find a library which supports OAuth or OIDC and does not work with FusionAuth, please https://github.com/FusionAuth/fusionauth-issues/issues/[open a bug], as we want to know about it. You can also use a link:/docs/v1/tech/client-libraries/[FusionAuth client library] to help with the OAuth/OIDC flow.

Using OAuth/OIDC lets your users authenticate and authorize; they'll receive the responses link:/docs/v1/tech/oauth/[documented for each grant]. If you choose SAML, link:/docs/v1/tech/samlv2/[configure FusionAuth as the IdP].

When you use this option, the data your client receives about the user is limited. You can put custom claims in your JWT using link:/docs/v1/tech/lambdas/[lambdas] if what you need is in the user or the registration objects.

If this level of integration meets your needs, you'll have more portability and less lock-in to FusionAuth.

=== Login API

You can also use the link:/docs/v1/tech/apis/login[Login API] to sign your users in directly. In this case, you will likely use one of the link:/docs/v1/tech/client-libraries/[FusionAuth client libraries].

When a user signs in with this API, you receive the entire user object, as well as the JWT.

When you build on top of the Login API, you're responsible for building the user interface for all login use cases. This gives you more control, as well. You can still use other FusionAuth provided user interfaces for use cases such as the forgot password flow.

Using the Login API means that since your application will see sensitive user credentials, you'll need to ensure the application secures such data appropriately. This is in contrast with the OAuth grants, where only the identity provider has access to the credentials, and your application only sees tokens.

=== Federated Authentication

Federated authentication, where FusionAuth isn't the system of record for users, is provided by link:/docs/v1/tech/apis/connectors/[Connectors] and link:/docs/v1/tech/identity-providers/[Identity Providers].

When this is used, FusionAuth will defer to the configured systems of record for authentication and authorization. Please consult the Connector or Identity Provider documentation for more information on these options.

== JSON Web Tokens

FusionAuth can create signed JSON web tokens. Customize these using the link:/docs/v1/tech/lambdas/jwt-populate[JWT Populate Lambda]. They can be signed with any of the link:/docs/v1/tech/apis/keys[supported key types].

When using OAuth/OIDC, there are multiple kinds of tokens: link:/docs/v1/tech/oauth/tokens[Access Tokens, Id Tokens and Refresh Tokens]. The Login API can also generate a JWT.

These tokens can be consumed by APIs or other systems to verify that the holder of the token has been authorized by FusionAuth. link:/learn/expert-advice/tokens/[Learn more about JWTs].

=== JWT Storage

FusionAuth recommends the Authorization Code grant, where there is a server side component which exchanges the one-time use authorization code for an access token. This server side component offers a lot of flexibility when it comes to storing the JWT.

But what should you do with it? After all, an access token is a bearer token, and should be properly secured. What you do with the token depends on what you are using it for as well as your security requirements. If you are wondering about your options, link:/learn/expert-advice/authentication/login-authentication-workflows[here are a number of common login flows].

Recommended storage mechanisms include:

* sending the token down to the browser as a `Secure`, `HTTPOnly` cookie. If you don't require cross-site cookie sharing, set `SameSite` to `Strict`. Otherwise, set `SameSite` to `Lax`, which will share the cookies in certain situations. Learn more about https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite[`SameSite` settings].
* storing it server side, in a session. The session is typically managed by a framework, and ideally adheres to the same cookie storage recommendations. Learn more about https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html[server side sessions]. Please consult your framework documentation around securing sessions and data in sessions.

.JWT Storage Options
[cols="3,1,1"]
|===
| Feature | Cookie | Server Side Session

|Allows for easy horizontal scaling
|Yes
|No

|Revocation possible
|link:/learn/expert-advice/tokens/revoking-jwts[Yes]
|Yes

|Revocation easy
|No
|Yes

|Sticky sessions or session datastore required
|No
|Yes

|Token transparently sent on requests (to APIs, etc)
|Yes
|N/A

|Token can be presented to APIs on domains other than that in which the cookie setting component resides
|No
|Yes (via server side requests)

|===

The proper JWT storage choice should be based on your threat modeling. You can configure your JWTs to be short lived, which minimizes the amount of time a stolen JWT can be used.

If you need to lock down JWTs further, implement https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html#token-sidejacking[token sidejacking protection] using cookies and a nonce. An alternative is https://github.com/FusionAuth/fusionauth-issues/issues/1679[DPoP], an open feature request for FusionAuth.

== FusionAuth APIs

Whether you use the Login API, identity federation, or an OAuth grant, you can use additional link:/docs/v1/tech/apis/[FusionAuth APIs] in your application.

These allow your application to access and modify data and entities beyond that available from OIDC/OAuth/SAML or a federated identity.

Common tasks such as registering a user to an application, removing them from a group, capturing a consent, or capturing custom data are accomplished with these APIs. APIs can also be used to manage entities other than users, such as applications, tenants or Identity Providers.

The upside of using these is the ability to leverage the FusionAuth data model and functionality. The downside is that your application is coupled to FusionAuth.

== Hosted Login Pages

You'll see the phrase "hosted login pages" used throughout the FusionAuth site. These are all the pages that your end user sees when you are hosting your login experience on FusionAuth, as opposed to within your application. These pages are link:/docs/v1/tech/themes/[themeable]; you can make them look exactly like your website or application.

Using the hosted login pages has a number of advantages. By doing so, FusionAuth handles the complexity of a number of different auth related use cases. These use cases include, but are not limited to, the following:

include::docs/v1/tech/shared/_list-hosted-login-pages-use-cases.adoc[]

Additionally, when you use the hosted login pages, FusionAuth provides transparent single sign on (SSO) between applications as well as support for localization of the user interface.

The alternative to using the hosted login pages is building your own login experience. You can then use the APIs or an OAuth grant to authenticate your user against FusionAuth. This alternative gives you more control at the cost of more development effort.

== Hosted Backend

The Authorization Code grant requires the use of a server side application to do the token exchange. This is often called the "backend". This server side code can securely hold secrets, which a client such as a single-page application (SPA) cannot. It also can send the access token to a SPA as a secure, `HTTPOnly` cookie.

Running your own backend offers you a lot of flexibility. However, it is not the correct solution for all situations.

As of version 1.45, FusionAuth provides a hosted backend. This is included with every FusionAuth installation and can be used to quickly integrate OAuth into a front-end only application.

Please consult the link:/docs/v1/tech/apis/hosted-backend[Hosted Backend API documentation for more details]. You can also work through a link:/docs/v1/tech/tutorials/integrate-react[React quickstart] which uses the hosted backend.

== SAML Integration Options

You can use SAML to integrate with FusionAuth in a few different ways, depending on the role that FusionAuth is playing and your other needs.

FusionAuth supports both Service Provider initiated login, as well as Identity Provider initiated login in both the Service Provider and Identity Provider roles.

In other words, FusionAuth can act as a SAML v2 Identity Provider or a SAML v2 Service provider, and in either configuration both SP and IdP initiated login flows are supported.


=== SP (Service Provider) Initiated Login

This is a traditional integration and the Service Provider will initiate the login request to the Identity Provider by building an AuthN request and sending it to the Identity Provider.

To configure FusionAuth as the Service Provider, see link:/docs/v1/tech/identity-providers/samlv2/[SAML v2 Identity Provider]. To configure FusionAuth as the Identity Provider, see link:/docs/v1/tech/samlv2/[SAML v2].

=== IdP (Identity Provider) Initiated Login
In this configuration, the login request is not solicited by the Service Provider, and instead the Identity Provider builds an AuthN response and sends it to the Service Provider.

To configure FusionAuth as the Service Provider, see  link:/docs/v1/tech/identity-providers/samlv2/[SAML v2 Identity Provider] and  link:/docs/v1/tech/identity-providers/samlv2-idp-initiated/[SAML v2 IdP Initiated Identity Provider]. To configure FusionAuth as the Identity Provider, see link:/docs/v1/tech/samlv2/[SAML v2].

.Summary of SAML v2 integration options
[cols="1,1,1,1"]
|===
| FusionAuth is the | Login initiated by | Replay protection | More details

|Service Provider
|Service Provider
|Yes
|link:/docs/v1/tech/identity-providers/samlv2/[SAML v2  Identity Provider]

|Service Provider
|Identity Provider
|Yes
|link:/docs/v1/tech/identity-providers/samlv2-idp-initiated/[SAML v2 IdP Initiated Identity Provider], link:/docs/v1/tech/identity-providers/samlv2/[SAML v2 Identity Provider]

|Identity Provider
|Service Provider
|No. This is managed by the SP.
|link:/docs/v1/tech/samlv2/[SAML v2]

|Identity Provider
|Identity Provider
|No. This is managed by the SP.
|link:/docs/v1/tech/samlv2/[SAML v2]

|===

*_Note:_* _SP_ refers to the Service Provider, and _IdP_ refers to the Identity Provider.

== Client Side API Usage

include::docs/v1/tech/shared/_client-side-api-keys.adoc[]

== Other Integration Points

There are a number of other integration points in FusionAuth beyond the APIs.

* link:/docs/v1/tech/apis/connectors/[Connectors] allow you to authenticate against external user data sources, and optionally migrate users into FusionAuth.
* link:/docs/v1/tech/account-management/[Account Management] Allows admins and users to dynamically edit user data, user passwords, and enable multi-factor authentication.
* link:/docs/v1/tech/identity-providers/[Identity Providers] allow you to federate authentication decisions to social or standards based providers. You can also specify a linking strategy which allows you to flexibly map between accounts with different identifiers.
* link:/docs/v1/tech/lambdas/[Lambdas] allow you to run business logic at certain points in the authentication lifecycle.
* link:/docs/v1/tech/plugins/[Plugins] allow you to extend FusionAuth with custom Java code. Currently the main use is to allow you to use custom password hashing. This allows you to import user data from existing systems without requiring user password changes.
* link:/docs/v1/tech/events-webhooks/[Webhooks] allow you to send data to external systems when events occur in FusionAuth.
* link:/docs/v1/tech/admin-guide/monitor[Monitoring] provides insight into a FusionAuth instance's debug messages, performance metrics and other data.
