---
layout: doc
title: Registrations
description: An overview of FusionAuth Registrations
navcategory: getting-started
---

:sectnumlevels: 0

== Overview

Registrations in FusionAuth are the link between link:/docs/v1/tech/core-concepts/users[Users] and link:/docs/v1/tech/core-concepts/applications[Applications].

A User can have zero or more registrations. Each registration can have zero or more link:/docs/v1/tech/core-concepts/roles[roles] associated with it. 


The link:/docs/v1/tech/apis/registrations[registrations API] documents the allowed attributes of a User registration.

If a User exists in a link:/docs/v1/tech/core-concepts/roles[tenant] and attempts to authenticate against an link:/docs/v1/tech/core-concepts/applications[Application], but are not registered, the link:/docs/v1/tech/core-concepts/authentication-authorization[authentication will succeed but they will not be authorized].

=== Attributes

With link:/docs/v1/tech/guides/advanced-registration-forms[advanced registration forms], you can customize the attributes of a registration. By default, registrations have the following attributes:

include::docs/v1/tech/core-concepts/_registration_attributes.adoc[]

=== Registrations and Self-Service Registration

When you enable self-service registration for an application and a user who does not have a registration for that application successfully logs in to that application, the user will automatically have a registration added for that application.

Let's walk through a scenario. Suppose there are three applications:

* Hooli Jobs
* Pied Piper Video Chat (which has self-service registration enabled)
* Pied Piper Email Service (which **does not** have self-service registration enabled)

User `richard@piedpiper.com` has a valid account, and has a registration for the Hooli Jobs.

When Richard tries to log into Pied Piper Video Chat, he is able to log in. He is automatically registered for this application, since self service registration is turned on for it. Therefore the `applicationId` claim is present in the token and any default roles are associated with his account.

When Richard tries to log into Pied Piper Email Service, he is able to log in, since he has a valid account in the tenant. But Richard is not registered for the application. Therefore no roles are associated with him and the `applicationId` claim is not present.

You can read more about link:/docs/v1/tech/core-concepts/authentication-authorization[authentication vs authorization and registrations].
