---
layout: doc
title: Registrations
description: An overview of FusionAuth Registrations
---

:sectnumlevels: 0

== Overview

Registrations in FusionAuth are the link between link:/docs/v1/tech/core-concepts/users/[Users] and link:/docs/v1/tech/core-concepts/applications/[Applications].

A User can have zero or more registrations. Each registration can have zero or more link:/docs/v1/tech/core-concepts/roles/[roles] associated with it. 


The link:/docs/v1/tech/apis/registrations/[registrations API] documents the allowed attributes of a User registration.

If a User exists in a link:/docs/v1/tech/core-concepts/roles/[tenant] and attempts to authenticate against an link:/docs/v1/tech/core-concepts/application/[Application], but are not registered, the link:/docs/v1/tech/core-concepts/authentication-authorization/[authentication will succeed but they will not be authorized].

=== Attributes

With link:/docs/v1/tech/guides/advanced-registration-forms/[advanced registration forms], you can customize the attributes of a registration. By default, registrations have the following attributes:

include::docs/v1/tech/core-concepts/_registration_attributes.adoc[]

