---
layout: doc
title: Registrations
description: An overview of FusionAuth Registrations
navcategory: getting-started
---
:page-liquid:
:sectnumlevels: 0

== Overview

Registrations in FusionAuth are the link between link:/docs/v1/tech/core-concepts/users[Users] and link:/docs/v1/tech/core-concepts/applications[Applications].

A User can have zero or more registrations. Each registration can have zero or more link:/docs/v1/tech/core-concepts/roles[roles] associated with it. 


The link:/docs/v1/tech/apis/registrations[registrations API] documents the allowed attributes of a User registration.

If a User exists in a link:/docs/v1/tech/core-concepts/roles[tenant] and attempts to authenticate against an link:/docs/v1/tech/core-concepts/applications[Application], but are not registered, the link:/docs/v1/tech/core-concepts/authentication-authorization[authentication will succeed but they will not be authorized].

== Core Concepts Relationships

Below is a visual reminder of the relationships between FusionAuth's primary core concepts.

++++
{% mermaid %}
{% include docs/_users-tenants-relation.liquid onregistrationpage ="true" %}
{% endmermaid %}
++++

=== Attributes

With link:/docs/v1/tech/guides/advanced-registration-forms[advanced registration forms], you can customize the attributes of a registration. By default, registrations have the following attributes:

include::docs/v1/tech/core-concepts/_registration_attributes.adoc[]

=== Registrations and Self-Service Registration

include::docs/v1/tech/shared/_registrations-self-service.adoc[]
