---
layout: doc
title: Roles
description: An overview of FusionAuth Roles
---

:sectnumlevels: 0

== Overview

Roles in FusionAuth are associated with an link:/docs/v1/tech/core-concepts/applications/[application].

You can define as many roles as you want in an application. There are no limits on the number of roles a user or a group can have. Roles are application specific and may be tuned to the domain. 

For example, an e-commerce application may have the following roles:

* admin
* seller
* shopper

A content management system may have these roles instead:

* admin
* editor
* contributor
* subscriber

Roles are available in a link:/docs/v1/tech/oauth/tokens/[token] upon successful link:/docs/v1/tech/core-concepts/authentication-authorization[authorization] and are also returned when as part of the link:/docs/v1/tech/apis/registrations/[user's registrations].

Roles are often used by APIs and applications to control access to functionality. For example, Zendesk presents a different user interface to users with the `agent` role than to users without that role. 

You can associate roles with link:/docs/v1/tech/core-concepts/users/[users] directly via their link:/docs/v1/tech/core-concepts/registrations/[registration]. Or you can assign an application role to a link:/docs/v1/tech/core-concepts/groups/[group], and then any users in that group who have access to that application will have that role.

=== Role Attributes

Roles have the following attributes:

include::docs/v1/tech/core-concepts/_role_attributes.adoc[]

=== FusionAuth Roles

FusionAuth provides a number of built-in roles which can be assigned to any user registered with the FusionAuth application. These roles control access to functionality within the FusionAuth administrative user interface.

