---
layout: doc
title: Search
description: Search options within FusionAuth
---

:sectnumlevels: 0

== Overview

SCIM (System for Cross-domain Identity Management) is a specification for a client to provision users and groups on a server using a standard protocol. FusionAuth can consume SCIM formatted requests and act as the provisioning server in a SCIM client/server environment.

Follow the links below for details about the SCIM specification and detailed information about the protocols and schemas:

- http://www.simplecloud.info/ Overview of the specification and links to all relevant RFCs.
- https://datatracker.ietf.org/doc/html/rfc7642 Direct link to the RFC defining the overall concepts and requirements.
- https://datatracker.ietf.org/doc/html/rfc7644 Direct link to the RFC defining the protocol.
- https://datatracker.ietf.org/doc/html/rfc7643 Direct link to the RFC defining the core schem definitions.

== FusionAuth SCIM Support

Any SCIM client can make requests to FusionAuth using the SCIM specification for defining Users and Groups. In this scenario FusionAuth acts as the provisioning server and can respond with SCIM compliant responses.

=== The FusionAuth SCIM Workflow

This is an example of a basic interaction between an external SCIM client provisioning request to create a FusionAuth User:

1. The client would send a SCIM compliant request to the FusionAuth link:/docs/v1/tech/apis/scim/index[SCIM API endpoint].
+
[source,json]
.Example User Create Request JSON
----
include::../../../src/json/scim/user-create-request.json[]
----
+
2. FusionAuth will authenticate the incoming request as coming from a known SCIM client.
+

3. FusionAuth will call the defined incoming request lambda passing the SCIM request data and a FusionAuth User object. The incoming request lambda is then responsible for converting the incoming SCIM request data into the appropriate User properties.
+

4. FusionAuth will attempt to create the FA User using the returned User data from the incoming request lambda.
+
5. Upon success, FusionAuth will call the outgoing response lambda passing the newly created FusionAuth User and the SCIMResponse. The outgoing lambda is then responsible for converting the FusionAuth User properties to the appropriate SCIM Response data.
+

== Configuration

In order for FusionAuth to accept requests from your SCIM clients, you need to setup a few things.

- You need to enable SCIM support on your tenant.
+
+
- You need to define your incoming request and outgoing response lambdas for each the supported SCIM resource types (User, Enterprise User, Group)
+
+
- You will need to verify that the default SCIM schemas provided match your desired SCIM schema for each of the SCIM resource types.
+
+
- You will need an Entity defined for each of you SCIM clients.
+

== FusionAuth SCIM API Endpoints

In order to use FusionAuth as your SCIM provisioning server for all of your SCIM clients, you will need to call the correct FusionAuth SCIM API endpoint. FusionAuth provides endpoints for retrieving, creating, replacing, and deleting SCIM Users, EnterpriseUsers, and Groups.

link:/docs/v1/tech/apis/scim[API Overview]








