---
layout: doc
title: Search
description: Search options within FusionAuth
---

:sectnumlevels: 0

== Overview

SCIM (System for Cross-domain Identity Management) is a specification for a client to provision users and groups on a server using a standard protocol. FusionAuth can consume SCIM formatted requests and act as the provisioning server in a SCIM client/server environment.

Follow the links below for details about the SCIM specification and detailed information about the protocols and schemas:

- http://www.simplecloud.info/ Overview of the specification and links to all relevant RFCs.
- https://datatracker.ietf.org/doc/html/rfc7642 Direct link to the RFC defining the overall concepts and requirements.
- https://datatracker.ietf.org/doc/html/rfc7644 Direct link to the RFC defining the protocol.
- https://datatracker.ietf.org/doc/html/rfc7643 Direct link to the RFC defining the core schem definitions.

== FusionAuth SCIM support

Any client can make requests to FusionAuth using the SCIM specification for defining Users and Groups. In this scenario FusionAuth acts as the provisioning server and can respond with SCIM compliant responses.

=== The FusionAuth SCIM Workflow

A basic interaction between an external SCIM client provisioning request to create a FusionAuth User, would include the following steps:

<TODO: insert pic here? SCIM client -> FA API -> FA Auth -> FA calls lambda to translate to FA User -> FA creates User -> FA calls lambda to translate from FA User to SCIM schema -> FA sends a SCIM compliant response to SCIM client >

1. The client would send a SCIM compliant request to the FusionAuth SCIM API endpoint <TODO: link to create user scim API endpoint>.

<TODO: insert example request body>

2. FusionAuth will authenticate the incoming request as coming from a known SCIM client.

<TODO: insert link to How to configure Entity for known SCIM client auth.>

3. FusionAuth will call the defined incoming request lambda passing the SCIM request data and a FusionAuth User object. The incoming request lambda is then responsible for converting the incoming SCIM request data into the appropriate User properties.

<TODO: insert link to Configuring SCIM lambdas.>

4. FusionAuth will attempt to create the FA User using the returned User data from the incoming request lambda.

5. Upon success, FusionAuth will call the outgoing response lambda passing the newly created FusionAuth User and the SCIMResponse. The outgoing lambda is then responsible for converting the FusionAuth User properties to the appropriate SCIM Response data.

<TODO: insert example response body>



