#!/bin/sh
set -e

cd $(dirname "$0")

IMAGE_NAME="fusionauth-site:latest"
PORT=${1:-3000}

# Building image
if [ "$(docker images -q "${IMAGE_NAME}" 2> /dev/null)" = "" ]; then
    docker build -t "${IMAGE_NAME}" .
fi

# Running docker
CID=$(docker run --rm -q -d -v "${PWD}:/app" -p "${PORT}:3000" "${IMAGE_NAME}")
echo "Started Astro container on http://localhost:${PORT}"
echo "If you want to see the logs, run:"
echo "docker logs -f ${CID}"
