---
layout: doc
title: Events
description: Learn about the different events that FusionAuth generates
---

== Events

These are the events that FusionAuth generates that can be optionally consumed by your registered Webhook.

* <<User Actions>> - when a moderator takes an action on a user
* <<User Bulk Create>> - when multiple users are created as the result of the Import API
* <<User Create>> - when a user is created
* <<User Update>> - when a user is updated
* <<User Deactivate>> - when a user is deactivated
* <<User Reactivate>> - when a user is reactivated
* <<User Delete>> - when a user is deleted
* <<User Email Verified>> - when a user verifies their email address
* <<User Login Success>> - when a user successfully completes login
* <<User Login Failure>> - when a user fails to complete login
* <<User Password Breach>> - when Reactor detects a user is using a potentially breached password
* <<User Registration Create>> - when a new user registration is created
* <<User Registration Update>> - when a user registration is update
* <<User Registration Delete>> - when a user registration is deleted
* <<User Registration Verified>> - when a user completes registration verification
* <<JWT Public Key Update>> - when a JWT RSA Public / Private keypair used for signing may have been updated.
* <<JWT Refresh>> - when an access token is refreshed using a refresh token
* <<JWT Refresh Token Revoke>> - when a refresh token (or multiple tokens) are revoked

=== Application Scoped Events

A few events can be generated for one or more specified applications, or for all applications within a tenant. 

[WARNING]
====
The ability to limit the generation of an event for only certain applications is legacy functionality and may be modified in the future. You almost certainly want to use a tenant scoped event and optionally filter on the `applicationId` when consuming the event.
====

These events can be application scoped:

* `jwt.public-key.update`
* `jwt.refresh-token.revoke`
* `user.action`

=== Tenant Scoped Events

Any events which are not application scoped events are tenant scoped. 

Tenant scoped events can't be limited to fire only for a certain application. These events are either generated for all applications in a tenant or for none of them.

All user events are tenant scoped because a user is a tenant scoped entity. For example, the `user.delete`, `user.create`, `user.update`, and `user.deactivate` events are all tenant scoped.

A tenant scoped event can, however contain an `applicationId` which can be used to filter events when received. One example is `user.registration.create`. 

== User Actions

This event is generated when a User Action is taken on a user and when temporal actions transition between phases.

A temporal action is one that has a start time and and a duration, when a phase transition occurs an event will be sent to the webhook. See the [field]#event.phase# in the message body.

[source,shell]
.Event type
----
user.action
----

=== Event Body

[.api]
[field]#event.action# [type]#[String]#::
This parameter specifies the name of the action that is occurring.

[field]#event.actionId# [type]#[UUID]#::
This parameter specifies the unique Id of the action that is occurring.

[field]#event.actioneeUserId# [type]#[UUID]#::
This parameter specifies the unique identifier of the user the action is being performed on.

[field]#event.actionerUserId# [type]#[UUID]#::
This parameter specifies the Id of the User that performed the action that resulted in the notification being sent. If the action was initiated by FusionAuth this value will not be provided.

[field]#event.applicationIds# [type]#[Array<UUID>]#::
This parameter if provided specifies the scope of the User Action. When an Action is scoped to one or more Applications the Application Ids will be provided in this parameter.

[field]#event.comment# [type]#[String]#::
An optional comment left to possibly indicate why the action was taken, modified or canceled.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.email# [type]#[Object]#::
When the action is configured to send the email in the event body, FusionAuth will render the email and provide the result in the event body. This can be used to send an email through a third party provider. See Example POST body below for fields.

[field]#event.emailedUser# [type]#[Boolean]#::
This parameter will indicate if FusionAuth has already sent an email to the user as a result of this event. When `true` an email was sent to the user, and if `false` an email was not sent to the user.

[field]#event.expiry# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the action will expire, if the action expires.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.localizedAction# [type]#[String]#::
This parameter specifies the localized version of the [field]#action# field, based on the user's preferred languages.

[field]#event.localizedDuration# [type]#[String]#::
The duration of the action in a human readable format that is localized based on the user's preferred languages.

[field]#event.localizedOption# [type]#[String]#::
This parameter specifies the localized version of the [field]#option# field, based on the user's preferred languages.

[field]#event.localizedReason# [type]#[String]#::
This parameter specifies the localized reason of the [field]#reason# field, based on the user's preferred languages.

[field]#event.notifyUser# [type]#[Boolean]#::
This parameter specifies whether the user should be notified. FusionAuth will only set this value based upon the event configuration, it is simply an indicator to the event consumer to notify the user.

[field]#event.option# [type]#[String]#::
An optional value to provide additional context to the Action. This value is free form and defined by the User Action.

[field]#event.phase# [type]#[Boolean]#::
If the Action is temporal, this parameter will be provided to indicate the current phase of the action. The following are the possible Action states:
+
    * `start` - The event has started.
    * `modify` - The event has been modified.
    * `cancel` - The event has been canceled, the `end` phase will not be reached.
    * `end` - The event has ended.
+
When the action is started by an admin, the phase will be "start". If an admin changes the duration of the action, the phase will be "modify". If an admin cancels an action it will be "cancel" or the action expires, the phase will be "end". If the action is key-based, the phase will be "start".

[field]#event.reason# [type]#[String]#::
The reason the admin selected. Reasons may be configured in the FusionAuth UI, navigate to [breadcrumb]#Settings -> User Actions -> Reasons#. This value will be omitted when no reasons are selected (or configured).

[field]#event.reasonCode# [type]#[String]#::
The reason code the admin selected. Reasons may be configured in the FusionAuth UI, navigate to [breadcrumb]#Settings -> User Actions -> Reasons#. This value will be omitted when no reasons are selected (or configured).

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.action`.


[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-actions.json[]
----

== User Bulk Create

This event is generated when multiple users are created. The JSON includes each of the Users that were created.

The final state of the operation which caused the webhook is not persisted to FusionAuth until after the webhook finishes; link:/docs/v1/tech/events-webhooks/writing-a-webhook/#calling-fusionauth-apis-in-webhooks[learn more].

[source,shell]
.Event type
----
user.bulk.create
----

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.bulk.create`.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.users# [type]#[Array<Object>]#::
The users that have been created. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-bulk-create.json[]
----

== User Create

This event is generated when a single user is created. The JSON includes the User that was created.

The final state of the operation which caused the webhook is not persisted to FusionAuth until after the webhook finishes; link:/docs/v1/tech/events-webhooks/writing-a-webhook/#calling-fusionauth-apis-in-webhooks[learn more].

[source,shell]
.Event type
----
user.create
----

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.create`.

[field]#event.user# [type]#[Object]#::
The user that has been created. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-create.json[]
----

== User Update

This event is generated when a user is updated. The event will include the before and after versions of the User being updated.

[source,shell]
.Event type
----
user.update
----

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.original# [type]#[Object]#::
The user before the update occurred, this is the old version of the user. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.update`.

[field]#event.user# [type]#[Object]#::
The user after the update, this is the new version of the user. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.



=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-update.json[]
----

== User Deactivate

This event is generated when a user is deactivated, also referred to as a soft delete.

[source,shell]
.Event type
----
user.deactivate
----


=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.deactivate`.

[field]#event.user# [type]#[Object]#::
The user that has been deactivated. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.



=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-deactivate.json[]
----

== User Reactivate

This event is generated when user is re-activated, a re-activated user is one that had been soft deleted and has now been un-deleted.

[source,shell]
.Event type
----
user.reactivate
----

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.reactivate`.

[field]#event.user# [type]#[Object]#::
The user that has been re-activated. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.



=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-reactivate.json[]
----

== User Delete

This event is generated when a user is deleted.

[source,shell]
.Event type
----
user.delete
----

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.delete`.

[field]#event.user# [type]#[Object]#::
The user that has been deleted. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-delete.json[]
----

== User Email Verified

[NOTE.since]
====
This event has been available since 1.8.0
====

This event is generated when a user verifies their email address.

[source,shell]
.Event type
----
user.email.verified
----

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.email.verified`.

[field]#event.user# [type]#[Object]#::
The user that has verified their email address. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-email-verified.json[]
----

== User Login Success

[NOTE.since]
====
This event has been available since 1.6.0
====

This event is generated when a user completes a successful login.

[source,shell]
.Event type
----
user.login.success
----

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the user has requested login. If the login request omits the [field]#applicationid# or the user is not registered for the requested [field]#applicationId# this value will not be returned in the event.

[field]#event.authenticationType# [type]#[String]#::
The type of authentication used in the login request.

[field]#event.connectorId# [type]#[UUID]# [since]#Available since 1.18.0#::
The unique Id of the connector used to complete the login.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.identityProviderId# [type]#[UUID]#::
The unique Id of the identity provider used to complete the login. This value will be omitted from the event if an identity provider was not used.

[field]#event.identityProviderName# [type]#[String]#::
The name of the identity provider used to complete the login. This value will be omitted from the event if an identity provider was not used.

[field]#event.ipAddress# [type]#[String]# [since]#Available since 1.26.0#::
The ip address provided in the login request.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.login.success`.

[field]#event.user# [type]#[Object]#::
The user that completed the login request. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.

=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-login-success.json[]
----

== User Login Failure

[NOTE.since]
====
This event has been available since 1.6.0
====

This event is generated when a user login request fails due to invalid credentials.

[source,shell]
.Event type
----
user.login.failed
----

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the user has requested login. If the login request omits the [field]#applicationid# or the user is not registered for the requested [field]#applicationId# this value will not be returned in the event.

[field]#event.authenticationType# [type]#[String]#::
The type of authentication used in the login request.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.ipAddress# [type]#[String]# [since]#Available since 1.26.0#::
The ip address provided in the login request.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.login.failed`.

[field]#event.user# [type]#[Object]#::
The user that failed the login request. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-login-failed.json[]
----

== User Password Breach

[NOTE.since]
====
This event has been available since 1.15.0
====

This event is generated when Reactor detects a user is using a vulnerable, or breached password. This event will only occur during login when the Tenant is not configured to require the user to change their password. All other breached password detections will occur during password validation and because the user will not be allowed to use the password.

[source,shell]
.Event type
----
user.password.breach
----

=== Event Body

[.api]
[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.tenantId# [type]#[UUID]#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.password.breach`.

[field]#event.user# [type]#[Object]#::
The user that failed the login request. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-password-breach.json[]
----

== User Registration Create

[NOTE.since]
====
This event has been available since 1.6.0
====

This event is generated when a user registration is created.

The final state of the operation which caused the webhook is not persisted to FusionAuth until after the webhook finishes; link:/docs/v1/tech/events-webhooks/writing-a-webhook/#calling-fusionauth-apis-in-webhooks[learn more].

[source,shell]
.Event type
----
user.registration.create
----

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the user has now been registered.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.registration# [type]#[Object]#::
The user registration that has been created. See the link:/docs/v1/tech/apis/registrations/[Registration API] for property definitions and example JSON.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.registration.create`.

[field]#event.user# [type]#[Object]#::
The user that owns the new registration. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-registration-create.json[]
----

== User Registration Update

[NOTE.since]
====
This event has been available since 1.6.0
====

This event is generated when a user registration has been updated.

[source,shell]
.Event type
----
user.registration.update
----

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the user registration has been updated.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.original# [type]#[Object]#::
The original registration prior to being updated. See the link:/docs/v1/tech/apis/registrations/[Registration API] for property definitions and example JSON.

[field]#event.registration# [type]#[Object]#::
The user registration that has been updated. See the link:/docs/v1/tech/apis/registrations/[Registration API] for property definitions and example JSON.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.registration.update`.

[field]#event.user# [type]#[Object]#::
The user that owns the registration being updated. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.



=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-registration-update.json[]
----

== User Registration Delete

[NOTE.since]
====
This event has been available since 1.6.0
====

This event is generated when a user registration has been deleted.

[source,shell]
.Event type
----
user.registration.delete
----

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the user's registration has been deleted.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.registration# [type]#[Object]#::
The user registration that has been deleted. See the link:/docs/v1/tech/apis/registrations/[Registration API] for property definitions and example JSON.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.registration.delete`.

[field]#event.user# [type]#[Object]#::
The user that owns the registration being deleted. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-registration-delete.json[]
----

== User Registration Verified

[NOTE.since]
====
This event has been available since 1.8.0
====

This event is generated when a user registration has been verified.

[source,shell]
.Event type
----
user.registration.verified
----

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the user registration has been updated.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.registration# [type]#[Object]#::
The user registration that has been verified. See the link:/docs/v1/tech/apis/registrations/[Registration API] for property definitions and example JSON.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `user.registration.verified`.

[field]#event.user# [type]#[Object]#::
The user that owns the registration being updated. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/user-registration-verified.json[]
----

== JWT Public Key Update

This event is generated when a public key configuration used to sign a JSON web token has been updated.


[source,shell]
.Event type
----
jwt.public-key.update
----

=== Event Body

[.api]
[field]#event.applicationIds# [type]#[Array<UUID>]#::
A list of Application Ids that may have been affected by a configuration change in which affect the public key used to sign JWTs.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `jwt.public-key.update`.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/jwt-public-key-update.json[]
----

== JWT Refresh

[NOTE.since]
====
This event has been available since 1.16.0
====

This event is generated when an access token is refreshed using a refresh token. This event is initiated from both the link:/docs/v1/tech/oauth/endpoints#refresh-token-grant-request[OAuth2 Refresh Token Grant], and the link:/docs/v1/tech/apis/jwt#refresh-a-jwt[Refresh a JWT API].

[source,shell]
.Event type
----
jwt.refresh
----

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the token provides access.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.original# [type]#[String]#::
The original encoded access token which was provided on the JWT refresh request.  This field will be omitted if the [field]#token# parameter was not provided on the initiating request.

[field]#event.refreshToken# [type]#[String]#::
The refresh token which was provided on the JWT refresh request, used in refreshing the JWT.

[field]#event.token# [type]#[String]#::
The new encoded access token.

[field]#event.tenantId# [type]#[UUID]#::
The unique tenant identifier.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `jwt.refresh`.


=== Event JSON

[source,json]
.Example Event JSON
----
include::docs/src/json/events/jwt-refresh.json[]
----

== JWT Refresh Token Revoke

This event is generated when a refresh token is revoked. The JSON includes either the User Id and User or the Application Id depending on what was revoked. It will also include the time to live duration (in seconds) for each Application. This value is used to determine if JWTs are valid or not based on their expiration instants.

The following scenarios will cause this event to be generated:

* A single Refresh Token is revoked
* All Refresh Tokens owned by a single User are revoked
* All Refresh Tokens for an Application are revoked

[source,shell]
.Event type
----
jwt.refresh-token.revoke
----

=== A single Refresh Token is revoked

This example JSON would reflect a scenario where a single refresh token is revoked for a single user for a single application.

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which the refresh token have been revoked.

[field]#event.applicationTimeToLiveInSeconds# [type]#[Map<UUID, Integer>]#::
A map of Application Id to the configured time to live (TTL) for the access token (JWT). This can be used to identify the maximum amount of time after this event occurred where an un-expired access token may be held by a user.
+
If you take the [field]#createInstant# of this event and add the number of seconds for a specific application TTL you come up with an instant in time where you should consider all access tokens issued before this time invalid. This is because the access token will have been issued on or before the instant the refresh token was revoked.
+
This map will contain a single entry for the application represented by the [field]#applicationId# field.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `jwt.refresh-token.revoke`.

[field]#event.userId# [type]#[UUID]#::
The unique Id of the User for which a refresh token has been revoked.

[field]#event.user# [type]#[Object]# [since]#Available since 1.8.0#::
The user for which a refresh token has been revoked. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


[source,json]
.Example Event JSON
----
include::docs/src/json/events/jwt-refresh-token-revoke-user.json[]
----

=== All Refresh Tokens owned by a single User are revoked

This example JSON would reflect a scenario where all refresh tokens owned by a single user are revoked.

=== Event Body

[.api]
[field]#event.applicationTimeToLiveInSeconds# [type]#[Map<UUID, Integer>]#::
A map of Application Id to the configured time to live (TTL) for the access token (JWT). This can be used to identify the maximum amount of time after this event occurred where an un-expired access token may be held by a user.
+
If you take the [field]#createInstant# of this event and add the number of seconds for a specific application TTL you come up with an instant in time where you should consider all access tokens issued before this time invalid. This is because the access token will have been issued on or before the instant the refresh token was revoked.
+
This map will contain an entry for each application for which the user has a refresh token.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `jwt.refresh-token.revoke`.

[field]#event.userId# [type]#[UUID]#::
The unique Id of the User for which all refresh tokens have been revoked.

[field]#event.user# [type]#[Object]# [since]#Available since 1.8.0#::
The user for which a refresh token has been revoked. See the link:/docs/v1/tech/apis/users/[Users API] for property definitions and example JSON.


[source,json]
.Example Event JSON
----
include::docs/src/json/events/jwt-refresh-token-revoke-all-user.json[]
----

=== All Refresh Tokens for an Application are revoked

This example JSON would reflect a scenario where all refresh tokens issued for a specific application are revoked.

=== Event Body

[.api]
[field]#event.applicationId# [type]#[UUID]#::
The unique Id of the Application for which all of the refresh tokens have been revoked.

[field]#event.applicationTimeToLiveInSeconds# [type]#[Map<UUID, Integer>]#::
A map of Application Id to the configured time to live (TTL) for the access token (JWT). This can be used to identify the maximum amount of time after this event occurred where an un-expired access token may be held by a user.
+
If you take the [field]#createInstant# of this event and add the number of seconds for a specific application TTL you come up with an instant in time where you should consider all access tokens issued before this time invalid. This is because the access token will have been issued on or before the instant the refresh token was revoked.

[field]#event.createInstant# [type]#[Long]#::
The link:/docs/v1/tech/reference/data-types/#instants[instant] that the event was generated.

[field]#event.id# [type]#[UUID]#::
The unique Id of the event. You may receive an event more than once based upon your transaction settings. This Id may be used to identify a duplicate event.

[field]#event.tenantId# [type]#[UUID]# [since]#Available since 1.8.0#::
The unique tenant identifier. This value may not be returned if not applicable.

[field]#event.type# [type]#[String]#::
The event type, this value will always be `jwt.refresh-token.revoke`.


[source,json]
.Example Event JSON
----
include::docs/src/json/events/jwt-refresh-token-revoke-application.json[]
----
