---
layout: doc
title: Upgrades and Patches
description: Learn how to upgrade and patch FusionAuth using our bundles and migration scripts
---

== FusionAuth Updates and Patches

Periodically, FusionAuth releases updates and you might also require a patch if you are running into problems and have contacted FusionAuth Support for assistance. In these cases, you will need to update the application.

To download or check on the latest updates, please visit https://fusionauth.io/downloads[Downloads].

=== Linux (RPM/DEB)

Updating your application is easy if you installed using the RPM or Debian packages. All you need to do is to issue an update command to the dpkg or rpm program and specify the new package file. Here is an example:

[NOTE]
====
Running the update script will shut down the FusionAuth service if they have not yet been stopped The service will need to be restarted after the update is finished.
====

[source,title=Shutdown FusionAuth]
----
sudo service fusionauth-app stop
sudo service fusionauth-search stop
----

[source,shell,title=Upgrade FusionAuth using Debian bundles]
----
sudo dpkg -i fusionauth-search-<version>.deb
sudo dpkg -i fusionauth-app-<version>.deb
----

[source,shell,title=Upgrade FusionAuth using RPM bundles]
----
sudo rpm -U fusionauth-search-<version>.rpm
sudo rpm -U fusionauth-app-<version>.rpm
----

[source,title=Start FusionAuth]
----
sudo service fusionauth-search start
sudo service fusionauth-app start
----

=== Mac and Linux (ZIP)

If you manually installed zips then you will need to delete the existing binaries and libraries to avoid classpath conflicts.

. First stop your app and search processes. The easiest way to do this is to kill their process ids.
. Navigate using terminal to the directory that contains fusionauth.
. It is always recommended to make a backup of your directory and database before continuing.
. Remove the existing app directories. (This won't affect any of your data)

[source,shell]
----
rm -rf fusionauth/fusionauth-app fusionauth/fusionauth-search fusionauth/bin
----

[start=5]
. Unzip your new zips on top of the fusionauth directory. The best way to do this is with a no overwrite flag so that we don't overwrite
 our configuration. `unzip` has a `-n` flag that will do exactly that. We also know that all of the files we wanted to overwrite were already
 deleted so everything we need will still get unzipped.

[source,shell]
----
unzip -nq new-fusionauth-app.zip
unzip -nq new-fusionauth-search.zip
----
(Note: `-q` is to quiet the output)

=== Windows (ZIP)

For this example, we'll assume you have previously installed FusionAuth in `\fusionauth` this will be referred to `FUSIONAUTH_HOME`.

[source,title=Example filesystem layout]
----
\fusionauth\bin
\fusionauth\config
\fusionauth\config\keystore
\fusionauth\config\fusionauth.properties
\fusionauth\fusionauth-app\
\fusionauth\fusionauth-search\
----

[source,title=Shutdown and Uninstall FusionAuth]
----
# Stop Services
net stop FusionAuthApp
net stop FusionAuthSearch

# Uninstall Services
cd \fusionauth\fusionauth-app\apache-tomcat\bin
FusionAuthApp.exe /uninstall
cd \fusionauth\fusionauth-search\elasticsearch\bin
FusionAuthSearch.exe /uninstall

# Delete or move existing installation
cd \fusionauth
move fusionauth-app fusionauth-app-old
move fusionauth-search fusionauth-search-old
----

Extract the new zips and place in `FUSIONAUTH_HOME`.

[source,title=Install and Start FusionAuth]
----
# Install Windows Services
cd \fusionauth\fusionauth-app\apache-tomcat\bin
FusionAuthApp.exe /install
cd \fusionauth\fusionauth-search\elasticsearch\bin
FusionAuthSearch.exe /install

# Startup Services
net start FusionAuthSearch
net start FusionAuthApp
----

=== Database

[NOTE]
====
In most cases, you will not need to upgrade you database manually using the information below. FusionAuth ships with a system called Maintenance
 Mode. When you restart FusionAuth after installing a new bundle using the steps above, FusionAuth will automatically upgrade your database.

You should always backup your database prior to using Maintenance Mode.
====

Depending on your current version and the new version you will be updating to you might need to execute one or more SQL scripts to update your
 database. These scripts are located in the migrations folder inside the Database Schema ZIP file. This file can be downloaded by logging into your account at fusionauth.io.

[WARNING]
====
When upgrading your database from a previous version, be sure to only run the scripts located in the `migrations` folder, the base files
 `mysql.sql` and `postgresql.sql` should only be used during a clean installation when no database schema is present.
====

Inside of the database schema zip file, you will find the following FusionAuth migrations, run in this order, starting with the first migration that is
greater than the version you are coming from, and ending with the version that is less than or equal to the target version.

[source]
----
fusionauth-database-schema
  |
  migrations
    |
    mysql | postgresql
      |
      |- 1.1.0.sql
----