@startuml
  !include ../../_config.plantuml

actor "Users" as u
agent "Load Balancer" as lb

rectangle "Blue Deployment (old version)" as f1 {
   [Node 1]#lightblue
   [Node 2]#lightblue
   [Node 3]#blue;text:white
}

rectangle "Green Deployment (new version)" as f2 {
   [Node #1]#lightgreen
   [Node #2]#lightgreen
   [Node #3]#lightgreen
}

u -> lb
lb -> f1
lb ..> f2 : Switch traffic when ready
@enduml
