@startuml
  !include ../../_config.plantuml

participant "User Agent" as u
participant "Proxy" as p
participant "FusionAuth" as f

u -> p : Request
p -> f : Request 
f -> p : Send page
p -> u : Send page

@enduml
