@startuml
  !include ../../_config.plantuml

actor "Users" as u
agent "Load Balancer" as lb
component "Node 1" as n1 #lightgreen
component "Node 2" as n2 #lightblue
component "Node 3" as n3 #lightblue

u -> lb
lb ..> n1 : Switch traffic when ready \n (Upgrade one node at a time)
lb --> n2
lb -> n3
@enduml
