@startuml
  !include ../../_config.plantuml

participant "User Agent" as u
participant "Proxy 1" as p1
participant "Proxy 2" as p2
participant "FusionAuth" as f

u -> p1  : Request
p1 -> p2 : Request 
p2 -> f  : Request 
f -> p2  : Send page
p2 -> p1 : Send page
p1 -> u  : Send page

@enduml
