name: bluehawk check

on:
  pull_request:
    paths:
      - 'astro/src/code-snippets/**'

jobs:
  check:
    name: Validate Bluehawk annotations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: '22'

      - name: Check Bluehawk tags
        run: npx bluehawk check -i "*.md" -i "package*.json" -i "*.lock" -i "node_modules" astro/src/code-snippets
