name: check-closed-github-issues

on:
  schedule:
    - cron: '31 18 * * *'
  workflow_dispatch:

jobs:
  check_closed_github_issues:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check for closed issues referenced in documentation
        run: src/scripts/check-for-closed-github-issues-in-docs.sh -v
        shell: bash
