name: Check that API docs match released client libraries

on:
  schedule:
    - cron: '31 18 * * *'
  workflow_dispatch:

jobs:
  check_apis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Check APIs for completeness against client libs
        run: |
          # check out last released version of the client libs
          tagver=`curl --silent https://account.fusionauth.io/api/version -o - | jq 'last(.versions[-1])'|sed 's/"//g'`
          if ! git ls-remote --exit-code --heads https://github.com/fusionauth/fusionauth-client-builder "$tagver" > /dev/null 2>&1; then
            tagver=$(echo "$tagver" | sed 's/\.[0-9]*$/.0/')
          fi
          git clone --depth 1 --branch $tagver https://github.com/fusionauth/fusionauth-client-builder
          src/check-apis-against-client-json.rb -f $PWD/src/.checkapis.yaml -c $PWD/fusionauth-client-builder -v
        shell: bash
