name: check-closed-github-issues

on:
  schedule:
    - cron: '31 18 * * *'
  workflow_dispatch:

jobs:
  check_closed_github_issues:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Check for closed issues referenced in documentation
        run: src/scripts/check-for-closed-github-issues-in-docs.sh
        shell: bash
