name: check-content
on: 
  pull_request:
  workflow_dispatch:

jobs:
  check_content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Check for blog posts that have incorrect categories
        run: |
          exit `src/scripts/check-for-incorrect-categories.sh`
        shell: bash
      - name: No absolute URLs referencing FusionAuth.io
        run: |
          exit `src/scripts/check-for-absolute-urls.sh`
        shell: bash
      - name: Check for erroneous markdown references
        run: |
          exit `src/scripts/check-for-incorrect-markdown-references.sh`
        shell: bash
      - name: check for APIFields with no name
        run: |
          exit `src/scripts/check-for-api-fields-no-name.sh`
        shell: bash
