name: check-json
on: 
  pull_request:
    paths:
      - 'astro/src/content/json/**.json'
      - '.github/workflows/jsoncheck.yml'
      - 'scripts/check_json.sh'
  workflow_dispatch:

jobs:
  check_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Check for broken json files
        run: ./src/scripts/check-json.sh
        shell: bash