name: check_closed_github_issues

# this checks to see what issues are closed in GH but still in our doc. 
# we should update doc to reflect closed issues

# Controls when the action will run. 
on:
  # Triggers the workflow once a day
  schedule:
    - cron: '31 18 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_closed_github_issues:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Check for closed issues referenced in documentation
        run: |
          # check docs for references to closed issues
          count=`src/scripts/check-for-closed-github-issues-in-docs.sh`
          exit $count
        shell: bash
