name: test code snippets

on:
  pull_request:
    paths:
      - 'astro/src/code-snippets/**'
  workflow_dispatch:

jobs:
  webauthn:
    name: WebAuthn utility functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: astro/src/code-snippets/webauthn
        run: npm install

      - name: Run Jest tests
        working-directory: astro/src/code-snippets/webauthn
        run: npm test

