# Prints out a list of all content in our site to be pulled into other workflows
name: content_list
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  content_list:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Find paths and titles of all content
        run: |
          find astro/src/content -type f|grep -v '/_' |xargs grep '^title:'|sed 's/:title: /,"/'|sed 's/$/"/'| sed 's!astro/src/content!!' |sed 's!/quickstarts!/docs/quickstarts!'|sed 's!/!https://fusionauth.io/!'
        shell: bash
