---
name: dev-publish-redirect-rules
env:
  BUCKET_NAME: "fusionauth-dev-us-east-1-artifacts"
  PUBLISHER_ROLE_ARN: "${{ secrets.DEV_PUBLISHER_ROLE_ARN }}"
  AWS_REGION: "us-east-1"

on:
  workflow_dispatch:
    inputs:
        branch:
          required: true
          type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          sparse-checkout: src/redirects.json

      - name: validate json
        run: cat src/redirects.json | jq empty

      - name: validate all redirects start with a `/`
        run: exit $(cat src/redirects.json| jq '.redirects|to_entries | map(select(.key | startswith("/") | not)) | length')
        shell: bash

      - name: validate all indexPaths start with a `/`
        run: exit $(cat src/redirects.json| jq '.indexPaths|to_entries | map(select(.key | startswith("/") | not)) | length')
        shell: bash

      - name: set aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ env.PUBLISHER_ROLE_ARN }}
          role-session-name: site_publisher_session
          aws-region: ${{ env.AWS_REGION }}

      - name: upload file to s3
        run: aws s3 cp src/redirects.json s3://${{ env.BUCKET_NAME }}/lambda/site-origin-request-handler/redirects.json
