# Checks example apps with the list of repos we have in GH to make sure we aren't missing any
name: example_app_check
on: 
  pull_request:
    paths:
      - 'astro/src/content/json/exampleapps.json'
      - 'astro/src/content/quickstarts/**'
      - '.github/workflows/exampleappcheck.yml'
      - '.github/scripts/count-repos.sh'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_json:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Check for example app completeness
        run: exit `sh .github/scripts/count-repos.sh`
        shell: bash
