name: example_app_check

on: 
  pull_request:
    paths:
      - '.github/scripts/count-repos.sh'
      - '.github/workflows/exampleappcheck.yml'
      - 'astro/src/content/json/exampleapps.json'
      - 'astro/src/content/quickstarts/**'
  workflow_dispatch:

jobs:
  check_example_apps:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for example app completeness
        run: .github/scripts/count-repos.sh
