name: (prod) invalidate_cache

on:
  schedule:
    - cron: '31 1,13 * * *'
  workflow_dispatch:

jobs:
  invalidate_cache:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-2
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set prod env vars based on branch
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ${GITHUB_ENV}
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ${GITHUB_ENV}
        shell: bash
      - name: Invalidate cache
        run: |
          CLOUDFRONT_DISTRIBUTION_ID=$(grep cloudfront_distribution_id s3_website.yml|awk -F: '{print $2}' |sed 's/ //g')
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        shell: bash
