name: check_apis

# Controls when the action will run. 
on:
  # Triggers the workflow once a day
  schedule:
    - cron: '31 18 * * *'
  # don't run on every push
  #push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_apis:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: octokit/request-action@v2.x
        id: get_issue_status
        with:
          route: GET /repos/{owner}/{repo}/issues/{issue_number}
          owner: fusionauth
          repo: fusionauth-issues
          issue_number: issue_number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo issue status: ${{ steps.get_issue_status.outputs.data.state }}"
#https://github.com/octokit/request-action
      - name: Check for issues in docs.
        run: |
          egrep -Ri 'github.com/fusionauth/fusionauth-issues/issues/[0-9]+' docs |grep -v release-notes |sed 's!.*issues/!!'| sed 's/\[.*//'|sed 's![^0-9]!!g'|sort -u > list.issues
          
        shell: bash
