# Checks json request objects with jq to make sure they are valid
name: json_check
on: 
  pull_request:
  # run once a day
  schedule:
    - cron: '31 21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_json:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Check for broken json files
        run: |
          busted_files=""        
          for file in `find site/docs/src -name "*.json"`; do
            cat $file |jq -j '.' >/dev/null
            if [ "x$?" != "x0" ]; then
              busted_files="$busted_files $file"
            fi
          done
          if [ "x$busted_files" != "x" ] ; then
            echo "Busted json files"
            echo $busted_files
            exit 1
          fi
        shell: bash
