# Checks json request objects with jq to make sure they are valid
name: json_check
on: 
  # run once a day
  schedule:
    - cron: '31 21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_json:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Check jq
        run: |
          jq --version
        shell: bash
      # invert the results of the find command. If we find anything, we want to fail. Otherwise succeed.
      # more here: https://stackoverflow.com/questions/367069/how-can-i-negate-the-return-value-of-a-process
      #- name: Check for broken internal asciidoctor links in output
        #run: |
          #! find _site/docs -type f|xargs grep -l 'BROKEN LINK'
        #shell: bash
      #- name: Check for broken external asciidoctor links in source
        #run: |
          #! find site/docs -type f -name "*.adoc"|xargs egrep '^/docs/v1/|[^:]/docs/v1/'|grep -v RSS
          ## ignore lines including the word RSS since those have an href, not a link:
        #shell: bash
