# Runs the linter on the changed files in the PR
name: Run ESLint on changed files, Build the site, and check APIs for completeness
env:
    BASE_REF: origin/${{ github.base_ref }}
on:
  pull_request:
  workflow_dispatch:

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0 # need all branches
    
      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: '22'

      - name: NPM Install
        run: |
          cd astro
          npm ci
        shell: bash

      - name: ESLint
        run: |
          cd astro
          npm run lint-pr
        shell: /usr/bin/bash -e -o pipefail {0}

      - name: Run a dev build
        run: |
          cd astro
          NODE_OPTIONS=--max_old_space_size=8192 npm run dev-build
        shell: /usr/bin/bash -e -o pipefail {0}

      - name: Check APIs for completeness against client libs
        run: |
          tagver=`curl --silent https://account.fusionauth.io/api/version -o - | jq 'last(.versions[-1])'|sed 's/"//g'`
          git clone --depth 1 --branch $tagver https://github.com/fusionauth/fusionauth-client-builder
          src/check-apis-against-client-json.rb -f $PWD/src/.checkapis.yaml -c $PWD/fusionauth-client-builder -v --pr
        shell: bash
