# Runs the linter on the changed files in the PR
name: Run ESLint on changed files
on:
  pull_request:
  workflow_dispatch:

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

        # I want to lint only the files that have changed in the PR
        # This is a bit tricky because we need to fetch the main branch to compare against
        # Instead I am using the GitHub cli to fetch the changes in the PR
      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Set Pull Request Number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: NPM Install
        run: |
          cd astro
          npm ci
        shell: bash

      - name: ESLint
        run: |
          cd astro
          npm run lint-pr
        shell: /usr/bin/bash -e -o pipefail {0}

      # Might as well
      - name: Run a dev build
        run: |
          cd astro
          npm run dev-build
        shell: /usr/bin/bash -e -o pipefail {0}

      - name: Check APIs for completeness against client libs
        # Only run if the API docs change. Not technically "lint" but it's a good place for it.
        if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.modified, 'astro/src/content/docs/apis/') || contains(github.event.head_commit.modified, '.github/workflows/apicheck.yml')) }}
        run: |
          tagver=`curl --silent https://account.fusionauth.io/api/version -o - | jq 'last(.versions[-1])'|sed 's/"//g'`
          git clone --depth 1 --branch $tagver https://github.com/fusionauth/fusionauth-client-builder
          src/check-apis-against-client-json.rb -f $PWD/src/.checkapis.yaml -c $PWD/fusionauth-client-builder -v --pr
        shell: bash