name: Update email and message templates

on:
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Check email and message templates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - run: src/scripts/update-templates.sh all
