name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: errata-ai/vale-action@2690bc95f0ed3cb5220492575af09c51b04fbea9 # reviewdog
        with:
          files: '["astro/src/components","astro/src/content"]'
          fail_on_error: true
