---
layout: passport-doc
title: Upgrades and Patches
description: Learn how to upgrade and patch Passport using our bundles and migration scripts
---

== Passport Updates and Patches

Periodically, Inversoft releases updates for the Passport. You might also require a patch if you are running into problems and have contacted Inversoft Support for assistance. In these cases, you will need to update the application.

To download or check on the latest updates, please visit your https://www.inversoft.com/account/[Inversoft Account] and find the Download link for your license.

=== Linux

Updating your application is easy if you installed using the RPM or Debian packages. All you need to do is to issue an update command to the dpkg or rpm program and specify the new package file. Here is an example:

[NOTE]
====
Running the update script will shut down the Passport service if they have not yet been stopped The service will need to be restarted after the update is finished.
====

[source,shell,title=Shutdown Passport]
----
$ sudo service passport-backend stop
$ sudo service passport-search-engine stop
----

[source,shell,title=Upgrade Passport]
----
# Using dpkg on a Debian based system
$ sudo dpkg -i passport-search-engine-<version>.deb
$ sudo dpkg -i passport-backend-<version>.deb

# Using rpm on a Red Hat based system
$ sudo rpm -U passport-search-engine-<version>.rpm
$ sudo rpm -U passport-backend-<version>.rpm
----

[source,shell,title=Start Passport]
----
$ sudo service passport-search-engine start
$ sudo service passport-backend start
----

=== Windows

For this example, we'll assume you have previously installed Passport in `C:\inversoft`. this will be referred to `PASSPORT_HOME`.

[source,shell,title=Example filesystem layout]
----
C:\inversoft\config
C:\inversoft\config\keystore
C:\inversoft\config\passport.properties
C:\inversoft\passport-backend\
C:\inversoft\passport-search-engine\
----

[source,shell,title=Shutdown and Uninstall Passport]
----
# Stop Services
C:\> net stop PassportBackend
C:\> net stop PassportSearchEngine

# Uninstall Services
C:\inversoft\passport-backend\apache-tomcat\bin>PassportBackend.exe /uninstall
C:\inversoft\passport-search-engine\elasticsearch\bin>PassportSearchEngine.exe /uninstall

# Delete or move existing installation
C:\inversoft> move passport-backend passport-backend-old
C:\inversoft> move passport-search-engine passport-search-engine-old
----

Extract the new zips and place in `PASSPORT_HOME`.

[source,shell,title=Install and Start Passport]
----
# Install Windows Services
C:\inversoft\passport-backend\apache-tomcat\bin>PassportBackend.exe /install
C:\inversoft\passport-search-engine\elasticsearch\bin>PassportSearchEngine.exe /install

# Startup Services
C:\> net start PassportSearchEngine
C:\> net start PassportBackend
----

=== Database

[NOTE]
====
In most cases, you will not need to upgrade you database manually using the information below. Passport ships with a system called Maintenance
 Mode. When you restart Passport after installing a new bundle using the steps above, Passport will automatically upgrade your database.

You should always backup your database prior to using Maintenance Mode.
====

Depending on your current version and the new version you will be updating to you might need to execute one or more SQL scripts to update your
 database. These scripts are located in the migrations folder inside the Database Schema ZIP file. This file can be downloaded by logging into your account at www.inversoft.com.

[WARNING]
====
When upgrading your database from a previous version, be sure to only run the scripts located in the `migrations` folder, the base files
 `mysql.sql` and `postgresql.sql` should only be used during a clean installation when no database schema is present.
====

Inside of the database schema zip file, you will find the following Passport migrations, run in this order, starting with the first migration that is
greater than the version you are coming from, and ending with the version that is less than or equal to the target version.

[source]
----
passport-database-schema
  |
  migrations
    |
    mysql | postgresql
      |
      |- 1.1.0.sql
      |- 1.3.0.sql
      |- 1.4.0.sql
      |- 1.5.0.sql
      |- 1.6.0.sql
      |- 1.6.1.sql
      |- 1.6.2.sql
      |- 1.7.0.sql
      |- 1.8.0.sql
      |- 1.9.0.sql
      |- 1.10.0.sql
      |- 1.11.0.sql
      |- 1.13.0.sql
      |- 1.13.2.sql
      |- 1.14.0.sql
      |- 1.16.0.sql
      |- 1.17.0.sql
      |- 1.19.0.sql
      |- 1.20.0.sql
      |- 1.21.0.sql
      |- 1.21.3.sql
      |- 1.22.0.sql
----